### ISSUE TITLE
Ssh jump host support

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#1014]

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1424

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1557

**Comment by abdalmoez** [comment]
Is there anyone working on this feature? If there is no one, can i take the initiative to do it?

**Comment by zxdong262** [comment]
@abdalmoez You are very welcome to do it!

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1567

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1782
