### ISSUE TITLE
the menu bar (minimize, maximize, close) is not easy to use

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1026]
## Electerm version:
25.61
## Operating system(linux, macos, or windows7/8/10?):
Windows
## Current Behavior

When wanting to minimize, maximize or close electerm it is necessary that the mouse pointer is on the LINE of the image, if the pointer is not on the line, the action to be performed does not work

As you can see in the image, I will lock the icon but it will not be marked blue and if I click it it does not work, that is, I have to position the pointer over the line of the image.

![imagen](https://user-images.githubusercontent.com/28075454/50297371-a42cc800-044a-11e9-835d-21c8c4db4d45.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Right!

**Comment by saulperez2905** [comment]
Hello, I have not been able to perform the action yet.

 



 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: jueves, 20 de diciembre de 2018 21:04
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [electerm/electerm] the menu bar (minimize, maximize, close) is not easy to use (#1026)

 

Closed #1026 <https://github.com/electerm/electerm/issues/1026>  via  <https://github.com/electerm/electerm/commit/09a3a5435ebe898ea1f8864ab73eddfb53bb4274> 09a3a54.

**Comment by zxdong262** [comment]
@saulperez2905 Hi, so you tried 0.25.65? windows 10?

**Comment by saulperez2905** [comment]
Yes

 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: sábado, 22 de diciembre de 2018 12:35
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] the menu bar (minimize, maximize, close) is not easy to use (#1026)

 

@saulperez2905 <https://github.com/saulperez2905>  Hi, so you tried 0.25.65? windows 10?
