### ISSUE TITLE
when editing bookmark, it is rearranged

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1030]
## Electerm version:
25.65
## Operating system(linux, macos, or windows7/8/10?):
Windows
## Expected Behavior

The bookmarks should not change the order
## Current Behavior

The bookmarks should not change the order
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

when a bookmark is edited it is reordered and becomes the first in the row of bookmarks. I understand that this should not happen to stay where it was

**Comment by zxdong262** [comment]
@saulperez2905 Not sure yet, but I will check this.

**Comment by saulperez2905** [comment]
Hi, zxdong262.
About this case, in the current version 26.71 when a bookmark is modified it is reordered. I have also noticed that now bookmarks can not be moved from position.

![imagen](https://user-images.githubusercontent.com/28075454/55264023-0151ca00-5241-11e9-8361-f53e8f5361eb.png)

**Comment by x0rsw1tch** [comment]
Came here to mention the same thing. Unable to rearrange bookmarks manually at all (win10 x64).
