### ISSUE TITLE
X11 is enabled by default

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1031]
## Electerm version:
25.65
## Operating system(linux, macos, or windows7/8/10?):
windows 10
## Expected Behavior

should be disabled for new connections
## Current Behavior

It is enabled and if the computer I want to connect to does not have X11, when trying to connect it fails.
## Possible Solution

that by default is disabled, if you need it, you can enable
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

![imagen](https://user-images.githubusercontent.com/28075454/50407902-bd1cdc80-07ae-11e9-8dfa-e264738d21c9.png)

**Comment by zxdong262** [comment]
@saulperez2905 Thank you for the feedback. Released a new version with fix.
