### ISSUE TITLE
electerm can't work with lrzsz?

### ISSUE THREAD

**Issue by helyho** [electerm/electerm#1033]
## Expected Behavior

**Comment by helyho** [comment]
lrzsz is a portable and fast implementation of the X/Y/Zmodem protocols.
lrzsz is a tool  what we can use it to transfer file between server and client
if you os ubuntu , you can install it like : apt install lrzsz
thanks

**Comment by zxdong262** [comment]
@helyho How is not working in electerm, so you run lrzsz in electerm, it does not work, but in other terminal, running lrzsz command works?

**Comment by helyho** [comment]
yes , i use secureCRT or iterm2 it can be work fine

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1174

**Comment by zxdong262** [comment]
Released new version with Zmodem support. 
https://github.com/electerm/electerm/releases/tag/v0.26.67

**Comment by helyho** [comment]
> Released new version with Zmodem support.
> https://github.com/electerm/electerm/releases/tag/v0.26.67

thanks for you support, buddy~
