### ISSUE TITLE
Page Up / Page Down not working

### ISSUE THREAD

**Issue by x0rsw1tch** [electerm/electerm#1049]
## Electerm version: 

0.26.2

## Operating system(linux, macos, or windows7/8/10?):

Windows 10

## Expected Behavior

When pressing Page Up / Page Down in programs like _less_ or _midnight commander_, the view scroll up or down a full page.

## Current Behavior

Pressing Page Up / Page Down, nothing happens

## Steps to Reproduce

1. cat a long text file and pipe it to less
2. Press Page Up or Page Down
3. Nothing Happens

This works in PuTTY and MobaXTerm

## Context (Environment)

Trying to quickly go through log files or long file lists has been cumbersome.

## Detailed Description

Allow Page Up and Page Down to work as intended.

**Comment by zxdong262** [comment]
shift + pagedown/up works
