### ISSUE TITLE
shell color error

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#1052]
## Electerm version:
26.2
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior

shell have color 
![Screenshot_1.png](https://i.loli.net/2018/12/29/5c2788d847846.png)
## Current Behavior

error color show
![Screenshot_2.png](https://i.loli.net/2018/12/29/5c278903c75d7.png)

## Steps to Reproduce

1.use new ui..
2.use have color shell. like fish 
3.
4.

**Comment by zxdong262** [comment]
Hi @blue-bird1 Can you share more detail about how to reproduce this?

**Comment by blue-bird1** [comment]
https://github.com/electerm/electerm/commit/68c2168d2e7593328a2a6ea82f8defdc4357b759  start  error occurred

**Comment by blue-bird1** [comment]
```

**Comment by zxdong262** [comment]
You can turn x11 off from bookmark edit->x11, can you try this?

**Comment by blue-bird1** [comment]
> You can turn x11 off from bookmark edit->x11, can you try this?

in 26.2 try open and close x11, but no effect. What happened in this commit?

**Comment by blue-bird1** [comment]
> @blue-bird1 Tested x11 on/off, works fine for 26.2
> 
> > ```
> > /app/lib/terminal.js
> > @@ -62,6 +63,7 @@ class Terminal {
> >            'host',
> >            'port',
> >            'username',
> > +            // 'x11',
> >            'password',
> >            'privateKey',
> >            'passphrase'
> > 
> >              conn.shell(
> > -              _.pick(initOptions, ['rows', 'cols', 'term']),
> > +              _.pick(initOptions, [
> > +                  'rows', 'cols', 'term',// 'x11'
> > +              ]),
> > ```
> > will work
> 
> This is old code, in 0.26.2, x11 disabled by default, but for old bookmarks, it might be opened, by previous electerm. Can you confirm x11 switch not working? like try run `xeyes` to check.

oh.. I will try , Is the new version the problem? ..

**Comment by blue-bird1** [comment]
> I not have env debug electerm.. @zxdong262 `typeof d.x11 == 'boolean'`?. if is true. (ssh2 code)[https://github.com/electerm/ssh2/blob/fdd1a18b70cc5c3f62aa9abf2fc048a87ca0a37b/lib/client.js#L793]
> 
> ```
>  if (wndopts && (wndopts.x11 !== undefined || wndopts.env !== undefined)) {
>     opts = wndopts;
>     wndopts = undefined;
>   }
> ```
> `undefined !== false`
> 
> ```
>  if (wndopts !== false)
>       todo.push(function() { reqPty(chan, wndopts, reqCb); });
> ```
> will get `undefined `
> 
> if I change ` todo.push(function() { reqPty(chan, wndopts, reqCb); });` to ` todo.push(function() { reqPty(chan, opts, reqCb); });` , will fix bug

The new version should also be the problem

**Comment by blue-bird1** [comment]
If your ssh2 library is only used by this client, just change this parameter like me or add extra `x11  === true`

**Comment by zxdong262** [comment]
@blue-bird1 Thank you! I will fix this.

**Comment by zxdong262** [comment]
@blue-bird1 Released new version, I think it would fix. Let me how it works.

**Comment by blue-bird1** [comment]
Didn't get fixed.

**Comment by blue-bird1** [comment]
```
if (initOptions.x11 !== false) {
        x11 = {
          cookie: x11Cookie
        }
      }
```
is `initOptions.x11`  `undefined;?
