### ISSUE TITLE
It does not work on macos.

### ISSUE THREAD

**Issue by fwk1010** [electerm/electerm#1053]
## Electerm version:
0.26.2
## Operating system(linux, macos, or windows7/8/10?):
macos 10.14.1
## Expected Behavior

use as ssh client
## Current Behavior

white screen and then had not thing
## Possible Solution

os compatibility？
## Steps to Reproduce

1.down and install app
2.open app
3.
4.

## Detailed Description

Screenshot 
<img width="1430" alt="2018-12-30 12 02 01" src="https://user-images.githubusercontent.com/10340097/50544285-532b8980-0c2b-11e9-8d23-4314fd2c465c.png">

**Comment by zxdong262** [comment]
Hi @fwk1010 

In my mac, it works fine, Can you try close electerm, and run this:
`rm -rf ~/Library/Application Support/electerm*`, then open electerm again?

**Comment by fwk1010** [comment]
@zxdong262 The same.It would have some logs to make this problem clearly？And I also try the previous version，but it was not work too.
Well，I try to make a new ssh by the menu bar but it said:
**Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at click (/Applications/electerm.app/Contents/Resources/app.asar/lib/menu.js:29:31)
    at MenuItem.click (/Applications/electerm.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/electerm.app/Contents/Resources/electron.asar/browser/api/menu.js:30:13)**

Thanks.

**Comment by zxdong262** [comment]
@fwk1010 Can you try
```
cd /Applications/electerm.app/Contents/MacOS/
./electerm
```

then terminal can show some error message.

**Comment by fwk1010** [comment]
@zxdong262  
There were log details:
```
error parsing $HOME/.ssh/config
maybe no $HOME/.ssh/config, but it is ok
[20:44:18.495] [info] App starting...
no /Users/mymac/Library/Application Support/electerm-config.js but it is ok
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
Emitted 'error' event at:
    at Server.emit (events.js:182:13)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1489:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:17)
```

**Comment by fwk1010** [comment]
It works.Because I used the [SwitchHosts](https://github.com/oldj/SwitchHosts) and it made my hosts be not thing.
Thank you very much.:smile:
