### ISSUE TITLE
line where commands are entered into the console is very low

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1056]
## Electerm version:
26.10
## Operating system(linux, macos, or windows7/8/10?):
windows 10
## Expected Behavior

The line where the text / command is entered should not be so low. It reaches the point of not observing some special characters "_"

![imagen](https://user-images.githubusercontent.com/28075454/50569928-52394b80-0d42-11e9-80f7-d5b5d17f38f7.png)

## Current Behavior

![imagen](https://user-images.githubusercontent.com/28075454/50569916-b7407180-0d41-11e9-8b1f-35b12de7b2ab.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Confirmed, you can turn off taskbar setting->use small icon to avoid this. I will fix it too.
