### ISSUE TITLE
the menu bar (minimize, maximize, close) is not easy to use (#1026)

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1057]
## Electerm version:
26.10
## Operating system(linux, macos, or windows7/8/10?):
windows 10
## Expected Behavior

With only positioning in the box of the icon, when clicking, the operation should work (maximize, minimize or close).
## Current Behavior

When wanting to minimize, maximize or close electerm it is necessary that the mouse pointer is on the LINE of the image, if the pointer is not on the line, the action to be performed does not work.

As you can see in the image, I will lock the icon but it will not be marked blue and if I click it it does not work, that is, I have to position the pointer over the line of the image.
## Steps to Reproduce
![imagen](https://user-images.githubusercontent.com/28075454/50569989-b578ad00-0d45-11e9-9d54-f111488e5c62.png)
![imagen](https://user-images.githubusercontent.com/28075454/50569990-c0cbd880-0d45-11e9-9df4-c5da3aa26616.png)
![imagen](https://user-images.githubusercontent.com/28075454/50569992-cb866d80-0d45-11e9-8614-2b742df837fc.png)

**Comment by zxdong262** [comment]
@saulperez2905 Hi, released new version, thank you for the feedback!
