### ISSUE TITLE
How about auto focus

### ISSUE THREAD

**Issue by inkroom** [electerm/electerm#1060]
## Operating system(linux, macos, or windows7/8/10?):linux

I hope that when Electerm get focus, the ssh could get focus to type command at any time

**Comment by zxdong262** [comment]
@inkroom Right, will be done.

**Comment by zxdong262** [comment]
@inkroom I checked, when switch to electerm, should be ready to type, will not lose terminal focus, unless you click somewhere in electerm to lose focus already. So what is your situation, how to reproduce it?

**Comment by inkroom** [comment]
> @inkroom I checked, when switch to electerm, should be ready to type, will not lose terminal focus, unless you click somewhere in electerm to lose focus already. So what is your situation, how to reproduce it?

I found it, I click other component before. But I still think  the terminal should get focus when switch to electerm  whether it has focus.

And I fount that the ssh component will lose focus when close a dialog such as confirm password

**Comment by zxdong262** [comment]
@inkroom Right!
