### ISSUE TITLE
sftp error

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#1062]
## Electerm version:
26.10
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior

sftp available
## Current Behavior

Will be wrong when the terminal is open
## Possible Solution

Just need to restart because this is due to unexpected behavior
## Steps to Reproduce

1.open a ssh. wait it timeout error
2.open sftp, unavailable
3.reload
4.Sftp is still unavailable

## Detailed Description

When opening a timeout terminal sftp will cause `WebSocket is already in CLOSING or CLOSED state`.
If reload now,` componentWillUnmount` that will trigger the sftp component.  will cause `WebSocket is already in CLOSING or CLOSED state`.
in new terminal `this.initData()`.->`this.localList()`  will cause `WebSocket is already in CLOSING or CLOSED state`.  
Should be accidentally reused for closed websocket

**Comment by zxdong262** [comment]
Should be fixed now, feel free to reopen it if you still experience this.

**Comment by blue-bird1** [comment]
in 0.27.12 Still have this problem.
 `electerm.0.27.12-465b468a449339cf6565e53f1b2c446ae6c7bf33.js:16 WebSocket is already in CLOSING or CLOSED state.
Vo.r.s @ electerm.0.27.12-465b468a449339cf6565e53f1b2c446ae6c7bf33.js:16`

**Comment by zxdong262** [comment]
@blue-bird1 How about now?

**Comment by blue-bird1** [comment]
It looks like it’s ok.
