### ISSUE TITLE
Build for snap

### ISSUE THREAD

**Issue by petrukngantuk** [electerm/electerm#1063]
## Operating system(linux, macos, or windows7/8/10?):
linux ubuntu 1804

## Expected Behavior
I want to build to snap app,

## Current Behavior
cannot build to snap app

## Possible Solution
Edit `package.json` to enable build for snap

## Context (Environment)
I want to build it to snappy package .snap

## Detailed Description
I'm using your code + add a line in `scripts` on `package.json` with:
`"snap":"./node_modules/.bin/electron-builder --linux snap"` but it's return error

I want to research it, but I think your code for me is extreme custom in compile/build the source code

## Suggestions?
I just can provide this link to you :
[https://docs.snapcraft.io/electron-apps/6748?_ga=2.63732780.2073004274.1546627457-563229706.1546455503](url)

**Comment by zxdong262** [comment]
@petrukngantuk Sure, I will check this.

**Comment by petrukngantuk** [comment]
> @petrukngantuk Sure, I will check this.

thanks bro...

**Comment by zxdong262** [comment]
@petrukngantuk Hi,

I do not know what is going on, I never used snap yet, but I will try. I will let you know when updated.

**Comment by zxdong262** [comment]
Hi @petrukngantuk, the newest release already included snap, you can try it.

**Comment by zxdong262** [comment]
Hi @petrukngantuk, I am just wondering why you prefer snap, seems the pack is much bigger than other release types, more than twice the size of `.dep` package.

**Comment by petrukngantuk** [comment]
> Hi @petrukngantuk, I am just wondering why you prefer snap, seems the pack is much bigger than other release types, more than twice the size of `.dep` package.

I want to integrate it to another app, snap it's like container(docker)
