### ISSUE TITLE
本机终端如何使用socks5 proxy

### ISSUE THREAD

**Issue by jay763190097** [electerm/electerm#1064]
Linux系统下默认打开就是终端。可以添加ssh连接，并且ssh可以设置socks5 proxy。
但是本机如何使用呢？

**Comment by zxdong262** [comment]
Try this: https://github.com/rofl0r/proxychains-ng

**Comment by jay763190097** [comment]
@zxdong262 怎么使用？能否给点文字说明

**Comment by zxdong262** [comment]
> @zxdong262 怎么使用呢？能否给点教程。我现在的问题不是科学上网，而是只让终端可以科学上网，这样我git clone就快很多了 

Read proxychains-ng readme.
