### ISSUE TITLE
Very slow file transfer

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1065]
## Electerm version:
26.12
## Operating system(linux, macos, or windows7/8/10?):
Windows 10
## Expected Behavior

You should transfer the files with the same speed as other applications

## Current Behavior

it takes more than twice as long as another application, for example WInSCP

## Steps to Reproduce
********************************************using winscp
transfer a file takes about 5 minutes, maybe 5 minutes with 30 seconds.

![imagen](https://user-images.githubusercontent.com/28075454/50914640-fedf9100-1404-11e9-8ce5-f00834d06cb3.png)

********************************************using electerm
When I try to transfer the same file using sft from electerm, in 10 minutes it gets to transfer only 55%

![imagen](https://user-images.githubusercontent.com/28075454/50914860-87f6c800-1405-11e9-9ded-f69d49e640f0.png)

past 10 min
![imagen](https://user-images.githubusercontent.com/28075454/50914951-c12f3800-1405-11e9-88d9-8ecca4f653b6.png)

## Context (Environment)
transfer files from unix to Windows.
For the comparison I see use the same network at the time (time)

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1202

**Comment by zxdong262** [comment]
should follow fastGet's path to do fast transfer: https://github.com/mscdex/ssh2-streams/blob/master/lib/sftp.js

**Comment by zxdong262** [comment]
Now it use fast download by default! @saulperez2905
