### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1066]
## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?

Regarding the transfer of files. I suggest that it could or would be very helpful to have the details of the time elapsed and the time it will take the transfer.

Similar to:

![imagen](https://user-images.githubusercontent.com/28075454/50915302-7f52c180-1406-11e9-832a-b9dc39c995f8.png)

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/5fc202064cdadbeeb697c5973a989c4d6ca342fe

Added time left to transfer list, already released.
