### ISSUE TITLE
The file transfer closed all my connections.

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1067]
## Electerm version:
26.12
## Operating system(linux, macos, or windows7/8/10?):
Windows 10
## Expected Behavior

Make the transfer in a normal way and do not close any connections.

## Current Behavior

All open connections closed and shows error when closing electerm

## Steps to Reproduce
try to transfer several files from AIX to Windows (12 in total), at the moment you paste the files all the other connections you had open were closed. Also, the percentage of transfer did not have any progress. 

![imagen](https://user-images.githubusercontent.com/28075454/50915897-c4c3be80-1407-11e9-810f-aa438b768c0f.png)

Finally, when I close electerm I throw the following message

![imagen](https://user-images.githubusercontent.com/28075454/50915862-ac53a400-1407-11e9-9569-e4c532a24cf2.png)

**Comment by zxdong262** [comment]
Hi @saulperez2905 Does this still happen?

**Comment by zxdong262** [comment]
Should be fixed now, feel free to reopen it if it still happens.
