### ISSUE TITLE
What is the function of the red circle?

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1069]
## Electerm version:
26.12
## Operating system(linux, macos, or windows7/8/10?):
Windows 10
## Expected Behavior

Disconnect from the session
## Current Behavior

continues to work normally
## Steps to Reproduce

for some reason the circle turns from green to red, I understand that if it turns red it is because the connection was lost and I should disconnect from the session but with the tab open and then I can give it to "reconnect". However, I can see that the circle is red and the session is still active and working normally

![imagen](https://user-images.githubusercontent.com/28075454/50917801-8250b080-140c-11e9-8994-6ca78da57824.png)

**Comment by zxdong262** [comment]
If it takes more than 10 sec to get response, will show the red dot to indicate lost connection, not a good design, Thank you for all the feedback! @saulperez2905
