### ISSUE TITLE
UI problem - no UI. Gentoo Linux, XFCE4.

### ISSUE THREAD

**Issue by ErmakovDmitriy** [electerm/electerm#1072]
## Electerm version: 0.26.13

Also tested with:
commit 20547ca08e563c9664cc7d6f4513dc84a8e67955 (HEAD -> master, origin/master, origin/HEAD)
Author: ZHAO Xudong <zxdong@gmail.com>
Date:   Fri Jan 11 15:14:18 2019 +0800

## Expected Behavior
I downloaded the 0.26.13 release, unpacked it, started.
I expected to see a main window.

## Current Behavior
I started the application and saw only a task on my taskbar but not the main application window.
As I understood the main windows existed (elements existed either - I saw a mouse cursor changes when I moved it over possible position of the main window) but the window was 100% transparent (I did not think that it was "HTML opacity 0").

Then I cloned current git with commit 20547ca08e563c9664cc7d6f4513dc84a8e67955 and started it in developer mode:
```
git clone git@github.com:electerm/electerm.git
cd electerm
npm i

# start webpack dev server
npm start

# in a separate terminal session run app
npm run app
```
I saw the main window with a debug console. Everything was OK.
Then I tried to build the application from git sources.
The build was successful but "release" version had the same problem with UI.

Thank you for your work. I will be happy to help you, if I can.

**Comment by zxdong262** [comment]
Hi, Can you run electerm from cmd line, and post the log here?

**Comment by zxdong262** [comment]
@ErmakovDmitriy Hi, can you try the latest version?
