### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by lordbasex** [electerm/electerm#1100]
Hello I pass the translation to Spanish. 

IF I need betatester in MacOS I am available.

regards

[es_es.js.txt](https://github.com/electerm/electerm/files/2787793/es_es.js.txt)

**Comment by zxdong262** [comment]
Hi @lordbasex 

Thank you, can you submit a pull request in https://github.com/electerm/electerm-locales, after merge your pull request, your contribution can be logged into commit records.

**Comment by zxdong262** [comment]
Like this one: https://github.com/electerm/electerm-locales/pull/5

**Comment by zxdong262** [comment]
@lordbasex After merge your PR, then I will publish new release to add Spanish translation support.

**Comment by zxdong262** [comment]
@lordbasex Hi, do you know how to submit a PR or do you want to try this, if you do not want to try, it is OK, I can submit the change for you, just let me know.

**Comment by lordbasex** [comment]
If you do it, I do not know how it is.

Enviado desde mi iPhone

**Comment by zxdong262** [comment]
Is "Española" the right Spanish name for Spanish? @lordbasex

**Comment by lordbasex** [comment]
Spanish the latinoamerica. Argentina

Enviado desde mi iPhone

**Comment by lordbasex** [comment]
Is “Español”

Enviado desde mi iPhone

**Comment by zxdong262** [comment]
New version released with Spanish language support. Thank you for the support!

**Comment by zxdong262** [comment]
Added you to contributor list: https://github.com/electerm/electerm-locales

Do you have a homepage or github profile link? I could add it to your name.
