### ISSUE TITLE
No matching ciphers - cannot connect to Cisco devices

### ISSUE THREAD

**Issue by iantriggs** [electerm/electerm#1104]
## Expected Behavior
Should be able to connect to Cisco devices via SSH.

## Current Behavior
Currently it's failing with the following error:

Error: Handshake failed: no matching client->server cipher at check_KEXINIT (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:2375:15) at check (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:2254:9) at onKEXINIT (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:2251:5) at SSH2Stream.<anonymous> (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:207:5) at SSH2Stream.emit (events.js:182:13) at parse_KEXINIT (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:3963:8) at parsePacket (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:3859:12) at SSH2Stream._transform (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:693:13) at SSH2Stream.Transform._read (_stream_transform.js:190:10) at SSH2Stream._read (C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:252:15) at SSH2Stream.Transform._write (_stream_transform.js:178:12) at doWrite (_stream_writable.js:410:12) at clearBuffer (_stream_writable.js:540:7) at onwrite (_stream_writable.js:465:7) at SSH2Stream.afterTransform (_stream_transform.js:94:3) at C:\Downloads\electerm-0.26.31-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:442:11

The Cisco device looks like this:
```
Router1#show ssh 
Connection Version Mode Encryption  Hmac         State                 Username
0          2.0     IN   aes256-cbc  hmac-sha1    Session started       fred

```
## Possible Solution
Allow the user to select older ciphers.  

## Steps to Reproduce
1. Add new connection to the bookmarks to a Cisco device.
2. Attempt to connect.
3. The handshake failed error appears.

**Comment by zxdong262** [comment]
Hi @iantriggs I will investigate this, maybe build a custom version for you to test.

**Comment by zxdong262** [comment]
https://github.com/mscdex/ssh2/issues/417

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/releases/download/untagged-56f3511d49574d9306d9/electerm-0.26.33-win-x64.tar.gz 

Hi @iantriggs  custom build done, can you try this?

**Comment by iantriggs** [comment]
The link just says 'Not found', so cannot download.

**Comment by zxdong262** [comment]
http://electerm.html5beta.com/temp-electerm-0.26.33-win-x64.tar.gz

How about this one, I upload it to my server with elelcterm.

**Comment by zxdong262** [comment]
@iantriggs I will merge this into master any way, let me know how it work when you got time to test it. If it do not work as expected, I would open this again.

**Comment by iantriggs** [comment]
@zxdong262 Still no luck.  The error message is almost the same:

Error: Handshake failed: no matching client->server cipher at check_KEXINIT (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:2375:15) at check (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:2254:9) at onKEXINIT (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:2251:5) at SSH2Stream.<anonymous> (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:207:5) at SSH2Stream.emit (events.js:182:13) at parse_KEXINIT (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:3963:8) at parsePacket (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:3859:12) at SSH2Stream._transform (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:693:13) at SSH2Stream.Transform._read (_stream_transform.js:190:10) at SSH2Stream._read (C:\Downloads\electerm-0.26.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:252:15) at SSH2Stream.Transform._write (_stream_transform.js:178:12) at doWrite (_stream_writable.js:410:12) at writeOrBuffer (_stream_writable.js:394:5) at SSH2Stream.Writable.write (_stream_writable.js:294:11) at Socket.ondata (_stream_readable.js:672:20) at Socket.emit (events.js:182:13)

**Comment by iantriggs** [comment]
@zxdong262 Thanks, this version now works fine :)
