### ISSUE TITLE
[UI][Request]: Compact/Minimalist UI

### ISSUE THREAD

**Issue by x0rsw1tch** [electerm/electerm#1108]
## Electerm version:
0.26.31

## Detailed Description

Hello, I've been using Electerm as my daily driver for a little while now. The main reason for this is that I've been looking for a fast and modern (looking) SSH/SFTP. This fits the bill for the most part. Played around in DevTools to alter the layout (with some Photoshop), to propose a new main UI layout. Ideally, I'd like controls when needed, but not there when focusing on doing the SSH stuff that people use SSH for.

## Suggestions?

As far as the Main UI is concerned, here is what I envisioned:
- The UI is just in one spot, the title bar
- No sidebar, functionality controls are out of the way
- No distracting icons
- Easier to click window controls in the corner, matches other Electron apps like Postman and VS Code.
- (Not Shown): Dynamic Tab Widths based on Session/Bookmark Name up to max 15-20vw, or at least show more text. I often work with machines that have very similar names, so it's easy to get them confused.

![image](https://user-images.githubusercontent.com/9543257/51781321-3a58ab80-20e5-11e9-823d-5fc5bd1cd737.png)

When clicking on the Electerm Icon, you would get a context menu like so (inspired by VS Code). How this menu works is pretty obvious:

![image](https://user-images.githubusercontent.com/9543257/51781374-c4087900-20e5-11e9-9148-9bd57ebff552.png)

And lastly, when right-clicking on the "+" next to the terminal would provide a list of Saved Sessions, just like when using the main menu >> Open Session.  No need to change the left-click behavior.

**Comment by zxdong262** [comment]
Hi @x0rsw1tch 

Some feature from your suggestions have been added, you may try the latest release.

**Comment by x0rsw1tch** [comment]
@zxdong262 looking good! I really like the new menu!

Any chance we can get a sub-menu for the bookmark lists?

**Comment by zxdong262** [comment]
> @zxdong262 looking good! I really like the new menu!
> 
> Any chance we can get a sub-menu for the bookmark lists?

Good idea, I will think about this.

**Comment by zxdong262** [comment]
Close it for now, can not do bookmark menu yet.
