### ISSUE TITLE
zsh settings ???? 

### ISSUE THREAD

**Issue by iperfex-team** [electerm/electerm#1116]
Hi, how can I make zsh run every time I open a new terminal? You can select the interpreter bash, sh, zsh. ??

Is it a good idea to be able to select the type of interpreter in the configuration?
this would be possible?

![captura de pantalla 2019-01-28 12 06 21](https://user-images.githubusercontent.com/9824068/51844907-2be0de80-22f5-11e9-82ba-df0a15e14f2b.png)

![captura de pantalla 2019-01-28 12 06 59](https://user-images.githubusercontent.com/9824068/51845279-06080980-22f6-11e9-9e55-95a53af4415c.png)

**Comment by zxdong262** [comment]
Hi @iperfex-team , Yes, it is on the todo list.

**Comment by zxdong262** [comment]
#885

**Comment by zxdong262** [comment]
I may release a new version with custom exec support in a few days.

**Comment by zxdong262** [comment]
Hi @iperfex-team, Thank you for the feedback. Released a new version with custom exec support in settings.
