### ISSUE TITLE
Minimize to system tray

### ISSUE THREAD

**Issue by lopezdonaque** [electerm/electerm#1124]
Hi, first of all, it's a nice project!!
I'm using MobaXterm on Windows and PAC Manager on Ubuntu and after searching for a cross-platform terminal/ssh manager I will find Electerm!!
I will start to use it and report if I find some bug or feature to implement.
Thanks and nice work!

## Electerm version:
0.26.40

## Operating system(linux, macos, or windows7/8/10?):
Ubuntu 18.10

## Expected Behavior
On menu it should be appear an option to minimize to system tray.
Th window should be hidden and an icon should appear on the system tray.

## Current Behavior
No option available.

## Possible Solution
Implement new feature.

**Comment by zxdong262** [comment]
@lopezdonaque Right, will be done! Thanks for the feedback~
