### ISSUE TITLE
split for different servers

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1125]
## Electerm version:
26.40
## Operating system(linux, macos, or windows7/8/10?):
Windows 10
## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?

Currently the split option generates a parallel window of the same server to which it is connected. It would be a good contribution if you could open a parallel session of another server. something like that:

split pc1 || split pc2

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/842
