### ISSUE TITLE
Bookmarks lost on application close

### ISSUE THREAD

**Issue by lopezdonaque** [electerm/electerm#1166]
## Electerm version:
0.26.62

## Operating system(linux, macos, or windows7/8/10?):
Ubuntu 18.10

## Current Behavior
Every time the application opens I import the bookmarks previously exported.
When I close the application and open again, the bookmarks are lost.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Not happening in 18.04, seems I need to install a 18.10 to check it.

**Comment by zxdong262** [comment]
@lopezdonaque How many bookmark item do you have?

**Comment by lopezdonaque** [comment]
I have a directory with 5 bookmarks.
I could check something if you would like.
Where are stored bookmarks after imported?

**Comment by zxdong262** [comment]
@lopezdonaque  You can check `.config/electerm-localstorage.json `, I installed a new 18.04Ubunru, can not reproduce this.

**Comment by zxdong262** [comment]
Can you run it from terminal and post the log here?
```bash
electerm
```

**Comment by lopezdonaque** [comment]
electerm-localstorage.json
`"sessions":null,`

electerm
```
error parsing $HOME/.ssh/config
maybe no $HOME/.ssh/config, but it is ok
no ../../install-src file
[11:45:20.441] [info] App starting...
no /home/alberto/.config/electerm-config.js but it is ok
no ../../install-src file
Fri Mar 08 2019 11:45:20 GMT+0100 (CET) server runs on localhost 3075
Fri Mar 08 2019 11:45:21 GMT+0100 (CET) Created terminal with PID: nCfqG7ZWf
Fri Mar 08 2019 11:45:21 GMT+0100 (CET) Connected to terminal nCfqG7ZWf
Fri Mar 08 2019 11:45:21 GMT+0100 (CET) Resized terminal  nCfqG7ZWf  to  206  cols and  20  rows.
Fri Mar 08 2019 11:45:21 GMT+0100 (CET) Resized terminal  nCfqG7ZWf  to  206  cols and  49  rows.


```

**Comment by zxdong262** [comment]
and logs when quit electerm

**Comment by zxdong262** [comment]
Can you try delete ~/.config/electerm-localstorage.json to see if this fix it?

**Comment by zxdong262** [comment]
No response, close for now.

**Comment by lopezdonaque** [comment]
Sorry for the delay. I will finally import the bookmarks, create a new bookmark, and then it persist after restart.

**Comment by zxdong262** [comment]
@lopezdonaque So, it is empty at first, after import, restart, this bug will happen again?
