### ISSUE TITLE
Linuxmint can't start

### ISSUE THREAD

**Issue by phpluo** [electerm/electerm#1167]
## Operating system(linux, macos, or windows7/8/10?):
linux mint 19.1
## Expected Behavior

I can't start after I download and install it.

## Current Behavior

I double-clicked and I saw the icon on Plank but it disappeared after a while, didn't start up, didn't see any interface.
**ps -aux |grep electerm **
`phpluo   17081  0.0  0.6 1441104 111696 ?      Sl   14:05   0:01 /opt/electerm/electerm
phpluo   17084  0.0  0.2 368400 39040 ?        S    14:05   0:00 /opt/electerm/electerm --type=zygote --no-sandbox
phpluo   17109  0.0  0.4 474848 67756 ?        Sl   14:05   0:00 /opt/electerm/electerm --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=5EF26BD5188E7AA81555AC7620F93418
phpluo   17198  0.1  0.6 1441104 112524 ?      Sl   14:06   0:01 /opt/electerm/electerm
phpluo   17203  0.0  0.2 368400 39044 ?        S    14:06   0:00 /opt/electerm/electerm --type=zygote --no-sandbox
phpluo   17230  0.0  0.4 474848 67880 ?        Sl   14:06   0:00 /opt/electerm/electerm --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=5B56188A51E9820BC1EAAC88561E2FD8
phpluo   18662  0.1  0.6 1440560 111908 ?      Sl   14:15   0:01 /opt/electerm/electerm
phpluo   18667  0.0  0.2 368400 38856 ?        S    14:15   0:00 /opt/electerm/electerm --type=zygote --no-sandbox
phpluo   18694  0.0  0.4 474880 67752 ?        Sl   14:15   0:00 /opt/electerm/electerm --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=A71319049927D6042DAE08963ACA70CA
phpluo   18780  0.1  0.6 1441072 111204 ?      Sl   14:15   0:01 /opt/electerm/electerm
phpluo   18785  0.0  0.2 368400 38800 ?        S    14:15   0:00 /opt/electerm/electerm --type=zygote --no-sandbox
phpluo   18812  0.0  0.4 474848 67676 ?        Sl   14:15   0:00 /opt/electerm/electerm --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=23DE905A0D956DE3D6FD82840960448C
phpluo   20800  0.0  0.0  16180  1000 pts/0    S+   14:29   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn electerm`

**Comment by zxdong262** [comment]
which desktop are you using?

```

Cinnamon | 32-bit | 64-bit | An edition featuring the Cinnamon desktop
-- | -- | -- | --
MATE | 32-bit | 64-bit | An edition featuring the MATE desktop
Xfce | 32-bit | 64-bit | An edition featuring the Xfce desktop


```

**Comment by zxdong262** [comment]
Can you run it from terminal and post the log here?
```bash
electerm
```

**Comment by zxdong262** [comment]
I tried electerm in linuxmint-19.1-cinnamon-64bit virtualbox, works fine.

**Comment by zxdong262** [comment]
No further response, closed
