### ISSUE TITLE
No settings option for Ctrl+/ shortcut to split.

### ISSUE THREAD

**Issue by owensys** [electerm/electerm#1168]
## Electerm version:
0.26.62
## Operating system(linux, macos, or windows7/8/10?):
Windows7
## Expected Behavior

Use custom key to split a new connection.
## Current Behavior

Must use Ctrl+/ to split.
## Possible Solution

Can set custom key in settings.

**Comment by zxdong262** [comment]
最新版已加入快捷键设置
