### ISSUE TITLE
Chinese fonts is blur

### ISSUE THREAD

**Issue by kasuganosoras** [electerm/electerm#1181]
## Electerm version:
v0.26.63

## Operating system(linux, macos, or windows7/8/10?):
Windows 10

## Expected Behavior

The clear fonts

## Current Behavior

The fonts are blurred

## Possible Solution

No...

## Steps to Reproduce

1. Open the software
2. Do nothing, and then the fonts begins to blur.

## Context (Environment)

Simple PC

## Detailed Description

When I move the mouse to the text, It is clear.

![img](https://i.natfrp.org/6977eedd7e4417f85bf23dbfab2d8666.png)

And when I move out the mouse, It is begins blur

![img](https://i.natfrp.org/17b5bdcf0d9b251e639bae03d24bfb8e.png)

## Suggestions?

No...

**Comment by kasuganosoras** [comment]
才发现作者是国人……那我就直接用中文说吧
就是这个软件，它会出现文字模糊的情况，鼠标移动上去它就变得清晰，移开就会变得模糊。
这个问题我之前在其他软件也遇到过，不过都有一个共同点，那就是这些软件全都是基于 Webkit 内核编写的，HTML 写的 UI，我不知道 Electerm 是不是也和这个原因有关系。
我录了一个 GIF，可以看看

https://i.natfrp.org/44addd63ddab69003f919b7b46f90399.gif

（GIF 图太大了 Github 貌似显示不出来）
如果需要帮忙可以 QQ 联系我远程演示，204034
谢谢作者，很好用的终端软件

**Comment by zxdong262** [comment]
@kasuganosoras 🤩6位QQ

**Comment by zxdong262** [comment]
不能复现，估计跟你电脑的设定有关

**Comment by kasuganosoras** [comment]
> 不能复现，估计跟你电脑的设定有关

您可以加我 QQ 我远程演示一下，这个问题在我的笔记本电脑上也存在

**Comment by zxdong262** [comment]
> > 不能复现，估计跟你电脑的设定有关
> 
> 您可以加我 QQ 我远程演示一下，这个问题在我的笔记本电脑上也存在

你可以自己尝试,看看跟什么设置相关,UI,显示效果,字体什么的,或者一个新的虚拟机看看.

**Comment by zxdong262** [comment]
我测试了另外一台机器win10也没有复现

**Comment by zxdong262** [comment]
Close it for now, feel free to reopen it if anyone find a similar case.
