### ISSUE TITLE
[Feature Request] file permission keep

### ISSUE THREAD

**Issue by leonunix** [electerm/electerm#1190]
## Electerm version:
v0.26.67
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Suggestions?

Is there a possible to keep file permission where sftp upload with overwrite type.
Like mobaXterm It will keep older file permission when new file overwrite.
I my case. Sometimes i will update a version file with sftp. But every time i need to run chmod +x ** with the new file.

**Comment by zxdong262** [comment]
@leonunix Thank you, I think it is a bug as you described, I will try to fix it.

**Comment by zxdong262** [comment]
@leonunix Already done, will release in a few days.

**Comment by zxdong262** [comment]
Thank you for the feedback. Released new version with fix https://github.com/electerm/electerm/releases/tag/v0.26.73
