### ISSUE TITLE
Close terminal when terminal got exit signal

### ISSUE THREAD

**Issue by junhuoku007** [electerm/electerm#1194]
## Electerm version:

v0.26.67

## Operating system(linux, macos, or windows7/8/10?):

windows10

## Current Behavior

连接到ssh终端后，输入exit退出，tab标签页没有自动关闭

## Expected Behavior

输入exit退出后自动关闭该tab标签页

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1400
