### ISSUE TITLE
bookmark does not contract.

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1198]
## Electerm version:
26.71
## Operating system(linux, macos, or windows7/8/10?):
Windows
## Expected Behavior

contract markers
## Current Behavior

nothing happens
## Steps to Reproduce

when it comes to contracting bookmarks: if a subcategory does not contract first, it can not be contracted from the parent bookmark.

![imagen](https://user-images.githubusercontent.com/28075454/55264429-50e4c580-5242-11e9-9fdb-c8aaff25c3f2.png)

**Comment by zxdong262** [comment]
@saulperez2905 Thank you for the feedback. Released new version with fix https://github.com/electerm/electerm/releases/tag/v0.26.73

**Comment by saulperez2905** [comment]
Hi, in the new version the same thing happens, you still can not get the drop-down list without first contracting the sub-categories

**Comment by zxdong262** [comment]
@saulperez2905 you are right, I got it wrong, not solved.
