### ISSUE TITLE
Split session exit Error

### ISSUE THREAD

**Issue by inkroom** [electerm/electerm#1237]
## Expected Behavior
The first session should be normal

## Current Behavior

The first session disappear

## Steps to Reproduce
- oepn a ssh session
- split a horizontal session 
- type exit command in secend session
- close the horizontal session 
- the first session was closed

![关闭错误](https://user-images.githubusercontent.com/27911304/56707554-ef821a80-674b-11e9-917c-a49fb949a42a.gif)

##### the first session width error

Sometimes, close the secend session,then the first width is not 100% ;
But I can't find the Steps to Reproduce

![深度截图_选择区域_20190425110758](https://user-images.githubusercontent.com/27911304/56707176-68807280-674a-11e9-9240-336d92281404.png)

**Comment by zxdong262** [comment]
Hi @inkroom Thank you for the feedback.
1. the close split icon always close current active split.
2. I will check other problems.
