### ISSUE TITLE
Add a close button on the top right corner of the Software about

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#1239]
## Electerm version:
0.27.13
## Operating system(linux, macos, or windows7/8/10?):
windows
## Expected Behavior

I can close by the top right corner
## Current Behavior

I have to roll the middle mouse button to get to the bottom to close. (Because my screen is small)
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
You can click anywhere of the mask to close it.

**Comment by zxdong262** [comment]
Added a close button in 0.27.20.
