### ISSUE TITLE
incorrect spanish translation Text in config

### ISSUE THREAD

**Issue by danielectronic** [electerm/electerm#1288]
## Possible Solution

![image](https://user-images.githubusercontent.com/16022110/58658276-c8d47800-82e5-11e9-8e74-c5d18896157a.png)

**Comment by zxdong262** [comment]
Hi @danielectronic 

Thank you for feedback.

Would you like to submit a PR in https://github.com/electerm/electerm-locales, maybe you can review other text in https://github.com/electerm/electerm-locales/blob/master/locales/es_es.js ?

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm-locales/commit/3574eab12da84eae9e976c6cbe6b79b8e2ca9dfd
