### ISSUE TITLE
Support Arch linux 

### ISSUE THREAD

**Issue by sain801028** [electerm/electerm#1298]
Support Arch linux

**Comment by zxdong262** [comment]
Have you tried the electerm-0.27.37-linux-amd64.snap or electerm-0.27.37-linux-x64.tar.gz?

**Comment by sain801028** [comment]
use electerm-0.27.37-linux-x64.tar.gz ,but how to start electerm ?

**Comment by zxdong262** [comment]
Can you get it work?
