### ISSUE TITLE
[SUGGESTION] Allow user to select external editor to edit remote file

### ISSUE THREAD

**Issue by paesjoaopaulo** [electerm/electerm#1314]
Allow user to select a default application to edit remote files on SFTP

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1367

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1452

**Comment by manni** [comment]
啥时候解决一下呀 这个功能还是挺重要的

**Comment by SekiBetu** [comment]
似乎问题没有解决，环境里有code，点击 `编辑...` — `打开` 之后服务器会断开连接变红
