### ISSUE TITLE
[Feature Request]support port forwarding

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1315]
##  [Feature Request]
support port forwarding,Tks
希望支持端口转发，谢谢

**Comment by zxdong262** [comment]
我觉得可以保存一个快速命令运行一下就好，要比填写表单合适，有什么特定需求要保存为书签来访问吗 @lizhuangs

**Comment by lizhuangs** [comment]
我之前试过用快速命令可以用，但是怎么说呢，需要代理转发的服务器多了，自己也忘了，而且每次都要先执行一下命令有点繁琐。

**Comment by zxdong262** [comment]
你是说jump host？

@lizhuangs

**Comment by lizhuangs** [comment]
我用的后面这种。ssh -N -f -D 127.0.0.1:10000 xxx@xxx.xxx

**Comment by lizhuangs** [comment]
这个实现在xshell需要，先建一个ssh连接，里面配置隧道（端口转发），连接建立后。再打开一个ssh连接的选项卡，这个ssh连接的配置那里要先配置代理，代理填第一个ssh连接的本地连接+端口。
假如服务器A，只能通过服务器B连接，而现在我有C,D,E等其它服务器想要连接A就遇到这种场景了。

**Comment by lizhuangs** [comment]
我现在先用快速命令简单实现了，每次ssh的时候需要输入服务器的密码，密码是随机的很长的串，于是我把密码也保存成了快速命令:joy::joy::joy:
