### ISSUE TITLE
[Feature Request]support quick command

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1316]
## [Feature Request]support quick command
希望支持快速命令，谢谢～

**Comment by zxdong262** [comment]
什么样的快速命令呢，可以解释一下吗

**Comment by lizhuangs** [comment]
就是终端的最下面有一个快速命令的状态栏，比如
这个命令每天查看服务器日志，取名为tail log：
```Date=`date "+%Y-%m-%d"`;echo -e " \n\033[42;31m ###today is "$Date" ，show logs start... : ###\033[0m\n";tail -400f ./logs/catalina.$Date.log;```
点击tail log终端上面就会自动执行这个命令，一般会把经常用的命令放在这里。可以在各种服务器执行。毕竟本地的alias只能在当前机器使用。

**Comment by zxdong262** [comment]
@lizhuangs 感谢，已发布新版本，支持快速命令，不知道是不是你期望的样子，欢迎反馈。

**Comment by lizhuangs** [comment]
昨天看到关闭issue就在等新版本了，发现官网没更新。已试用，体验很棒，感谢！
