### ISSUE TITLE
选项卡标题栏仅显示标题名称

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1317]
## 选项卡标题栏仅显示标题名称
试用了一下electerm，觉得做得很不错，但是还有不少东西不全，所以我单独提了几个issue。
比如快速命令和端口转发是常用的2个功能。另外说一些细节，个人看法：
1. 既然ssh连接那里已经配置了标题，选项卡就仅显示标题就行了，为什么后面要多此一举显示用户名@服务器地址，这样会显得标题栏非常的宽，如果选项卡再多几个会显得不够用。建议做成类似xshell的那种，鼠标移到选项卡标题栏显示用户名@服务器地址即可
2.  设置界面在1080p上面会显示不全，要上下拉动，页面肯定是够用的而且大片空白，个人建议把类似的选项放在一起分类，然后左右布局，现在每行一个设置感觉好空荡而且麻烦，过于简洁了。上下拖动滚动条，来回切换窗口，偶现点击关闭设置界面右上角的x没有反应，双击变成放大或缩小窗口的问题。
3. 安装完成后在deepin没有icon。
4. 内置多来几套主题就更好了～

其它以后发现再来评论，感谢作者！

**Comment by zxdong262** [comment]
@lizhuangs "安装完成后在deepin没有icon" 是下载deb安装的？

**Comment by lizhuangs** [comment]
是的。icon显示的是一个默认的齿轮状图标。
![深度截图_选择区域_20190822145954](https://user-images.githubusercontent.com/7904121/63493197-a4a3c400-c4ed-11e9-831a-64db79fd9d85.png)

**Comment by ImMrMa** [comment]
我觉得你的提议非常不错，希望可以尽快搞定啊。还有很多小问题呢。。
