### ISSUE TITLE
我调整不了窗口的大小

### ISSUE THREAD

**Issue by mlzxdzl** [electerm/electerm#1318]
## Electerm version:
0.27,50
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior

我打开electerm后只能最大化 没有办法调整窗口大小。
win10有个功能是把程序拖到屏幕边缘他会自动把程序变成半个屏幕大小的，或者使用win+后方向键可以将窗口变成屏幕右边一半大小，这样我可以把屏幕左边放个网页或者文档方便我操作，但是程序现在实现不了，希望可以加这个功能

**Comment by zxdong262** [comment]
我试了可以拖动，或者在边缘调整宽度高度，如果还有问题欢迎提交，这个关闭了
