### ISSUE TITLE
sftp does not work

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1320]
## 软件版本
0.27
## 系统
deepin15.11，linux内核4.15
## 问题描述
今天连接上服务器之后，想上传一个文件。提示是否覆盖，点击覆盖后页面没有任何反应。后来在最顶部中间发现一个很小的上传列表。里面点击继续进度条也没反应。
## 建议
建议electerm最下面增加一个控制面板，可以控制隐藏显示。面板有选项卡功能，比如第一个选项卡上传下载列表，第二个选项卡调试面板显示上传下载的日志信息和错误信息，当然可能还有很多其他功能的选项卡。现在这个列表太不显眼了，而且我也不知道我为什么卡住了没有动。

**Comment by lizhuangs** [comment]
对了，补充说一下，我当时上传的账号出现这个问题是因为没有权限。

**Comment by zxdong262** [comment]
ref to https://github.com/electerm/electerm/issues/1446
