### ISSUE TITLE
sftp卡死

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1323]
## Electerm version:
0.27.52
## Operating system(linux, macos, or windows7/8/10?):
deepin15.10
## Possible Solution
文件过多，大约几百个
## Steps to Reproduce
我以为左侧路径是路径导航用的，于是我把本地要上传的路径复制进行，然后点击后面的向右的箭头。发现它把这个路径的所有文件都上传到服务器了。由于文件过多，很卡，我强制关闭了。
## Suggestions?
1.左侧路径输入框，点击后面的向右箭头，不应该是切换到指定的这个目录么，怎么是上传操作。。
2.建议在隐藏显示目录、前往上一级后面再添加一个按钮：切换到ssh命令所在的目录。
经常在ssh操作的时候，切换到sftp需要上传文件，如果有这个按钮会方便太多。

**Comment by zxdong262** [comment]
@lizhuangs 能截个图么，“向右的箭头”是什么

**Comment by lizhuangs** [comment]
发生问题时的图大约是这样的：
![深度截图_electerm_20190822114559](https://user-images.githubusercontent.com/7904121/63493287-da48ad00-c4ed-11e9-9547-2d7fe0b41e34.png)
向右的箭头指的是当我复制一个路径到下面这个输入框的时候，后面那个刷新的图标，变成了向右的箭头，点击这个箭头就成了上传操作。
![深度截图_选择区域_20190822150213](https://user-images.githubusercontent.com/7904121/63493292-dddc3400-c4ed-11e9-8315-3639ba483700.png)
