### ISSUE TITLE
Sync settings between multiple electerm on different machines

### ISSUE THREAD

**Issue by pincopallopino** [electerm/electerm#1326]
IMPROVEMENT

Sync settings/theme/bokmarks of two programs of electerm installed on different machines.

maybe using an account?

**Comment by zxdong262** [comment]
![electerm-gist-id1](https://user-images.githubusercontent.com/1641949/64153660-e32c6d80-ce61-11e9-9464-431bbffd1729.png)
![electerm-gist-id2](https://user-images.githubusercontent.com/1641949/64153662-e32c6d80-ce61-11e9-94b7-0963da558726.png)

**Comment by zxdong262** [comment]
Now support sync to secret github gist
