### ISSUE TITLE
快速命令点击无效

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1328]
## Electerm version:
0.27.53
## Operating system(linux, macos, or windows7/8/10?):
deepin15.10
## Expected Behavior
刚刚提示升级，就更新了一下，发现之前的那个向右是上传的问题好了。感谢。
然后我正好想试用一下，发现点击快速命令没反应，有时候却突然又是好的。
我仔细看了下，发现鼠标移动到快速命令的下半部分就是好的，鼠标样式也改变了。
上半部分没有获取到点击的事件，貌似是我看不到的一个组件只显示了一半。

**Comment by lizhuangs** [comment]
对了，顺便提一下，快速命令在设置界面左右2侧的i18n没有处理，显示的是quickCommands.非常显眼总感觉怪怪的～

**Comment by lizhuangs** [comment]
又发现一个问题，新建快速命令的时候，点击保存成功后，输入框没有清空，当我直接用这个输入框再次保存快速命令的时候，会直接修改之前的那一条，而不是新建。

**Comment by zxdong262** [comment]
fixed
