### ISSUE TITLE
[功能建议] 登录shell后，自动输入命令

### ISSUE THREAD

**Issue by yzfly** [electerm/electerm#1331]
首先感谢： 很棒的 SSH 客户端, UI 和功能都让人赏心悦目，感谢开发者的付出
 
提一点小建议，就是登录 shell 后能否设置自动执行预先设定的命令，如 xshell 里面的预定义规则一样，如： https://blog.csdn.net/SwTesting/article/details/80283632

应用场景： 多人使用同一个用户登录linux, 每个人都有自己的文件夹，希望在不修改 .bashrc 的情况下，自己登录的时候能够自动切换到自己的文件夹。

该功能也可通过 quick command 实现，手动多点一下即可。

简单建议，仅供参考，谢谢～

**Comment by lizhuangs** [comment]
看来quick command需求的人挺多的。我上次提了一下，作者马上就加上去了，简直神速。。。现在用得飞起。

**Comment by zxdong262** [comment]
@yzfly 有的，试试这个
<img width="528" alt="Screen Shot 2019-08-26 at 10 35 12 AM" src="https://user-images.githubusercontent.com/1641949/63661472-4fb5c580-c7ed-11e9-8c8f-6c94f9290495.png">

**Comment by yzfly** [comment]
> @yzfly 有的，试试这个
> <img alt="Screen Shot 2019-08-26 at 10 35 12 AM" width="528" src="https://user-images.githubusercontent.com/1641949/63661472-4fb5c580-c7ed-11e9-8c8f-6c94f9290495.png">

谢谢, 刚刚使用了该功能, 很棒, 是自己之前疏忽了

**Comment by qqwmly** [comment]
run script  能执行多个命令吗
比如
cd work
./a.bash
echo 'aaaa'
我只会执行一个命令

**Comment by zxdong262** [comment]
> run script 能执行多个命令吗 比如 cd work ./a.bash echo 'aaaa' 我只会执行一个命令

可以` ls && mkdir a && rm -rf a`这样
