### ISSUE TITLE
无法使用 ed25519 密匙登录.

### ISSUE THREAD

**Issue by loveqianool** [electerm/electerm#1334]
## Electerm version:
v0.27.53

## Operating system(linux, macos, or windows7/8/10?):
windows 10 1903

## Current Behavior

无法使用 ed25519 密匙登录,同一时间我用另一个客户端能成功登录.
以下是报错

`Error: Cannot parse privateKey: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT at Client.connect (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\node_modules\@electerm\ssh2\lib\client.js:241:13) at run (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\server\terminal.js:209:12) at C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\server\terminal.js:223:9 at Promise._execute (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:313:9) at Promise._resolveFromExecutor (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\node_modules\bluebird\js\release\promise.js:488:18) at new Promise (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\node_modules\bluebird\js\release\promise.js:79:10) at Terminal.remoteInit (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\server\terminal.js:84:12) at async exports.terminal (C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\server\terminal.js:272:3) at async C:\Users\Downloads\electerm-0.27.53-win-x64\resources\app.asar\server\server.js:23:16`

顶部无法调整窗口大小.

![nFFWBd.png](https://s2.ax1x.com/2019/09/03/nFFWBd.png)

**Comment by zxdong262** [comment]
发布了新版本，应该可以了，感谢反馈！

**Comment by loveqianool** [comment]
https://i.niupic.com/images/2019/09/03/_8.gif

看上图,我这边更新之后还是一样的报错,是因为我的私匙有密码吗?

**Comment by zxdong262** [comment]
@loveqianool 我再看看

**Comment by zxdong262** [comment]
不是有密匙的问题，我得看看怎么回事

**Comment by zxdong262** [comment]
根据这个应该可以，但是仍然不行，我还没有找到原因，不过用默认方式创建的key还是支持的
 https://github.com/mscdex/ssh2/issues/352

**Comment by zxdong262** [comment]
这次应该可以了 @loveqianool

**Comment by loveqianool** [comment]
我没办法测试了，我已经转到 RSA 密匙了。谢谢你的工作。
