### ISSUE TITLE
希望增加对串口协议的支持

### ISSUE THREAD

**Issue by winter110** [electerm/electerm#1348]
## Current Behavior

因为工作中需要使用ssh和serial，之前一直用的SecureCRT，但是一直不好用，现在ssh用electerm，串口调试时候还是用的SecureCRT，希望可以增加对串口的支持，那就能彻底用electerm了。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
@winter110 代码已经写好了，不过还没有在真实设备上测试，下周arduino套件到货测试一下，大概就会发布了。

**Comment by winter110** [comment]
嗯，太感谢了，这么快就开发完了，等新版本发布了我第一时间更新。

**Comment by yi-ge** [comment]
哇，太牛了！正期待呢！

**Comment by zxdong262** [comment]
耽搁了一段时间，现已发布，欢迎测试~
