### ISSUE TITLE
建议增加一个如xshell那样的“保持活动状态”

### ISSUE THREAD

**Issue by shinebay** [electerm/electerm#1349]
![image](https://user-images.githubusercontent.com/7820385/64506308-b5d03b80-d309-11e9-9720-b0fd03916127.png)
包括：

1. 连接会话期间发送保持活动状态信息
2. 网络为空闲状态时发送TCP保持活动数据包

这样可以避免频繁断线

**Comment by zxdong262** [comment]
默认就是会保持连接，如果断了，那么有可能是网络或者其他问题
