### ISSUE TITLE
Terminal Themes: Foreground color not respected

### ISSUE THREAD

**Issue by x0rsw1tch** [electerm/electerm#1355]
## Expected Behavior
Foreground color set in theme is applied to un-formatted text in terminal.

## Current Behavior
Un-formatted foreground text is always #bbbbbb, regardless of configuration.

## Steps to Reproduce
1. Create new terminal theme
2. Change foreground color from #bbbbbb to something else
3. Open new terminal, or SSH session. 
4. Foreground text is incorrect color.

Sample Config:
```
foreground=#ff5c33
background=#000000
cursor=#b5bd68
cursorAccent=#1d1f21
selection=rgba(255, 255, 255, 0.3)
black=#575757
red=#bb0000
green=#00bb00
yellow=#bbbb00
blue=#0000bb
magenta=#bb00bb
cyan=#00bbbb
white=#acacac
brightBlack=#757575
brightRed=#ff5555
brightGreen=#55ff55
brightYellow=#ffff55
brightBlue=#5555ff
brightMagenta=#ff55ff
brightCyan=#55ffff
brightWhite=#cacaca
```

**Comment by zxdong262** [comment]
@x0rsw1tch Thank you for the feedback!
