### ISSUE TITLE
SFTP上传文件页面卡死

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1364]
## Electerm version:
最新版本
## Operating system(linux, macos, or windows7/8/10?):
deepin15.11
## Expected Behavior
上传文件的时候卡死，只好强制关闭了终端

## Steps to Reproduce
1.SFTP左侧选择了17个文件，右键上传，提示是否覆盖，选择全部覆盖
2.可以看到中间在上传，但是此时明显感觉很卡
3.到99%时卡死，右侧不时出现转圈的图标
![深度截图_electerm_20190924211235](https://user-images.githubusercontent.com/7904121/65514842-b1627000-df10-11e9-84dc-39479bdf89ef.png)

**Comment by zxdong262** [comment]
-> merge to https://github.com/electerm/electerm/issues/1446
