### ISSUE TITLE
can't delete connection

### ISSUE THREAD

**Issue by lushunming** [electerm/electerm#1368]
## Expected Behavior
add ssh connection then want to delete it ,it should be deleted.

## Current Behavior
add ssh connection then want to delete it but it failed and show no message.

## Possible Solution
did't implent the function 

## Steps to Reproduce
1. add a ssh connection 
2. go to bookmark and click edit ,then click the X( delete)
3. click on delete on the confirm 
4. the connection still there

## Detailed Description
download the newest version

**Comment by zxdong262** [comment]
Thank you for the bug report, released new version, should fix now.

**Comment by lushunming** [comment]
好的，有空下载看下
 
------------------
苏州大学 网络工程系 卢顺明


 




------------------ 原始邮件 ------------------
发件人: "ZHAO Xudong"<notifications@github.com>; 
发送时间: 2019年10月8日(星期二) 下午3:49
收件人: "electerm/electerm"<electerm@noreply.github.com>; 
抄送: "Mars "<1357197829@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [electerm/electerm] can't delete connection (#1368)




Thank you for the bug report, released new version, should fix now.
