### ISSUE TITLE
How to set terminal type in settings

### ISSUE THREAD

**Issue by xcomart** [electerm/electerm#1370]
## Electerm version:
v0.27.67

## Operating system(linux, macos, or windows7/8/10?):
linux

## Expected Behavior

Terminal-type(ansi, vt100, xterm, xterm-color, xterm-color256...) setting must be shown and can be chosen in settings UI.

## Current Behavior

There is no settings about terminal-type.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
@xcomart Now there is a terminal type setting in setting panel, which will affect local terminal. Thank you for the feedback!
