### ISSUE TITLE
希望支持调整窗口大小

### ISSUE THREAD

**Issue by mlzxdzl** [electerm/electerm#1376]
## Electerm version:
electerm-0.27.70
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior

希望可以调整窗口大小，现在打开不能自由调整程序窗口大小，很不方便

**Comment by zxdong262** [comment]
不能复现这个问题，可以调整窗口大小，你可以截图看看吗？

**Comment by mlzxdzl** [comment]
抱歉现在有可以了，之前可能是电脑问题。。。。
