### ISSUE TITLE
窗口最小化以后， 就再也打不开了， 而且close时报错

### ISSUE THREAD

**Issue by Jesse2134** [electerm/electerm#1383]
## Expected Behavior
 
最小化窗口
## Current Behavior

最小化后 才能还原回来
## Possible Solution

窗口管理
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Jesse2134** [comment]
报错内容：
Uncaught Exception:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:188:13)
    at /Volumes/electerm 0.27.72/electerm.app/Contents/Resources/app.asar/app.js:63:13
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by zxdong262** [comment]
不能复现，看起来你没有安装到application?,可以试试安装到application吗

**Comment by Jesse2134** [comment]
很抱歉，我再次 安装到application， 软件 能打开，但是没有窗口可显示，电脑桌面有灰暗，command+0 也不行。。。  Windows目前使用不错， 所以，很想解决Mac上这个问题

**Comment by Jesse2134** [comment]
使用ClearnMyMac 重置应用，好像也不可以

**Comment by zxdong262** [comment]
试试把配置文件删除然后再打开electerm看看
```bash
rm -rf ~/Library/Application\ Support/electerm*
```

**Comment by zxdong262** [comment]
应该被修复了 https://github.com/electerm/electerm/commit/ece7c3dcca9439e46cf51530c3022b58ec0b19e7
