### ISSUE TITLE
sftp右侧不显示列表，提示超时

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1384]
## Electerm version:
0.27.72
## Operating system(linux, macos, or windows7/8/10?):
deepin15.11
## Expected Behavior

sftp超时不显示文件
## Steps to Reproduce

1.ssh -N -f -D 127.0.0.1:10000 xxx@xxx
2.连接服务器，ssh连接正常
3.点击sftp，sftp右侧界面显示加载中的转圈图标
4.过一会右下角显示超时，关闭electerm后重复执行有一定机率正常。
```
Timed out while waiting for handshake
Error: Timed out while waiting for handshake
    at file:///opt/electerm/resources/app.asar/assets/js/electerm.0.27.72-23ebfa626cf341600289d47538d4195c7284860c.js:156:86335
    at WebSocket.a (file:///opt/electerm/resources/app.asar/assets/js/electerm.0.27.72-23ebfa626cf341600289d47538d4195c7284860c.js:156:48789)
```
![深度截图_electerm_20191023164813](https://user-images.githubusercontent.com/7904121/67375973-f207e480-f5b5-11e9-8477-b23ae8e4cf53.png)

**Comment by 617721040** [comment]
在右上角手动输入一个路径试试看，比如 / 或者 /root

**Comment by lizhuangs** [comment]
@617721040  下次遇到了我试试，不过我感觉应该不行，因为出问题的那会儿，我点击了右面的刷新按钮，但是那时候那个按钮似乎只是可见的状态无法点击。

**Comment by zxdong262** [comment]
@lizhuangs 通常应该就是连不上或者网络堵塞超时，可以试试设置更长的超时时间，在设置里

**Comment by lizhuangs** [comment]
@zxdong262 我看了下设置里面的超时时间是50秒，好像已经很长了。。我今天重试了几次，没有复现这个问题。我ssh那里连接是正常的，sftp是因为连接使用的协议不同么？

**Comment by zxdong262** [comment]
@lizhuangs 你的授权方式是什么，密码还是key或者组合？

**Comment by zxdong262** [comment]
@lizhuangs 也可能是偶然的网络问题吧

**Comment by lizhuangs** [comment]
@zxdong262 就是第一步的使用ssh做了一个端口映射，因为公司的服务器不让直连。sftp界面我之前也遇到过慢的问题，但是没有这次这样不显示了。

**Comment by kevinxu001** [comment]
Electerm version:
0.27.74

Operating system(linux, macos, or windows7/8/10?):
deepin15.11

SSH  SERVER
freebsd 12.0

Expected Behavior
sftp右侧无法显示文件，一直转圈，如果服务器系统是LINUX正常

**Comment by zxdong262** [comment]
@kevinxu001 确实没有测试过freebsd， 我看看如何能验证一下
