### ISSUE TITLE
登陆Juniper设备提示Error: No such file

### ISSUE THREAD

**Issue by 617721040** [electerm/electerm#1385]
## Electerm version:
27.72

## Operating system(linux, macos, or windows7/8/10?):
windows10

## Current Behavior
登陆juniper设备提示error
Error: No such file
    at file:///D:/electerm-0.27.72-win-x64/resources/app.asar/assets/js/electerm.0.27.72-23ebfa626cf341600289d47538d4195c7284860c.js:156:86930
    at WebSocket.a (file:///D:/electerm-0.27.72-win-x64/resources/app.asar/assets/js/electerm.0.27.72-23ebfa626cf341600289d47538d4195c7284860c.js:156:49384)

## Steps to Reproduce
ssh登陆juniper设备一定会出现这个error

## Context (Environment)

不影响正常使用

**Comment by zxdong262** [comment]
可能是隐藏文件或者链接文件解析问题，不过我没有这种设备，很难验证。

**Comment by 617721040** [comment]
我可以提供一个juniper测试设备，您看需要吗

**Comment by zxdong262** [comment]
@617721040 感谢，登录方式可以发我邮箱 zxdong@gmail.com

**Comment by 617721040** [comment]
@zxdong262 您好，已经发了

**Comment by zxdong262** [comment]
@617721040 确认了问题，非常感谢!你可以取消发给我的授权了。

**Comment by zxdong262** [comment]
@617721040 已发布新版本，解决了这个问题
