### ISSUE TITLE
Bookmarks have disappeared

### ISSUE THREAD

**Issue by j53c0rd** [electerm/electerm#1386]
## Electerm version:
v0.27.72

## Operating system(linux, macos, or windows7/8/10?):
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

## Expected Behavior
Bookmarks should be visible in the bookmarks menu when starting the application.

## Current Behavior
After Electerm loads all of my previously saved bookmarks are no longer visible in the Bookmarks menu.

## Steps to Reproduce

1. Open Electerm
2. Create ~50 bookmarks
3. Close Electerm
4. Open Electerm and go to the Bookmarks menu, all bookmarks are missing except entries pulled from my ssh_config

**Comment by zxdong262** [comment]
@j53c0rd Can you try one bookmark, would it disappear after closing? So I can confirm it is not related to bookmark counts.

**Comment by j53c0rd** [comment]
I can try this tomorrow however I don't think that is the issue, I've had a static number of bookmarks since initially installing electerm a couple of months ago, the bookmarks just disappeared this morning when I booted up and opened the application.  Where are the bookmarks stored? Any chance I can recover them, setting them up again from scratch is going to be a major pita.

Thanks for your time!

**Comment by zxdong262** [comment]
@j53c0rd You can check `~/.config/electerm-localstorage.json`

**Comment by j53c0rd** [comment]
I looked at that file today after reading another ticket while researching the problem, that file has no bookmark related info in it on my machine.

**Comment by zxdong262** [comment]
@j53c0rd In that case, it may lost the data already during file saving, you may try the sync feature, it can sync bookmarks and some other data to your personal secret gist.

And how about now, if you add some new bookmark, will it disappear after closing?
