### ISSUE TITLE
[Suggest]弹出窗口本身添加滚动条

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#1389]
## Electerm version:
0.27.74
## Operating system(linux, macos, or windows7/8/10?):
deepin15.11
## Suggestions?
现在的窗口滚动条都是全局的，弹出来的窗口把页面撑得很高很丑。
建议窗口都做成依赖组件这个窗口这个大小就可以了。然后固定高度，如果高度超出，则滚动条在依赖组件这个窗口本身的右侧就行。
![深度截图_electerm_20191025111058](https://user-images.githubusercontent.com/7904121/67540625-9efa7280-f718-11e9-9945-c760cf337d7b.png)
像下面这2个，窗口就很高很高了，撑出去了。
![深度截图_electerm_20191025111110](https://user-images.githubusercontent.com/7904121/67540641-a588ea00-f718-11e9-8ae1-55e837650fed.png)
![深度截图_electerm_20191025111126](https://user-images.githubusercontent.com/7904121/67540644-a883da80-f718-11e9-8f8c-b244d103700b.png)

**Comment by zxdong262** [comment]
这是antd modal组件的默认行为，如果你能说服antd改变，我也会采用。

**Comment by lizhuangs** [comment]
antd作者告诉我，这样设置就可以，并且我测试过，这个是可行的：
bodyStyle={
     maxHeight: 400,
     overflow: 'auto' 
  }

**Comment by lizhuangs** [comment]
@zxdong262 求支持呀，我搜索代码有8个地方出现这个modal。实际过程中maxHeight还得动态获取屏幕分辨率做减法算出来。

**Comment by zxdong262** [comment]
现在不再使用modal了
