### ISSUE TITLE
打开多个窗口,然后将新打开的窗口关闭,会提示error

### ISSUE THREAD

**Issue by 617721040** [electerm/electerm#1390]
## Electerm version:
27.74
## Operating system(linux, macos, or windows7/8/10?):
windows 10
## Expected Behavior

打开两个窗口,然后将新打开的关闭,100%复现错误
## Current Behavior

![image](https://user-images.githubusercontent.com/7239754/67830331-31ce4f00-fb15-11e9-869b-f78cfbee9b0c.png)
![image](https://user-images.githubusercontent.com/7239754/67830404-72c66380-fb15-11e9-9a36-2c8e57b3a939.png)

**Comment by zxdong262** [comment]
@617721040 目前不支持多窗口

**Comment by zxdong262** [comment]
fixed by https://github.com/electerm/electerm/commit/8224a7d9750921df8f96a36e7d71edf74e310c51
