### ISSUE TITLE
 connect server report a error

### ISSUE THREAD

**Issue by tuablove** [electerm/electerm#1396]
## Electerm version:
v0.27.74
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

connection fails: Handshake failed: no matching key exchange algorithm
## Current Behavior

i can't connection server
## trace
Error: Handshake failed: no matching key exchange algorithm at check_KEXINIT (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:2336:15) at check (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:2274:9) at onKEXINIT (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:2271:5) at SSH2Stream.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:208:5) at SSH2Stream.emit (events.js:200:13) at parse_KEXINIT (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3960:8) at parsePacket (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3856:12) at SSH2Stream._transform (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:694:13) at SSH2Stream.Transform._read (_stream_transform.js:189:10) at SSH2Stream._read (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:253:15) at SSH2Stream.Transform._write (_stream_transform.js:177:12) at doWrite (_stream_writable.js:417:12) at writeOrBuffer (_stream_writable.js:401:5) at SSH2Stream.Writable.write (_stream_writable.js:301:11) at Socket.ondata (_stream_readable.js:713:22) at Socket.emit (events.js:200:13)

**Comment by tuablove** [comment]
it's cool,it works well again! awesome!!!

**Comment by zxdong262** [comment]
@tuablove Thank you for the feedback!
