### ISSUE TITLE
use command sz to download from server the progress  keep in 99%

### ISSUE THREAD

**Issue by tuablove** [electerm/electerm#1399]
## Electerm version:
v0.27.76
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

use command sz to download from server the progress  keep in 99% and the computer cpu keep in high level,the package which i download has already downloaded,but the progess keep in 99%.
## Current Behavior

i canceled that.
![image](https://user-images.githubusercontent.com/475774/68831307-e1481b80-06e8-11ea-81ca-9237b6fc0060.png)

**Comment by zxdong262** [comment]
@tuablove How about small files, can you try a small file, maybe only works for small files.

**Comment by tuablove** [comment]
@zxdong262 i tried a file with size 87KB ,it works well.

**Comment by zxdong262** [comment]
@tuablove It is based on https://github.com/FGasper/zmodemjs, the only js solution I know, probably not solid enough.

**Comment by tuablove** [comment]
@zxdong262  突然发现你会中文....我还以为老外呢，这整的我累得...

**Comment by lonnywong** [comment]
@tuablove 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
