### ISSUE TITLE
Need a better zmodem module

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#1401]

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1399

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1392

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1435

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1533

**Comment by gefule** [comment]
rzsz看到您说的不支持取消上传功能，能否通过隐藏窗口实现

**Comment by zxdong262** [comment]
@gefule 具体是怎么个流程呢

**Comment by gefule** [comment]
> @gefule具体是怎么个流程呢

点击取消的时候把上传的窗口隐藏 ，而不是关闭，这样不会重置了把，如果再上传，打开一个新的上传窗口

**Comment by gefule** [comment]
上传的问题没办法解决吗？有点遗憾

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1603

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1873

**Comment by lonnywong** [comment]
@gefule 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
