### ISSUE TITLE
X11 can not run on WINDOWS 10

### ISSUE THREAD

**Issue by 442179055** [electerm/electerm#1404]
error log like this:

Error: Unable to request X11 at D:\Program Files (x86)\electerm\resources\app.asar\node_modules\@electerm\ssh2\lib\client.js:1273:21 at SSH2Stream.<anonymous> (D:\Program Files (x86)\electerm\resources\app.asar\node_modules\@electerm\ssh2\lib\Channel.js:206:24) at SSH2Stream.emit (events.js:200:13) at parsePacket (D:\Program Files (x86)\electerm\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:3352:10) at SSH2Stream._transform (D:\Program Files (x86)\electerm\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:694:13) at SSH2Stream.Transform._read (_stream_transform.js:189:10) at SSH2Stream._read (D:\Program Files (x86)\electerm\resources\app.asar\node_modules\ssh2-streams\lib\ssh.js:253:15) at SSH2Stream.Transform._write (_stream_transform.js:177:12) at doWrite (_stream_writable.js:417:12) at writeOrBuffer (_stream_writable.js:401:5) at SSH2Stream.Writable.write (_stream_writable.js:301:11) at Socket.ondata (_stream_readable.js:713:22) at Socket.emit (events.js:200:13) at addChunk (_stream_readable.js:294:12) at readableAddChunk (_stream_readable.js:275:11) at Socket.Readable.push (_stream_readable.js:210:10)

**Comment by zxdong262** [comment]
@442179055 So you can get x11 working using other terminal app?

**Comment by hqabcxyxz** [comment]
> @442179055 So you can get x11 working using other terminal app?

my electerm version is 1.5.4 win portable...

**Comment by zxdong262** [comment]
@captainfffsama @442179055 As I tested, start Mobaxterm's x11 window, then it will work
