### ISSUE TITLE
一个奇怪右键粘贴的问题

### ISSUE THREAD

**Issue by leonunix** [electerm/electerm#1408]
问题是这样的。我有多台电脑都装了electerm。
但是有一台electerm有一个很大的差异。就是右键的时候会自动贴上剪贴板的内容。但是无法叫出右键菜单。但是其他安装的electerm的都不会。我也不记得我在这台机器上设置过什么特殊的东西。
虽然这个功能是我一直很想要的。但是这个差异太诡异了。

**Comment by zxdong262** [comment]
确实有这么一个设置，好像我不小心给删除了，稍等，我得恢复一下这个设置。

**Comment by zxdong262** [comment]
感谢反馈，在最新版已恢复这个选项
