### ISSUE TITLE
建议去除点击链接自动打开浏览器的功能

### ISSUE THREAD

**Issue by vicliucn** [electerm/electerm#1415]
目前点击链接，会自动打开浏览器，这个功能经常引起误操作，建议去除或者添加开关选项配置。

**Comment by zxdong262** [comment]
@vicliucn 感谢反馈，已经加了一个新的设定，可以试试

**Comment by vicliucn** [comment]
> @vicliucn 感谢反馈，已经加了一个新的设定，可以试试

赞，处理非常快。
