### ISSUE TITLE
mac下本地终端中文乱码

### ISSUE THREAD

**Issue by mhlywxl** [electerm/electerm#1417]
## Current Behavior

用electerm的本地终端：

![image](https://user-images.githubusercontent.com/8207774/69911559-20e86480-1458-11ea-9d58-729c43243d72.png)

mac系统本地终端：

![image](https://user-images.githubusercontent.com/8207774/69911609-bdab0200-1458-11ea-86b8-5ea688f70de3.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1421
