### ISSUE TITLE
mac下关闭electerm会报错

### ISSUE THREAD

**Issue by mhlywxl** [electerm/electerm#1418]
## Current Behavior

![image](https://user-images.githubusercontent.com/8207774/69911657-a1f42b80-1459-11ea-954c-b21a389db71f.png)

![image](https://user-images.githubusercontent.com/8207774/69911658-a91b3980-1459-11ea-962e-68db6a7cfcd8.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
重复合并 https://github.com/electerm/electerm/issues/1402
