### ISSUE TITLE
怎么禁止更新？？？

### ISSUE THREAD

**Issue by sunzhengbo** [electerm/electerm#1419]
你们这个更新太频繁了，隔了一天就有新的安装包，且只要有新的安装包，不去更新，就会每次打开都会有更新的弹窗出现。这个频繁的有点令人讨厌了，直接点击升级还不能，每次升级都是重新去下载整个安装包，然后解压替换。能否有一个禁止提醒的功能，或者是设置一个时间段，一周或者一月提醒一次这种的。

**Comment by leonunix** [comment]
自动更新是一个玄学。我这里3台里面有1台可以自动更新。奇怪的很。其他都是卡在0%

**Comment by sunzhengbo** [comment]
> 
> 
> 自动更新是一个玄学。我这里3台里面有1台可以自动更新。奇怪的很。其他都是卡在0%

我两台机组都是0%

**Comment by zxdong262** [comment]
@sunzhengbo @leonunix 目前更新的话也就是从github release的地址下载，国内连接可能有时候会有些问题吧。

**Comment by zxdong262** [comment]
@sunzhengbo 感谢反馈，已发布新版本，加入跳过版本按钮

**Comment by sunzhengbo** [comment]
响应效率很高，我也已经更新到最新版本了，但是使用新的版本，没有在设置中看到关闭更新提醒的按钮？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 上午9:20
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] 怎么禁止更新？？？ (#1419)




@sunzhengbo 感谢反馈，已发布新版本，加入跳过版本按钮

**Comment by zxdong262** [comment]
@sunzhengbo 没有关闭提醒设置，而是有一个不再提示这个版本按钮在升级提示面板，下个升级你就会看到了。

**Comment by sunzhengbo** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 下午3:50
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] 怎么禁止更新？？？ (#1419)




@sunzhengbo 没有关闭提醒设置，而是有一个不再提示这个版本按钮在升级提示面板，下个升级你就会看到了。
