### ISSUE TITLE
mac版本相关问题

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1421]
## Electerm version:
0.27.84
## Operating system(linux, macos, or windows7/8/10?):
macOS 10.15.1
## 问题反馈

1. macOS 10.15.1开始系统终端改成了zsh，但是electerm默认还是使用bash打开，建议添加终端环境检查。
2. MacOS10.15下，设置默认bash打开本地终端的话中文打不出来，默认zsh的话，打中文会变成乱码，很影响使用。
3. 建议将默认终端类型改为xterm-256color，xterm-color is really out of date。
4. macOS版本打开时会有一段空窗画面，看起来就像是卡住了一样，不太美观，如果无法优化的话建议添加一个启动图。

**Comment by zxdong262** [comment]
感谢反馈，处理了3，4
