### ISSUE TITLE
UI展示问题

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1430]
## Electerm version:
0.27.89
## Operating system(linux, macos, or windows7/8/10?):
macOS 10.15.1
## 问题反馈
1. 检查更新会在右下角弹出窗口，但是默认的黑色背景会导致这个窗口根本看不到，只有在未选中窗口时的高透明度界面才能看得到右下角出现的弹出窗口，大概通知一类的问题都有这个问题。
2. 当新建连接之后，关闭这个连接并不会自动选择上一个标签，而是会出现两种情况，一种是一个高透明度界面，第二种是选中第一个标签，按正常的交互逻辑应该是关闭当前标签则选中上一标签才对。
3. 打开Electerm之后会默认有一个本地终端的新连接标签页，左上角会有表示状态的颜色点，有时会出现明明终端未断开，却显示红点的情况。
4. 左侧书签交互的话，现在是必须选中三角符号才会展开分类页，个人认为三角符号比较小，不好选中，如果选中文字也能展开的话会更友好。

**Comment by zxdong262** [comment]
@zhengyongtao 高透明度界面是什么，可以发个截图看看吗？

**Comment by zhengyongtao** [comment]
![QQ20191204-104940](https://user-images.githubusercontent.com/23188362/70108269-d21f1280-1683-11ea-935f-d3cecadc48f8.png)
类似这样，或许这是个bug?

**Comment by zhengyongtao** [comment]
当打开多个新连接，并关闭其中一个时，就有概率复现出这个界面。

**Comment by zxdong262** [comment]
@zhengyongtao 确实，我复现了，感谢反馈！

**Comment by zhengyongtao** [comment]
![image](https://user-images.githubusercontent.com/23188362/70109224-304cf500-1686-11ea-808e-dd85d04c076f.png)
还有这种情况，打开终端敲几行字，放一会儿左上角显示状态的点就有几率变为红色，且此时终端并未断开，还可以正常输入并获得反馈。

**Comment by zhengyongtao** [comment]
另再反馈一条，按mac的操作习惯，command+w应该是关闭当前标签页，在Electerm中也即是对应关闭当前连接，但是在Electerm当前的交互command+w变为退出了，这和mac的操作习惯有冲突。

**Comment by fanhua1550** [comment]
![image](https://user-images.githubusercontent.com/30012917/170242160-e582a119-b8d0-4104-8038-4562c0b9df16.png)
左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项

**Comment by zxdong262** [comment]
> ![image](https://user-images.githubusercontent.com/30012917/170242403-e2cedd01-cf77-498a-a246-e537c25b5475.png)
> 
> 左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项

最新版吗？

**Comment by fanhua1550** [comment]
> > ![image](https://user-images.githubusercontent.com/30012917/170242403-e2cedd01-cf77-498a-a246-e537c25b5475.png)
> > 左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项
> 
> 最新版吗？

是最新版本  1.21.57

**Comment by zxdong262** [comment]
> > > ![image](https://user-images.githubusercontent.com/30012917/170242403-e2cedd01-cf77-498a-a246-e537c25b5475.png)
> > > 左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项
> > 
> > 
> > 最新版吗？
> 
> 是最新版本 1.21.57

可以从菜单打开开发者工具看看报错吗

**Comment by fanhua1550** [comment]
> > > > ![image](https://user-images.githubusercontent.com/30012917/170242403-e2cedd01-cf77-498a-a246-e537c25b5475.png)
> > > > 左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项
> > > 
> > > 
> > > 最新版吗？
> > 
> > 
> > 是最新版本 1.21.57
> 
> 可以从菜单打开开发者工具看看报错吗

![image](https://user-images.githubusercontent.com/30012917/170246897-774f4e20-db06-48ed-98fc-b45df1ef8e6c.png)
没有任何信息。

**Comment by zxdong262** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/30012917/170242403-e2cedd01-cf77-498a-a246-e537c25b5475.png)
> > > > > 左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项
> > > > 
> > > > 
> > > > 最新版吗？
> > > 
> > > 
> > > 是最新版本 1.21.57
> > 
> > 
> > 可以从菜单打开开发者工具看看报错吗
> 
> ![image](https://user-images.githubusercontent.com/30012917/170246897-774f4e20-db06-48ed-98fc-b45df1ef8e6c.png) 没有任何信息。

从console里看

**Comment by fanhua1550** [comment]
> > > > ![image](https://user-images.githubusercontent.com/30012917/170242403-e2cedd01-cf77-498a-a246-e537c25b5475.png)
> > > > 左侧一开始安装的时候能显示书签，但是突然就变成这样，也找不到设置项
> > > 
> > > 
> > > 最新版吗？
> > 
> > 
> > 是最新版本 1.21.57
> 
> 可以从菜单打开开发者工具看看报错吗

![image](https://user-images.githubusercontent.com/30012917/170247332-a64bb25e-da78-405f-8a42-dcf0bcd3f80e.png)

**Comment by zxdong262** [comment]
从菜单里刷新看看

**Comment by fanhua1550** [comment]
> 从菜单里刷新看看

![image](https://user-images.githubusercontent.com/30012917/170247927-bf2515b3-da0c-440c-bbee-6909a86c7dc6.png)

**Comment by zxdong262** [comment]
删除C:\Users\Jios\AppData\Roaming\electerm试试

**Comment by fanhua1550** [comment]
> C:\Users\Jios\AppData\Roaming\electerm



> 删除C:\Users\Jios\AppData\Roaming\electerm重新打开electerm试试

问题我已经复现了，传输文件到linux上面，然后点击传输按钮，出来的弹窗，左侧的显示书签栏就会消失，停留在书签按钮上也不会出现信息。

**Comment by zxdong262** [comment]
> > C:\Users\Jios\AppData\Roaming\electerm
> 
> > 删除C:\Users\Jios\AppData\Roaming\electerm重新打开electerm试试
> 
> 问题我已经复现了，传输文件到linux上面，然后点击传输按钮，出来的弹窗，左侧的显示书签栏就会消失，停留在书签按钮上也不会出现信息。

可以截图看看怎么个步骤吗？传输按钮，出来的弹窗是什么？

**Comment by fanhua1550** [comment]
> > > C:\Users\Jios\AppData\Roaming\electerm
> > 
> > 
> > > 删除C:\Users\Jios\AppData\Roaming\electerm重新打开electerm试试
> > 
> > 
> > 问题我已经复现了，传输文件到linux上面，然后点击传输按钮，出来的弹窗，左侧的显示书签栏就会消失，停留在书签按钮上也不会出现信息。
> 
> 可以截图看看怎么个步骤吗？传输按钮，出来的弹窗是什么？

那不是个弹窗，就是传文件到服务器，在传输那个按钮会有个提示，你点击不是有个显示传输文件速度的窗口吗，就是点击了这个，书签按钮停留不出现任何信息。

**Comment by zxdong262** [comment]
> > > > C:\Users\Jios\AppData\Roaming\electerm
> > > 
> > > 
> > > > 删除C:\Users\Jios\AppData\Roaming\electerm重新打开electerm试试
> > > 
> > > 
> > > 问题我已经复现了，传输文件到linux上面，然后点击传输按钮，出来的弹窗，左侧的显示书签栏就会消失，停留在书签按钮上也不会出现信息。
> > 
> > 
> > 可以截图看看怎么个步骤吗？传输按钮，出来的弹窗是什么？
> 
> 那不是个弹窗，就是传文件到服务器，在传输那个按钮会有个提示，你点击不是有个显示传输文件速度的窗口吗，就是点击了这个，书签按钮停留不出现任何信息。

明白了，感谢，下个版本修复，不要点传输按钮，鼠标经过就会显示

**Comment by zxdong262** [comment]
#4ff4ad1d4170c2f4710c05aab25812f87dca73d0

**Comment by fanhua1550** [comment]
> [4ff4ad1](https://github.com/electerm/electerm/commit/4ff4ad1d4170c2f4710c05aab25812f87dca73d0)

收到，谢谢！
