### ISSUE TITLE
MacOS10.15 黑屏

### ISSUE THREAD

**Issue by BYNepenthe** [electerm/electerm#1432]
electerm-0.27.89-mac

macos15

前几天下载后，记不清具体操作什么了，可能是全屏，然后就黑屏了，可能在最上层，其他应用打不开，没办法，只能重启电脑。
刚才，我看今天解决了一些 BUG，就下载了新版本，问题依旧，又重启了电脑。

**Comment by zxdong262** [comment]
试一下 `rm -rf ~/Library/Application\ Support/electerm*`

**Comment by BYNepenthe** [comment]
> 试一下 `rm -rf ~/Library/Application\ Support/electerm*`

不好意思，回复太晚了，试过可以了，应该是这个问题，多谢/:strong
