### ISSUE TITLE
sz有问题

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1435]
## Electerm version:
v0.27.89
## Operating system(linux, macos, or windows7/8/10?):
macOS 10.15.1
## 问题描述
使用sz下载文件会卡在99%

**Comment by zxdong262** [comment]
目前的zmodem 模块不是很可靠，好像大文件都不行，可能需要我自己写一个可靠的zmodem lib

**Comment by zxdong262** [comment]
合并到 #1433 1401

**Comment by lonnywong** [comment]
@zhengyongtao 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
