### ISSUE TITLE
SFTP上传多个文件或者文件夹，部分文件丢失或上传失败，文件未上传完整

### ISSUE THREAD

**Issue by faquir-sun** [electerm/electerm#1441]
## Electerm version:
0.27.89
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

SFTP上传多个文件，或者上传有多个文件的文件夹。有部分文件会上传失败，丢失文件、上传文件大小不正确。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
ref to https://github.com/electerm/electerm/issues/1446
