### ISSUE TITLE
ssh窗口内容复制到excel不是多列

### ISSUE THREAD

**Issue by Aronlele** [electerm/electerm#1449]
## Expected Behavior

在ssh窗口内，对于多行多列数据的复制，到excel中粘贴，应该是多行多列的

## Current Behavior

目前，复制到excel中之后，是一列，并非多列
## Possible Solution

处理一下分隔符

**Comment by zxdong262** [comment]
其他的终端软件同样复制出来是多行多列么？

**Comment by Aronlele** [comment]
> 其他的终端软件同样复制出来是多行多列么？

xshell是的呀

**Comment by zxdong262** [comment]
fixed

**Comment by Aronlele** [comment]
good job

ZHAO Xudong <notifications@github.com> 于2020年10月26日周一 下午9:48写道：
