### ISSUE TITLE
可以更改背景吗

### ISSUE THREAD

**Issue by efaun** [electerm/electerm#1450]
更改背景颜色或者背景图片？

**Comment by zxdong262** [comment]
设置里可以选择图片

**Comment by efaun** [comment]
> 设置里可以选择图片

找到了，不过对于图片分辨率希望可以自适应，对于纯色背景，小分辨率的只是居中在终端里，最好能放大到整个终端

**Comment by zxdong262** [comment]
@efaun 不适合做复杂的图片处理, 但是用户可以自行制作任何图片来配合自行设定的图片。
