### ISSUE TITLE
the tree of bookmarks always appears deployed

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1454]
## Electerm version:
v0.27.89
## Operating system(linux, macos, or windows7/8/10?):
Windows
## Expected Behavior

the bookmarks tree should appear compressed
## Current Behavior

whenever electerm starts, the bookmark tree appears already deployed
![2019-12-13-16_57_21-000636](https://user-images.githubusercontent.com/28075454/70835091-086a3980-1dca-11ea-95a7-fb9250e066c7.jpg)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Hi @saulperez2905 

What if you mannually compact all categories, and restart electerm, the tree still expanded?

**Comment by saulperez2905** [comment]
Yes, when you restart electerm the tree appears again expanded.

 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: domingo, 15 de diciembre de 2019 21:37
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] the tree of bookmarks always appears deployed (#1454)

 

Hi @saulperez2905 <https://github.com/saulperez2905> 

What if you mannually compact all categories, and restart electerm, the tree still expanded?

**Comment by damosse31** [comment]
Hi guys !

I suggest to add expand/collapse buttons in bookmarks list

Waiting to take it if i'ts ok for you.
