### ISSUE TITLE
建议增加日志记录的功能

### ISSUE THREAD

**Issue by yayaysya** [electerm/electerm#1456]
建议增加日志记录的功能
找了一圈， 发现你的工具做的真的很棒！但是还有一点希望能完善。 日常工作中需要增加记录日志， xshell和secruecrt都有完善的ssh日志记录功能。 
如果可以的话， 希望能添加下。 
谢谢！

**Comment by zxdong262** [comment]
感谢反馈！我完全没想到这个。

**Comment by zxdong262** [comment]
@yayaysya 可以帮助提供log的样例吗

**Comment by lain-github** [comment]
同样的需求 #1636

**Comment by qiuhaining** [comment]
问一下，现在有记录日志功能了吗？
