### ISSUE TITLE
Control+Shift+C is not working

### ISSUE THREAD

**Issue by cypherbits** [electerm/electerm#1459]
On Windows 10 or Ubuntu: selecting a text on the terminal and pressing Control+Shift+C is not working. Clicking copy on the context menu is ok.
Control+Shift+V for pasting is working fine.

**Comment by zxdong262** [comment]
As I test, do not work in win 10, but works in Ubuntu

**Comment by cypherbits** [comment]
Ubuntu 19.10 + master branch is not working for me...

**Comment by zxdong262** [comment]
@cypherbits Oh, I tested in Ubuntu 18.04, seems a tricky problem

**Comment by damosse31** [comment]
Hi there !

normally, the PR #1490 I just sent fix this issue. Tested on my side with Ubuntu 18.03

Will see...
