### ISSUE TITLE
希望可以完善更换字体的功能

### ISSUE THREAD

**Issue by PigPigZzz** [electerm/electerm#1461]
希望可以完善修改字体，因为使用YCM插件的时候会出现乱码，得使用Droid Sans Mono字体，但客户端不知道该怎么修改。希望开发大大能完善一下这个功能，可以自行添加字体等功能

**Comment by zxdong262** [comment]
设置里有默认自体选项，你可以试试

**Comment by PigPigZzz** [comment]
> 
> 
> 设置里有默认自体选项，你可以试试

我用的是Linux版本，我知道设置里面有字体选项，但设置里面让我自己填写字体名称，我不知道该怎么填写

**Comment by zxdong262** [comment]
https://www.ostechnix.com/find-installed-fonts-commandline-linux/
看看这个，我觉得列表里
> /usr/share/fonts/TTF/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book

`DejaVu Sans`就是要填写的字体名字，可以试试

**Comment by PigPigZzz** [comment]
> https://www.ostechnix.com/find-installed-fonts-commandline-linux/
> 看看这个，我觉得列表里
> 
> > /usr/share/fonts/TTF/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book
> 
> `DejaVu Sans`就是要填写的字体名字，可以试试

谢谢开发大大的帮助，解决了我的问题。非常喜欢这个程序，希望这个程序做的越来越好，这个字体我还是建议做一个下拉拦，更加方便

**Comment by zxdong262** [comment]
> > https://www.ostechnix.com/find-installed-fonts-commandline-linux/
> > 看看这个，我觉得列表里
> > > /usr/share/fonts/TTF/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book
> > 
> > 
> > `DejaVu Sans`就是要填写的字体名字，可以试试
> 
> 谢谢开发大大的帮助，解决了我的问题。非常喜欢这个程序，希望这个程序做的越来越好，这个字体我还是建议做一个下拉拦，更加方便

谢谢反馈~有道理，我看看怎么实现这个

**Comment by shuncon** [comment]
怎么设置字体颜色
