### ISSUE TITLE
order in selection of categories and subcategories

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1463]
## Electerm version:
v0.27.89
## Operating system(linux, macos, or windows7/8/10?):
Windows
## Expected Behavior

The list of categories when creating a bookmark are all at the same level and in disarray.
## Current Behavior

When choosing a category, it should show the category and subcategory as shown in the main bookmarks tree
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Hi @saulperez2905 
Can you provide more detail about this, I do not understand it.

**Comment by saulperez2905** [comment]
Hi

I describe what happened.

In the creation of bookmarks, when a category and / or subcategory is assigned, it appears in disorder, the same tree is not observed as when they are already created.

 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: martes, 17 de diciembre de 2019 18:25
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] order in selection of categories and subcategories (#1463)

 

Hi @saulperez2905 <https://github.com/saulperez2905> 
Can you provide more detail about this, I do not understand it.

**Comment by zxdong262** [comment]
@saulperez2905 I get it, thank you!
