### ISSUE TITLE
SFTP:Throw  error   “No such file“

### ISSUE THREAD

**Issue by 976546460** [electerm/electerm#1464]
## Expected Behavior
SFTP should open this directory!

## Current Behavior
```
No such file
Error: No such file
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.0.27.89-6d7466726fb2e235da9d8c81502332de557cf4ab.js:25:196878
    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.0.27.89-6d7466726fb2e235da9d8c81502332de557cf4ab.js:25:154584

```
## This is a screenshot.

<img width="1166" alt="屏幕快照 2019-12-18 下午7 06 14" src="https://user-images.githubusercontent.com/29286699/71081174-a8103900-21c9-11ea-9318-88b61b59e0a1.png">

## Possible Solution
The "." character exists in my server directory. I don't know if it's caused by this!

**Comment by zxdong262** [comment]
@976546460 Can you provide the file path in the screenshot?

**Comment by 976546460** [comment]
> @ 976546460可以在屏幕截图中提供文件路径吗？

I found the reason. There is a wrong soft connection in the path to be opened. Thank you for your help
