### ISSUE TITLE
最新版本 v0.27.96 有不少bug

### ISSUE THREAD

**Issue by kexirong** [electerm/electerm#1467]
1. 终端的单行输出溢出时会有部分不显示
2. 不会根据窗口调整后调整 ssh协议的tty 的size

**Comment by kexirong** [comment]
更新了 快速修复版本 问题还是存在 @zxdong262 
![image](https://user-images.githubusercontent.com/31177595/71168832-8b8c0380-2292-11ea-99cf-c95e798eaadb.png)

**Comment by zxdong262** [comment]
复现不了，可以提供更多的信息吗，操作系统，更多的截图

**Comment by kexirong** [comment]
当时操作系统用的Debian10，远程是centos8，这个问题多截图也体现不出，猜测是tty窗口尺寸控制跟输出渲染上的问题，发生溢出时结尾多了个`>`符号

**Comment by kexirong** [comment]
@zxdong262 这个好像不是et的问题，我刚刚尝试使用 系统自带的终端ssh 过去，也存在这个问题，应该是centos 8 的问题
