### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1472]
## Electerm version:
v0.27.97
## Operating system(linux, macos, or windows7/8/10?):
macOS 10.15.2
## Expected Behavior
1. 更新有问题，基本不能工作，一直卡在0%
2. 建议添加复制当前连接快捷键，比如command+r，现在的command+r是直接重启整个软件，不太合理，chrome本来的command+r也仅仅是刷新当前标签页。
3. 添加书签的时候，拖动一下窗口，添加窗口就自动关闭了。。。要了命了

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1471

**Comment by liushan150** [comment]
在window系统下 ctrl+f快捷键与linux命令行 前移快捷键 冲突.希望有设置的快捷键的地方可以替换其他键位

**Comment by zxdong262** [comment]
下个版本提供快捷键设置，就可以自行设定为其他组合了
