### ISSUE TITLE
希望增加telnet客户端功能，连堡垒机2分钟就会超时

### ISSUE THREAD

**Issue by bianyifeng** [electerm/electerm#1491]
1. 希望增加telnet客户端功能
2. ssh 连接堡垒机的时间2分钟就会超时断开，连非堡垒机的ssh 没问题

以下为日志
[2020-01-01 19:06:48.843] [error] Error: Keepalive timeout
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.0.1-e37bef11a9c55e635d9e4cdb04f96a55846e916a.js:19:202101
    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.0.1-e37bef11a9c55e635d9e4cdb04f96a55846e916a.js:19:159637)

**Comment by zxdong262** [comment]
https://github.com/mscdex/ssh2/issues/367

**Comment by bianyifeng** [comment]
@zxdong262 补充一下，非书签连接的堡垒机SSH 没有超时退出，好像只有书签打开的堡垒机SSH 才会超时退出

**Comment by zxdong262** [comment]
@bianyifeng 非书签连接的SSH实际就是用bash运行ssh

**Comment by hope250** [comment]
最近在试用阿里云的堡垒机，这个问题确实是存在的，特别是SFTP，问题比较大，干脆拉不到任何目录信息。
