### ISSUE TITLE
希望能优化一下书签展示

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1501]
## Electerm version:
v1.0.7
## Operating system(linux, macos, or windows7/8/10?):
macOS 10.15.2
## Expected Behavior

当前的书签展示存在以下几个问题：
1. 最多只能有两个层级，往加分类就分不了了
2. 当书签量大的时候（目前我只添加了50台主机左右），书签展示就变得异常卡
3. 同上面的问题，书签数量多了以后，由于分类最多两层，所以找书签就变得很不直观
4. 针对单个书签进行编辑十分不方便，要先点击编辑书签，然后找到具体书签，再进书签详情页里进行编辑，能不能简化成在左侧书签栏右键编辑即可针对单个书签进行编辑？

**Comment by zxdong262** [comment]
可以试试最新版
