### ISSUE TITLE
快捷键问题：切换多个标签页、清空当前屏命令

### ISSUE THREAD

**Issue by feeltens** [electerm/electerm#1504]
## Electerm version
1.0.7

## Operating system
macOS 10.15.2

## Detailed Description

在使用 electerm 中，遇到了一些快捷键问题，如下：
1. 切换多个标签页，现在只能手动点击每个标签来完成切换，不能 `Ctrl + Tab` 逐个切换，或者也可以参考 Chrome 浏览器的 Ctrl + num 切换到不同的标签；
2. 之前在使用 iTerm 时，习惯了 `Command + R` 是 clear ，即清空当前屏命令。但在配置快捷命令时，始终没能成功，都是刷新了页面，然后连接全没了。

**Comment by zxdong262** [comment]
----> https://github.com/electerm/electerm/issues/1508
