### ISSUE TITLE
[Bug] 分割窗口的按钮问题

### ISSUE THREAD

**Issue by Seraphli** [electerm/electerm#1518]
分割窗口的按钮本来的排序是: 纵向, 横向
但是在第一次点击横向的时候, 图标会调换一下, 然后不会有任何分割的窗口
然后第二次点击之后才会有对应的分割窗口出现.

**Comment by zxdong262** [comment]
第一个按钮是分割，第二个是切换纵横放向

**Comment by Seraphli** [comment]
这样的吗...那如果要横向分割...就是一定要点击第二个然后再点第一个才能做到么

**Comment by zxdong262** [comment]
> 这样的吗...那如果要横向分割...就是一定要点击第二个然后再点第一个才能做到么

这个有兴趣你自己研究吧，一共就俩按钮。
