### ISSUE TITLE
Common keyboard-interactive solution

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#1526]

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1599

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1520

**Comment by davidxujiayang** [comment]
请问一下之前几个关闭的问题是合并到这里表示解决了么？之前在1520下回复的问题今天更新到最新版本还是存在。

**Comment by zxdong262** [comment]
这个issue没有关闭代表没有解决 @davidxujiayang

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/a06805ec9dc1ca8bfb1be14e4501a5d5f417ecdb done
