### ISSUE TITLE
szrz的时候rz的时候选择取消后会返回用户主目录

### ISSUE THREAD

**Issue by MrYangyt** [electerm/electerm#1533]
在使用szrz的时候，rz的时候选择取消后会返回用户主目录，并不是返回我rz之前的目录。还有一个建议，rz的时候那个选项上传，取消感觉有点多余，不如xshell那样直接选文件，因为选文件的时候也可以取消。

**Comment by zxdong262** [comment]
目前的zmodem module没有取消这个功能，所以取消就只能刷新这个连接。

**Comment by zxdong262** [comment]
goto -> https://github.com/electerm/electerm/issues/1401

**Comment by lonnywong** [comment]
@MrYangyt 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
