### ISSUE TITLE
[Feature Request] 一些外观,交互,和小功能建议

### ISSUE THREAD

**Issue by lkqm** [electerm/electerm#1535]
## Detailed Description

1. [bug]: 在macos上操作菜单和系统默认: 关闭, 最小化重复
![image](https://user-images.githubusercontent.com/20638840/72680680-a521a480-3af7-11ea-96d4-6998611f846d.png)

## Suggestions?

1. 希望能内置几套主题配色, 我很难配置出像默认主题那样好看的主题
2. 移除掉终端中默认的“electerm"背景图, 它虽然看起来很酷, 但是会让人分心
![image](https://user-images.githubusercontent.com/20638840/72680731-1a8d7500-3af8-11ea-99a9-80d44818f266.png)
3. 移除掉左侧"主题设置"的快捷菜单, 对于"设置菜单"显的有些冗余

**Comment by zxdong262** [comment]
1. 你的macos 什么版本？
2. 可以设置一个黑色背景图替换掉默认背景

**Comment by lkqm** [comment]
1. macos catalina 10.15.2
2. 是可以通过替换图片实现, 不过其实期望的功能就是没有背景图
