### ISSUE TITLE
无法取消设置系统快捷键

### ISSUE THREAD

**Issue by Seraphli** [electerm/electerm#1547]
##  Electerm version:
v1.0.23

## Operating system(linux, macos, or windows7/8/10?):
macos

## Current Behavior
无法取消系统快捷键ctrl+2的设置, 也无法将其设置为其他快捷键, 在后面的2中点击下拉菜单里面是空的, 在上面输入任何键都会显示no data然后回到2.
![image](https://user-images.githubusercontent.com/1586755/73820327-76f8d000-482c-11ea-8808-cc9823cffad8.png)

**Comment by zxdong262** [comment]
发布了新版本，修复了这个问题，感谢反馈

**Comment by Seraphli** [comment]
好的
