### ISSUE TITLE
compatibility with toxsocks

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1549]
## Electerm version:
1.0.19
## Operating system(linux, macos, or windows7/8/10?):
RHEL7.7
## Expected Behavior

connect to my servers clients using toxsocks proxy.
## Current Behavior

nothing, electerm not connected
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
@saulperez2905 Can you provide more detail?

**Comment by saulperez2905** [comment]
In my work we use toxsocks as a proxy to connect to servers.

electerm is added to toxsock with the app allowed, however the connection to the servers cannot be made. It was tested with putty and works normally

![image](https://user-images.githubusercontent.com/28075454/74049035-4d14ea00-49a1-11ea-89b1-963229561552.png)

**Comment by saulperez2905** [comment]
execute: toxsocks electerm

![image](https://user-images.githubusercontent.com/28075454/74049302-da583e80-49a1-11ea-900b-ffbcab1e0921.png)

**Comment by saulperez2905** [comment]
and view new issues

[sperez@oc1178881380 ~]$ electerm
Gtk-Message: 12:10:07.269: Failed to load module "pk-gtk-module"
Gtk-Message: 12:10:07.273: Failed to load module "pk-gtk-module"
12:10:07 › error parsing $HOME/.ssh/config
12:10:07 › maybe no $HOME/.ssh/config, but it is ok
12:10:07 › no ../../install-src file
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
12:10:07 › App starting...
12:10:07 › no /home/sperez/snap/electerm/x2/.config/electerm-config.js but it is ok
[12366:0207/121007.673378:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
12:10:07 › no ../../install-src file
12:10:07 › server runs on localhost 3075
12:10:09 › Created terminal with PID: rNgBE3_1
12:10:09 › Connected to terminal rNgBE3_1
12:10:09 › Resized terminal  rNgBE3_1  to  153  cols and  34  rows.
12:10:16 › close app
12:10:16 › close app
[sperez@oc1178881380 ~]$

**Comment by zxdong262** [comment]
I really want to look into this, but I can not even google toxsocks for its document, no result for that, any suggestions? anywhere I can find docs about how it works? Does it provide mannually proxy method, like give a proxy addr like sock5://127.0.0.1:xxxx?

@saulperez2905

**Comment by saulperez2905** [comment]
hi
@zxdong262 
Overview
SOCKS is a protocol that allows you to access hosts on the other side of a firewall. A SOCKS server either allows or rejects connection requests, based on the requested internet destination or user identification. After a connection and a subsequent bind request have been set up, the flow of information exchange follows the usual protocol, i.e., HTTP. It secures privacy by hiding your IP address.

Use the Toxsocks Socks Client to socksify a remote host connection to a customer site from your Linux computer. Toxsocks only runs on the Linux,  not in a Windows Kernel Virtual Machine (KVM).

Install Toxsocks
Toxsocks requires two packages :

ibm-config-toxsocks
toxsocks
Important: These are 64-bit packages. There is also a 32-bit version of toxsocks. Don't install both.

Installation Process
To install the Toxsocks client:

To start the installation click Activities and type tox in the search field. Click the toxclient icon.

The application installer starts. Click Install to install the required software packages.

After the installation completes, click Activities and type tox in the search field again. You're now ready to either configure or start the ToxClient.

Alternative Install Option via Command Line
Alternatively you can install toxsocks via the command line. To install from a command line, open a Terminal window and type:
     sudo yum install toxsocks  ibm-config-toxsocks

Confirm the Installation
You can use Add/Remove Software to confirm that the software is installed. If selected with a check mark, it's installed.

You can also confirm what packages are installed with a command, which also provides details in the terminal screen. Type:

     rpm -qi toxsocks ibm-config-toxsocks

Launch Toxsocks
To launch the client, click Activities on the Dash to Dock and type socks. Click the client to launch it.



The first time you launch the client, you're asked if you want to integrate Toxsocks with Citrix. Click Install.

When it launches, the Toxsox Management Tool opens.



Note: If the Socks Client doesn't show up when you search for it, you might need to log out and log back in.

Profiles and Applications
You must configure the Toxsocks client on your PC before using it. If you have a preconfigured profile, you don't have to configure it manually.

Some markets, countries, and accounts maintain a common configuration file that supports all of the customers in that market or account. The Global Service Network Infrastructure (GSNI) profiles are dynamically imported from both US and Brazil GSNI websites.

If you're a member of one or more of these subcommunities, check in the GSNI profiles listed here for a shared SOCKS profile that you can use. 
Create a GSNI Connection
To configure a GSNI connection:

Click Profiles and then "Import from GSNI Sites."
Select the country (Brazil or United States).
Select a profile. If you would like to import more than one profile, hold down the control key and select any number of them. When selecting only one profile to import, you can find the name of it by just typing in the name.
When finished, select "Import all selected profiles."

When asked to confirm, click Close. A message confirms that the profiles imported successfully.


Click Close again, unless you have more profiles to import.
For non-GSNI sites, select Profiles, Add New, fill in the information needed to connect to the server, and select Save.

Notes:

In the following example screenshot, two profiles are imported, one for Coca Cola, and another for BNSF Railway. By default, you don't need to edit these profiles, unless you need to add credentials.
Each profile appears with a row of associated icons.

Available Socksified Applications for Each Profile
After starting the Socks Client, a set of icons displays under the profile name (e.g., BSNF Railway). These applications have been associated with the Socks Client.

This list is dynamically built and only displays those applications you have installed. The example displays the applications for BNSF Railway.

Terminal: A socksified terminal can be used to launch socksified applications or connect to a host in a more traditional way, telnet, SSH, or FTP.
If you launch a terminal session, you can use it to start other socksified applications.
Firefox: Enables socksified web use.
Remmina: A Windows terminal server, VNC, SSH and more
SAPGUI.
TS Client: A Windows terminal server and more.
RDesktop: A remote desktop takeover tool.
PuTTY: A common terminal application used for Telnet and SSH.
TigerVNC Viewer: A commonly used VNC connection tool.
Edit Profile.
Delete Profile.


Move the mouse over an icon to get a description of the application.

If you want to add an application to ToxSocks that isn't in the list:

Shut down ToxSocks.
Install the application and filter on the name (e.g. remmina).
Launch ToxSocks again. This refreshes the list of available applications.
Edit a Connection/Profile
After you have one or more profiles imported, click the Edit button of a profile to confirm the configuration. If you need to enter a username and password, do it here and click Save.



Create a New Profile
To create a new profile:

From the Toxocks Profiles menu, select Add New.
The source where you want to connect should provide you with connection information. Fill in the form with this Socks information.
Server Name
Server IP
Port
Server Type
Default Username
Default Password


Click Save.
You've added a new profile, and you can now launch it.

Launch a Profile/Connection
You can launch a profile or connection by selecting one of the tools listed under the name of the GSNI profile where you want to connect.

Location of Profile Configuration Files
Your configuration is stored in your home folder under .toxsocks. When navigating using Nautilus (File Browser), select View, and then Show Hidden Files.

Create a Connection Using Firefox
You can create a socksified connection using Firefox:

Start Toxsocks, locate the GNSI site where you want to connect, and then start Firefox.
Enter the URL, and click "Run application." The IP address is typically used. If you want to use the host names for the remote sites, you  must create and maintain a hosts file in Linux.

When Firefox launches, it uses your default account, or you must create a new profile.

Firefox now launches and starts the socksified connection to your remote account.

Always launch the URL from toxsocks by clicking the Firefox icon, or launch Firefox from a socksified Terminal window.

**Comment by saulperez2905** [comment]
Hi any update?

**Comment by zxdong262** [comment]
Not yet @saulperez2905

**Comment by saulperez2905** [comment]
hi @zxdong262  could you get any progress with toxsocks?
When I use Putty, since toxsocks this works fine.
Another tool that I have used with toxsocks is "PAC Manager". but in PAC if there is an additional configuration to be made in each session created.
![ksnip_20200322-231721](https://user-images.githubusercontent.com/28075454/77280862-84123700-6c93-11ea-94df-a6e866fec962.png)

**Comment by zxdong262** [comment]
@saulperez2905 No pregress yet, seems more issues than I can handle, may take a while to do this.

**Comment by zxdong262** [comment]
Seems no need to do this, since electerm now can set proxy in settings
