### ISSUE TITLE
brake execute nodejs expresss in port 3000

### ISSUE THREAD

**Issue by Paul75** [electerm/electerm#1551]
## Expected Behavior
When launch my application nodejs (server) with express on port 3000, Electerm launch it but with 3075 port ..... On mac it not do this problem ...

## Steps to Reproduce
When launch my application nodejs (server) with express on port 3000, Electerm launch it but with 3075 port ..... On mac it not do this problem ...

## Context (Environment)
It produce in Windows, not Mac.

Thanks

**Comment by zxdong262** [comment]
Can you give more detail? I do not understand what is the issue.

**Comment by Paul75** [comment]
Hello,

I use server node and in windows when start on port 3000 not give error bug start with the port 3075 not 3000 like I write in the code .....

**Comment by zxdong262** [comment]
Can you post your code here?

**Comment by Paul75** [comment]
Hello,

I can't give my code of project but I test with the code what I start and same problem.

My project start with : https://github.com/w3tecch/express-typescript-boilerplate

Thanks

**Comment by zxdong262** [comment]
Thank you for the feedback, will release new version that fix it(in 30 minutes).
