### ISSUE TITLE
[Password Length] 40 chars max

### ISSUE THREAD

**Issue by TheWanderingCoel** [electerm/electerm#1552]
记得挺早之前的版本可以用128位的密码，最近在windows上显示不能超过40chars。现在只能使用ssh命令去连接服务器了。

## Electerm version:
v1.0.24

## Operating system(linux, macos, or windows7/8/10?):
Windows 10

## Expected Behavior

No error generated

## Current Behavior

40 chars max

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
感谢反馈，将在下一个版本修复（30分钟内）

**Comment by TheWanderingCoel** [comment]
> 感谢反馈，将在下一个版本修复（30分钟内）

感谢作者大佬
