### ISSUE TITLE
last version 1.0.26 not see prompt in windows

### ISSUE THREAD

**Issue by Paul75** [electerm/electerm#1556]
## Expected Behavior

Not see the prompt of command. Seee screen

![image](https://user-images.githubusercontent.com/457062/74154483-03cbd100-4c13-11ea-985b-16ed71ac9269.png)

Thanks

**Comment by zxdong262** [comment]
I can not reproduce this problem, can you check the log and post logs here?
![5G6VBLVTJOAS9V6PQF5GAWS](https://user-images.githubusercontent.com/1641949/74157016-7c05b700-4c52-11ea-9a6d-a1edea2fac69.png)

**Comment by zxdong262** [comment]
Oh, I know it, press enter, it will work

**Comment by Paul75** [comment]
yes

[2020-02-10 15:24:07.254] [error] fs error ENOENT: no such file or directory, open 'C:\Users\pkbp512\AppData\Roaming\electerm\log.old.log'


But why press enter on all time when open ?

**Comment by zxdong262** [comment]
@Paul75 It is a bug, I will fix it in next release

**Comment by zxdong262** [comment]
Should fix now, you can try it

**Comment by Paul75** [comment]
Works Thanks

**Comment by Paul75** [comment]
Hello,

Works only  when open program. But not when open new tabs or slip horizontally or vertically ...

**Comment by zxdong262** [comment]
@Paul75 Fixed with new release, thank you.

**Comment by Paul75** [comment]
Hello,

Sorry but I update today to the last and got back the error again when lanching or open new tabs or split ...

![image](https://user-images.githubusercontent.com/457062/74417222-a61fca80-4e46-11ea-91d7-e70741025b7b.png)

**Comment by zxdong262** [comment]
@Paul75 You are right

**Comment by zxdong262** [comment]
@Paul75 Sorry, I failed to find a proper way to handle it. it might need more time to fix.
