### ISSUE TITLE
DSA算法生成私钥登录报错

### ISSUE THREAD

**Issue by lumingdong** [electerm/electerm#1561]
connection fails: Error while signing data with privateKey: error:06000080:public key routines:OPENSSL jnternal:UNSUPPORTED_ ALGORITHM

**Comment by zxdong262** [comment]
pubkey开头是什么样的 ssh-xxxx? @lumingdong

**Comment by lumingdong** [comment]
@zxdong262 公钥开头是ssh-dss，私钥是-----BEGIN DSA PRIVATE KEY-----

**Comment by zxdong262** [comment]
@lumingdong 推荐使用 ECDSA
DSA: It’s unsafe and even no longer supported since OpenSSH version 7, you need to upgrade it!
https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54
