### ISSUE TITLE
【问题反馈】非书签的rzsz上传下载功能不可用

### ISSUE THREAD

**Issue by bianyifeng** [electerm/electerm#1568]
非书签的rzsz上传下载功能不可用

**Comment by bianyifeng** [comment]
是否考虑增加一个zmodem协议的 rzsz 上传下载功能，因为堡垒机的原因无法使用SCP,经常会用到这个rzsz 上传下载。

**Comment by zxdong262** [comment]
非书签情况就是调用本机的终端，其支持情况取决于本地终端，不会对这个提供支持了。

**Comment by lonnywong** [comment]
@bianyifeng 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
