### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1579]
## Electerm version:
v1.0.31
## Operating system(linux, macos, or windows7/8/10?):
MacOS 10.15.3
## Expected Behavior

1. 更新用不了了，目测是域名被墙了
2. sftp功能基本凉凉，什么文件都传不上去，直接卡0%

**Comment by bianyifeng** [comment]
@zhengyongtao 1. 域名应该已经恢复了，我这边是可以了，昨晚就可以了

**Comment by zhengyongtao** [comment]
![image](https://user-images.githubusercontent.com/23188362/75602501-e8146600-5b00-11ea-8ed0-099651856726.png)
那应该是业务问题了，目前检查更新会报错
