### ISSUE TITLE
Error: No Such File in jump server

### ISSUE THREAD

**Issue by ShingmoYeung** [electerm/electerm#1590]
## Electerm version:
v1.0.33
## Operating system(linux, macos, or windows7/8/10?):
MacOS 10.15.3
## Expected Behavior

通过跳板机访问时报如下，进入跳板机即报
Error: No Such File
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.0.33-51317d2f6f5200b2781d11ad8e83a130b21c11f7.js:19:203345
    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.0.33-51317d2f6f5200b2781d11ad8e83a130b21c11f7.js:19:160404)
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
使用其他终端进入跳板机的默认路径是什么？

**Comment by sguphil** [comment]
i found this error message too, what does it mean ?

**Comment by zxdong262** [comment]
@sguphil Could be error finding a proper init path for login.

**Comment by sguphil** [comment]
any clue to solve this issue?

**Comment by zxdong262** [comment]
@sguphil A possible situation is that jump servers have special entry path, I do have a jump server, can not test to confirm.

**Comment by ShingmoYeung** [comment]
我们用的跳板机是基于开源的一个，进去标题是Welcome to use Jumpserver open source fortress system，看看是否有帮助

**Comment by zxdong262** [comment]
@ShingmoYeung 谢谢，我会试试

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1602

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1607

**Comment by chenrizhi** [comment]
你好，我提供一个Jumpserver官网提供的一个体验地址，希望对你有帮助。
地址：134.175.107.119
端口：2222
账号：test
密码：test01

**Comment by zxdong262** [comment]
@chenrizhi 多谢，不过不要发在这里啊，可以给我发个邮件，zxdong@gmail.com, 我先删除了。

**Comment by zxdong262** [comment]
@chenrizhi 我试了官网那个，可以连接，并没有报错？也许跟你的真实跳板机有不一样的地方？我会加一个初始目录设置，也许这个可以解决。

**Comment by chenrizhi** [comment]
v1.3.21版本还存在此问题。

**Comment by chenrizhi** [comment]
新版本已经不存在此问题了。

**Comment by passionings** [comment]
![image](https://user-images.githubusercontent.com/67681222/115385092-4e2ee180-a20a-11eb-89b1-3e06892ecdc7.png)

官网下载的Mac最新版，公司使用的jumpserver，每次打开都提示下面这两个错误：
Error: Unable to exec
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.15:2:387761
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.15:2:321009)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.15:2:321939

Error: Failure
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.15:2:387761
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.15:2:321009)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.15:2:321939)
