### ISSUE TITLE
ubuntu19.10 使用electerm 字体间距问题

### ISSUE THREAD

**Issue by dai19470** [electerm/electerm#1598]
## Electerm version:
v10.2.0
## Operating system(linux, macos, or windows7/8/10?):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
## Expected Behavior

打开electerm终端，字体间距太大了，
![image](https://user-images.githubusercontent.com/21135250/76142706-04894300-60ab-11ea-8548-69bc319218b8.png)

## Possible Solution

可能是字体问题，但是不确定是什么字体导致的。修改了electerm 的默认字体为：
Ubuntu Regular,Sans Regular, monospace
但是没有起作用。

**Comment by zxdong262** [comment]
可以试试升级到最新版以及其他字体吗？放在最前面优先生效

**Comment by zxdong262** [comment]
没有进一步的信息，关闭，有新的反馈欢迎再打开

**Comment by wmailn** [comment]
1.21.14版本有此问题，不知道如何解决，间距过大

![image](https://user-images.githubusercontent.com/4081554/162649550-062b515e-0d82-4c46-ba70-a3ee60fef951.png)


![image](https://user-images.githubusercontent.com/4081554/162649523-7abcf4e7-325e-4573-96e1-6b46237ff553.png)
