### ISSUE TITLE
how to open search dialog when paste when right click

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#1606]
## What happen
when "paste when right click" is enabled, no other way to open search dialog to search keyword in history?

## Expected Behavior
please provide a edit menu or kind of staff to click and open the search dialog? or some kind of hotkey?

**Comment by sguphil** [comment]
By the way, how to use the "select All" when "paste when right click" is enabled ? please help, thanks

**Comment by zxdong262** [comment]
Should be ctrl + F as other ternimal's shortcut

**Comment by zxdong262** [comment]
And `Ctrol + A` to select all

**Comment by sguphil** [comment]
> 
> 
> And `Ctrol + A` to select all

i have tried, this is not work

**Comment by zxdong262** [comment]
Now has a search icon
