### ISSUE TITLE
每次连接会报的错

### ISSUE THREAD

**Issue by gefule** [electerm/electerm#1607]
No such file or directory
Error: No such file or directory at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.2.2-42a49cbb715fa4391eb9118c1577bc8e47122c5c.js:19:414932 at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.2.2-42a49cbb715fa4391eb9118c1577bc8e47122c5c.js:19:371960

![image](https://user-images.githubusercontent.com/20297369/76861839-2a2aff00-6898-11ea-8926-e29acbfc6729.png)
大家有没有遇到过帮忙看下

**Comment by gefule** [comment]
还有这个
Error: Unable to start subsystem: sftp
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.2.2-42a49cbb715fa4391eb9118c1577bc8e47122c5c.js:19:414932
    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.2.2-42a49cbb715fa4391eb9118c1577bc8e47122c5c.js:19:371960)

**Comment by zxdong262** [comment]
连接什么样服务器呢，认证方式？可以提供更多的信息吗？

**Comment by gefule** [comment]
公司内网的堡垒机

**Comment by zxdong262** [comment]
大概跟这个一样 --> https://github.com/electerm/electerm/issues/1590

**Comment by bianyifeng** [comment]
关闭SFTP,很快就会断开，日志报错[2020-06-22 10:21:38.504] [debug] socket closed, pid: bW9__G_yq

**Comment by zxdong262** [comment]
有可能是跳板机有特别的设定，得验证一下 @bianyifeng
