### ISSUE TITLE
Log file path when no file err

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#1608]

**Comment by gefule** [comment]
When using the "rz", "sz" command to upload a file, clicking the cancel button will close the entire window and reconnect, instead of canceling the upload of the file, please look at this problem, thank you

**Comment by zxdong262** [comment]
@gefule It is a know issue, due to the zmodem module electerm use do not support cancel, seem can not be resolved soon.

**Comment by gefule** [comment]
thank you

**Comment by gefule** [comment]
运行脚本 不回显是怎么回事

**Comment by zxdong262** [comment]
@gefule 如果用其他终端也是同样的情况吗？
