### ISSUE TITLE
内存占用高

### ISSUE THREAD

**Issue by sunzhengbo** [electerm/electerm#1609]
![image](https://user-images.githubusercontent.com/29298020/77029286-3ddc7f80-69d6-11ea-8a32-7931a97bc463.png)
内存占用太高了，这个可以优化吗？

**Comment by zxdong262** [comment]
估计有内存泄漏。

**Comment by zxdong262** [comment]
不是刚运行就占用这么多吧？

**Comment by sunzhengbo** [comment]
这个怎么处理，都快近1G的运行内存了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHAO&nbsp;Xudong"; 
发送时间: 2020年3月19日(星期四) 中午12:39
收件人: "electerm/electerm";
抄送: "sunzhengbo";"Author";
主题: Re: [electerm/electerm] 内存占用高 (#1609)





 
估计有内存泄漏。
 
&mdash;

**Comment by zxdong262** [comment]
哦不对我看错了，还以为是8000M

**Comment by sunzhengbo** [comment]
800多M也不算少了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 中午12:41
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] 内存占用高 (#1609)





 
哦不对我看错了，还以为是8000M

**Comment by sunzhengbo** [comment]
只开了一个ssh




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 中午12:40
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] 内存占用高 (#1609)





 
不是刚运行就占用这么多吧？

**Comment by zxdong262** [comment]
估计也优化不了多少，毕竟基于Electron。

**Comment by zxdong262** [comment]
主要问题倒不是内存占用，更大的问题是在windows下性能不行，电脑差一点会感觉卡。

**Comment by sunzhengbo** [comment]
哦哦，好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 中午12:45
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] 内存占用高 (#1609)





 
估计也优化不了多少，毕竟基于Electron。
