### ISSUE TITLE
书签导入导出数据混乱

### ISSUE THREAD

**Issue by Refuel-ZL** [electerm/electerm#1610]
## Electerm version:
v1.2.2
## Operating system(linux, macos, or windows7/8/10?):
linux
## Expected Behavior

书签导出后能够完整（包括结构）导入
## Current Behavior

书签导出后json 再次导入时 结构混乱
## Possible Solution

无
## Steps to Reproduce

1.导出书签
2.导入书签
3.书签结构混乱了
4.

## Detailed Description

书签也尝试清空所有 再导入之前导出的json文件书签，也是混乱了

**Comment by Refuel-ZL** [comment]
把json文件分内容写到github 再下载设定在正常了

**Comment by zxdong262** [comment]
OK,那关闭了
