### ISSUE TITLE
mac版外接显示屏把窗口拖到显示屏无法最大化

### ISSUE THREAD

**Issue by gefule** [electerm/electerm#1611]
拖到显示屏后只能拉着窗口放大缩小，无法通过最大化，或者单击上面最大化窗口

**Comment by sguphil** [comment]
linux centos8, virtualbox.  got this issue too. please help to check, thanks

**Comment by lifei6671** [comment]
我也是Mac，在外接显示屏中，只能点击最大化按钮最大化，双击标题栏没办法最大化。

**Comment by zxdong262** [comment]
最新版已修复
