### ISSUE TITLE
Lose config when reload or restart

### ISSUE THREAD

**Issue by bianyifeng** [electerm/electerm#1614]
mac 更新1.30版本后，配置无法保存，重启后恢复默认状态，完全卸载后重装问题依旧

mac os 10.15.3 版本

**Comment by zxdong262** [comment]
可以在命令行运行`/Applications/electerm.app/Contents/MacOS/electerm` 看看log吗

**Comment by bianyifeng** [comment]
$ /Applications/electerm.app/Contents/MacOS/electerm
20:58:08 › no ../../install-src file
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
20:58:08 › no install-src file
20:58:08 › App starting...
20:58:09 › no ../../install-src file
20:58:09 › no install-src file
20:58:09 › server runs on localhost 3076
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
20:58:10 › Created terminal with PID: gGJoul8Ll
20:58:10 › ws: connected to terminal -> gGJoul8Ll
(node:3727) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:3727) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
20:58:21 › Closing app
20:58:21 › Closing app
20:58:21 › Closed terminal gGJoul8Ll
20:58:21 › Closed terminal gGJoul8Ll

**Comment by bianyifeng** [comment]
windows 10 也一样，1.30版本调整设置以后，关闭再打开，部分配置就恢复默认状态了

**Comment by zxdong262** [comment]
具体什么设置呢，我试了win10和mac14都不能复现

**Comment by bianyifeng** [comment]
语言、背景图 、Default ExecMac、Default Font size

以下是录屏


[录屏.zip](https://github.com/electerm/electerm/files/4365398/default.zip)

**Comment by zxdong262** [comment]
看起来是刷新的问题，彻底关闭再打开没问题吧？

**Comment by zxdong262** [comment]
感谢反馈，发布了新版本

**Comment by bianyifeng** [comment]
刚试了1.32版本，刷新、重启、关闭再打开，依旧还是配置会恢复默认状态，如果和之前的录屏效果一样

**Comment by zxdong262** [comment]
@bianyifeng win和mac都不行吗，我两个系统都试了不能复现

**Comment by sguphil** [comment]
@zxdong262  linux centos 8 : electerm v1.3.2, can not download configutions, AND the configuration will be restore after restart the electerm, need a quick fix, thanks

**Comment by sguphil** [comment]
i found another issue, there is duplicate copy of bookmarks. maybe i have tried to download configuration many times with the gitst id.

**Comment by bianyifeng** [comment]
mac 更新1.30在两台电脑上测试都一样，更新1.32后在一台电脑上测试问题依旧， windows 10 是在系统版本1909上测试1.30是 有这个问题，我再找一个其它版本的win10再试试。

**Comment by zxdong262** [comment]
Confirmed in Ubuntu 18.04, I will try to fix it ASAP

**Comment by zxdong262** [comment]
@bianyifeng 试试最新版吧
@sguphil please try the leatest release

**Comment by bianyifeng** [comment]
@zxdong262 mac 1.35版本后正常，windows 提示一直在升级版本，please wait

**Comment by sguphil** [comment]
updated the new version 1.3.5, seems the issue is gone.

**Comment by zxdong262** [comment]
> @zxdong262 mac 1.35版本后正常，windows 提示一直在升级版本，please wait

试试手动修复一下

1. 关闭程序
2. 如果是从1.3以前升级的,把C:\Users\你的用户名\AppData\Roaming\electerm-localstorage.json.backup 改名为·electerm-localstorage.json·，
3. 删除C:\Users\你的用户名\AppData\Roaming\electerm\users
4. 启动程序

**Comment by zxdong262** [comment]
发布了新版，很抱歉1.3.x系列问题太多了，希望这一次修复了
