### ISSUE TITLE
mac 更新到1.3.1打开问题

### ISSUE THREAD

**Issue by gefule** [electerm/electerm#1617]
更新到新版本后，每次打开软件会弹出
![image](https://user-images.githubusercontent.com/20297369/77256130-37d0f200-6ca7-11ea-9b25-2ac025462ef5.png)

**Comment by zxdong262** [comment]
可以命令行运行，看看log吗？

**Comment by zxdong262** [comment]
感谢反馈！

**Comment by gefule** [comment]
不客气，感谢你的软件
