### ISSUE TITLE
Whether this tool is safe and will disclose the server login information？

### ISSUE THREAD

**Issue by qhrking** [electerm/electerm#1626]
Whether this tool is safe and will disclose the server login information？
This is very important！！！

**Comment by zxdong262** [comment]
As far as I know, it would only request for new version info from github, no other data collected or submit to any server by itsself, if this is you want to know.

If you really need to comfirm it, better monitor the network activities yourself to confirm. After all I used many modules I would not check their code or security, so no guarantees.
