### ISSUE TITLE
win10更新1.3.7一直卡在upgrading database

### ISSUE THREAD

**Issue by Lawrence-Albet** [electerm/electerm#1629]
## Expected Behavior

进入页面
## Current Behavior

升级后一直卡在升级数据库界面
## Steps to Reproduce

1.升级electerm
2.打开electerm

**Comment by Lawrence-Albet** [comment]
![image](https://user-images.githubusercontent.com/59958227/77401221-7cfc3d80-6de7-11ea-9724-d835fb7733f3.png)

**Comment by zxdong262** [comment]
试试
1. 关闭程序
2.如果是从1.3以前升级的,把`C:\Users\你的用户名\AppData\Roaming\electerm-localstorage.json.backup` 改名为·electerm-localstorage.json·，
3.删除C:\Users\你的用户名\AppData\Roaming\users
4.启动程序

**Comment by lain-github** [comment]
18766225813@163.com
 同样的问题, 还没有解决.
发件人： ZHAO Xudong
发送时间： 2020-03-24 18:31
收件人： electerm/electerm
抄送： Subscribed
主题： Re: [electerm/electerm] win10更新1.3.7一直卡在upgrading database (#1629)
试试
关闭程序
2.如果是从1.3以前升级的,把C:\Users\你的用户名\AppData\Roaming\electerm-localstorage.json.backup 改名为·electerm-localstorage.json·，
3.删除C:\Users\你的用户名\AppData\Roaming\users
4.启动程序

**Comment by Lawrence-Albet** [comment]
> 18766225813@163.com 同样的问题, 还没有解决. 发件人： ZHAO Xudong 发送时间： 2020-03-24 18:31 收件人： electerm/electerm 抄送： Subscribed 主题： Re: [electerm/electerm] win10更新1.3.7一直卡在upgrading database (#1629) 试试 关闭程序 2.如果是从1.3以前升级的,把C:\Users\你的用户名\AppData\Roaming\electerm-localstorage.json.backup 改名为·electerm-localstorage.json·， 3.删除C:\Users\你的用户名\AppData\Roaming\users 4.启动程序 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

删除electerm文件夹和electerm相关配置文件后成功启动，然后同步下配置就能正常使用了

**Comment by lain-github** [comment]
嗯, 将上面提到的文件全删除后启动就可以了, 只是之前的配置都没有了.




18766225813@163.com
 
发件人： Lawrence-Albet
发送时间： 2020-03-25 09:36
收件人： electerm/electerm
抄送： lain-github; Comment
主题： Re: [electerm/electerm] win10更新1.3.7一直卡在upgrading database (#1629)
18766225813@163.com 同样的问题, 还没有解决. 
删除electerm文件夹和electerm相关配置文件后成功启动，然后同步下配置就能正常使用了

**Comment by zxdong262** [comment]
发布了一个新版本，应该能修正这个问题，不过看起来没法验证了。。。感谢反馈。
