### ISSUE TITLE
mac 下在sftp模式下，会出现本地文件更新后，在sftp下如果不刷新上传会出现上传了没改变的文件

### ISSUE THREAD

**Issue by crazyfly1115** [electerm/electerm#1630]
## Steps to Reproduce

1.打开sftp
2.在编辑器中修改了文件
3.在sftp模式下直接上传
4.在服务器上打开发现文件并未改变

**Comment by zxdong262** [comment]
是编辑本地文件，然后上传？我试了一下没有问题。
编辑之后保存了吗？保存后是自动刷新列表，你可以看到文件大小变了。
