### ISSUE TITLE
书签文件夹出现空白的情况

### ISSUE THREAD

**Issue by NilsonC348** [electerm/electerm#1632]
现在出现书签那里有部分的文件夹是空白的，在24号晚用的时候还是正常的，且上传到了gist保存配置。但25号早上继续使用时就发现这个状况，更新到最新的1.3.8版，从gist上面同步之前上传的配置之后也还是这样。空白的书签文件夹没有删除按钮，只能删里面的书签，删完之后还是有一个空白行在那里。创建书签的时候选“书签分类”的时候，显示这些空白文件夹是“---”的状态。

请问这个问题要怎么解决？

**Comment by zxdong262** [comment]
把appPath/electerm/users 删除试试，

appPath位置：
%APPDATA% ----Windows 中
$XDG_CONFIG_HOME or ~/.config ----Linux 中
~/Library/Application ----Support macOS 中

**Comment by zxdong262** [comment]
是升级到1.3.8就出现的？

**Comment by NilsonC348** [comment]
是的  用着1.3.7的时候没有这个情况。第二天早上用新版之后有这个情况，同步云端的数据下来也没用。

**Comment by NilsonC348** [comment]
![QQ图片20200326140316](https://user-images.githubusercontent.com/59073982/77615598-bd37f900-6f6a-11ea-859c-f32552d326f4.png)
![9AD5 IVC 6GBGA0O0 {K5M6](https://user-images.githubusercontent.com/59073982/77615687-e9ec1080-6f6a-11ea-8bca-43baf5e8e572.png)

这图片能看到吗？情况就是这样子的

**Comment by NilsonC348** [comment]
![9AD5 IVC 6GBGA0O0 {K5M6](https://user-images.githubusercontent.com/59073982/77615741-08eaa280-6f6b-11ea-879c-37d01c6863a9.png)

**Comment by NilsonC348** [comment]
![QQ图片20200326140316](https://user-images.githubusercontent.com/59073982/77615870-5830d300-6f6b-11ea-8dc2-4064b203c623.jpg)

**Comment by NilsonC348** [comment]
好像是我同步到gist上面的有问题，但24号晚用的时候没发现有这个问题。刚把 appPath/electerm/users里面的东西删了重新同步，也还是有这个问题。

**Comment by zxdong262** [comment]
书签页面有个导出功能，看看导出再导入可以不

**Comment by zxdong262** [comment]
如果方便的话可以把导出的数据脱敏发我一份我试试吗

**Comment by NilsonC348** [comment]
[bookmarks-2020-03-27-10-26-18.zip](https://github.com/electerm/electerm/files/4391135/bookmarks-2020-03-27-10-26-18.zip)


不好意思，现在才发。这个是导出来的书签，希望对你有用！

**Comment by NilsonC348** [comment]
对了  这个导出再重新导入  也还是这样

**Comment by NilsonC348** [comment]
有邮箱吗  我私发一份导出的数据给你？

**Comment by NilsonC348** [comment]
可以给个邮箱地址，我私发一份数据给你吧

**Comment by zxdong262** [comment]
发布了新版，很抱歉1.3.x系列问题太多了，希望这一次修复了
