### ISSUE TITLE
日志是否可以输出到文件

### ISSUE THREAD

**Issue by lain-github** [electerm/electerm#1636]
如题, 是否可以通过邮件菜单直接将打印保存到文件中呢.

**Comment by zxdong262** [comment]
什么日志呢？传输的，连接的，或者app日志？

**Comment by lain-github** [comment]
就是屏幕显示的打印信息, 比如手动运行一个程序, 程序中有许多调试信息会输出到屏幕, 能否选择在屏幕显示的同时备份到文件中呢.

**Comment by zxdong262** [comment]
merge to #1456
