### ISSUE TITLE
"取消窗口最大化"功能异常

### ISSUE THREAD

**Issue by lain-github** [electerm/electerm#1640]
## Expected Behavior

点击取消最大化按钮, 软件界面变为小窗口.

## Current Behavior

点击取消最大化按钮, 应该变为小窗口, 而不是最小化, 并且最小化之后无法重新恢复界面.

## Steps to Reproduce

1. 启动软件, 默认窗口最大化, 点击取消最大化按钮, 软件变为最小化, 而且无法恢复.
2. 如果手动拖动边框使窗口变小, 然后再使用"最大化"和"取消最大化", 异常消失.

**Comment by zxdong262** [comment]
方便的话请按照模板提交issue，包括操作系统版本之类的信息

**Comment by lain-github** [comment]
> 
> 
> 方便的话请按照模板提交issue，包括操作系统版本之类的信息

已经按照模版提交, 应该好复现.

**Comment by tenndou** [comment]
此问题在Mac下也会发生，macOS 10.15

**Comment by zxdong262** [comment]
最新版本已修复，感谢反馈
