### ISSUE TITLE
日志记录功能异常

### ISSUE THREAD

**Issue by lain-github** [electerm/electerm#1645]
## Expected Behavior

右键菜单中或者设置菜单中应该能修改日志记录文件的路径
## Current Behavior

现在点击日志文件的路径设置没有反应.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
看起来是打开目录的功能在win下无效

**Comment by lain-github** [comment]
哦哦, 后期会考虑添加路径修改吗, 这样固定的话文件可能会很大, 建议右键菜单添加启动停止功能, 如果每次想记录日志的时候去设置里面开启的话并不是很方便.

发件人: ZHAO Xudong
发送时间: 2020年4月3日 16:57
收件人: electerm/electerm
抄送: lain-github; Author
主题: Re: [electerm/electerm] 日志记录功能异常 (#1645)

目前没有修改路径功能，只是打开或者关闭日志，以及查看日志

**Comment by zxdong262** [comment]
@lain-github 你的想法有道理~

**Comment by zxdong262** [comment]
发布了新版，应该修复了不能打开文件夹的问题，请试试吧，感谢反馈

**Comment by lain-github** [comment]
辛苦啦, 更新到1.3.15, 在设置中打开日志记录开关, 可以指定文件路径了, 但是在右键菜单中仍然无法打开文件夹, 不知道是不是本来右键菜单就是不支持修改日志文件路径.

**Comment by zxdong262** [comment]
@lain-github 开关打开之后新的连接的log也无法打开吗？

**Comment by lain-github** [comment]
清楚了:
1. 日志文件默认路径和文件名是固定的, 不能修改, 之前以为可以修改.
2. 当默认路径下有日志文件时, 设置和右键菜单都可以打开文件夹.
3. 当默认路径下没有生成改日志文件或者日志文件被删除, 设置中可以打开文件夹(上一级), 右键菜单中无法打开.
4. 如果先开终端, 在从设置中打开日志, 当前终端是没有日志文件生成的, 必须重新开终端才会生成日志文件, 也就会出现上述2/3项的问题.
5. 总之个人感觉当前的日志记录功能并不是很方便.

**Comment by zxdong262** [comment]
> 清楚了:
> 
> 1. 日志文件默认路径和文件名是固定的, 不能修改, 之前以为可以修改.
> 2. 当默认路径下有日志文件时, 设置和右键菜单都可以打开文件夹.
> 3. 当默认路径下没有生成改日志文件或者日志文件被删除, 设置中可以打开文件夹(上一级), 右键菜单中无法打开.
> 4. 如果先开终端, 在从设置中打开日志, 当前终端是没有日志文件生成的, 必须重新开终端才会生成日志文件, 也就会出现上述2/3项的问题.
> 5. 总之个人感觉当前的日志记录功能并不是很方便.

确实如此，有待于优化
