### ISSUE TITLE
点击访问历史直接报错

### ISSUE THREAD

**Issue by lbmzorx** [electerm/electerm#1649]
## Electerm version:
v1.3.12
## Operating system(linux, macos, or windows7/8/10?):
windows7
## Expected Behavior

点击  设置 -> 访问历史   直接动不了
![image](https://user-images.githubusercontent.com/26056895/78380948-3e485d80-7607-11ea-9721-1137e145abda.png)
杀死进程重启 报错
![image](https://user-images.githubusercontent.com/26056895/78381187-95e6c900-7607-11ea-9fb2-42886da8106b.png)
再点击 关闭
再重新进入才能进入
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
感谢反馈，修复了，请试试新版本~

**Comment by lbmzorx** [comment]
假期修复，辛苦了...



lbmzorx@163.com
 
发件人： ZHAO Xudong
发送时间： 2020-04-05 20:59
收件人： electerm/electerm
抄送： Orx; Author
主题： Re: [electerm/electerm] 点击访问历史直接报错 (#1649)
感谢反馈，修复了，请试试新版本~
