### ISSUE TITLE
能否增加数据监控栏

### ISSUE THREAD

**Issue by andyxqq** [electerm/electerm#1657]
![image](https://user-images.githubusercontent.com/8818092/78754634-65f24980-79aa-11ea-9076-3ab1503e7859.png)
类似这种监控，这对运维非常有帮助。参考finalshell

**Comment by zxdong262** [comment]
好主意！

**Comment by zxdong262** [comment]
这是本机的，还是连接的服务器的信息呢？

**Comment by andyxqq** [comment]
@zxdong262  服务器信息。定时刷新的。

**Comment by zxdong262** [comment]
@andyxqq 我正在做这个功能，请教0ms那个表格显示的是什么信息呢，以及60k下面的77k,53k,27k是什么意思呢？

**Comment by andyxqq** [comment]
太棒了 ！
这是一个图表，上边的60k、30k 分别代表着服务器“eth0”这个网卡的上下行速率。77k,53k,27k是图表的纵坐标。

下方的0ms其实意义不大。这个代表着本机到服务器的ping值。

其他：
“内存\CPU\命令”这个表格其实还可以点击，点击之后会打开一个tab，如下图
![image](https://user-images.githubusercontent.com/8818092/79813753-1864dc00-83af-11ea-8eed-132771fef7f0.png)

点击“网卡速率”这个图标会弹出如下图
![image](https://user-images.githubusercontent.com/8818092/79814275-64fce700-83b0-11ea-8000-d43ded145cc3.png)
仅供参考。

**Comment by zxdong262** [comment]
@andyxqq 不知道你用了新版本的信息展示功能没有（右下角有个info图标），想看看是不是有没有建议或者需求

**Comment by andyxqq** [comment]
已经第一时间更新了。体验很棒！不过有一点自己的拙见

1、可否把下图的数据处理一下，然后整理一下排列方式，如下
![image](https://user-images.githubusercontent.com/8818092/82116391-0a329180-979c-11ea-8b46-201e32665d52.png)

运行时长：16天9小时
CPU：9%
内存：50% 5.2G/6.9G
交换：2% 89Mb/2G
这样看起来更加人性化一些，如果能有进度条的显示就更完美了，嘿嘿

2、点击图标i后的窗体(信息窗)可否不浮在命令窗之上，而是将命令窗挤窄一点，当信息窗失去焦点时也不自动关闭窗口，点击x关闭窗口。

3、信息窗大小有限，可以精简一些内容，使其边窄一些，如：
进程列表：可以只显示”CPU“（百分比）、”内存“（百分比）
文件系统：路径、占用百分比

4、第3条精简掉的内容可以在sftp后边增加一个信息详情页，在详情页中可以展示服务器的各种详情信息。如：
进程列表可以复制pid、结束选中进程、查看进程的目录等

感谢提供这么优秀的工具！
