### ISSUE TITLE
连接服务器弹出 Failed to fetch 错误

### ISSUE THREAD

**Issue by liupeizhi** [electerm/electerm#1666]
## Electerm version:
1.3.18
## Operating system(linux, macos, or windows7/8/10?):
macos x
## Expected Behavior

连接服务器弹出 Failed to fetch 错误
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
每次连接都会弹出吗?连接不会成功?

**Comment by liupeizhi** [comment]
每次都会弹，而且打开以后本地shell也会弹，可以在mac os最新版试试

**Comment by liupeizhi** [comment]
升级系统后，好了
