### ISSUE TITLE
windows10下运行程序无法进行窗口化

### ISSUE THREAD

**Issue by Burchencode** [electerm/electerm#1668]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Burchencode** [comment]
Electerm version: electerm-1.3.18-win-x64
Operating system windows10 1903
Expected Behavior：When I click maximize and minimize, I hope the window can change accordingly.
Current Behavior：the reality is that when I click on maximize the window, the window is maximized. Later, when I clicked on the minimize window, the window did not respond. I can only minimize by dragging the four corners of the window.

**Comment by zxdong262** [comment]
Fixed now in latest release
