### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by GreedySnake9527** [electerm/electerm#1669]
如果主机开启了Google Authenticator（MFA）认证，在electerm设置好ip 、port、username、password后，登录，会弹出

  MFA验证码输入框，dansh但是我看后台日志，当弹出这个验证码输入框的时候原来的连接就结束了，相当于建立了一个新的连接，导致登录不了。希望可以支持MFA

**Comment by lustlost** [comment]
请问这个功能什么时候能够支持呢

**Comment by chaochensd** [comment]
这功能很迫切啊

**Comment by zxdong262** [comment]
最新版已经支持了，可以试一试
