### ISSUE TITLE
Cannot enter admin mode

### ISSUE THREAD

**Issue by nZeus** [electerm/electerm#1670]
sudo command gives a Permission denied error 

``` bash
$ sudo -s
bash: /usr/bin/sudo: Permission denied
```

## Operating system(linux, macos, or windows7/8/10?):
Ubuntu Fossa + Gnome

## Expected Behavior
It should ask for password

## Current Behavior
I get error: `Permission denied`

**Comment by zxdong262** [comment]
Can you do this with other terminal?

**Comment by nZeus** [comment]
yes, it works fine when I use Ubuntu's default terminal

**Comment by zxdong262** [comment]
That is strange, it works fine in Ubuntu 18.04.  I will try download 20.04 and test it.

**Comment by tglhteam** [comment]
Hello! I have the same problem. I use Ubuntu 20.04 Lts. When using the sudo command, this message is issued bash: `/usr/bin/sudo: Permission denied`
Please fix the problem. Your terminal is very cool!

**Comment by zxdong262** [comment]
@tglhteam @nZeus I created a new Ubuntu 20.04 virtual box machine, `sudo  su` works, do you have any special settings you can think of?

**Comment by tglhteam** [comment]
Today, May 10, I installed a clean Ubuntu system on 04/20. I didn’t do any special settings at all. In the terminal Gnome, a `sudo su` works. Installed your program and `sudo su` does not work. Checked several times. The error is the same: `bash: /usr/bin/sudo: Permission denied`

**Comment by zxdong262** [comment]
@tglhteam How about `sudo ls`, will it trigger same error?

**Comment by tglhteam** [comment]
Yes, this command `sudo ls` also shows an error.
![image](https://user-images.githubusercontent.com/39122932/81543242-2491f700-93b9-11ea-81d2-2cd826c0ea23.png)

**Comment by zxdong262** [comment]
Hi @tglhteam
When run `lsof -i | grep electerm`, can you see your current username, and you run electerm from command line or click the icon? How did you install electerm?

**Comment by tglhteam** [comment]
Here are the messages after entering the command:
![image](https://user-images.githubusercontent.com/39122932/81549896-cf5ae300-93c2-11ea-8ec0-deb9173d4836.png)

 I launch Elekterm by click the icon. Installed the program from the Ububntu application center.

**Comment by nZeus** [comment]
Same output. I installed it using snap

**Comment by tglhteam** [comment]
I also tried to enter the directory through Electerm - nothing works. Everything works through the Gnome terminal.
![2020-05-11_20-20](https://user-images.githubusercontent.com/39122932/81551739-b6076600-93c5-11ea-8431-6a3df5dd9bdb.png)
![2020-05-11_20-21](https://user-images.githubusercontent.com/39122932/81551746-b869c000-93c5-11ea-8524-d53e800dae33.png)

**Comment by zxdong262** [comment]
@tglhteam @nZeus I can reproduce this when install from snap, seems related to --no-sandbox param, when run from commandline `electerm --no-sandbox`, it will be OK, also seems download from relealse page and install with `sudo dpkg -i electerm.xxxx.dep` would be OK too, anyway I will release new version to fix it, thank you for the feedback.

**Comment by zxdong262** [comment]
@nZeus @tglhteam Oh, no, --no-sandbox do not work. Still do not know why...

**Comment by tglhteam** [comment]
@zxdong262 I installed the .deb package. `Sudo` works, thanks! But the `cd` command does not work I enter the `cd` command, drag the folder, but the path to this folder in the terminal is not displayed. I took screenshots above. See also this error.

**Comment by zxdong262** [comment]
@tglhteam Yes, it is bug, created a new issue from your comment.

**Comment by zxdong262** [comment]
@tglhteam @nZeus Still did not find a way to resolve electerm installed from snap can not sudo.

**Comment by zxdong262** [comment]
Resolved now, need `--classic`, `sudo snap install electerm --classic`
