### ISSUE TITLE
可以支持自定义快捷键吗，目前只看到分屏 Ctrl+/

### ISSUE THREAD

**Issue by lbmzorx** [electerm/electerm#1672]
## Electerm version:
v1.3.18
## Operating system(linux, macos, or windows7/8/10?):
10
## Expected Behavior

目前看到右上角有分屏的按钮提示 ctrl+\  
是否可以增加查看快捷键设置，并且可以自己定义快捷键

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
暂不支持（还没轮到），不过大多数都是参照通用的快捷键设定
