### ISSUE TITLE
恢复未正确关闭的连接?

### ISSUE THREAD

**Issue by wangweili006** [electerm/electerm#1674]
恢复未正确关闭的连接?

能不能把这个提示信息做成配置，现在每次打开都会有这个提示，很烦人的

**Comment by zxdong262** [comment]
什么操作系统？

**Comment by wangweili006** [comment]
1. macos 10.14.6
2. cmd + q，关闭后，再次打开会出现这种情况
3. 点击左上角的electerm菜单中的关闭时，再次打开就不会出现










4. 能不能把主题做成像termius的一样，方便，而且termius的内置主题都是比较常见的












 原始邮件 
发件人: ZHAO Xudong<notifications@github.com>
收件人: electerm/electerm<electerm@noreply.github.com>
抄送: 王伟利<wangweili006@qq.com>; Author<author@noreply.github.com>
发送时间: 2020年5月7日(周四) 22:30
主题: Re: [electerm/electerm] 恢复未正确关闭的连接? (#1674)


什么操作系统？

**Comment by zxdong262** [comment]
已经去掉了
