### ISSUE TITLE
新版本越来越卡了

### ISSUE THREAD

**Issue by zhengyongtao** [electerm/electerm#1676]
## Electerm version:
1.3.21
## Operating system(linux, macos, or windows7/8/10?):
MacOS10.15
## Expected Behavior

新版本相当卡，程序切换都会卡一会儿才能正常输入字符，另外sftp的稳定性相当糟糕，在零碎小文件多的时候右下角疯狂弹窗报错。

**Comment by zxdong262** [comment]
sftp功能正在重写中，确实有问题 --合并到 https://github.com/electerm/electerm/issues/1446
