### ISSUE TITLE
window拼贴功能崩溃

### ISSUE THREAD

**Issue by BetterChenMing** [electerm/electerm#1677]
## Operating system(linux, macos, or windows7/8/10?):
macos 10.15.4 Catalina
## Expected Behavior

do not collapse.

## Current Behavior

collapse >,<

## Possible Solution

fix it.
but I don't know how to do

## Steps to Reproduce

1. click the icon
2. choose the window option
3. then click '将窗口拼接到窗口左侧'
4. it happens, again and again

## Context (Environment)

just for a functional test

## Detailed Description

fix it or not, maybe you guys have some other important issues to fix.

**Comment by zxdong262** [comment]
merge -> https://github.com/electerm/electerm/issues/1707
