### ISSUE TITLE
ubuntu上运行报错 Failed to fetch

### ISSUE THREAD

**Issue by lbmzorx** [electerm/electerm#1678]
## Electerm version:
v1.3.21
## Operating system(linux, macos, or windows7/8/10?):
ubuntu 20.04LTS
## Expected Behavior

进入electerm 时候是正常的
配置了标签后测试 显示 失败 
error
Failed to fetch

连接后 本地的命令行也不可用
![2020-05-10 21-29-18 的屏幕截图](https://user-images.githubusercontent.com/26056895/81500543-65c8cf00-9305-11ea-8d92-234ab8d023bb.png)

错误信息

Error: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR at signOneShot (internal/crypto/sig.js:124:10) at OpenSSH_Private.sign (/opt/electerm/resources/app.asar/node_modules/ssh2-streams/lib/keyParser.js:424:16) at /opt/electerm/resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:576:36 at SSH2Stream.authPK (/opt/electerm/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:1646:3) at SSH2Stream.onUSERAUTH_PK_OK (/opt/electerm/resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:575:14) at Object.onceWrapper (events.js:299:28) at SSH2Stream.emit (events.js:210:5) at parse_USERAUTH (/opt/electerm/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:4078:12) at parsePacket (/opt/electerm/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3772:12) at SSH2Stream._transform (/opt/electerm/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:701:13) at SSH2Stream.Transform._read (_stream_transform.js:189:10) at SSH2Stream._read (/opt/electerm/resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:253:15) at SSH2Stream.Transform._write (_stream_transform.js:177:12) at doWrite (_stream_writable.js:431:12) at writeOrBuffer (_stream_writable.js:415:5) at SSH2Stream.Writable.write (_stream_writable.js:305:11)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
z这个报错把后台进程弄崩溃了，用户名加private key?

**Comment by lbmzorx** [comment]
用private key 和直接输密码都不行

**Comment by zxdong262** [comment]
@lbmzorx 你是用snap安装的还是下载的dep然后`sudo dpkg -i electerm.xxx.dep`

**Comment by lbmzorx** [comment]
直接在这里下载，然后安装的，没有经过应用商定，安装时候没有报错

**Comment by zxdong262** [comment]
最新版应该没问题了
