### ISSUE TITLE
Terminal font display spacing is strange！

### ISSUE THREAD

**Issue by SvenAugustus** [electerm/electerm#1697]
## Electerm version:
1.3.28

## Operating system(linux, macos, or windows7/8/10?):
OS: Arch Linux 
Kernel: x86_64 Linux 5.6.12-arch1-1

## Expected Behavior
normal spacing expected.

## Current Behavior
see the image below:
![图片](https://user-images.githubusercontent.com/11767671/82044161-684d6f00-96df-11ea-8a09-130fc6cc0634.png)

**Comment by zxdong262** [comment]
Can you try some other fonts in setting?

**Comment by SvenAugustus** [comment]
> Can you try some other fonts in setting?

Σ( ° △ °|||)︴ , only i clear all the default font (may not exists in the system), and set the font to 'Source Code Pro' , it 's fine now.

but it seems not support fonts like : wqy-microhei, dejavu-sans-mono ....
