### ISSUE TITLE
mac下的一些使用问题

### ISSUE THREAD

**Issue by ChironChen** [electerm/electerm#1698]
## Electerm version:
1.3.28
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

1.macos下使用右上角最小化和关闭按钮，需要多次尝试点击，无法一次成功，左上角mac原版关闭和最小化按钮被logo功能键遮挡，使用不便。

2.希望提供electerm常驻后台功能，每次关闭后默认软件进程直接结束，重启时所需时间长于iterm2，希望可以提供此功能，以便于关闭现有窗口后快速重启。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
10.15？

**Comment by ChironChen** [comment]
macos catalina 10.15.4

**Comment by zxdong262** [comment]
可以提供一个截图吗，我还在10.14，左上角是没有按钮的

**Comment by ChironChen** [comment]
<img width="1123" alt="iShot2020-05-16下午05 05 41" src="https://user-images.githubusercontent.com/30064603/82115857-f9801c80-9797-11ea-911f-95dad88c150b.png">

**Comment by zxdong262** [comment]
@ChironChen  谢谢，我才发现10.14也有，要鼠标移动到左上角才能看到，10.15是也要移动到左上角才能看到吗？

**Comment by Robin-byte** [comment]
刚从win换到macos，就发现了这款神器。用了一下有很多贴心的功能。就是右上角的最大最小化不是很方便，左边mac风格，右边还有windows风格的按钮，哈哈。整个ui再优化一下就完美了 👍

**Comment by yymmhh** [comment]
@zxdong262 请问Mac 版本有全屏功能吗

**Comment by zxdong262** [comment]
> 刚从win换到macos，就发现了这款神器。用了一下有很多贴心的功能。就是右上角的最大最小化不是很方便，左边mac风格，右边还有windows风格的按钮，哈哈。整个ui再优化一下就完美了 👍

10.15左上角按钮是一直显示吗？

**Comment by ChironChen** [comment]
左上角不是一直显示

**Comment by ChironChen** [comment]
但是右上角的按钮会失灵，mac下还是左上角原生的按钮好用
