### ISSUE TITLE
How to disable the usless pop up info

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#1709]
## Operating system(linux, macos, or windows7/8/10?): centos

How to disable the usless pop up info ? 
<img width="226" alt="uslessPopUp" src="https://user-images.githubusercontent.com/8896611/82401787-51b36900-9a8d-11ea-8ad3-14e6bcc6ccc8.png">

**Comment by sguphil** [comment]
the pop up info is usless at all and will break the foucus of what i am doing, the pop should be some kind of warning/error that need to be hendled.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/9c62a8e0dc572179cb5f5e71d8e4e397eb387161
