### ISSUE TITLE
Suppress "Restore Terminal windows" on start up

### ISSUE THREAD

**Issue by christatedavies** [electerm/electerm#1710]
## Expected Behavior
This popup appears everytime I start and I don't like it.

## Can you reproduce the same behavior in other terminal:
No

## Possible Solution
Have a setting to disable this if user wishes

## Steps to Reproduce
1. Open Electerm
2. Popup appears

## Context (Environment)
I have to basically just close it every time
I use bookmarks so have no need for a "new terminal" every time

## Suggestions?
I jut think a boolean option to show/suppress the "restore terminals" panel on startup

**Comment by christatedavies** [comment]
Heres the panel I was talking about:

<img width="601" alt="Screenshot 2020-05-20 at 17 00 53" src="https://user-images.githubusercontent.com/1114343/82469466-f51b7280-9abb-11ea-960c-d3a1acaa2f31.png">

**Comment by christatedavies** [comment]
This happens however I close the application by the way. It wasn't an "uncorrect shutdown"

**Comment by zxdong262** [comment]
Thank you for the feedback, I removed the recover session function in the leatest release.
