### ISSUE TITLE
quickCommands加载问题

### ISSUE THREAD

**Issue by TangHanF** [electerm/electerm#1712]
## Electerm version:
v1.3.31

## Operating system(linux, macos, or windows7/8/10?):
macOS 10.14.6

## Expected Behavior

选择某个书签可以正常查看该书签配置的quickCommand

## Current Behavior

从书签中打开某一个具体书签并增加了quickCommands之后再次打开该书签看不到之前添加的quickCommands项，需要新增一条记录才能加载出来。

## Steps to Reproduce

1.设置>书签
2.选择一个书签，然后切换到quickCommands标签页，增加一个quickCommand，关闭设置
3.重新进入设置>书签，选择刚才编辑的书签，切换到quickCommands标签页，看不到刚才新增的quickCommand，此时需要新增一个quickCommand才能加载出历史新增的quickCommand

**Comment by zxdong262** [comment]
@TangHanF 新增quickCommand之后是不是没有点击保存？

**Comment by zxdong262** [comment]
@TangHanF 保存并连接 也可以的，是不是没有点击那个对号？

**Comment by TangHanF** [comment]
> @TangHanF 保存并连接 也可以的，是不是没有点击那个对号？

是的，没有点击

**Comment by zxdong262** [comment]
@TangHanF 那就是这个原因了，一定要点击对号才是真正添加了，确实有点反直觉
