### ISSUE TITLE
sftp没有远程目录只有本地目录

### ISSUE THREAD

**Issue by wukai1211** [electerm/electerm#1715]
操作系统：macos10.15.4
electerm: 1.3.34
ssh什么的都没有问题。就是在sftp管理中没有远程sftp目录。。整个sftp管理界面只有本地的目录显示。
![截屏2020-05-26 上午11 31 52](https://user-images.githubusercontent.com/12652827/82857865-c7fc1380-9f44-11ea-8f06-2aaccda6c172.png)
![截屏2020-05-26 上午11 32 16](https://user-images.githubusercontent.com/12652827/82857871-cfbbb800-9f44-11ea-98b7-4a41a9f92d21.png)
请看第二张图片，文件管理器只有本地的目录。没有远程目录

**Comment by zxdong262** [comment]
目前ssh-config只是在本地命令行帮助输入命令而已，还不是完善的支持
