### ISSUE TITLE
TypeError:Cannot read property 'getSize'of null

### ISSUE THREAD

**Issue by sunzhengbo** [electerm/electerm#1716]
软件版本：electerm-1.3.28-win-x64
系统版本：Windows10 2004
![image](https://user-images.githubusercontent.com/29298020/83102499-31b42300-a0e7-11ea-988e-f2714bb32d99.png)

**Comment by zxdong262** [comment]
做了什么操作报错的？

**Comment by sunzhengbo** [comment]
不知道，应该是没有做过什么操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 下午2:49
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] TypeError:Cannot read property 'getSize'of null (#1716)





 
做了什么操作报错的？

**Comment by sunzhengbo** [comment]
我现在是打不开了，打开就在后台，再去点击后台的图标，就报截图的错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZHAO Xudong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 下午2:49
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] TypeError:Cannot read property 'getSize'of null (#1716)





 
做了什么操作报错的？

**Comment by zxdong262** [comment]
删除C:\Users\你的用户名\AppData\Roaming\electerm试试
