### ISSUE TITLE
Window control buttons hard to click

### ISSUE THREAD

**Issue by vimlet** [electerm/electerm#1718]
## Electerm version:
v1.3.34

## Operating system(linux, macos, or windows7/8/10?):
Windows 10

## Expected Behavior
Top right window control buttons (minimize, restore, close) buttons should respond to click on all of its size.

## Current Behavior
Top right window control buttons (minimize, restore, close) buttons only respond to click on the actual icon.

## Possible Solution
Add click listeners on the actual button element instead of the icons.

**Comment by zxdong262** [comment]
Fixed in latest release
