### ISSUE TITLE
Allow restore session initial popup to be optional

### ISSUE THREAD

**Issue by vimlet** [electerm/electerm#1719]
## Electerm version:
v1.3.34

## Operating system(linux, macos, or windows7/8/10?):
Windows 10

## Expected Behavior
Restore session popup should be togglable in Electerm preferences.

## Current Behavior
Restore session dialog always appear on Electerm startup.

## Possible Solution
Add an option in preferences.

**Comment by zxdong262** [comment]
Already removed
