### ISSUE TITLE
Theming support for Electerm

### ISSUE THREAD

**Issue by vimlet** [electerm/electerm#1720]
## Electerm version:
v1.3.34

## Operating system(linux, macos, or windows7/8/10?):
Windows 10

## Expected Behavior
Electerm should be themeable, not only the terminal colors.

## Current Behavior
Only terminal colours are themeable.

## Possible Solution
Implement CSS override themes.

**Comment by zxdong262** [comment]
Merge to https://github.com/electerm/electerm/issues/3
