### ISSUE TITLE
Electerm logo/design issues

### ISSUE THREAD

**Issue by vimlet** [electerm/electerm#1721]
With all the respect of the world, the current logo and text seem terribly old, like those old animated texts gifs of the year 2000 and the icon seems like the famous E.T. film.

**current:**
![image](https://user-images.githubusercontent.com/2963607/83305886-d9257880-a201-11ea-940e-bd2bf4128129.png)
**reminds:**
![image](https://user-images.githubusercontent.com/2963607/83305679-7a5fff00-a201-11ea-9c08-c0b071852f36.png)

**current:**
![image](https://user-images.githubusercontent.com/2963607/83305741-9cf21800-a201-11ea-91ad-b3ed33e569f9.png)
**reminds:**
![image](https://user-images.githubusercontent.com/2963607/83305826-bdba6d80-a201-11ea-85e8-ec3c08016236.png)

### Design

I've made a quick design, you can use it freely if you wish or use it as inspiration.
![image](https://user-images.githubusercontent.com/2963607/83306075-35889800-a202-11ea-881e-4b4c3ab6b59e.png)

I'm sure that if you make a public design contest many people will make a much better job at it.
 
Here are the files.
[electerm.zip](https://github.com/electerm/electerm/files/4704410/electerm.zip)

**Comment by zxdong262** [comment]
@vimlet Thank you, I will think about the design contest.
