### ISSUE TITLE
Add disable sftp option

### ISSUE THREAD

**Issue by marskang** [electerm/electerm#1724]
## Electerm version:
v1.3.35
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

连接上堡垒机之后，可以正常选择服务器
## Can you reproduce the same behavior in other terminal:

SecureCRT连上堡垒机后，可正常选择服务器
## Current Behavior

Electerm连接上堡垒机之后，可以看到服务器列表，但是立马报错断开，
错误信息如下:
[2020-06-02 12:01:59.592] [error] {
  constructor: 'Error',
  stack: 'Error: Unable to start subsystem: sftp\n' +
    '    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.3.35-a7dd29513827de7b29ba64a43211c38638802f02.js:19:422657\n' +
    '    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.3.35-a7dd29513827de7b29ba64a43211c38638802f02.js:19:379923)'
}
[2020-06-02 12:01:59.634] [debug] socket closed, pid: 1ZtdFeqOp
[2020-06-02 13:38:40.702] [debug] sftp error Unable to start subsystem: sftp
[2020-06-02 13:38:40.713] [error] {
  constructor: 'Error',
  stack: 'Error: Unable to start subsystem: sftp\n' +
    '    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.3.35-a7dd29513827de7b29ba64a43211c38638802f02.js:19:422657\n' +
    '    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.3.35-a7dd29513827de7b29ba64a43211c38638802f02.js:19:379923)'
}
## Steps to Reproduce

1.
2.
3.
4.

**Comment by marskang** [comment]
可以关掉这个sftp自动连接吗

**Comment by bianyifeng** [comment]
书签关闭SFTP 依然断开
[2020-06-22 10:21:38.504] [debug] socket closed, pid: bW9__G_yq
