### ISSUE TITLE
rz上传 进度99% 一直卡顿

### ISSUE THREAD

**Issue by orange-son** [electerm/electerm#1727]
## Electerm version:
v1.3.35
## Operating system(linux, macos, or windows7/8/10?):
macos
## Steps to Reproduce

1.本地代码打zip包；文件大小约30+M
2.远程Centos7服务器上执行 rz 命令
3.选择本地打包的30+M.zip
4.前期正常，上传进度到99%，直接卡死。无法上传。可以取消上传。
5.点击取消上传当前会话重新链接。

**Comment by mose-zm** [comment]
我的也是这样
me，too

**Comment by zxdong262** [comment]
目前的只有一个可用的js zmodem module，看起来是有缺陷的，只能传较小的文件

**Comment by zxdong262** [comment]
合并到 https://github.com/electerm/electerm/issues/1401

**Comment by lonnywong** [comment]
@wind-2019 @mose-zm 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
