### ISSUE TITLE
Uncaught Exception: TypeError:

### ISSUE THREAD

**Issue by harvies** [electerm/electerm#1728]
Uncaught Exception:
TypeError: Cannot read property 'getSize' of null
    at Tray.onClick (/Applications/electerm.app/Contents/Resources/app.asar/lib/tray.js:15:31)
    at Tray.emit (events.js:210:5)

**Comment by zxdong262** [comment]
Can you provide more info, like OS, version

**Comment by harvies** [comment]
> Can you provide more info, like OS, version

MacOS 10.14.6 

![image](https://user-images.githubusercontent.com/16585330/83967598-ba0ba280-a8f5-11ea-986a-eb4780656b7d.png)

![image](https://user-images.githubusercontent.com/16585330/83967602-c263dd80-a8f5-11ea-9ccd-dfbee1928d9d.png)

**Comment by zxdong262** [comment]
merge to #1716
