### ISSUE TITLE
Program crash，100%

### ISSUE THREAD

**Issue by xgene** [electerm/electerm#1729]
## Electerm version:
1.3.35
## Operating system(linux, macos, or windows7/8/10?):
macOS
## Expected Behavior

Drag the program window to another desktop and display it side by side with another program

## Can you reproduce the same behavior in other terminal:

yes
## Current Behavior

no display, but crashed
## Possible Solution

no
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Process:               electerm [2260]
Path:                  /Applications/electerm.app/Contents/MacOS/electerm
Identifier:            org.electerm.electerm
Version:               1.3.35 (1.3.35.480)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           electerm [2260]
User ID:               501

Date/Time:             2020-06-06 12:55:03.616 +0800
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        5F90C8DB-A61E-441B-BDFC-433AD18DC3B5

Time Awake Since Boot: 3600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [2260]

## Suggestions?

no

**Comment by zxdong262** [comment]
It is known issue, no solution yet, unless drop support for transparent window. 

https://github.com/electron/electron/issues/15704
