### ISSUE TITLE
中文输入乱码

### ISSUE THREAD

**Issue by gnayuyiel** [electerm/electerm#1734]
## Electerm version: 
v1.3.36
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior
中文输入乱码  Disorderly code while typing in chinese with gbk、utf-8 

## Can you reproduce the same behavior in other terminal:

no

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Close due to not active
