### ISSUE TITLE
ERROR Internal Service Error

### ISSUE THREAD

**Issue by ShawZG** [electerm/electerm#1739]
## Operating system(linux, macos, or windows7/8/10?): Linux/UOS

曾经安装过zsh，后来删除了，然后再打开，就报错了，不知道这个操作是否有影响。

![截图录屏_electerm_20200616144258](https://user-images.githubusercontent.com/22807878/84740469-0767ce00-afe0-11ea-8cc6-5663a4c117dd.jpg)

**Comment by zxdong262** [comment]
什么Linux发行版？

**Comment by ShawZG** [comment]
Debian

**Comment by zxdong262** [comment]
之前运行正常过吗？重启可以解决不？

**Comment by ShawZG** [comment]
大概发现问题原因了，应为我改过bash，用的zsh，后来把zsh卸载了，但是系统设置里仍然是zsh，我改成bash就可以了。

![image](https://user-images.githubusercontent.com/22807878/85088784-809b3700-b213-11ea-8068-89b333931905.png)

**Comment by zxdong262** [comment]
OK
