### ISSUE TITLE
如何跳转

### ISSUE THREAD

**Issue by martin820303** [electerm/electerm#1742]
系统：ubuntu 18.04
版本：1.3.38
我有几台云机器，对外只有一个外网地址，第二台机器需要登录第一台后跳转，才能登录。
我试过用命令，但是要输入密码。
不知道这个如何设置才能自动跳转？

**Comment by zxdong262** [comment]
暂不支持

**Comment by hope250** [comment]
SSH隧道，代理

**Comment by martin820303** [comment]
> SSH隧道，代理

可是还是要输入密码

**Comment by zxdong262** [comment]
合并到 https://github.com/electerm/electerm/issues/1014
