### ISSUE TITLE
ubuntu18.04使用rz -be传输时总是直接到99%，实际传输只有0.02%

### ISSUE THREAD

**Issue by TheDavidGithub** [electerm/electerm#1743]
## Steps to Reproduce

1.ubuntu18.04安装electerm
2.在远程登录的debain4.9执行rz -be传输9MB的zip压缩包

**Comment by zxdong262** [comment]
合并到 #1401

**Comment by zxdong262** [comment]
确实只支持小文件，目前npm就只有这个zmodem module

**Comment by TheDavidGithub** [comment]
好的，感谢回复，Ubuntu使用rz的希望破灭了。



&nbsp;

**Comment by lonnywong** [comment]
@TheDavidGithub 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
