### ISSUE TITLE
功能建议：设置使用独立窗口

### ISSUE THREAD

**Issue by renxia** [electerm/electerm#1744]
在 `xterm.js`里看到了这个客户端，试用了一下觉得相当不错。初步体验后有以下几个功能建议：

1. 设置不是独立窗口，用习惯了流行的 ssh 管理客户端，总想拖动它，不是很方便
2. 可以自定义背景图片，这个功能很赞。不过背景图片不能进行模糊，使得对背景图片的要求比较高。建议增加 `filter` 设置，比如可以调整 blur、brightness、contrast、opacity 的值，达到更好的自由定义。

3. 最大化的按钮可点击区域过小，建议调整一下样式。调试了下只有 10x6 大小，导致经常未点击到有效区域无反应，让人觉得是有bug

4 . 增加一些常用快捷键，方便用习惯流行同类工具的同学，也可快速习惯使用。如 ctrl+T 新建 tab，ctrl+W 关闭 tab 等

**Comment by xiekunwhy** [comment]
强烈建议。
