### ISSUE TITLE
cant connect to server

### ISSUE THREAD

**Issue by liuqinfu** [electerm/electerm#1753]
## Expected Behavior

connected to my server with ip and name、password

## Can you reproduce the same behavior in other terminal:

secureCRT is normal
but this app cant do it,there is error log:

Error: Handshake failed: signature verification failed at onKEXDH_REPLY (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:2797:15) at SSH2Stream.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:217:45) at SSH2Stream.emit (events.js:210:5) at parse_KEXDH_REPLY (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3970:8) at parse_KEX (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3916:16) at parsePacket (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3770:12) at SSH2Stream._transform (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:701:13) at SSH2Stream.Transform._read (_stream_transform.js:189:10) at SSH2Stream._read (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:253:15) at SSH2Stream.Transform._write (_stream_transform.js:177:12) at doWrite (_stream_writable.js:431:12) at writeOrBuffer (_stream_writable.js:415:5) at SSH2Stream.Writable.write (_stream_writable.js:305:11) at Socket.ondata (_stream_readable.js:726:22) at Socket.emit (events.js:210:5) at addChunk (_stream_readable.js:308:12)

**Comment by zxdong262** [comment]
Is your server a windows server?
