### ISSUE TITLE
No resource with given URL found

### ISSUE THREAD

**Issue by woshihoujinxin** [electerm/electerm#1754]
执行yarn run app 为什么 是空白页
![image](https://user-images.githubusercontent.com/3643467/86069462-7c410a80-baac-11ea-8473-b6b7b249763a.png)

**Comment by woshihoujinxin** [comment]
看着图 正常打包 就可以展示页面 我是一个初学者 请指教

**Comment by zxdong262** [comment]
有没有另开一个terminal运行yarn start?
