### ISSUE TITLE
SFTP Error displaying folder if it contains a broken symlink

### ISSUE THREAD

**Issue by dskrad** [electerm/electerm#1755]
## Operating system(linux, macos, or windows7/8/10?):
Windows 10 client; Linux host

## Expected Behavior
The folder should display properly, with the broken symbolic link greyed out (or otherwise)

## Can you reproduce the same behavior in other terminal:
No

## Current Behavior
Error

## Steps to Reproduce

1. place a broken symbolic link in a folder on linux (e.g. /home/username/broken-link.txt)
2. try to navigate to that folder (e.g. /home/username)
3. error message, and folder never displayed

**Comment by zxdong262** [comment]
@dskrad Thank you for the feedback!
