### ISSUE TITLE
SendEnv when ssh connect

### ISSUE THREAD

**Issue by degbug** [electerm/electerm#1759]
是否能支持通过SendEnv方式将本地的环境变量(如lang等传递到服务器中）？
我直接使用electerm连接服务器时，`echo $LANG` 输出是`en_US.UTF-8`， 而在terminal中通过ssh命令建立连接后查看输出的是
`zh_CN.UTF-8`

因为权限原因，我没有办法修改服务器的LANG，

我的/etc/ssh/ssh_config中配置了如下信息时，
![image](https://user-images.githubusercontent.com/11486075/86446562-b594a700-bd46-11ea-8ee3-8a1a80c93776.png)

在terminal中使用ssh 命令连接时，会带上语言等信息，如下：
```
ssh root@192.168.32.1 -v
```
![image](https://user-images.githubusercontent.com/11486075/86446103-0f48a180-bd46-11ea-9f84-e365a24a43ec.png)

请问是否electerm是否能支持这种方式呢？

**Comment by zxdong262** [comment]
我看看，应该可以加个设置

**Comment by degbug** [comment]
谢谢！
