### ISSUE TITLE
书签中的quickCommands,ENV:LANG保存行为不正常

### ISSUE THREAD

**Issue by degbug** [electerm/electerm#1761]
## Electerm version:
1.3.46
## Operating system(linux, macos, or windows7/8/10?):
maos
## Expected Behavior

希望能正常保存
## Can you reproduce the same behavior in other terminal:

no
## Current Behavior

1. 设置了ENV:LANG，保存以后再看，就又不见了。不知道是保存了还是没有保存。
如下图，我新增了一条书签，并设置了ENV:LANG为`zh_CN.UTF-8` 保存后，再点到设置,没有正常保存
![Kapture 2020-07-04 at 9 54 12](https://user-images.githubusercontent.com/11486075/86503062-cabc1500-bddc-11ea-8a6c-e78f53091471.gif)

2. quickCommands添加了以后，再次打开，配置没有填充，需要新加一条才能出来
如下图，我先加了一个1的命令后，保存关闭，再打开到quickCommands，没有之前加的命令，再添加一个2的命令，之前的那个1就出来了
![Kapture 2020-07-04 at 10 01 24](https://user-images.githubusercontent.com/11486075/86503143-aad92100-bddd-11ea-96d7-3dd58cc73391.gif)

3. 还有个小意见，保存的时候没有提示保存成功，新增的时候还好，左边可以看到新增了一条，修改时就不知道自己有没有改成功了，是否能加个提示呢？

**Comment by degbug** [comment]
@zxdong262 你好，我试了最新1.3.49版本，对于第二个问题似乎没有解决呢,
我设置的quickCommands,点击进去还是需要添加一个才能把之前的带出来。
![Kapture 2020-07-04 at 19 40 25](https://user-images.githubusercontent.com/11486075/86511726-688c0000-be2e-11ea-840b-5edca2102fee.gif)

**Comment by zxdong262** [comment]
@degbug 复现不了，是不是没有点保存呢？

**Comment by zxdong262** [comment]
可以给一个从打开程序的详细复现步骤吗 @degbug

**Comment by degbug** [comment]
你好，详细的步骤是这样的：
1. 打开设置->书签->选中default->新建一个ssh连接（填好服务器信息）
2.点到quickCommonds分页，添加了一个1的的快捷命令，选中勾号后，点击保存。
3.关闭窗口
4.再次打开设置->书签->选中刚刚新增的服务器->进入quickCommands分页，发现之前添加的那条1的命令没有出现。
5.添加了一个2的快捷命令，点击勾号，这个时候之前的1出现了。
下面的GIF图片是我操作的具体过程，您看看，试试跟我一样的操作会不会出现同样的问题：
![Kapture 2020-07-04 at 21 35 07](https://user-images.githubusercontent.com/11486075/86513720-0f789800-be3f-11ea-83db-25644b4f7c7d.gif)

**Comment by degbug** [comment]
补充下，我的系统是macos catalina，我试过卸载了重装，也在win10上操作了一次，也是如gif图中一样结果

**Comment by degbug** [comment]
> 你好，详细的步骤是这样的：
> 
> 1. 打开设置->书签->选中default->新建一个ssh连接（填好服务器信息）
>    2.点到quickCommonds分页，添加了一个1的的快捷命令，选中勾号后，点击保存。
>    3.关闭窗口
>    4.再次打开设置->书签->选中刚刚新增的服务器->进入quickCommands分页，发现之前添加的那条1的命令没有出现。
>    5.添加了一个2的快捷命令，点击勾号，这个时候之前的1出现了。
>    下面的GIF图片是我操作的具体过程，您看看，试试跟我一样的操作会不会出现同样的问题：
>    ![Kapture 2020-07-04 at 21 35 07](https://user-images.githubusercontent.com/11486075/86513720-0f789800-be3f-11ea-83db-25644b4f7c7d.gif)

@zxdong262

**Comment by zxdong262** [comment]
一样的步骤我复现不了

**Comment by degbug** [comment]
@zxdong262 我本地调试了下，`this.props.form.getFieldValue('quickCommands')`返回的是`undefined`
![image](https://user-images.githubusercontent.com/11486075/86553961-dba48c00-bf7e-11ea-8b04-8449be2b4326.png)
我Google了下，在前面加了一段如下的代码就可以了，我对react不熟，不知道原因。这种情况调试的时候，发现
`this.props.form.getFieldValue('quickCommands')`会走两次，第一次获取不到值，第二次就可以了
![image](https://user-images.githubusercontent.com/11486075/86554050-18708300-bf7f-11ea-9267-ed52fe6afd98.png)
