### ISSUE TITLE
无法同步gist数据

### ISSUE THREAD

**Issue by mintonzhang** [electerm/electerm#1765]
问题： 无法同步gist数据

1. 我的token和gistid是由保存起来的，在上一台电脑里面都能够使用。我回家换了一台电脑就不能用了。
![image](https://user-images.githubusercontent.com/45935465/86524952-412b4680-beb3-11ea-93f3-8482bab74dca.png)

疑惑：
我怀疑是github的token限制的，因为我使用idea的时候 一个token不能在两个设备上使用(不知道是不是这样的)。但是我token都重置一次了。。。。还是无法同步 一直转圈

**Comment by zxdong262** [comment]
我自己测试两台设备是可以的，是不是网络问题呢？

**Comment by Vrolist** [comment]
我想用gitee同步，一直都不行，版本 1.5.19
