### ISSUE TITLE
 请问文件大小显示能不能更直观一点

### ISSUE THREAD

**Issue by aiustcer** [electerm/electerm#1766]
## Electerm [version:1.3.49]
>
<img width="382" alt="截屏2020-07-05 下午1 45 58" src="https://user-images.githubusercontent.com/31919111/86526378-0bdc2400-bec6-11ea-88c1-c1fdb01226a6.png">

sftp文件管理器文件大小数值可不可以显示多少多少G 多少多少MB什么的，这样显示不直观呀?

**Comment by zxdong262** [comment]
有道理
