### ISSUE TITLE
electerm升级实在太慢了，怎样让升级过程走代理？

### ISSUE THREAD

**Issue by shinebay** [electerm/electerm#1775]
每次升级都要升级好几个小时，速度实在太慢，怎样让升级过程也走代理？

**Comment by AGou-ops** [comment]
不知道，在软件设置里设置的代理更新的时候不知道怎么回事没法用，我都是直接从网站下载新版更新的。

**Comment by zxdong262** [comment]
merge to https://github.com/electerm/electerm/issues/1777
