### ISSUE TITLE
request ssh agent forwarding feature

### ISSUE THREAD

**Issue by ycflash** [electerm/electerm#1782]
Is it possible to add ssh agent forwarding feature to make host jumping easily? ssh with opt -A / putty / SecureCRT etc. has this function with public key auth.

**Comment by zxdong262** [comment]
It is possible and in the todo list

**Comment by ssmmtt** [comment]
刚需呀，多个跳板机，好几跳！

**Comment by tianleiyiji123** [comment]
解决了么？确实很实用的功能点哈

**Comment by zxdong262** [comment]
> 解决了么？确实很实用的功能点哈

最新版已经支持
https://user-images.githubusercontent.com/1641949/273494735-da12c608-4b92-4531-a66c-654c937a4fd6.png
