### ISSUE TITLE
Windows客户端，在远程的机器上不能粘贴

### ISSUE THREAD

**Issue by joket1999** [electerm/electerm#1783]
Electerm version: v1.3.54

本地机器系统：Windows 7 and Windows 10
远程机器系统：CentOS Linux release 7.8.2003 (Core)

## Expected Behavior

本地可以复制粘贴，但远程不能粘贴。
![image](https://user-images.githubusercontent.com/6611880/87623222-8115e780-c757-11ea-9f7f-1fdc65dd8139.png)
![image](https://user-images.githubusercontent.com/6611880/87623589-4bbdc980-c758-11ea-8682-5431c459aeaa.png)

**Comment by zxdong262** [comment]
fixed
