### ISSUE TITLE
建议 Mac 版本 electerm 按 Command + R 修改为清空当前屏幕上的命令，而非直接像浏览器一样刷新页面

### ISSUE THREAD

**Issue by feeltens** [electerm/electerm#1785]
## Operating system:
macOS

## Expected Behavior
建议 Mac 版本 electerm 按 Command + R 修改为清空当前屏幕上的命令，而非直接像浏览器一样刷新页面

## Current Behavior

Mac 版本 electerm 按 Command + R 直接像浏览器一样刷新页面，连接重置到本地 localhost shell

## Possible Solution
Mac 版本 electerm 按 Command + R 修改为清空当前屏幕上的命令

**Comment by zxdong262** [comment]
我搜了一下，一般是cmd+K或者cmd+L

**Comment by nmgliangwei** [comment]
这个确实有影响，我经常不小心按Command + R，然后electerm就刷新了，打开的连接全没了。能不能作为选项设置。

**Comment by nmgliangwei** [comment]
@zxdong262 这个有计划处理吗，因为习惯了Command + R 刷页面，有时候按的快了，没切换到网页端，还在electerm，导致连接全没了，太痛苦了。
