### ISSUE TITLE
Why is there no color matching in my theme? Whatever is displayed is white

### ISSUE THREAD

**Issue by ma3252788** [electerm/electerm#1786]
## Electerm version:
1.3.31
## Operating system(linux, macos, or windows7/8/10?):
mac 10.15.3
## Expected Behavior

like this :
![image](https://raw.githubusercontent.com/electerm/electerm-resource/master/static/images/electerm.gif)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
Can you provide a screenshot?

**Comment by ma3252788** [comment]
> Can you provide a screenshot?

Hello, I have a new problem while solving this problem. I can't open the local terminal now, and it displays "Internal Service Error"

I want to take a screenshot for you, but the following error occurred:

![](https://ypyssl.machunjie.com/machunjie/20200727122252.png_machunjie.png)

**Comment by ma3252788** [comment]
This is the setting:
![setting](https://ypyssl.machunjie.com/machunjie/20200727122924.png_machunjie.png)

**Comment by zxdong262** [comment]
Can you try restart your mac to see if it works?

**Comment by ma3252788** [comment]
> Can you try restart your mac to see if it works?

I restarted the mac, but it still doesn't work. Then I checked the settings and found that it was caused by an extra space after bash.

Now, I found that my terminal has white fonts, and there is no color distinction between folders and files. Can you tell me why?

![](https://ypyssl.machunjie.com/machunjie/20200727191019.png_machunjie.png)

**Comment by ma3252788** [comment]
I modified the color scheme of the bash terminal, and now it works. It turns out that electerm uses the same color scheme as bash, and I finally understand.
Thanks for the help.
