### ISSUE TITLE
sftp上传卡顿，提示失败

### ISSUE THREAD

**Issue by heyknowit** [electerm/electerm#1791]
## Electerm version:
1.3.54

## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

文件上传成功

## Can you reproduce the same behavior in other terminal:

不能在类似于secureFX等复现该问题
## Current Behavior

_上传一个多级目录的文件夹时，首先会出现卡顿，卡顿一段时间后弹出多个Failure弹框，报错信息如下
Error: Failure at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.3.54-d2c7f6caaea7466962ee5e0ffd86cf411ecfe1b0.js:19:422720 at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.3.54-d2c7f6caaea7466962ee5e0ffd86cf411ecfe1b0.js:19:379941)_

## Steps to Reproduce

1.连接环境
2.拖动上传包含多级子目录及子文件的文件夹
3.卡顿一会进度开始变化，变化一会开始弹框Failure
4.上传貌似还在继续

**Comment by zxdong262** [comment]
正在重写sftp部分，确实有问题

**Comment by zxdong262** [comment]
合并到 #1446
