### ISSUE TITLE
书签设计建议

### ISSUE THREAD

**Issue by Jial08** [electerm/electerm#1792]
## Electerm version:
v1.3.54
## Operating system(linux, macos, or windows7/8/10?):
manjaro

建议对书签做以下修改：
1.可以固定及修改书签宽度，现在每次需要把鼠标放到书签图标上，弹出的列表有时候还没点到书签栏就又隐藏了；
2.可以重命名链接名，现在的用户名加ip的形式看着不友好

感谢作者的付出

**Comment by sunnywa** [comment]
是否可以提供提供书签栏固定在左侧的选项。
@zxdong262 
感谢作者

**Comment by Jial08** [comment]
在1.10.31版本虽然书签有固定功能了，但是固定后命令窗口区没有相应的右移，导致命令被遮盖，建议参考成熟的ssh功能，比如SecureCRT、XShell和MobaXterm等，效果如下，感谢作者的无私付出，@zxdong262
[MobaXterm](https://img.linux.net.cn/data/attachment/album/201505/19/150943x43w9qzuquezg9um.png)

**Comment by zxdong262** [comment]
最新版已修复
