### ISSUE TITLE
Quick command is error

### ISSUE THREAD

**Issue by hoan277** [electerm/electerm#1794]
Hello, i get an issue when click to add Quick command like this images

![image](https://user-images.githubusercontent.com/19620524/89104360-1943ea00-d443-11ea-94f4-3be202d9524a.png)

**Comment by zxdong262** [comment]
Can you give a detailed desc how to reproduce this error?

**Comment by zxdong262** [comment]
No need, I can reproduce it, seems it is windows problem, not able to reproduce in mac

**Comment by zxdong262** [comment]
Published new version with fix, thank you for the feedback.
