### ISSUE TITLE
password protection

### ISSUE THREAD

**Issue by perfectwebtech** [electerm/electerm#1796]
hello

there is more server if add locally then password are secured savedor

any remote third party leak informaiton or on live server somewhere capture our passwrod and server info ? 

like how ransomware comes and then they ask money so ask you if leak our information might be dangerous becuase software is very good so i might be ask this question :)

**Comment by zxdong262** [comment]
No, there is no encription for passwords, the data stored in local nedb files, will not be upload to any server, unless you choose to sync to your secret gist in sync setting.

Anyway, use it at your own risk, and you should not believe what I claim, but check it yourself or some people or company you trust.
