### ISSUE TITLE
Electerm not show files

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1797]
## Electerm version:
v1.3.54
## Operating system(linux, macos, or windows7/8/10?):
Red Hat Enterprise Linux Workstation release 7.8 (Maipo)

## Expected Behavior

be able to view / run files
## Current Behavior

I try to search and / or execute and cannot find it obviously I cannot execute it

## Steps to Reproduce

HEREEEEE!!!!!!!!!!!!!!!!!!!!!!

On Electerm:
![image](https://user-images.githubusercontent.com/28075454/89216900-df80f980-d590-11ea-811a-c0f72356b026.png)

On Linux terminal:
![image](https://user-images.githubusercontent.com/28075454/89216936-f1fb3300-d590-11ea-8ef5-1ae1580620ce.png)

**Comment by saulperez2905** [comment]
hello please your help

**Comment by zxdong262** [comment]
Did you installed it from snap or rpm? @saulperez2905

**Comment by saulperez2905** [comment]
snap

**Comment by saulperez2905** [comment]
Hi @zxdong262, This will take time?

**Comment by zxdong262** [comment]
@saulperez2905 Snap release do have this problem, I have not resolve this problem.

**Comment by zxdong262** [comment]
Mege to https://github.com/electerm/electerm/issues/1670
