### ISSUE TITLE
如何移除默认的“新连接”选项卡？

### ISSUE THREAD

**Issue by shinebay** [electerm/electerm#1808]
每次打开后都有一个默认的“新连接”的tab，启动新的ssh标签后又得重新把这个“新连接”给关闭，每次都这样很繁琐，能不能默认就没有这个“新连接”的空白tab？

**Comment by zxdong262** [comment]
除了远程连接，本地终端也是应用的一部分，所以不能去掉。

**Comment by shinebay** [comment]
@zxdong262 能否在“设置”中新增一个可以关掉该“新连接”的选项，毕竟有很大一部分人只用来远程ssh，而非本地终端
