### ISSUE TITLE
MAC上command 与 + 无法放大字体

### ISSUE THREAD

**Issue by lyhxiangyang** [electerm/electerm#1812]
我使用command - 可以减小字体， command 0 重置字体大小，但是command + 无法弄大字体

但是我点击上方的view中的zoomin是可以放大字体的。

不确定是否是我本机上的快捷键冲突还是软件问题

**Comment by zxdong262** [comment]
确实存在，感谢反馈

**Comment by zxdong262** [comment]
合并到https://github.com/electerm/electerm/issues/1453
