### ISSUE TITLE
几点给electerm的建议

### ISSUE THREAD

**Issue by shinebay** [electerm/electerm#1813]
1. 底部设置一个像xshell的快捷输入框，一次性输完全部发送数据，这点对海外主机很重要，因为ssh上输入是交互式的，海外主机连接慢，敲一个字母很久才显示出来，有个输入框把命令全部敲进去统一全部发出去这样方便很多
2. 左侧的那个固定栏，能否不用时隐藏，在鼠标hover时再显示出来，或者顶部设置一个按钮，点击才下拉显示该固定栏，这点mobaxterm做得很好，增加了一个compact模式：尽可能给界面留出更多空间。electerm左侧固定栏那几十个像素特别在垂直分屏的情况下让空间显得更加寒酸
3. 增加断线自动重连的功能
4. 增加一个亮色主题
5. 感谢作者的辛苦付出！

**Comment by junmoxiao** [comment]
第一点可以参考mosh的方式
