### ISSUE TITLE
sz传输文件到99% 卡主

### ISSUE THREAD

**Issue by dashi6174** [electerm/electerm#1819]
ssh登录到一台Ubuntu，使用sz传输一个文件：
root@ubuntu:~# sz b.py

然后，在传输到99%的时候卡主了。
![RTX截图未命名](https://user-images.githubusercontent.com/1617266/92382626-7a946280-f13f-11ea-8cb5-ec923c2cb3fe.jpg)

**Comment by zxdong262** [comment]
sz/rz 模块不是很可靠，尤其对大文件，不过目前也没有其他选择

**Comment by lonnywong** [comment]
@dashi6174 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
