### ISSUE TITLE
mac sftp只有本地没有远程的。

### ISSUE THREAD

**Issue by wukai1211** [electerm/electerm#1820]
mac10.15.6中
electerm V1.4.4
连接服务器后，文件管理只显示本地文件，没有远程文件。如下图：
![截屏2020-09-10 上午9 29 07](https://user-images.githubusercontent.com/12652827/92671201-39bb6a00-f348-11ea-9566-75235fa0832f.png)
这是怎么回事，重装了好几次了。是我本地环境少装了什么吗？

**Comment by zxdong262** [comment]
ssh-config 目前只是读取命令并且运行在本地终端而已，还不支持sftp

**Comment by zxdong262** [comment]
@wukai1211 新建书签是没问题的
