### ISSUE TITLE
deepin 15.11 sftp文件过多就会抛出异常

### ISSUE THREAD

**Issue by tnnevol** [electerm/electerm#1821]
electerm version 1.4.4

[2020-09-11 09:39:50.439] [error] {
  constructor: 'Error',
  stack: 'Error\n' +
    '    at file:///opt/electerm/resources/app.asar/assets/js/electerm.1.4.4-e0874f426d428cf8c4c91040592d1b4e8c0c5f26.js:287:383517\n' +
    '    at WebSocket.n (file:///opt/electerm/resources/app.asar/assets/js/electerm.1.4.4-e0874f426d428cf8c4c91040592d1b4e8c0c5f26.js:287:383067)'
}
[2020-09-11 09:40:15.446] [debug] sftp error No such file

**Comment by zxdong262** [comment]
确实如此，正在重写sftp部分 -> https://github.com/electerm/electerm/issues/1446
