### ISSUE TITLE
feat: add classification support for quict command, and make it fixable in the bottom

### ISSUE THREAD

**Issue by xmmgithub** [electerm/electerm#1822]
## Electerm version:
Electerm 1.4.4

**Comment by xmmgithub** [comment]
快速命令真的很重要啊，就像finalshell或者secureCrt的那种，可以直接点的，求求小编整一个，救救孩子吧，谢谢啦

**Comment by zxdong262** [comment]
@xmmgithub 最新版本的快速命令放在了底部，你说的直接点是什么意思呢，可以给个截图吗？

**Comment by xmmgithub** [comment]
![图片](https://user-images.githubusercontent.com/16660844/95808975-3bf65700-0d40-11eb-8a94-88de8eaae43e.png)
就像上图中的securecrt的快速命令，它可以固定在底部，并且会进行分组，然后左边的下拉框可以切换分组。
当前分组的所有命令会显示在命令栏里，直接点击就能发送命令，比较高效快捷。

目前的版本，需要先点击“快速命令”，再在里面查找，比较费劲，对于开发人员还是略影响效率的。

或者也可以参照finalshell的方式，在底部有个快速命令的面板：
![图片](https://user-images.githubusercontent.com/16660844/95809360-27ff2500-0d41-11eb-9da5-e02437f14640.png)

小编你也可以看哪种方式比较好实现，最重要的是能够分组，以及快速地点点点~

祝好~

**Comment by xmmgithub** [comment]
@zxdong262

**Comment by zxdong262** [comment]
最新版已经加入标签分组
