### ISSUE TITLE
终端直接回车，报错问题

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#1835]
## Operating system(linux, macos, or windows7/8/10?):
macOS Catalina

## Expected Behavior

点击加号创建“新连接”，在下方批量输入个命令比如ls，在回到终端直接回车，就会显示“出错了”。

这是错误信息
Need at least a key or a value or a label (only for OptGroup) for [object Object]
Error: Need at least a key or a value or a label (only for OptGroup) for [object Object] at A (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1.js:283:76522) at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1.js:283:109539 at Array.forEach (<anonymous>) at Function.we.getOptionsInfoFromProps (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1.js:283:109512) at we.getDerivedStateFromProps (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1.js:283:108613) at Lc (file:///Applications/electerm.app/Contents/Resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1:67:290) at rh (file:///Applications/electerm.app/Contents/Resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1:101:395) at zj (file:///Applications/electerm.app/Contents/Resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1:228:490) at Th (file:///Applications/electerm.app/Contents/Resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1:152:223) at tj (file:///Applications/electerm.app/Contents/Resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.5.4-f6ccfd6bc8f046c554fb47a0fa2967e00e0877b1:152:152)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
"在回到终端直接回车" 这个是什么操作，怎么回到？直接点击终端吗？

**Comment by zxdong262** [comment]
哦我知道了，感谢反馈

**Comment by bb7788** [comment]
> "在回到终端直接回车" 这个是什么操作，怎么回到？直接点击终端吗？

就是在打开的“新连接” 终端里面直接敲回车键
