### ISSUE TITLE
macOS 10.15.7上安装完成之后不显示界面

### ISSUE THREAD

**Issue by 36k** [electerm/electerm#1840]
## Electerm version:
1.5.7
## Operating system(linux, macos, or windows7/8/10?):
macOS 10.15.7
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
是点击图标无反应吗？

**Comment by 36k** [comment]
> 是点击图标无反应吗？

导航栏显示已经打开了，但是不显示界面。
![Uploading 截屏2020-10-07 下午9.06.00.png…]()

**Comment by zxdong262** [comment]
可以命令行运行 `/Applications/electerm.app/Contents/MacOS/electerm` 看看报什么错误吗

**Comment by 36k** [comment]
<img width="1438" alt="企业微信截图_173fa4b9-8b6e-4d34-a501-577e4cf7b952" src="https://user-images.githubusercontent.com/44507667/96344747-dbaf3e80-10cc-11eb-8a39-f32e2578c297.png">

**Comment by 36k** [comment]
hosts 增加 127.0.0.1 localhost 可以打开了

**Comment by zxdong262** [comment]
好的，那就关闭了
