### ISSUE TITLE
上传文件一直99%

### ISSUE THREAD

**Issue by nondevops** [electerm/electerm#1842]
## Expected Behavior

![image](https://user-images.githubusercontent.com/12181410/95649485-2864a980-0b10-11eb-9ddd-2293573e1159.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
目前的zmodem module功能有缺陷 实测对于大文件几乎必定无法传输 -> https://github.com/electerm/electerm/issues/1401

**Comment by lonnywong** [comment]
@nondevops 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
