### ISSUE TITLE
RPM release number is wrong

### ISSUE THREAD

**Issue by sixg0000d** [electerm/electerm#1847]
## Electerm version:
1.5.7

## Operating system(linux, macos, or windows7/8/10?):
Linux

## Expected Behavior

The release number of rpm package released may be smaller, more likely to be 1.

## Steps to Reproduce

1.Download the rpm package from [the release](https://github.com/electerm/electerm/releases), then:
```
rpm -qi ./*.rpm
```
2.it show me
```
Release: 508
```

## Detailed Description

The most of RPM build guide / guideline is guiding us the release number should reset when software is update, like:
https://rpm-packaging-guide.github.io/
https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_release_and_post_release_versions

If there is a problem with the package and it is not related to the source code of electerm itself but related to packaging, you can rebuild with same version and increase the release number, it's beneficial to RPM version and upgrade management.

I have tried to build the RPM package follow the README to figure out why the release number is so large, but the package I built locally, twice, the release numbers are 1 .

## Suggestions?

> The number of times this version of the software was released. Normally, set the initial value to 1%{?dist}, and increment it with each new release of the package. Reset to 1 when a new Version of the software is built.

And the `%{?dist}` is a rpm macro, the results are like `el8`, `fc32`, but it's can only expansions for rpmbuild system, so just ignore that, set release value to `1` each release.

**Comment by zxdong262** [comment]
Thank you @sixg0000d I will investigate

**Comment by zxdong262** [comment]
Fixed in latest release
