### ISSUE TITLE
ET可以使用端口隧道吗？

### ISSUE THREAD

**Issue by kay-cl0324** [electerm/electerm#1848]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
暂时还没有这个功能

**Comment by zxdong262** [comment]
你是想怎么使用呢 是用`ssh -R`，如果是这种情况建议保存一个快速命令

**Comment by kay-cl0324** [comment]
就是类似于多台服务器，只有一台公网ip，我从公网去连接其他服务的地址，我可以通过端口隧道，去实现保存连接会话，也可以通过透端口来进行本地localhost访问。



wangcl@huayunworld.com
 
发件人： ZHAO Xudong
发送时间： 2020-10-29 10:38
收件人： electerm/electerm
抄送： kay-cl0324; Author
主题： Re: [electerm/electerm] ET可以使用端口隧道吗？ (#1848)
你是想怎么使用呢 是用ssh -R，如果是这种情况建议保存一个快速命令

**Comment by zxdong262** [comment]
最新版已经加入ssh tunnel支持

**Comment by Facebooksx** [comment]
> 

你好，隧道如何设置？

**Comment by zxdong262** [comment]
> > 
> 
> 你好，隧道如何设置？

![Screen Shot 2023-08-03 at 11 37 32](https://github.com/electerm/electerm/assets/1641949/ae71563c-9a21-474f-841a-5831f7ecee84)
![Screen Shot 2023-08-03 at 11 37 48](https://github.com/electerm/electerm/assets/1641949/f97cc237-5076-4230-a029-3548948f916d)

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/wiki/How-to-use-ssh-tunnel
