### ISSUE TITLE
使用命令 exit 退出后，光标无法移动

### ISSUE THREAD

**Issue by bo-don** [electerm/electerm#1852]
## Electerm 版本
  1.5.13

## 操作系统
  win10

## 问题
 使用命令 exit 退出后，光标无法移动

## 步骤
  1.  打开软件，正常打开一个连接
  2.  输入命令 exit

## 预期结果
  系统关闭当前的标签或者光标仍可以正常使用

## 实际结果
  光标反应![微信截图_20201027130400](https://user-images.githubusercontent.com/35206653/97259097-f152ff80-1854-11eb-9035-af7b8ef82df5.png)
## 建议
  可关闭当前标签或者使光标仍可以正常使用

**Comment by zxdong262** [comment]
合并到 https://github.com/electerm/electerm/issues/1802

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1852
