### ISSUE TITLE
UI使用起来很卡，感觉掉帧严重

### ISSUE THREAD

**Issue by cmmchina** [electerm/electerm#1860]
## Operating system(linux, macos, or windows7/8/10?):
MacOS 10.15.7  Macbook pro 13 2107
## Expected Behavior

软件UI使用时候比较卡，感觉像掉帧，软件是默认设置。
另外希望能有独立窗口模式
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
是打开就感觉卡吗？

**Comment by cmmchina** [comment]
是的，打开就感觉UI卡



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHAO Xudong"<notifications@github.com&gt;; 
发送时间: 2020年10月29日(星期四) 上午10:36
收件人: "electerm/electerm"<electerm@noreply.github.com&gt;; 
抄送: "CMMChina"<cmmth@cmmchina.cn&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [electerm/electerm] UI使用起来很卡，感觉掉帧严重 (#1860)





 
是打开就感觉卡吗？

**Comment by zxdong262** [comment]
@cmmchina 可以activity monitor里看看cpu和内存占用如何吗？

**Comment by cmmchina** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "electerm/electerm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月29日(星期四) 中午1:07
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"CMMChina"<cmmth@cmmchina.cn&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] UI使用起来很卡，感觉掉帧严重 (#1860)





 
@cmmchina 可以activity monitor里看看cpu和内存占用如何吗？

**Comment by zxdong262** [comment]
@cmmchina 猜测大概是优化不行，对机器性能要求高。

**Comment by cmmchina** [comment]
在我独显的mac上感觉还好，没有这种掉帧的感觉

**Comment by hxnan** [comment]
同感，我在堡垒机（windows server）上跑，也是很卡，在自己笔记本上跑，就还好。
