### ISSUE TITLE
1.5.13版本开始，sftp远程目录到根目录后再进文件夹报错

### ISSUE THREAD

**Issue by DifferentFire** [electerm/electerm#1861]
## Electerm version:
1.5.15
## Operating system(linux, macos, or windows7/8/10?):
windows 10
## Current Behavior

Error: No such file at file:///B:/electerm/resources/app.asar/assets/js/electerm.1.5.15-4233bc3678dcc1074f07f6cca91db4cf35b49a76.js:291:425042 at WebSocket.n (file:///B:/electerm/resources/app.asar/assets/js/electerm.1.5.15-4233bc3678dcc1074f07f6cca91db4cf35b49a76.js:291:399738
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
最新版应该解决了
