### ISSUE TITLE
1.5.15版本，打开连接有报错，但不影响正常使用

### ISSUE THREAD

**Issue by Ixiaodao** [electerm/electerm#1864]
## Electerm version:
1.5.15、1.5.18
## Operating system(linux, macos, or windows7/8/10?):
windows 10 ltsc
## Current Behavior

连接我自己的云服务器正常，连接公司堡垒机成功后有提示：WARNING: Terminal type 'xterm-256color' is not supported, 'xterm' will be used as default.
然后后下角就有以下报错信息了
General failure
Error: General failure at file:///D:/Scoop/apps/electerm/1.5.15/resources/app.asar/assets/js/electerm.1.5.15-4233bc3678dcc1074f07f6cca91db4cf35b49a76.js:291:425042 at WebSocket.n (file:///D:/Scoop/apps/electerm/1.5.15/resources/app.asar/assets/js/electerm.1.5.15-4233bc3678dcc1074f07f6cca91db4cf35b49a76.js:291:399738)
## Steps to Reproduce

1.新建一个连接
2.在应用首页从书签栏进行连接，就出现了这个错误

**Comment by zxdong262** [comment]
有没有试试新版本还有这个问题吗？
