### ISSUE TITLE
Upgrade database is not responding

### ISSUE THREAD

**Issue by hoan277** [electerm/electerm#1865]
Electerm version: 1.5.15
Deepin Linux 20
Problem: Stuck here, can't continue
![image](https://user-images.githubusercontent.com/19620524/97838631-31adf400-1d13-11eb-968a-e89aa47a1fa6.png)

I'm try install via deb and Deepin Store

**Comment by zxdong262** [comment]
deb and Deepin Store? Which one? or both? @hoan277

**Comment by zxdong262** [comment]
@hoan277 Should fix now in latest release
