### ISSUE TITLE
能否支持zmodem

### ISSUE THREAD

**Issue by zhouqian486** [electerm/electerm#1873]
新版本能否支持zmodem

**Comment by zhouqian486** [comment]
Zmodem aways 99% can't finish

**Comment by zxdong262** [comment]
已知问题是对大文件支持不好，暂时没有其他的替代库

**Comment by lonnywong** [comment]
@zhouqian486 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
