### ISSUE TITLE
windows版本打开服务器目录报错

### ISSUE THREAD

**Issue by West121** [electerm/electerm#1874]
## Operating system(linux, macos, or windows7/8/10?):win10

Error: No such file
    at file:///D:/dev/electerm-1.5.19-win-x64/resources/app.asar/assets/js/electerm.1.5.19-9361fe576bd3fda2878745e84952c4842b441b3f.js:291:424976
    at WebSocket.n (file:///D:/dev/electerm-1.5.19-win-x64/resources/app.asar/assets/js/electerm.1.5.19-9361fe576bd3fda2878745e84952c4842b441b3f.js:291:399896)

**Comment by zxdong262** [comment]
@West121 可以继续使用吗？只是报错？

**Comment by West121** [comment]
不能使用了。点不进去

**Comment by West121** [comment]
@zxdong262 不能使用了。点不进去

**Comment by West121** [comment]
> @West121 可以继续使用吗？只是报错？

双击不能使用。
![image](https://user-images.githubusercontent.com/29170680/98919153-74d54780-2509-11eb-8fb9-7b75074427ca.png)

**Comment by West121** [comment]
> > @West121 可以继续使用吗？只是报错？
> 
> 双击不能使用。
![image](https://user-images.githubusercontent.com/29170680/98919266-8f0f2580-2509-11eb-8d76-262f82ad615d.png)
