### ISSUE TITLE
在我的mac上启动不了，启动后没有任何窗口出现。

### ISSUE THREAD

**Issue by yaozaiwind** [electerm/electerm#1876]
## Electerm version:
1.5.19.1
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

正常启动。。。。
## Can you reproduce the same behavior in other terminal:

i don't have another computernow
## Current Behavior

启动后，没有任何窗口出现。昨天晚上刚下载的时候可以用，今天打开就再也启动不了了。重装也没有用。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以看看 https://github.com/electerm/electerm/issues/1840 是不是一样的问题？

**Comment by yaozaiwind** [comment]
是一个问题。我添加了host好使了。
