### ISSUE TITLE
滚动条无法选中拖动

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#1888]
## Electerm version: 
1.7.10

## Operating system(linux, macos, or windows7/8/10?):
centos8 xfce4

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
哪里的滚动条？可以截图看看吗？

**Comment by sguphil** [comment]
![图片](https://user-images.githubusercontent.com/8896611/99057604-fcd55300-25d6-11eb-9d07-4206406143ce.png)


右下角很细的蓝色滚动条无法选中

**Comment by androidfans** [comment]
+ 1. Ubuntu 同样的问题. 鼠标到边缘以后 会进入resize模式 .  无法选中滚动条
