### ISSUE TITLE
横向或者纵向切屏后，怎么关闭切屏

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#1889]
## Electerm version:
1.7.10
## Operating system(linux, macos, or windows7/8/10?):
centos8 xfce4 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
请问什么是切屏？

**Comment by sguphil** [comment]
![图片](https://user-images.githubusercontent.com/8896611/99204942-1c949300-27f2-11eb-835a-95cc6f77a6d8.png)
右上角横向或者纵向切割屏幕出来的窗口不知道怎么关闭？

**Comment by zxdong262** [comment]
有个bug，关闭按钮没有显示，就在那两个图标左边

**Comment by zxdong262** [comment]
在最新版本修复了，感谢反馈
