### ISSUE TITLE
鼠标移动到左下角自动弹出的快捷命令对话框点击旁边空白无法关闭

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#1891]
## Electerm version:
1.7.17
## Operating system(linux, macos, or windows7/8/10?):
centos8 xfce4
## Can you reproduce the same behavior in other terminal:
鼠标移动到左下角自动弹出的快捷命令对话框, 点击旁边空白大概率出现无法关闭的现象

## Current Behavior

鼠标移动到左下角自动弹出的快捷命令对话框, 点击旁边空白大概率出现无法关闭的现象
![图片](https://user-images.githubusercontent.com/8896611/99206544-9c246100-27f6-11eb-9f8e-5919559557d8.png)

## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?
可否改回有个箭头点击一下才弹出这些快捷命令框

**Comment by JinHsu** [comment]
建议不要弹出来提示
