### ISSUE TITLE
快速命令浮窗，经常性收不回去，一直显示出来，影响输入

### ISSUE THREAD

**Issue by ansoda** [electerm/electerm#1899]
## Electerm version:
v1.7.18
## Operating system(linux, macos, or windows7/8/10?):
win10

感觉在开多个ssh窗口切换时，使用快速命令，经常性快速命令浮窗会收不回去。

**Comment by androidfans** [comment]
+ 1.  hover的时候会弹出来. 但是hover走的时候 不会自动收起来
