### ISSUE TITLE
添加快捷命令输入框BUG

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#1902]
## Electerm version:

v1.7.18

## Operating system(linux, macos, or windows7/8/10?):

mac 10.15.5 (19F101)

## Expected Behavior

添加快捷命令输入框，一直显示在最前面不会消失掉，非常碍事，都挡住命令的输入了。

[截图](https://i.loli.net/2020/11/18/nSo4fjlhVy72OmQ.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by liter7** [comment]
同，最好是点击之后才弹出，不然鼠标放入就弹出太频繁了😂

**Comment by zxdong262** [comment]
升级到最新版就好了
