### ISSUE TITLE
用zsh 每次用electerm打开会出现一行log  manpath: can't set the locale; make sure $LC_* and $LANG are correct

### ISSUE THREAD

**Issue by androidfans** [electerm/electerm#1908]
## Electerm version:
1.9.0
## Operating system(linux, macos, or windows7/8/10?):
ubuntu 18.04

用zsh 每次用electerm打开会出现一行log  manpath: can't set the locale; make sure $LC_* and $LANG are correct

然后在electerm里面执行python脚本 set locale 也set失败.   使用系统的terminal可以set成功. 
新版本刚打开也比之前的卡了

**Comment by zxdong262** [comment]
如果用bash正常吗？

**Comment by androidfans** [comment]
bash 正常

**Comment by sguphil** [comment]
是不是和我遇到的类似？ #1905 
手动配置以下项后中文显示恢复正常了：
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

**Comment by sguphil** [comment]
确实打开明显比1.8的之前版本卡了很多，希望有能改进，并且我遇到了tail -f log 的时候 ctrl+c很难退出来，感觉是终端响应用户输入很慢
