### ISSUE TITLE
登录成功后自动执行指定脚本

### ISSUE THREAD

**Issue by wxz2561** [electerm/electerm#1910]
你好，有一个个人认为比较有意义的功能，就是指定一个服务器已经存在的脚本，在登录成功之后自动执行该脚本做一些事情，例如自动跳转到其他机器，谢谢。

**Comment by zxdong262** [comment]
新建书签有一个Run script可以做这个事情

**Comment by wxz2561** [comment]
> 新建书签有一个Run script可以做这个事情

啊我竟然没看到，找到了，谢谢
