### ISSUE TITLE
外接多个显示器时，功能与显示有问题

### ISSUE THREAD

**Issue by iamlinix** [electerm/electerm#1913]
## Electerm version: 
1.9.0

## Operating system(linux, macos, or windows7/8/10?): 
windows 10

## Expected Behavior
在外接多个显示器时：
1. 点击“最大化”按钮，窗口应该在当前显示器最大化；
2. 命令行工作区域，应该自动利用所有可用区域

## Can you reproduce the same behavior in other terminal:
其它工具无上述两类问题

## Current Behavior
1.  点击“最大化”按钮后，程序窗体自动跳回到主显示器，只在主显示器最大化；但是双击窗体上沿，窗体便可以在当前显示器最大化；
2. 在分辨率较大的显示器"2560 x 1440"最大化窗口时，有相当部分的区域，不能作为命令行的工作区域，不能显示任何内容, 如图：
https://drive.google.com/file/d/1WcffuaIF1feJKqSlyDbVyGZINXbtC81j/view?usp=sharing

## Steps to Reproduce
1. 打开程序，在非主显示器点击“最大化”按钮
2. 在大分辨率显示器上，最大化窗口，查看工作区域

**Comment by zxdong262** [comment]
> 在分辨率较大的显示器"2560 x 1440"最大化窗口时，有相当部分的区域，不能作为命令行的工作区域，不能显示任何内容, 如图
这个可以给个详细的复现步骤吗，我用1920高的显示器也复现不了（显示器竖着）

**Comment by iamlinix** [comment]
> > 这个可以给个详细的复现步骤吗，我用1920高的显示器也复现不了（显示器竖着）

这个问题，现在好像不复现了。

我只有在**第一次使用的时候**，在大分辨率的显示器上，无论是双击窗口最大化，还是手动拖动改变窗口大小，都会出现，像截图一样的效果，最下方会有一片区域无法使用，但我report了这个bug之后不久，不知道什么时候，这个问题，它自己就好了，所有区域就都能填满了，现在我自己的显示器上也复现不了了
