### ISSUE TITLE
sftp双击根目录下的目录报错【No such file     at file:///D:/java/electerm/resources/app.asar/assets/js/electerm.js...】

### ISSUE THREAD

**Issue by supmry** [electerm/electerm#1920]
Electerm version: v1.9.14

Operating system(linux, macos, or windows7/8/10?): windows10

Expected Behavior
sftp双击根目录下的目录报错【[2020-11-24 20:51:52.329] [error] Error: No such file
    at file:///D:/java/electerm/resources/app.asar/assets/js/electerm.js?1.9.14:2:363429
    at WebSocket.n (file:///D:/java/electerm/resources/app.asar/assets/js/electerm.js?1.9.14:2:295414)】

## Can you reproduce the same behavior in other terminal:
![微信截图_20201124210133](https://user-images.githubusercontent.com/16367988/100098133-8e2aac00-2e98-11eb-82e8-5819e366e66e.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
本地的根目录还是服务器端的根目录呢？

**Comment by supmry** [comment]
服务器根目录，直接双击“/”下的目录（例如sys）会报错，但是通过顶部输入框输入“/sys”回车可以正常打开"/sys"目录,，打开后可以正常双击打开“/sys”下的目录。
sys是个例子，“/”目录下所有的目录双击都会出现这样情况
早上又看到新版本了，不知道新版本有没有同样问题
![aaa](https://user-images.githubusercontent.com/16367988/100173307-34140000-2f05-11eb-8a49-5349588fc8a5.png)

**Comment by supmry** [comment]
![aaa](https://user-images.githubusercontent.com/16367988/100173371-586fdc80-2f05-11eb-87c6-048592b0410c.png)

**Comment by wen-carl** [comment]
版本1.5之前好像没有这个问题，最近几个版本都有这个问题

**Comment by supmry** [comment]
> 版本1.5之前好像没有这个问题,最近几个版本都有这个问题

最近看到新版本就更新，每次都希望新版本能修复这个问题
