### ISSUE TITLE
1.9.19无法打开

### ISSUE THREAD

**Issue by chaser8** [electerm/electerm#1924]
## Electerm version:
1.9.19
## Operating system(linux, macos, or windows7/8/10?):
macos 10.14.6 
## Expected Behavior

打开程序报错
![image](https://user-images.githubusercontent.com/10428821/100190364-0d67c080-2f29-11eb-9be5-f3a1e6410e42.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
显示器的情况如何？如果用回之前版本就没有这个错误吗？

**Comment by chaser8** [comment]
> 显示器的情况如何？如果用回之前版本就没有这个错误吗？

确认了外接显示器双屏才有出现，以前1.5老版本没问题

**Comment by zxdong262** [comment]
@chaser8 可以试试最新版还有没有问题吗
