### ISSUE TITLE
编辑文件时不能查看终端之前输出的内容

### ISSUE THREAD

**Issue by chenrizhi** [electerm/electerm#1925]
## Electerm version:
v1.9.19
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

使用vim等工具编辑文件时，期望可以通过滚动鼠标滚轮来显示终端之前输出的内容
## Current Behavior

使用vim等工具编辑文件时，会占用整个终端，滚动鼠标滚轮只会滚动文本中的内容，相当于按键盘的上下键。此时我想看终端之前输出的内容就只能退出vim了，比较不方便。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
其他终端不是这样的吗？

**Comment by chenrizhi** [comment]
> 其他终端不是这样的吗？

不是的，windows平台的putty、xshell等终端，都可以，跨平台的finalshell也可以。

不知道electerm能不能改成这样的行为，真的会方便很多。

**Comment by zxdong262** [comment]
https://github.com/xtermjs/xterm.js/issues/3184 看起来暂时实现不了

**Comment by zxdong262** [comment]
在最新版支持cmd or ctrl + ArrowUp 显示normal buffer内容，你可以试试
