### ISSUE TITLE
希望能在会话有新内容被打印时，高亮对应的 Tab 标签

### ISSUE THREAD

**Issue by iamlinix** [electerm/electerm#1929]
## Electerm version:
All

## Operating system(linux, macos, or windows7/8/10?):
All

## Expected Behavior

特别是在同时打开多个连接，在不同机器上调试时，如果在任意的会话中，有新的内容打印出来了，比如：

a. 我在一个窗口中编辑文件，另一个窗口在运行一个耗时的任务，任务完成后会有一个成功或者失败的文本输出，我想要及时知晓；
b. 我在当前窗口做一个网络操作，等待另一个连接里的监听程序的输出内容;
c. 我在一个窗口操作，另一个窗口在 tail 日志
d. 等等等等

如果能够实时地将所有，有新的内容输出的 Tab 高亮，能很大提高工作效率，我之前使用 MobaXterm，就有这个功能，感觉非常实用，希望能移植过来

## Can you reproduce the same behavior in other terminal:

MobaXterm 自带此功能

**Comment by Wjt11** [comment]
这个功能需要在设置里边打开吗，我看现在好像没有这个功能。现在是某个tab页有输出时，他和其他的tab页并没有区别。
