### ISSUE TITLE
希望 mac 版本能够全屏幕 独立屏幕空间

### ISSUE THREAD

**Issue by yj-stack** [electerm/electerm#1931]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
能详细说说吗？

**Comment by pastcloud** [comment]
同想达到这个效果，希望Mac版本的最大化是最大化到一个新的屏幕之上而不是单纯的占满主屏幕

**Comment by zxdong262** [comment]
> 同想达到这个效果，希望Mac版本的最大化是最大化到一个新的屏幕之上而不是单纯的占满主屏幕

最大化到一个新的屏有什么用处，可以解释一下吗？

**Comment by yj-stack** [comment]
mac 程序独立屏幕空间 方便划屏切换程序,
![image](https://user-images.githubusercontent.com/33690544/100690948-99169c80-33c2-11eb-9040-5c2f85ced504.png)
截图, 程序左上角

**Comment by zxdong262** [comment]
为了支持程序透明牺牲了全屏之类的功能，目前还没有解决方案
https://github.com/electron/electron/issues/15704

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1707

**Comment by yj-stack** [comment]
regrettable😭

**Comment by you-notfish** [comment]
> 为了支持程序透明牺牲了全屏之类的功能，目前还没有解决方案
> [electron / electron＃15704](https://github.com/electron/electron/issues/15704)
个人觉得可以选择放弃程序透明添加全屏功能的话不是更好
