### ISSUE TITLE
命令行几乎无法输入中文

### ISSUE THREAD

**Issue by iamlinix** [electerm/electerm#1933]
## Electerm version:
1.9.24

## Operating system(linux, macos, or windows7/8/10?):
Windows 10

## Expected Behavior

能够正常输入中文

## Can you reproduce the same behavior in other terminal:

NO

## Current Behavior

好像是只能输入两个中文字符，再往后输入，命令行无反应，光标也不移动

## Steps to Reproduce

1. 打开 vim 等文本编辑器，或者直接就在 shell 下尝试输入中文
2. 只有前两个字符能正常显示，后面输入的内容均无法显示
3. 我用的是搜狗五笔输入法
4.

**Comment by zxdong262** [comment]
拼音输入法可以吗？

**Comment by iamlinix** [comment]
> 拼音输入法可以吗？

专门下了一个搜狗拼音试了一下，拼音是可以，只有五笔是有问题的

**Comment by nuccch** [comment]
我的v1.14.0，在Windows10 搜狗拼音 在命令行下 无法输入中文

**Comment by sprainJinyu** [comment]
我的v1.13.4，在windows10下，搜狗拼音无法输入中文

**Comment by sprainJinyu** [comment]
> 我的v1.13.4，在windows10下，搜狗拼音无法输入中文

升级最新版本【1.17.16】，就可以了

**Comment by zxdong262** [comment]
merge to https://github.com/electerm/electerm/issues/2232
