### ISSUE TITLE
执行 top 命令，在窗口中按空格键时，窗口内容会向左偏移，右边会多出一片空白区域

### ISSUE THREAD

**Issue by iamlinix** [electerm/electerm#1936]
## Electerm version:
1.9.24

## Operating system(linux, macos, or windows7/8/10?):
Win 10

## Expected Behavior

窗口应该正常显示

## Can you reproduce the same behavior in other terminal:

NO

## Current Behavior

在执行 top 命令时，按空格键刷新，tab页和左边栏，会整体向左偏移，右边会出现一小片空白区域，如图，在窗口全屏的情况下，左边栏，会整体被挡住，但是按回车刷新，则不会有这个问题

https://drive.google.com/file/d/1mBoml6S_zEn8YH8hhLwhQ5WNmLXyexpf/view?usp=sharing

## Steps to Reproduce

1. 连接上任意 Linux 服务器，执行 top 命令
2. 按空格键刷新

**Comment by zxdong262** [comment]
我能复现，我也不知道咋回事

**Comment by iamlinix** [comment]
> 我能复现，我也不知道咋回事

在设置里，把渲染类型，从 canvas 换成 dom，这个 bug 就消失了，所以应该跟渲染类型有关

**Comment by zxdong262** [comment]
最新版本已经没有这个问题
