### ISSUE TITLE
RZ/SZ FAIL

### ISSUE THREAD

**Issue by gwjgithub** [electerm/electerm#1937]
使用rz sz 快捷上传下载会卡在�*B00000000000000　这样的状态下，然后连接会断开

**Comment by zxdong262** [comment]
使用其他终端会发生么

**Comment by gwjgithub** [comment]
不会，试了另外二款

**Comment by zxdong262** [comment]
操作系统，electerm软件版本，服务器端rz版本可以提供吗

**Comment by gwjgithub** [comment]
mac 10.15.7  electerm 1.9.31  我跟了最近连续的几个版本，发现都不行。

**Comment by zxdong262** [comment]
@gwjgithub 服务器端rz什么版本呢

**Comment by zxdong262** [comment]
@gwjgithub 另外你可以试试连接本机吗，使用lrz是不是也会有问题？

**Comment by gwjgithub** [comment]
![image](https://user-images.githubusercontent.com/34211554/100688123-8dc07280-33bc-11eb-8fb5-67273a7ef7de.png)
也是同样的。服务端版本lrzsz-0.12.20-36.el7.x86_64　在很早之前的这个软件版本是可以用的

**Comment by zxdong262** [comment]
可以发log看看吗？
<img width="832" alt="Screen Shot 2020-12-01 at 13 48 06" src="https://user-images.githubusercontent.com/1641949/100702073-e81cfb80-33db-11eb-8585-c5a41b575a9f.png">

**Comment by gwjgithub** [comment]
![image](https://user-images.githubusercontent.com/34211554/100714083-3fc56200-33f0-11eb-8bca-5dcea67bdee6.png)

**Comment by zxdong262** [comment]
@gwjgithub 触发断线以后就这这个log吗？

**Comment by gwjgithub** [comment]
这个log不太确定什么时候产生的，但是在卡住时，就已经可以看到这条log　现象非常像像iterm2 在没有配置rz/sz的时候

**Comment by zxdong262** [comment]
有其他电脑和服务器可以试试吗？我也想不出什么原因

**Comment by harvies** [comment]
同卡住

**Comment by gwjgithub** [comment]
你自己的lrz 或远程服务器，并不会遇到吗？

**Comment by zxdong262** [comment]
> 你自己的lrz 或远程服务器，并不会遇到吗？

当然不会。

**Comment by gwjgithub** [comment]
![image](https://user-images.githubusercontent.com/34211554/101657667-1c995300-3a7f-11eb-9324-89fa154b4dcb.png)
升级系统到mac big sur lrzsz重装，还是基本同样的问题

**Comment by sunhailin-Leo** [comment]
@gwjgithub @harvies 
* 你们是用跳板机登进去才会出现嘛？

**Comment by gwjgithub** [comment]
本地rz也不行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "electerm/electerm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 中午11:14
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"-"<58059191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] RZ/SZ FAIL (#1937)





 
@gwjgithub @harvies
  
你们是用跳板机登进去才会出现嘛？

**Comment by darrenliuwei** [comment]
我好像很早之前也遇到过，后来升级到最新版就可以了

**Comment by gwjgithub** [comment]
很早之前的版本，我有段时间是可以的。包括现在最新版及之前的多个版本都不行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "electerm/electerm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 中午1:19
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"-"<58059191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] RZ/SZ FAIL (#1937)





 
我好像很早之前也遇到过，后来升级到最新版就可以了

**Comment by garywu520** [comment]
Don't use，+1

**Comment by lonnywong** [comment]
Try trzsz ( trz / tsz ), similar to rz/sz, and compatible with tmux.

Upgrade electerm to 1.19 or higher. Install trzsz on the server: https://github.com/trzsz/trzsz
