### ISSUE TITLE
是否可以考虑支持导入iterm的配色文件？

### ISSUE THREAD

**Issue by reinstallsys** [electerm/electerm#1938]
感觉electerm的很多设计非常好，使用后第一时间推荐给了周围的同学们，多谢作者提供这么好的shell工具！

不知道是否可以在配色上更加丰富一些，如果可以导入iterm的配色文件，这样就可以使用大量现成的iterm配色，以下是配色文件的下载地址：

https://iterm2colorschemes.com/

**Comment by Liuhongdan** [comment]
It's a very good feature to have. I want this color scheme also.
Please support.

Thank you.

**Comment by zxdong262** [comment]
Submit a PR, try to add support to electerm:
https://github.com/mbadolato/iTerm2-Color-Schemes/pull/288

Before merged, you can download from https://github.com/electerm/iTerm2-Color-Schemes/tree/electerm-theme-support/electerm
