### ISSUE TITLE
希望有字体配色

### ISSUE THREAD

**Issue by 1298509345** [electerm/electerm#1939]
Linux命令查看信息似乎只有黑白色

**Comment by zxdong262** [comment]
如果是root，可以参考这个https://unix.stackexchange.com/questions/565033/non-color-kali-linux-terminal-in-root-user

**Comment by 1298509345** [comment]
emm，不是root

**Comment by zxdong262** [comment]
`ls -al`也没有颜色吗,是bash吗？bashrc或者bash_profile什么情况？
