### ISSUE TITLE
期待可以丰富快捷键，调整书签的交互逻辑

### ISSUE THREAD

**Issue by wxz2561** [electerm/electerm#1949]
1.期待作者加入一些快捷键，个人比较喜欢用快捷键切换多个窗口，比如command+左箭头，command+有箭头切换窗口选项卡，command+d打开会话管理器等的。

2.当前的书签处于最左侧，并且宽度有限，标签长一点的就显示不全了；弹出和关闭书签的时候会有一点点的不跟手，感觉操作起来稍微有点奇怪。如果可以把书签加宽，或者改成弹出会话管理器窗口，加上快捷键打开也许会更好。

**Comment by uncleheart** [comment]
强烈建议
并且，希望能够command+1 +2 切换标签页

**Comment by oliver-lin** [comment]
貌似没有设置快捷键的地方呢？比如如何设置“快速粘贴SSH密码”？

**Comment by wxz2561** [comment]
> 貌似没有设置快捷键的地方呢？比如如何设置“快速粘贴SSH密码”？

确实还没有，期待加入，提高下效率
