### ISSUE TITLE
sftp下载远程文件时剩余时间为NaN

### ISSUE THREAD

**Issue by DifferentFire** [electerm/electerm#1951]
## Electerm version:
1.10.0
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior

sftp下载远程文件时正确显示剩余时间
![QQ截图20201204091936](https://user-images.githubusercontent.com/67768306/101109417-d91f8e80-3611-11eb-8da5-041ec7cbeb34.png)

## Can you reproduce the same behavior in other terminal:

是
## Current Behavior

sftp下载远程文件时剩余时间为NaN
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
能下载完成吗？多大的文件？

**Comment by DifferentFire** [comment]
多大的文件都这样，能下载完成

**Comment by weilining** [comment]
上传下载问题解决了就完美了
