### ISSUE TITLE
Download Setting Error

### ISSUE THREAD

**Issue by hoan277** [electerm/electerm#1954]
## Operating system(linux, macos, or windows7/8/10?):
Deepin OS 20
## Image
![image](https://user-images.githubusercontent.com/19620524/101234932-66d4aa00-36f6-11eb-9b13-52eb8b3a3b6f.png)

## Suggestions?
Import / Export Setting to/from single file an save to SSD

**Comment by zxdong262** [comment]
So you did not use existing id? Right, if so, it will create an empty gist, so download will get anything, if you already have existing gist id, you can click the using existing id to input it.
