### ISSUE TITLE
windows系统程序启动后停留在欢迎页面

### ISSUE THREAD

**Issue by Markghz** [electerm/electerm#1956]
## Electerm version:
1.10.0

## Operating system(linux, macos, or windows7/8/10?):
windows 10 20H2

## Expected Behavior

双击运行程序之后，应该能进入程序主体

## Current Behavior

双击运行程序之后，一直停留在该页面
![image](https://user-images.githubusercontent.com/13289111/101253924-8e109300-3759-11eb-9acf-11cb08f629d9.png)
尝试过好几个最近的版本，都有这个问题，之前的版本没有欢迎页面，直接不能显示主窗口，但是进程还在。在另一台win10上面遇到过（1.5.x版本，后来升级到1.9.x版本后那台机器就没遇到过了，但这台还有）

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以命令行运行一下看看报的什么错误吗？还有上一个正常工作的版本号？

**Comment by Markghz** [comment]
> 可以命令行运行一下看看报的什么错误吗？还有上一个正常工作的版本号？

很抱歉回复晚了……我感觉跟windows10的更新有关系，我是更新win10 4月更新之后就不行了，有可能跟electerm的升级无关。然后昨天装了一下20H2功能更新，今天就好了。但不确定，这个问题有时候出现有时候不出现。

**Comment by Markghz** [comment]
今天安装了windows 10的更新KB4592438，然后又有这个问题了。我尝试了一下用命令行执行electerm.exe，然后日志是这样的。
`22:07:07 debug › electerm start
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:3075
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at doListen (net.js:1493:7)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (events.js:223:5)
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3075
}`

**Comment by Markghz** [comment]
定位到了，win10开了HyperV之后，会保留一些低位端口，然后electerm就申请不到了，然后就挂了。我把HyperV关了就好了。

**Comment by GitHub-LG** [comment]
同一问题，关闭HyperV后解决。
