### ISSUE TITLE
log 正则匹配

### ISSUE THREAD

**Issue by Veng0923** [electerm/electerm#1958]
log日志，颜色没有匹配到，希望有个设置可以自定义log正则颜色，
目前日志等级匹配不到
![image](https://user-images.githubusercontent.com/34118386/101330899-26b82780-38ae-11eb-871b-bd9f495b9bfe.png)

**Comment by Veng0923** [comment]
主要是为了在  tail -f 的时候看日志比较直观一点

**Comment by bulldevil** [comment]
刚需刚需，看log眼睛要瞎了哈哈🤩

**Comment by zxdong262** [comment]
最新版已加入

**Comment by zxdong262** [comment]
![Screen Shot 2023-12-18 at 09 57 37](https://github.com/electerm/electerm/assets/1641949/ec6009c1-cb62-4510-b70e-72b781953f7e)
https://github.com/electerm/electerm/wiki/Terminal-keywords-highlight-regular-expression-exmaples
