### ISSUE TITLE
点击“搜索”会默认将终端所有的内容复制到粘贴板

### ISSUE THREAD

**Issue by zhanglianjie-163** [electerm/electerm#1963]
## Electerm version:
v1.10.9
## Operating system(linux, macos, or windows7/8/10?):
linux
## Expected Behavior

1. 想在终端上搜索一个关键字，先复制该关键字，然后点击搜索，ctrl+v 想把关键字粘贴到搜索框中，结果ctrl+v的结果是将终端上显示的所有内容都复制到了搜索框中；
2. 经测试发现是在点击“搜索”会默认将终端所有的内容复制到粘贴板
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
mint里不能复现，哪一个发行版？

**Comment by LianJieZhang** [comment]
使用的是UOS系统

**Comment by zxdong262** [comment]
最新版应该已经修复
