### ISSUE TITLE
无法进入electerm，一直在欢迎界面

### ISSUE THREAD

**Issue by xmmgithub** [electerm/electerm#1967]
Electerm1.10.0以后的版本，在linux上（ubuntu20.4）会卡在开始界面，一直进不去，如下所示：
![图片](https://user-images.githubusercontent.com/16660844/101749255-7eea6600-3b08-11eb-875b-6b921837b88c.png)

一直在闪，半个小时了都进不去，麻烦关注一下哈，多谢~

**Comment by zxdong262** [comment]
可以命令行运行看看报错内容吗？

**Comment by xmmgithub** [comment]
> 可以命令行运行看看报错内容吗？

我已经装回之前的版本了。运行命令行没有报错，就停留在运行服务在3075端口那一行，而且我把~/.config/electerm配置文件删除了都不行。

**Comment by zxdong262** [comment]
可以试试最新版吗，如果是端口问题，也许可以解决

**Comment by xmmgithub** [comment]
> 可以试试最新版吗，如果是端口问题，也许可以解决

最新版也不行呢，运行electerm命令后的输出如下：

![图片](https://user-images.githubusercontent.com/16660844/102031840-32e23e80-3df2-11eb-9778-ad543a380312.png)

并没有报什么错误，单就是显示不出来，着急

**Comment by xmmgithub** [comment]
最新版v1.11.5已经不存在该问题，谢谢~
