### ISSUE TITLE
sftp  上传几十个文件就卡死

### ISSUE THREAD

**Issue by flyinke** [electerm/electerm#1975]
sftp 上传 50几个jar包，总共近30M,就卡死
最新版本deb,uos系统
Windows上传文件多了也容易卡死，上传也很慢。

![截图录屏_选择区域_20201217105327](https://user-images.githubusercontent.com/16532650/102438248-e0ee2280-4056-11eb-9dcd-74650bfc5692.png)

**Comment by chenweiwen07** [comment]
一直都觉得自带sftp上传特别慢，最近上传一批文件30G左右，上传了两三个小时还没到一半，后来换winscp半小时不到就上传完了。
