### ISSUE TITLE
rz 上传文件取消不了

### ISSUE THREAD

**Issue by Veng0923** [electerm/electerm#1978]
rz 回车之后，突然不想上传了，点击取消，取消不了，界面一直卡在这

![image](https://user-images.githubusercontent.com/34118386/102584971-63322180-40ff-11eb-89e3-dd96931b5eea.png)

**Comment by Veng0923** [comment]
希望后期 rz上传文件的大小能够更大一点，8 M实在太小了

**Comment by lonnywong** [comment]
@Veng0923 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
