### ISSUE TITLE
几个体验增强小建议

### ISSUE THREAD

**Issue by fantastlcok** [electerm/electerm#1979]
1. 1批量输入” 框太短了，建议跟随窗口最大长度。
2. SFTP建议显示隐藏文件，或者设置里增加个是否显示隐藏文件的开关。
3. 编辑远程脚本唤起第三方文本编辑器处理。

使用了几个月，免费里最好用的编辑器了，感谢作者的付出。除了一些小问题让人有点难受，希望能变得更好。

**Comment by zxdong262** [comment]
@fantastlcok 感谢反馈，关于2，地址栏有个眼睛图标是切换隐藏文件显示的
