### ISSUE TITLE
mac os bigsur can't full screen

### ISSUE THREAD

**Issue by jzdayz** [electerm/electerm#1980]
## Electerm version:
![image](https://user-images.githubusercontent.com/35563513/102748776-cd67f200-439d-11eb-8fc4-18e8827a3a85.png)

## Operating system(linux, macos, or windows7/8/10?):
![image](https://user-images.githubusercontent.com/35563513/102748689-9f82ad80-439d-11eb-9884-8c2608dc59b2.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/35563513/102748749-bfb26c80-439d-11eb-91ea-3ef176aafbb5.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jzdayz** [comment]
![Uploading image.png…]()

**Comment by jzdayz** [comment]
![image](https://user-images.githubusercontent.com/35563513/102748935-17e96e80-439e-11eb-8011-39e1abfc48d0.png)

**Comment by zxdong262** [comment]
https://github.com/electron/electron/issues/15704 Do not support it due to know issue.
