### ISSUE TITLE
使用一段时间后的几个小建议

### ISSUE THREAD

**Issue by cainb** [electerm/electerm#1982]
已经使用 Electerm 一段时间了，体验很棒！现在已经是我的默认 SSH 连接客户端了，以下是我在使用后的一点点小建议：

1.  希望点击关闭时，如果有正在连接中的 SSH 标签可以弹出一个确认退出的提示框，防止有些时候手抖
2. 希望可以设置默认启动时直接打开指定的 SSH 连接书签以替换默认的新连接界面
3.  SFTP 的文件上传和上传详情界面里的 **取消/继续** 按钮都有点小，希望能大一点点
4. 打开 terminal info 终端信息时，似乎对 cpu 占用挺高的，1 个 cpu 核心的小机子每次一打开都是直接满负载和使用状态，且直到关闭 terminal info 终端信息后才会恢复正常，如下图;

![image](https://user-images.githubusercontent.com/48700331/102915145-452c3e80-44bc-11eb-8a01-a53703e8841d.png)

**Comment by zxdong262** [comment]
> 已经使用 Electerm 一段时间了，体验很棒！现在已经是我的默认 SSH 连接客户端了，以下是我在使用后的一点点小建议：
> 
> 1. 希望点击关闭时，如果有正在连接中的 SSH 标签可以弹出一个确认退出的提示框，防止有些时候手抖
> 2. 希望可以设置默认启动时直接打开指定的 SSH 连接书签以替换默认的新连接界面
> 3. SFTP 的文件上传和上传详情界面里的 **取消/继续** 按钮都有点小，希望能大一点点
> 4. 打开 terminal info 终端信息时，似乎对 cpu 占用挺高的，1 个 cpu 核心的小机子每次一打开都是直接满负载和使用状态，且直到关闭 terminal info 终端信息后才会恢复正常，如下图;
> 
> ![image](https://user-images.githubusercontent.com/48700331/102915145-452c3e80-44bc-11eb-8a01-a53703e8841d.png)

感谢反馈，都是可以改进的地方
