### ISSUE TITLE
不能删除本地文件夹

### ISSUE THREAD

**Issue by wen-carl** [electerm/electerm#1987]
## Operating system(linux, macos, or windows7/8/10?): windows10

删除本地文件夹的时候显示删除成功，实际上没有删掉。
文件是可以删掉的.

**Comment by zxdong262** [comment]
感谢反馈，在新版已经修复

**Comment by wen-carl** [comment]
@zxdong262 **1.10.39** 上面似乎还是不能删除，不知道是不是我的问题

还有个小问题，本地根目录文件夹点击刷新按钮的时候 会提示 path not valid
![image](https://user-images.githubusercontent.com/24239653/103836724-dad2eb00-50c4-11eb-82a2-83b25744ea83.png)
