### ISSUE TITLE
希望能有心跳包

### ISSUE THREAD

**Issue by max2max** [electerm/electerm#1989]
openssh为了在恶劣环境下保持连接，有定时发送心跳包的功能。

其他功能已经非常棒了！加油

**Comment by zxdong262** [comment]
感谢反馈

**Comment by max2max** [comment]
https://github.com/openssh/openssh-portable/search?q=client_alive_interval&type=

**Comment by max2max** [comment]
@zxdong262 https://github.com/electerm/electerm/blob/master/src/app/server/session.js#L252

开发者您好，我发现代码中有这个设置，期待您把功能整出来，谢谢！

**Comment by zxdong262** [comment]
@max2max 这个是默认开启的，所以不是这个问题

**Comment by max2max** [comment]
@zxdong262 我看到了，谢谢提醒。

我是想自定义的时候发现没有这个选项才以为没有这个功能，没想到全局设置里已经设置好了
