### ISSUE TITLE
增加命令行参数选项

### ISSUE THREAD

**Issue by wangsuiche** [electerm/electerm#1992]
增加命令行参数选项，实现自动登录。比如putty的命令行参数

**Comment by zxdong262** [comment]
书签表单里登录后运行脚本，你看这个是不是你需要的？

**Comment by wangsuiche** [comment]
不是我需要的。
是在程序没运行时。进入到electerm文件夹，执行windows的命令，命令如下
```
electerm.exe  -ssh -l  user  pw  password  -P  2222  192.168.0.1
```
程序就会启动，通过读取启动参数，使用密码：password，帐号：user，连接到192.168.0.1:2222这台机子上。
不需要增加机子到书签里。相应的参数也可以另行定义。

**Comment by zxdong262** [comment]
--> #2029
