### ISSUE TITLE
切换已连接多个窗口卡顿

### ISSUE THREAD

**Issue by nmgliangwei** [electerm/electerm#1995]
Electerm version: v1.10.31
os: macos big sur
问题:
连接多个ssh窗口, 在其中一个 ssh 窗口,使用 top 命令或者 tail 打开日志,过一会,在切换这个几个已连接的ssh窗口卡顿严重,但是切换过去后在窗口中输入命令不会卡顿,就是在各个窗口间切换卡顿严重, 切换不顺畅.

**Comment by KnightCicada** [comment]
+1 确实有点卡顿

**Comment by bb7788** [comment]
+1 那是巨卡 卡的没法用

**Comment by zxdong262** [comment]
@nmgliangwei @bb7788 @KnightCicada 可以试试最新版吗？

**Comment by nmgliangwei** [comment]
@zxdong262 我目前使用的已经不卡顿,感谢.
