### ISSUE TITLE
1.10.31的mac版本强退

### ISSUE THREAD

**Issue by 0OxXD** [electerm/electerm#1999]
## Electerm version:
1.10.31
## Operating system(linux, macos, or windows7/8/10?):
macos
## Current Behavior

点击serial和本地按钮会发生强退
![图片](https://user-images.githubusercontent.com/44028942/103528877-b3f79780-4ebf-11eb-98ab-cc1e0aae15f3.png)

![图片](https://user-images.githubusercontent.com/44028942/103528707-5fecb300-4ebf-11eb-87b2-8633198f4496.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
感谢反馈，最新版修复了
