### ISSUE TITLE
v1.10.31 这个版本实在是太卡了

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2000]
## Electerm version:
v1.10.31
## Operating system(linux, macos, or windows7/8/10?):
macos 10.15.5 
## Expected Behavior

这个版本实在是太卡了，真是比之前还要卡，这个版本简直巨卡，书签选择服务器的时候就反应特别慢，
在开几个链接后就更卡，在用一会那卡的敲个命令都得一两秒才反应，会越来越卡，基本后面没法操作了。
我这才开了2、3个链接就这样。之前是能开个7、8个链接

这个速度真该好好优化下，服务器多，不可能就开1、2个窗口，只求速度快点，要不完全没法用。

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Creling** [comment]
确实非常卡，很影响体验。

**Comment by zxdong262** [comment]
@bb7788 @Creling 可以试试最新版吗

**Comment by Creling** [comment]
> @bb7788 @Creling 可以试试最新版吗

我这里测试，v1.10.35已经没有卡顿的问题了，但是新出现了#2003中提到的闪退现象。
