### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by GitHubOSX** [electerm/electerm#2003]
Electerm version:1.10.35

Operating system(macos&windows10):
  连接类型选用本地时直接程序退出

**Comment by Creling** [comment]
确实有这个问题。
当 书签-新建书签-本地 时，程序直接退出。

![image.png](https://i.loli.net/2021/01/05/iYBjl7XV1gLoEdb.png)

**Comment by justmd5** [comment]
![image](https://user-images.githubusercontent.com/4120960/103863643-32d91400-50fc-11eb-972b-92103a023948.png)
点击后两个都是闪退 
版本：v1.10.39
系统：macOS Big Sur 11.1

**Comment by bb7788** [comment]
+1 闪退

**Comment by zxdong262** [comment]
我检查是因为serialport组件，我试了很多种方式，怎么也无法正常工作了，只好新版里去掉了。
