### ISSUE TITLE
文件管理器加载不出来

### ISSUE THREAD

**Issue by reF1nd** [electerm/electerm#2007]
## Electerm version:
v1.10.39
## Operating system(linux, macos, or windows7/8/10?):
MacOS 11.1
## Expected Behavior

文件管理器一直卡在转圈，加载不出来，如图：
![1](https://user-images.githubusercontent.com/24762710/103889596-a5a8b600-5121-11eb-8681-02c37356c6b4.jpg)

另外连接服务器之后的sftp中，本地也有一定几率卡在转圈的状态，虽然可以看到文件，但是无法操作，但是有时候能加载出来也能操作。远端则无问题。如图：
<img width="1316" alt="2" src="https://user-images.githubusercontent.com/24762710/103890387-ef45d080-5122-11eb-9dbf-3448dc5f8d1f.png">

**Comment by zxdong262** [comment]
可以看看控制台有报错吗？

**Comment by reF1nd** [comment]
> 可以看看控制台有报错吗？

@zxdong262 好像没有
<img width="1316" alt="3" src="https://user-images.githubusercontent.com/24762710/103892768-1a322380-5127-11eb-831c-b001bd8607e4.png">

**Comment by zxdong262** [comment]
@reF1nd 可以试试最新版吗？

**Comment by reF1nd** [comment]
没问题了
