### ISSUE TITLE
Windows10 强退后启动灰屏

### ISSUE THREAD

**Issue by Loudomian** [electerm/electerm#2010]
## Electerm version:
v1.10.39
## Operating system
Windows10
## Expected Behavior

在某次卡死后我任务管理器强制退出，重开后显示欢迎页与短暂的正常主页后灰屏。
![欢迎页](https://user-images.githubusercontent.com/40517361/104048539-53998a80-521e-11eb-9882-a33aa342b743.png)

![短暂的主页](https://user-images.githubusercontent.com/40517361/104048563-61e7a680-521e-11eb-9320-0c913c0c8ec0.png)

![灰屏](https://user-images.githubusercontent.com/40517361/104048466-32d13500-521e-11eb-890a-5b19114d72fa.png)

**Comment by Loudomian** [comment]
命令行启动无报错，使用v1.10.35一样灰屏

![命令行启动](https://user-images.githubusercontent.com/40517361/104049087-4af58400-521f-11eb-8489-4ddcf4e7a6cd.png)

**Comment by zxdong262** [comment]
可能数据损坏了，删除 `%APPDATA%/electerm`试试

**Comment by Loudomian** [comment]
修复了，感谢 😊👍
