### ISSUE TITLE
打开软件第一个标签一直那个卡着无法自动开启，只有手动reload才能打开

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#2016]
## Operating system(linux, macos, or windows7/8/10?):
centos8

## Expected Behavior
应该和之前版本打开默认会初始化出一个终端

## Current Behavior
打开软件第一个标签一直那个卡着无法自动开启，只有手动reload才能打开
![图片](https://user-images.githubusercontent.com/8896611/104142392-623a9a00-53f6-11eb-8b47-02538eb23f26.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by sguphil** [comment]
/var/log/message
Jan 15 01:42:30 localhost /usr/libexec/gdm-x-session[2321]: 01:42:30 debug › electerm start
Jan 15 01:42:30 localhost dbus-daemon[1403]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.269' (uid=0 pid=3794 comm="/opt/electerm/electerm --no-sandbox " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Jan 15 01:42:30 localhost /usr/libexec/gdm-x-session[2321]: (node:3794) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Jan 15 01:42:31 localhost /usr/libexec/gdm-x-session[2321]: 01:42:31 info › server runs on 127.0.0.1 30975
Jan 15 01:42:31 localhost /usr/libexec/gdm-x-session[2321]: 01:42:31 debug › error parsing $HOME/.ssh/config
Jan 15 01:42:31 localhost /usr/libexec/gdm-x-session[2321]: 01:42:31 debug › maybe no $HOME/.ssh/config, but it is ok
Jan 15 01:42:31 localhost /usr/libexec/gdm-x-session[2321]: 01:42:31 info › database version: 1.11.6
Jan 15 01:42:40 localhost /usr/libexec/gdm-x-session[2321]: 01:42:40 debug › ws: connected to terminal -> ouaE0p3TYVH_N1upGyZUx
Jan 15 01:42:55 localhost dbus-daemon[1403]: [system] Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)

**Comment by sguphil** [comment]
更新到1.11.11后问题消失了，不知道是什么导致的

**Comment by zxdong262** [comment]
那就好
