### ISSUE TITLE
更新版本问题

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2019]
## Electerm version:
v1.11.1
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

早上更新的时候自动下载的更新包是 electerm-1.11.1-mac-arm64.dmg，这个用不了啊。
这个更新的版本弄错了吧，应是 electerm-1.11.1-mac.dmg
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
系统什么版本？是m1的本子吗？

**Comment by ViewWholeWorld** [comment]
我是intel的，下载下来的更新也是arm版本的安装包

**Comment by bb7788** [comment]
> 系统什么版本？是m1的本子吗？
@zxdong262 不是m1的本子

**Comment by lighthx** [comment]
一样，黑白苹果都是下载的arm内核的

**Comment by bb7788** [comment]
问题已经修复了
