### ISSUE TITLE
sftp本地目录加载不出来

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2020]
## Electerm version:
v1.11.1
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

sftp本地目录加载不出来，一直在转圈
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
打开就这样吗？每次必然复现？

**Comment by evenwangcn** [comment]
有同样的问题

**Comment by evenwangcn** [comment]
从1.10.35版本开始就有这个问题，1.10.31版本没问题

**Comment by bb7788** [comment]
> 打开就这样吗？每次必然复现？

嗯，每次必然复现的。默认的本地连接的文件管理器也是！

**Comment by zxdong262** [comment]
可以试试最新版吗？

**Comment by zxdong262** [comment]
@ARH-SILY 可以试试1.11.8吗

**Comment by bb7788** [comment]
> @ARH-SILY 可以试试1.11.8吗

1.11.11 已经没有问题了，1.11.8好像也没有问题。

**Comment by ARH-SILY** [comment]
> @ARH-SILY 可以试试1.11.8吗

确实如楼上所说，1.11.8和1.11.11都修复了这个问题
