### ISSUE TITLE
无法通过检查更新完成更新

### ISSUE THREAD

**Issue by cainb** [electerm/electerm#2021]
刚刚打开的时候提醒我有新版本了，我便点击了升级，下载完后弹窗便消失了，看了下版本号，没变

我便手动重启了下，但是重启打开后还是照常弹窗提醒我更新，版本还是没变

![image](https://user-images.githubusercontent.com/48700331/104151297-9e322700-5417-11eb-8abb-e227e7d57177.png)

**Comment by hlgsdx** [comment]
Possible duplicate of issue #2018.

**Comment by zxdong262** [comment]
最新版应该没有了
