### ISSUE TITLE
[feat] Support command line params

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#2029]
不是我需要的。
是在程序没运行时。进入到electerm文件夹，执行windows的命令，命令如下
```
electerm.exe  -ssh -l  user  pw  password  -P  2222  192.168.0.1
```
程序就会启动，通过读取启动参数，使用密码：password，帐号：user，连接到192.168.0.1:2222这台机子上。
不需要增加机子到书签里。相应的参数也可以另行定义。

_Originally posted by @wangsuiche in https://github.com/electerm/electerm/issues/1992#issuecomment-758386635_

**Comment by wangzw** [comment]
`SecureCRT` and `putty`  have their own command line arguments. It would be nice to be compatible with one of them and much easier to integrate electerm with other system.

**Comment by zxdong262** [comment]
Done
