### ISSUE TITLE
建议固定书签栏的时候，终端可以右移，与书签栏并列

### ISSUE THREAD

**Issue by xmmgithub** [electerm/electerm#2031]
![图片](https://user-images.githubusercontent.com/16660844/104418305-a58d3800-55b1-11eb-9162-b3b3941b70c4.png)

看这里，固定书签栏的时候，输入终端左边会被覆盖掉，没法正常使用。
建议固定书签栏的时候，也能够正常使用终端。

**Comment by panw3i** [comment]
复议

**Comment by xmmgithub** [comment]
复议+1

**Comment by darrenliuwei** [comment]
复议+1

**Comment by xmmgithub** [comment]
@zxdong262 老哥，考虑一下噻~

**Comment by zxdong262** [comment]
@xmmgithub 可以做到的，就是有点麻烦

**Comment by xmmgithub** [comment]
> @xmmgithub 可以做到的，就是有点麻烦

辛苦一下噻，这个功能还是挺实用的，最好固定后能够左右拖拽调整宽带。

谢谢～

**Comment by zxdong262** [comment]
已经实现
