### ISSUE TITLE
无法连接ssh及使用任意功能（重装也未解决）

### ISSUE THREAD

**Issue by UncleBrown** [electerm/electerm#2033]
## Current Behavior

All function clicks are invalid

## Steps to Reproduce

1. brew install --cask electerm
2. Open && Edit - New ssh

## Detailed Description
![1](https://user-images.githubusercontent.com/46209527/104539159-f48da880-5657-11eb-843a-d5e8c993e717.png)
![2](https://user-images.githubusercontent.com/46209527/104539177-f9eaf300-5657-11eb-9953-84718854fe9a.png)

**Comment by zxdong262** [comment]
可以试试从https://github.com/electerm/electerm/releases下载安装吗，如果还不行, 可以删除配置文件试试吗`rm -rf ~/Library/Application\ Support/electerm*`，还有可以从命令行启动看看输出吗？运行`/Applications/electerm.app/Contents/MacOS/electerm`

**Comment by zxdong262** [comment]
如果都不行只能退回到更早的版本了

**Comment by zxdong262** [comment]
最新版应该可以了
