### ISSUE TITLE
MacOS下如果使用左右分屏，electerm会挂掉

### ISSUE THREAD

**Issue by shuaiZend** [electerm/electerm#2034]
## Electerm version:
v1.10.39
## Operating system(linux, macos, or windows7/8/10?):
MacOS 10.15
## Expected Behavior

当使用Mac的左右分屏功能的时候，如果选择了electerm，electerm未达到预期，并且会挂掉。
注意是MacOS自己的左右分屏，并不是electerm自己的分屏功能。因为我想浏览器和electerm一起使用。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
参考https://github.com/electerm/electerm/wiki/Know-issues
