### ISSUE TITLE
堡垒机无法登录，需要使用键盘交互认证

### ISSUE THREAD

**Issue by postblue** [electerm/electerm#2045]
## Electerm version:
v1.11.8
## Operating system(linux, macos, or windows7/8/10?):
 macos：11.1
## Expected Behavior

想要正常登录堡垒机。
使用其他软件会有一个，键盘交互认证选项，选择该选项后，登录时会有一个小弹窗输入密码。

## Can you reproduce the same behavior in other terminal:

不能。
## Current Behavior

想要正常登录堡垒机，没有键盘选项，无法登录堡垒机。

## Possible Solution

登录认证增加一个键盘交互认证。

## 其他软件登录堡垒机的认证方式
<img width="431" alt="1" src="https://user-images.githubusercontent.com/39828275/105627154-f9303900-5e6f-11eb-9bee-9c2e585b6bf4.png">
<img width="620" alt="2" src="https://user-images.githubusercontent.com/39828275/105627158-fe8d8380-5e6f-11eb-80cb-b7e3258d5718.png">

**Comment by zxdong262** [comment]
理论上连接程序会尝试每一种认证方式，所以是无需指定键盘交互。如果没有弹出键盘交互认证窗口，那就是其他的问题了。

**Comment by postblue** [comment]
> 理论上连接程序会尝试每一种认证方式，所以是无需指定键盘交互。如果没有弹出键盘交互认证窗口，那就是其他的问题了。

@zxdong262 因为我也是刚接触ssh这个东西，所以您说的这个其他问题，是什么问题？  可以提供一下思路或者关键词我去搜索吗？

**Comment by zxdong262** [comment]
@postblue 可能得看看debug信息，我会在下个版本加入debug设置以便可以看到ssh调试信息
类似 `ssh -vv xxx@xxxx.com`看到的信息

**Comment by postblue** [comment]
> @postblue 可能得看看debug信息，我会在下个版本加入debug设置以便可以看到ssh调试信息
> 类似 `ssh -vv xxx@xxxx.com`看到的信息

@zxdong262 好的，谢谢，那就等您这边新增debug调试之后，我再关闭该Issues

**Comment by zxdong262** [comment]
@postblue 最新版可以试试吗？
加了个debug选项在设置页面，开启后命令行运行electerm: `/Applications/electerm.app/Contents/MacOS/electerm`，连接书签ssh时候既可以看到debug信息了。

**Comment by postblue** [comment]
@zxdong262 还是无法链接，但是有了错误提示。
<img width="1213" alt="Snipaste_2021-01-29_14-11-53" src="https://user-images.githubusercontent.com/39828275/106238556-04061780-623c-11eb-89f6-5380717061d8.png">

**Comment by postblue** [comment]
@zxdong262 有了错误日志，但是我还是看不懂这是什么问题，麻烦您再帮忙看一下。

```
Unexpected packet before version

Error: Unexpected packet before version
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.11:2:370402
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.11:2:304366)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.11:2:305295
```

**Comment by zxdong262** [comment]
@postblue 我也看不出来什么问题

**Comment by postblue** [comment]
@zxdong262 那我只能放弃这个软件了！ 😭

**Comment by hope250** [comment]
堡垒机的话，要么换软件，要么直接 ssh，要不然即便连上也会固定时间断线

**Comment by postblue** [comment]
最新版本，已经修复该问题
