### ISSUE TITLE
最近几个mac版本均无法使用

### ISSUE THREAD

**Issue by JaheimLee** [electerm/electerm#2046]
m1重新编译可以理解，为啥普通mac版的也无法使用了呢。最近好像只有1.10.39可以用

**Comment by zxdong262** [comment]
你是m1的本子吗？估计是使用web worker连接websocket的原因，或者升级到electron11的原因，可能在一个月之后有望解决

**Comment by 4860575** [comment]
m1的目前只有1.10.39可以运行

**Comment by MapleGone** [comment]
> m1的目前只有1.10.39可以运行

是的，我尝试了arm版本和非arm版本在1.10.39之前都是不可用的。非常感谢你的推荐！

**Comment by zxdong262** [comment]
可以试试最新版吗，回退到electron9了

**Comment by 4860575** [comment]
@zxdong262 1.11.1可以了。但不是arm64了
<img width="251" alt="image" src="https://user-images.githubusercontent.com/24975201/105973699-06476500-60c8-11eb-98b7-322e525c2d68.png">

**Comment by zxdong262** [comment]
暂时不会发布mac-arm版本了
