### ISSUE TITLE
引起无法连接任何服务器的问题

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2047]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.11.8
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

我这边有个a服务器(centos)，只要我连接这个服务器，其他已经连接的服务器都立刻会断开，包括默认新建立的本地连接，
而且一旦触发这个问题，所有的服务器连接都无法重新连接，会一直抱一个错误。只有重启程序。
只要不连接a服务器，连接其他服务器都是正常的，而且我也尝试在软件中删除这个连接，重新建立，还是不行。
之前还是正常的，突然就这样。

 TypeError: Cannot set property 'onclose' of undefined
    at St (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.8:2:305583)
    at async kt (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.8:2:305714)
    at async qo.localList (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.8:2:413315)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以看看centos 的 ssh-server版本吗？

**Comment by bb7788** [comment]
> 可以看看centos 的 ssh-server版本吗？
@zxdong262 
CentOS release 6.5 (Final)

ssh -V
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

rpm -qa|grep ssh
libssh2-1.4.2-1.el6.x86_64
openssh-5.3p1-94.el6.x86_64
openssh-clients-5.3p1-94.el6.x86_64
openssh-server-5.3p1-94.el6.x86_64

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/releases/tag/v1.11.11 @bb7788 可以试试最新版吗？

**Comment by bb7788** [comment]
> https://github.com/electerm/electerm/releases/tag/v1.11.11 @bb7788 可以试试最新版吗？

 #测试了一下，没有之前的问题了，谢谢！神速修复😄。
@zxdong262

**Comment by zxdong262** [comment]
😄
