### ISSUE TITLE
对macOS下界面UI的建议

### ISSUE THREAD

**Issue by Derrors** [electerm/electerm#2052]
软件很好用，但是有一个问题是在macOS下的UI风格问题就是：软件页面UI与macOS系统下其他软件的整体风格不一致，例如：

1. 最大化、最小化、关闭按钮的UI是否可适配macOS风格？
2. 左侧功能栏是否可适配macOS风格做到顶部菜单栏？
3. 软件最大化后，在macOS下并不是真正的全屏，下边边界会顶到程序坞的位置，且无法通过macOS的通过触摸滑动实现切换屏幕。

归纳来说，就是在macOS下的软件风格仍为WindowUI，建议对此进行适配macOS风格，功能很强大了，美观方面还可以再改善一下。

**Comment by zxdong262** [comment]
为了支持透明度，采用了无边框的设定，就无法支持全屏了 https://github.com/electron/electron/issues/15704
也许可以加一个设定允许用户选择放弃透明度支持而保留全屏功能

**Comment by epenli** [comment]
最重要的是 如果全屏了 窗口上边是无法拉动的 也就是如果在外屏上打开 尺寸较高 你就完全没办法调整尺寸了

**Comment by starxg** [comment]
的确。macOS下的ui太难操作了，希望大佬优化一波😆😆😆

**Comment by muyixiaohui** [comment]
请还是将最大化、最小化、关闭按钮适配macOS风格吧，透明度什么的，可以不用要了。

**Comment by zxdong262** [comment]
@muyixiaohui @starxg @epenli @Derrors 最新版加了个使用系统标题栏的选项在设置里，可以试试

**Comment by muyixiaohui** [comment]
> @muyixiaohui @starxg @epenli @Derrors 最新版加了个使用系统标题栏的选项在设置里，可以试试

@zxdong262  没有找到这个设置 ,1.13.1上找了N遍都没有发现这个选项。

**Comment by zxdong262** [comment]
> > @muyixiaohui @starxg @epenli @Derrors 最新版加了个使用系统标题栏的选项在设置里，可以试试
> 
> @zxdong262 没有找到这个设置 ,1.13.1上找了N遍都没有发现这个选项。

哎呀我记错了，不好意思，马上发布，下个版本
