### ISSUE TITLE
中文必是乱码

### ISSUE THREAD

**Issue by cnloveboy** [electerm/electerm#2054]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
electerm-1.11.8，electerm-1.11.11
## Operating system(linux, macos, or windows7/8/10?):
win7,win10
## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

   编码依次选择为gbk、gb18030、hz-gb2312都依然是乱码，显示为????.ink
## Suggestions?
   怀疑编码未真正作为变量起改变编码作用，请核查。如果用xshell，选择gb2312就没乱码。确认是程序对编码处理存在问题。请给予解决。

**Comment by zxdong262** [comment]
是连接远程服务器还是本地终端呢？

**Comment by cnloveboy** [comment]
尊敬的开发者：
&nbsp; &nbsp; &nbsp; 你好！
&nbsp; &nbsp; &nbsp; 很高兴收到这个反馈的回复，非常快速，深感意外。
&nbsp; &nbsp; &nbsp; 问题细节描述：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;服务端：centos7 , evn lang = en_US UTF-8;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;本地：win10 64bits
&nbsp; &nbsp; &nbsp; 昨晚，反复思考一下，度娘了关于乱码问题，应该与服务器默认语言有关。
&nbsp; &nbsp; &nbsp; 今天，把服务器默认语言更改为，zh_CN UTF-8,用GBK编码，查看TOMCAT输入显示中文正常，用UTF-8编码，查看服务端中文文件名显示正常。
&nbsp; &nbsp; &nbsp; 但是，之前作为参照的一个文件乱码依然是乱码，应该还是编码没有对应，不过，影响不大。
&nbsp; &nbsp; &nbsp;下面是相关截图：
&nbsp; &nbsp; &nbsp;


&nbsp; &nbsp; 请海涵这个误报，确实是那个文件????.ink影响了判断。经过这次操作经历，感觉electerm软件确实做的功能到位，并且对于bug收集和回复，乃至处理、修复都是快速的，再次深表歉意。
xuyuanjun



&nbsp;

**Comment by zxdong262** [comment]
@cnloveboy 客气了老铁，软件问题很多，很不成熟，我也水平有限，问题越来越多，愿意花时间提issue就很感谢了
