### ISSUE TITLE
v1.11.12版本启动后无法弹出本地shell命令交互

### ISSUE THREAD

**Issue by bryan31** [electerm/electerm#2057]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:

v1.11.12

## Operating system(linux, macos, or windows7/8/10?):

macos

## Expected Behavior

之前版本启动后，直接弹出本地的shell命令交互，现在不行

## Current Behavior

现在启动后，弹不出本地的shell命令交互，就一直这样了
![image](https://user-images.githubusercontent.com/924838/108223317-a4cd6000-7174-11eb-960b-a9cef27aaf23.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
点击一下，然后回车呢？

**Comment by zxdong262** [comment]
点击一下，然后回车呢？

**Comment by nmgliangwei** [comment]
@zxdong262 @bryan31  我的 mac big sur 也无法进入,回车也不行, 复制窗口也不行,debug模式打开 electerm提示 ioctl 之类的错误.  我回到1.11.11 了.

**Comment by bryan31** [comment]
@zxdong262 也不行

**Comment by iqueids** [comment]
同样的问题

**Comment by nmgliangwei** [comment]
@zxdong262 1.11.13已经可以了.

**Comment by zxdong262** [comment]
好的，感谢反馈
