### ISSUE TITLE
electerm 新建快速命令

### ISSUE THREAD

**Issue by knightdax** [electerm/electerm#2058]
新建快速命令窗口老是挡住我输入命令，能否去掉

**Comment by zxdong262** [comment]
可以截图看看吗？

**Comment by knightdax** [comment]
您好，就是图中的这个，请问有办法去掉吗，经常挡住我输入命令
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "electerm/electerm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月18日(星期四) 中午12:09
收件人:&nbsp;"electerm/electerm"<electerm@noreply.github.com&gt;;
抄送:&nbsp;"黄大欣"<1193862877@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [electerm/electerm] electerm 新建快速命令 (#2058)





 
可以截图看看吗？

**Comment by knightdax** [comment]
![image](https://user-images.githubusercontent.com/22837109/108304261-99b11900-71e2-11eb-83e3-91ce45ef0c6d.png)
您好，就是这个，经常挡住我输入命令

**Comment by zxdong262** [comment]
@knightdax 新版应该没有这个问题了

**Comment by knightdax** [comment]
收到，多谢大佬



---原始邮件---
发件人: "ZHAO Xudong"<notifications@github.com&gt;
发送时间: 2021年2月26日(周五) 晚上7:41
收件人: "electerm/electerm"<electerm@noreply.github.com&gt;;
抄送: "knightdax"<1193862877@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [electerm/electerm] electerm 新建快速命令 (#2058)




 
Closed #2058.
