### ISSUE TITLE
打开卡启动图

### ISSUE THREAD

**Issue by Refuel-ZL** [electerm/electerm#2060]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Operating system(linux, macos, or windows7/8/10?):
linux (deepin) + zsh 
## Current Behavior

安装完，打开直接卡图片 加载不了工具栏，回滚1.11.11 无此问题

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
最新版应该修复了，可以试试吗？

**Comment by Refuel-ZL** [comment]
新版的可以了
