### ISSUE TITLE
快速命令是否可以支持排序？

### ISSUE THREAD

**Issue by dlockhart210** [electerm/electerm#2061]
目前好像只能按照创建时间的顺序排列，而无法自定义顺序，希望可以加上拖拽调整顺序之类的。
另外在配置里，删除快速命令的X号，是否可以加个二次确认，一不小心点到，就无从恢复了

**Comment by zxdong262** [comment]
可以的

**Comment by tianyunperfect** [comment]
请问快捷命令排序的问题解决了吗？我测试还是不行啊？

**Comment by zxdong262** [comment]
> 请问快捷命令排序的问题解决了吗？我测试还是不行啊？

还没做这个功能

**Comment by tianyunperfect** [comment]
> > 请问快捷命令排序的问题解决了吗？我测试还是不行啊？
> 
> 还没做这个功能

希望能加上这个，是一个使用频率非常的需求。感恩

**Comment by zxdong262** [comment]
将在下个版本加入
