### ISSUE TITLE
sftp上传报错了。。。

### ISSUE THREAD

**Issue by guyuting** [electerm/electerm#2062]
## 报错内容及截图
 Error: Failure
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.12:2:370402
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.12:2:304366)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.12:2:305295)

![image](https://user-images.githubusercontent.com/27722742/108492611-550ba780-72e0-11eb-8622-3fba9c62006c.png)

![image](https://user-images.githubusercontent.com/27722742/108492108-b8490a00-72df-11eb-9b90-f689036d8ab4.png)

## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
1.11.12
## Operating system(linux, macos, or windows7/8/10?):
macOS Big Sur 11.2.1 (20D74)
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
如果单个文件上传，可以正常进行吗？

**Comment by guyuting** [comment]
> 如果单个文件上传，可以正常进行吗？

随便新建了一个文件，可以正常上传
