### ISSUE TITLE
每次升级时都好麻烦，必须要打开GitHub然后找到这里下载

### ISSUE THREAD

**Issue by darrenliuwei** [electerm/electerm#2063]
能不能优化一下版本升级的方式呀
![image](https://user-images.githubusercontent.com/10508248/108586674-f5b6a180-738a-11eb-864f-45ffc798a475.png)
这个按钮点了一点作用都没有，下载下来之后，你还是需要重新回到GitHub，然后再次下载

**Comment by darrenliuwei** [comment]
![image](https://user-images.githubusercontent.com/10508248/108586723-36aeb600-738b-11eb-8864-d6664ae28326.png)
每次升级版本，都必须要到这个地方下载，感觉有点麻烦

能不能像vs code那样，点击升级按钮，然后它自己升级版本

**Comment by Bennett-Yang** [comment]
可以考虑一下[scoop](https://github.com/lukesampson/scoop)，添加[dorado](https://github.com/chawyehsu/dorado)这个仓库后就可以找到electerm了。

**Comment by zxdong262** [comment]
> 可以考虑一下[scoop](https://github.com/lukesampson/scoop)，添加[dorado](https://github.com/chawyehsu/dorado)这个仓库后就可以找到electerm了。

方便提个PR加到readme吗？

**Comment by Bennett-Yang** [comment]
> > 可以考虑一下[scoop](https://github.com/lukesampson/scoop)，添加[dorado](https://github.com/chawyehsu/dorado)这个仓库后就可以找到electerm了。
> 
> 方便提个PR加到readme吗？

ok, no problem
