### ISSUE TITLE
windows下 install 安装 一直报vscode-icons 问题

### ISSUE THREAD

**Issue by a852882874** [electerm/electerm#2078]
![image](https://user-images.githubusercontent.com/25943026/110283935-e470c480-801b-11eb-9994-1f51f4a2c8da.png)
打扰了 请问下 windows下 install 安装 一直报vscode-icons 问题

**Comment by zxdong262** [comment]
看起来是连不上github，可能得用个vpn什么的

**Comment by a852882874** [comment]
请问下 怎么把这个项目接入到自己的electron项目里面。有提供api接口吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 晚上9:21
收件人: "electerm/electerm"<electerm@noreply.github.com&gt;; 
抄送: "冰淇淋"<852882874@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078)





 
看起来是连不上github，可能得用个vpn什么的

**Comment by zxdong262** [comment]
> 请问下 怎么把这个项目接入到自己的electron项目里面。有提供api接口吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年3月8日(星期一) 晚上9:21 收件人: "electerm/electerm"<electerm@noreply.github.com&gt;; 抄送: "冰淇淋"<852882874@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078) 看起来是连不上github，可能得用个vpn什么的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有接口，你可以克隆项目自己修改

**Comment by a852882874** [comment]
嗯嗯&nbsp; 谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 晚上10:58
收件人: "electerm/electerm"<electerm@noreply.github.com&gt;; 
抄送: "冰淇淋"<852882874@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078)





  
请问下 怎么把这个项目接入到自己的electron项目里面。有提供api接口吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年3月8日(星期一) 晚上9:21 收件人: "electerm/electerm"<electerm@noreply.github.com&gt;; 抄送: "冰淇淋"<852882874@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078) 看起来是连不上github，可能得用个vpn什么的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没有接口，你可以克隆项目自己修改

**Comment by a852882874** [comment]
打扰了，请问下 这个项目打包以后 出现图片路径加载不出来，这个怎么解决呀








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "冰淇淋"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 晚上10:59
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078)



 嗯嗯&nbsp; 谢谢啦




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月8日(星期一) 晚上10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078)





  
请问下 怎么把这个项目接入到自己的electron项目里面。有提供api接口吗
 …
 ------------------ 原始邮件 ------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月8日(星期一) 晚上9:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [electerm/electerm] windows下 install 安装 一直报vscode-icons 问题 (#2078) 看起来是连不上github，可能得用个vpn什么的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没有接口，你可以克隆项目自己修改
