### ISSUE TITLE
【SFTP】文件冲突提示框的“X”(关闭窗口按钮)按钮点击无效

### ISSUE THREAD

**Issue by bo-don** [electerm/electerm#2082]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## 问题
文件冲突提示框的关闭窗口按钮无线
![image](https://user-images.githubusercontent.com/35206653/111075893-f3c4a600-8524-11eb-9d7e-ca70508d3760.png)

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
