### ISSUE TITLE
下载设置出现错误Cipher functions:OPENSSL_internal:BAD_DECRYPT

### ISSUE THREAD

**Issue by lxxself** [electerm/electerm#2084]
## Expected Behavior

一台电脑正常同步到github后，在另一台电脑下载使用相同gist id但token不同的情况下，一直如下错误无法完成同步。两台电脑均配置的是加密。
`Error: Error invoking remote method 'async': Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
    at EventEmitter.i.send.i.invoke (electron/js2c/renderer_init.js:75:535)
    at async Proxy.e.downloadSetting (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.2:2:573974)`

请问是什么问题？

**Comment by zxdong262** [comment]
加密是用token加密的，所以得使用同一个token

**Comment by tangna** [comment]
一台电脑正常同步到github后，生成了一个gist。然后我好像在另外一个电脑使用了该token，没有填写gist，点击【上传设置】生成了一个新的gist，然后再在github里面Regenerate token。请问下现在最开始的那个gist能怎么同步下载到电脑上吗？

**Comment by zxdong262** [comment]
> 一台电脑正常同步到github后，生成了一个gist。然后我好像在另外一个电脑使用了该token，没有填写gist，点击【上传设置】生成了一个新的gist，然后再在github里面Regenerate token。请问下现在最开始的那个gist能怎么同步下载到电脑上吗？

是很旧的版本吗？新版本里可以填写gist id，两边都用同一个token和gist id不行吗？

**Comment by tangna** [comment]
> > 一台电脑正常同步到github后，生成了一个gist。然后我好像在另外一个电脑使用了该token，没有填写gist，点击【上传设置】生成了一个新的gist，然后再在github里面Regenerate token。请问下现在最开始的那个gist能怎么同步下载到电脑上吗？
> 
> 是很旧的版本吗？新版本里可以填写gist id，两边都用同一个token和gist id不行吗？

比较新的版本，我最后的那个gist是两边都可以用。之前那个gist想从github同步，一直没同步下来，就把gist删除了，不小心点了【上传设置】。现在想问下最先那个gist还有没有办法同步下载

**Comment by zxdong262** [comment]
> > > 一台电脑正常同步到github后，生成了一个gist。然后我好像在另外一个电脑使用了该token，没有填写gist，点击【上传设置】生成了一个新的gist，然后再在github里面Regenerate token。请问下现在最开始的那个gist能怎么同步下载到电脑上吗？
> > 
> > 
> > 是很旧的版本吗？新版本里可以填写gist id，两边都用同一个token和gist id不行吗？
> 
> 比较新的版本，我最后的那个gist是两边都可以用。之前那个gist想从github同步，一直没同步下来，就把gist删除了，不小心点了【上传设置】。现在想问下最先那个gist还有没有办法同步下载

如果已经加密目前不能，得加一个加密密码选项，填写你旧的token才可以。你已经没有其他备份了？

**Comment by tangna** [comment]
哦哦，只是想问下能不能有办法同步回来。那个gist我就把它删了，影响不大。后面就用最新的gist同步了
