### ISSUE TITLE
Can not use GitBash in windows as "Default ExecWindows"

### ISSUE THREAD

**Issue by lannyyip** [electerm/electerm#2085]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.12.1

## Operating system(linux, macos, or windows7/8/10?):
windows10

## Expected Behavior

1. Capable to specify bash or git-bash in "Default ExecWindows"
## Current Behavior

When I specifed bash in "Default ExecWindows" with following locations, it prompted that "File not found: C:\Program\" when I open a new tab:
C:\Program/ Files\Git\bin\bash.exe
C:/Program\ Files/Git/bin/bash.exe
When I specified bash with following location, it promted that "File not found: C:\WINDOWS\"C:\Program":
"C:/Program Files/Git/bin/bash.exe"
"C:\Program Files\Git\bin\bash.exe"

## Possible Solution

None

## Steps to Reproduce

1.
2.
3.
4.

**Comment by lannyyip** [comment]
May I know how to specified BASH in windows. I can't set even in 1.12.6.
Thank you very much!

**Comment by zxdong262** [comment]
Should be `C:/Program Files/Git/bin/bash.exe` if this is the bash.exe path, sorry, I missed something, https://github.com/electerm/electerm/releases/tag/v1.12.7 should work as I tested. Thank you for the feedback @lannyyip

**Comment by lannyyip** [comment]
Woh. Thank you very much! It is OK now!
