### ISSUE TITLE
[BUG] Default terminal type doesn't work when starting a new session from bookmark

### ISSUE THREAD

**Issue by JunweiSUN** [electerm/electerm#2086]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
1.12.2
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

Default terminal type should work when starting a new session from bookmark
## Can you reproduce the same behavior in other terminal:

Yes
## Current Behavior

If I change the default terminal type from `xterm-256color` to `xterm-color` in the settings, it will work if I start a new tab and then connect to the remote server. However, if I directly start a session from bookmark, the `$TERM` will be `xterm-256color` unchanged.

**Comment by zxdong262** [comment]
Thank you for the feedback, will fix in next release
