### ISSUE TITLE
在使用nano编辑时，粘贴不会自动换行

### ISSUE THREAD

**Issue by cantona97** [electerm/electerm#2090]
Windows 10 
v1.12.7
问题：
在Ubuntu等终端使用nano编辑文件，粘贴的内容不会换行，无论多少行的内容都是一行显示，例如：
“11111
22222
33333”
在粘贴后会变成“111112222233333”

但使用vi编辑时，粘贴的内容就完全没有问题；当使用其它SSH客户端登录同一服务器并且使用nano编辑文件，粘贴也是正常的，请查查是什么原因，谢谢！

**Comment by zxdong262** [comment]
是在win10的electerm1.12.7连接到ubuntu服务器？我试了一下，没有复现，请问nano和服务器是什么版本呢？

**Comment by cantona97** [comment]
> 是在win10的electerm1.12.7连接到ubuntu服务器？我试了一下，没有复现，请问nano和服务器是什么版本呢？

GNU nano 5.2    Ubuntu Server 20.04

**Comment by zxdong262** [comment]
最新版应该已经修复
