### ISSUE TITLE
tab栏能设置hide/show吗

### ISSUE THREAD

**Issue by macomzzl** [electerm/electerm#2095]
这几个部分现在能自定义显示还是隐藏吗？太影响阅读代码的可使用空间了
![image](https://user-images.githubusercontent.com/7599290/112930273-8fbcf700-914c-11eb-9a01-ce6382c23178.png)
![image](https://user-images.githubusercontent.com/7599290/112930300-9a778c00-914c-11eb-9243-91e8a5d4616d.png)

**Comment by zxdong262** [comment]
我想想，怎么做这个功能

**Comment by zxdong262** [comment]
感谢反馈，将出现在下个版本
