### ISSUE TITLE
mac绿屏

### ISSUE THREAD

**Issue by HAND-kemeng** [electerm/electerm#2097]
![image](https://user-images.githubusercontent.com/69496103/112985868-578cd700-9193-11eb-9dbb-944fbe71b2ab.png)

**Comment by zxdong262** [comment]
方便详细描述下怎么触发吗？

**Comment by HAND-kemeng** [comment]
打开就绿屏了，重新安装了也是这样。

**Comment by HAND-kemeng** [comment]
@zxdong262 重启电脑好了
