### ISSUE TITLE
360报node-pty为木马

### ISSUE THREAD

**Issue by CLovinr** [electerm/electerm#2098]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Current Behavior

360报node-pty为木马：
![image](https://user-images.githubusercontent.com/8369542/113095658-6bcde400-9226-11eb-8ecc-40e48508fdc8.png)

**Comment by zxdong262** [comment]
安全方面我没有研究，我也不知道怎么回事。

**Comment by joket1999** [comment]
node-pty是微软的(https://github.com/microsoft/node-pty)，你的360放行就可以

**Comment by CLovinr** [comment]
好的，谢谢
