### ISSUE TITLE
服务端仅允许 SFTP 链接时链接无法完成

### ISSUE THREAD

**Issue by meilonme** [electerm/electerm#2100]
![image](https://user-images.githubusercontent.com/27793923/113385681-30b0e980-93bb-11eb-9e90-3b0b67a92c2e.png)
![image](https://user-images.githubusercontent.com/27793923/113385709-3c9cab80-93bb-11eb-873c-75df63966f8e.png)
服务端设置为禁止SSH链接时, SFTP 链接一直无法完成;

**Comment by zxdong262** [comment]
这种情况我还没试过，得研究一下

**Comment by 996uci** [comment]
+1, 我也遇到了

**Comment by AminYabut** [comment]
I also have game servers that only allow sftp connections only no ssh. would be great for an option to just connect thru sftp only.
