### ISSUE TITLE
[deb]关闭检查更新无效

### ISSUE THREAD

**Issue by yftls** [electerm/electerm#2102]
OS : deepin 20.2
electerm v : 1.12.9
描述 : 在设置中关闭"启动时检查更新"后无效果.启动时还是弹框"检查失败:获取不到版本信息".

**Comment by yftls** [comment]
经过对其他基debian的发行版测试后,暂时确定是deepin底层调用的问题.
deepin20.2此次更新自身的问题也较多,但通过utools调用electerm时不会复现此问题.

**Comment by zxdong262** [comment]
oh不对，这个bug存在
