### ISSUE TITLE
请问下我想把CTRL + 2 送到shell里面应该怎么做?

### ISSUE THREAD

**Issue by androidfans** [electerm/electerm#2103]
我把 Ctrl+2 配置成了zsh的auto suggestion的accept suggest.
但是按Ctrl+2好像没有生效
默认的那个把electerm拉到前台的配置已经改到其他键了

**Comment by androidfans** [comment]
按键配置是没问题的  这台机器我接上键盘以后是可以正常用的.  用electerm远程就不行了

**Comment by zxdong262** [comment]
我研究一下

**Comment by zxdong262** [comment]
请问用其他的终端远程连接可以发送吗？

**Comment by androidfans** [comment]
@zxdong262  好吧试了windows terminal .  直接用wsl可以识别. 但是连上ssh好像就识别不了了.  可能是ssh的问题.
试了termius 也一样

**Comment by androidfans** [comment]
又尝试了一下,   用ubuntu 系统的自带terminal  ssh到远程机器上可以支持. 
用windows terminal 进入 wsl  在ubuntu 系统下 ssh到远程机器 也可以
