### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by NightSkyAurora** [electerm/electerm#2104]
![error](https://user-images.githubusercontent.com/33333107/113928456-1f1e7600-97ef-11eb-9726-509b963b26f2.png)
![error2](https://user-images.githubusercontent.com/33333107/113929227-19756000-97f0-11eb-9523-936fab08d1e0.png)
![error3](https://user-images.githubusercontent.com/33333107/113929242-1f6b4100-97f0-11eb-8f47-148cab7a8917.png)

Only shows when running Electerm for the first time. The application starts regardless.

Linux Manjaro 64-bit
KDE Plasma 5.21.3
electerm-1.12.9-linux-x64.tar.gz

**Comment by zxdong262** [comment]
So from second time run, do not show this any more?
