### ISSUE TITLE
sz 命令在 99% 卡住

### ISSUE THREAD

**Issue by 5139** [electerm/electerm#2113]
## Electerm version:
截至目前的最新版本上（v1.12.15）仍存在此问题。

## Operating system(linux, macos, or windows7/8/10?):
运行 electerm 的客户端：windows 10
远程：Ubuntu 20.04

## Can you reproduce the same behavior in other terminal:
在 3 台不同的电脑上试过，复现率 100%

## Current Behavior
sz -be file
接收文件到 99% 就不动了。这个时候看接收文件的大小，已经接收完了。
实际查看已经接收的文件，也是完整的。
这个时候只能点击“取消”才能继续，但是一旦取消，再运行下一个 sz 命令就没有响应了。
也就是说，一旦取消过 sz 接收，必须重新启动 electerm，再运行 sz 命令才会有响应。

## Detailed Description
如图，看字节数，34280 已经全部下载完，但进度是 99%，不动了。
![99](https://user-images.githubusercontent.com/50733782/114996323-4cdf7b00-9ed1-11eb-825e-1b997ffa0e16.png)

## Suggestions?
建议解决此两个问题：
1、sz 下载到 99% 卡住；
2、取消 sz 接收以后，需要重新启动 electerm 才能再次运行 sz。

**Comment by Loovelj** [comment]
客户端mac，服务器ubuntu1604,现在sz还是卡在99%

**Comment by lonnywong** [comment]
@5139 @Loovelj 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
