### ISSUE TITLE
quick-command 在 windows powershell 下命令顺序颠倒

### ISSUE THREAD

**Issue by foxes1998** [electerm/electerm#2117]
## Electerm version: 
1.12.15

## Operating system(linux, macos, or windows7/8/10?):
windows 10 ( powershell )

## Expected Behavior

quick-command 中的指令按顺序在 powershell 中执行

## Can you reproduce the same behavior in other terminal:

在 macOS、linux 测试结果符合预期(包括在 win 下使用 ssh 连接到 linux 也符合预期)

## Current Behavior & steps

![在 win powershell 环境，指令顺序反了](https://ftp.bmp.ovh/imgs/2021/04/0e57a5894124e473.gif)

**Comment by zxdong262** [comment]
确实存在, 我还不知道原因，临时方案可以用 `;`来分割, `cd xxxx ; pwd`
