### ISSUE TITLE
lrzsz上传文件一直显示99%

### ISSUE THREAD

**Issue by 280455936** [electerm/electerm#2120]
![image](https://user-images.githubusercontent.com/12490349/115978437-f7caf580-a5b1-11eb-84e8-8142d5486b9a.png)

**Comment by 280455936** [comment]
lrzsz上传文件一直显示99%

**Comment by darrenliuwei** [comment]
我有时候也会遇到，重新上传一次就好了

**Comment by NeilXu2017** [comment]
mac 上 sz 命令每次都是停留在这里, 尽管文件已经保存到指定位置了,已经下载成功, 如果关掉这个页面, ssh 页面也不可用了显示 一小段乱码.  又需要重新登录了, 很麻烦

**Comment by lonnywong** [comment]
@280455936 @darrenliuwei @NeilXu2017 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
