### ISSUE TITLE
[建议]增加“使用系统标题栏和边框”

### ISSUE THREAD

**Issue by rexlevin** [electerm/electerm#2121]
## Suggestions

我用的ubuntu unity，所有的窗口按钮都在左边，就electerm没有窗口边框，是自己实现的，是在窗口右上角。
为了和系统的风格统一，希望能像chrome一样，可以选择“使用系统标题栏和边框”。
谢谢。

**Comment by muyixiaohui** [comment]
https://github.com/electerm/electerm/issues/2147
