### ISSUE TITLE
密码明文存储 passwords are stored without encryption

### ISSUE THREAD

**Issue by lengran** [electerm/electerm#2122]
## Electerm version: 
        v1.12.19
## Operating system(linux, macos, or windows7/8/10?):
        Win10
## Expected Behavior
        密码被加密保存
        Passwords are encrypted before being saved on disk.

## Can you reproduce the same behavior in other terminal:
        其他终端是加密保存的。
        Yes, other terminals I used to use save passwords with encryption.

## Current Behavior
        密码明文存储，直接可以看到
        I can open the DB simply using a notepad and get all saved passwords.

## Possible Solution
        增加加密？允许用户设置一个主密码，或者非对称加密什么的？不知道……
       Add an encryption module? Something like that. Maybe allow user to set a main password and use that to encrypt all the important info.

**Comment by ranbest** [comment]
现在居然还有密码不加密保存的？

**Comment by lengran** [comment]
这加密算法形同虚设啊……
