### ISSUE TITLE
设置背景图之后重启就会变成无背景图片的

### ISSUE THREAD

**Issue by Kris-shen** [electerm/electerm#2123]
win10
v1.12.19
## Expected Behavior
设置背景图之后 重启软件应该显示之前设置的背景图。并且可以随意更换背景图

## Current Behavior
设置背景图之后关掉重新启动会变成无背景图片的模式，这时再设置图片或者调成默认背景，背景图都无法改变；
将选项选择为默认背景，然后关掉重启软件，就变成默认背景图了，而且可以随意更换。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
