### ISSUE TITLE
Windows下无法分屏

### ISSUE THREAD

**Issue by chenstin** [electerm/electerm#2139]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Expected Behavior

windows中，拖动程序窗口至最左边/右边，正常情况下程序会自动缩放为显示器一半的大小。

## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?

目前无法分屏，建议支持。windows有分屏功能，但是electerm好像不支持。

**Comment by zxdong262** [comment]
最新版加了个使用系统标题栏的设置，应该这样就可以了
