### ISSUE TITLE
本地文件上传远程服务器报错

### ISSUE THREAD

**Issue by hsessay** [electerm/electerm#2140]
本地Mac 系统版本11.2.3
远程服务器信息
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:        6.5
Codename:       Santiago

**问题1：**
手动编译打包了Vue开发的项目后，选中dist里面所有文件上传至远程服务器，无论是覆盖原有文件还是删除原有文件上传，均报以下错误
<img width="1383" alt="Snipaste_2021-05-13_11-32-02" src="https://user-images.githubusercontent.com/5794389/118073691-f0dc1980-b3de-11eb-86d6-89d7a99e3eb8.png">

文字信息：
at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.21:2:387810
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.21:2:321009)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.21:2:321939)

**问题2：**
点击取消上传后，远程服务器文件分页一直如图loading
<img width="1390" alt="Snipaste_2021-05-13_11-26-40" src="https://user-images.githubusercontent.com/5794389/118073341-39470780-b3de-11eb-8027-874de84edcdd.png">

**Comment by zxdong262** [comment]
上传多层文件夹有bug，可以打包再上传再解压这样

**Comment by rainto** [comment]
同  ：

ror: Failure at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:388320 at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:321254) at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:322184)
Failure
Error: Failure at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:388320 at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:321254) at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:322184)
Failure
Error: Failure
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:388320
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.12.24:2:321254)
    at Worker.<anonymous> (file:///Applicatio

**Comment by sufylaw** [comment]
我也遇到了，这个问题能否解决一下，打包上传再解压有点麻烦

**Comment by duktig666** [comment]
上传速度有影响吗，我上传了25M的文件夹，用时超过了报个小时还没上传完

**Comment by zxdong262** [comment]
建议使用右键菜单里的压缩上传 @sufylaw @duktig666
