### ISSUE TITLE
Installation failed via npm i -g

### ISSUE THREAD

**Issue by rapha8l** [electerm/electerm#2143]
Hi,

I'm trying to install electerm via root on Void Linux
I get this

> npm i -g electerm
> 
> /usr/bin/electerm -> /usr/lib/node_modules/electerm/npm/electerm
> 
> > electerm@1.10.4 postinstall /usr/lib/node_modules/electerm
> > node npm/install.js
> 
> downloading https://github.com/electerm/electerm/releases/download/v1.12.24/electerm-1.12.24-linux-x64.tar.gz
> (node:21356) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electerm/electerm-1.12.24-linux-x64'
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:21356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:21356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> + electerm@1.10.4
> 

Part of the package is written, but not enough to make it run

Thanks

**Comment by zxdong262** [comment]
I see, I would suggest you install npm/nodejs with [nvm](https://github.com/nvm-sh/nvm), which only use local user permission, then `npm i -g` will not encounter permission issue.
