### ISSUE TITLE
是否可以考虑增加一个X11-forwarding转发功能

### ISSUE THREAD

**Issue by kevinsun6610** [electerm/electerm#2149]
不知道本软件是否有服务器上运行 GUI 程序 (即 X client)，通过 SSH X11 Forwarding，转发到本地 (机器上的X Server)。
是否可以增加一个X11-forwarding转发功能，windows上有xmanager里面可以实现，mac的终端软件有这个功能的太少了。

**Comment by zxdong262** [comment]
选项里有个x11, 你可以试试行不行

**Comment by kevinsun6610** [comment]
![image](https://user-images.githubusercontent.com/38686609/119593587-d6596580-be0c-11eb-808a-faa795fa35a7.png)
![image](https://user-images.githubusercontent.com/38686609/119593652-ec672600-be0c-11eb-88e3-aef3af3bbc88.png)
开了，用oracle的dbca测了下好像没反应，正常应该会弹出对话框，有日志么？在哪可以看到

**Comment by zxdong262** [comment]
我在mac试了一下是可以的，如果是windows下，需要装特定的软件，哪一种我也忘记了

**Comment by kevinsun6610** [comment]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/38686609/119798938-308e1f80-bf0e-11eb-95bc-7a2bb53979e7.png">

我的也是mac，和macos版本有关么？
除了在设置那把x11打开，还有别的设置么？

**Comment by zxdong262** [comment]
@kevinsun6610 需要安装 https://www.xquartz.org/
