### ISSUE TITLE
终端界面，快速命令——右键——新建、编辑

### ISSUE THREAD

**Issue by xuchuan40444** [electerm/electerm#2152]
![image](https://user-images.githubusercontent.com/39369888/120072427-768de380-c0c6-11eb-8f52-9201526a316f.png)

**Comment by xuchuan40444** [comment]
同时
![image](https://user-images.githubusercontent.com/39369888/120072515-e2704c00-c0c6-11eb-8f47-6e5d56dc51f0.png)

**Comment by darrenliuwei** [comment]
> 同时
> ![image](https://user-images.githubusercontent.com/39369888/120072515-e2704c00-c0c6-11eb-8f47-6e5d56dc51f0.png)

这个深有同感
