### ISSUE TITLE
设置后配置未保存/sz功能异常？

### ISSUE THREAD

**Issue by huai168an** [electerm/electerm#2158]
win7 专业版 sp1
1. “setting”功能配置后，正常，然后关闭程序，再次打开，所有配置就还原了

2. sz 将文件下载到本地后，怎么会自动加.txt 后缀，无论下载的是执行文件，还是普通的如Dockerfile文件，到本地pc后就自动加了 .txt了，是不是没后缀的文件，这个终端自动加的？这个完全没必要吧

**Comment by lonnywong** [comment]
@huai168an 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
