### ISSUE TITLE
UWP应用安装失败

### ISSUE THREAD

**Issue by Baizhixi** [electerm/electerm#2159]
`此应用包未使用受信任的证书签名。请与系统管理员或应用程序开发人员联系，以获取新证书或带有受信任证书的应用程序包。应用程序包中签名的根证书和所有即时证书必须受信任（0x800B010A）`
似乎没有包含证书，已开启开发者模式

**Comment by zxdong262** [comment]
方便提供详细的信息吗，就模板那些？
