### ISSUE TITLE
大佬，不能上划查看前面的记录啊

### ISSUE THREAD

**Issue by MuChen886** [electerm/electerm#2165]
不能鼠标上划查看前面的记录，希望批量输入是固定位置的不要这样收缩。
大佬，不能上划看历史记录这很重要，我不想换软件啊。。。。

**Comment by zxdong262** [comment]
方便详细描述下吗？

**Comment by MuChen886** [comment]
鼠标中键滑动不能上下滑动查看历史记录

**Comment by darrenliuwei** [comment]
> 鼠标中键滑动不能上下滑动查看历史记录

我刚刚试了下，可以上下滑动查看历史记录呀

**Comment by MuChen886** [comment]
不知道为什么我这边是只有命令之前输入的命令在切换，并且重装设置不变，恢复默认设置也没恢复回来

**Comment by zxdong262** [comment]
操作系统和软件版本？

**Comment by MuChen886** [comment]
win10
软件版本electerm-1.13.4-win-installer

**Comment by MuChen886** [comment]
![QQ图片20210615180648](https://user-images.githubusercontent.com/55978588/122034842-7c90fd80-ce04-11eb-8a1b-1206db57700f.png)

**Comment by MuChen886** [comment]
您好，我终于发现问题出在哪里了，问题就出在screen这个插件里，只要使用它创建了会话窗口和加载会话窗口就会导致不能使用
鼠标滚轮来滑动，其他软件是可以实现鼠标滚轮滑动的，希望作者能更新一下这个问题。

**Comment by zxdong262** [comment]
> 您好，我终于发现问题出在哪里了，问题就出在screen这个插件里，只要使用它创建了会话窗口和加载会话窗口就会导致不能使用
> 鼠标滚轮来滑动，其他软件是可以实现鼠标滚轮滑动的，希望作者能更新一下这个问题。

请问screen插件是什么，可以给个链接吗？

**Comment by MuChen886** [comment]
在CentOS服务器上输入：yum install -y screen 即可安装，这是他的官网：http://www.gnu.org/software/screen/
这是命令详解：https://www.cnblogs.com/mchina/archive/2013/01/30/2880680.html
screen是一个可以实现会话分离恢复和多用户共享同一个窗口内容的插件，只要加载它就不能使用鼠标滑动历史记录。

**Comment by zxdong262** [comment]
> 在CentOS服务器上输入：yum install -y screen 即可安装，这是他的官网：http://www.gnu.org/software/screen/
> 这是命令详解：https://www.cnblogs.com/mchina/archive/2013/01/30/2880680.html
> screen是一个可以实现会话分离恢复和多用户共享同一个窗口内容的插件，只要加载它就不能使用鼠标滑动历史记录。

请问其他的终端即便开了screen也一样可以鼠标滚轮滑动吗？

**Comment by MuChen886** [comment]
可以

**Comment by zxdong262** [comment]
https://stackoverflow.com/questions/359109/using-the-scrollwheel-in-gnu-screen

这里看到个说法说用终端类型vt100可以，你方便测试下吗

**Comment by MuChen886** [comment]
因为我使用screen是为了挂着服务器，这个插件能让我在关了软件后重新连接进来到我服务器的窗口，所以我开了服务器Linux的命令就不能在使用

**Comment by MuChen886** [comment]
所以这个应该也实现不了

**Comment by MuChen886** [comment]
我尝试使用刚刚你发过来里面说得命令，返回的是我服务器提示没有此命令
![image](https://user-images.githubusercontent.com/55978588/122151192-b1976180-ce91-11eb-9d67-333cc5217713.png)

**Comment by MuChen886** [comment]
所以说目前Linux的命令我是无法在使用了

**Comment by zxdong262** [comment]
@MuChen886 我是说在electerm新建书签时候设置里选择vt100作为终端类型

**Comment by zxdong262** [comment]
<img width="1542" alt="Screen Shot 2021-06-16 at 12 24 03 PM" src="https://user-images.githubusercontent.com/1641949/122157707-e7dade00-ce9d-11eb-901f-e3927103991a.png">

**Comment by MuChen886** [comment]
可以了，感谢！！！

**Comment by getfox** [comment]
我发现连接到Ubuntu18.04系统中以后特定场景下也有类似的问题：开启了tmux以后就无法向上滚动查看历史输出了，只能够查看历史输入。

**Comment by KangodYan** [comment]
> @MuChen886 我是说在electerm新建书签时候设置里选择vt100作为终端类型

使用 mosh 之后也出现这个问题，设置 vt100 为终端类型也可以解决
