### ISSUE TITLE
win10 x64家庭中文版 卡启动界面 无法打开

### ISSUE THREAD

**Issue by 0cat-r** [electerm/electerm#2167]
一直无法打开 卡在启动界面
![image](https://user-images.githubusercontent.com/49912303/122376266-93675980-cf96-11eb-8ce4-a0eecfa9daa6.png)

**Comment by zxdong262** [comment]
请问哪个版本，什么渠道安装的或者下载的哪个包？

**Comment by 0cat-r** [comment]
最新版本 就在此github下载的

**Comment by 0cat-r** [comment]
用习惯了 突然有天打不开。。。然后我升级之后还是不行 ，此间win10系统更新过一次目前系统版本号19042.1052

**Comment by zxdong262** [comment]
可以命令行运行看看什么错误吗

**Comment by zxdong262** [comment]
另外windows store 也发布了，可以试试安装store版本吗？

**Comment by 0cat-r** [comment]
感谢回复 已经解决了  实际上我也不知道为什么 刚又试了一下 就可以了
