### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by liuxin2533** [electerm/electerm#2168]
使用sftp点击远程的/etc和/root目录会报如下错误, 使用ssh命令行可以正常cd进入。

Permission denied
Error: Permission denied at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.13.4:2:1505560 at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.13.4:2:1438032) at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.13.4:2:1438961

**Comment by zxdong262** [comment]
请问登录的用户是什么权限呢？root还是sudoer?

**Comment by SekiBetu** [comment]
提供一个不确定是否安全的做法：

```shell
sudo vim /etc/ssh/sshd_config
```

修改

```shell
Subsystem sftp  /usr/lib/openssh/sftp-server
```

为

```shell
Subsystem sftp sudo /usr/lib/openssh/sftp-server
```
