### ISSUE TITLE
👍 好应用，已收录，感谢开发者！

### ISSUE THREAD

**Issue by macwkcom** [electerm/electerm#2169]
![image](https://user-images.githubusercontent.com/53843550/122954837-5c3be280-d3b2-11eb-8760-ed8d5d7c671e.png)

[收录地址](https://www.macwk.com/soft/electerm)

因为并不是多有开发者都需要被宣传，如果开发者觉得不合适，回复我一下，我把它下掉。🥰

**Comment by zxdong262** [comment]
@macwkcom 我看到了，网站做的挺好的，欢迎分发
