### ISSUE TITLE
建议将sftp客户端单独分离出来

### ISSUE THREAD

**Issue by shinebay** [electerm/electerm#2171]
目前市面上ssh工具很多，而sftp客户端很少，electerm的sftp显得有点鸡肋，功能简单。建议单独将sftp单独分离出来打造一个好的sftp客户端，优化好一点的在线编辑器，将远程文件操作能够像Windows本地文件操作一样得心应手，感谢作者的努力！

**Comment by rexlevin** [comment]
我觉得放里面挺好的，不用要分出来。
本来现在sftp需要用，但是用得却又不多，有个这个作为有益补充还挺好的。

**Comment by darrenliuwei** [comment]
我觉得还是不要分出来吧

**Comment by SHANGJX** [comment]
对, 我也觉得放里面挺好的

**Comment by zxdong262** [comment]
暂时无此计划
