### ISSUE TITLE
Error in sychronization

### ISSUE THREAD

**Issue by lannyyip** [electerm/electerm#2172]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
V1.13.4 and early versions
## Operating system(linux, macos, or windows7/8/10?):
Windows 10
## Expected Behavior

I have difficulty in sychronization.
a . Enable proxy for the reason you know.
b.  Fill in the secrect key and gist id
c.  Save config and download
d. Promted as follow:
 "Error: Seems you have a empty gist, you can try use existing gist ID or upload first
    at Proxy.e.downloadSetting (file:///C:/Users/YourUser/AppData/Local/Programs/electerm/resources/app.asar/assets/js/electerm.js?1.13.4:2:1718962)"
## Can you reproduce the same behavior in other terminal:

Yes, I am not getting well in sychronization for my different terminals.

## Current Behavior

Can not Sychronize.
## Possible Solution

1. Fix the sychronize issue with gist.
2. May be kind to provide file import for the config / bookmarks.
## Steps to Reproduce

1. Enable proxy for the reason you know.
2. Fill in the secrect key and gist id
3. Save config and download
4.Promted as follow:
 "Error: Seems you have a empty gist, you can try use existing gist ID or upload first
    at Proxy.e.downloadSetting (file:///C:/Users/YourUser/AppData/Local/Programs/electerm/resources/app.asar/assets/js/electerm.js?1.13.4:2:1718962)"

**Comment by zxdong262** [comment]
I tried in mac and win10, all works as expected, possible guess is proxy issue or maybe typo? Can you check again? or try gitee? Also you can export/import from bookmark page
