### ISSUE TITLE
您好 electerm如何配置Teleport调用呢？

### ISSUE THREAD

**Issue by Pililink** [electerm/electerm#2173]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.12.15
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Expected Behavior

在堡垒机中链接服务器时调用Electerm 进行连接。
## Current Behavior

![image](https://user-images.githubusercontent.com/29655914/123355951-49cfcd80-d599-11eb-812d-28af58c456ae.png)
我通过这样的配置无法进行连接。
## Possible Solution
![image](https://user-images.githubusercontent.com/29655914/123356015-6a982300-d599-11eb-9cd9-ba860588b34f.png)
Xshell通过这样可以链接。
请问Electerm 该如何配置呢?

 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
试试按照这个：https://github.com/electerm/electerm/wiki/Command-line-usage
