### ISSUE TITLE
Windows: Does not snap

### ISSUE THREAD

**Issue by splitice** [electerm/electerm#2174]
Electerm version: 1.13.4

Operating system(linux, macos, or windows7/8/10?): Windows 10

Drag to top of screen after opening. Application does not snap or resize.

**Comment by zxdong262** [comment]
Can you try turn on use system menu bar in settings

**Comment by splitice** [comment]
Yes, with system menu bar enabled the window snaps correctly.

**Comment by splitice** [comment]
Can I suggest that this remains a bug? The system menu bar isnt exactly great.

**Comment by zxdong262** [comment]
> Can I suggest that this remains a bug? The system menu bar isnt exactly great.

Sure, can you provide more detail?
