### ISSUE TITLE
无法修改默认字体。

### ISSUE THREAD

**Issue by fenghuan1994** [electerm/electerm#2176]
Ubuntu18.04
snap安装的edge通道1.13.4版本和1.13.1stable版本均有此问题
无法修改默认字体，点击默认字体框显示No data。
见附件图片。
![深度截图_选择区域_20210630153458](https://user-images.githubusercontent.com/22291785/123920899-0ae6b100-d9b9-11eb-9061-fcd137c7fe8c.png)

**Comment by zxdong262** [comment]
确实如此，估计是font-list这个包没有正确在linux版本编译，得研究一下

**Comment by zxdong262** [comment]
@fenghuan1994 snap版本有更严格的权限限制，其他版本应该没问题

**Comment by zxdong262** [comment]
安装时候使用` --classic`就可以了 `snap install electerm --classic`

**Comment by fenghuan1994** [comment]
感谢大佬解决这个bug。
