### ISSUE TITLE
Mac m1版本的，希望添加xml，shell等特殊文件语法高亮

### ISSUE THREAD

**Issue by 1298509345** [electerm/electerm#2177]

**Comment by 4860575** [comment]
希望作者添加M1的支持。

**Comment by nizongdai** [comment]
同样的诉求，M1处理器应该下载哪个版本的dmg呢？

**Comment by zxdong262** [comment]
已经加入，参考https://github.com/electerm/electerm/wiki/Terminal-keywords-highlight-regular-expression-exmaples
