### ISSUE TITLE
SFTP error with SOCKS proxy in MacOS big sur 

### ISSUE THREAD

**Issue by YaoYinYing** [electerm/electerm#2183]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
1.13.4
## Operating system( ):
macos big sur latest ver

## Expected Behavior

Remote folder should be shown in Sftp session

## Can you reproduce the same behavior in other terminal:

Transmit5 (MacOS, same machine) didnot work in that proxy condition either

MobaXterm and Xftp in my Windows machine work with that Socks proxy

## Current Behavior

SSH over SOCKS5 proxy works but SFTP never does. No remote content shows

error msg bubble: 
Error: Unexpected packet before version
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.13.4:2:1505560
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.13.4:2:1438032)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.13.4:2:1438961)

## Possible Solution

I aways transfer my files via an windows host running RDP then send them to my destination host with Xftp.

## Steps to Reproduce

1. Running Easyconnect in docker (see https://github.com/Hagb/docker-easyconnect) to create a SOCKS5 proxy
2. in Electerm bookmark preference, set the hostname and port of proxy for session use
3. Create an SSH session. this works.
4. Open attached Sftp session (error bubble and blank)

**Comment by zxdong262** [comment]
@YaoYinYing I tried my sock5 proxy, it works, so I think it is something related to proxy that I do know yet.

**Comment by YaoYinYing** [comment]
Thx for ur quick reply. I have already solved this problem with endless and painful tests within these days. It's accurally caused by a `echo something` command in `~/.bashrc` of my host. It's weird but works.
