### ISSUE TITLE
Session time

### ISSUE THREAD

**Issue by WebProviderNGO** [electerm/electerm#2185]
Hi, I have a short session time so I have to reboot the connection and run the commands again. The session time is configured on the server or is it an electerm setting?

**Comment by zxdong262** [comment]
Inertnally it send keep alive pack every 10 seconds, so would it expire if you do not input anything for 10 seconds?

I think I should add a setting so user can decide it.

**Comment by WebProviderNGO** [comment]
Yes, I do not enter data and after 10 seconds the session stops.
It would be great to add a session time setting or always work.

**Comment by BigBull-man** [comment]
How can this problem be solved
