### ISSUE TITLE
又出现了 win10 最新版本无法打开

### ISSUE THREAD

**Issue by 0cat-r** [electerm/electerm#2186]
命令行下显示报错
14:17:28 debug 鈥?electerm start
useSystemTitleBar false
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:30975
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 30975

netstat -ano  显示端口30975并没被占用。

**Comment by zxdong262** [comment]
这可能跟你本机情况有关，试试其他机器能复现吗？或者重启什么的？

**Comment by 0cat-r** [comment]
可以 我同事的win10 也是这样  一直卡 其他机器完全可以复现  我看了这几天提的issues 也有人遇到了啊

**Comment by 0cat-r** [comment]
![image](https://user-images.githubusercontent.com/49912303/125554030-44c91f47-56e1-41d9-beab-5498dc19b073.png)

**Comment by zxdong262** [comment]
可以试试用admin权限运行吗？

**Comment by 0cat-r** [comment]
不是权限问题导致的 呜呜 有时候他又正常 不行的时候  admin
权限也是这样

**Comment by Nguyendream** [comment]
是不是启用了hyper-v，会随机保留（占用）端口的，使用`netstat -ano`是查不到的

使用以下命令查看保留端口，如果端口30975在`开始端口`和`结束端口`之间，则复现问题
```
netsh int ipv4 show excludedportrange protocol=tcp
```

@zxdong262 目前遇到这个问题会卡在加载页，不用命令行启动无法得知。
造成此问题的主要原因是固定端口30975被占用/无权限

是否可以采用动态端口的策略呢，监听端口失败，则换个端口重试

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/2548#issuecomment-1842513418 有人说这样可以解决
```
net stop winnat

net start winnat
```
