### ISSUE TITLE
在windows server2016上打开是白屏 没有任何显示

### ISSUE THREAD

**Issue by yufengshizhe** [electerm/electerm#2196]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以命令行运行看看什么错误吗？

**Comment by yufengshizhe** [comment]
useSystemTitleBar false
12:27:43 info 鈥?server runs on 127.0.0.1 30975
12:27:43 debug 鈥?error parsing $HOME/.ssh/config
12:27:43 debug 鈥?maybe no $HOME/.ssh/config, but it is ok
12:27:43 info 鈥?database version: 1.14.0
12:27:47 debug 鈥?ws: connected to terminal -> 1TJ22uHdiARPry8f9mHSG

**Comment by cagianx** [comment]
I am experiencing the same problem with Windows 10 but within HyperV. On my windows machine it works perfectly.
It seems to be a deep level rendering issue, between the graphics drivers and electron because I don't see any errors in the console either.

**Comment by lightnear** [comment]
windows 10上打开白屏，我的windows 10是esxi中的虚拟机

**Comment by malsony** [comment]
我笔记本上能运行，但是两台台式一台正常一台却也是白屏。三台全都是win10最新版

**Comment by feidie12** [comment]
这个问题我在虚拟机环境下必现，只要远程到虚拟机上，打开就会白屏。

**Comment by zxdong262** [comment]
可以试试最新版吗
