### ISSUE TITLE
强烈建议增加 Port tunnel 功能

### ISSUE THREAD

**Issue by tonycody** [electerm/electerm#2197]
端口映射会有很多这种需求，强烈建议增加这样的功能。
![image](https://user-images.githubusercontent.com/6773121/126885843-a17c898b-9f7c-4b47-a00a-4d8f153ec52d.png)

可以参考 Windows 下的 SSH Tunnel、Mac 下的SSH Manager

**Comment by zxdong262** [comment]
好的，感谢反馈

**Comment by zxdong262** [comment]
已经加入ssh tunnel支持
