### ISSUE TITLE
sz怎么指定默认的下载路径

### ISSUE THREAD

**Issue by dlinka** [electerm/electerm#2198]
每次下载多个文件  每个文件下载成功后都要选择路径

**Comment by zxdong262** [comment]
目前不支持，利用第三方的zmodem组件，功能有限

**Comment by lonnywong** [comment]
使用 [trzsz](https://github.com/trzsz/trzsz) ( trz / tsz ) 是可以支持的，需要为 electerm 增加配置项的功能，详见 https://github.com/electerm/electerm/issues/2407
