### ISSUE TITLE
能否增加个选项，软件启动后可以不自动打开本地terminal。

### ISSUE THREAD

**Issue by xSeaGull** [electerm/electerm#2200]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.14.0
## Operating system(linux, macos, or windows7/8/10?):
macos
## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?

能否增加个选项，软件启动后可以不自动打开本地terminal。
很多时候，其实只是想拿它远程ssh。

**Comment by rexlevin** [comment]
这个建议好，等待加上这个配置选项。
