### ISSUE TITLE
建议增加同步功能或改为Portable模式

### ISSUE THREAD

**Issue by malsony** [electerm/electerm#2202]
虽然GitHub、Gitee可以免费使用，但是如果用户可以将“书签”以文件的形式存到用户付费或自建的文件服务器，会不会更灵活？

**Comment by malsony** [comment]
我又想了一下，好像更理想的设计应该是这样：

1. 用户可能用多个版本的便携模式Electerm（Win、Lin、Mac）；
2. 但是用户希望在不同平台上使用Electerm的时候，“书签”都是一致的（可能需要把“书签”改成“站点”或“连接”，可以放到另一个目录）

**Comment by MasterOfStar** [comment]
也许webdav形式会比较合适？

**Comment by malsony** [comment]
> 也许webdav形式会比较合适？

是啊，现在我就是把eleterm放在自建的owncloud。要是“书签”也放在另一个目录，就可以实际不同平台的客户端都用同一个“站点管理器”了。

**Comment by malsony** [comment]
呃，系统升级到Windows 11预览版，现在书签全没了…… 😢

**Comment by jcm007** [comment]
像securecrt那样书签和设置都在某个文件夹里，或者整个软件都做成portable的，是吧？

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/pull/2916 将在下个版本支持便携化
