### ISSUE TITLE
改进建议！望采纳！！！

### ISSUE THREAD

**Issue by 443126500** [electerm/electerm#2212]
**作者你好，Mac系统，希望快捷命令能够批量导入导出，并且常驻下栏，感觉下拉框的方式展开不是很便捷，另外希望打开软件的时候是可供选择的，而不是打开默认终端，点击加号时，希望是可以选择服务器进行链接，毕竟自带的终端用的不是很多，都是链接服务器进行使用，鼠标移动到服务器列表的时候，服务器信息已经显示很清楚了，不需要再有个鼠标悬浮显示服务器信息了，会遮挡服务器列表的视图，设置界面的关闭按钮太迷你了，不是很好看到，希望更改下！！望采纳 ， 祝electerm越做越好！！！**
![image](https://user-images.githubusercontent.com/57339701/129134649-a247a513-3c8a-49c7-8f29-9aea637c89df.png)
![image](https://user-images.githubusercontent.com/57339701/129134705-0dd0d20d-3a87-4de9-9240-564d56cac091.png)

**Comment by 443126500** [comment]
![image](https://user-images.githubusercontent.com/57339701/129134833-6e430468-109b-4adf-9e92-6e41293e0f2b.png)，快捷命令希望是常驻下栏更便捷
sftp如果可以和ssh在同一个窗口左右分屏或者上下分屏就更好了

**Comment by zxdong262** [comment]
感谢反馈

**Comment by zxdong262** [comment]
已经在新版本更新
