### ISSUE TITLE
在线更新一直无法使用（已扶墙）

### ISSUE THREAD

**Issue by geekbb** [electerm/electerm#2216]
如果要添加白名单，请告知域名
![image](https://user-images.githubusercontent.com/46196358/129501676-a3f6e724-a3b7-42b5-b84a-95966f5bead3.png)

**Comment by zxdong262** [comment]
请问当前版本是什么版本，什么操作系统？

**Comment by geekbb** [comment]
> 好像当前版本是什么版本，什么版本？

从v1.14.0 升级到v1.15.3 
从v1.15.3 升级到v1.16.1 
都是如此

**Comment by zxdong262** [comment]
确实有问题，从1.16版本应该可以
