### ISSUE TITLE
快速命令是否支持分组管理？

### ISSUE THREAD

**Issue by geekbb** [electerm/electerm#2217]
![image](https://user-images.githubusercontent.com/46196358/129501871-7086a130-9fa3-406c-8e10-c44ff1b964aa.png)

**Comment by zxdong262** [comment]
不支持，也许在下个版本

**Comment by geekbb** [comment]
> 不支持，也许在下个版本

谢谢付出

**Comment by zxdong262** [comment]
加入了标签过滤
