### ISSUE TITLE
最新版本使用建议！

### ISSUE THREAD

**Issue by 443126500** [electerm/electerm#2219]
![image](https://user-images.githubusercontent.com/57339701/129652054-cb95d04c-1dea-4c33-91c1-4be6f270d4a3.png)
Mac 10.15.7 点击设置-书签-serial（不知是啥功能）会闪退！<br/>
![image](https://user-images.githubusercontent.com/57339701/129652276-df0e3184-2cbc-4ec9-8557-fcc3dd12bb7a.png)
ssh和sftp能否支持同一个窗口左右或者上下分屏显示？<br/>
![image](https://user-images.githubusercontent.com/57339701/129652434-b9241323-3553-4895-94d9-bc3d32f86af9.png)
快捷命令是否考虑添加一个分组功能并且能够保持面板打开<br/>
打开软件是否可以调成手动选择需要链接的服务器而不是默认打开自身的终端？

**Comment by zxdong262** [comment]
@443126500 设置里有一个当程序启动时候打开的书签

**Comment by 443126500** [comment]
> @443126500设置里有一个当程序启动时打开的书签

看到了，但是默认窗口还是自身的终端。

**Comment by zxdong262** [comment]
下个版本不再打开默认本地终端，如果用户已经设置打开书签
