### ISSUE TITLE
进入 tmux 后 ctrl + 方向上 会出现 Normal buffer content 的窗口

### ISSUE THREAD

**Issue by ghost** [electerm/electerm#2221]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
1.16.1
## Operating system(linux, macos, or windows7/8/10?):
本地机器 windows10,目标机器 ubuntu20.04 server
## Expected Behavior

不出现Normal buffer content 的窗口

tmux 里的  ctrl + 方向上 用来切换窗口,弹出这个窗口比较碍事

## Can you reproduce the same behavior in other terminal:

别的term工具没有这个问题
## Current Behavior

不进tmux同样的操作不会出现这个窗口
## Possible Solution

这个窗口有什么作用?是否可以取消掉?
## Steps to Reproduce

1.进入tmux
2. 按  ctrl + 方向上

**Comment by weihaipy** [comment]
代码位于 electerm\src\client\components\terminal\normal-buffer.jsx

**Comment by zxdong262** [comment]
下个版本加入快捷键设置，可以改为其他键
