### ISSUE TITLE
bug,敲击1次，输入了多个字符

### ISSUE THREAD

**Issue by xtoshii** [electerm/electerm#2226]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Current Behavior

在命令行敲击一次会输入多个相同的字符，例如我输入 l , 实际却是 lll
## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

在命令行敲击一次会输入多个相同的字符，例如我输入 l , 实际却是 lll ,

**Comment by zxdong262** [comment]
本地终端还是连接服务器？可以提供更详细的复现步骤吗，我试了没有出现

**Comment by xtoshii** [comment]
> 本地终端还是连接服务器？可以提供更详细的复现步骤吗，我试了没有出现

刚刚才找到复现步骤：
0. 连接上远程服务器，
1. rz
2. 选择一个大于8M的文件上传（）
3. 上传失败后，敲击ls,实际输入 llllssss

**Comment by zxdong262** [comment]
哦，这个是已知问题，只有重新连接了
