### ISSUE TITLE
Jumpserver not able to exec

### ISSUE THREAD

**Issue by lemon9921010** [electerm/electerm#2227]
堡垒机使用非22端口 报错 Jumpserver not able to exec xxx/electerm.js   
关闭sftp功能 就不报错了， 希望同类问题有帮助

**Comment by zhouyuangan** [comment]
遇到了同样的问题，同时伴随着sftp没法显示服务器路径下文件夹

**Comment by yuanyiwei** [comment]
> 堡垒机使用非22端口 报错 Jumpserver not able to exec xxx/electerm.js
> 关闭sftp功能 就不报错了， 希望同类问题有帮助

![图片](https://user-images.githubusercontent.com/40692073/131240664-58d73728-fa99-4966-a1d4-ff0a03df3e91.png)

请问一下怎么设置 proxyjump，没有找到选项

**Comment by lemon9921010** [comment]
不用配置代理的

**Comment by yuanyiwei** [comment]
那怎么通过堡垒机登陆内部服务器呢，给稍微给下步骤吗

**Comment by lemon9921010** [comment]
ssh里面填堡垒机登录的信息， 登上堡垒机就行了，和xshell，scrt一样啊
