### ISSUE TITLE
freezes when i try to download files

### ISSUE THREAD

**Issue by manuelrojasc** [electerm/electerm#2228]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Expected Behavior
electerm is frozen when browsing, to transfer file, it does not stop or close the application

## Can you reproduce the same behavior in other terminal:
the same thing happens it is frozen in the file transfer navigation
## Current Behavior
it remains the same, I have already opened many times and do the same process many times

## Steps to Reproduce

1.open electerm
2.open the connection to your server, in this case my server is elsewhere, not on my machine
3.then go to sftp option, try to navigate folders to download a file
4.This is where the freezing happens, sometimes it stays charging

## Context (Environment)

I am trying to download some files from my server to my laptop
## Detailed Description

i nedd suggestions
![Sin título](https://user-images.githubusercontent.com/49658419/130699024-01a3d809-5cb1-4b88-abb4-984556e47cc4.png)

**Comment by manuelrojasc** [comment]
![image](https://user-images.githubusercontent.com/49658419/130699244-e6fd4302-776c-4491-9c18-ff353ab5574f.png)

**Comment by zxdong262** [comment]
It is a known issue, if need  download many files in folders, especially with sub folders, this would happen, try the compress and download menu, much faster and solid.

**Comment by manuelrojasc** [comment]
only download a one file not a many file or folder
