### ISSUE TITLE
书签太难移动了！

### ISSUE THREAD

**Issue by Suremotoo** [electerm/electerm#2236]
## Operating system(linux, macos, or windows7/8/10?):
macOS

书签上下移动，向上移动还好，向下移动死活没反应，偶尔成功几次

**Comment by zxdong262** [comment]
分类高亮的时候再松开鼠标

**Comment by Suremotoo** [comment]
我等了很久都没有提示高亮，偶尔才成功几次，成功的时候也没有高亮什么的。

**Comment by bulldevil** [comment]
1.16.11更新之后只要拖动书签就会被移动到所有书签最底部...

**Comment by chris-ss** [comment]
> 1.16.11更新之后只要拖动书签就会被移动到所有书签最底部...

同样情况

**Comment by tanyicheng** [comment]
同分类中的排序有问题，偶尔成功几次，希望尽快修复，或者默认根据‘标题’排序也行，ssh链接太多，不排序看不过来

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/releases/tag/v1.39.47 最新版重做了拖拽，可以试试
