### ISSUE TITLE
Quick Command 需要提高效率

### ISSUE THREAD

**Issue by edwardgc** [electerm/electerm#2238]
## Current Behavior
目前的quick command 需要鼠标移动两次， command数量多的时候需要大范围移动， 效率较低， 如果需要选择标签，则需要点击更多次

## Suggestion
增加快速命令窗口驻留选项， 并且可以设置该连接书签的缺省标签以减少点击次数

v1.16.5

**Comment by zxdong262** [comment]
最新版已经支持快速命令面板固定在底部
