### ISSUE TITLE
使用代理不能同步配置

### ISSUE THREAD

**Issue by edwardgc** [electerm/electerm#2241]
使用代理上传配置转圈一会后没有效果
使用代理下载配置报empty gist错误

v1.16.5

**Comment by zxdong262** [comment]
有设定gist ID 吗？
<img width="1017" alt="Screen Shot 2021-09-07 at 12 47 22 PM" src="https://user-images.githubusercontent.com/1641949/132285912-0558587b-7bc0-462d-a84d-a581a9bb2f9c.png">

**Comment by edwardgc** [comment]
设定了的， 因为公司电脑不能直连， 用手机开热点直连了就能sync成功， github和gitee都是如此

**Comment by zxdong262** [comment]
@edwardgc 什么代理呢，socks还是http?

**Comment by edwardgc** [comment]
http代理，不需要验证

**Comment by zxdong262** [comment]
@edwardgc http代理可能有问题，如果有sock5可以试试

**Comment by edwardgc** [comment]
手头没有sock5的代理，暂时还好，有 work around，用手机开个热点连一下同步，就是麻烦一点

**Comment by laggage** [comment]
同样的问题+1

**Comment by zxdong262** [comment]
最新版本已修复
