### ISSUE TITLE
m1 mac 

### ISSUE THREAD

**Issue by leqq00** [electerm/electerm#2242]
希望增加 Mac m1 版本的安装包

**Comment by zxdong262** [comment]
将在下一期加入安装包，不一定能用，因为我没有设备测试，欢迎到时候下载试试

**Comment by devourbots** [comment]
https://pastebin.com/cnq2X87b
m1 air macOS 12 beta6崩溃报告

**Comment by zxdong262** [comment]
@devourbots 请问这是打开就崩溃吗？
