### ISSUE TITLE
切屏卡顿

### ISSUE THREAD

**Issue by lemon9921010** [electerm/electerm#2243]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1. 连上服务器
2. 切换到别的窗口
3. 切换回来要卡主好几秒
4.

**Comment by zxdong262** [comment]
方便提供其他的情况吗，操作系统，软件版本，硬件

**Comment by lemon9921010** [comment]
![Uploading image.png…]()
win7， electerm 1.16.5

**Comment by lemon9921010** [comment]
运维老需要切换到浏览器查资料啥的， 每次回来卡个5-8s， 很稳定的现象

**Comment by lemon9921010** [comment]
最新本部感觉好多了， 感谢大佬
