### ISSUE TITLE
MacBook ARM（M1）使用报告

### ISSUE THREAD

**Issue by sjlleo** [electerm/electerm#2251]
等了好久，终于来了原生ARM版本的electerm。

在ARM版本的`Big Sur`上偶见启动时闪退，因为频率非常低，而且第二次启动必定可以起来，所以当时也未提取`log`，基本不影响使用，在升级最新版Montery（Beta）系统后再也未能复现此闪退，看起来是彻底正常了。

electerm各功能都正常，启动后再也未见任何故障，总体来说此次编译的ARM Test分支版本，还是很稳定的。

在Intel的MacBook（Big Sur）上未发现任何稳定性问题。

**Comment by zxdong262** [comment]
感谢反馈 @sjlleo
