### ISSUE TITLE
[建议]连接的时候增加通过ssh隧道连接

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2252]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.16.5
## Operating system(linux, macos, or windows7/8/10?):
macos
## Expected Behavior

建议增加个通过ssh隧道连接，有时候连接服务器的时候可能需要通过跳板机器进行连接，一般都是通过ssh隧道连接。
## Steps to Reproduce

1.
2.
3.
4.

**Comment by youyanghuang** [comment]
+1

**Comment by ma-x-x** [comment]
+1

**Comment by zxdong262** [comment]
最新版已经加入ssh tunnel支持

**Comment by ma-x-x** [comment]
您好，我已经收到您的来件，我会尽快处理的。祝您工作生活愉快。                                              ——BastogneYu
