### ISSUE TITLE
win10更新后出现菜单栏和标题栏

### ISSUE THREAD

**Issue by yuanhu7069** [electerm/electerm#2253]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

 Electerm version: 1.16.11

Operating system: win10

Expected Behavior：
之前正常使用，在win10更新后，顶部就出现了白色的标题栏和菜单栏。

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以看看设置里`使用系统标题栏`是不是打开了吗

**Comment by yuanhu7069** [comment]
> 可以看看设置里`使用系统标题栏`是不是打开了吗

已解决，是这个问题，非常感谢
