### ISSUE TITLE
中文输入法下，不能输入中文或者按shift的英文

### ISSUE THREAD

**Issue by laowang815** [electerm/electerm#2261]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.
2.
3.
4.

**Comment by wxpsjhhd** [comment]
亲测，QQ输入法，小狼毫输入法可以输入中文，百度输入法也不能输入中文

**Comment by zxdong262** [comment]
目前这个只能由输入法自己提供支持
