### ISSUE TITLE
sftp上传文件时会弹框报错，electerm/resources/app.asar/assets/js/electerm.js有问题

### ISSUE THREAD

**Issue by duktig666** [electerm/electerm#2262]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.16.11

## Operating system(linux, macos, or windows7/8/10?):
win10

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

## Context (Environment)

Does not affect use, but looks very unfriendly.

## Detailed Description

When uploading files through SFTP or refreshing folders on the remote server, an error message is displayed.  

```
Error: Failure
    at file:///D:/software/electerm/resources/app.asar/assets/js/electerm.js?1.16.11:2:1498498
    at Object.resolve (file:///D:/software/electerm/resources/app.asar/assets/js/electerm.js?1.16.11:2:1429208)
    at Worker.<anonymous>(file:///D:/software/electerm/resources/app.asar/assets/js/electerm.js?1.16.11:2:1430137)

```
![image](https://user-images.githubusercontent.com/53132746/135701318-4eb13560-754e-4b3d-99df-6166cd48e92c.png)

## Suggestions?

It is recommended to fix this problem to ensure user friendly use.

**Comment by zxdong262** [comment]
merge to-----> #2270
