### ISSUE TITLE
openssh 8.8P1连接不上了

### ISSUE THREAD

**Issue by 68cs** [electerm/electerm#2268]
![Xnip2021-10-04_01-02-53](https://user-images.githubusercontent.com/25496213/135764085-e0e0a475-b459-43b7-a181-e2530aebebe4.png)

**Comment by zxdong262** [comment]
openssh之前的版本就可以吗？

**Comment by 68cs** [comment]
之前的版本一直正常

**Comment by zxdong262** [comment]
`/etc/ssh/sshd_config`看看`PasswordAuthentication `是不是`yes`?

**Comment by 68cs** [comment]
![image](https://user-images.githubusercontent.com/25496213/135973046-560f249a-fc18-4fc7-b457-734f77ae7fc4.png)

**Comment by zxdong262** [comment]
去掉`#`保存重启sshd服务试试？

**Comment by 68cs** [comment]
![image](https://user-images.githubusercontent.com/25496213/135974119-a4e1a332-330d-4e26-a1e5-75d35177e48f.png)
保存重启后还是“connect ECONNREFUSED 192.168.2.2:22”

**Comment by zxdong262** [comment]
`ChallengeResponseAuthentication yes`也打开试试

**Comment by zxdong262** [comment]
另外，你直接用系统终端的命令行能连上吗

**Comment by 68cs** [comment]
> `ChallengeResponseAuthentication yes`也可以打开实用

还是拒绝连接，另外用Mac自带的终端也是连接不上

**Comment by 68cs** [comment]
![image](https://user-images.githubusercontent.com/25496213/135975762-b0fcc76a-8b7a-4ca7-9849-619179792f7d.png)
刷完这个固件后才发现这个问题的

**Comment by zxdong262** [comment]
我试了下mac的8.8p1,改了下配置就连上了，用ed25519 private key登录没改配置也是可以登录的, 还可以参考这个https://ttys3.dev/post/openssh-8-8-p1-no-matching-host-key-type-found-their-offer-ssh-rsa/
