### ISSUE TITLE
希望支持隧道功能

### ISSUE THREAD

**Issue by wangpre** [electerm/electerm#2278]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Operating system(linux, macos, or windows7/8/10?):
macos

## Expected Behavior

隧道的应用场景太多了，跳板机，本地端口映射
希望下个版本能支持该功能

## Steps to Reproduce

1.
2.
3.
4.

**Comment by LiuChiennan** [comment]
+1，有隧道就棒了

**Comment by LiuChiennan** [comment]
不过隧道倒是直接能通过命令行敲，只是没那么方便罢了，辛苦作者，以后可以把随倒功能考虑一下，确实用途蛮广的

**Comment by zxdong262** [comment]
最新版已经加入ssh tunnel支持
