### ISSUE TITLE
作为网络工程师，希望能添加Serial和Telnet功能

### ISSUE THREAD

**Issue by Arise2** [electerm/electerm#2279]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.
2.
3.
4.

**Comment by etanman** [comment]
不明白为什么要去掉Serial，Serial和Telnet的确是工作中经常用到的功能。

**Comment by zxdong262** [comment]
> 不明白为什么要去掉Serial，Serial和Telnet的确是工作中经常用到的功能。

从某一个版本开始，构建通不过

**Comment by etanman** [comment]
> 

感谢作者的回复，您的意思是不符合开源构建是吗？

**Comment by etanman** [comment]
> > 不明白为什么要去掉Serial，Serial和Telnet的确是工作中经常用到的功能。
> 
> 从某一个版本开始，构建通不过

感谢作者的回复，您的意思是不符合开源构建是吗？

**Comment by etanman** [comment]
> > 不明白为什么要去掉Serial，Serial和Telnet的确是工作中经常用到的功能。
> 
> 从某一个版本开始，构建通不过

感谢作者的回复，您的意思是不符合开源构建是吗？是不是调用了系统内部的东西？以后还有可能加上吗？

**Comment by zxdong262** [comment]
> > > 不明白为什么要去掉Serial，Serial和Telnet的确是工作中经常用到的功能。
> > 
> > 
> > 从某一个版本开始，构建通不过
> 
> 感谢作者的回复，您的意思是不符合开源构建是吗？是不是调用了系统内部的东西？以后还有可能加上吗？
依赖于一个叫做serialport的包，在早期版本是可用的，之后就有问题了，会导致程序崩溃，我也没有能够解决。

**Comment by zxdong262** [comment]
下个版本支持serialport

**Comment by Arise2** [comment]
感谢回复，真是太好了！！！

**Comment by Arise2** [comment]
> 下个版本支持serialport

感谢回复，真是太好了！！！
