### ISSUE TITLE
强烈建议 sftp远程端ui(右边)修改并默认平铺布局 列表布局不合适

### ISSUE THREAD

**Issue by hummingsoul** [electerm/electerm#2287]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.
2.
3.
4.

**Comment by blankhang** [comment]
反对 列表才是方便查看的

**Comment by hummingsoul** [comment]
列表布局没问题 问题是这个列表布局做的没有一点留白的空间 一行一行的格子从最左边占到最右边 两边拖文件时 不注意就拉某个文件夹里了 在根目录找半天找不到文件
