### ISSUE TITLE
SFTP cannot connect normally and reports an error

### ISSUE THREAD

**Issue by MC-Nirvana** [electerm/electerm#2296]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
1.16.21
## Operating system(linux, macos, or windows7/8/10?):
Windows10 21H1
## Expected Behavior

SFTP normal connection
## Can you reproduce the same behavior in other terminal:

No
## Current Behavior

SFTP cannot connect normally and an error is reported. The content is as follows:
Error: Unable to start subsystem: sftp
    at file:///C:/Program%20Files/electerm/resources/app.asar/assets/js/electerm.js?1.16.21:2:1416520
    at Object.resolve (file:///C:/Program%20Files/electerm/resources/app.asar/assets/js/electerm.js?1.16.21:2:1346858)
    at Worker.<anonymous> (file:///C:/Program%20Files/electerm/resources/app.asar/assets/js/electerm.js?1.16.21:2:1347787)
## Steps to Reproduce

1.Create and connect to SSH
2.SSH is normal after connection, but SFTP cannot be connected and an error is reported
3.
4.

## Context (Environment)

Unable to manage files on remote server
## Detailed Description

It is recommended to fix this error as soon as possible

**Comment by zxdong262** [comment]
Is it situation like this: https://github.com/mscdex/ssh2/issues/115

**Comment by MC-Nirvana** [comment]
yes
