### ISSUE TITLE
1.1.7.3-arm64 Startup error

### ISSUE THREAD

**Issue by bryan31** [electerm/electerm#2297]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version: 
1.17.3-arm64

## Operating system(linux, macos, or windows7/8/10?): 
macos m1
 
## Expected Behavior

can't open it，if I open it again, still get this error
![image](https://user-images.githubusercontent.com/924838/139801586-6ec2e4c8-5ea9-4e9b-9149-fb5761244de2.png)

![image](https://user-images.githubusercontent.com/924838/139801824-f5a99306-4d9b-4dc9-9114-7323ee156fc3.png)

## Can you reproduce the same behavior in other terminal:

no

## Current Behavior

Successful open

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
ARM版本仅供测试，目前我没有设备，无法验证，如果不行可以用macx64版本的
