### ISSUE TITLE
上传文件后文件名变了 

### ISSUE THREAD

**Issue by blankhang** [electerm/electerm#2304]
## Electerm version:
 snap安装 v1.17.3  界面设置为了中文

## Operating system(linux, macos, or windows7/8/10?):
ubuntu 20.04 lts 英文系统

## Expected Behavior
上传文件后 右边的文件名跟 本机应该是完全一致才对吧 除非是有相同文件名 提示是否覆盖

## Can you reproduce the same behavior in other terminal:
Remmina 上上传文件正常

## Current Behavior
上传jar-standalone-1.0.2.jar 到服务器上到变成了 jar-standalone-1.0.2(rename-XXXX一对随机英文字符串).jar

## Steps to Reproduce
上传到一个文件到服务器空目录后 服务器上的文件名跟 本机不一致了。。。
本机文件名是 
jar-standalone-1.0.2.jar

上传到服务器上到变成了 
jar-standalone-1.0.2(rename-XXXX一对随机英文字符串).jar

## Suggestions?
上传文件时能否在底部实时显示上传任务进度列表  类似 xshell 中的 xftp中那样 而不是要鼠标放上才浮动显示？

**Comment by zxdong262** [comment]
每次都能复现吗？可以把两边的路径发一下吗

**Comment by blankhang** [comment]
> 每次都能复现吗？可以把两边的路径发一下吗

是的
我试过所有 路径 都 有这个问题

是因为我两边路径一样？
/data/docker/ /data/docker/
/data/docker/app/  /data/docker/app

**Comment by zxdong262** [comment]
> > 每次都能复现吗？可以把两边的路径发一下吗
> 
> 是的 我试过所有 路径 都 有这个问题
> 
> 是因为我两边路径一样？ /data/docker/ /data/docker/ /data/docker/app/ /data/docker/app/
> 
> 还有个小问题 打开的浏览器是默认的火狐浏览器 而不是我系统默认的 edge/chrome
> 
> 希望能有像Xftp的 远程 编辑文本功能。。。在本地用指定文本编辑器打开 编辑远程服务器中的文本

  可以试试右键`编辑...`菜单

**Comment by blankhang** [comment]
可以试试右键编辑...菜单 跟我说的 体验差距还蛮大的。。。
建议你试试 Xftp的 右键远程编辑
除了第一次需要指定本机编辑器之外  后面再 右键就能直接用之前配置的编辑器打开  就像在本地操作一样 在编辑器中保存 会触发 Xftp覆盖更新文件操作

**Comment by zxdong262** [comment]
> > 每次都能复现吗？可以把两边的路径发一下吗
> 
> 是的 我试过所有 路径 都 有这个问题
> 
> 是因为我两边路径一样？ /data/docker/ /data/docker/ /data/docker/app/ /data/docker/app/
> 
> 还有个小问题 打开的浏览器是默认的火狐浏览器 而不是我系统默认的 edge/chrome
> 
> 希望能有像Xftp的 远程 编辑文本功能。。。在本地用指定文本编辑器打开 编辑远程服务器中的文本

确实是路径一样会有这个bug
