### ISSUE TITLE
操作十分卡顿,延迟严重,影响使用

### ISSUE THREAD

**Issue by ryzencool** [electerm/electerm#2305]
系统 mac os
![image](https://user-images.githubusercontent.com/12694592/141065886-e894a6f8-6853-4cf3-8a8c-b025f2e56cc2.png)
软件版本: 1.17.3

**Comment by chuntsky** [comment]
我在Windows 10，11 环境使用下，多开几个标签页就会出现卡顿的情况，不知道什么原因。
这个情况有一段时间了，升级过好几个版本，没有改变。
![image](https://user-images.githubusercontent.com/22720116/141223296-89f282eb-8cb1-4676-ae6e-bc0e065a2667.png)

**Comment by zxdong262** [comment]
确实是性能不行（源于开发者水平和时间有限）

**Comment by AnShengqiang** [comment]
> 确实是性能不行（源于开发者水平和时间有限）

要不下个版本多关注一下性能？确实用起来有些卡顿，包括启动速度和使用中速度

**Comment by lidano** [comment]
同上，建议多关注下性能。 mac上跑几个小时后，就不是流畅不流畅的事儿了，标签切换都成问题。

**Comment by chuntsky** [comment]
使用 electerm  的人应该不少的，考虑把捐助放出来？  爱发电  ！

**Comment by etanman** [comment]
改个字号大小，反应都滞后。

**Comment by etanman** [comment]
> 确实是性能不行（源于开发者水平和时间有限）

你行的，相信你一定能够解决这个问题。
非常崇拜你，你是代码界的费翔，混血面孔很酷，很帅。

**Comment by leizhu900516** [comment]
mac 下开三个标签，切换起来，就很卡顿了。

**Comment by shenzhuangzhi1** [comment]
加油哦！
