### ISSUE TITLE
Mac版本窗口退出按键部分有个小问题

### ISSUE THREAD

**Issue by JackLiu1214** [electerm/electerm#2307]
![image](https://user-images.githubusercontent.com/86704136/141437544-3c25c0ea-baa4-47ad-8c79-56a174ba5578.png)
左右两侧都会有按钮出现，左侧的按钮应该是Mac的，但是默认是隐藏的，右侧的是其他系统的，按理说在Mac上还是不出现比较舒服，希望可以修复！

**Comment by zxdong262** [comment]
设置里选择使用系统标题栏可以解决
