### ISSUE TITLE
electerm is running slow

### ISSUE THREAD

**Issue by saodis** [electerm/electerm#2308]
Electerm version: v1.17.16

OS: windows 10 Pro, 21H1, 19043.1320

electerm is running slow

**Comment by zxdong262** [comment]
Do have performance issue, especially in PC without powerful hardware

**Comment by jpgkudo** [comment]
No, when the hardware performance is very strong, it still runs slowly, which has affected the normal use!
Under the same hardware conditions, electerm is much slower than other SSH clients (such as xshell and SecureCRT).
It is recommended to solve the performance problem first.

**Comment by tan-wei** [comment]
Indeed. But why the issue is closed? @saodis

**Comment by nlzq** [comment]
@tan-wei https://github.com/kingToolbox/WindTerm
