### ISSUE TITLE
是否可以支持SCP功能。

### ISSUE THREAD

**Issue by samshum** [electerm/electerm#2309]
需求场景：使用OpenWRT系统时需要做文件传输时，只能使用SCP功能，SFTP用不了。
一般在Windows里面使用WinScp解决，但在MACOS里面用不了，只能使用Termial，用SSH时还得开另外一个窗口。

## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
方便具体描述一下吗

**Comment by zxdong262** [comment]
只能命令行了
