### ISSUE TITLE
Connection stuck

### ISSUE THREAD

**Issue by zundaren** [electerm/electerm#2312]
![image](https://user-images.githubusercontent.com/44863479/143155057-78fb67f2-39d5-4315-b274-e84ea861ffa3.png)

I first connected to the server to download the log, downloaded it 3 times, and then returned to the ssh stuck,
window11 21H2 22000.318

**Comment by zundaren** [comment]
I used easyconnect locally to log in to vpn

**Comment by zxdong262** [comment]
Can you try latest release?
