### ISSUE TITLE
rz上传文件没反应

### ISSUE THREAD

**Issue by James601232** [electerm/electerm#2316]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
![image](https://user-images.githubusercontent.com/19258506/143978255-8e48b8e4-c60c-4d07-841b-bcbcfef675b9.png)

## Operating system(linux, macos, or windows7/8/10?):
macos
## Steps to Reproduce

1.  
![image](https://user-images.githubusercontent.com/19258506/143978206-15b59977-ed1f-4c8f-b4de-797a843385c2.png)

2.
3.
4.

**Comment by zxdong262** [comment]
应该是无法更新上传进度，实际还在上传，就一直等待上传完毕就好了

**Comment by zxdong262** [comment]
哦不是，还真不好使了

**Comment by lonnywong** [comment]
@James601232 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
