### ISSUE TITLE
ERROR with connecting with server

### ISSUE THREAD

**Issue by jahidhasanlinix** [electerm/electerm#2317]
So I was using electerm to connect with my server, I added my server information correctly but its showing an error line below:

```
"error
getaddrinfo ENOTFOUND server_name"
```

**Comment by zxdong262** [comment]
How is the result when `ping your_domain_name_or_ip`?
Anyway, seems just dns issue, not related to electerm, you may try resstart your computer or clear dns cache or try another network.

**Comment by jahidhasanlinix** [comment]
It works perfectly on my ubuntu terminal when I do ssh, at first it worked but recently it stopped working and always giving that error

**Comment by Troymayrain** [comment]
![image](https://user-images.githubusercontent.com/12369731/146663943-4c2ea9f5-b1e6-4d68-8d65-aaa6a62e01d5.png)
![image](https://user-images.githubusercontent.com/12369731/146663964-a9f5800d-9a8a-4a21-a5ec-22c1d676746d.png)
连接阿里云ECS的时候报错了！

**Comment by Troymayrain** [comment]
@zxdong262

**Comment by hope250** [comment]
> ![image](https://user-images.githubusercontent.com/12369731/146663943-4c2ea9f5-b1e6-4d68-8d65-aaa6a62e01d5.png) ![image](https://user-images.githubusercontent.com/12369731/146663964-a9f5800d-9a8a-4a21-a5ec-22c1d676746d.png) 连接阿里云ECS的时候报错了！

可以试一试 `telnet 47.96.69.5 22` 看端口通不通，是端口没开，还是防火墙拦截了

**Comment by Troymayrain** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Troymayrain** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
