### ISSUE TITLE
连续新建书签并且保存时同一个目录重复出现

### ISSUE THREAD

**Issue by gengyang1986** [electerm/electerm#2319]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
1.17.16
## Operating system(linux, macos, or windows7/8/10?):
macos arm
## Expected Behavior

同一书签重复显示
## Can you reproduce the same behavior in other terminal:

No
## Current Behavior

连续新建多个书签 显示重复
## Possible Solution

重启之后显示正常 可能是保存数据后显示错误

## Detailed Description
参考截图 新建一个LAN 目录下面有三台机器 保存之后出现了三个LAN 重启之后显示正常
<img width="623" alt="截屏2021-12-02 下午6 08 55" src="https://user-images.githubusercontent.com/4454822/144403393-a85ef3d6-b2d0-4846-b4e7-4a3ade540c4f.png">

**Comment by zxdong262** [comment]
可以详细描述复现的步骤吗，我试了下没有复现
