### ISSUE TITLE
How to access the temrinal (Question)

### ISSUE THREAD

**Issue by ayoub-tl** [electerm/electerm#2323]
this is a question:
how can i access the web terminal, i lunched using npm start then I tried to access the terminal through the web, it only show this image
![image](https://user-images.githubusercontent.com/68382823/144726668-68b098d5-c477-4658-bb56-b2d962cf6796.png)
I think the wiki is little short, I didn't find any helpful information about how to connect , the URL , if I can change the port on the web, how to enable feauters like x11, and other things

Thank you

**Comment by zxdong262** [comment]
do not support web, can only run in electron

**Comment by ayoub-tl** [comment]
ok thanks
