### ISSUE TITLE
remote linux ssh server dev start issue

### ISSUE THREAD

**Issue by perfectwebtech** [electerm/electerm#2325]
when i start 

npm start with env settings in linux remote ssh client  with ip base i trying open 

### network  error during development start version 

ws://192.168.100.245:5570/ws

connection fetched to this resources is not secure 

############  below console error: 

webpack-dev-server] Disconnected! index.js:519
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools react-dom.development.js:26274:19
[HMR] Waiting for update signal from WDS... log.js:24
Uncaught (in promise) TypeError: window.pre is undefined
    load basic.jsx:34
    jsx basic.jsx:57
    Webpack 3
basic.jsx:34:16
GEThttp://192.168.100.245:5570/favicon.ico
[HTTP/1.1 404 Not Found 24ms]

[webpack-dev-server] Hot Module Replacement enabled. index.js:519
[webpack-dev-server] Live Reloading enabled. index.js:519

​

**Comment by zxdong262** [comment]
Can only run in electron

**Comment by perfectwebtech** [comment]
from linux machine in browser can not test ? 

development version ? 

[HMR] Waiting for update signal from WDS... [log.js:24](webpack://Et/node_modules/webpack/hot/log.js)
Uncaught (in promise) TypeError: window.pre is undefined
    load basic.jsx:34
    jsx basic.jsx:57
    Webpack 3
[basic.jsx:34:16](webpack://Et/src/client/entry/basic.jsx)
[webpack-dev-server] Hot Module Replacement enabled. [index.js:551](webpack://Et/node_modules/webpack-dev-server/client/modules/logger/index.js)
[webpack-dev-server] Live Reloading enabled. [index.js:551](webpack://Et/node_modules/webpack-dev-server/client/modules/logger/index.js)
TypeError: e is undefined
[in-place-play.js:1:2088](moz-extension://b00f2431-16fe-5f4f-81f1-9a37d147f010/javascripts/in-place-play.js)

​
