### ISSUE TITLE
Settings sync encryption 

### ISSUE THREAD

**Issue by onikienko** [electerm/electerm#2326]
Looks like the app uses token for encryption. And you have to use the same token in each Electerm instance to have access to encrypted settings. At least for Github. 

The issue with this approach, that when the token will expire you will lose your saved data. 

Maybe will be better to use some passphrase here instead of the token?

Thanks for the nice useful app!

**Comment by yanickxia** [comment]
@zxdong262  token maybe expire after sometime，he want encrypt by passphrase, token just for auth to github/gitee。

**Comment by onikienko** [comment]
@yanickxia Exactly

**Comment by zxdong262** [comment]
Now support standalone password
