### ISSUE TITLE
双击顶部标题栏时，建议增加最大化与正常大小切换功能

### ISSUE THREAD

**Issue by qtvbwfn** [electerm/electerm#2327]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
V1.17.19
## Expected Behavior

双击顶部标题栏时，增加最大化与正常大小切换功能，具体可以参考windows上软件，比如浏览器、微信、文件管理器等

## Steps to Reproduce

1.无
2.
3.
4.

**Comment by zxdong262** [comment]
可以打开使用系统标题栏，设置里
