### ISSUE TITLE
通过跳板机登录出现错误

### ISSUE THREAD

**Issue by Soulballad** [electerm/electerm#2328]
## Please check known issues first
![image](https://user-images.githubusercontent.com/19262272/145166174-05dd6fd3-f286-4597-bfb2-130377da61c8.png)

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.新建ssh
2.连接ssh
3.出现错误
4.

**Comment by zxdong262** [comment]
连接普通的ssh就没有这个错误是吗？另外在选项里试试关闭sftp看看行不行

**Comment by Soulballad** [comment]
> 连接普通的ssh就没有这个错误是吗？另外在选项里试试关闭sftp看看行不行

由于都是云服务器普通ssh没有试，不过关闭sftp之后没有出现错误了
