### ISSUE TITLE
同步到github提示token invalid但同样的token另外一台电脑没问题

### ISSUE THREAD

**Issue by willie91** [electerm/electerm#2329]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
v1.17.19
## Operating system(linux, macos, or windows7/8/10?):
windows11
## Expected Behavior

token invalid
## Can you reproduce the same behavior in other terminal:

不能
## Current Behavior

很奇怪，我这同步到github的token在另外一台电脑没问题
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
检查一下是不是有遗漏字母或者多余空格之类的，或者删除所有配置
