### ISSUE TITLE
中文字符重复两遍输入

### ISSUE THREAD

**Issue by wangduanduan** [electerm/electerm#2332]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
```
v1.17.19
```

## Operating system(linux, macos, or windows7/8/10?):
linux deepin

## Expected Behavior

输入中文字符，回车确认后，字符在终端上出现两次。输入法是搜狗输入法。

例如输入：你好啊
终端上看到：你好啊你好啊 

## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?

![image](https://user-images.githubusercontent.com/16631306/145964625-84a90d99-5e0e-4222-88ce-d9f88038e2b5.png)

**Comment by zxdong262** [comment]
可以试试其他输入法是不是也这样吗

**Comment by wangduanduan** [comment]
重新安装了一个输入法，中文输入也是重复。英文正常。

我怀疑是不是和我刚升级了deepin的系统有关，升级系统之前，中文输入都是正常的。

**Comment by wangduanduan** [comment]
但是除了electerm, 其他应用，中文输入都是正常的，没有重复

**Comment by frankwu5099** [comment]
遇到同样问题，把输入法系统从ibus换成fctix就没问题了

**Comment by hope250** [comment]
中文输入法，重复上屏问题，同样。
Deepin 20.3
搜狗输入法2.4.0.3469
fcitx version: 4.2.9.5

**Comment by wangduanduan** [comment]
在tabby上输入中文字符，都是正常的。只能临时换tabby用了。

https://github.com/Eugeny/tabby

**Comment by wangduanduan** [comment]
deepin的默认输入法就是fcitx吧

**Comment by hope250** [comment]
> fcitx

是的，据说全新安装新版的话是fcitx5，升级的一直都是fcitx4
