### ISSUE TITLE
感觉很卡，有解决办法么？

### ISSUE THREAD

**Issue by nlzq** [electerm/electerm#2338]
用的最新版 electerm，系统是 windows 10

运行一会儿，多开几个标签，就卡的不能用，什么原因？

**Comment by jiayouzl** [comment]
macOS m1最新系统也卡卡的，我杭州电信，服务器是阿里云杭州机房100M宽带的服务器，不应该啊，在终端打字很慢。

**Comment by nlzq** [comment]
> macOS m1最新系统也卡卡的，我杭州电信，服务器是阿里云杭州机房100M宽带的服务器，不应该啊，在终端打字很慢。

我这是内网用，xshell 不让用，secureCRT 太丑了，这会用 windows 自带的😂

**Comment by zxdong262** [comment]
请问硬件什么情况？@nlzq

**Comment by nlzq** [comment]
@zxdong262 
cpu: i5-8250U
内存：16GB
硬盘：500GB RC10 固态 + 1TB 机械

**Comment by jiayouzl** [comment]
> 请问硬件什么情况？@nlzq

我Windows配置i9 9900K 64G ddr4 3600内存 Rtx3080这套我用来机器学期的台式机一样卡！MacBook Pro M1也卡，跟配置一点关系都没。

**Comment by nlzq** [comment]
@zxdong262 看了下历史 issue，挺多人说卡的，先优化优化呗，应该不是机器问题。

**Comment by nlzq** [comment]
@zxdong262 考虑一下这样，新特性就先不做了，性能先优化，就目前这样的功能，很够用了。

**Comment by linuxyn** [comment]
确实很卡，功能方面其实够用了，就是体验感不好，特别卡。

**Comment by ytqiao3** [comment]
真的很卡，添加书签保存3秒才有反应提示保存成功

**Comment by leonunix** [comment]
个人觉得。应该是书签方面有问题。因为每次打开书签列表都可以卡上几秒。保存更是需要1分钟左右。

**Comment by chenqikai** [comment]
➕1️⃣  确实很卡

**Comment by tonyttz** [comment]
这个工具界面及功能方面确实非常完美了, 但就是这个标签卡的问题, 简直到了没法用的地卡. 
硬件: mbp 2020款

**Comment by lzw5399** [comment]
确实有点卡，尤其tab一多

**Comment by shenzhuangzhi1** [comment]
应该是渲染速度的问题吧？

**Comment by tlm629** [comment]
我感觉得卡主要集中在切换tab的时候
MacBook Pro (15-inch, 2017)
3.1 GHz 四核Intel Core i7
16 GB 2133 MHz LPDDR3
11.6.1

**Comment by porro-tian** [comment]
卡主要集中在切换tab的时候
MacBook Pro (16-inch, 2019)
2.6 GHz 六核Intel Core i7
16 GB 2667 MHz DDR4
11.1 (20C69)

**Comment by zxdong262** [comment]
@tlm629 @porro-tian @nlzq @lzw5399 请问最新吧有改善吗
