### ISSUE TITLE
sftp无法显示 “.”符号开头的文件

### ISSUE THREAD

**Issue by JackiePenghe** [electerm/electerm#2340]
MAC系统上没有找到关于sftp文件浏览选项的设置，无法显示出“.”符号开头的文件。
希望能加入一个配置选项，使sftp也能看到“.”符号开头的文件

**Comment by zxdong262** [comment]
<img width="786" alt="Screen Shot 2021-12-30 at 10 16 30 AM" src="https://user-images.githubusercontent.com/1641949/147716395-7694ae28-140c-4c51-8ab0-703659e99477.png">
点一下那个眼睛试试
