### ISSUE TITLE
最新版本 修改默认UI主题 不生效。

### ISSUE THREAD

**Issue by AlfredMiss** [electerm/electerm#2344]
https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm

按照以上主题配色 修改最新版本的ui 配色参数 不生效。

**Comment by zxdong262** [comment]
确实有点问题

**Comment by zxdong262** [comment]
你试试别的，我试了是生效的，大概颜色接近默认的看起来像是没有生效

**Comment by WLaoDuo** [comment]
我修改了主题是生效了的，你可能是选了颜色差不多的，不容易看出来
