### ISSUE TITLE
tab移动不了

### ISSUE THREAD

**Issue by lzw5399** [electerm/electerm#2347]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号):
v1.17.21

## Operating system(linux, macos, or windows7/8/10?)(操作系统):
macos

见图
![untitled](https://user-images.githubusercontent.com/45249999/148889635-ed80d5c0-7aef-4fce-827a-22c807cd558c.gif)

多tab一些时候想整理移动位置还是蛮不方便的

**Comment by darrenliuwei** [comment]
windows10也有一点点小问题，windows10只能往前移动，但是却不能往后移动，版本是v1.17.21

**Comment by zxdong262** [comment]
注意拖动时候有个虚线，虚线的位置决定放置位置
