### ISSUE TITLE
命令行中输入下划线时 不会正确显示 _

### ISSUE THREAD

**Issue by blankhang** [electerm/electerm#2348]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号):  
1.17.21

## Operating system(linux, macos, or windows7/8/10?)(操作系统):  
Ubuntu 20.04.3 LTS

## Expected Behavior(期望的行为)
  
输入框应该能正确渲染显示 _ 下划线

## Can you reproduce the same behavior in other terminal(是否能在其他同类软件中复现):
  
其他同类软件无此问题

## Current Behavior(当前行为)
  
![image](https://user-images.githubusercontent.com/3981276/148889527-bead9b1d-e104-4fc3-aff6-77d2a55bd9d1.png)
只要输入 _ 都会变成空格的效果

## Steps to Reproduce(复现步骤)

1. 新建带 _ 下划线的文件夹
2. 只要输入 _

**Comment by zxdong262** [comment]
可以设置里换个字体试试吗？

**Comment by blankhang** [comment]
找到问题原因了 应该是因为软件默认配置的字体 Ubuntu 中都没有 退回到了系统默认字体DejaVu导致的
建议添加 Ubuntu Mono 字体
