### ISSUE TITLE
服务器文件时间显示异常

### ISSUE THREAD

**Issue by gadfly3173** [electerm/electerm#2350]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

![image](https://user-images.githubusercontent.com/28685179/149101054-62f4e637-80d8-4a12-b2cd-2dd430260cf5.png)

## Expected Behavior(期望的行为)

正确的时间显示

## Can you reproduce the same behavior in other terminal(是否能在其他同类软件中复现):

/

## Current Behavior(当前行为)

奇怪的时间

## Steps to Reproduce(复现步骤)

1.
2.
3.
4.

## Context (Environment)(环境)

服务器centos7 替换文件

**Comment by zxdong262** [comment]
请问本地是什么系统？

**Comment by gadfly3173** [comment]
这么看的话本地和远程也标反了？

**Comment by gadfly3173** [comment]
![image](https://user-images.githubusercontent.com/28685179/149502702-782f7324-f55b-4a3d-bc2f-b28b02c2126f.png)
![image](https://user-images.githubusercontent.com/28685179/149502807-b518185b-f457-4c03-baef-6463749b2c5c.png)
