### ISSUE TITLE
sz 下载文件默认txt格式问题

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2355]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号):
v1.17.21
## Operating system(linux, macos, or windows7/8/10?)(操作系统):
macos
## Steps to Reproduce(复现步骤)

1.
2.
3.
4.

## Detailed Description(详细描述)

使用sz下载文件的时候，如果文件没有格式后缀，保存的时候默认是.txt，

## Suggestions?(建议)

建议去掉默认的.txt，因为每次保存都要手动去掉比较麻烦。

**Comment by zxdong262** [comment]
这个electron的行为，目前还没发现可以控制的地方

**Comment by lonnywong** [comment]
@bb7788 可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz
