### ISSUE TITLE
[bug]托盘tray展示问题

### ISSUE THREAD

**Issue by rexlevin** [electerm/electerm#2356]
## Electerm version(版本号):

从有tray的版本到目前1.17.26的版本都有

## Operating system(linux, macos, or windows7/8/10?)(操作系统):

ubuntu20.04 unity

## Expected Behavior(期望的行为)

先读取用户对tray是否展示的配置，然后再决定是否展示tray

## Current Behavior(当前行为)

目前是启动应用时，直接就初始化并展示tray，然后再读取用户配置，然后再展示/不展示tray

## Possible Solution(可能的解决办法)

init-app时不要直接initTray(menu)，先读取用户配置，根据用户配置来决定是否initTray(menu)

**Comment by zxdong262** [comment]
已经去掉
