### ISSUE TITLE
多个标签页情况下，切换标签页会导致CPU飙升导致页面卡顿

### ISSUE THREAD

**Issue by r0ckysec** [electerm/electerm#2357]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号):
v1.17.26

## Operating system(linux, macos, or windows7/8/10?)(操作系统):
Mac M1系统

## Possible Solution(可能的解决办法)

优化页面性能

## Steps to Reproduce(复现步骤)

1.多个标签页的情况下，切换标签页

## Detailed Description(详细描述)

多个标签页的情况下，切换标签页，会导致CPU飙升损耗性能，配置低的话会导致卡顿

## Suggestions?(建议)

功能能不能先暂时放放，把页面优化一下，至少体验感好，用的才舒服

**Comment by zxdong262** [comment]
请问你用的是mac-arm版本还是macx64版本?

**Comment by r0ckysec** [comment]
mac-arm的



---- 回复的原邮件 ----
| 发件人 | ZHAO ***@***.***> |
| 日期 | 2022年01月22日 08:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [electerm/electerm] 多个标签页情况下，切换标签页会导致CPU飙升导致页面卡顿 (Issue #2357) |

请问你用的是mac-arm版本还是macx64版本?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zxdong262** [comment]
请问你有多少个书签，多个标签是多少个，如果是多个本地终端，切换也会卡吗？

**Comment by r0ckysec** [comment]
就两个标签相互切换，CPU会突然暴增到 40-50%，我这台是新款性能好点所以不卡顿，原来那台16g内存的 卡顿非常明显，体验感大幅度下降，感觉是前端UI性能没优化好，我看issues里好多人提了，好像还是没解决。
<img width="769" alt="截屏2022-01-23 20 16 30" src="https://user-images.githubusercontent.com/44518337/150677985-c114d6dc-c3e6-492f-8cf0-27a5555da71c.png">

**Comment by makeloffve** [comment]
@zxdong262 这个性能问题如果没时间解决，建议开发一个保留当前打开窗口工作区的功能，重启electerm之后还能恢复之前的窗口，我觉得也能接受

**Comment by zxdong262** [comment]
@makeloffve 我在mbp（不是m1）里试切换tab是没有变化的，你有其他环境试验切换tab也是会卡吗，另外想知道你有多少个书签？

**Comment by zxdong262** [comment]
> @zxdong262 这个性能问题如果没时间解决，建议开发一个保留当前打开窗口工作区的功能，重启electerm之后还能恢复之前的窗口，我觉得也能接受

复现了，大概开了10个tab就能cpu占用飙升了

**Comment by Refuel-ZL** [comment]
我的也是（配置和版本一致）， 我书签管理剧卡: 大概有四五个分组，共有100左右的ssh信息，每次编辑、保存、删除等都假死状，等待数秒才可以，尤其是删除其中一个ssh 信息，确定框都得等待数秒。希望大佬再优化优化 @zxdong262

**Comment by makeloffve** [comment]
> 

@zxdong262 大佬新年好啊

我的环境信息：

cpu：2*2*Xeon Gold 6146 @ 3.20GHz
memory: 16G
os: windows 7 Enterprise Service Pack 1
electerm version：v1.17

我的情况是开了4个标签，放置了1晚，第二天继续使用的时候就有CPU飙升问题，同 @Refuel-ZL  一样切换标签、管理ssh信息都处于假死状态。我怀疑是内存泄露问题导致频繁GC，但是我没有nodejs的GC debug经验，所以只是怀疑。

**Comment by foranewlife** [comment]
intel 的也这样

**Comment by mindfocus** [comment]
windows 11下，多个标签长时间（4-5个小时）打开，切换时，也会有明显的卡顿

**Comment by porro-tian** [comment]
macx64版本
2个页签之间切换，也非常卡。

**Comment by hummingsoul** [comment]
跟几个标签页面没关系 只要多个标签页在那放着 过一段时间 就会卡死

**Comment by hummingsoul** [comment]
跟几个标签页面没关系 只要多个标签页在那放着 过一段时间 就会卡死

个人环境: linuxmint

**Comment by autumnzq** [comment]
多页签的情况下，我开全屏后（不是最大化）会有这个问题，特别卡，最近的几个版本都是，最大化不卡（相对于全屏而言，也有一点延迟，但是能接受），但是全屏卡，

**Comment by imtiantian** [comment]
4.23号更新了一版，已解决，现在速度贼快！
