### ISSUE TITLE
使 rz / sz 支持 tmux

### ISSUE THREAD

**Issue by lonnywong** [electerm/electerm#2369]
使用 tmux 时，rz / sz 上传和下载文件会出问题，于是我写了个类似 rz / sz 的 [trzsz](https://trzsz.github.io/) ( trz / tsz )。

现在 trzsz ( trz / tsz ) 仅支持 iTerm2，有进度条。希望可以与 electerm 集成，提供更完善的 rz / sz 上传和下载功能。

trzsz github: https://github.com/trzsz/trzsz

**Comment by lonnywong** [comment]
我准备用 js 实现一个 [trzsz](https://github.com/trzsz/trzsz) 的组件 trzsz.js ( https://github.com/trzsz/trzsz.js )，搞好后提个 PR 集成进来。

**Comment by lonnywong** [comment]
`nodeIntegration` 是否可以设置为 `true`？如果 rz / sz 的插件不能使用 `fs`，做起来的效果会差很远。
https://github.com/electerm/electerm/blob/1e820752783eeabb076c86082c50efc181203dd9/src/app/app.js#L56

**Comment by zxdong262** [comment]
> 我准备用 js 实现一个 [trzsz](https://github.com/trzsz/trzsz) 的组件 trzsz.js ( https://github.com/trzsz/trzsz.js )，搞好后提个 PR 集成进来。

好用！要是可以支持rz/sz就好了，https://www.npmjs.com/package/zmodem.js 不太行

**Comment by lonnywong** [comment]
> > 我准备用 js 实现一个 [trzsz](https://github.com/trzsz/trzsz) 的组件 trzsz.js ( https://github.com/trzsz/trzsz.js )，搞好后提个 PR 集成进来。
> 
> 好用！要是可以支持rz/sz就好了，https://www.npmjs.com/package/zmodem.js 不太行

主要是 rz / sz 不支持 tmux ，而 tmux 也不愿意支持它，所以才写了 trzsz ( trz / tsz )。

[trzsz.js](https://github.com/trzsz/trzsz.js) 要支持 rz / sz 应该不难，代码框架都写好了，再套一个 zmodem 协议就行了。

electerm 的哪个版本会带上 trzsz ( trz / tsz ) 的功能？我在更新 trzsz 的文档，想把 electerm 也列在支持的列表中。

**Comment by zxdong262** [comment]
> > > 我准备用 js 实现一个 [trzsz](https://github.com/trzsz/trzsz) 的组件 trzsz.js ( https://github.com/trzsz/trzsz.js )，搞好后提个 PR 集成进来。
> > 
> > 
> > 好用！要是可以支持rz/sz就好了，https://www.npmjs.com/package/zmodem.js 不太行
> 
> 主要是 rz / sz 不支持 tmux ，而 tmux 也不愿意支持它，所以才写了 trzsz ( trz / tsz )。
> 
> [trzsz.js](https://github.com/trzsz/trzsz.js) 要支持 rz / sz 应该不难，代码框架都写好了，再套一个 zmodem 协议就行了。
> 
> electerm 的哪个版本会带上 trzsz ( trz / tsz ) 的功能？我在更新 trzsz 的文档，想把 electerm 也列在支持的列表中。

马上就发一个版本1.9.0

**Comment by lonnywong** [comment]
> 1.9.0

不急，我知道版本号就行。

**Comment by zxdong262** [comment]
> > 1.9.0
> 
> 不急，我知道版本号就行。

写错了，是1.19.0

**Comment by lonnywong** [comment]
> > > 1.9.0
> > 
> > 
> > 不急，我知道版本号就行。
> 
> 我写错了，是1.19.0

OK

**Comment by lonnywong** [comment]
> 
> 好用！要是可以支持rz/sz就好了，https://www.npmjs.com/package/zmodem.js 不太行

看到了很多都在用 `zmodem.js` ，感觉应该还是可以的。我怀疑是 `node-pty` 默认 `encoding` 为 `utf8` 导致它不能用的。

我提的 PR 已经将 `encoding` 设置为 `null`，你试试看 rz / sz 是不是神奇地变得好使了？

https://github.com/electerm/electerm/blob/master/src/app/server/session.js#L145

**Comment by zxdong262** [comment]
> > 好用！要是可以支持rz/sz就好了，https://www.npmjs.com/package/zmodem.js 不太行
> 
> 看到了很多都在用 `zmodem.js` ，感觉应该还是可以的。我怀疑是 `node-pty` 默认 `encoding` 为 `utf8` 导致它不能用的。
> 
> 我提的 PR 已经将 `encoding` 设置为 `null`，你试试看 rz / sz 是不是神奇地变得好使了？
> 
> https://github.com/electerm/electerm/blob/master/src/app/server/session.js#L145

没有，跟之前体验是一样的

**Comment by lonnywong** [comment]
> 
> 没有，跟之前体验是一样的

具体有哪些问题？确实有很多终端都在用它，不过我觉得他的接口可以优化一下。

**Comment by zxdong262** [comment]
> > 没有，跟之前体验是一样的
> 
> 具体有哪些问题？确实有很多终端都在用它，不过我觉得他的接口可以优化一下。

代码逻辑混乱，同步异步处理也不对，在某些情况下会有些传输进度无法更新的问题
