### ISSUE TITLE
书签悬停和固定没有层次

### ISSUE THREAD

**Issue by Refuel-ZL** [electerm/electerm#2370]
## Electerm version(版本号):
1.18.0/1.18.1
## Operating system(linux, macos, or windows7/8/10?)(操作系统):
macos
## Expected Behavior(期望的行为)

如同书签编辑一样 具有一致的层次目录结构
## Current Behavior(当前行为)

书签侧栏和固定 没有目录层次 全部平铺

## Possible Solution(可能的解决办法)

暂无
## Steps to Reproduce(复现步骤)

1.
2.
3.
4.

## Detailed Description(详细描述)

悬停效果
<img width="470" alt="image" src="https://user-images.githubusercontent.com/22957560/153164716-e0ddf22c-8719-42df-a6bd-c630f08dc47f.png">
固定效果
<img width="458" alt="image" src="https://user-images.githubusercontent.com/22957560/153164806-13624b43-07dd-485d-9563-f10a3d6339a3.png">
编辑书签
<img width="498" alt="image" src="https://user-images.githubusercontent.com/22957560/153164977-48aadfc0-0b11-4ee1-b01e-629cea75b12c.png">

**Comment by zxdong262** [comment]
你是不是只有默认目录，没有新建任何的顶级目录？如果是这样，你可以试试把目录都拖到顶层去

**Comment by zxdong262** [comment]
或者新建一个顶层目录就行了
