### ISSUE TITLE
无法输入中文，只能复制粘贴

### ISSUE THREAD

**Issue by SevenWong7** [electerm/electerm#2374]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号):
1.17.21
## Operating system(linux, macos, or windows7/8/10?)(操作系统):
windows10
## Steps to Reproduce(复现步骤)

1.
2.
3.
4.

**Comment by normalhh** [comment]
v1.17.19是可以的，我目前在用这个版本。之前发现升级后无法输入中文就回退了。

**Comment by SevenWong7** [comment]
> 好的，谢谢你。但如果新版本能解决这个问题就更好了，毕竟修复了很多问题。

**Comment by xcbdjazk** [comment]
windows10 自带的输入法可以输入

**Comment by zxdong262** [comment]
merge to https://github.com/electerm/electerm/issues/2232
