### ISSUE TITLE
Electerm don't pase code in wright order

### ISSUE THREAD

**Issue by PrzemekSkw** [electerm/electerm#2379]
## Expected Behavior(期望的行为)

When I paste code in nano Electerm does not paste code in the correct order like other terminals:

![Zrzut ekranu z 2022-02-22 10-10-47](https://user-images.githubusercontent.com/25219988/155099785-5401f74d-16c8-419a-8cce-42d0e3ee3f94.png)

and that look code in my tilix terminal:
![Zrzut ekranu z 2022-02-22 10-12-58](https://user-images.githubusercontent.com/25219988/155100254-c1939bd4-bcc5-4350-8b99-819b2cfd13af.png)

It's possible to fix that?
Regards.

**Comment by zxdong262** [comment]
Paste with `ctrl+v` or use context menu paste? `ctrl+v` should be OK, context menu paste seems not right.

**Comment by PrzemekSkw** [comment]
Hi, @zxdong262 
In nano don't work `ctrl+v`. There's `ctrl+U` option to paste but also don't work. Show me messege `clipboard is empty`.
Regards.

**Comment by zxdong262** [comment]
@PrzemekSkw  Can you try latest release? Fixed context menu paste.

**Comment by PrzemekSkw** [comment]
Thanks, it works OK after upgrade.
