### ISSUE TITLE
切换Tab速度慢

### ISSUE THREAD

**Issue by sacredaioros** [electerm/electerm#2384]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Expected Behavior(期望的行为)

切换Tab能够顺滑
## Can you reproduce the same behavior in other terminal(是否能在其他同类软件中复现):

无
## Current Behavior(当前行为)

在Tab打开一段时间之后，切换Tab会卡2秒左右
## Possible Solution(可能的解决办法)

无
## Steps to Reproduce(复现步骤)

1. 开好几个Tab
2. 每个Tab正常工作一段时间
3. 切换Tab

**Comment by hummingsoul** [comment]
切换tab 太卡了

**Comment by shutter-cp** [comment]
Mac m1芯片和Mac inter芯片 ，也有同样的问题。只要开个四五个、或者分屏两三个，用一段时间就会奇卡无比

**Comment by XJain01** [comment]
win10 也卡 切换不流畅

**Comment by saodis** [comment]
看来卡的问题还是没解决

**Comment by G-Akiraka** [comment]
一开始我以为只有mac有，换了linux和win系统一样卡的飞起，复制会话等操作也是一样的卡

**Comment by nlzq** [comment]
有没有大佬，帮忙解决下卡顿的问题。目前的几个维护者似乎解决不了，更新了好几个版本，更没更新前一样卡。

**Comment by nlzq** [comment]
作者估计都不用这客户端🤣

**Comment by zxdong262** [comment]
> 有没有大佬，帮忙解决下卡顿的问题。目前的几个维护者似乎解决不了，更新了好几个版本，更没更新前一样卡。

改动比较大，需要一些时间

**Comment by G-Akiraka** [comment]
> 作者估计都不用这客户端🤣

去年老早就试过一阵子太卡就放弃了，最近公司逼不得已换系统又开始用，快1年了还是一样卡

**Comment by nlzq** [comment]
> > 有没有大佬，帮忙解决下卡顿的问题。目前的几个维护者似乎解决不了，更新了好几个版本，更没更新前一样卡。
> 
> 改动比较大，需要一些时间

好久了哦，功能就先别做了吧  眼下流畅更重要，功能该有的都有，非常够用了。

**Comment by nlzq** [comment]
@zxdong262 肯定不是电脑配置的问题，是电脑都卡。

**Comment by zxdong262** [comment]
请问最新版本切换tab卡顿有改善吗 ! @G-Akiraka @shutter-cp @sacredaioros @nlzq

**Comment by G-Akiraka** [comment]
> 

你更新了不就知道了，确实快很多，但是长时间运行就会卡，但是也比之前强一些，关闭重新打开就是了
