### ISSUE TITLE
使用鼠标右键选择粘贴导致窗口失焦，需要再次点击； 顺便问一下批量输入命令EOF不能换行如何解决

### ISSUE THREAD

**Issue by xcbdjazk** [electerm/electerm#2385]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce(复现步骤)

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以详细描述下怎么重现这个吗 --"批量输入命令EOF不能换行 "

**Comment by xcbdjazk** [comment]
> 可以详细描述下怎么重现这个吗 --"批量输入命令EOF不能换行 "


我有一段命令如下
```
cat << EOF >test.sh
> 123456
> 234567
> EOF
```
直接粘贴到批量输入框中，无法得到我想要的效果
![image](https://user-images.githubusercontent.com/37769031/157469411-c0b33c2a-84ad-463d-bf3e-b4bc1199ba8e.png)
