### ISSUE TITLE
Electerm doesn't resize on snap

### ISSUE THREAD

**Issue by tomcrofty** [electerm/electerm#2386]
## Electerm version(版本号):

v1.18.5

## Operating system(linux, macos, or windows7/8/10?)(操作系统):

Windows 11/10

## Expected Behavior(期望的行为)

When snapping the window to the left/right, the app should resize to fit the zone.

## Can you reproduce the same behavior in other terminal(是否能在其他同类软件中复现):

Same issue on my laptop and on previous Windows versions (10)

## Current Behavior(当前行为)

When snapping the window, the application doesn't resize to fit. Tested using PowerToys FancyZones and usual Windows window snapping.

## Possible Solution(可能的解决办法)

There is no `resizeable` attribute set when creating the BrowserWindow, could be the cause, if I get time I'll download the source and test this myself to see if the fix is that simple. According to stackoverflow, someone said if you change the resizeable property at all after creating the window, the window will no longer resize when snapping. This may have been fixed in a later version of electron but I'm unsure on that.

## Steps to Reproduce(复现步骤)

1. Set the window size to something small
2. Snap the window to the left/right
3. Notice the window doesn't resize.

**Comment by tomcrofty** [comment]
After doing some digging, using the system title bar instead of the custom one does sort the problem. Must be some issue related to the custom title bar causing resizing not to work.

**Comment by zxdong262** [comment]
> After doing some digging, using the system title bar instead of the custom one does sort the problem. Must be some issue related to the custom title bar causing resizing not to work.

That is right, glad you resolved it.

**Comment by tomcrofty** [comment]
This isn't a fix really though, this is a work around, shouldn't we try to make the custom title bar behave properly?

**Comment by zxdong262** [comment]
> This isn't a fix really though, this is a work around, shouldn't we try to make the custom title bar behave properly?

Due to electron limitation: https://www.electronjs.org/docs/latest/tutorial/window-customization#limitations

I did not find a solution.

**Comment by tomcrofty** [comment]
The question is would you prefer Electerm to be functional with the
resizing or to have the translucent window.
