### ISSUE TITLE
mac m1 1.19.0 program unexpectedly exited

### ISSUE THREAD

**Issue by ishells** [electerm/electerm#2389]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号):  
electerm-1.19.0-mac-arm64.dmg

## Operating system(linux, macos, or windows7/8/10?)(操作系统): 
mac pro m1

## Current Behavior(当前行为)

When I open the 1.19.0 arm64.dmg version, the program unexpectedly exits。

## Detailed Description(详细描述)

Details of the error are as follows:
[error.log](https://github.com/electerm/electerm/files/8282118/error.log)

**Comment by zxdong262** [comment]
Please use the macx64 version if arm build not working, currently no arm device to debug.
