### ISSUE TITLE
保存ssh的时候报错

### ISSUE THREAD

**Issue by PengFei-io** [electerm/electerm#2396]
![image](https://user-images.githubusercontent.com/55048787/159938826-86873a5f-93b5-471b-9745-6daaa774d4c3.png)

**Comment by zxdong262** [comment]
方便按模板填写一下吗？

**Comment by PengFei-io** [comment]
## Electerm version(版本号):
1.9.5
## Operating system(linux, macos, or windows7/8/10?)(操作系统):
macos 12.3
## Expected Behavior(期望的行为)

测试连接和保存不报错
## Can you reproduce the same behavior in other terminal(是否能在其他同类软件中复现):
我的win电脑没有这种错误,mac有

## Current Behavior(当前行为)

填写ssh信息，然后点击测试链接,但不影响保存和使用,但使用时还是会报这个错

## Possible Solution(可能的解决办法)


## Steps to Reproduce(复现步骤)


1. 填写ssh信息
2.点击测试链接

**Comment by zxdong262** [comment]
可以试试最新版是不是解决了吗？
