### ISSUE TITLE
麻烦作者指点下初始窗口大小在哪修改

### ISSUE THREAD

**Issue by hxhaozi** [electerm/electerm#2416]
如题

**Comment by darrenliuwei** [comment]
我也想知道，现在每次启动之后，都需要手动点一下全屏

**Comment by fishcg** [comment]
看源码应该在下面这儿改
https://github.com/electerm/electerm/blob/ea0762dd9693f3fb248a82c14996709e6c1ac361/src/app/lib/window-control.js#L9

**Comment by zxdong262** [comment]
是个bug，下个版本修复
