### ISSUE TITLE
macos arm版 终端自动变大写

### ISSUE THREAD

**Issue by lutgcy** [electerm/electerm#2422]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/42140616/161175611-509f08fb-a39f-4751-8cc4-e4669ac6ed29.png">

**Comment by zxdong262** [comment]
可以试试x64版本吗？

**Comment by zwn888zwn** [comment]
复现方式：
1，安装搜狗输入法mac版
2，偏好设置-按键-状态切换-中英文-caps lock
3，进入electerm终端，按caps lock切换，发现要么是中文，要么是大写字母输入；其他APP无此问题
