### ISSUE TITLE
mac下无法全屏

### ISSUE THREAD

**Issue by sysuwsh** [electerm/electerm#2424]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version(版本号): 
v1.20.10

## Operating system(linux, macos, or windows7/8/10?)(操作系统): 
macOS Monterey 12.3.1

## Expected Behavior(期望的行为)

有标准的关闭、缩小、全屏按钮。

## Current Behavior(当前行为)

<img width="226" alt="image" src="https://user-images.githubusercontent.com/22320998/161378847-928aa0cd-2109-445d-9d91-d4e5840da686.png">
目前如上图，没有全屏按钮。
<img width="267" alt="image" src="https://user-images.githubusercontent.com/22320998/161378874-b530b9b6-89fd-4b22-9a33-022ebd187e28.png">
右上角的三个按钮略显突兀冗余，且中间按钮不是全屏操作，而是最大化软件界面。

**Comment by sysuwsh** [comment]
刚发现前面有issue了...

**Comment by zxdong262** [comment]
设置里使用系统标题栏就可以了

**Comment by sysuwsh** [comment]
> 

解决了，产品非常棒，感谢～
