### ISSUE TITLE
建议支持打开多个窗口（不是标签页）

### ISSUE THREAD

**Issue by Nguyendream** [electerm/electerm#2432]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

当前版本:
v1.20.10 win

有很多场景多个窗口会更方便，比如
- 方便区分不同的服务器组，避免搞混
- 一组服务器需要使用批量输入功能，另一组不需要

记得老版本支持开启多个程序窗口，当前版本打开第一个后，再次打开，只会命中已经打开的窗口。

**Comment by zxdong262** [comment]
最新版已经支持
