### ISSUE TITLE
终端vim的普通模式下，backspace识别错误

### ISSUE THREAD

**Issue by PaTTeeL** [electerm/electerm#2435]
### Electerm Version(Electerm版本)

v1.20.10

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19042.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

终端在vim的普通模式下，backspace识别错误，一旦输错命令无法回退，还会出现^?符号

![屏幕截图 2022-04-06 224937](https://user-images.githubusercontent.com/9150277/162003410-c573dfab-3e9e-4f85-a495-8e046cfad33d.jpg)

### What should have happened?(期望的结果)

vim普通模式可以正常使用backspace键

**Comment by zxdong262** [comment]
可以试试最新版本吗？

**Comment by PaTTeeL** [comment]
> 可以试试最新版本吗？

嗯嗯，试过可以正常使用退格键了
