### ISSUE TITLE
连接ssh自动断开，或无法连接ssh

### ISSUE THREAD

**Issue by ygzhong000** [electerm/electerm#2437]
### Electerm Version(Electerm版本)

1.21.9

### Platform detail (平台详情)

Windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

关闭App启动后的第一个标签，之后连接ssh会自动断开，或无法连接ssh

### What should have happened?(期望的结果)

修复bug

**Comment by zxdong262** [comment]
-> #2438
