### ISSUE TITLE
密码输入框无法粘贴

### ISSUE THREAD

**Issue by shutter-cp** [electerm/electerm#2444]
### Electerm Version(Electerm版本)

1.21.14.1

### Platform detail (平台详情)

Darwin chenpengdeMacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="874" alt="image" src="https://user-images.githubusercontent.com/37921589/162872246-730c3b94-9582-425f-bd45-547faadcbc77.png">

### What should have happened?(期望的结果)

希望可以粘贴

**Comment by zxdong262** [comment]
ctrl + v不行吗？

**Comment by shutter-cp** [comment]
> v

ctrl v 或者 command v都不行

**Comment by shutter-cp** [comment]
1.21.18.1 已修复
