### ISSUE TITLE
Ubuntu下无法运行

### ISSUE THREAD

**Issue by atomxw** [electerm/electerm#2447]
### Electerm Version(Electerm版本)

1.21.18

### Platform detail (平台详情)

linux

### What steps will reproduce the bug?(重新问题的详细步骤)

$electerm 
error: unknown option '--no-sandbox'
09:06:00 debug › electerm start
09:06:00 info › server runs on 127.0.0.1 30975
09:06:00 debug › error parsing $HOME/.ssh/config
09:06:00 debug › maybe no $HOME/.ssh/config, but it is ok
Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')
    at initApp (/snap/electerm/188/resources/app.asar/lib/init-app.js:34:19)
    at Object.init (/snap/electerm/188/resources/app.asar/lib/ipc.js:83:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:193:563

### What should have happened?(期望的结果)

11

**Comment by blankhang** [comment]
+1

**Comment by hmahdiany** [comment]
I have the same problem and there is only one error:
`Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')`
Electerm was working just fine until I updated my Ubuntu system. 
My system kernel version now is `5.13.0-39-generic` and Electerm version is `1.21.18`

**Comment by blankhang** [comment]
> I have the same problem and there is only one error: `Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')` Electerm was working just fine until I updated my Ubuntu system. My system kernel version now is `5.13.0-39-generic` and Electerm version is `1.21.18`

by now just remove the 1.21.18 version and then reinstall the 1.21.14 version and don't upgrade until the problem was solved

**Comment by hmahdiany** [comment]
> > I have the same problem and there is only one error: `Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')` Electerm was working just fine until I updated my Ubuntu system. My system kernel version now is `5.13.0-39-generic` and Electerm version is `1.21.18`
> 
> by now just remove the 1.21.18 version and then reinstall the 1.21.14 version and don't upgrade until the problem was solved

Thank you @blankhang 
Version `1.21.14` is working fine. But I have one follow up question: Is there any way to restore my bookmarks? Now I lost all of them

**Comment by blankhang** [comment]
> > > I have the same problem and there is only one error: `Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')` Electerm was working just fine until I updated my Ubuntu system. My system kernel version now is `5.13.0-39-generic` and Electerm version is `1.21.18`
> > 
> > 
> > by now just remove the 1.21.18 version and then reinstall the 1.21.14 version and don't upgrade until the problem was solved
> 
> Thank you @blankhang Version `1.21.14` is working fine. But I have one follow up question: Is there any way to restore my bookmarks? Now I lost all of them

you should always use github gist sync functin to backup all your bookmarks to cloud!

**Comment by zxdong262** [comment]
fixed in 1.21.20

**Comment by tiger7chan** [comment]
在ubuntu18.04下面，安装最新的1.21.93版本，一直卡在启动界面了

**Comment by zxdong262** [comment]
> 在ubuntu18.04下面，安装最新的1.21.93版本，一直卡在启动界面了

可以命令行运行看看什么信息吗
