### ISSUE TITLE
Win11 安装版运行时一直卡在加载页面

### ISSUE THREAD

**Issue by Studyofslag** [electerm/electerm#2448]
### Electerm Version(Electerm版本)

1.21.18

### Platform detail (平台详情)

win 11

### What steps will reproduce the bug?(重新问题的详细步骤)

- 安装覆盖之前的安装时加载不进去
- 卸载之前的安装，重新安装最新版依然卡在加载页面

### What should have happened?(期望的结果)

期望点开进入界面

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其他同类软件没遇到

### Additional information(其他任何相关信息)

1.21.14版本没有问题

**Comment by 1nfin1ty** [comment]
一样，新版本卡在启动界面

**Comment by Feng-Lin-Xi** [comment]
win10 也是复现同样问题

**Comment by zxdong262** [comment]
fixed in 1.21.20
