### ISSUE TITLE
1.21.18有问题，从上一版本覆盖安装更新后没法运行了

### ISSUE THREAD

**Issue by aheig** [electerm/electerm#2450]
### Electerm Version(Electerm版本)

1.21.18有问题，从上一版本覆盖安装更新后没法运行了

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

从上一版本覆盖安装更新后没法运行了，打开后，一直在logo界面闪logo  进不了程序界面

### What should have happened?(期望的结果)

一直在这儿闪logo
![闪](https://user-images.githubusercontent.com/61814388/163082659-97f56d56-7004-402b-b26e-174a3985b041.jpg)

**Comment by blankhang** [comment]
一样的问题...我卸载重装也是一样 
ubuntu20.04.4LTS

**Comment by maningphp** [comment]
顶一下，一样的问题，我是win10系统

**Comment by thjgit** [comment]
同问

**Comment by enyusmile** [comment]
+1
已回退到1.21.14

**Comment by slankka** [comment]
一样，怎么解决？

**Comment by siutung** [comment]
一样的问题，准备回退了。。。。。

**Comment by hummingsoul** [comment]
是打开后 一直卡在启动界面进不去吧 已卸载

**Comment by FerrySpace** [comment]
+1   已经回退1.21.14

**Comment by zxdong262** [comment]
fixed in 1.21.20
