### ISSUE TITLE
建议重新设计一下菜单的排列方式。

### ISSUE THREAD

**Issue by siutung** [electerm/electerm#2452]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

建议重新设计一下菜单的排列样式。
发现在连接了远程机器后，会话没有断开，此时想修改一下主题样式，发现修改了主题样式后，无法返回会话控制台窗口，必须关闭或重启eleterm主程序，一切重新来过么？

**Comment by zxdong262** [comment]
右上角的关闭按钮不好使吗？

**Comment by siutung** [comment]
> 

看到了，多谢！只是这窗口是不是可以设计得稍微精细一点啊？
