### ISSUE TITLE
Win11打开一直停留在初始页

### ISSUE THREAD

**Issue by 986823307** [electerm/electerm#2455]
### Electerm Version(Electerm版本)

1.21.18

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

机型是Lenovo R9000P 2021H，操作系统为windows11 dev内测版本，下载安装后打开一直卡在初始页
![image](https://user-images.githubusercontent.com/56620683/163339202-1dc5a551-ac78-41b4-b612-8703dda5634b.png)

### What should have happened?(期望的结果)

望修复

**Comment by darrenliuwei** [comment]
升级到最新版好像就解决了。

https://github.com/electerm/electerm/tags

**Comment by 986823307** [comment]
> 升级到最新版好像就解决了。
> 
> https://github.com/electerm/electerm/tags

哦哦 我刚下载试了可行，谢谢

**Comment by 986823307** [comment]
我已收到您的邮件【自动回复】

**Comment by 986823307** [comment]
我已收到您的邮件【自动回复】
