### ISSUE TITLE
ssh标签页不显示标题，仅显示“新连接-user@IP:port”，不方便区分不同服务器

### ISSUE THREAD

**Issue by frankterm** [electerm/electerm#2467]
### Electerm Version(Electerm版本)

v1.21.34

### Platform detail (平台详情)

mac os darwin 20.6.0

### What steps will reproduce the bug?(重新问题的详细步骤)

ssh登录即可

### What should have happened?(期望的结果)

像原来一样，显示标题/用户/IP/端口即可

**Comment by zxdong262** [comment]
-> https://github.com/electerm/electerm/issues/2466
