### ISSUE TITLE
标签页不显示链接的别名

### ISSUE THREAD

**Issue by AD1026** [electerm/electerm#2468]
### Electerm Version(Electerm版本)

v1.21.34

### Platform detail (平台详情)

mac os

### What steps will reproduce the bug?(重新问题的详细步骤)

更新新版本后，标签页不显示链接的别名了，打开任何链接，标签页都只显示新连接

### What should have happened?(期望的结果)

恢复原先版本的显示就好

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/ed362fb66ee95dcde9db6de98a79077400db6c8a
