### ISSUE TITLE
win10上传设置到gitee的token。mac m1用token下载设置报错

### ISSUE THREAD

**Issue by LiFuHai1106** [electerm/electerm#2470]
### Electerm Version(Electerm版本)

win10-1.21.34   Mac m1-1.21.34

### Platform detail (平台详情)

win10, mac m1

### What steps will reproduce the bug?(重新问题的详细步骤)

win10上传设置到gitee的token。mac m1用token下载设置报错

### What should have happened?(期望的结果)

mac能使用win10的设置

### Additional information(其他任何相关信息)

TerminalFile manager
Batch input
Encode
Request failed with status code 404
Error: Request failed with status code 404 at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.21.34:2:1664673 at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.21.34:2:1663192) at Worker.<anonymous> (file:///Applic

**Comment by zxdong262** [comment]
下载时候有填写正确的gist id吗

**Comment by LiFuHai1106** [comment]
> 填了gist id可以了。但没恢复中文，还是英文
