### ISSUE TITLE
TELNET

### ISSUE THREAD

**Issue by mnscc** [electerm/electerm#2482]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

是否能添加TELNET书签

**Comment by zxdong262** [comment]
本地书签的运行命令里设置为 telnet xxxx 是不是可以满足需求？

**Comment by zxdong262** [comment]
-> https://github.com/electerm/electerm/issues/1941

**Comment by zxdong262** [comment]
-> https://github.com/electerm/electerm/issues/1532

**Comment by Veng0923** [comment]
> 
不太行 希望直接可以选书签自动登陆进去
