### ISSUE TITLE
当只打开一个选项卡的时候，会自动打开一个终端

### ISSUE THREAD

**Issue by 443126500** [electerm/electerm#2485]
### Electerm Version(Electerm版本)

v1.21.48

### Platform detail (平台详情)

Darwin MacBook-Pro 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 默认打开控制A窗口，此时打开B窗口，再把A窗口关掉，软件会自动打开终端，关掉终端口也会再次打开
2.Mac版本的右上角显示最小化，全屏，关闭按钮，显示有点别扭，希望Mac版本的去掉这个显示

### What should have happened?(期望的结果)

1.有已用窗口的时候不自动打开终端，只有当所有窗口关闭的时候才自动打开终端
2.希望去掉右上角的三个按钮

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能

### Additional information(其他任何相关信息)

![image](https://user-images.githubusercontent.com/57339701/166878293-41b17f8b-925c-4dcb-9346-77c59118e0af.png)
![image](https://user-images.githubusercontent.com/57339701/166878325-9077646f-c80e-4a3f-af5b-e8a0852169aa.png)
![Uploading image.png…]()

**Comment by wmy1010719164** [comment]
![electerm_s2ZaMorbqN](https://user-images.githubusercontent.com/36840717/166891088-edd50fac-ac11-4a3f-9126-02691b0f97d8.png)
两个问题，其实非常影响体验：
1。打开软件的时候会默认打开一个终端，能否去掉这个，或者在设置里可以关掉
2。当关掉这个默认终端时，会再自动打开一个，无法关掉。

**Comment by wmy1010719164** [comment]
谢谢回复。第一感觉不够清爽。应该允许自定义设置是否自动打开一个终端，毕竟不是每次都要连接同一个服务器。并且打开一个窗口也会占用系统资源，我观察了一下，一个窗口占用100到500兆不等，其实也是一个不小的开销。最新版本关闭一个复制的窗口后，还会再打开，这个更不合理，既然我手动关闭了，为什么还会自动打开呢？



---- 回复的原邮件 ----
| 发件人 | ZHAO ***@***.***> |
| 日期 | 2022年05月05日 23:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [electerm/electerm] 当只打开一个选项卡的时候，会自动打开一个终端 (Issue #2485) |

请问为什么感觉默认保持的一个终端影响体验呢

**Comment by kingofkids** [comment]
我也windows10上遇到了相同的问题，暂时只在v1.21.48版本上遇到了这样的问题，在使用时感觉不够清爽

**Comment by jiangdi1118** [comment]
我也遇到了这个问题。

**Comment by zxdong262** [comment]
将在下个版本修复

**Comment by kiolygenius** [comment]
Linux 下面有个问题 直接关闭退出后，残留子进程(bash 或者 zsh)无法退出。（v1.21.48 on archlinux)
