### ISSUE TITLE
1.21.48 in bugs

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2487]
### Electerm Version(Electerm版本)

1.21.48

### Platform detail (平台详情)

Darwin MacBook_Pro_M1Pro.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?(重新问题的详细步骤)

最新版本,关闭一个不要的标签后,竟然会自己在打开一个新标签,而且关都关不掉!以前的版本没有这个问题.

具体看图:
![iShot_2022-05-06_13 42 44](https://user-images.githubusercontent.com/7685337/167074136-abfdbe5c-c025-4b7a-8645-f475977a4ae3.gif)

### What should have happened?(期望的结果)

解决Bug

**Comment by woody3rd** [comment]
我更新完也发现了这个bug，关不掉了

**Comment by zxdong262** [comment]
merge to #2485
