### ISSUE TITLE
希望能逐渐走向手机端，或者网页端

### ISSUE THREAD

**Issue by Adsryen** [electerm/electerm#2498]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

相信一定会存在一部分人群，会在工作环境外临时使用到ssh，或者依赖移动数据连接only ipv6，在平板或者手机端一定会是一个优选，就像termius一样。另外通过登录账号（二步验证）相关方式同步备份，以上仅一个小点子，望成真💕💕

**Comment by zxdong262** [comment]
已经有 https://github.com/electerm/electerm-web
