### ISSUE TITLE
设置gitee同步 status code 400

### ISSUE THREAD

**Issue by strive1216** [electerm/electerm#2500]
### Electerm Version(Electerm版本)

1.21.57

### Platform detail (平台详情)

M1

### What steps will reproduce the bug?(重新问题的详细步骤)

![Uploading image.png…]()

github 同步正常
gitee 同步400  
使用现有的gitsid或自动新建(能看到新建的gist)都一样
`Error: Request failed with status code 400
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.21.57:2:1601882
    at Object.resolve (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.21.57:2:1600401)
    at Worker.<anonymous> (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.21.57:2:1601330)`

### What should have happened?(期望的结果)

gitee能正常上传配置

**Comment by zxdong262** [comment]
gist secret scope
是不是正确呢？https://gitee.com/github-zxdong262/electerm/wikis/Create%20personal%20access%20token?sort_id=3028409

**Comment by strive1216** [comment]
> 私人令牌的权限是不是正确呢？参考 https://gitee.com/github-zxdong262/electerm/wikis/Create%20personal%20access%20token?sort_id=3028409

应该不是，如果不指定现有gist ID 能自动创建一个gistid，但是也不能上传设置

**Comment by zxdong262** [comment]
> > 私人令牌的权限是不是正确呢？参考 https://gitee.com/github-zxdong262/electerm/wikis/Create%20personal%20access%20token?sort_id=3028409
> 
> 应该不是，如果不指定现有gist ID 能自动创建一个gistid，但是也不能上传设置

是不是书签太多，gitee对大小有限制？

**Comment by strive1216** [comment]
是的 我尝试删除大量书签后是可以正常上传了，
PS:吐槽一下删除功能:不能批量删除、删除目录仅把下级书签平铺(此处可加一个勾选框)；
