### ISSUE TITLE
[功能请求] 希望配置文件同步方式能支持 Gitea

### ISSUE THREAD

**Issue by cainb** [electerm/electerm#2506]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

如标题所言，希望配置文件同步方式能支持 [Gitea](https://github.com/go-gitea/gitea)

**Comment by zxdong262** [comment]
最新版已经支持

**Comment by cainb** [comment]
> 最新版已经支持

em，最新版（v1.21.57）并没有看到 Gitea 同步项，只有 GitHub 和 Gitee

![image](https://user-images.githubusercontent.com/48700331/170306102-5b3d0d80-427c-419b-96e6-01277bec87cb.png)

**Comment by zxdong262** [comment]
> > 最新版已经支持
> 
> em，最新版（v1.21.57）并没有看到 Gitea 同步项，只有 GitHub 和 Gitee
> 
> ![image](https://user-images.githubusercontent.com/48700331/170306102-5b3d0d80-427c-419b-96e6-01277bec87cb.png)

啊，我看错了，原来是gitea
