### ISSUE TITLE
macOS只要一睡眠状态或者稍微过段时间所有连接窗口都自动关闭了

### ISSUE THREAD

**Issue by Tonny-zhou** [electerm/electerm#2509]
### Electerm Version(Electerm版本)

v.21.57

### Platform detail (平台详情)

mac OS

### What steps will reproduce the bug?(重新问题的详细步骤)

您好，
macOS只要一在睡眠状态或者稍微过段时间所有之前开的服务器连接窗口都自动关闭了，只剩下一个本地的新连接窗口，这有啥办法能避免吗？我记得之前的版本不会自动关掉的，只是每个窗口断开连接而已，不会自动关掉的。

是和Keepalive间隔(ms)这个参数有关吗，可是这个参数最大值也就20000

<img width="556" alt="image" src="https://user-images.githubusercontent.com/36953648/170851295-274cd15f-fc68-416a-aeb8-5c8cf33f84b8.png">

### What should have happened?(期望的结果)

连接的窗口希望不要自动关闭，只要是断开状态就行了

**Comment by zxdong262** [comment]
-> https://github.com/electerm/electerm/issues/2508
