### ISSUE TITLE
网络断开连接之后并再次重连后，原打开标签全部自动关闭

### ISSUE THREAD

**Issue by wenmang** [electerm/electerm#2511]
### Electerm Version(Electerm版本)

1.21.57

### Platform detail (平台详情)

Windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

打开多个远程标签页正常使用

![image](https://user-images.githubusercontent.com/34470691/170911013-a056eea7-8afa-4e39-8158-20760e57ecb6.png)

网络断开之后，所有标签全部关闭，只剩下默认标签页

![image](https://user-images.githubusercontent.com/34470691/170911130-76722f79-aee2-4e16-8d19-809121168971.png)

### What should have happened?(期望的结果)

网络断开连接之后不自动关闭已断连的标签页

**Comment by zxdong262** [comment]
--> https://github.com/electerm/electerm/issues/2508
