### ISSUE TITLE
固定书签后，窗口镂空了

### ISSUE THREAD

**Issue by yanguangjian** [electerm/electerm#2513]
### Electerm Version(Electerm版本)

1.21.73

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19043.0，x64

### What steps will reproduce the bug?(重新问题的详细步骤)

固定书签后，窗口镂空了
![image](https://user-images.githubusercontent.com/26669317/171084487-363f74f8-ed21-482d-b888-8766c1caee13.png)

### What should have happened?(期望的结果)

修复

**Comment by zxdong262** [comment]
可以描述下详细的复现步骤吗

**Comment by zxdong262** [comment]
打开开发者工具，在Application->local storage清空即可去掉默认的固定书签状态

**Comment by yanguangjian** [comment]
1、问题出在上个版本。 在书签选择“保持面板打开”后出现问题现象：
![image](https://user-images.githubusercontent.com/26669317/171091071-0aed7d6c-1b42-4e5d-ab8a-efcb515de4c1.png)
2、更新到1.21.73问题依旧，删除旧版本后再重装1.21.73后问题消除
