### ISSUE TITLE
更新至1.21.73后设置丢失

### ISSUE THREAD

**Issue by mrmyn** [electerm/electerm#2515]
### Electerm Version(Electerm版本)

1.21.73

### Platform detail (平台详情)

macOS 10.15.7

### What steps will reproduce the bug?(重新问题的详细步骤)

如题，更新至Electerm v1.21.73后，打开后以前的配置都丢失，重新设置了Socks代理、语言设置为中文、添加好服务器书签保存好后，关闭Electerm再次打开时又恢复到初始状态(Socks置空，语言恢复到英文，书签全部丢失)

### What should have happened?(期望的结果)

感谢修复

**Comment by zxdong262** [comment]
你有其他设备可以试试吗，不能复现这个情况

**Comment by djm430** [comment]
win10 今天更新后出现同样问题，而且重新设置后重启客户端，也无法加载配置

**Comment by mrmyn** [comment]
> 你有其他设备可以试试吗，不能复现这个情况

暂时没有--  看2楼也是这个情况。

**Comment by litai686** [comment]
macbook m1 同样情况，设置丢失

**Comment by darrenliuwei** [comment]
Windows11下载这个包没有问题，配置没有丢失。
![image](https://user-images.githubusercontent.com/10508248/171308610-48d8cb86-2ef1-45bd-8fe0-bd4e5ca22cb0.png)

**Comment by mrmyn** [comment]
补充一下，是在electerm 内在线升级的

**Comment by zxdong262** [comment]
已经发布新版本，请试试吧

**Comment by imic07** [comment]
配置也丢失了，Manjaro 21.2.6 Qonos
