### ISSUE TITLE
macOS经常出现死机

### ISSUE THREAD

**Issue by james-ok** [electerm/electerm#2523]
### Electerm Version(Electerm版本)

1.21.57

### Platform detail (平台详情)

macOS Monterey 12.1

### What steps will reproduce the bug?(重新问题的详细步骤)

Electerm打开使用一段时间后macOS死机，并且用时间长了，软件非常卡

### What should have happened?(期望的结果)

流畅，至少不会造成系统死机

**Comment by zxdong262** [comment]
可以升级到最新版本试试
