### ISSUE TITLE
无法使用外部编辑器

### ISSUE THREAD

**Issue by BigUIFU** [electerm/electerm#2528]
### Electerm Version(Electerm版本)

v1.21.74

### Platform detail (平台详情)

Win10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

已连接状态标签左上角本来是个绿色的点，使用“编辑...”后，不能使用外部编辑器，以自带notepad为例，填写绝对地址或者notepad.exe或者直接写notepad都不行，标签上原本绿色的点变成红色，好像断开连接了一样，重新连接会一直转，关闭标签重开个书签也不行，就像崩溃了一样，另外使用一卡一卡的，设置项里面的表单输入字符串要5-7秒才出来

### What should have happened?(期望的结果)

想知道这是什么问题，另外建议出个简易的使用文档

**Comment by zxdong262** [comment]
可以试试最新版本
