### ISSUE TITLE
标签无法重连 

### ISSUE THREAD

**Issue by tonyttz** [electerm/electerm#2530]
### Electerm Version(Electerm版本)

v1.21.88

### Platform detail (平台详情)

macos  10.15.7

### What steps will reproduce the bug?(重新问题的详细步骤)

连接断开后, 点击标签上的重连按钮, 窗口变成半透明, 无法重连成功.

### What should have happened?(期望的结果)

能正常重连

### Additional information(其他任何相关信息)

另外, 感觉最近几个版本在标签上问题有点多, 前面有个版本是 session 断开后, 标签就自动消失了

**Comment by zxdong262** [comment]
确实存在，需要点一下ssh才可以

**Comment by yzlfhcx** [comment]
👌

**Comment by twwch** [comment]
什么时候发版？一直忍受这个bug
