### ISSUE TITLE
启动慢，每次打开都透明显示其他窗口内容

### ISSUE THREAD

**Issue by yzlfhcx** [electerm/electerm#2534]
### Electerm Version(Electerm版本)

1.21.x

### Platform detail (平台详情)

window10

### What steps will reproduce the bug?(重新问题的详细步骤)

启动，如下图：
![image](https://user-images.githubusercontent.com/41557301/174446024-9662ef1c-6f01-417b-bc29-df9253484437.png)
![image](https://user-images.githubusercontent.com/41557301/174446045-1adc15d7-4be8-4088-a251-f0c3d8192fb0.png)

### What should have happened?(期望的结果)

启动再快些，千万别再有透明的了，这都2022年下半年了。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

没有

### Additional information(其他任何相关信息)

没有

**Comment by yzlfhcx** [comment]
一直没有提这些问题，认为更新几个版本就会解决，好长时间都没发现解决，真无奈，只好亲自提了。标签问题、日志问题、启动问题  三个问题吧，那个固定问题解决了就不提了。

**Comment by zxdong262** [comment]
可以试试最新版
