### ISSUE TITLE
连接断开后重新连接无反应

### ISSUE THREAD

**Issue by mnscc** [electerm/electerm#2536]
### Electerm Version(Electerm版本)

v1.21.88

### Platform detail (平台详情)

mac

### What steps will reproduce the bug?(重新问题的详细步骤)

登陆窗口连接断开后点击重新连接，连接不上（不显示登陆界面）需要手动点击ssh才能正常连接。点击重新连接后会弹出新窗口连接标签。

### What should have happened?(期望的结果)

1. 点击重新连接后自动连接
2. 点击重新连接后不弹出新窗口连接标签
3. 提高响应速度

**Comment by mnscc** [comment]
![image](https://user-images.githubusercontent.com/88484485/174471553-fd4ebd07-a3a3-4151-a8de-a157df0961e2.png)

**Comment by mnscc** [comment]
![image](https://user-images.githubusercontent.com/88484485/174471600-cb2c139c-b0d5-4556-a4d3-55cfd6704c73.png)

**Comment by zxdong262** [comment]
-> https://github.com/electerm/electerm/issues/2530
