### ISSUE TITLE
switching tab slow 

### ISSUE THREAD

**Issue by heaseny** [electerm/electerm#2541]
### Electerm Version(Electerm版本)

v21.57

### Platform detail (平台详情)

Ubuntu 20.04.2 LTS 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

create more than 10 terminal connections with new tab for each, then switch to different tabs, you will see the switching time nearly 3 seconds, this is beyond endurance
创建10个tab，每个tab对应一个ssh连接，然后在tab间进行切换，会发现切换时间需要将近3秒，这个切换速度无法忍受
![image](https://user-images.githubusercontent.com/35910818/175482417-c1ad2ff6-f873-420f-833c-6b501ba85380.png)

### What should have happened?(期望的结果)

改进切换terminal tab的速度，控制在1s以内

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

There is no such problem in other terminal apps, such as tabby or Ásbrú Connection Manager
使用tabby或者Ásbrú Connection Manager没有出现这个问题

**Comment by zxdong262** [comment]
Can you try latest release?

**Comment by ouyangxudu** [comment]
I met this issue too, the latest version v1.21.88, mac

**Comment by heaseny** [comment]
@zxdong262 this issue also exists with v1.21.88 on Ubuntu 20.04.2 LTS

**Comment by zxdong262** [comment]
Should be fixed in latest release v1.22.1+

**Comment by heaseny** [comment]
@zxdong262 It's a little quicker than before within 10 tabs with v1.22.1,  but  the switching time will increase to 3s when there are 15+ tabs.
Thank you very much for fixing this, a greater improvement is also looked forwarding to .

**Comment by heaseny** [comment]
This issue  disappears with v1.22.20, this is really exciting.  @zxdong262 Thanks a lot for fixing it.

**Comment by zxdong262** [comment]
> This issue disappears with v1.22.20, this is really exciting. @zxdong262 Thanks a lot for fixing it.

Thank you for letting me know, also please try 1.22.30

**Comment by heaseny** [comment]
I just try with 1.22.30, and it is also excellent one, thanks
