### ISSUE TITLE
版本升级到1.21.91后升级提示还在

### ISSUE THREAD

**Issue by 2273267033zzz** [electerm/electerm#2547]
### Electerm Version(Electerm版本)

1.21.91

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://user-images.githubusercontent.com/50507638/176804462-46357867-622b-494b-ab08-9eca374ccaaa.png)

### What should have happened?(期望的结果)

去掉这个提示，因为鼠标点击不再提示这个版本没有反应

**Comment by 1nfin1ty** [comment]
一样的问题，一直提示版本更新

**Comment by sunchunfeng** [comment]
mac m1 也是一样。
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/30862573/176805353-f578400b-472f-4edd-9a42-e3101f4cea88.png">

**Comment by tonyttz** [comment]
最近的版本一直是改了几个问题后, 又增加一些新问题, 东哥的头发估计又掉了不少, 哈哈!
