### ISSUE TITLE
listen EACCES: permission denied 127.0.0.1: 5571   at Server.

### ISSUE THREAD

**Issue by XiaoSong2017** [electerm/electerm#2548]
### Electerm Version(Electerm版本)

1.21.91

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

目前在Windows平台下的最新的两个版本安装后da'k打开出现以下问题：
![image](https://user-images.githubusercontent.com/35443773/176852759-e593ff17-9fb9-4f40-8d77-4b1bbf798623.png)
导致无法正常运行；

### What should have happened?(期望的结果)

期待该应用在之后的版本中能够解决这个bug

**Comment by zxdong262** [comment]
我这里复现不了，应该是跟你本机环境有关

**Comment by wqk151** [comment]
我也遇到了同样的问题，退回旧版本就没问题了

**Comment by wqk151** [comment]
我是win10企业版，1.21.93版本出现同样的问题。现在用的1.21.74正常

**Comment by zxdong262** [comment]
@wqk151 之前的版本不占用端口，直接载入文件，大概有什么软件和设置占用或者控制端口

**Comment by zxdong262** [comment]
@wqk151 @XiaoSong2017 [electerm-1.21.93-win-x64-loose.tar.gz](https://github.com/electerm/electerm/releases/download/v1.21.93/electerm-1.21.93-win-x64-loose.tar.gz) 方便下载这个版本试试哪个端口可用吗？`electerm-1.21.93-win-x64-loose/resources/app/lib/create-window.js` 里面有个5571, 改为10000+端口试试行不行

**Comment by zxdong262** [comment]
哦，我知道了，用30000+的端口应该就可以了

**Comment by wqk151** [comment]
是的，我改成了15571和35571是可以的，默认的5571不行

**Comment by XiaoSong2017** [comment]
好的！谢谢！

**Comment by comandowang** [comment]
改成30000+, 新建连接的时候 还是会报
  at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:500)
    at Object.runGlobalAsync (D:\tools\electerm\electerm-1.21.93-win-x64-loose\resources\app\preload\preload.js:101:24)
    at Hv (http://127.0.0.1:35571/js/electerm.js?1.21.93:2:1848235)
    at Wv (http://127.0.0.1:35571/js/electerm.js?1.21.93:2:1848445)
    at http://127.0.0.1:35571/js/electerm.js?1.21.93:2:1860508

**Comment by zxdong262** [comment]
> 改成30000+, 新建连接的时候 还是会报 at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:500) at Object.runGlobalAsync (D:\tools\electerm\electerm-1.21.93-win-x64-loose\resources\app\preload\preload.js:101:24) at Hv (http://127.0.0.1:35571/js/electerm.js?1.21.93:2:1848235) at Wv (http://127.0.0.1:35571/js/electerm.js?1.21.93:2:1848445) at http://127.0.0.1:35571/js/electerm.js?1.21.93:2:1860508

具体信息是什么呢，端口被占用吗？

**Comment by kele2016** [comment]
我也是这个问题，就不提新的ISSUE了。
也是WIN11系统，关闭重新打开，还是报这个错误
![image](https://github.com/electerm/electerm/assets/17295910/a4d2f68b-ffb1-4c8c-bdcb-83f9f7a799fd)
![image](https://github.com/electerm/electerm/assets/17295910/42ae4f52-17bd-40c9-bb74-2aafa62d5df9)
端口并没有被占用。
