### ISSUE TITLE
sftp文件夹上传速度慢

### ISSUE THREAD

**Issue by 1nfin1ty** [electerm/electerm#2551]
### Electerm Version(Electerm版本)

1.21.93

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

sftp拖拽文件夹上传速度很慢，而且会导致软件非常卡顿，上传单个文件似乎没有这个问题

### What should have happened?(期望的结果)

文件夹能正常上传

**Comment by zxdong262** [comment]
文件夹也是压缩后上传，然后解压的

**Comment by zxdong262** [comment]
可以试试最新版
