### ISSUE TITLE
使用openssh8.8以上版本的系统无法通过密匙登录(ubuntu22.04)

### ISSUE THREAD

**Issue by leonunix** [electerm/electerm#2555]
### Electerm Version(Electerm版本)

1.21.93

### Platform detail (平台详情)

windows 7/8/10/11, mac os, or linux

### What steps will reproduce the bug?(重新问题的详细步骤)

https://www.openssh.com/txt/release-8.8

SHA-1已经被新的版本移除。所以导致ubuntu22.04 centos9 以后都无法使用密匙登录。
使用密匙登录的时候会跳出输入密码。

### What should have happened?(期望的结果)

可以支持ubuntu 22.04 centos9

**Comment by zxdong262** [comment]
请问你的密匙是怎么生成的呢

**Comment by leonunix** [comment]
@zxdong262 
我这里密匙是公司派发的。在macos本地使用ssh -i 是可以ubuntu22.04系统的。

这个是debug。我再附上macos上的ssh本地的log

08:02:54 info › Handshake: (local) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
08:02:54 info › Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
08:02:54 info › Handshake: KEX algorithm: curve25519-sha256
08:02:54 info › Handshake: (local) Host key format: ssh-ed25519,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss
08:02:54 info › Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
08:02:54 info › Handshake: Host key format: ssh-ed25519
08:02:54 info › Handshake: (local) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,aes128-ctr,aes192-ctr,aes256-ctr,blowfish-cbc,3des-cbc,arcfour256,arcfour128,arcfour
08:02:54 info › Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
08:02:54 info › Handshake: C->S Cipher: aes128-ctr
08:02:54 info › Handshake: (local) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,aes128-ctr,aes192-ctr,aes256-ctr,blowfish-cbc,3des-cbc,arcfour256,arcfour128,arcfour
08:02:54 info › Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
08:02:54 info › Handshake: S->C cipher: aes128-ctr
08:02:54 info › Handshake: (local) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com
08:02:54 info › Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
08:02:54 info › Handshake: C->S MAC: hmac-sha2-256
08:02:54 info › Handshake: (local) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com
08:02:54 info › Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
08:02:54 info › Handshake: S->C MAC: hmac-sha2-256
08:02:54 info › Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
08:02:54 info › Handshake: (remote) C->S compression: none,zlib@openssh.com
08:02:54 info › Handshake: C->S compression: none
08:02:54 info › Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
08:02:54 info › Handshake: (remote) S->C compression: none,zlib@openssh.com
08:02:54 info › Handshake: S->C compression: none
08:02:54 info › Outbound: Sending KEXECDH_INIT
08:02:54 info › Received DH Reply
08:02:54 info › Host accepted by default (no verification)
08:02:54 info › Host accepted (verified)
08:02:54 info › Outbound: Sending NEWKEYS
08:02:54 info › Inbound: NEWKEYS
08:02:54 info › Verifying signature ...
08:02:54 info › Verified signature
08:02:54 info › Handshake completed
08:02:54 info › Outbound: Sending SERVICE_REQUEST (ssh-userauth)
08:02:54 info › Inbound: Received SERVICE_ACCEPT (ssh-userauth)
08:02:54 info › Outbound: Sending USERAUTH_REQUEST (none)
08:02:54 info › Inbound: Received USERAUTH_FAILURE (publickey)
08:02:54 info › Client: none auth failed
08:02:54 info › Outbound: Sending USERAUTH_REQUEST (publickey -- check)
08:02:54 info › Inbound: Received USERAUTH_FAILURE (publickey)
08:02:54 info › Client: publickey auth failed
08:02:54 info › Agent: No more keys left to try
08:02:54 info › Client: agent auth failed
08:02:54 info › Outbound: Sending USERAUTH_REQUEST (keyboard-interactive)
08:02:54 info › Inbound: Received USERAUTH_FAILURE (publickey)
08:02:54 info › Client: keyboard-interactive auth failed
08:02:54 error › errored terminal Error: All configured authentication methods failed
    at doNextAuth (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:803:21)
    at tryNextAuth (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:993:7)
    at USERAUTH_FAILURE (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:373:11)
    at 51 (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/protocol/handlers.misc.js:337:16)
    at Protocol.onPayload (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/protocol/Protocol.js:2025:10)
    at GenericDecipherNative.decrypt (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/protocol/crypto.js:1269:26)
    at Protocol.parsePacket [as _parse] (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:713:21)
    at Socket.emit (node:events:390:28)
08:02:54 info › Outbound: Sending DISCONNECT (11)
08:02:54 info › Socket ended
08:02:54 info › Socket closed


macos local ssh

**OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to **************** [*************] port 22.
debug1: Connection established.
debug1: identity file private.txt type -1
debug1: identity file private.txt-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3
debug1: compat_banner: match: OpenSSH_8.9p1 Ubuntu-3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to *************1:22 as 'zhou-jielei'
debug1: load_hostkeys: fopen /Users/usr0102412/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:X7CekR93q3XYCam3155VY+u+yyptNLVKHbXuR8s29yA
debug1: load_hostkeys: fopen /Users/usr0102412/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '172.22.20.51' is known and matches the ED25519 host key.
debug1: Found key in /Users/usr0102412/.ssh/known_hosts:217
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: private.txt  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com (unrecognised)
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: private.txt
Enter passphrase for key 'private.txt':
debug1: Authentication succeeded (publickey).
Authenticated to ************ ([*************]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem full
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching /Users/usr0102412/.ssh/known_hosts for ********* / (none)
debug1: client_input_hostkeys: searching /Users/usr0102412/.ssh/known_hosts2 for ******** / (none)
debug1: client_input_hostkeys: hostkeys file /Users/usr0102412/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
debug1: Remote: /usr/bin/sss_ssh_authorizedkeys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Sending environment.**

**Comment by leonunix** [comment]
[v1.22.30](https://github.com/electerm/electerm/releases/tag/v1.22.30)
fixed
