### ISSUE TITLE
增加终端Keepalive保持连接功能

### ISSUE THREAD

**Issue by mnscc** [electerm/electerm#2556]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

增加终端Keepalive保持连接功能
![image](https://user-images.githubusercontent.com/88484485/177460776-324097de-8027-4e79-ab28-41dc5b716f42.png)

**Comment by mnscc** [comment]
软件自身包含X11图像处理库

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/2998 最新版支持设为0，这个案例设为0解决了，可以试试
