### ISSUE TITLE
在ftp功能下 cmd+a 全选路径的时候，会自动复制一些不想要的内容

### ISSUE THREAD

**Issue by CoffeersJhon** [electerm/electerm#2560]
### Electerm Version(Electerm版本)

v1.21.93

### Platform detail (平台详情)

mac os arch

### What steps will reproduce the bug?(重新问题的详细步骤)

在ftp功能下 cmd+a 全选路径的时候，会自动复制一些不想要的内容，使得本来想全选清空内容重新粘贴新内容时出现问题，我未升级成这个版本的时候不会出现该问题

### What should have happened?(期望的结果)

ftp不启用自动复制的功能

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不会

### Additional information(其他任何相关信息)

应该是新代码出现了部分冲突，建议限制自动复制功能只在shell框而不是全局使用

**Comment by zxdong262** [comment]
方便描述下详细步骤吗，复现不了

**Comment by zxdong262** [comment]
我知道了，编辑器模式下
