### ISSUE TITLE
快速命令输入问题

### ISSUE THREAD

**Issue by yangqs1995** [electerm/electerm#2566]
### Electerm Version(Electerm版本)

V1.21.57

### Platform detail (平台详情)

windows x64

### What steps will reproduce the bug?(重新问题的详细步骤)

同时打开多个任务分栏时输入快速命令都会跑到第一个分栏窗口

### What should have happened?(期望的结果)

光标在那个分栏窗口，快速命令输入到那个分栏

**Comment by zxdong262** [comment]
方便在最新版确认是不是存在这个问题吗
