### ISSUE TITLE
下载更新包后提示无法在电脑上运行，请咨询软件提供者

### ISSUE THREAD

**Issue by yangqs1995** [electerm/electerm#2568]
### Electerm Version(Electerm版本)

V1.21.57

### Platform detail (平台详情)

windows x64

### What steps will reproduce the bug?(重新问题的详细步骤)

v1.21.57 升级1.21.93失败

### What should have happened?(期望的结果)

如何正常升级

**Comment by zxdong262** [comment]
下载的是tar.gz压缩包，安装一个支持压缩软件如7zip即可
