### ISSUE TITLE
书签弹窗搜索中文时会消失

### ISSUE THREAD

**Issue by flyinke** [electerm/electerm#2571]
### Electerm Version(Electerm版本)

v1.21.93

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

win11自带五笔输入法，在书签搜索框输入中文时，书签弹窗会消失，无法完成搜索。
![Video_2022-07-22_144538](https://user-images.githubusercontent.com/16532650/180380591-ea878edb-f98c-476b-b06f-66c2874187ae.gif)

### What should have happened?(期望的结果)

正常搜索

**Comment by zxdong262** [comment]
我试了一下没有复现，方便描述详细的操作顺序嘛，以及打开开发者工具看看控制台报错不

**Comment by flyinke** [comment]
好的，我先固定上
