### ISSUE TITLE
sftp编辑文件的功能bug

### ISSUE THREAD

**Issue by wcxcool** [electerm/electerm#2577]
### Electerm Version(Electerm版本)

v1.22.1

### Platform detail (平台详情)

windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.使用工具连接linux,并使用sftp的编辑文件功能，编辑配置文件时windows编码的空格无法被linux识别。
2.编辑文件功能，缩进有问题。调整代码的对齐太不友好了。

### What should have happened?(期望的结果)

希望能处理好常见字符的转换。调整好缩进。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

暂无

### Additional information(其他任何相关信息)

就这两个问题

**Comment by zxdong262** [comment]
有没有试过使用系统编辑器编辑按钮？
