### ISSUE TITLE
MacBook Pro M1 Max无法设置gitee同步

### ISSUE THREAD

**Issue by 2273267033zzz** [electerm/electerm#2578]
### Electerm Version(Electerm版本)

1.22.1

### Platform detail (平台详情)

MacOs Monterey 12.5 ,MacBook Pro M1 Max

### What steps will reproduce the bug?(重新问题的详细步骤)

最近换了电脑，发现同步功能的按钮点了没反应，
<img width="654" alt="截屏2022-07-25 14 58 41" src="https://user-images.githubusercontent.com/50507638/180717165-eafb526a-a4e8-4d67-a912-6305d76b385c.png">
红色框里的按钮点了没反应的

### What should have happened?(期望的结果)

能让我同步其他电脑的设置

**Comment by zxdong262** [comment]
最新版本引入的bug，你可以用之前版本同步之后，再使用最新版本

**Comment by 2273267033zzz** [comment]
好的，谢谢
