### ISSUE TITLE
1.22.8 版本 mac os 上无法新建的 bug

### ISSUE THREAD

**Issue by yellowlemon** [electerm/electerm#2581]
### Electerm Version(Electerm版本)

1.22.8

### Platform detail (平台详情)

mac os

### What steps will reproduce the bug?(重新问题的详细步骤)

打开界面，点击左上角的加号，报错
复现步骤：
![image](https://user-images.githubusercontent.com/6091681/180906846-b65dae9a-627d-4f6e-b75d-1d3e30eefb12.png)
出错截图：
![image](https://user-images.githubusercontent.com/6091681/180906917-b128f167-9524-43bd-b925-9597b59698ff.png)

出错了.
Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1 at JSON.parse (<anonymous>) at http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1872197 at Proxy.map (<anonymous>) at Proxy.get sshConfigItems (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1872184) at Object.t.runAndMonitor (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1026171) at Object.sshConfigItems (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1026450) at Object.get (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1021099) at Is.render (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1702765) at Function.t.runAndMonitor (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:1026171) at Is.render (http://127.0.0.1:30974/js/electerm.js?1.22.8:2:840591)

### What should have happened?(期望的结果)

打开界面，点击左上角的加号，能够正常展示功能

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

未使用其他同类软件

### Additional information(其他任何相关信息)

暂无

**Comment by zxdong262** [comment]
鼠标指向➕的下拉菜单里的新建连接点击也是一样吗

**Comment by yellowlemon** [comment]
我描述错误了，应该是指向加号就报这个错误
我现在回退到 1.22.1 版本了，没有问题

**Comment by zxdong262** [comment]
mac os 什么版本，下载的是是mac-arm吗

**Comment by yellowlemon** [comment]
mac版本：
![image](https://user-images.githubusercontent.com/6091681/180945434-34f503bd-9780-479d-b0c8-fabe7379b5f0.png)
下载软件包名：
electerm-1.22.8-mac-x64.dmg

**Comment by strive1216** [comment]
我也是一样 M1   鼠标悬停到对应位置就报错  Unexpected token o in JSON at position 1

**Comment by strive1216** [comment]
> 

补充：双击顶栏可以新建，悬停左侧书签也报错，

**Comment by zxdong262** [comment]
可以试下删除数据吗 `rm -rf ~/Library/Application\ Support/electerm*` 然后打开看看（注意这会删除所有数据）

**Comment by zxdong262** [comment]
@strive1216 @yellowlemon 我知道了，是读取ssh-config部分有bug导致的，临时解决方案是用旧版或者删除`~/.ssh/config`,将在下个版本修复

**Comment by yellowlemon** [comment]
OK，那我先用旧版，待新版本在更新，麻烦了
