### ISSUE TITLE
升级v1.22.8后不能查看服务器信息了。

### ISSUE THREAD

**Issue by imic07** [electerm/electerm#2585]
### Electerm Version(Electerm版本)

v1.22.8

### Platform detail (平台详情)

5.10.131-1-MANJARO   x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

以前登录远程后，右下角有一个i图标，可以查看服务器的一些信息。升级后没有了。

### What should have happened?(期望的结果)

有查看远程服务器信息的功能

**Comment by zxdong262** [comment]
在最新版修复了
