### ISSUE TITLE
有些文件如.log文件右键编辑、查看不了

### ISSUE THREAD

**Issue by LiFuHai1106** [electerm/electerm#2590]
### Electerm Version(Electerm版本)

Mac m1-1.22.20

### Platform detail (平台详情)

mac m1

### What steps will reproduce the bug?(重新问题的详细步骤)

有些文件如.log文件右键编辑、查看不了

### What should have happened?(期望的结果)

有些文件如.log文件右键可以编辑、查看

**Comment by zxdong262** [comment]
目前有个大小限制，太大的文件不支持直接打开，你可以下载之后用合适的工具编辑处理

**Comment by francisLee777** [comment]
> 目前有个大小限制，太大的文件不支持直接打开，你可以下载之后用合适的工具编辑处理

为什么要有这个限制？而且限制的非常小，实测 100KB左右

**Comment by zxdong262** [comment]
> > 目前有个大小限制，太大的文件不支持直接打开，你可以下载之后用合适的工具编辑处理
> 
> 为什么要有这个限制？而且限制的非常小，实测 100KB左右

我之前考虑本质上也是下载到本地临时目录再编辑，如果太大的话，下载耗时太长体验不好，但是现在我觉得可以通过给出下载进度的方式提高体验，也就不必要限制大小
