### ISSUE TITLE
Mac version icon adaptation

### ISSUE THREAD

**Issue by ShineYangGod** [electerm/electerm#2592]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

I hope the Mac version can adapt to the icon of the big sur version

**Comment by zxdong262** [comment]
Can you provide screenshot?

**Comment by ShineYangGod** [comment]
<img width="197" alt="截屏2022-08-03 08 12 35" src="https://user-images.githubusercontent.com/19811314/182497606-93324739-ae4f-45e0-a9e1-4d66a98b5db3.png">

I hope it can be adapted to such an icon, in line with the Big Sure system style

**Comment by zxdong262** [comment]
Can you explain what is Big sur system style? Square icon?

**Comment by ShineYangGod** [comment]
yes, rounded rectangle

**Comment by ShineYangGod** [comment]
<img width="1999" alt="截屏2022-08-17 14 34 19" src="https://user-images.githubusercontent.com/19811314/185051412-bb6432fa-8701-4703-8195-4659295de6e5.png">
Hello, I get this error when I click the add window in the application on the Mac
