### ISSUE TITLE
创建书签分类后没有立即展示

### ISSUE THREAD

**Issue by cliveyuan** [electerm/electerm#2597]
### Electerm Version(Electerm版本)

1.22.20

### Platform detail (平台详情)

mac os(x64)

### What steps will reproduce the bug?(重新问题的详细步骤)

创建书签分类后没有立即展示，需要重启才会显示

### What should have happened?(期望的结果)

创建书签后立即展示

**Comment by zxdong262** [comment]
最新版已经修复
