### ISSUE TITLE
2048位密钥ssh登录oracle cloud认证失败

### ISSUE THREAD

**Issue by FourLeafTec** [electerm/electerm#2598]
### Electerm Version(Electerm版本)

1.22.24

### Platform detail (平台详情)

windows 11 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 使用ssh-keygen -t rsa -b 2048创建密钥对
2. 使用刚创建得密钥对创建oracle cloud ubuntu22.04实例
3. SSH连接测试认证失败
4. 保存并连接弹出密码输入框，无法登入

### What should have happened?(期望的结果)

认证成功

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能重现，使用 ssh -i <key_file> user@ip 能够成功登入

### Additional information(其他任何相关信息)

4096位密钥登入其他服务商的服务器一直能够成功，登入oracle cloud的服务器依然失败

**Comment by zxdong262** [comment]
Ed25519格式的可以吗？

**Comment by FourLeafTec** [comment]
Ed25519可以

**Comment by zxdong262** [comment]
1.22.20 可以试一下吗

**Comment by FourLeafTec** [comment]
1.22.20 同样是Ed25519可以，rsa不行

**Comment by zxdong262** [comment]
22.30可以试试吗
