### ISSUE TITLE
连接上H3C交换机几秒之后就提示终端连接丢失

### ISSUE THREAD

**Issue by h605290713** [electerm/electerm#2604]
### Electerm Version(Electerm版本和后缀.deb, .rpm...)

exe

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

连接上H3C交换机几秒之后就提示终端连接丢失

### What should have happened?(期望的结果)

希望能修复

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

xshell 没有问题

**Comment by zxdong262** [comment]
可以试试设置里keepalive间隔设置短一点，看看有效果吗

**Comment by h605290713** [comment]
改到1000了 还是这样 几秒就断了

**Comment by wpf973** [comment]
> 改到1000了 还是这样 几秒就断了

改为0 或者升级新版本
