### ISSUE TITLE
打开Electerm 出现BUG（提示终端连接失败、重连后Cannot set properties of undefined (setting 'onclose')）

### ISSUE THREAD

**Issue by Long-Tu** [electerm/electerm#2607]
### Electerm Version(Electerm版本和后缀.deb, .rpm...)

Electerm Version 1.22.30

### Platform detail (平台详情)

Windows 10 专业版 21H2 内部版本（19044.1889）

### What steps will reproduce the bug?(重新问题的详细步骤)

# 1、electerm打开后提示终端连接失败
![图片](https://user-images.githubusercontent.com/37840939/184783859-8dffa955-6e05-4ca3-b7b1-ec24e59bfbca.png)

# 2、重新连接报错
error
Cannot set properties of undefined (setting 'onclose')
![图片](https://user-images.githubusercontent.com/37840939/184783889-3d1e34cd-a241-4519-8eed-702bd16a267d.png)

### What should have happened?(期望的结果)

# 正常远程连接远程机器

**Comment by zxdong262** [comment]
可以命令行运行看看什么输出吗

**Comment by Long-Tu** [comment]
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ZHAO ***@***.***>
发送时间: 2022年8月16日 11:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [electerm/electerm] 打开Electerm 出现BUG（提示终端连接失败、重连后Cannot set properties of undefined (setting 'onclose')） (Issue #2607)


可以命令行运行看看什么输出吗

―

**Comment by Long-Tu** [comment]
![图片](https://user-images.githubusercontent.com/37840939/184806316-c842561b-78de-4268-8920-e07b9479a1cc.png)

**Comment by zxdong262** [comment]
> ![图片](https://user-images.githubusercontent.com/37840939/184806316-c842561b-78de-4268-8920-e07b9479a1cc.png)

看起来是没有权限运行 node-font-list-fonts.vbs, 管理员权限运行可以吗

**Comment by Long-Tu** [comment]
![图片](https://user-images.githubusercontent.com/37840939/184813140-d2804253-3b47-4471-89b9-b2fd8e613288.png)

**Comment by Long-Tu** [comment]
这个使用管理员还是同样报错

**Comment by zxdong262** [comment]
下载的是哪个文件呢? tar.gz？

**Comment by Long-Tu** [comment]
electerm-1.22.30-win-x64-installer.exe

**Comment by Long-Tu** [comment]
安装选择的是全部账户进行安装的，这个会不会影响到文件的访问权限

**Comment by zxdong262** [comment]
> 安装选择的是全部账户进行安装的，这个会不会影响到文件的访问权限

我没有试过这种方式，可以试试tar.gz包吗

**Comment by zxdong262** [comment]
> 安装选择的是全部账户进行安装的，这个会不会影响到文件的访问权限

试了一下，应该不是这个问题

**Comment by Long-Tu** [comment]
使用tar.gz绿色安装使用正常

**Comment by Long-Tu** [comment]
![图片](https://user-images.githubusercontent.com/37840939/184839092-e58e566a-92e3-4ceb-83dd-a30673b61b18.png)
