### ISSUE TITLE
I don't maintain SubX any more

### ISSUE THREAD

**Issue by tylerlong** [electerm/electerm#2612]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

I see you forked SubX, but I am not maintaining it any more.

I created https://github.com/tylerlong/use-proxy which I believe is a better solution.

Here is a working demo: https://github.com/tylerlong/use-proxy-demo-todomvc/blob/main/src/store.ts

I also have lots of private projects based on use-proxy. Let me know if you need more projects for reference and I will add you as collaborator.

Tyler

**Comment by zxdong262** [comment]
Great! Seems it is just what I need! Would try it!

**Comment by tylerlong** [comment]
[tylerlong/use-proxy](https://github.com/tylerlong/use-proxy) 最大的特色是可以以 **纯 OOP** 的风格去维护 state。

我有一个electron-apps 的私有项目，加你为collaborator 了。 你能访问后可以参考 apps/icon-composer 这个项目的实现。 
那个项目的可执行文件可以在这下载： https://github.com/tylerlong/icon-composer-app/releases
