### ISSUE TITLE
MFA认证如果不输入任何信息点击提交，打开相同地址标签会报错：Cannot set properties of undefined (setting 'onclose')

### ISSUE THREAD

**Issue by lswandt** [electerm/electerm#2622]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.22.30-mac-arm64.dmg

### Platform detail (平台详情)

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?(重新问题的详细步骤)

MFA认证的ssh，在maf输入框中直接点击提交。会导致所有的窗口无法使用；同时，打开新的标签 会提示：Cannot set properties of undefined (setting 'onclose')

### What should have happened?(期望的结果)

这也许是个bug

**Comment by zxdong262** [comment]
输入错误mfa提交是同样情况吗？

**Comment by lswandt** [comment]
> 输入错误mfa提交是同样情况吗？

不是，提交错误的mfa会提示输入密码，这个逻辑看起来是正常的
