### ISSUE TITLE
version of 1.22.33 can not save settings

### ISSUE THREAD

**Issue by ygrdsj** [electerm/electerm#2630]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.22.33-mac-arm64.dmg

### Platform detail (平台详情)

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?(重新问题的详细步骤)

After the electerm restarts, the previous settings will be lost and restored to the default state

### What should have happened?(期望的结果)

Can save the settings

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

This problem does not occur in version 1.21.x (I forgot which version specifically). This problem occurs after updating to version 1.22.33

**Comment by zxdong262** [comment]
How about 1.22.30? can you try it?

**Comment by zxdong262** [comment]
Also can you provide more detail which setting can not be saved or all settings? How about bookmarks? Would new bookmark would be saved?

**Comment by ygrdsj** [comment]
I tested it just now. The 1.22.30 version doesn't have this problem.

**Comment by zxdong262** [comment]
should be fixed in latest release
