### ISSUE TITLE
mac1.23版本设置出现问题

### ISSUE THREAD

**Issue by Sentiger** [electerm/electerm#2635]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.23

### Platform detail (平台详情)

mac 

### What steps will reproduce the bug?(重新问题的详细步骤)

1.23版本在设置的时候出现覆盖问题
1. 先设置无背景图
2. 退出然后设置bin的路径
3. 发现第一次设置的背景图又恢复默认的了，其他的设置也是一样

### What should have happened?(期望的结果)

期待本地设置不被覆盖

**Comment by jiayouzl** [comment]
我靠,我刚更新也碰到这个bug了,这软件bug是真的真的太多了.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/0a4d25211f2041e3bb2c17a11a49c6eb46832bfa
