### ISSUE TITLE
win1.23设置bug

### ISSUE THREAD

**Issue by wylsgame** [electerm/electerm#2636]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.2-win-x64-installer.exe

### Platform detail (平台详情)

win11 

### What steps will reproduce the bug?(重新问题的详细步骤)

设置字体报错

### What should have happened?(期望的结果)

修复bug

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

现安装1.22.33无此问题

**Comment by jiayouzl** [comment]
设置字体报错
+1

我也碰到了

**Comment by wylsgame** [comment]
ths

ZHAO Xudong ***@***.***> 于2022年9月19日周一 16:54写道：
