### ISSUE TITLE
1.23.2 macos10.15.7版本 全屏幕快捷键失效 control+command+f

### ISSUE THREAD

**Issue by ArexdOr** [electerm/electerm#2638]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electrm-1.23.2-mac-arm64.dmg

### Platform detail (平台详情)

macos 10.15.7

### What steps will reproduce the bug?(重新问题的详细步骤)

全屏幕快捷键失效 control+command+f

### What should have happened?(期望的结果)

放大窗口到全屏幕

**Comment by zxdong262** [comment]
之前版本可以吗？

**Comment by ArexdOr** [comment]
> 之前的版本可以吗？

之前版本都不行，我这偶然发现的

**Comment by zxdong262** [comment]
将在下个版本增加alt+f切换全屏快捷键，同时可以自定义设置快捷键
