### ISSUE TITLE
1.23.3配置无法保存

### ISSUE THREAD

**Issue by 1nfin1ty** [electerm/electerm#2639]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.23.3

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

重启软件之后设置失效

### What should have happened?(期望的结果)

正常保存设置

**Comment by zxdong262** [comment]
请问哪个设置还是任何设置，书签也会丢失吗？

**Comment by zxdong262** [comment]
可以试试删除`%APPDATA%\electerm`之后的情况吗

**Comment by jiayouzl** [comment]
> 可以试试删除`%APPDATA%\electerm`之后的情况吗

我特意在我专门用过测试的macos虚拟主机上测试过,这台主机从来没安装过你们的软件,一样出现配置无法保存的问题!

**Comment by 1nfin1ty** [comment]
> 请问哪个设置还是任何设置，书签也会丢失吗？

书签没有丢失，同时设置字号和字体重启之后失效，设置ui主题也是重启之后失效

**Comment by 1nfin1ty** [comment]
> 可以试试删除`%APPDATA%\electerm`之后的情况吗

似乎一样有问题，而且会重置所有设置
