### ISSUE TITLE
Mac版本，点击Command+F搜索，在输入框输入字符时，会自动复制搜索到的内容！！！

### ISSUE THREAD

**Issue by zqxsober** [electerm/electerm#2640]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.4-mac-x64.dmg

### Platform detail (平台详情)

mac os x64

### What steps will reproduce the bug?(重新问题的详细步骤)

点击Command+F搜索，在输入框输入字符时，会自动复制搜索到的内容！！！
![WechatIMG133](https://user-images.githubusercontent.com/33095205/191684513-580e12c8-9b4f-40b6-af4a-c14f1762d4d9.png)

### What should have happened?(期望的结果)

尽快修复搜索功能，在使用搜索功能时，希望鼠标光标自动移动到搜索框内

**Comment by jiayouzl** [comment]
我也发现这个问题.

**Comment by zxdong262** [comment]
fixed in latest release
