### ISSUE TITLE
批量输入地方的历史记录如何删除?

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2643]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

就这个地方,如何删除?软件内没找到地方,或者清空.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/7685337/192093082-b203d279-f7e6-483b-8782-2a4a992fb17c.png">

**Comment by zxdong262** [comment]
下个版本加入
