### ISSUE TITLE
 why is there nothing about tunnel ssh?

### ISSUE THREAD

**Issue by caicob** [electerm/electerm#2652]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

I found the tool very good, but I didn't find anything about tunnel ssh, do you have any predictions for this feature?

**Comment by zxdong262** [comment]
In todo list for sure, just no solid plan.

**Comment by zxdong262** [comment]
Supported in latest release

**Comment by frankterm** [comment]
能给一个配置的例子吗

**Comment by zxdong262** [comment]
> 能给一个配置的例子吗

https://github.com/electerm/electerm/wiki/how-to-use-ssh-tunnel
