### ISSUE TITLE
默认窗口是本机命令，是否可以设置默认为空窗口？

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2653]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

第一现在这样经常会命令输错地方，第二每次启动先关默认窗口也很不方便啊。

**Comment by zxdong262** [comment]
设置里可以设置启动打开书签

**Comment by jiayouzl** [comment]
> 设置里可以设置启动打开书签

我看了只能设置打开那个服务器,我在想能不能加个默认空白页.
