### ISSUE TITLE
【选中复制】标签添加的输入框中全选时会选中终端的内容

### ISSUE THREAD

**Issue by cliveyuan** [electerm/electerm#2660]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.8-mac-x64.dmg

### Platform detail (平台详情)

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

前提：开启选中自动复制功能
<img width="676" alt="image" src="https://user-images.githubusercontent.com/33131649/194838724-70eb7bef-668e-41f5-a8e2-08abd9b5be74.png">

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/33131649/194838568-b2e1bebd-2c23-4f7c-9851-d3621676548d.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/33131649/194838832-5a2da69c-8730-4013-abab-767ad424439b.png">

### What should have happened?(期望的结果)

选中书签输入框的内容，不要去选中终端的内容

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否

**Comment by zxdong262** [comment]
可以试试最新版吗
