### ISSUE TITLE
sftp无法处理无效的软链接

### ISSUE THREAD

**Issue by SamThicker** [electerm/electerm#2661]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

v1.23.8  mac-x64dmg && win-x64-installer.exe

### Platform detail (平台详情)

MacOS12.4 & Windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

当文件夹中包含一个指向不存在文件的软链接，sftp浏览窗口访问开该文件夹时提示 NO SUCH FILE。我从他人的tar包中把文件解压出来，发现有个文件夹无法访问，右下角弹窗提示“NO SUCH FILE”，起初怀疑与操作系统有关，实则不然。从ssh ls -l结果发现该文件夹中包含一个软链接指向一个我本地不存在的文件，于是把该软链接删除，可正常访问文件夹。重试，问题可复现。

### What should have happened?(期望的结果)

正常处理无效的软链接。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其它软件如MobaXterm, winscp无该问题。

**Comment by zxdong262** [comment]
dup
