### ISSUE TITLE
刚重装了下系统后恢复了下,提示错误,谢谢~

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2663]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

最新

### Platform detail (平台详情)

macos

### What steps will reproduce the bug?(重新问题的详细步骤)

已经设置/bin/zsh了,为啥还提示?~
<img width="789" alt="image" src="https://user-images.githubusercontent.com/7685337/195817113-c385dd64-c3d6-4ce6-91dd-93d19e46c57f.png">

### What should have happened?(期望的结果)

1234

**Comment by zxdong262** [comment]
需要在electerm的设置里设为zsh
