### ISSUE TITLE
Sftp无法前往服务器根目录

### ISSUE THREAD

**Issue by black-zero358** [electerm/electerm#2664]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.15-win-x64-installer.exe

### Platform detail (平台详情)

windows 10 64位

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://user-images.githubusercontent.com/53086059/195975123-9d8bdec5-52e7-4669-be17-303f7e3f7ff7.png)
进入sftp页面默认打开/root路径，在路径栏里输入"/"再回车便会报错

### What should have happened?(期望的结果)

No such file
Error: No such file
    at http://127.0.0.1:30974/js/electerm.js?1.23.15:2:1465616
    at Object.resolve (http://127.0.0.1:30974/js/electerm.js?1.23.15:2:1415120)
    at Worker.<anonymous> (http://127.0.0.1:30974/js/electerm.js?1.23.15:2:1416050)

### Additional information(其他任何相关信息)

但是如果在地址栏输入/usr之类的路径便可以访问根目录下的其他文件

**Comment by zxdong262** [comment]
从`/root`点击向上箭头可以到`/`吗？
