### ISSUE TITLE
在单台PC上启动多个进程时，提示端口被占用

### ISSUE THREAD

**Issue by DachuanXUAN** [electerm/electerm#2667]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.8-win-x64-installer

### Platform detail (平台详情)

Windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

在同一台 PC 上启动多个进程提示窗口被占用，即使在 Windows 上的不同用户也会这样

### What should have happened?(期望的结果)

在同一台 PC 上可以启动多个进程

**Comment by zxdong262** [comment]
非安装版本，可以试试吗 tar.gz那个
