### ISSUE TITLE
sftp 拖拽不能下载

### ISSUE THREAD

**Issue by k2jiaozi** [electerm/electerm#2672]
SFTP拖拽可以上传,不可以下载.右键下载正常

**Comment by zxdong262** [comment]
方便按模板填写一下吗？

**Comment by k2jiaozi** [comment]
> 方便按模板填写一下吗？

Electerm Version and download file extension(Electerm版本和下载文件后缀)
v1.23.20 v1.23.22 win-x64-installer.exe

Platform detail (平台详情)
win10 21h2 专业版 X64

What steps will reproduce the bug?(重新问题的详细步骤)
问题描述：链接SSH后,点击顶部SFTP标签,右边服务端目录拖拽文件到本地目录,显示一直在传输中,速度为0.右键服务端目录点下载,可以正常下载完成.拖拽文件上传可以完成
