### ISSUE TITLE
批量输入框 拖动超过边界

### ISSUE THREAD

**Issue by MaxKingPor** [electerm/electerm#2675]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.22-win-x64.tar.gz

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

点击拖后会超过外边界, 在超出边界后松开无法恢复,需要重启
![image](https://user-images.githubusercontent.com/43533178/197930803-de6088cb-cf41-4a92-845f-b721ef1212c5.png)

### What should have happened?(期望的结果)

向上拖动 或者 其他???

**Comment by strive1216** [comment]
[1.23.28](https://github.com/electerm/electerm/releases/tag/v1.23.28)  这版 修改为普通文本输入框后，长命令行自动换行后 无法使用上下键(ps.与历史记录选择框冲突)进行修改，只能使用左右键。
