### ISSUE TITLE
Installing via snapcraft fails to open on a WSL instance with systemd turned on

### ISSUE THREAD

**Issue by linghengqian** [electerm/electerm#2678]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.22-linux-amd64.snap

### Platform detail (平台详情)

Linux DESKTOP-L90K6GN 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

- Install via snapcraft after making sure `Ubuntu 22.04` has built-in support for systemd turned on in `/etc/wsl.conf`.
```shell
sudo snap install electerm --classic
electerm
```
- There is an error log this time.
```shell
lingh@DESKTOP-L90K6GN:~$ electerm
/snap/electerm/227/electerm: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
lingh@DESKTOP-L90K6GN:~$ electerm
/home/lingh/Desktop was removed, reassigning DESKTOP to homedir
/home/lingh/Downloads was removed, reassigning DOWNLOAD to homedir
/home/lingh/Templates was removed, reassigning TEMPLATES to homedir
/home/lingh/Public was removed, reassigning PUBLICSHARE to homedir
/home/lingh/Documents was removed, reassigning DOCUMENTS to homedir
/home/lingh/Music was removed, reassigning MUSIC to homedir
/home/lingh/Pictures was removed, reassigning PICTURES to homedir
/home/lingh/Videos was removed, reassigning VIDEOS to homedir
lingh@DESKTOP-L90K6GN:~$ electerm
lingh@DESKTOP-L90K6GN:~$ electerm
```
- ![image](https://user-images.githubusercontent.com/20187731/198828794-9b68ba45-160b-4be1-b6b3-0523b1cd090a.png)
- I have tried to open it multiple times, but no new window pops up.

### What should have happened?(期望的结果)

- Normal start.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

- No problem with gedit and gimp installed via snapcraft.

### Additional information(其他任何相关信息)

- Null.

**Comment by linghengqian** [comment]
- I recreated a new WSL instance and got the same log, looks like I'm reporting the wrong place. 😂This seems strongly related to WSLg, but I'm not sure which missing `.so` files should be reported to https://github.com/microsoft/wslg , is there anything I can use for reference?
```shell
lingh@DESKTOP-L90K6GN:/tmp$ sudo apt install ./electerm-1.23.22-linux-amd64.deb

lingh@DESKTOP-L90K6GN:/tmp$ electerm
electerm: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
lingh@DESKTOP-L90K6GN:/tmp$ electerm
electerm: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
lingh@DESKTOP-L90K6GN:/tmp$
```
- ![image](https://user-images.githubusercontent.com/20187731/198864201-7688b417-c21e-430c-bb03-a2e2ce571a7c.png)

**Comment by zxdong262** [comment]
Unfortnately I have no idea, never tried running in wsl myself @linghengqian

**Comment by linghengqian** [comment]
- Thanks for your reply! I'll close this issue and try to report it on the wslg side shortly.
