### ISSUE TITLE
背景设置后模糊

### ISSUE THREAD

**Issue by qing-root** [electerm/electerm#2680]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

mac m1 macos13

### What steps will reproduce the bug?(重新问题的详细步骤)

背景设置后很模糊：不知道为什么设置了背景非常模糊背景
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/30001685/199156019-4d47cb67-658d-41e5-b2b1-925043585587.png">

### What should have happened?(期望的结果)

有什么设置或者方法可以使背景更清晰吗？以前用老版本的时候就很清晰的。

**Comment by zxdong262** [comment]
设置里有个blur默认值应为0，实际为1，这是个bug，你可以通过设置为0恢复清晰，下个版本修复

**Comment by qing-root** [comment]
> 设置里有个blur默认值应为0，实际为1，这是个bug，你可以通过设置为0恢复清晰，下个版本修复

感谢 有效
