### ISSUE TITLE
可以支持粘贴当前选中内容的功能吗？

### ISSUE THREAD

**Issue by vdisk-group** [electerm/electerm#2684]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

类似 xshell 的 alt + insert 的功能，可以不用经过剪贴板，直接将选中的内容粘贴到当前的输入光标下

**Comment by zxdong262** [comment]
设置里有个自动复制选中内容，可以试试是不是你需要的

**Comment by vdisk-group** [comment]
> 设置里有个自动复制选中内容，可以试试是不是你需要的

这个不是我想要的，我希望的是可以不通过剪贴板直接粘贴所选内容。
大致的使用场景是这样的
1. 当前我的剪贴板上复制了一个待搜索的关键字
2. 使用 ls -l 列出当前目录下是所有文件
3. 使用 less 命令来打开某个文件
4. 在 less 中使用剪贴板上复制的关键字进行搜索

我希望在第3步的时候能够通过选中文件名之后按下某个快捷键，直接将我选中的文件名直接粘贴到 less 命令后面，但是不要覆盖我的剪贴板，这样我在进行第4步操作的时候就可以直接使用我之前复制的关键字了。

具体的操作体验的话就是
1. 输入 less + 空格
2. 鼠标选中文件名
3. 按下快捷键(粘贴文件名到 less 后面)
4. 按下回车(使用 less 打开该文件)
