### ISSUE TITLE
连接IBM AIX  backspace按键问题

### ISSUE THREAD

**Issue by fanmasoft** [electerm/electerm#2695]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows 7/10

### What steps will reproduce the bug?(重新问题的详细步骤)

连接IBM AIX  backspace按键问题

1.连接IBM AIX（我的环境是AIX 6.1），在命令行下无法使用backspace键，按下会显示^?
2.在编辑器里面也无法使用backspace键，按下没有反应。

### What should have happened?(期望的结果)

兼容IBM AIX系统

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其他同类软件上暂时还没发现有类似问题

**Comment by zxdong262** [comment]
删除键正常吗？

**Comment by fanmasoft** [comment]
DEL键也不正常。。。。按删除键会切换大小写。。。在其他Shell工具上正常。。我把源码clone下来了。折腾一天。。也能正常编译了。。。就是技术水平一般。。。没找到原因。

**Comment by zxdong262** [comment]
可以试试其他终端类型吗，设置里

**Comment by fanmasoft** [comment]
好的，我今天尝试一下所有的终端类型。。。这个问题是ssh2模块的问题吗？

**Comment by zxdong262** [comment]
> 好的，我今天尝试一下所有的终端类型。。。这个问题是ssh2模块的问题吗？

我也不清楚，似乎更可能是xtermjs的问题

**Comment by fanmasoft** [comment]
所有终端类型我全测试了。。。主要测试了backspace按键和del按键。。其他没测。结果如下
1.终端类型xterm-256color
命令行 backspace 键输出 ^? DEL切换大小写   VIM编辑器中 backspace键 输出 ^? DEL正常
2.终端类型xterm-new
命令行 backspace 键输出 ^? DEL切换大小写   VIM编辑器中 backspace键 输出 ^? DEL正常
3.xterm-color
命令行 backspace 键输出 ^? DEL切换大小写    VIM编辑器中 backspace键 无响应 DEL正常
4.xterm-vt220
命令行 backspace 键输出 ^? DEL切换大小写    VIM编辑器中 backspace键 输出 ^?  DEL正常
5.xterm
命令行 backspace 键输出 ^? DEL切换大小写    VIM编辑器中 backspace键 输出 ^?  DEL正常
6.linux
命令行 backspace 键无响应 	DEL切换大小写	VIM编辑器中 backspace键 从光标所在位置往后删除跟DEL一样 DEL切换大小写
7.vt100
命令行 backspace 键输出 ^?	DEL切换大小写	VIM编辑器中 backspace键 在中间能删除 在行尾删除不了  DEL切换大小写
8.ansi
命令行 backspace 键输出 ^?	DEL切换大小写	VIM编辑器中 backspace键 从光标所在位置往后删除跟DEL一样 DEL切换大小写
9.rxvt
命令行 backspace 键输出 ^?	DEL切换大小写	VIM编辑器中 backspace键 从光标所在位置往后删除跟DEL一样 DEL正常

**Comment by fanmasoft** [comment]
我测试了另外一款web terminal也这样   软件名【Aechoterm】
效果一模一样。。估计就是这个xtermjs的问题

**Comment by fanmasoft** [comment]
我在[xterm.js](https://github.com/xtermjs/xterm.js) 项目下提问了。。
https://github.com/xtermjs/xterm.js/issues/4278

有人提出了解决方案，作者修改了。
https://github.com/xtermjs/xterm.js/pull/4280/commits/6b09c1b576609e6f2dc2f70b9e1a57b4ccea0467

**Comment by fanmasoft** [comment]
@zxdong262 我英文不是很好，用中文提问的，麻烦您帮忙给看一下，他解决的是我遇到的问题吗？

**Comment by zxdong262** [comment]
> @zxdong262 我英文不是很好，用中文提问的，麻烦您帮忙给看一下，他解决的是我遇到的问题吗？

样例代码似乎是加一个检测，按shift+退格，就转化为输出删除，似乎并没有从根源解决问题

**Comment by zxdong262** [comment]
最新版已经解决
