### ISSUE TITLE
能否支持SFTP目录与SSH终端所在路径同步

### ISSUE THREAD

**Issue by TTT-TD** [electerm/electerm#2696]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

某同类型项目Tab**支持以添加环境变量`export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'`的方式实现SSH与SFTP路径同步。如果electerm在不另设环境变量的前提下实现该功能会很棒

**Comment by zxdong262** [comment]
将在下个版本加入，无需添加环境变量的解决方案

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/2616

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/2310
