### ISSUE TITLE
SFTP在使用socks5代理的情况下直接报错断连，重复多次

### ISSUE THREAD

**Issue by kele2016** [electerm/electerm#2702]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.23.32-win-x64-installer.exe

### Platform detail (平台详情)

Windows 11 专业版 21H2

### What steps will reproduce the bug?(重新问题的详细步骤)

socks5连接的SSH，只要打开SFTP标签，必然崩溃。
[img]https://monose.net/2022/12/03/1.jpg[/img]
[img]https://monose.net/2022/12/03/2.jpg[/img]
报错信息内容如下：
(SSH) Channel open failure: open failed
Error: (SSH) Channel open failure: open failed at http://127.0.0.1:30974/js/electerm.js?1.23.32:2:1465855 at Object.resolve (http://127.0.0.1:30974/js/electerm.js?1.23.32:2:1415120) at Worker.<anonymous> (http://127.0.0.1:30974/js/electerm.js?1.23.32:2:1416050)

### What should have happened?(期望的结果)

socks5连接的SSH，能正常使用SFTP

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能

**Comment by zxdong262** [comment]
是sock5代理？我试了一下是可以的，你有没有其他ssh可以测试一下的？

**Comment by kele2016** [comment]
我用xshell试了下，也存在不能连接的问题，应该是服务端设置的。不好意思。
