### ISSUE TITLE
希望可以在arm64位的Linux上使用

### ISSUE THREAD

**Issue by wxtewx** [electerm/electerm#2710]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

希望可以在arm64位的Linux上使用

**Comment by GreatHaop** [comment]
Gonna open the same issue

**Comment by baozitao** [comment]
+1,非常希望

**Comment by xiuyuanxm** [comment]
+1

**Comment by zxdong262** [comment]
目前还没有找到合适的开源构建服务

**Comment by xiuyuanxm** [comment]
+1,非常希望

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm-web

**Comment by xiuyuanxm** [comment]
> 可以试试 https://github.com/electerm/electerm-web

非常感谢！
