### ISSUE TITLE
同步功能存在问题

### ISSUE THREAD

**Issue by bambooqj** [electerm/electerm#2711]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.18363.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

终端文件管理器
批量输入
编码
Error invoking remote method 'async': Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
Error: Error invoking remote method 'async': Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT at EventEmitter.o.invoke (node:electron/js2c/renderer_init:57:526) at async Proxy.e.downloadSetting (http://127.0.0.1:30974/js/electerm.js?1.24.13:2:1777407)

大概七个月前上传的，现在看代码好像是解密不了。。不理解为啥。。

### What should have happened?(期望的结果)

还原

**Comment by zxdong262** [comment]
token是一样的吗，两次都点了加密设置吗？

**Comment by bambooqj** [comment]
之前token忘记了。。重置了一下。。id是一致的。解密密码用的token的话。。我是不是找不回来了。。

**Comment by zxdong262** [comment]
> 之前token忘记了。。重置了一下。。id是一致的。解密密码用的token的话。。我是不是找不回来了。。

那找不回来了。。。

**Comment by bambooqj** [comment]
这个地方后期能否修改下，主要，token token不一定一直能留着。。
