### ISSUE TITLE
新增书签、快速命令手工排序功能

### ISSUE THREAD

**Issue by liumingxiyou** [electerm/electerm#2714]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

1、目前书签和快速命令的顺序都是按照添加时的先后顺序排列且无法手工重新排序
2、例如快速命令，当新填一个快速命令后，经常需要调整其顺序，将其和原先已有的某个历史命令排放在一起。

**Comment by jiayouzl** [comment]
这个功能很重要!排序.

**Comment by aogg** [comment]
还有快捷命令分组功能

**Comment by imic07** [comment]
排序是刚需，希望能够安排上

**Comment by hwlts** [comment]
书签（组）和快捷命令的排序功能真的很需要！希望能早点支持！

**Comment by zxdong262** [comment]
#3167

**Comment by zxdong262** [comment]
将在下个版本加入
