### ISSUE TITLE
npm start后，打开页面怎么一直只有图标的

### ISSUE THREAD

**Issue by aogg** [electerm/electerm#2720]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

git clone https://github.com/electerm/electerm

### Platform detail (平台详情)

alpine

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://user-images.githubusercontent.com/8998031/210341971-3ede71b9-2aac-4f2a-921a-d834ee4cf2d8.png)

### What should have happened?(期望的结果)

无法打开首页

**Comment by aogg** [comment]
basic.jsx:32 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'packInfo')
    at loadScript (basic.jsx:32:46)
    at load (basic.jsx:46:3)

**Comment by zxdong262** [comment]
不支持浏览器运行
