### ISSUE TITLE
version 1.25.6 has no macOS codesignature

### ISSUE THREAD

**Issue by core-code** [electerm/electerm#2729]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.6-mac-x64.dmg

### Platform detail (平台详情)

Darwin iMac27 21.6.0 Darwin Kernel Version 21.6.0

### What steps will reproduce the bug?(重新问题的详细步骤)

download electerm

### What should have happened?(期望的结果)

electerm should be properly code-signed like all previous releases with

Developer ID: Xudong ZHAO (38ZYC7L6N5)

### Additional information(其他任何相关信息)

previous releases were properly codesigned, but 1.25.6 is unsigned

**Comment by zxdong262** [comment]
1.25.10 fixed

**Comment by core-code** [comment]
confirmed fixed, thanks!
