### ISSUE TITLE
搞什么啊?最新版压根无法打开????

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2730]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.6-mac-arm64

### Platform detail (平台详情)

macos

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="390" alt="image" src="https://user-images.githubusercontent.com/7685337/212088587-08355af0-5626-4e18-96dd-cbcdb2a39878.png">

### What should have happened?(期望的结果)

electerm-1.25.6-mac-arm64

**Comment by zxdong262** [comment]
可以重新下载试试吗，以及可以试试x64版本吗？

**Comment by zxdong262** [comment]
可能是签名失败导致的。

**Comment by chaselen** [comment]
一样。。

**Comment by zxdong262** [comment]
下个版本修复，包括签名问题

**Comment by zxdong262** [comment]
可以试试1.25.10吗

**Comment by jiayouzl** [comment]
> 

可以了~
