### ISSUE TITLE
建议：支持连字字体

### ISSUE THREAD

**Issue by Cookie987** [electerm/electerm#2736]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

希望支持连字字体，比如[Fira Code](https://github.com/tonsky/FiraCode).

**Comment by txl263** [comment]
同样需求，我所有的终端都用的[SourceCodePro+Powerline+Awesome Regular](https://eng.m.fontke.com/font/178573369/)

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入
