### ISSUE TITLE
打开直接展示首页，不展示新连接页面

### ISSUE THREAD

**Issue by 842087571** [electerm/electerm#2740]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

你好，请问可以在打开软件的时候，只展示欢迎页，不默认打开新连接么，每次都得手动关闭
![image](https://user-images.githubusercontent.com/50511097/215701528-c3a195bf-7ac1-4203-9b3a-e0164c34726f.png)

**Comment by zxdong262** [comment]
目前还没有，可以在设置里设置程序启动打开某一个书签，这样就没有默认终端

**Comment by zxdong262** [comment]
哦不对，设置里有个“”“打开默认选项卡当应用启动时”,关闭即可
