### ISSUE TITLE
Microsoft Defender SmartScreen blocks Installation of electerm 1.25.14

### ISSUE THREAD

**Issue by pixelhomie** [electerm/electerm#2745]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.14-win-x64-installer.exe

### Platform detail (平台详情)

Windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

- Download newest electerm Windows Version 1.25.14 from Github
- Start electerm-1.25.14-win-x64-installer.exe
- Microsoft Defender SmartScreen is blocking the installation: "Running this app may put your PC at risk"

### What should have happened?(期望的结果)

- Installation should be possible without Administrator Rights and without disabling Microsoft Defender SmartScreen (like older Versions before)
- Microsoft Defender SmartScreen should not be Warning when trying to install electerm

### Additional information(其他任何相关信息)

- I have currently installed Version 1.25.10 where Installation was no problem
- Update from 1.25.10 to 1.25.14 within electerm not possible. After pressing the Update Button nothing happens (Window will always show "Upgrading ...0%" without any progress)

**Comment by zxdong262** [comment]
You may try electerm in microsoft store, upgrade from microsoft server would be smoother
