### ISSUE TITLE
左上角Menu菜单中，新建连接事件触发范围BUG

### ISSUE THREAD

**Issue by miko-chen** [electerm/electerm#2752]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows11  /  Microsoft Windows NT 10.0.22623.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 右上角点击Menu按钮
2. 点击新建连接
3. 新建一个默认终端

“新建连接”按钮的事件触发范围有问题，目测应该是单项的文本遮挡了选项的事件触发，在“新建连接”文本上下都能触发事件，文本上就不行

### What should have happened?(期望的结果)

整个“新建连接”选项都能被单击，而不是只有除了文本以外的部分可以被单击

**Comment by zxdong262** [comment]
最新版已修复
