### ISSUE TITLE
自动更新功能不正常

### ISSUE THREAD

**Issue by Fr33raNg3r** [electerm/electerm#2753]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-linux-amd64.deb

### Platform detail (平台详情)

LinuxMint 5.19.0-32

### What steps will reproduce the bug?(重新问题的详细步骤)

能够检测到有新版本，但是点击自动更新后一直卡在0%处。

### What should have happened?(期望的结果)

能够自动更新。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

![image](https://user-images.githubusercontent.com/15374658/219649558-e106dadd-3852-4fce-9573-26c82949bc5f.png)

**Comment by zxdong262** [comment]
如果有代理可以在全局设置里设置代理看看

**Comment by qwganker** [comment]
下载太慢了，几乎下不了

**Comment by zxdong262** [comment]
发布了新版本，这次会从sourceforge镜像下载如果github release连不上
https://sourceforge.net/projects/electerm.mirror/files/
