### ISSUE TITLE
Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by vitofasano** [electerm/electerm#2755]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

Darwin MacBook-Air-di-Vito.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:50:21 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8112 arm64

### What steps will reproduce the bug?(重新问题的详细步骤)

Cannot parse privateKey: Unsupported key format

### What should have happened?(期望的结果)

When I try to configure electerm to connect to my oracle VM using a private, key this message appears: "Cannot parse privateKey: Unsupported key format".
This doesn't happen if I use the normal if I use the normal terminal using "ssh ubuntu@xxx.xxx.xxx.xxx -i ssh-key-2020-10-07.key"

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

This doesn't happen if I use the normal if I use the normal terminal using "ssh ubuntu@xxx.xxx.xxx.xxx -i ssh-key-2020-10-07.key"

**Comment by zxdong262** [comment]
How did you created the key?

**Comment by vitofasano** [comment]
I don't remember very well, maybe I generated it from ORACLE CLOUD.
Furthermore I use this key to successfull connect to VM using windows terminal and macOS terminal.

**Comment by itc7** [comment]
I also encountered this problem now,
Can't import file private key after I update to version 1.28.1
Display characters are incorrect.

<img width="763" alt="image" src="https://github.com/electerm/electerm/assets/24414113/23090b83-8b72-4089-984c-d6e19aa594c9">

**Comment by zxdong262** [comment]
最新版已经修复
