### ISSUE TITLE
ssh认证协议扩展

### ISSUE THREAD

**Issue by zealotTL** [electerm/electerm#2756]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

基于键盘交互的验证方式（keyboard interactive authentication method），能否支持这种协议？当前认证圈里，很多都依赖短信验证码，这种键盘交互的验证方式会越来越流行，以及password + keyboard 组合方式认证
PS：主要是我这边有这种需求zzz

**Comment by zxdong262** [comment]
有试过吗，我记得是支持的，也许在某些情况下不好使

**Comment by zxdong262** [comment]
是支持的
