### ISSUE TITLE
在线升级功能不可用

### ISSUE THREAD

**Issue by mrmyn** [electerm/electerm#2763]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.14-mac-x64.dmg

### Platform detail (平台详情)

macOS 10.15.7

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="1068" alt="CleanShot 2023-02-27 at 22 01 56@2x" src="https://user-images.githubusercontent.com/20763281/221583749-d03caa6a-c81b-4bd9-ba2c-2f13159b8861.png">
已开启全局socks5，自测谷歌可用，http/socks5均已测试无效，在之前的几个版本还可用，使用Clash和Surge测试都是无法在线升级

### What should have happened?(期望的结果)

可以在线升级

**Comment by zxdong262** [comment]
最新版修复了
