### ISSUE TITLE
mac版本的ui，混进来了window的按钮

### ISSUE THREAD

**Issue by druid137** [electerm/electerm#2766]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://user-images.githubusercontent.com/125956530/221749300-8f2f2f66-f40b-4632-979d-450b1db8bf74.png)
如图

**Comment by zxdong262** [comment]
这个是统一的UI，设置里可以设置为使用系统标题栏就可以使用系统默认的标题栏了
