### ISSUE TITLE
同步 没有加密密码 下载配置报错

### ISSUE THREAD

**Issue by blankhang** [electerm/electerm#2768]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.25.16

### Platform detail (平台详情)

Mac x64 10.15.7

### What steps will reproduce the bug?(重新问题的详细步骤)
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/3981276/222136530-46c5a9e0-439e-4086-be45-a03361e8da71.png">
点击下载配置后报错

```sh
Error: Error invoking remote method 'async': TypeError [ERR_INVALID_ARG_TYPE]: The "password" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, or DataView. Received undefined
    at EventEmitter.o.invoke (node:electron/js2c/renderer_init:57:526)
    at async Proxy.e.downloadSetting (http://127.0.0.1:30974/js/electerm.js?1.25.16:2:1884855)
```

### What should have happened?(期望的结果)

正常下载配置

**Comment by zxdong262** [comment]
看一看你的gist里的书签数据，是不是加密的？试试使用gist id或者gist secret作为密码

**Comment by blankhang** [comment]
> 看一看你的gist里的书签数据，是不是加密的？试试使用gist id或者gist secret作为密码

没加密的 明文
尝试用了 token 作为密码ok了 拉下来了 。。。但是 这任然是个bug  不能空加密密码

**Comment by zxdong262** [comment]
> > 看一看你的gist里的书签数据，是不是加密的？试试使用gist id或者gist secret作为密码
> 
> 没加密的 明文 尝试用了 token 作为密码ok了 拉下来了 。。。但是 这任然是个bug 不能空加密密码

我试了是可以的，你把密码清空，保存再上传下载试试

**Comment by blankhang** [comment]
![image](https://user-images.githubusercontent.com/3981276/222618883-8727192f-f5e7-42e6-8e51-7fa7f8843c98.png)

**Comment by blankhang** [comment]
> > > 看一看你的gist里的书签数据，是不是加密的？试试使用gist id或者gist secret作为密码
> > 
> > 
> > 没加密的 明文 尝试用了 token 作为密码ok了 拉下来了 。。。但是 这任然是个bug 不能空加密密码
> 
> 我试了是可以的，你把密码清空，保存再上传下载试试

![image](https://user-images.githubusercontent.com/3981276/222618930-3d19200a-4022-4ab0-81f6-0a7dfafa6234.png)

**Comment by zxdong262** [comment]
> > > > 看一看你的gist里的书签数据，是不是加密的？试试使用gist id或者gist secret作为密码
> > > 
> > > 
> > > 没加密的 明文 尝试用了 token 作为密码ok了 拉下来了 。。。但是 这任然是个bug 不能空加密密码
> > 
> > 
> > 我试了是可以的，你把密码清空，保存再上传下载试试
> 
> ![image](https://user-images.githubusercontent.com/3981276/222618930-3d19200a-4022-4ab0-81f6-0a7dfafa6234.png)

确定是以下步骤？
1.清除密码
2.点击保存
3.点击上传设置
4.点击下载设置

**Comment by blankhang** [comment]
> > > > > 看一看你的gist里的书签数据，是不是加密的？试试使用gist id或者gist secret作为密码
> > > > 
> > > > 
> > > > 没加密的 明文 尝试用了 token 作为密码ok了 拉下来了 。。。但是 这任然是个bug 不能空加密密码
> > > 
> > > 
> > > 我试了是可以的，你把密码清空，保存再上传下载试试
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/3981276/222618930-3d19200a-4022-4ab0-81f6-0a7dfafa6234.png)
> 
> 确定是以下步骤？ 1.清除密码 2.点击保存 3.点击上传设置 4.点击下载设置

124

**Comment by zxdong262** [comment]
3是确保上传的未加密版本数据，这样无密码下载才可行

**Comment by zxdong262** [comment]
> 3是确保上传的未加密版本数据，这样无密码下载才可行

你可以对比一下目前的gist数据和执行123之后的gist数据

**Comment by zxdong262** [comment]
> 我从来就没有点过3 的 而且 我之前下载没成功前 不可能去点上传的 如果把本地的空数据给覆盖到云端那才是坑大了

同步数据那里可以手动导出导入所有数据

**Comment by zxdong262** [comment]
> 我从来就没有点过3 的 而且 我之前下载没成功前 不可能去点上传的 如果把本地的空数据给覆盖到云端那才是坑大了

**Comment by 443126500** [comment]
Error: Error invoking remote method 'async': Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT at EventEmitter.o.invoke (node:electron/js2c/renderer_init:57:526) at async Proxy.e.downloadSetting (http://127.0.0.1:30974/js/electerm.js?1.26.0:2:1889451)
一样的报错，保存的有密码，在其他设备同步的时候点击下载配置报错

**Comment by zxdong262** [comment]
可以试试最新版吗
