### ISSUE TITLE
mac版 拖动界面后出现外框变大，但是终端框不变

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#2769]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.16-mac-x64.dmg

### Platform detail (平台详情)

mac x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 连接ssh服务器
2. 鼠标拖动界面的大小
3. 命令执行框的大小未发生改变
![bug111](https://user-images.githubusercontent.com/8625218/222348392-e185c8ec-48a2-4608-8bf6-083f96fd8e73.png)

### What should have happened?(期望的结果)

命令执行框的大小同步发生改变

**Comment by super-lzb** [comment]
没错，window11也是这样

**Comment by zxdong262** [comment]
确实有问题，临时的解决方法是切换到其他tab再切换回来
