### ISSUE TITLE
1.25.16版本， ui最大、最小化卡死或点击没反应

### ISSUE THREAD

**Issue by super-lzb** [electerm/electerm#2770]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

Windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

win11系统，1.25.16版本， ui最大化最小化卡死或点击没反应

### What should have happened?(期望的结果)

nothing

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

no

### Additional information(其他任何相关信息)

nothing

**Comment by ldw97** [comment]
但windows  10   1.25.20版本仍然存在此问题

**Comment by zxdong262** [comment]
最新版应该已经修复
