### ISSUE TITLE
electerm-xx.xx.xx-mac-arm64.dmg crash-down

### ISSUE THREAD

**Issue by freepository** [electerm/electerm#2776]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

macOS ARM M2 Max

### What steps will reproduce the bug?(重新问题的详细步骤)

Simply crashed down when launching Electerm.  The latest macOS arm one doesn't work.  

### What should have happened?(期望的结果)

please fix it

**Comment by zxdong262** [comment]
可以试试最新版吗？
