### ISSUE TITLE
windows 平台 1.25.20 点击关闭无效

### ISSUE THREAD

**Issue by ldw97** [electerm/electerm#2780]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.20 -win-x64-installer.exe

### Platform detail (平台详情)

Windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

打开 electerm 就会出现

### What should have happened?(期望的结果)

![image](https://user-images.githubusercontent.com/57819255/224530087-bdec4ffb-a0a0-421e-9ee2-a3aaec6a583a.png)

### Additional information(其他任何相关信息)

1.25.16之前未发现此问题，17， 18,19  未尝试 ，不确定

**Comment by ldw97** [comment]
![image](https://user-images.githubusercontent.com/57819255/224535031-2c106641-934b-4ded-8a48-49fdfff26ca4.png)

**Comment by lighteninglin** [comment]
我也有同样的问题，系统windows 10

**Comment by night-rainy** [comment]
我也有同样的问题,系统是windows11
