### ISSUE TITLE
能否支持一下M1啊

### ISSUE THREAD

**Issue by bee-lgtm** [electerm/electerm#2785]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

能否支持一下M1啊

**Comment by yumetal12138** [comment]
因为苹果会拒绝打开不明来源的软件，你可以参考这个链接里的做法来解决，我已经成功打开了[https://blog.csdn.net/iiiliuyang/article/details/104186265](url)

**Comment by bee-lgtm** [comment]
> 因为苹果会拒绝打开不明来源的软件，你可以参考这个链接里的做法来解决，我已经成功打开了[https://blog.csdn.net/iiiliuyang/article/details/104186265](url)
