### ISSUE TITLE
macos下使用系统标题栏,设置好窗口大小后,下次启动窗口会缩小一点,然后越来越小,非系统标题栏正常,请修复下.

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2788]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

最新

### Platform detail (平台详情)

macos

### What steps will reproduce the bug?(重新问题的详细步骤)

macos下使用系统标题栏,设置好窗口大小后,下次启动窗口会缩小一点,然后越来越小,非系统标题栏正常,请修复下.

### What should have happened?(期望的结果)

macos下使用系统标题栏,设置好窗口大小后,下次启动窗口会缩小一点,然后越来越小,非系统标题栏正常,请修复下.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

macos下使用系统标题栏,设置好窗口大小后,下次启动窗口会缩小一点,然后越来越小,非系统标题栏正常,请修复下.

### Additional information(其他任何相关信息)

macos下使用系统标题栏,设置好窗口大小后,下次启动窗口会缩小一点,然后越来越小,非系统标题栏正常,请修复下.

**Comment by jiayouzl** [comment]
解决了没?

**Comment by zxdong262** [comment]
> 解决了没?

还没有，下个版本吧，本来要处理的，遗漏了。

**Comment by jiayouzl** [comment]
update?

**Comment by zxdong262** [comment]
下次一定！-_-||
