### ISSUE TITLE
rz 功能如果不上传文件点击取消取消不了

### ISSUE THREAD

**Issue by Silence0516** [electerm/electerm#2789]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.22-win-x64-installer.exe

### Platform detail (平台详情)

OS 名称:          Microsoft Windows 11 专业版 OS 版本:          10.0.22621 暂缺 Build 22621 OS 制造商:        Microsoft Corporation OS 配置:          独立工作站 OS 构建类型:      Multiprocessor Free 注册的所有人:     hsYang 注册的组织: 产品 ID:          00330-80000-00000-AA279 初始安装日期:     2022/9/26, 14:33:47 系统启动时间:     2023/3/17, 11:39:38 系统制造商:       LENOVO 系统型号:         82F8 系统类型:         x64-based PC 处理器:           安装了 1 个处理器。                   [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2419 Mhz BIOS 版本:        LENOVO F8CN38WW(V2.03), 2021/4/9

### What steps will reproduce the bug?(重新问题的详细步骤)

1、rz 回车
2、点击弹出层中的取消
实际结果：取消不了

### What should have happened?(期望的结果)

可以直接取消

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

### Additional information(其他任何相关信息)

无

**Comment by czxin788** [comment]
我也遇到这个问题

**Comment by wanglu-yao** [comment]
我也遇到这个问题
