### ISSUE TITLE
macos下最新版本点击cmd+左键点击链接地址,不会打开浏览器的!

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2792]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

macos下最新版本点击cmd+左键点击链接地址,不会打开浏览器的!

### Platform detail (平台详情)

macos下最新版本点击cmd+左键点击链接地址,不会打开浏览器的!

### What steps will reproduce the bug?(重新问题的详细步骤)

macos下最新版本点击cmd+左键点击链接地址,不会打开浏览器的!

### What should have happened?(期望的结果)

macos下最新版本点击cmd+左键点击链接地址,不会打开浏览器的!

**Comment by zxdong262** [comment]
我试了可以啊，设置了交换ctrl和cmd键吗？

**Comment by jiayouzl** [comment]
> 我试了可以啊，设置了交换ctrl和cmd键吗？

不是每次都这样的,偶尔会碰到的.
