### ISSUE TITLE
最新版本macos下,设置选择文本复制后,在SFTP上编辑文本内容,竟然也会复制?导致没错都要重复好几次黏贴文本!

### ISSUE THREAD

**Issue by jiayouzl** [electerm/electerm#2794]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

最新版本macos下,设置选择文本复制后,在SFTP上编辑文本内容,竟然也会复制?导致没错都要重复好几次黏贴文本!

### Platform detail (平台详情)

最新版本macos下,设置选择文本复制后,在SFTP上编辑文本内容,竟然也会复制?导致没错都要重复好几次黏贴文本!

### What steps will reproduce the bug?(重新问题的详细步骤)

最新版本macos下,设置选择文本复制后,在SFTP上编辑文本内容,竟然也会复制?导致没错都要重复好几次黏贴文本!

### What should have happened?(期望的结果)

最新版本macos下,设置选择文本复制后,在SFTP上编辑文本内容,竟然也会复制?导致没错都要重复好几次黏贴文本!

**Comment by zxdong262** [comment]
可以截图看看你的设置吗，我试了选择复制，在编辑器里没有影响，还有什么其他的设置开启了？

**Comment by jiayouzl** [comment]
> 可以截图看看你的设置吗，我试了选择复制，在编辑器里没有影响，还有什么其他的设置开启了？

我试了N次了,每次sftp上在线编辑脚本文件的时候,本地复制了内容要黏贴到sftp里的时候,返回你这个软件都自动把终端的文本都复制到剪切板了非常麻烦,要重新再复制一次才行.

**Comment by jiayouzl** [comment]
如果你无法复现这个bug的话我建议你可以在打开sftp文本编辑器的时候,搞个变量,在打开编辑器的时候,自动把选择复制的功能暂时关闭,在编辑器被关闭的时候再打开这个功能已修复这个bug!

**Comment by zxdong262** [comment]
> > 可以截图看看你的设置吗，我试了选择复制，在编辑器里没有影响，还有什么其他的设置开启了？
> 
> 我试了N次了,每次sftp上在线编辑脚本文件的时候,本地复制了内容要黏贴到sftp里的时候,返回你这个软件都自动把终端的文本都复制到剪切板了非常麻烦,要重新再复制一次才行.

`本地复制了内容`可以详细说说吗

**Comment by jiayouzl** [comment]
> > > 可以截图看看你的设置吗，我试了选择复制，在编辑器里没有影响，还有什么其他的设置开启了？
> > 
> > 
> > 我试了N次了,每次sftp上在线编辑脚本文件的时候,本地复制了内容要黏贴到sftp里的时候,返回你这个软件都自动把终端的文本都复制到剪切板了非常麻烦,要重新再复制一次才行.
> 
> `本地复制了内容`可以详细说说吗

本地复制就是我在其他地方复制的文本内容啊,然后点击你这个软件,压根就不在终端界面,在sftp界面就提示我复制了终端所有内容!

**Comment by jiayouzl** [comment]
你无法复现的话,我觉得还是用我上面的方法解决吧.

**Comment by jiayouzl** [comment]
macos 13.2.1 M1max.

**Comment by zxdong262** [comment]
我知道了全选生效了

**Comment by jiayouzl** [comment]
> 我知道了全选生效了

你能知道那晚我在线编辑文档时候的无助了吧!哈哈哈哈,我找你这个软件bug都找好久!
