### ISSUE TITLE
无法使哟哦那个代理

### ISSUE THREAD

**Issue by HeiyirenCode** [electerm/electerm#2798]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.22-mac-x64.dmg -  最新版

### Platform detail (平台详情)

mac os. x64

### What steps will reproduce the bug?(重新问题的详细步骤)

设置 全局socks5 后 无法连接服务器，本地使用 curl 测试socks5都是正常的，在某种特殊情况下（多次配置代理工具后暂时可以，连接上去后秒断开），目前测试了多个代理，clashx。v2rayu   ，都出现这种情况，其他软件可以正常使用该代理提供的本地socks5断开

### What should have happened?(期望的结果)

正常连接服务器

**Comment by zxdong262** [comment]
我试了一下是可以的，一种可能的情况是代理延迟太高就不够稳定了

**Comment by HeiyirenCode** [comment]
ZHAO Xudong ***@***.***>于2023年3月29日 周三下午6:30写道：

**Comment by HeiyirenCode** [comment]
他是秒提示连接错误，几乎连接的瞬间就提示了，代理正常畅通无阻的，就像本地代理驳回了请求一样。

黑衣人 ***@***.***>于2023年3月29日 周三下午6:32写道：
