### ISSUE TITLE
产品很棒，建议新增一个命令行“粘贴选择内容”命令

### ISSUE THREAD

**Issue by kugousvip** [electerm/electerm#2799]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

**建议新增一个命令行的“粘贴选择内容”命令，以实现“复制并粘贴”功能。**

**Comment by zxdong262** [comment]
方面详细描述一下吗

**Comment by kugousvip** [comment]
> 方面详细描述一下吗

![问题描述](https://user-images.githubusercontent.com/70506808/228737450-7c7585af-73de-46d3-929b-cad58dccac36.png)
您好，感谢回复。
如图所示：如果我要将（1）处选中的内容插入（3）处光标处，需要先右键复制选中内容，再右键粘贴，如此两步操作才可在光标处插入所选文字。
但如果右键菜单新增“粘贴选择内容”或者类似菜单，实现“右键菜单选择一次即可将选择内容粘贴至光标处”，如此操作会很便捷，相关内容可参考Xshell或者finalShell等shell软件

**Comment by zxdong262** [comment]
目前增加了粘贴选中内容的快捷键alt-insert,可以在快捷键设置里修改
