### ISSUE TITLE
Win8命令行启动，密码包含英文冒号，导致启动不了

### ISSUE THREAD

**Issue by lvhill** [electerm/electerm#2804]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.30-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 6.3.9600.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

Windows 8 操作系统，命令行启动命令如下：

`D:\electerm\electerm.exe -nw -l gxt -P 2255 -pw itx:2yIpLt0v 192.1.2.9`

启动没响应。
经测试，是因为密码 `itx:2yIpLt0v` 包含了英文冒号，导致启动无响应。

### What should have happened?(期望的结果)

修复bug

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

putty、SecureCRT、Xshell并无这个问题

### Additional information(其他任何相关信息)

putty、SecureCRT、Xshell并无这个问题

**Comment by zxdong262** [comment]
-pw “itx:2yIpLt0v” 可以吗？

**Comment by lvhill** [comment]
PowerShell 窗口不管是加双引号 `"` 还是单引号 `'` 都不行； cmd窗口加双引号 `"` 也是启动不了，但是单引号 `'` 可以启动，只是密码不对。

**Comment by lvhill** [comment]
> -pw “itx:2yIpLt0v” 可以吗？


PowerShell 窗口不管是加双引号 " 还是单引号 ' 都不行； cmd窗口加双引号 " 也是启动不了，但是单引号 ' 可以启动，只是密码不对。

**Comment by lvhill** [comment]
> -pw “itx:2yIpLt0v” 可以吗？


PowerShell 窗口不管是加双引号 `"` 还是单引号 `'` 都不行； cmd窗口加双引号 `"` 也是启动不了，但是单引号 `'` 可以启动，只是把单引号也认为是密码的一部分了，导致密码不对。

**Comment by zxdong262** [comment]
将在下个版本修复
