### ISSUE TITLE
书签显示描述信息等

### ISSUE THREAD

**Issue by imic07** [electerm/electerm#2810]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

如下图： 鼠标移动上去后，只展示了名称，没有描述等信息，当节点比较多的时候，不知道这个节点是做什么用的。希望提示里面能增加显示 没描述等信息，方便使用者快速找到需要的节点。
![image](https://user-images.githubusercontent.com/16321067/230534672-d486e0ab-4f6d-4dc4-836f-ed9fbb12a20e.png)

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/194bd2b8c96f294f098327215af820a4d11f3401
