### ISSUE TITLE
在输入法为搜狗的时候，搜狗输入法无法输入中文

### ISSUE THREAD

**Issue by dengwentong** [electerm/electerm#2815]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.41-win-x64-installer.exe

### Platform detail (平台详情)

Windows 11 专业版X64  22H2 22621.1485

### What steps will reproduce the bug?(重新问题的详细步骤)

在输入法为搜狗的时候，搜狗输入法无法输入中文

### What should have happened?(期望的结果)

在输入法为搜狗的时候，搜狗输入法能允许中文

**Comment by dwtowen** [comment]
### 这个问题一直困扰我很久，今天终于解决了。

> 之前尝试过很多方法，网上各位建议的方法也都试了一遍，依然不行。
> 
> 只能复制中文，粘贴中文；搜狗输入法始终不能输入中文；
> 
> 环境及版本说明：
> 
> 操作系统：windows11 专业版 23H2
> 
> electerm：electerm-1.37.121-win-x64-installer.exe
> 
> 搜狗输入法：sogou_pinyin_13.13a.exe

### 解决步骤

1. 保证搜狗输入法和electerm为最新版本；
  
2. 卸载已安装版本electerm；
  
3. 清除配置及用户数据(此步骤极为重要，否则依然不行)；
  
  A、定位到如下目录
  
  ```bash
  C:\Users\dengw\AppData\Roaming
  ```
  
  说明：**dengw** 为你计算机的用户名；**AppData** 为隐藏目录，如果没有，请显示隐藏文件夹；
  
  B、找到 `electerm` 目录并删除；
  
4. 重新安装electerm；
  
5. 再次打开，发觉已经可以输入中文了。

**Comment by dwtowen** [comment]
😁😁😁😁😁
