### ISSUE TITLE
外部编辑器以及SFTP使用问题

### ISSUE THREAD

**Issue by TTT-TD** [electerm/electerm#2816]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.41-win-x64.tar.gz

### Platform detail (平台详情)

Windows 11 Home x64 22H2 (22621.1555)

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 遇到的编辑器方面的问题
    - 设置中填写VS Code的绝对路径`D·:\VSCode\Code.exe`之后在SFTP中文件右键菜单没有使用外部编辑器的选项
    - sftp中后缀为txt或者log的文件，双击会使用electerm内置编辑器，点击下方使用外部编辑器编辑会一直卡在加载动画，同时Windows文件管理器会打开系统的Temp目录，同时使用系统notepad.exe打开了文件，而非设置的VSCode
    - 大部分非文本文件的后缀格式无法直接编辑，右键菜单没有编辑选项，双击是下载
2. sftp遇到的问题
    - 这应该也不属于是问题，就是想知道如何实现sftp路径和终端中路径进行同步
 3. 是否支持便携版
    - 下载的压缩包文件，发现所有数据依然存储在系统用户目录，无法达到便携版效果，应该是考虑到了目录权限问题 

### What should have happened?(期望的结果)

可以正常使用外部编辑器

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

**Comment by zxdong262** [comment]
1.这是个bug，路径已经无效了，下个版本会移除，会使用系统关联的编辑器打开，如果没有设置关联会打不开（体验是有问题的），同时打开文件目录是作为安全措施，假如打不开文件用户也可以自行右键设置关联打开什么的，为了防止卡死，太大的文件是双击传输而非打开
2.我也想知道。。。
3.暂不支持，也许可以在windows下提供支持

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/pull/2916 将在下个版本支持便携化
