### ISSUE TITLE
可否为"Proxy type"中的SOCKS类型增加远程域名解析选项？

### ISSUE THREAD

**Issue by PaTTeeL** [electerm/electerm#2820]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

问问"Proxy type"中的"SOCKS5"和"SOCKS4"现在是本地解析域名还是远程解析域名？

可否增加一个远程解析域名的选项或者在"Proxy type"中增加"socks5h"和"socks4a"两个类型实现远程解析域名？
刚才检查了一下，发现Global Proxy也是一样，能否有远程解析域名的方案？

![image](https://user-images.githubusercontent.com/9150277/232656259-5d810181-a96c-40e3-8dae-73036169342f.png)

![image](https://user-images.githubusercontent.com/9150277/232543485-d5457dfe-35af-46c9-b155-27bab9aa84eb.png)

**Comment by zxdong262** [comment]
将在下个版本支持

**Comment by zxdong262** [comment]
已经支持
