### ISSUE TITLE
snapcraft  简介中的链接有点小问题

### ISSUE THREAD

**Issue by lonnywong** [electerm/electerm#2826]
在 [https://snapcraft.io/electerm](https://snapcraft.io/electerm) 简介中，好像不支持 `[xxx](http://xxx)` 这种语法。

特别是 trzsz 的链接 `[Trzsz](https://github.com/trzsz/trzsz)(trz/tsz)`，把 `https://github.com/trzsz/trzsz)(trz/tsz` 解释成链接了。不知道在 `(trz/tsz)` 前面加一个空格会不会有用？

**Comment by zxdong262** [comment]
确实不支持，修正了一下，至少链接对了
