### ISSUE TITLE
mac按住command+滚轮是缩放字体大小快捷键问题

### ISSUE THREAD

**Issue by Lction** [electerm/electerm#2827]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

现在按住command+滚轮是缩放字体大小快捷键，冒昧问下可以增加个自定义设置么？或者可以关闭这个快捷键，因为会和其他应用冲突，感谢

**Comment by zxdong262** [comment]
下个版本将提供快捷键设定，可以注册为其他按键
