### ISSUE TITLE
macOS，新建连接， 测试连接，提示这个错误 “connection fails: Failed to execute 'postMessage' on 'Worker': [object Array] could not be cloned.”

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#2830]
macOS，新建连接， 测试连接，提示这个错误 “connection fails: Failed to execute 'postMessage' on 'Worker': [object Array] could not be cloned.”

_Originally posted by @yiyanwei in https://github.com/electerm/electerm/discussions/2829_

**Comment by lystrosaurus** [comment]
windows 11 , electerm 1.25.41, 也有这个错误。

**Comment by zxdong262** [comment]
方便详细描述一下复现步骤不，我试了一下没有复现
