### ISSUE TITLE
可以支持语法高亮显示嘛

### ISSUE THREAD

**Issue by LIHAQI** [electerm/electerm#2832]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

可以支持语法高亮显示嘛

**Comment by etanman** [comment]
作者终于要这个振奋人心的功能了，一定要全面支持交换机、路由器、防火墙和linux。

**Comment by zxdong262** [comment]
已经加入，参考https://github.com/electerm/electerm/wiki/Terminal-keywords-highlight-regular-expression-exmaples
