### ISSUE TITLE
窗口最大化后无法恢复

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#2835]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

Windowsx64

### What steps will reproduce the bug?(重新问题的详细步骤)

问题如题目，窗口最大化后，点击还原按钮没有反应，无法还原到原来的窗口大小。

### What should have happened?(期望的结果)

改进这个问题

**Comment by zxdong262** [comment]
可以试试设置里使用系统标题栏
