### ISSUE TITLE
部分场景下，ssh连接刚建立，会自动断开

### ISSUE THREAD

**Issue by xiaofeige** [electerm/electerm#2837]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-x64.dmg

### Platform detail (平台详情)

型号名称：	MacBook Pro   型号标识符：	MacBookPro16,1   处理器名称：	六核Intel Core i7   处理器速度：	2.6 GHz   处理器数目：	1   核总数：	6   L2缓存（每个核）：	256 KB   L3缓存：	12 MB   超线程技术：	已启用   内存：	16 GB   系统固件版本：	1916.80.2.0.0 (iBridge: 20.16.3045.0.0,0)   操作系统加载程序版本：	540.120.3~22   序列号（系统）：	C02FV74TMD6M

### What steps will reproduce the bug?(重新问题的详细步骤)

兼容性问题，通过ATrust vpn连接远程linux机器时，刚登陆之后，几秒后连接会自动断开，但是我直接用系统自带的terminal访问则没有问题。
![image](https://github.com/electerm/electerm/assets/10513399/daec340c-9365-4806-aa05-2ba82baccf17)

### What should have happened?(期望的结果)

连接不要自动断开

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能，系统自带terminal ，  secureCRT 上都正常，唯独这个软件不行。

### Additional information(其他任何相关信息)

调整electerm的  ssh/sftp timeout貌似能延缓几秒的断开时间。不确定是否关联，体感如此。

**Comment by xiaofeige** [comment]
问题一直存在，升级过多次electerm版本，最新版本 1.25.41仍然存在

**Comment by tudoujunha** [comment]
我也遇到这个问题，后来发现用openssh命令连接，就不会自动断开，非常稳定，所以现在都直接用命令

**Comment by zxdong262** [comment]
可以把设置里keepalive间隔设为0试试，最新版默认为0
