### ISSUE TITLE
关于sftp删除文件的一个bug

### ISSUE THREAD

**Issue by cangkuai** [electerm/electerm#2843]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.41-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

现在sftp如果同时选中文件夹和文件，然后右键删除，会出现文件夹没有被删除的情况

### What should have happened?(期望的结果)

文件和文件夹都会被删除

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

目前finallshell没有这个问题

**Comment by zxdong262** [comment]
试了一下没有复现，会不会是文件夹设置了只读或者其他权限问题？
