### ISSUE TITLE
什么时候能实现连接设备关键字高亮呀？

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#2844]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

现在连接交换机路由器等设备，都无法像MobaXterm一样高亮关键字。

**Comment by LIHAQI** [comment]
同求

**Comment by zxdong262** [comment]
已经加入，参考https://github.com/electerm/electerm/wiki/Terminal-keywords-highlight-regular-expression-exmaples
