### ISSUE TITLE
我问下快速命令是怎么使用的，我添加了快速命令，然后输入快捷指令，无效啊

### ISSUE THREAD

**Issue by Xuzan9396** [electerm/electerm#2858]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

我问下快速命令是怎么使用的，我添加了快速命令，然后输入快捷指令，没反应

**Comment by Xuzan9396** [comment]
<img width="1313" alt="image" src="https://github.com/electerm/electerm/assets/24741439/f967ef69-5794-4767-9184-f76936cb263f">
比如我设置了dp，但是我登录服务器执行dp不生效啊

**Comment by zxdong262** [comment]
鼠标指向左下角快速命令就会弹出列表，点击即可，不用输入

**Comment by Xuzan9396** [comment]
@zxdong262  感谢，这莫大的字没看到，哈哈
