### ISSUE TITLE
1.26.0版本面板问题

### ISSUE THREAD

**Issue by LIHAQI** [electerm/electerm#2863]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.26.0-win-x64-installer.exe

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

更新到1.26.0版本后，隐藏到后台，再打开就会出现以下问题。
![image](https://github.com/electerm/electerm/assets/57976650/bca17f5a-d151-446f-b5e1-53851472b252)

### What should have happened?(期望的结果)

隐藏到后台无问题

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

### Additional information(其他任何相关信息)

无

**Comment by zxdong262** [comment]
可以试试1.26.1吗

**Comment by LIHAQI** [comment]
> 可以试试1.26.1吗

升级到了1.26.2，目前没这个问题了
