### ISSUE TITLE
双击标题栏可最大化，最小化窗口

### ISSUE THREAD

**Issue by wwek** [electerm/electerm#2866]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/electerm/electerm/assets/1239403/84245011-b4a9-4f18-92b7-2678949120af)

特性rt
windows上的软件基本都带这个特性，较多人都有这个习惯

**Comment by zxdong262** [comment]
可以在设置里改为使用系统标题栏

**Comment by zxdong262** [comment]
最新版已经优化
