### ISSUE TITLE
设置同步-gitee-下载设置报错

### ISSUE THREAD

**Issue by Kabulaka** [electerm/electerm#2867]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.26.2 所有版本

### Platform detail (平台详情)

windows 11，mac os(ARM)

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 点击“设置同步”
2. 点击“gitee”
3. 配置“token”、“gist”、“加密 密码”
4. 点击“下载配置”

此时出现错误：
```
Error: Seems you have a empty gist, you can try use existing gist ID or upload first
    at Proxy.e.downloadSetting (http://127.0.0.1:30974/js/electerm.js?1.26.2:2:1889388)
```
但是实际书签是**同步成功**的，但是重启后**书签丢失**

### What should have happened?(期望的结果)

下载配置，可以正常完成

**Comment by zxdong262** [comment]
复现不了这个情况。数据是什么样的，方便提供一个脱敏的副本让我试试不

**Comment by Kabulaka** [comment]
> 复现不了这个情况。数据是什么样的，方便提供一个脱敏的副本让我试试不

应该是老版本升级上来数据不兼容，报错后不重启，直接再上传一次，下载一次就正常了
