### ISSUE TITLE
【功能建议】期望可以支持导入批量主机管理的功能

### ISSUE THREAD

**Issue by qinwentu** [electerm/electerm#2868]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

导入主机ip账户列表、批量执行命令、批量发送文件

**Comment by zxdong262** [comment]
可以试试最新版吗，加入了批量操作功能
![Screen Shot 2023-07-09 at 16 30 37](https://github.com/electerm/electerm/assets/1641949/b50dc285-6cdd-4477-82c8-1cd87ca1bae9)
