### ISSUE TITLE
X11无法正常使用

### ISSUE THREAD

**Issue by helloworld288** [electerm/electerm#2869]
electerm-1.26.2-win-x64-installer.exe

windows 11

已经下载了xming，并且在其他软件比如putty上可以运行良好。

在electerm上设置启动X11后，每次登录都会报错：
/usr/bin/xauth:  file /home/username/.Xauthority does not exist
/usr/bin/xauth: (stdin):2:  bad "add" command line

并且在服务器节点切换过程中，使用srun -x11时，会报告：
srun: error: x11_get_xauth: Could not retrieve magic cookie. Cannot use X11 forwarding.

并不确定这个问题是否是软件的问题，但还是希望能够得到解决，这对经常画图的科研狗会起到很大帮助。泪目~拜托啦~~~

**Comment by zxdong262** [comment]
之前的测试，打开 Mobaxterm's x11 窗口才可以

**Comment by helloworld288** [comment]
具体是什么原因呀？因为如果这样的话，我要是图方便就直接用Mobaxterm了。（没别的意思哈，就是想让electerm功能更完善）

**Comment by helloworld288** [comment]
> 

具体是什么原因呀？因为如果这样的话，我要是图方便就直接用Mobaxterm了。（没别的意思哈，就是想让electerm功能更完善）

**Comment by zxdong262** [comment]
> > 
> 
> 具体是什么原因呀？因为如果这样的话，我要是图方便就直接用Mobaxterm了。（没别的意思哈，就是想让electerm功能更完善）

几年前我挨个验证的，也许现在不同了，有空我试试看是不是有其他的选项。

**Comment by helloworld288** [comment]
谢谢，麻烦您了

**Comment by xiekunwhy** [comment]
xming好像也连接不了，有什么办法可以直接打开服务器上的png或者html吗（xshell可以分别使用display和Firefox查看）？

**Comment by xiekunwhy** [comment]
可以了，在连接的设置里打开x11
![image](https://github.com/electerm/electerm/assets/17738229/83323628-eaa3-41ab-a98f-b8d70a381636)

**Comment by zxdong262** [comment]
> xming好像也连接不了，有什么办法可以直接打开服务器上的png或者html吗（xshell可以分别使用display和Firefox查看）？
> 
> ![image](https://user-images.githubusercontent.com/17738229/250259137-7ebf1753-8cc6-42ef-b7fe-75e6909f28bf.png)

你用xming连接成功的吗？

**Comment by xiekunwhy** [comment]
> 

是的，xming连接的，在书签里对具体的连接打开x11，然后运行xming就可以了
