### ISSUE TITLE
xshell的xterm主题

### ISSUE THREAD

**Issue by xiekunwhy** [electerm/electerm#2870]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

能否实现xshell的xterm主题。主要是颜色搭配非常好，文件夹的蓝色不要太蓝。
![xterm-1](https://github.com/electerm/electerm/assets/17738229/dd5b2545-3f1a-4bf5-bcc6-eba37bc28d94)
![xterm-2](https://github.com/electerm/electerm/assets/17738229/2adeb346-0afe-4416-b813-65621afbd8e2)

祝好！

**Comment by xiekunwhy** [comment]
包括你们的网页，蓝色太蓝了，蓝得很暗，看一下眼睛就疲惫了
![image](https://github.com/electerm/electerm/assets/17738229/5aa8bd79-1ac7-4d08-90d8-6b02806053c4)

**Comment by zxdong262** [comment]
可以在主题列表里自己编写一个主题

**Comment by xiekunwhy** [comment]
试了一下，好像没用，比如这里面的（https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt）两个blue相关的被改成了\#00CCFF，却不起作用，目录的蓝色还是和那种深蓝色。
所以想问下具体是哪个参数影响目录的颜色？

**Comment by zxdong262** [comment]
> 试了一下，好像没用，比如这里面的（[https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt）两个blue相关的被改成了\#00CCFF，却不起作用，目录的蓝色还是和那种深蓝色。](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt%EF%BC%89%E4%B8%A4%E4%B8%AAblue%E7%9B%B8%E5%85%B3%E7%9A%84%E8%A2%AB%E6%94%B9%E6%88%90%E4%BA%86%5C#00CCFF%EF%BC%8C%E5%8D%B4%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%EF%BC%8C%E7%9B%AE%E5%BD%95%E7%9A%84%E8%93%9D%E8%89%B2%E8%BF%98%E6%98%AF%E5%92%8C%E9%82%A3%E7%A7%8D%E6%B7%B1%E8%93%9D%E8%89%B2%E3%80%82) 所以想问下具体是哪个参数影响目录的颜色？

我也不清楚，只是实现了这些参数的支持。

**Comment by zxdong262** [comment]
> 试了一下，好像没用，比如这里面的（[https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt）两个blue相关的被改成了\#00CCFF，却不起作用，目录的蓝色还是和那种深蓝色。](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt%EF%BC%89%E4%B8%A4%E4%B8%AAblue%E7%9B%B8%E5%85%B3%E7%9A%84%E8%A2%AB%E6%94%B9%E6%88%90%E4%BA%86%5C#00CCFF%EF%BC%8C%E5%8D%B4%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%EF%BC%8C%E7%9B%AE%E5%BD%95%E7%9A%84%E8%93%9D%E8%89%B2%E8%BF%98%E6%98%AF%E5%92%8C%E9%82%A3%E7%A7%8D%E6%B7%B1%E8%93%9D%E8%89%B2%E3%80%82) 所以想问下具体是哪个参数影响目录的颜色？

你可以打开编辑xshell主题那里看看它的参数设置，命名应该是类似的，那样的话可以移植过来

**Comment by yohohero** [comment]
> 试了一下，好像没用，比如这里面的（[https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt）两个blue相关的被改成了\#00CCFF，却不起作用，目录的蓝色还是和那种深蓝色。](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/electerm/Dark%2B.txt%EF%BC%89%E4%B8%A4%E4%B8%AAblue%E7%9B%B8%E5%85%B3%E7%9A%84%E8%A2%AB%E6%94%B9%E6%88%90%E4%BA%86%5C#00CCFF%EF%BC%8C%E5%8D%B4%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%EF%BC%8C%E7%9B%AE%E5%BD%95%E7%9A%84%E8%93%9D%E8%89%B2%E8%BF%98%E6%98%AF%E5%92%8C%E9%82%A3%E7%A7%8D%E6%B7%B1%E8%93%9D%E8%89%B2%E3%80%82) 所以想问下具体是哪个参数影响目录的颜色？

您那边实现Xshell的主题了吗

**Comment by xiekunwhy** [comment]
没有，但是在设置里面选择xterm就会和xshell差不多（但字体，包括粗斜的调整没那么灵活），但是目录链接的颜色（绿底）实在难看（虽然可以通过设置系统的ls color来改），所以用回xshell了，现在xshell也是全功能对personal用户免费的，只是关闭时候会弹一个窗口几秒钟。
![image](https://github.com/electerm/electerm/assets/17738229/ad29cc9c-e6db-481a-8582-536322447c37)
