### ISSUE TITLE
1.26.2无法连接github，提示空gist，降级1.26.0后没问题

### ISSUE THREAD

**Issue by liyboy** [electerm/electerm#2872]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.26.2-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19045.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.26.2无法连接github，提示空gist，降级1.26.0后没问题

### What should have happened?(期望的结果)

不知道啥原因，希望尽快修复

**Comment by zxdong262** [comment]
最新版应该没问题了
