### ISSUE TITLE
每次打开软件都会自动回车添加一行空内容

### ISSUE THREAD

**Issue by zqxsober** [electerm/electerm#2873]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-x64.dmg

### Platform detail (平台详情)

mac os

### What steps will reproduce the bug?(重新问题的详细步骤)

每次打开软件都会自动回车添加一行空内容
<img width="1536" alt="image" src="https://github.com/electerm/electerm/assets/33095205/e87d4c98-061b-4fca-9650-bcfb20e6e2e6">

### What should have happened?(期望的结果)

期望每次打开不需要产生新的空白行

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否

**Comment by cantona97** [comment]
默认 ExecMac为bash就正常，为zsh就跟楼主一样

**Comment by zxdong262** [comment]
将在下个版本移除
