### ISSUE TITLE
Can't run in Ventura 13.4.1 on M1

### ISSUE THREAD

**Issue by pietrodicaprio** [electerm/electerm#2874]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.26.2-mac-arm64.dmg

### Platform detail (平台详情)

Mac OS ARM (M1 Pro)

### What steps will reproduce the bug?(重新问题的详细步骤)

Download the latest release from brew or from the Release section of GitHub.\
Try to open the app:
![image](https://github.com/electerm/electerm/assets/37634431/013a2007-3856-40b9-921b-ec97cd62206c)

### What should have happened?(期望的结果)

User should be at least able to aknowledge that the app is unsigned and proceed opening it

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

Not if up to date

**Comment by zxdong262** [comment]
Can you try latest release 1.27.0?

**Comment by pietrodicaprio** [comment]
It works! It's clearly slow switching pages, I don't know if it's so visible also on other platforms, but it works!\
Is there a wiki page with the supported SSH private key types? I can't connect with the same key file I use in Termius and other clients

**Comment by zxdong262** [comment]
> It works! It's clearly slow switching pages, I don't know if it's so visible also on other platforms, but it works! Is there a wiki page with the supported SSH private key types? I can't connect with the same key file I use in Termius and other clients

If the key generate with ssh-keygen, should be OK, other than that, may not be supported, it is a known limitation.
