### ISSUE TITLE
1.27.0安装后打开面板是透明的，什么都看不到

### ISSUE THREAD

**Issue by LIHAQI** [electerm/electerm#2876]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.0-win-x64-installer.exe

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

无

### What should have happened?(期望的结果)

无

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

### Additional information(其他任何相关信息)

无

**Comment by wwek** [comment]
问题相同
win10 系统

**Comment by mamengchao** [comment]
同样的问题，win10系统，还有就是更新后新老版本的安装包都启动不了

**Comment by er0603** [comment]
The same issue on Windows 11, after upgrade to v1.27.0

**Comment by vkviyu** [comment]
同样的问题 win11系统 安装版本和压缩版本都存在这个问题

**Comment by er0603** [comment]
> 同样的问题，win10系统，还有就是更新后新老版本的安装包都启动不了

I tried to remove the software through [Settings]-> [Application] and re-installed a 1.26.2-win-x64-installer.exe version. 
Now it can work normally. It seems a temporary solution.

**Comment by wwek** [comment]
> 

yes,   back to version 1.26.2

**Comment by zxdong262** [comment]
抱歉，确实有问题，撤回到1.26.2

**Comment by zxdong262** [comment]
如果回退到1.26有问题，可以试着删除配置数据。if having issue open it, check wiki to delete data folder: https://github.com/electerm/electerm/wiki/Troubleshoot

Mac: rm -rf ~/Library/Application\ Support/electerm*
Linux: rm -rf ~/.config/electerm
Windows: delete %APPDATA%\electerm

**Comment by mianxiangdahai** [comment]
同样的问题，win11系统
