### ISSUE TITLE
1.27.0版本快速命令按钮无法使用

### ISSUE THREAD

**Issue by zhouchitc** [electerm/electerm#2877]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.0-mac-arm64.dmg

### Platform detail (平台详情)

mac os(ARM) Apple M2 Max

### What steps will reproduce the bug?(重新问题的详细步骤)

我从1.26.2升级到1.27.0版本。界面联通后左下角的快速命令无法点开。
<img width="350" alt="image" src="https://github.com/electerm/electerm/assets/11803579/cecc769a-29a4-4c29-91a8-689f6a84123b">

### What should have happened?(期望的结果)

期望快速命令可以正常使用

**Comment by zxdong262** [comment]
1.27有问题，已撤回到1.26.2
