### ISSUE TITLE
macOS 13.4适中安装失败

### ISSUE THREAD

**Issue by Hyingerrr** [electerm/electerm#2879]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

brew cask install electerm

### Platform detail (平台详情)

mac os 13.4

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="1439" alt="image" src="https://github.com/electerm/electerm/assets/38207007/d7be6281-6d2c-417f-b66c-0442aee02a1c">
始终失败，尝试过HOMEBREW_FORCE_BREWED_CURL=1 arch -x86_64 brew install --cask electerm
brew cask install electerm 等都失败。

### What should have happened?(期望的结果)

什么原因？我应该怎么操作安装？

**Comment by zxdong262** [comment]
最新版本有问题，我给删除了，你可以下载dmg 1.26.2版本 https://github.com/electerm/electerm/releases https://sourceforge.net/projects/electerm.mirror/files/

**Comment by zxdong262** [comment]
发布了新版本，现在应该可以了
