### ISSUE TITLE
多个版本软件无法正常打开

### ISSUE THREAD

**Issue by DarkSwords** [electerm/electerm#2887]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.5-win-x64-installer.exe

### Platform detail (平台详情)

windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

![2023-07-19-01：30-948](https://github.com/electerm/electerm/assets/28711483/6c88a269-8823-4f19-a4c9-20be92f8cd11)
好几个版本都会出现这个问题，打开即弹窗如上图，难道是u amd3600有问题，因为另外一台intel安装同样的版本丝滑，甚至都没有出现过这个问题

### What should have happened?(期望的结果)

https://github.com/electerm/electerm/assets/28711483/410963c0-7638-4681-80f8-f680bc5abb74

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

使用Termius、WindTerm、Xshell 7、putty都没有问题

**Comment by zxdong262** [comment]
可以检查一下30974端口是不是被占用了

**Comment by DarkSwords** [comment]
没发现有程序占用
![2023-07-19-13：13-951](https://github.com/electerm/electerm/assets/28711483/a124f143-205b-4977-919b-f8e4940601ac)

**Comment by zxdong262** [comment]
有什么安全设定吗？看错误信息的话就是访问端口被拒绝

**Comment by DarkSwords** [comment]
手动添加防火墙出站，可以打开了，但卡在这个界面了。退回v1.26.2，也一样
![2023-07-19-14：04-952](https://github.com/electerm/electerm/assets/28711483/f4af6f0f-e994-4db5-ae24-16337ccf9ed7)

**Comment by zxdong262** [comment]
用管理员权限运行试试？

**Comment by DarkSwords** [comment]
不知道跟BIOS有关，还是最新版本（v1.27.20）解决的，这次安装可以用。稳！

**Comment by DarkSwords** [comment]
应该更某个服务有关，因为多次重启可以复现
重启后进去桌面马上打开electerm，则没有30974弹窗；
等一阵再打开electerm，则弹窗，猜测这时候某个服务启动了，但netstat -ano | findstr ":30974"却没有显示有关程序。
是否可以添加个修改electerm端口功能

**Comment by DarkSwords** [comment]
**这次真解决了，确定是端口问题**

解决方案从一个帖子上再结合GPT

**管理员**执行以下两条命令后，electerm顺利打开，通过一些工具看到electerm会占用本地30974、30975

```
net stop winnat

net start winnat
```

GPT提示是**Windows NAT**服务问题，但查不到端口占用，另外每次系统重启了都要再执行。于是有了以下措施

[解决30974弹窗问题：](https://user-images.githubusercontent.com/28711483/254448509-6c88a269-8823-4f19-a4c9-20be92f8cd11.png)
`
netsh int ipv4 add excludedportrange protocol=tcp startport=30974 numberofports=1
`
[解决卡在启动界面问题：](https://user-images.githubusercontent.com/28711483/254478610-f4af6f0f-e994-4db5-ae24-16337ccf9ed7.png)
`
netsh int ipv4 add excludedportrange protocol=tcp startport=30975 numberofports=1
`

[参考帖子（windows部分）](https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports)

**Comment by zxdong262** [comment]
> **这次真解决了，确定是端口问题**
> 
> 解决方案从一个帖子上再结合GPT
> 
> **管理员**执行以下两条命令后，electerm顺利打开，通过一些工具看到electerm会占用本地30974、30975
> 
> ```
> net stop winnat
> 
> net start winnat
> ```
> 
> GPT提示是**Windows NAT**服务问题，但查不到端口占用，另外每次系统重启了都要再执行。于是有了以下措施
> 
> [解决30974弹窗问题：](https://user-images.githubusercontent.com/28711483/254448509-6c88a269-8823-4f19-a4c9-20be92f8cd11.png) `netsh int ipv4 add excludedportrange protocol=tcp startport=30974 numberofports=1` [解决卡在启动界面问题：](https://user-images.githubusercontent.com/28711483/254478610-f4af6f0f-e994-4db5-ae24-16337ccf9ed7.png) `netsh int ipv4 add excludedportrange protocol=tcp startport=30975 numberofports=1`
> 
> [参考帖子（windows部分）](https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports)

最新版本支持`electerm -sp 30000`这样设定端口, 可以试试好使不

**Comment by suoc** [comment]
在 windows server 2012R2上报错:

<img width="552" height="147" alt="Image" src="https://github.com/user-attachments/assets/cd9044a2-86d7-46e7-8ad2-74d9c07dc380" />

直接运行也报错:

<img width="1322" height="450" alt="Image" src="https://github.com/user-attachments/assets/da2fc5c6-6428-43c4-8539-ab0d0ee8d474" />

@zxdong262

**Comment by zxdong262** [comment]
> 在 windows server 2012R2上报错:
> 
> <img alt="Image" width="552" height="147" src="https://private-user-images.githubusercontent.com/16681502/499811072-cd9044a2-86d7-46e7-8ad2-74d9c07dc380.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwOTU3MzIsIm5iZiI6MTc2MDA5NTQzMiwicGF0aCI6Ii8xNjY4MTUwMi80OTk4MTEwNzItY2Q5MDQ0YTItODZkNy00NmU3LThhZDItNzRkOWMwN2RjMzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDExMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MmIwNTA3NWFmODEzMTMxM2YzMzRiM2FjNDJjYjVkNDMzNTllNWM2M2M3MTk5ZGQ3YzU2Y2NiYjQwZDM3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kn14XLUA0vFOnZI3vpsr7OfOcQwPsWMRus6ClcNIzqM">
> 直接运行也报错:
> 
> <img alt="Image" width="1322" height="450" src="https://private-user-images.githubusercontent.com/16681502/499811378-da2fc5c6-6428-43c4-8539-ab0d0ee8d474.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwOTU3MzIsIm5iZiI6MTc2MDA5NTQzMiwicGF0aCI6Ii8xNjY4MTUwMi80OTk4MTEzNzgtZGEyZmM1YzYtNjQyOC00M2M0LTg1MzktYWIwZDBlZThkNDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDExMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTY4MWQxODdmMTgyZGIxZjFjOGFmZDgxYWI5YWI5MWU5ZDFhMzZiOTc3YTdiNTU2OGI5OGYwNDhlZmIzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.saoj5mVhR0QdtS9pA3bPwNfiVTq3c-1I6P91qaTNtWU">
> [@zxdong262](https://github.com/zxdong262)

试试win7那个行不行

<img width="1111" height="399" alt="Image" src="https://github.com/user-attachments/assets/ea789c7a-4c53-4c75-a0cb-8ef57786b537" />

**Comment by suoc** [comment]
> > 在 windows server 2012R2上报错:
> > <img alt="Image" width="552" height="147" src="https://private-user-images.githubusercontent.com/16681502/499811072-cd9044a2-86d7-46e7-8ad2-74d9c07dc380.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwOTU3MzIsIm5iZiI6MTc2MDA5NTQzMiwicGF0aCI6Ii8xNjY4MTUwMi80OTk4MTEwNzItY2Q5MDQ0YTItODZkNy00NmU3LThhZDItNzRkOWMwN2RjMzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDExMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MmIwNTA3NWFmODEzMTMxM2YzMzRiM2FjNDJjYjVkNDMzNTllNWM2M2M3MTk5ZGQ3YzU2Y2NiYjQwZDM3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kn14XLUA0vFOnZI3vpsr7OfOcQwPsWMRus6ClcNIzqM">
> > 直接运行也报错:
> > <img alt="Image" width="1322" height="450" src="https://private-user-images.githubusercontent.com/16681502/499811378-da2fc5c6-6428-43c4-8539-ab0d0ee8d474.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwOTU3MzIsIm5iZiI6MTc2MDA5NTQzMiwicGF0aCI6Ii8xNjY4MTUwMi80OTk4MTEzNzgtZGEyZmM1YzYtNjQyOC00M2M0LTg1MzktYWIwZDBlZThkNDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEwVDExMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTY4MWQxODdmMTgyZGIxZjFjOGFmZDgxYWI5YWI5MWU5ZDFhMzZiOTc3YTdiNTU2OGI5OGYwNDhlZmIzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.saoj5mVhR0QdtS9pA3bPwNfiVTq3c-1I6P91qaTNtWU">
> > [[@zxdong262](https://github.com/zxdong262)](https://github.com/zxdong262)
> 
> 试试win7那个行不行
> 
> <img alt="Image" width="1111" height="399" src="https://private-user-images.githubusercontent.com/1641949/499834780-ea789c7a-4c53-4c75-a0cb-8ef57786b537.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxMDE1NjksIm5iZiI6MTc2MDEwMTI2OSwicGF0aCI6Ii8xNjQxOTQ5LzQ5OTgzNDc4MC1lYTc4OWM3YS00YzUzLTRjNzUtYTBjYi04ZWY1Nzc4NmI1MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMTBUMTMwMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzFjZTgyOThkZjc2ZDQ5NDgxMDFmMjhiZWQ3NzE5ZTMxMzYwNjE4YjM0YTdjOTdmNGI2MDJjNDFlMTk4NmY2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7aKCFsDvMiHd4zqSt_Oox08x2a47bFmJmm_AroqjhA0">

不得行
<img width="2232" height="1572" alt="Image" src="https://github.com/user-attachments/assets/5e6b7a10-a205-493d-a501-6581f5457171" />

**Comment by zxdong262** [comment]
那就没办法了，实在太老了
