### ISSUE TITLE
debian信息多处显示错误

### ISSUE THREAD

**Issue by cangkuai** [electerm/electerm#2888]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.5-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

在连接debian11时内存使用比例直接不显示，Activities里面显示进程的内存使用量单位也有错误，比如占了我1.4g的一个java进程却显示之用了1.4m（其他进程也是这样不是特例）

### What should have happened?(期望的结果)

显示正常

**Comment by zxdong262** [comment]
可以运行`ps --no-headers -o pid,user,%cpu,size,command ax | sort -b -k3 -r`给个输出看看不，我看看格式有什么不同，以及`free -h`的输出

**Comment by zxdong262** [comment]
明白了，感谢反馈，将在下个版本修复
