### ISSUE TITLE
建议像xshell那样，搜索的内容，能自动全部高亮出来，不用再一个一个点下一个

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#2892]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)
![image](https://github.com/electerm/electerm/assets/13861904/8c88fdce-806e-4eed-8b41-5cc2ae8616b9)

建议像xshell那样，搜索的内容，能自动全部高亮出来，不用再一个一个点下一个

**Comment by czxin788** [comment]
这个搜索自动显示功能目前已经在electerm实现了。
但electerm直接显示的是session最上面的搜索结果。
能够修改成，搜索结果优先显示最底下的。

因为我们一般都是从下往上找搜索结果，很少从上往下看搜索结果

**Comment by zxdong262** [comment]
> 这个搜索自动显示功能目前已经在electerm实现了。 但electerm直接显示的是session最上面的搜索结果。 能够修改成，搜索结果优先显示最底下的。
> 
> 因为我们一般都是从下往上找搜索结果，很少从上往下看搜索结果

感谢反馈，将在下个版本改为从底部开始匹配
