### ISSUE TITLE
建议精简UI主题

### ISSUE THREAD

**Issue by fszok** [electerm/electerm#2905]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

UI主题搞了一大堆,但感觉都差不多,毫无意义,建议保留十个以内就可以了.搞这不么多区别不大的UI主题实不想不明白是为了什么?有什么意义呢?

**Comment by zxdong262** [comment]
有一个开源的iterm2主题库，只是把这个主题库全部导入进来了。https://github.com/mbadolato/iTerm2-Color-Schemes，

**Comment by niko-liu** [comment]
主题选择又没有预览，搞一大堆没用的
