### ISSUE TITLE
[Bug] ssh新连接无视代理启用设置使用代理连接

### ISSUE THREAD

**Issue by Yurinann** [electerm/electerm#2907]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.20-win-x64-installer.exe

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 使用 1.27.20 版本打开软件
2. 创建新连接

### What should have happened?(期望的结果)

代理设置能够正常被启用/禁用

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否

### Additional information(其他任何相关信息)

版本回退至 1.27.5 则无此问题

**Comment by zxdong262** [comment]
将在下个版本修复，临时方案可以删除代理来关闭代理
