### ISSUE TITLE
你好，请问这个放大按钮，为什么点击之后，百分比数字没有变化？

### ISSUE THREAD

**Issue by ioplmk** [electerm/electerm#2908]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

你好，请问这个放大按钮，为什么点击之后，百分比数字没有变化？还有这个配置可以持久化吗？就是重启应用之后保持之前的缩放比。
![Snipaste_2023-08-03_13-05-09](https://github.com/electerm/electerm/assets/93701868/76c905fa-8a04-422e-b495-866b2fb3d097)

**Comment by zxdong262** [comment]
100%那个点击就回到100%状态，左侧的100表示放大程度，将在下个版本加入持久化
