### ISSUE TITLE
光标选中复制一行长文本会自动添加换行符

### ISSUE THREAD

**Issue by tudoujunha** [electerm/electerm#2909]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.30-win-x64.appx

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

一行较长的文字内容显示为多行的时候，选中文字复制会自动添加换行符，导致一行内容被分割成两行。

选中复制：
![image](https://github.com/electerm/electerm/assets/131859738/eb20cf64-eab6-45da-ab91-8648a931227e)
粘贴到命令行：
![image](https://github.com/electerm/electerm/assets/131859738/27b73212-934c-4fe5-a27d-04b9f7bcf89c)

复制到文本编辑器可以看到复制的一行文字变成了两行：
![image](https://github.com/electerm/electerm/assets/131859738/f30f25f5-6c46-49ec-baf7-f93f43a8db6f)

### What should have happened?(期望的结果)

一行较长的文字即使显示为多行，选中文字复制也应该没有换行符，仍然是一行完整的内容。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否。比如 windows powershell 复制显示为多行的内容，复制后仍然是一行完整的内容。

**Comment by czxin788** [comment]
我也遇到这个问题了，一行内容，复制粘贴后，变成多行了

**Comment by zxdong262** [comment]
我试了一模一样的文字，没有复现，正常识别为一行，设置里有什么非默认的设置吗？

**Comment by tudoujunha** [comment]
@zxdong262 复制的是显示的路径，路径过长一行显示不完整显示为两行的时候，复制下来就会为两行。
![image](https://github.com/electerm/electerm/assets/131859738/ce2c1d4a-a9b0-48df-bea8-a6ea88477898)

**Comment by tudoujunha** [comment]
复制的是显示的路径，路径过长一行显示不完整显示为两行的时候，复制下来就会为两行。
https://user-images.githubusercontent.com/131859738/263524669-ce2c1d4a-a9b0-48df-bea8-a6ea88477898.png

![image](https://github.com/electerm/electerm/assets/131859738/056d9c43-3346-4abf-a9c9-a49d41ad9ff5)

**Comment by tudoujunha** [comment]
复制的是显示的路径，路径过长一行显示不完整显示为两行的时候，复制下来就会为两行。
![image](https://github.com/electerm/electerm/assets/131859738/de5177c9-5753-4409-bd10-7b91d8ae0a8c)


![image](https://github.com/electerm/electerm/assets/131859738/056d9c43-3346-4abf-a9c9-a49d41ad9ff5)

设置里面基本没改什么：
![image](https://github.com/electerm/electerm/assets/131859738/55d4d2dd-dc60-48d4-8de4-ed9e65f3ced9)

**Comment by zxdong262** [comment]
我知道了，右键自动粘贴的问题，手动粘贴就没问题

**Comment by tudoujunha** [comment]
不是自动粘贴的问题，我用快捷键粘贴也是一样的。
更关键的是，复制出来就已经是 两行了，在剪贴板就可以看得到。
![image](https://github.com/electerm/electerm/assets/131859738/0e3cde9f-31ea-4ecc-9c90-a936f15e0d03)
所以是复制的问题。

**Comment by SimonFuInSky** [comment]
2024年了，也是碰到这个问题，快修复一下吧

**Comment by SimonFuInSky** [comment]
截图
![image](https://github.com/electerm/electerm/assets/6703174/4a0b9900-b816-4805-bc62-b8261bd1ccd5)
![image](https://github.com/electerm/electerm/assets/6703174/3b7f9809-076e-4d53-8632-89b365d1b522)

**Comment by zxdong262** [comment]
可以试试最新版吗，我试了没有这个问题了

**Comment by Hoshiya233** [comment]
几个月前确实有这个问题，我记不清日期了。不过今天看了下1.40.18版本已经不存在这个问题了
