### ISSUE TITLE
在macOs Ventura系统中开启台前调度 切换electerm窗口与其他窗口的时候动画会卡

### ISSUE THREAD

**Issue by HuangWeiHaii** [electerm/electerm#2919]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

<img width="294" alt="image" src="https://github.com/electerm/electerm/assets/44046269/d92975d0-1a83-4e32-b8d3-7d3eb270686b">

**Comment by HuangWeiHaii** [comment]
<img width="280" alt="image" src="https://github.com/electerm/electerm/assets/44046269/0a474309-b5ad-4e14-be36-a365d35d0184">

**Comment by zxdong262** [comment]
设置里有个使用系统标题栏，可以开启试试吗？
