### ISSUE TITLE
mac M2pro 打开左侧菜单显示“只能在主窗口中执行此操作”

### ISSUE THREAD

**Issue by hh-fly** [electerm/electerm#2923]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.27.30-mac-arm64.dmg

### Platform detail (平台详情)

MacBook m2Pro

### What steps will reproduce the bug?(重新问题的详细步骤)

打开左侧菜单栏会显示“只能在主窗口中执行此操作”（确定只有一个窗口）
<img width="783" alt="image" src="https://github.com/electerm/electerm/assets/45842282/b59bac9e-af3d-4a4f-b294-20d894eff3ef">

### What should have happened?(期望的结果)

打开对应的菜单

**Comment by zxdong262** [comment]
可以重启电脑试试吗？
