### ISSUE TITLE
1.28.0版本无法启动  Version 1.28.0 won't start

### ISSUE THREAD

**Issue by ame-yu** [electerm/electerm#2924]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.28.0-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64
Windows11 22H2

### What steps will reproduce the bug?(重新问题的详细步骤)

电脑上首次安装（非升级安装），选择为所有用户安装，安装完成后启动卡在启动页面

Install for all users and then get stuck on the startup page

### What should have happened?(期望的结果)

正常启动

Starts up properly

### Additional information(其他任何相关信息)

<img width="1525" alt="image" src="https://github.com/electerm/electerm/assets/42380973/c3aaba49-fb48-48d7-9392-d7aff740f6d2">

Version 1.27.30 does not have this issue

**Comment by hityb** [comment]
follow

**Comment by cBigglesworth** [comment]
win 11 下载后也启动不了，Windows 11 专业版 22621.1778

**Comment by zxdong262** [comment]
得清理一下缓存，删除C:\Users\你的用户名\AppData\Roaming\electerm下面的文件，除了users目录

**Comment by zxdong262** [comment]
请问是从哪个版本升级到1.28的呢

**Comment by ame-yu** [comment]
新电脑直接安装1.28.0无法运行，先安装1.27.30然后升级到1.28.0可以运行。

**Comment by ame-yu** [comment]
1.28.1版本问题已修复
