### ISSUE TITLE
新链接时，控制台会默认带有输出信息

### ISSUE THREAD

**Issue by lvwshuai** [electerm/electerm#2925]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.28.1

### Platform detail (平台详情)

macOS M2  13.5

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="1293" alt="image" src="https://github.com/electerm/electerm/assets/2986900/eb39e426-fde7-45bd-9dd9-8f5c955c2dfa">
启动页点新建链接，或是启动时默认打开新链接，则控制台会不停的输出信息，也没有压到键盘
<img width="840" alt="image" src="https://github.com/electerm/electerm/assets/2986900/1ec46b85-75bb-47d1-8bdc-8e207ad68c36">

### What should have happened?(期望的结果)

希望打开时不输出这些无用信息

**Comment by zxdong262** [comment]
是历史记录，如果不想留记录，关闭之前右键清空就没有了

**Comment by ddlzr** [comment]
> 
同样的问题，清屏后再打开，还是会出现。

**Comment by ddlzr** [comment]
> 是历史记录，如果不想留记录，关闭之前右键清空就没有了

同样的问题，清屏不起作用，清屏后再打开，还是会出现。
