### ISSUE TITLE
web server may start after app start, make webview load fail

### ISSUE THREAD

**Issue by jingle0927** [electerm/electerm#293]
刚升级体验正常，用半天后，再次打开就空白了。
![_desktop_20180129143118](https://user-images.githubusercontent.com/26103116/35496637-d123561a-0501-11e8-80ae-2fbb86c44219.gif)

**Comment by zxdong262** [comment]
windows?
linux?

**Comment by jingle0927** [comment]
@zxdong262  linux发行版  [deepin](www.deepin.org)
