### ISSUE TITLE
书签中主机地址如果填域名等非数字的地址都会报错

### ISSUE THREAD

**Issue by JackHuang90** [electerm/electerm#2930]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.28.1-linux-amd64.snap

### Platform detail (平台详情)

6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

书签中主机地址如果填域名等非数字的地址都会报错，进程卡死，必须强制关闭。
A JavaScript error occurred in the main process
![image](https://github.com/electerm/electerm/assets/32409853/19a2e276-e416-42d9-958e-aeb5fca3ed9d)

### What should have happened?(期望的结果)

在主机地址输入域名不应该报错卡死

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

未尝试

### Additional information(其他任何相关信息)

无

**Comment by zxdong262** [comment]
发布了最新版本，修复了这个问题，感谢提交

**Comment by JackHuang90** [comment]
@zxdong262 感谢！但是更新了1.28.3后,书签的主机地址没这个报错了，但是在命令行里面如果点击存在链接的url也会报这个错。
![image](https://github.com/electerm/electerm/assets/32409853/d3c5c090-0994-403f-a5f5-463492022df8)
