### ISSUE TITLE
Hi, can more split screen be considered?

### ISSUE THREAD

**Issue by godaizhan** [electerm/electerm#2935]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

At present, the split screen can only be divided up and down, and multiple screens cannot be divided, so it seems that the window is not enough for development and debugging! , if you want more, you can only create new tabs, which requires switching screens back and forth, which is very time-consuming, and it is not conducive for developers to observe details at the same time

At present, it can only be allocated in this way, and it cannot be split into multiple screens.
![image](https://github.com/electerm/electerm/assets/103105164/3d1d01e2-da4a-41ef-a97b-29e8de10de2f)

Hope to support split screen like this
![image](https://github.com/electerm/electerm/assets/103105164/1442e3ca-c4f1-4c86-8bf5-526aa4328c55)
![image](https://github.com/electerm/electerm/assets/103105164/48d68272-02a3-4bc0-9a72-0fa6ced9ebb5)

Thank you so much

**Comment by zxdong262** [comment]
Latest release now support layout: 1x2, 1x3, 2x2 views
