### ISSUE TITLE
tsz报错

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#2936]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.28.4-mac-x64.dmg

### Platform detail (平台详情)

mac x64

### What steps will reproduce the bug?(重新问题的详细步骤)

tsz /etc/passwd

### What should have happened?(期望的结果)

成功下载文件

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

root@808171deb106:/opt/python/discuz# tsz /etc/passwd
::TRZSZ:TRANSFER:S:1.1.5:9267520154800
Write Downloads/passwd error: NotAllowedError: The request is not allowed by the user agent or the platform in the current context.

**Comment by xxoxx** [comment]
<img width="1266" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/06451e88-6a17-450f-9626-1562a82e14a6">

**Comment by xxoxx** [comment]
之前的版本是正常的， 升级到这个版本就报错了， 不能成功下载文件

**Comment by xxoxx** [comment]
trz能正常工作

**Comment by xxoxx** [comment]
@zxdong262   1.29.2版本  此问题还存在哦，  我对tsz比较刚需求，麻烦尽快解决，谢谢

**Comment by zxdong262** [comment]
> @zxdong262 1.29.2版本 此问题还存在哦， 我对tsz比较刚需求，麻烦尽快解决，谢谢

sz行不行

**Comment by zxdong262** [comment]
> @zxdong262 1.29.2版本 此问题还存在哦， 我对tsz比较刚需求，麻烦尽快解决，谢谢

将在下个版本修复
