### ISSUE TITLE
会话保持时长太短

### ISSUE THREAD

**Issue by lovek8s** [electerm/electerm#2939]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

目前最大值是20000ms,是否可以自定义或者增加上限

**Comment by zxdong262** [comment]
那个不是最大时长的意思，而是发送保活信号的间隔，越短可能更有利于保活，可以试试

**Comment by zxdong262** [comment]
可以试试这个：
```
Creating ~/.ssh/config with this contents kept connection alive.

Host *
ServerAliveInterval 30
ServerAliveCountMax 2
```

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/2998 新版支持设置keepalive间隔为0，似乎可以解决问题
