### ISSUE TITLE
能不能改一下图标

### ISSUE THREAD

**Issue by MrZhangWeiCe** [electerm/electerm#2944]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

能不能改一下图标，改成现在mac新系统中的 圆角设计的呢

**Comment by wangjiawen2013** [comment]
@zxdong262 
我也同意上面的看法，圆角图标现在很流行，现在的电脑软件图标大多都是圆角的，windterm的直角显得太突兀了。现在的主流审美就是图标讲究平滑和流线。生活中的汽车、飞船、桌椅、碗筷等现在也都是设计成流线型的。这是我的桌面：

<img width="306" height="416" alt="Image" src="https://github.com/user-attachments/assets/90ff950b-2c20-454f-9dff-2be1f713ce11" />

下面是一个jupyterlab的圆角图标，希望您能将直角改为圆角，现在的作图软都有这种功能。

<img width="775" height="461" alt="Image" src="https://github.com/user-attachments/assets/bf1d9f1d-272c-4b22-b355-ef19789e993d" />
