### ISSUE TITLE
mac系统,cmd + shift + r会重启客户端,导致所有打开的连接关闭

### ISSUE THREAD

**Issue by shenmuegit** [electerm/electerm#2946]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

为什么会做出一个隐藏的快捷键命令并且不可修改呢?
有什么哲学上的用意吗?
我已经不止一次在electerm误操作使用cmd + shift + r导致10几个连接和当前的设置丢失.

**Comment by zxdong262** [comment]
应该是electron默认的刷新页面快捷键，我来把它屏蔽掉，下个版本
