### ISSUE TITLE
update bug because of theme（从1.28.4升级至1.29.5出错，发现原因是theme主题文件不兼容）

### ISSUE THREAD

**Issue by WLaoDuo** [electerm/electerm#2952]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.29.2-win-x64-installer.exe,electerm-1.29.4-win-x64-installer.exe,electerm-1.29.5-win-x64-installer.exe

### Platform detail (平台详情)

win11,Microsoft Windows NT 10.0.22621.0,x64

### What steps will reproduce the bug?(重新问题的详细步骤)

从1.28.4更新至1.29.x，测试过1.29.2/1.29.4/1.29.5，更新完毕后均无法打开。
![图片](https://github.com/electerm/electerm/assets/69497874/893a0594-2f42-4132-8563-dc902448ceb1)

### What should have happened?(期望的结果)

正常启动electerm

### Additional information(其他任何相关信息)

查看了更新日志，1.28.4至1.29.x最大的变化是更新了antd 5。推测是更新antd v5造成的。

**Comment by zxdong262** [comment]
可以试试v1.30.9吗？ https://github.com/electerm/electerm/releases/tag/v1.30.9

**Comment by WLaoDuo** [comment]
> 可以试试v1.30.9吗？ https://github.com/electerm/electerm/releases/tag/v1.30.9
测试换到win7虚拟机内可以安装。遂确认您的安装包没问题，是我的环境有问题。遂使用https://github.com/Klocman/Bulk-Crap-Uninstaller/ 卸载并清理C盘残余文件，发现之前残留了不少文件，全部清除后可以正常安装并启动。

**Comment by zxdong262** [comment]
> Fwarn=#E55934

可能这里多了一个`F`导致的

**Comment by zxdong262** [comment]
不过这确实是个问题，需要加一个验证，确保符合格式

**Comment by zxdong262** [comment]
还有一处
```
error=#EF476 -> error=#EF476F
```
