### ISSUE TITLE
默认新链接终端触摸板点击乱码

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#2954]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.30.9-mac-x64.dmg

### Platform detail (平台详情)

mac os(x64)

### What steps will reproduce the bug?(重新问题的详细步骤)

升级到1.30.9版本后，默认新链接终端触摸板点击乱码
<img width="925" alt="WX20230906-100743@2x" src="https://github.com/electerm/electerm/assets/14172278/a599e4f2-a911-4ba4-aa38-274fde11e837">

### What should have happened?(期望的结果)

无

**Comment by zxdong262** [comment]
请问你前一个版本号是多少？

**Comment by bb7788** [comment]
@zxdong262  这个升级之前没注意看多少版本的。

**Comment by zxdong262** [comment]
> @zxdong262 这个升级之前没注意看多少版本的。

方便试试之前的版本不,27,28,29有哪个可以吗，还是说第一次用触摸设备？

**Comment by zxdong262** [comment]
可能得处理一下触摸事件 https://stackoverflow.com/questions/1517924/javascript-mapping-touch-events-to-mouse-events

**Comment by bb7788** [comment]
刚才升级遇到这个问题，#3035，测试了下 27,28,29版本，都是卡在logo那里进不去，然后我又测试了下1.30.9版本，可以正常进入同时，默认新链接终端触摸板点击乱码的问题也不存在了 😄
@zxdong262

**Comment by zxdong262** [comment]
> 刚才升级遇到这个问题，#3035，测试了下 27,28,29版本，都是卡在logo那里进不去，然后我又测试了下1.30.9版本，可以正常进入，并且默认新链接终端触摸板点击乱码的问题也不存在了 😄 @zxdong262

1.34.20版本可以吗？

**Comment by bb7788** [comment]
> > 刚才升级遇到这个问题，#3035，测试了下 27,28,29版本，都是卡在logo那里进不去，然后我又测试了下1.30.9版本，可以正常进入，并且默认新链接终端触摸板点击乱码的问题也不存在了 😄 @zxdong262
> 
> 1.34.20版本可以吗？

这个版本进不去，一直卡在logo那里

**Comment by zxdong262** [comment]
> > > 刚才升级遇到这个问题，#3035，测试了下 27,28,29版本，都是卡在logo那里进不去，然后我又测试了下1.30.9版本，可以正常进入，并且默认新链接终端触摸板点击乱码的问题也不存在了 😄 @zxdong262
> > 
> > 
> > 1.34.20版本可以吗？
> 
> 这个版本进不去，一直卡在logo那里

1.34.26可以吗？

**Comment by bb7788** [comment]
> > > > 刚才升级遇到这个问题，#3035，测试了下 27,28,29版本，都是卡在logo那里进不去，然后我又测试了下1.30.9版本，可以正常进入，并且默认新链接终端触摸板点击乱码的问题也不存在了 😄 @zxdong262
> > > 
> > > 
> > > 1.34.20版本可以吗？
> > 
> > 
> > 这个版本进不去，一直卡在logo那里
> 
> 1.34.26可以吗？

1.34.26 打不开，还是卡在logo那里

```
/Applications/electerm.app/Contents/MacOS/electerm           
09:47:36 debug › electerm start
(node:76299) UnhandledPromiseRejectionWarning: Error: Attempted to register a second handler for 'async'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:2:105966)
    at initIpc (/Applications/electerm.app/Contents/Resources/app.asar/lib/ipc.js:163:11)
    at exports.createWindow (/Applications/electerm.app/Contents/Resources/app.asar/lib/create-window.js:44:3)
(Use `electerm --trace-warnings ...` to show where the warning was created)
(node:76299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

<img width="850" alt="image" src="https://github.com/electerm/electerm/assets/14172278/29daf03a-cf2a-4119-a24d-9a8a13a1a627">

**Comment by bb7788** [comment]
有什么办法能把书签里的链接导出来吗，我想都清掉，重新装下

**Comment by zxdong262** [comment]
可以在同步界面把数据全部导出/导入，书签界面也有导入导出按钮

**Comment by zxdong262** [comment]
可以试试重启之后再运行一下1.34.30不

**Comment by bb7788** [comment]
> 可以试试重启电脑之后再运行一下1.34.30不

1.34.30 正常了，但是默认连接又触摸板乱码了，不过没什么影响，非常感谢😁

<img width="841" alt="image" src="https://github.com/electerm/electerm/assets/14172278/9dfa9c95-a55c-4f3f-9fb4-46c34d17b72c">

**Comment by bb7788** [comment]
升级1.37.126后没有出现触摸板点击乱码
