### ISSUE TITLE
Stuck on the connecting screen under certain circumstances

### ISSUE THREAD

**Issue by mio-19** [electerm/electerm#2956]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.30.9-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

Add a bookmark for 192.168.8.167 and connect it.
卡在这里
![image](https://github.com/electerm/electerm/assets/57285379/4ad1cdb7-5134-4b7d-aa0c-c96e58808e9f)

### What should have happened?(期望的结果)

Ask for a password

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

Windows自带的ssh client可以正常连接，使用~/.ssh/id_rsa下的私钥

### Additional information(其他任何相关信息)

Microsoft Store安装的版本有同样的结果。

**Comment by zxdong262** [comment]
![Screen Shot 2023-09-07 at 08 50 07](https://github.com/electerm/electerm/assets/1641949/f51327bb-878a-4420-b47d-93631a2c838a)
导入了私钥吗

**Comment by zxdong262** [comment]
最新版在没有密码时候会自动读取~/.ssh/挨个尝试
