### ISSUE TITLE
关于Mac版本关闭/最小化/最大化在右上角的问题

### ISSUE THREAD

**Issue by Astry-l** [electerm/electerm#2963]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

网上搜了一圈都在推荐大佬做的这个终端软件，本人mac多年老用户，刚打开居然发现关闭/最小化/最大化居然是和windows保持一致在右上角，很不协调，如果大佬有空的话建议放在左上角和mac保持一致，另外祝大佬越来越好！

**Comment by zxdong262** [comment]
可以在设置页面设置使用系统标题栏，这样就是跟其他mac软件一样了
