### ISSUE TITLE
便携版似乎没有真正意义上生效

### ISSUE THREAD

**Issue by suiyueou** [electerm/electerm#2966]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.31.1-win-x64.tar.gz

### Platform detail (平台详情)

Windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

自 [v1.28.1](https://github.com/electerm/electerm/releases/tag/v1.28.1) 引入的 [Support portable in Windows OS #2916](https://github.com/electerm/electerm/pull/2916) 似乎没有真正意义上生效。

因为我在使用最新版 [v1.31.1](https://github.com/electerm/electerm/releases/tag/v1.31.1) 的免安装便携版过程中发现 `electerm.exe` 同级目录下并没有保存相关的配置文件信息，electerm 依旧是前往 `C:\Users\username\AppData\Roaming\electerm` 下读取。

### What should have happened?(期望的结果)

理想中的 `portable` 便携版应该是在同一个目录中（electerm.exe 同级、相对路径下）存储相关的配置文件信息。

**Comment by zxdong262** [comment]
要在设置那里点一下 便携化 按钮

**Comment by suiyueou** [comment]
> 要在设置那里点一下 便携化 按钮

看到啦，感谢提醒（！

但是为什么不是默认便携化呢？毕竟本身不就是免安装（压缩包解压）便携版嘛（？

**Comment by zxdong262** [comment]
> > 要在设置那里点一下 便携化 按钮
> 
> 看到啦，感谢提醒（！
> 
> 但是为什么不是默认便携化呢？毕竟本身不就是免安装（压缩包解压）便携版嘛（？

考虑兼容之前的用户，用户下载这个版本未必是期望这个是便携版。也许可以专门加一个便携版提供下载。

**Comment by suiyueou** [comment]
> 考虑兼容之前的用户，用户下载这个版本未必是期望这个是便携版。也许可以专门加一个便携版提供下载。

期待（~

**Comment by zxdong262** [comment]
> > 考虑兼容之前的用户，用户下载这个版本未必是期望这个是便携版。也许可以专门加一个便携版提供下载。
> 
> 期待（~

最新版已提供专门的便携版下载。

**Comment by suiyueou** [comment]
> 最新版已提供专门的便携版下载。

看到啦，非常感谢（~
