### ISSUE TITLE
无法保存修改老版本导出导入的书签

### ISSUE THREAD

**Issue by suiyueou** [electerm/electerm#2967]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.31.1-win-x64.tar.gz and electerm-1.23.22-win-x64-installer.exe

### Platform detail (平台详情)

Windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

我刚刚准备从 electerm-1.23.22-win-x64-installer.exe 版本升级更换至先前版本更新说明里令人兴奋的 portable 免安装便携版 [v1.31.1](https://github.com/electerm/electerm/releases/tag/v1.31.1)。

卸载清空前我一键导出了相关的配置文件，并在解压升级后再次导入，成功导入后便是测试书签是否可行，测试过程中发现了一个书签信息有点老旧，便准备修改更新，但是发现修改完后无法保存，点击保存无反应。

但是新版本中新建的书签没有这个问题，导入导出后亦可以随意修改保存。

### What should have happened?(期望的结果)

老版本导出导入新版本后的书签可以正常修改保存。

**Comment by zxdong262** [comment]
打开electerm.exe在设置里点击“使其便携“就会把数据都转到electerm.exe同目录下名为`electerm`的文件夹,直接备份保存这个electerm文件夹也是可以的

**Comment by suiyueou** [comment]
> 打开electerm.exe在设置里点击“使其便携“就会把数据都转到electerm.exe同目录下名为`electerm`的文件夹,直接备份保存这个electerm文件夹也是可以的

嗯，这个我在另一个 issue 里知道了

但是问题是之前老版本导出并导入到新版本的书签在修改后无法正常保存，哪怕是复制也不行，似乎只能通过一个一个手动截图然后重新创建（˃ ˄ ˂̥̥

**Comment by zxdong262** [comment]
同步那里也有一个导出导入,可以试试那个吗？

**Comment by suiyueou** [comment]
> 同步那里也有一个导出导入,可以试试那个吗？

我就是在同步界面进行的一键导出导入（

**Comment by suiyueou** [comment]
不论是 `设置同步` 界面的一键导出导入，还是书签页单独导出导入都是无法正常修改后保存。

我甚至试图在老版本导出并导入新版后，在新版里重新导出后再次导入，也是一样的结果。

且似乎只有书签如此，至少快速命令的修改保存是正常的（~

**Comment by zxdong262** [comment]
方便发我一份脱敏的样例导出数据不，我想看看哪里出了问题，如果可以的话请发zxdong@gmail.com

**Comment by suiyueou** [comment]
> 方便发我一份脱敏的样例导出数据不，我想看看哪里出了问题，如果可以的话请发[zxdong@gmail.com](mailto:zxdong@gmail.com)

已发送（~
