### ISSUE TITLE
ssh <> sftp 切换刷新文件功能不生效

### ISSUE THREAD

**Issue by ioplmk** [electerm/electerm#2969]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.31.1-win-x64-installer.exe

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

从ssh页面切换到sftp

### What should have happened?(期望的结果)

从ssh页面切换到sftp刷新本地文件目录和远程文件目录

**Comment by zxdong262** [comment]
需要在设置里开启切换到sftp自动刷新

**Comment by ioplmk** [comment]
> 需要在设置里开启切换到sftp自动刷新

👍👍👍现在可以了
![IMG_20230911_171559.jpg](https://github.com/electerm/electerm/assets/93701868/33071275-ce1a-433c-af57-c869473af85b)

这个配置项还没有汉化

**Comment by zxdong262** [comment]
> > 需要在设置里开启切换到sftp自动刷新
> 
> 👍👍👍现在可以了 ![IMG_20230911_171559.jpg](https://user-images.githubusercontent.com/93701868/266970826-33071275-ce1a-433c-af57-c869473af85b.jpg)
> 
> 这个配置项还没有汉化

最新版修复了

**Comment by ioplmk** [comment]
> > > 需要在设置里开启切换到sftp自动刷新
> > 
> > 👍👍👍现在可以了 ![IMG_20230911_171559.jpg](https://user-images.githubusercontent.com/93701868/266970826-33071275-ce1a-433c-af57-c869473af85b.jpg)
> > 
> > 这个配置项还没有汉化
> 
> 最新版修复了

😁👍
