### ISSUE TITLE
shift 多选删除问题

### ISSUE THREAD

**Issue by fangcongyang** [electerm/electerm#2971]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.32.6

### Platform detail (平台详情)

windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/42265255/d1dcf5e7-f0e0-4a72-8e84-832c31afdbc3)
前面提交的会重复统计删除

### What should have happened?(期望的结果)

只显示选中的五条

**Comment by zxdong262** [comment]
方便详细描述下怎么复现吗？

**Comment by fangcongyang** [comment]
先多选，点删除。再多选，点删除。第一次删除的文件会在第二次的删除列表里面。

**Comment by fangcongyang** [comment]
> 方便详细描述下怎么复现吗？

先多选，点删除。再多选，点删除。第一次删除的文件会在第二次的删除列表里面。

**Comment by zxdong262** [comment]
> > 方便详细描述下怎么复现吗？
> 
> 先多选，点删除。再多选，点删除。第一次删除的文件会在第二次的删除列表里面。

按这个操作没有复现，可能哪个细节我没有掌握，方便做个视频或者看看哪个操作可能会被忽略？

**Comment by fangcongyang** [comment]
> > > 方便详细描述下怎么复现吗？
> > 
> > 
> > 先多选，点删除。再多选，点删除。第一次删除的文件会在第二次的删除列表里面。
> 
> 按这个操作没有复现，可能哪个细节我没有掌握，方便做个视频或者看看哪个操作可能会被忽略？

我也复现不了，忘了怎么操作导致的这个问题了，后面再遇到，到时候我记录下。

**Comment by fangcongyang** [comment]
> > > 方便详细描述下怎么复现吗？
> > 
> > 
> > 先多选，点删除。再多选，点删除。第一次删除的文件会在第二次的删除列表里面。
> 
> 按这个操作没有复现，可能哪个细节我没有掌握，方便做个视频或者看看哪个操作可能会被忽略？

![image](https://github.com/electerm/electerm/assets/42265255/612f73d4-5b49-4416-a408-d27a0688b8f0)
我切换文件夹之后就有这个问题。。。
而且第一进去我选择两个文件，提示我有三个选中文件。

**Comment by fangcongyang** [comment]
![image](https://github.com/electerm/electerm/assets/42265255/62e68674-ec5b-45a8-884b-f6df3cadb61d)

**Comment by zxdong262** [comment]
切换文件夹还是复现不了，可以重启一下程序从头操作看看这么复现不？

**Comment by zxdong262** [comment]
> > 切换文件夹还是复现不了，可以重启一下程序从头操作看看这么复现不？
> 
> 没做其他操作，我用的ctrl不是shift。

哦复现了，ctrl选中后切换文件夹，感谢反馈，将在下个版本修复
