### ISSUE TITLE
快速命令不正常的收起

### ISSUE THREAD

**Issue by 2273267033zzz** [electerm/electerm#2972]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.32.6-mac-arm64.dmg

### Platform detail (平台详情)

M1 Mac book 

### What steps will reproduce the bug?(重新问题的详细步骤)

我记录了很多的快速命令，然后当鼠标放在搜索框开始输入的时候，由于第一个字母查不到对应的快速命令，导致快速命令的菜单变小了，由于菜单变小了，鼠标焦点不在菜单上了，就又导致整个快速命令菜单直接收起了，导致我只能每次先点击锁定按钮，但锁定状态每次打开软件都会重新重置。

### What should have happened?(期望的结果)

当搜索框里有数据时，不管鼠标焦点是否在菜单上，快速命令菜单都不应该收起

**Comment by 2273267033zzz** [comment]
<img width="1642" alt="image" src="https://github.com/electerm/electerm/assets/50507638/6e7e3f72-a183-4e0e-a068-09116c891f69">

**Comment by 2273267033zzz** [comment]
QQ20230912-102339-HD.mp4

**Comment by 2273267033zzz** [comment]
https://github.com/electerm/electerm/assets/50507638/133e5db7-ba20-45da-b4f2-f33228f0e23e

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
