### ISSUE TITLE
启动的时候视图最小化，放大后不能保存设置吗？每次启动都最小化了，怎么解决？

### ISSUE THREAD

**Issue by darqiu** [electerm/electerm#2973]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.32.6-mac-arm64.dmg

### Platform detail (平台详情)

mac os(ARM or x64)

### What steps will reproduce the bug?(重新问题的详细步骤)

启动，视图字体很小。用 command 和 + 放大后，关闭 electerm 。再重新运行，还是最小化，没法保存

### What should have happened?(期望的结果)

希望每次打开的时候是最后的视图和字体大小

**Comment by zxdong262** [comment]
将在下个版本修复，点击左上角e图标菜单里的缩放是会记住的
