### ISSUE TITLE
vim分屏切换快捷键ctrl+w无效

### ISSUE THREAD

**Issue by mumingwu** [electerm/electerm#2978]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

vim分屏切换快捷键ctrl+w无效

### Platform detail (平台详情)

Windows10系统

### What steps will reproduce the bug?(重新问题的详细步骤)

vim分屏切换快捷键ctrl+w无效

### What should have happened?(期望的结果)

快捷键ctrl+w实现vim分屏切换

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

非常重视此类问题

**Comment by zxdong262** [comment]
目前分屏的快捷键目前是ctrol + /, 以后会加入快捷键自定义，就可以自行设定了

**Comment by mumingwu** [comment]
感谢答复，现在的问题是vim分屏后，使用Ctrl+w快捷捷无法在分屏之间切换，考虑是快捷键之间存在冲突，在cmd.exe上可以使用vim分屏切换功能







在 2023-09-13 14:05:08，"ZHAO Xudong" ***@***.***> 写道：

目前分屏的快捷键目前是ctrol + /, 以后会加入快捷键自定义，就可以自行设定了

**Comment by zxdong262** [comment]
> 感谢答复，现在的问题是vim分屏后，使用Ctrl+w快捷捷无法在分屏之间切换，考虑是快捷键之间存在冲突，在cmd.exe上可以使用vim分屏切换功能 在 2023-09-13 14:05:08，"ZHAO Xudong" ***@***.***> 写道： 目前分屏的快捷键目前是ctrol + /, 以后会加入快捷键自定义，就可以自行设定了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

哦，我搞错了

**Comment by zxdong262** [comment]
将在下个版本加入快捷键设置页面 https://github.com/electerm/electerm/commit/feefdf015254276eabf8a7b6cda15d52ac39ef62

![Screen Shot 2023-11-20 at 10 40 11](https://github.com/electerm/electerm/assets/1641949/76f5d183-9fd0-4944-94eb-9e2d9a27990b)
