### ISSUE TITLE
页面缩放级别自由调节

### ISSUE THREAD

**Issue by ioplmk** [electerm/electerm#2979]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![屏幕截图 2023-09-13 205126](https://github.com/electerm/electerm/assets/93701868/4ce623a7-c42f-41b0-a298-1542ae4db54a)
目前页面缩放级别是25一档
100 -> 125 -> 150
能否开发自由调节

**Comment by zxdong262** [comment]
将在下个版本加入~
