### ISSUE TITLE
窗口的名称希望能给一个默认较为短一点的名称以及每个窗口添加区分标识

### ISSUE THREAD

**Issue by danghuagood** [electerm/electerm#2980]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

我看现在窗口的名称规则好像是username@hostname:port这种规则，有时候需要开多个窗口，如果窗口名称过长的话，屏幕上排不下那么多的窗口，需要来回点击右边的“< >”按钮，感觉不是很方便，建议做如下改进：
1、每个窗口默认的名称取短一点，这样可以开更多的窗口，不用来回点击“< >”来切换窗口
2、每个窗口添加区分标识（比如1, 2, 3.....，或者小颜色块），现在所有的窗口名称都一样，有时候要切换不同的窗口来操作，然后要找原来的窗口比较费劲，所以的窗口名称都一样，根本不知道上一次操作的是哪个窗口，现在比如添加1，2,3或者颜色块区分，很容易就能找到操作的上一次端口

**Comment by zxdong262** [comment]
有道理！
