### ISSUE TITLE
安装程序删除了便携模式下的数据

### ISSUE THREAD

**Issue by 233zone** [electerm/electerm#2984]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.32.28-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

使用在线升级或手动下载安装程序进行安装时，会自动删除安装目录下的便携模式数据：electerm文件夹。

### What should have happened?(期望的结果)

保留electerm文件夹。

**Comment by zxdong262** [comment]
请下载那个portable版本的

**Comment by zxdong262** [comment]
下个版本我试试构建一个便携版的安装包，也许可以解决覆盖问题

**Comment by zxdong262** [comment]
windows构建的包太多了，暂时不增加了
