### ISSUE TITLE
最新版本（1.32.36）从书签连接报错：sshTunnels is not iterable

### ISSUE THREAD

**Issue by chaselen** [electerm/electerm#2986]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.32.36

### Platform detail (平台详情)

Darwin

### What steps will reproduce the bug?(重新问题的详细步骤)

展开书签，点击进行连接

### What should have happened?(期望的结果)

ssh登录成功

**Comment by zxdong262** [comment]
感谢反馈，立刻修复~

**Comment by zxdong262** [comment]
已发布新版
