### ISSUE TITLE
支持直接连接不保存bookmark并且默认使用.ssh/id_rsa

### ISSUE THREAD

**Issue by mio-19** [electerm/electerm#2991]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

如题。我会经常处于不同的网络环境连接的机器没有固定的ip；私钥保存在git for windows/windows自带ssh client默认会去读的位置，希望可以省略一个在electerm导入的步骤

**Comment by zxdong262** [comment]
将在下个版本加入
