### ISSUE TITLE
打开X11功能不能连接服务器

### ISSUE THREAD

**Issue by lxsexl** [electerm/electerm#2993]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.32.38-win-x64.tar.gz

### Platform detail (平台详情)

WINDOWS 10 X64

### What steps will reproduce the bug?(重新问题的详细步骤)

在SSH模式下，打开X11功能不能连接服务器。关闭X11就可以连接。以下是日志出错信息：
[2023-09-20 19:55:18.837] [error] fetch error {
  message: 'this.getExecOpts is not a function',
  stack: 'TypeError: this.getExecOpts is not a function\n' +
    '    at E:\\Program Files\\Electerm\\resources\\app.asar\\server\\session.js:43:32\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at getDisplay (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\session.js:42:10)\n' +
    '    at Terminal.remoteInitProcess (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\session.js:317:36)\n' +
    '    at Terminal.remoteInit (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\session.js:224:19)\n' +
    '    at Terminal.init (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\session.js:86:36)\n' +
    '    at exports.terminal (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\session.js:972:14)\n' +
    '    at createTerm (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\terminal-api.js:37:3)\n' +
    '    at WebSocket.<anonymous> (E:\\Program Files\\Electerm\\resources\\app.asar\\server\\dispatch-center.js:195:9)\n' +
    '    at WebSocket.emit (node:events:513:28)'
}
[2023-09-20 19:55:18.839] [debug] { message: 'this.getExecOpts is not a function' }
[2023-09-20 19:55:18.840] [debug] this.getExecOpts is not a function fetch err info

### What should have happened?(期望的结果)

本来打开X11功能，希望能用上X11 forwarding。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

下载了MobaXterm可以正常连接同一服务器，并使用X11功能。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
