### ISSUE TITLE
ubnutu18无法启动

### ISSUE THREAD

**Issue by yanteng** [electerm/electerm#2994]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.32.38-linux-x64.tar.gz

### Platform detail (平台详情)

ubuntu18.04

### What steps will reproduce the bug?(重新问题的详细步骤)

启动程序

### What should have happened?(期望的结果)

正常进入

### Additional information(其他任何相关信息)

`21:26:17 debug › electerm start
21:26:18 info › database version: 1.32.38
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js
- /home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/server/session.js
- /home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/server/dispatch-center.js
- /home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/server/server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/server/session.js',
    '/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/server/dispatch-center.js',
    '/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/server/server.js'
  ]
}
/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:40
        throw outerError;
        ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/teng/Downloads/electerm-1.32.28-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1271:14) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.1

`

**Comment by zxdong262** [comment]
可以试试deb那个包吗

**Comment by zxdong262** [comment]
可能跟GLIBC_2.28有关，我试了在ubuntu20.04是可以的，有可能deb或者snap的包可以

**Comment by yanteng** [comment]
> 可以试试deb那个包吗

试过了，都不行，snap也不行。压缩包中的也不行。

**Comment by mishi5250** [comment]
> > 可以试试deb那个包吗
> 
> 试过了，都不行，snap也不行。压缩包中的也不行。
可以试试应用商店的1.32.46版本
最新版确实不行

**Comment by zxdong262** [comment]
有试过之前哪个版本可以吗？使用Ubuntu20.04构建有一段时间了

**Comment by zxdong262** [comment]
我知道了，因为升级到electron v22 导致的，v22使用nodejs18,需要glibc2.0.8, ubuntu 18没有，也许这个方法可以解决https://blog.csdn.net/weixin_42237990/article/details/129703945?spm=1001.2101.3001.6650.2&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-129703945-blog-129343107.235%5Ev38%5Epc_relevant_anti_vip_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-129703945-blog-129343107.235%5Ev38%5Epc_relevant_anti_vip_base&utm_relevant_index=3

**Comment by mishi5250** [comment]
> 有试过之前哪个版本可以吗？使用Ubuntu20.04构建有一段时间了

1.32.46 18.04应用商店版本是可以的

**Comment by mishi5250** [comment]
> 我知道了，因为升级到electron v22 导致的，v22使用nodejs18,需要glibc2.0.8, ubuntu 18没有，也许这个方法可以解决https://blog.csdn.net/weixin_42237990/article/details/129703945?spm=1001.2101.3001.6650.2&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-129703945-blog-129343107.235%5Ev38%5Epc_relevant_anti_vip_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-129703945-blog-129343107.235%5Ev38%5Epc_relevant_anti_vip_base&utm_relevant_index=3

晚点试试

**Comment by mishi5250** [comment]
> > 我知道了，因为升级到electron v22 导致的，v22使用nodejs18,需要glibc2.0.8, ubuntu 18没有，也许这个方法可以解决https://blog.csdn.net/weixin_42237990/article/details/129703945?spm=1001.2101.3001.6650.2&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-129703945-blog-129343107.235%5Ev38%5Epc_relevant_anti_vip_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-129703945-blog-129343107.235%5Ev38%5Epc_relevant_anti_vip_base&utm_relevant_index=3
> 
> 晚点试试

更新 该解决方案有用，安装更新后，就可以正常打开Ubuntu18.04.6 ,5.4.0.150  内核 测试ok
