### ISSUE TITLE
点击使其便携按钮提示错误

### ISSUE THREAD

**Issue by lxsexl** [electerm/electerm#2995]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.32.46-win-x64.tar.gz

### Platform detail (平台详情)

Windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

点了使其便携按钮，提示错误，错误日志：
[2023-09-21 09:12:13.328] [error] fetch error {
  message: '��Ч�Ĳ�������',
  stack: 'InvocationError: ��Ч�Ĳ�������\n' +
    '    at PowerShell.<anonymous> (D:\\Program Files\\Electerm\\resources\\app.asar\\node_modules\\child-shell\\dist\\Shell.js:245:23)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (D:\\Program Files\\Electerm\\resources\\app.asar\\node_modules\\child-shell\\dist\\Shell.js:5:58)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
[2023-09-21 09:12:13.329] [error] Error: ��Ч�Ĳ�������
    at async http://127.0.0.1:30974/js/electerm-1.32.46.js:163:63936

### What should have happened?(期望的结果)

可以使其便携

**Comment by zxdong262** [comment]
可以直接下载那个便携版
