### ISSUE TITLE
建议快速命令功能中选择的标签可以持久化保存

### ISSUE THREAD

**Issue by winter110** [electerm/electerm#2996]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

操作系统：deepin linux v23 beta2
软件包：electerm-1.32.46-linux-amd64.deb

建议在左下角的快速命令下如果用户选中了某几个标签后，能够对用户选择的标签选项进行持久化保存，这样无论用户重启系统或者重启软件后，都永远只显示之前用户选择的标签下的命令，而没选中的标签下的命令则不显示。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入

**Comment by cantona97** [comment]
更新到最新版本后试用了这个功能，但是选了一个Label之后再次打开软件使用quick command时就崩溃：


Something went wrong.
Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes') at http://127.0.0.1:30974/js/electerm-1.34.8.js:170:890 at Array.some (<anonymous>) at http://127.0.0.1:30974/js/electerm-1.34.8.js:170:873 at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:28807 at nn (http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:859) at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:28783 at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:26924 at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:23245 at cu (http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:26896) at wu (http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:28756)

**Comment by winter110** [comment]
试用了最新版本（electerm-1.34.10-linux-amd64.deb），未选中的lable下的命令依然还是会显示出来

**Comment by zxdong262** [comment]
> 试用了最新版本（electerm-1.34.10-linux-amd64.deb），未选中的lable下的命令依然还是会显示出来

目前只是改变排序，不会隐藏任何命令，得优化一下
