### ISSUE TITLE
mac 13.5.2   electerm 1.32.46  ssh 通过华为堡垒机连上服务器1分钟就掉线

### ISSUE THREAD

**Issue by 53761142** [electerm/electerm#2997]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm 1.32.46

### Platform detail (平台详情)

mac 13.5.2   electerm 1.32.46  ssh 连接华为云堡垒机到具体服务器1分钟就掉线

### What steps will reproduce the bug?(重新问题的详细步骤)

mac 13.5.2   electerm 1.32.46  ssh 连上1分钟就掉线，用其他的ssh工具啥事没有， 
我这边操作步骤是：首先连接到华为云堡垒机，然后通过上下键选择到具体服务器，然后回车到具体的服务器中，在ssh模式下，不管是否操作1-2分钟一定端口。用其他的ssh工具 都正常的。
Keepalive间隔(ms): 10000，Ssh/sftp超时时间(毫秒): 50000 都调过不管用，，profile也改过也不管用

这个也不管用，
Creating ~/.ssh/config with this contents kept connection alive.

Host *
ServerAliveInterval 30
ServerAliveCountMax 2

### What should have happened?(期望的结果)

修复

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能，其他的ssh工具都正常

### Additional information(其他任何相关信息)

![1](https://github.com/electerm/electerm/assets/58580154/02c54d6b-c0fd-4a71-8197-91e7b98d000b)

**Comment by zxdong262** [comment]
可以试试Keepalive设为特别长或者0试试
