### ISSUE TITLE
mac 13.5.2   electerm 1.32.46  ssh 连上1分钟就掉线 提示:终端连接丢失

### ISSUE THREAD

**Issue by 53761142** [electerm/electerm#2998]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm 1.32.46

### Platform detail (平台详情)

mac 13.5.2   electerm 1.32.46 

### What steps will reproduce the bug?(重新问题的详细步骤)

mac 13.5.2   electerm 1.32.46  ssh 连上1分钟就掉线，用其他的ssh工具啥事没有， 
我这边首先通过ssh连接的是华为云堡垒机【linux】，然后选择进去到具体服务器中【linux】，进去后终端最多2分钟就断开。
用其他的ssh工具 都正常。
Keepalive间隔(ms): 10000，Ssh/sftp超时时间(毫秒): 50000 都调过不管用，，profile也改过也不管用

这个也不管用，
Creating ~/.ssh/config with this contents kept connection alive.

Host *
ServerAliveInterval 30
ServerAliveCountMax 2

### What should have happened?(期望的结果)

修复

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其他ssh软件都正常

### Additional information(其他任何相关信息)

![Xnip2023-09-21_13-48-03](https://github.com/electerm/electerm/assets/58580154/325adaa9-93a2-478e-b370-155d59dc8960)

**Comment by zxdong262** [comment]
可以试试Keepalive间隔设为0或者最大值吗？

**Comment by 53761142** [comment]
Keepalive 设置0 目前看没问题了，这软件很棒，谢谢你们

**Comment by Samge0** [comment]
> 可以试试Keepalive间隔设为0或者最大值吗？

我的配置为0没有效果，还是会自动断开，断开后无法输入，需要右击顶部选择“刷新”，但刷新后原来页面操作记录都清空了。

版本信息：
1.34.30
系统信息：
version:"Windows Server 2022 Standard"
machine:"x86_64"
