### ISSUE TITLE
將密碼欄位留空，不會提示輸入密碼，顯示連線失敗

### ISSUE THREAD

**Issue by pingchou8** [electerm/electerm#3001]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electterm 1.32.46

### Platform detail (平台详情)

Linux 6.2.0-33-generic #33~22.04.1-Ubuntu

### What steps will reproduce the bug?(重新问题的详细步骤)

將密碼欄位留空，不會提示輸入密碼，顯示連線失敗。
若密碼欄有輸入保存密碼可以正常連線。

### What should have happened?(期望的结果)

將密碼欄位留空，連線應該提示輸入密碼。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其他終端程式可以正常使用

### Additional information(其他任何相关信息)

electterm 1.28.4此版本可以密碼欄位留空，連線提示輸入密碼。
electterm 1.28.4後的版本密碼欄位留空，則無法連線。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
