### ISSUE TITLE
無存儲密碼下，使用sshkey passwd無法登入

### ISSUE THREAD

**Issue by pingchou8** [electerm/electerm#3005]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electterm 1.33.0

### Platform detail (平台详情)

Linux 6.2.0-33-generic #33~22.04.1-Ubuntu

### What steps will reproduce the bug?(重新问题的详细步骤)

在沒有保存sshkey密碼情況下，連線到ssh主機，提示輸入密碼，輸入密碼後無法連線

### What should have happened?(期望的结果)

在沒有保存sshkey密碼情況下，連線到ssh主機，提示輸入密碼，輸入密碼後可以連線

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其他終端程式可以在沒有保存sshkey密碼情況下，連線到ssh，提示輸入密碼，輸入密碼後可連線

### Additional information(其他任何相关信息)

electterm 1.33.0已經修復一般在沒有保存密碼情況下，連線到ssh主機，提示輸入密碼，輸入密碼後無法連線。
目前在electterm 1.33.0上，沒有保存sshkey密碼情況下，連線到ssh主機，提示輸入密碼，輸入密碼後無法連線。
electterm 1.28.4上，沒有保存sshkey密碼情況下，連線到ssh主機，提示輸入密碼，輸入密碼後是可以連線的。

**Comment by zxdong262** [comment]
![Screen Shot 2023-09-27 at 09 55 04](https://github.com/electerm/electerm/assets/1641949/07644f2c-0b34-48f2-8103-7a44a6a31c36)
请问是这样的吗

**Comment by pingchou8** [comment]
是的，輸入密碼後無法連線，只會一直轉圈

**Comment by zxdong262** [comment]
我知道了，确实存在，如果不输入privatekey,会自动读取.ssh目录下的key，以及询问密码，那样可以登陆

**Comment by pingchou8** [comment]
我管理主機多，「.ssh」下的key很多，可以指定key；但目前sshkey只能匯入，也沒辦法指定路徑，若是自動讀取出錯機率很高。

**Comment by zxdong262** [comment]
感谢反馈，将在一小时内发布新版本修复
