### ISSUE TITLE
更新v1.33.6后，使用zsh界面变成灰色

### ISSUE THREAD

**Issue by Mist1987** [electerm/electerm#3007]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.33.6-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19045.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

之前的版本在设置里渲染类型选择webGl没问题，正常颜色如下
![image](https://github.com/electerm/electerm/assets/35526973/55fb4961-81c1-45dc-a4b6-519f0c1feb7f)

现在：
![image](https://github.com/electerm/electerm/assets/35526973/968f7316-9215-4b43-95cb-d39ddb6d2043)
![image](https://github.com/electerm/electerm/assets/35526973/4ff5f414-2852-4092-832a-3a173fc457b3)

### What should have happened?(期望的结果)

![image](https://github.com/electerm/electerm/assets/35526973/55fb4961-81c1-45dc-a4b6-519f0c1feb7f)

**Comment by zxdong262** [comment]
请问之前版本号是多少？

**Comment by zxdong262** [comment]
请问之前版本号是多少？

**Comment by Mist1987** [comment]
1.32.46还是好的，1.33.0就出现这个问题了

**Comment by zxdong262** [comment]
渲染方面代码没有变化 https://github.com/electerm/electerm/compare/v1.32.46...v1.33.6 ，会不会是其他的环境变化呢？

**Comment by Mist1987** [comment]
有没有可能是其他的问题，我刚试了下，环境不变从1.32.46升到1.33.0会灰色，退回到32.46又正常了

**Comment by zxdong262** [comment]
> 1.32.46



> 有没有可能是其他的问题，我刚试了下，环境不变从1.32.46升到1.33.0会灰色，退回到32.46又正常了

有其他设备可以试试吗

**Comment by Mist1987** [comment]
试了，同样会出现

**Comment by awayme** [comment]
同样颜色问题，v1.33.6，
但细节不同，同样都是zsh
服务器上以前的tmux的session，attach回去后，颜色变灰，且tmux的鼠标交互失效
但如果只是ssh不开tmux，则颜色正常
同样退回上一版本就好了

**Comment by zxdong262** [comment]
重新新建了一个win10虚拟机，复现了，颜色确实不一样

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
