### ISSUE TITLE
ssh 颜色

### ISSUE THREAD

**Issue by mio-19** [electerm/electerm#3013]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.33.26-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

+ 连接到ssh，颜色不显示，回车出现错位
+ 在electerm内的powershell中连接ssh，颜色显示
 
![image](https://github.com/electerm/electerm/assets/57285379/a54bb5ef-b074-456c-a48f-40bd43a315a7)
![image](https://github.com/electerm/electerm/assets/57285379/39a034d5-5c04-4836-99c8-77ef3dd47b18)

### What should have happened?(期望的结果)

-

**Comment by mio-19** [comment]
依次降级到electerm-1.33.26-win-x64-installer.exe以后问题消失

![image](https://github.com/electerm/electerm/assets/57285379/85d606b2-0734-4d1a-96cb-048f2741ee91)

**Comment by zxdong262** [comment]
请问有问题的是哪个版本？

**Comment by zxdong262** [comment]
哦我知道了，确实存在颜色不对 同#3007

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
