### ISSUE TITLE
htop不显示色彩了

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3014]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.33.26-mac-x64.dmg

### Platform detail (平台详情)

mac-x64

### What steps will reproduce the bug?(重新问题的详细步骤)

htop本来是有色彩的，现在的htop显示的是黑白版本了

### What should have happened?(期望的结果)

变成彩色的

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

htop

**Comment by xxoxx** [comment]
<img width="1403" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/bc292415-0eed-4ba9-a5cc-5cb18ef73652">

**Comment by xxoxx** [comment]
<img width="1438" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/4bb272e8-cbd8-43a0-ae1f-d5e9401437fb">
这是Iterm2的，这个就是彩色的。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复 https://github.com/electerm/electerm/commit/46ddcbae78d2a4f73f9ceaca66797ebadaed0f0b
