### ISSUE TITLE
SFTP: show appropriate error message on permission denied

### ISSUE THREAD

**Issue by uniquejava** [electerm/electerm#3015]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.33.36-mac-x64.dmg

### Platform detail (平台详情)

mac os x64

### What steps will reproduce the bug?(重新问题的详细步骤)

When target linux directory has no write permission.  Electerm just simply hang there which is very user unfriendly.

I think electerm should prompt user "permission denied" like what Filezilla does

### Filezilla

<img width="589" alt="image" src="https://github.com/electerm/electerm/assets/1049271/37a1e077-c0a3-4728-b074-35fa5ca558a3">

### Electerm just hang there

<img width="817" alt="image" src="https://github.com/electerm/electerm/assets/1049271/e8bbf3bc-daf9-4e34-ad29-07ece7a105cf">

### What should have happened?(期望的结果)

Electerm should tell user the target directory has no write permission.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

No

**Comment by zxdong262** [comment]
Would fix in next release, thank you for the feedback.
