### ISSUE TITLE
我经常找不到我的终端跑哪里去了,原来所有的其他窗口都是一个 overlay

### ISSUE THREAD

**Issue by uniquejava** [electerm/electerm#3016]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

我安装了得有2~3月, 用了十来次, 才发现, 主窗口是被覆盖了. 建议和 vscode 一样左侧高亮选中的菜单, 点一下能 show 主窗口,  我把左侧图标挨个点一遍 都 找不到我的终端列表跑哪里去了, 这个对初次使用者非常的不友好.  我才发现右上角 不太明显的关闭窗口不是关闭 Electerm而是显示 Terminal List.

**Comment by zxdong262** [comment]
方便截图解释一下不，没看懂

**Comment by uniquejava** [comment]
当我初次装上这个软件以后, 我都想看看有哪些功能, 挨个点一遍以后.

<img width="869" alt="image" src="https://github.com/electerm/electerm/assets/1049271/fe6ea5c5-8a65-4fe9-800f-6e99bb4b980f">


我发现 终端窗口不见了, 我很慌, 我发现这里可以 New Tab, 但是无论我点多少下,  UI 上都没有反应

<img width="599" alt="image" src="https://github.com/electerm/electerm/assets/1049271/0804817f-97e2-4270-9a3b-54c8c8ae3467">


我很慌,  原因是右上角的 x 按钮太不明显了, 而且给人一种是要退出 app 的感觉. 

<img width="872" alt="image" src="https://github.com/electerm/electerm/assets/1049271/6d4c97ff-f796-4c8c-9e05-5e5f06323e5f">


只有 about 框 是合理的设计, 其它的都不太合理. 

建议进入到其他页面时不要覆盖 Terminal 的 tab 页,   就是不要遮肚下面的部分.

<img width="872" alt="image" src="https://github.com/electerm/electerm/assets/1049271/35c1ff4f-052f-48e8-8c2d-49456d36aa1d">

让人一看就知道, 哦, 我打开的是一个浮动的层.   还有 点 New Tab 的时候 自动关闭弹出的层, 不要点了 New Tab 没有反应.

Just some advice

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by lvwshuai** [comment]
> 感谢反馈，将在下个版本优化

about，关于页面上面的关闭按钮，也跟更新之后的其他页面保持一致吧，现在关闭都在左边了唯独about在右边，有点别扭
