### ISSUE TITLE
密钥登陆失败时，直接卡死

### ISSUE THREAD

**Issue by algodauphin** [electerm/electerm#3017]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

v1.33.6 -win-x64-loose.tar.gz

### Platform detail (平台详情)

Windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

生产环境的服务器每天第一次登陆必须输入密码，之后可以用密钥登陆。
当验证方法为密钥，每天第一次登陆生产服务器时，窗口没有任何提示信息，直接卡死。用别的终端输入密码登陆后则可用electerm登陆。

### What should have happened?(期望的结果)

先尝试密钥登陆，如果失败则提示输入密码

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

MobaXterm等终端会提示输入密码

**Comment by zxdong262** [comment]
感谢反馈，下个版本实现

**Comment by zxdong262** [comment]
已发布
