### ISSUE TITLE
Please add skip all function when there are file conflicts on sftp

### ISSUE THREAD

**Issue by TomoyaKuroda** [electerm/electerm#3019]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Please add skip all function when there are file conflicts on sftp
![Untitled](https://github.com/electerm/electerm/assets/31934952/e55a0708-3288-451c-9092-6695e1a55bc4)

**Comment by TomoyaKuroda** [comment]
@zxdong262 Thanks!

**Comment by zxdong262** [comment]
Thank you for the feedback, feature would be in next release~
