### ISSUE TITLE
Bookmark里面的"Test Connection"无效

### ISSUE THREAD

**Issue by cantona97** [electerm/electerm#3023]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.6-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

Bookmark里面的"Test Connection"无效，即使无论是新输入的登录信息或者在成功在用的收藏站点中点击Test Connection后的结果都是“Connection Fails: test failed”，最近的好几个版本都是这样，包括1.34.6这个版本

### What should have happened?(期望的结果)

希望能修复这个功能

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
