### ISSUE TITLE
测试连接按钮功能不对

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3024]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.6-mac-x64.dmg

### Platform detail (平台详情)

mac-x64

### What steps will reproduce the bug?(重新问题的详细步骤)

新增ssh连接中，  点测试连接  按钮报不能连接，   但是点保存并连接是能正常连接的。  

### What should have happened?(期望的结果)

测试连接  按钮 功能正常

**Comment by xxoxx** [comment]
<img width="1296" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/26c6e169-1cb0-47d9-905a-416e6afbcc66">

**Comment by xxoxx** [comment]
<img width="919" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/4e352da4-56b0-4548-a853-502998b1a790">

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复 https://github.com/electerm/electerm/commit/598a4f4a10056daa63ac17340b8771b13c62e94a
