### ISSUE TITLE
M1 pro使用1.34.6版本，新建linux连接并设置打开X11无法连接：

### ISSUE THREAD

**Issue by SmallMousePP** [electerm/electerm#3026]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.6-mac-arm64.dmg

### Platform detail (平台详情)

mac os(ARM) M1 Pro

### What steps will reproduce the bug?(重新问题的详细步骤)

aliyun新建的一个服务器，编辑正确连接信息，并开启X11开关，连接时失败（Unable to request X11）

### What should have happened?(期望的结果)

正常连接，并能使用x11转发

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否

### Additional information(其他任何相关信息)

更新至该版本后，无法刷新出程序的日志，无法提供报错信息

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
