### ISSUE TITLE
Quick Command导致软件崩溃

### ISSUE THREAD

**Issue by cantona97** [electerm/electerm#3027]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.8-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

更新到最新版本后试用了[#2996](https://github.com/electerm/electerm/issues/2996)这个功能，但是选了一个Label之后再次打开软件使用quick command时就崩溃
Something went wrong.
Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes') at http://127.0.0.1:30974/js/electerm-1.34.8.js:170:890 at Array.some () at http://127.0.0.1:30974/js/electerm-1.34.8.js:170:873 at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:28807 at nn (http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:859) at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:28783 at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:26924 at http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:23245 at cu (http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:26896) at wu (http://127.0.0.1:30974/chunk/lodash-es-1.34.8-9eb4e24a.js:1:28756)

### What should have happened?(期望的结果)

修复这个错误

**Comment by cantona97** [comment]
鼠标指针经过左下角的“Q”就弹出软件出错的对话框（只能按Reload）

**Comment by zxdong262** [comment]
感谢反馈，已发布新版
