### ISSUE TITLE
希望增加一项配置自动（定时）同步的功能

### ISSUE THREAD

**Issue by gaoliuzhu** [electerm/electerm#3029]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

electerm是一款很优秀的终端工具，目前使用过程中体验良好，settings sync功能中，能否增加一项自动同步，或者定时同步，或者打开electerm之后触发同步的操作，可以把一些变更或者新增的主机信息同步到云端，防止因为电脑更换，办公环境更换，而忘记做同步信息，导致主机信息丢失。

自动同步的功能，不太会注重账号密码的隐私，更注重便利性。

感谢作者阅读。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入
