### ISSUE TITLE
左下角快速命令和批量输入

### ISSUE THREAD

**Issue by huyuanjun976** [electerm/electerm#3032]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)
1.34.0  macos14
1.建议放大放宽，现在好小，都不方便点击，也没有快捷键
2.批量输入建议可选窗口，现在是要么全选，要么全不选
3.批量输入有BUG，有时有些窗口没生效
其它：窗口断开连接后,每次都要点击那标签上小小的图标，能否直接在窗口回车动作后自动重连或快捷键

**Comment by zhouchitc** [comment]
快捷窗口小么？我觉得比xshell大太多了。占用屏幕的比例太大了
<img width="1728" alt="image" src="https://github.com/electerm/electerm/assets/11803579/29516e01-21db-4806-9ba0-5ce43d3c6de8">

**Comment by huyuanjun976** [comment]
不好意思  可能是没表达清楚
我表达的是 那个 Q  和   B  所占位置太小了  建议放大这两个点击的区域，还有加上快捷键来打开这两功能就更好了

**Comment by zxdong262** [comment]
> 不好意思 可能是没表达清楚 我表达的是 那个 Q 和 B 所占位置太小了 建议放大这两个点击的区域，还有加上快捷键来打开这两功能就更好了

明白了，很有道理，将在下个版本改进
