### ISSUE TITLE
显示bug

### ISSUE THREAD

**Issue by lians0** [electerm/electerm#3034]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.34.20-x64.installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

如图

![screenshots](https://github.com/electerm/electerm/assets/30581350/b479d5a0-e690-4e0e-8758-8b16a479a87b)

### What should have happened?(期望的结果)

如图

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
