### ISSUE TITLE
mac os SFtp cannot save remote server favorites

### ISSUE THREAD

**Issue by credit03** [electerm/electerm#3036]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.26-mac-x64.dmg

### Platform detail (平台详情)

Darwin bogon 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.1. On the mac os, Sftp adds a favorites folder of the remote server, closes and re-opens the electerm favorites folder is lost and cannot be found.
2. Save the local data to prevent loss

### What should have happened?(期望的结果)

fix

**Comment by zxdong262** [comment]
will fix in next release, thank you for the feedback
