### ISSUE TITLE
版本 1.34.26 新发现三个bug。

### ISSUE THREAD

**Issue by pengweizhong** [electerm/electerm#3037]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

[electerm-1.34.26-win-x64-installer.exe](https://github.com/electerm/electerm/releases/download/v1.34.26/electerm-1.34.26-win-x64-installer.exe)

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

**第一个BUG**：书签页面右击或者点击齿轮后，“剪贴”，“粘贴”等按钮不会消失，即使点击其他界面。
![image](https://github.com/electerm/electerm/assets/48546556/015d351e-5e26-4963-91aa-b3500386429b)

**第二个BUG**：全屏状态下，鼠标置于底部无法唤出任务栏。我这里的任务栏设置的状态是：移除鼠标后自动隐藏
![image](https://github.com/electerm/electerm/assets/48546556/9c755e40-773c-4060-a4b1-b3ff11dc3fb8)

**第三个BUG**：小窗状态下，拉伸应用边界没有自适应。在默认主题下，新拉出的区域是黑色的。
![image](https://github.com/electerm/electerm/assets/48546556/0f1a3493-7b90-46d7-83f4-22d75c466126)

### What should have happened?(期望的结果)

**第一个BUG**：点击其他界面后让  “剪贴”，“粘贴”消失。
**第二个BUG**：全屏状态下，鼠标置于底部可以唤出任务栏
**第三个BUG**：小窗状态下，拉伸应用边界希望自适应

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

no

**Comment by pengweizhong** [comment]
**第四个bug：默认用户名root无效，必须手动输入root**
![image](https://github.com/electerm/electerm/assets/48546556/7f7955e2-fea0-40aa-acd8-3847defe542e)
手动输入后即可连接
![image](https://github.com/electerm/electerm/assets/48546556/23e6f7ef-c71b-46e1-9789-f14fd7c62582)

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
关于第二个，我试了一下，似乎其他软件比如Chrome在全屏时候也是同样的行为？

**Comment by zxdong262** [comment]
最新版修复了1,3,4bug

**Comment by pengweizhong** [comment]
关于第二个问题，在谷歌下是可以正常唤出任务栏的。我注意到鼠标移至electerm底部时，触发的是一个窗口拉伸操作，而谷歌触发的是“最大边界”操作，就是说谷歌在全屏时和小窗时鼠标触发的逻辑是不一样的
