### ISSUE TITLE
在Sftp模块中操作服务端文件，将文件拖放至一个文件夹下时一直显示在传输中。查看传输进度时一直显示为0%。

### ISSUE THREAD

**Issue by yanyouqing** [electerm/electerm#3038]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.26-win-x64-loose.tar.gz

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

1、打开electerm客户端连接远程服务器
2、点击Sftp页面，在右侧操作服务端文件。
3、选择一个文件拖放至一个文件夹时，此时传输进度显示为0。
4、等待一段时间后传输进度仍为0。
5、尝试过使用之前1.34.6版本进行同样的操作，是可以正常操作的。

### What should have happened?(期望的结果)

服务端可以正常拖放文件到目录

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
