### ISSUE TITLE
希望连接的服务器可以显示服务器名字或者IP？

### ISSUE THREAD

**Issue by cenyi** [electerm/electerm#3040]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/electerm/electerm/assets/7018650/5467aef2-a2dc-444a-8942-a2358c837126)

期待连接的服务器可以显示服务器名字或者IP，这样比较方便识别是哪台机器

**Comment by zxdong262** [comment]
请问是通过书签创建的连接吗，还是在本地终端ssh命令连接的？

**Comment by cenyi** [comment]
> 请问是通过书签创建的连接吗，还是在本地终端ssh命令连接的？

是通过书签创建的链接。

**Comment by zxdong262** [comment]
> > 请问是通过书签创建的连接吗，还是在本地终端ssh命令连接的？
> 
> 是通过书签创建的链接。

可以在创建书签时候加一个标题，标题会显示在前面
![Screen Shot 2023-12-05 at 13 01 48](https://github.com/electerm/electerm/assets/1641949/dacdb190-364e-44d7-a1cb-de454a19c69a)
