### ISSUE TITLE
可否添加一个设置项

### ISSUE THREAD

**Issue by ZVimel** [electerm/electerm#3049]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

设置项：退出时记住窗口大小和位置

**Comment by zxdong262** [comment]
默认是记住的，请问在用哪个版本，什么操作系统？

**Comment by ZVimel** [comment]
> 默认是记住的，请问在用哪个版本，什么操作系统？

Win11 22H2
electerm-1.34.30-win-x64-loose
electerm-1.34.30-win-x64-portable
两个版本都不能记住窗口位置

**Comment by zxdong262** [comment]
确实没有记住位置，感谢反馈，将在下个版本修复
