### ISSUE TITLE
Display issue with the Mac title bar

### ISSUE THREAD

**Issue by Super-LUOKI** [electerm/electerm#3053]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.34.30-mac-x64.dmg 

### Platform detail (平台详情)

Darwin LuoKingdeMacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

Without using the system title bar, the program displays both Mac system window operation buttons and the program's own window operation buttons.
<img width="855" alt="图片" src="https://github.com/electerm/electerm/assets/30767779/ae794db0-1277-4ff6-8e7e-ef0786b9ead8">

### What should have happened?(期望的结果)

Do not display system window operation buttons without using the system title bar
<img width="929" alt="图片" src="https://github.com/electerm/electerm/assets/30767779/08c1416c-d133-4f8d-ab1a-8d0efcf2d963">

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

No.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/pull/3062

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
