### ISSUE TITLE
mac使用的时候 会莫名字体变小

### ISSUE THREAD

**Issue by Saiyking** [electerm/electerm#3055]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

用着用着有时候就会这样 是我按到快捷键了？ 还是bug？

**Comment by Saiyking** [comment]
![image](https://github.com/electerm/electerm/assets/20600757/390f2836-fa63-4b05-9ff0-a35c12853c8f)

**Comment by zxdong262** [comment]
cmd+ +- 或者滚轮会缩放，可能误触发了，可以在左上角菜单里重置为100%

**Comment by Lction** [comment]
> cmd+ +- 或者滚轮会缩放，可能误触发了，可以在左上角菜单里重置为100%

大佬，可以去掉这个么？之前的版本我自己注释掉这部分代码了，但是新版本不知道为什么注释之后打包，还是原来的代码

**Comment by zxdong262** [comment]
> > cmd+ +- 或者滚轮会缩放，可能误触发了，可以在左上角菜单里重置为100%
> 
> 大佬，可以去掉这个么？之前的版本我自己注释掉这部分代码了，但是新版本不知道为什么注释之后打包，还是原来的代码

之后会加入快捷键设置，可以解决这个问题，需要一段时间

**Comment by xxoxx** [comment]
@zxdong262   的确会自动变大， 不是手动触发缩放的问题， 但是不好复现。

**Comment by Lction** [comment]
> > > cmd+ +- 或者滚轮会缩放，可能误触发了，可以在左上角菜单里重置为100%
> > 
> > 
> > 大佬，可以去掉这个么？之前的版本我自己注释掉这部分代码了，但是新版本不知道为什么注释之后打包，还是原来的代码
> 
> 之后会加入快捷键设置，可以解决这个问题，需要一段时间

嗯嗯，非常感谢！

**Comment by zxdong262** [comment]
将在下个版本加入快捷键设置
