### ISSUE TITLE
macOS 端 1.34.30 问题

### ISSUE THREAD

**Issue by gradypark86** [electerm/electerm#3056]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.30-mac-arm64.dmg

### Platform detail (平台详情)

macOS ARM 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112 arm64

### What steps will reproduce the bug?(重新问题的详细步骤)

1. UI 主题界面，每页条数失效。调节为20/page或以上失效，始终显示 10/page。复现视频如下。

https://github.com/electerm/electerm/assets/39909237/a6be3bb1-989a-464e-a34c-d6c5df4ef04c

2. 新建书签界面，修改端口号时输入1 个字符自动触发端口号检测，输入框失去焦点，只能重新点击输入框继续输入。仅新建书签时第一次出现此状况，后续再次修改端口号则无问题。复现视频如下，例如想修改端口号为“123”，输入 1 后无法继续输入。

https://github.com/electerm/electerm/assets/39909237/9ec2ced8-cc56-4e8d-bb01-b44e633c5136

### What should have happened?(期望的结果)

1. 正常选择*/page。
2. 正常修改端口号，输入完毕后再检测。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
