### ISSUE TITLE
exit命令出错了

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3058]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.38-mac-x64.dmg

### Platform detail (平台详情)

mac-x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.进入某个docker 容器，
2.在容器中输入exit
3. 整个标签页面关闭

### What should have happened?(期望的结果)

这种情况仅退出当前容器啊，别关闭标签页啊
别外在连接的ssh中输入exit   就直接退出了， 之前不是还会弹出对应框， 刷新 与  重连，  现在这个也没有了。

**Comment by xxoxx** [comment]
<img width="624" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/85adfbb3-3884-4b1d-bc98-08aa8c4d86ea">

**Comment by zxdong262** [comment]
感谢反馈，已发布新版修复了这个问题
