### ISSUE TITLE
1.34.10版本之后，开始目录远程这个功能怎么不管用了 #3059

### ISSUE THREAD

**Issue by 18500507445** [electerm/electerm#3060]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

之前设置之后，打开一个地址会自动进入到设置的路径，之后的版本都没有了

**Comment by zxdong262** [comment]
考虑到可以通过运行脚本设置来实现，就去掉了，可以试试这个看可以不？
![Screen Shot 2023-10-30 at 20 22 49](https://github.com/electerm/electerm/assets/1641949/52701640-5093-4de6-a0d1-8a5708000a28)

**Comment by zxdong262** [comment]
哦，我理解错了，我以为去掉了，还在，应该是bug，下个版本修复，感谢反馈

**Comment by 18500507445** [comment]
> 哦，我理解错了，我以为去掉了，还在，应该是bug，下个版本修复，感谢反馈

谢谢您
