### ISSUE TITLE
sftp里看不到vue项目里的.env文件

### ISSUE THREAD

**Issue by LiFuHai1106** [electerm/electerm#3063]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.34.30 .dmg

### Platform detail (平台详情)

linux

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/57932634/11d351e9-53ff-4499-99a3-767bf8d52f9b)

### What should have happened?(期望的结果)

sftp里能显示.env文件

**Comment by zxdong262** [comment]
点击那个眼睛的标志试试

**Comment by zxdong262** [comment]
下个版本将默认显示隐藏文件
