### ISSUE TITLE
文件传输列表超出窗口之后没有下拉框或者分页

### ISSUE THREAD

**Issue by miaokela** [electerm/electerm#3067]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.39-mac-arm64.dmg

### Platform detail (平台详情)

mac os arm

### What steps will reproduce the bug?(重新问题的详细步骤)

文件传输的列表超出窗口没有下拉或者分页

### What should have happened?(期望的结果)

无限下拉加上搜索

**Comment by miaokela** [comment]
单页10条太多了，窗口不够大的话dialog没有滚动条，建议改成5条。还有就是点了分页，比如第2页第3页，窗口会立马关闭。

**Comment by zxdong262** [comment]
> 单页10条太多了，窗口不够大的话dialog没有滚动条，建议改成5条。还有就是点了分页，比如第2页第3页，窗口会立马关闭。

感谢反馈，将在下个版本优化
