### ISSUE TITLE
windows连接wsl，设置的连接后运行脚本未生效，连接后未执行脚本

### ISSUE THREAD

**Issue by zxfskr** [electerm/electerm#3068]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.39-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19045.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

再windows远程wsl（ubuntu），配置运行脚本连接后未执行。

连接后手动执行配置的命令行，脚本正常生成文件，没有问题
zxf@DESKTOP-3S5GP0U:~$ sh /home/zxf/workspace/run.sh
zxf@DESKTOP-3S5GP0U:~$ cat /tmp/test.txt 
Sat Nov  4 10:25:11 CST 2023

### What should have happened?(期望的结果)

期望在连接后自动执行脚本

**Comment by zxdong262** [comment]
感谢支持！可以截图看看你的脚本设置吗？

**Comment by zxfskr** [comment]
设置是这样的     
 "password": "123456",
      "port": 22,
      "runScripts": [
        {
          "script": "sh /home/zxf/workspace/run.sh"
        }
      ],
      "encode": "utf-8",
      "enableSsh": true,
      "envLang": "en_US.UTF-8",
      "term": "xterm-256color",

**Comment by zxdong262** [comment]
可以试试`chmod +x /home/zxf/workspace/run.sh`，script改为 `/home/zxf/workspace/run.sh`

**Comment by zxdong262** [comment]
另外可以试试加个500ms延迟试试

**Comment by zxfskr** [comment]
文件已经加到777了，
zxf@DESKTOP-3S5GP0U:~$ ll /home/zxf/workspace/run.sh 
-rwxrwxrwx 1 zxf zxf 43 Nov  4 15:18 /home/zxf/workspace/run.sh*
还是不得行     
 "authType": "password",
      "password": "123456",
      "port": 22,
      "runScripts": [
        {
          "script": "/home/zxf/workspace/run.sh",
          "delay": 500
        }
      ],
      "encode": "utf-8",
      "enableSsh": true,
      "envLang": "en_US.UTF-8",

**Comment by zxdong262** [comment]
我试了无延迟确实没有执行，加了延迟就执行了

**Comment by zxdong262** [comment]
加载很快的话，也许需要更长的延迟时间，将在下个版本修复

**Comment by zxdong262** [comment]
4c8395783151c9d557ac876995e0367625fd5740

**Comment by zxfskr** [comment]
@zxdong262 解决了，太牛了哥们，开源项目你们这么上心，

**Comment by zxdong262** [comment]
> @zxdong262 解决了，太牛了哥们，开源项目你们这么上心，

对榜一大哥必须上心😄
