### ISSUE TITLE
升级到v1.34.46版本后分屏功能无法使用

### ISSUE THREAD

**Issue by queuelovestack** [electerm/electerm#3071]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.39-win-x64-installer.exe

### Platform detail (平台详情)

Linux DESKTOP-1R058BI 4.4.0-19041-Microsoft #3570-Microsoft Fri Sep 29 17:00:00 PST 2023 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

下载的是electerm-1.34.39-win-x64-installer.exe这个版本，然后今天提示升级，升级之后分屏功能无法使用，点击分屏可以分屏，但是输入框是空的，里面也没有光标，无法输入

### What should have happened?(期望的结果)

分屏能够正常使用

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by queuelovestack** [comment]
谢谢您的来信，我会尽快处理的

**Comment by zxdong262** [comment]
已发布新版修复了这个问题
