### ISSUE TITLE
复制带有分屏的标签页会出现空白分屏

### ISSUE THREAD

**Issue by winddriver** [electerm/electerm#3073]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.48-win-x64-portable.tar.gz

### Platform detail (平台详情)

Windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

在一个标签页中打开多个分屏，然后双击或者右键标签页选择复制，生成新的标签页，在新的标签页中，只有一个分屏会正常连接SSH，其它分屏都是空白

### What should have happened?(期望的结果)

希望要么复制后不要分屏，要么将所有分屏都正确连接服务器

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
