### ISSUE TITLE
windows下使用批处理命令上传或者下载文件会卡住，

### ISSUE THREAD

**Issue by fashen002** [electerm/electerm#3074]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.48-win-x64-installer.exe

### Platform detail (平台详情)

Windows x64

### What steps will reproduce the bug?(重新问题的详细步骤)

使用示例中的上传和下载命令。
"192.168.1.3","22","username","password","touch yy.js && ls -al","/home/user/some_local_file_or_folder_to_upload","/server/some_server_folder_for_upload","upload","touch yy1.js && ls -al"
"192.168.1.3","22","username","password","ls -al","/home/user/some_local_folder_for_download","/server/some_server_file_or_folder","download","ls"

文件成功上传，但是状态并没有更新，不能继续进行，不能结束

### What should have happened?(期望的结果)

预期结果是上传或者下载完成，状态更新。。。。

### Additional information(其他任何相关信息)

![image](https://github.com/electerm/electerm/assets/55468180/1889f728-5246-4f69-95dc-bbb9464970b5)
windows下使用批处理命令上传或者下载文件会卡住，不能成功返回状态。。。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
将在下个版本修复
