### ISSUE TITLE
建议加宽 SSH/SFTP 标签页的宽度

### ISSUE THREAD

**Issue by winddriver** [electerm/electerm#3075]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

如图，目前这个标签太窄了，点击的时候比较费神，那个SFTP标签还集成了上传状态的功能，太小的标签看起来比较费劲。

加宽既能方便操作，也能方便查看SFTP上传的状态

另外建议将标题全部大写，因为 SSH SFTP 本来就是几个单词的首字母缩写，通常这种情况都应该使用大写

![image](https://github.com/electerm/electerm/assets/3221597/a5865ab5-1204-4e40-a911-8aab74fd511e)

**Comment by zxdong262** [comment]
有道理，感谢反馈，将在下个版本优化

**Comment by winddriver** [comment]
更新了最新的1.34.58，SSH/SFTP那个标签似乎完全没变化，还和以前一样

这是现在版本的界面截图
![image](https://github.com/electerm/electerm/assets/3221597/5c0d7889-d19a-4130-8396-429eecb23582)

我打开开发者工具，自己调整了一下样式给你们参考下吧，我已经把需要调整地地方用红框标注了
![image](https://github.com/electerm/electerm/assets/3221597/64a5c66f-920e-4b31-afe9-6849c6cce1ae)

**Comment by winddriver** [comment]
其实如果能够增加一个允许用户自定义css的机制，这种小问题完全可以我们自己来调整
比如允许用户创建一个custom.css，程序启动时自动加载该css即可，只要保证这个css最后加载，用户的修改就能覆盖默认值
