### ISSUE TITLE
建议双击文字时，只选择需要的部分

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#3077]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/electerm/electerm/assets/13861904/57d78a16-cea3-4379-adf8-74cebffd5691)

![image](https://github.com/electerm/electerm/assets/13861904/14abc042-9b7d-453a-bef8-4b8d84815270)

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本改进

**Comment by zxdong262** [comment]
![Screen Shot 2023-11-10 at 15 58 06](https://github.com/electerm/electerm/assets/1641949/842d7ba9-e5f5-4ebc-8c61-3e8bad89c140)
将在下个版本加入设置，可以自定义哪些字符分离文字，默认为 ```./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?```

**Comment by czxin788** [comment]
谢谢，真是太好了。
