### ISSUE TITLE
连接安全密码

### ISSUE THREAD

**Issue by bendchen** [electerm/electerm#3081]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

为了方便连接，在一些书签中输入了密码，这样每次使用书签时可以实现自动登录远程系统。
当重新打开electerm时，再打开这些已输入密码的书签时，能否要求输入一个安全连接密码，以实现安全连接书签？

**Comment by zxdong262** [comment]
新版本加入了登录密码设置
![Screen Shot 2023-11-12 at 15 05 24](https://github.com/electerm/electerm/assets/1641949/36c79bc0-577f-44b8-b174-db554bd2bf75)

**Comment by bendchen** [comment]
Test OK ,thanks!
menu at setting--common--login password.
