### ISSUE TITLE
JSON配置文件导入后不生效

### ISSUE THREAD

**Issue by alexblair** [electerm/electerm#3084]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.48-win-x64-installer.exe

### Platform detail (平台详情)

win10 /win 2022 sever/win11   X64

### What steps will reproduce the bug?(重新问题的详细步骤)

1、打开electerm（B)，建立一个书签，或者别的 例如快速指令等。
2、导出 electerm JSON配置文件 （B.JSON)，并查看JSON，确保建立的书签或者别的设置在JSON中已经记录。
3、打开新的electerm（A）
4、在A中任意设置一些数据，例如 host 或者书签等，确保不是初始化的状态
5、导入electerm（B)导出的配置文件 B.JSON
6、故障出现，A中依然没有出现 B.JSON中的配置。 

### What should have happened?(期望的结果)

1、当导入配置文件后，electerm可以接受配置文件中的内容并生效（例如 书签、快速指令等）

### Additional information(其他任何相关信息)

最近的3个版本中，该BUG都出现。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
