### ISSUE TITLE
在SSH窗口中，双击无法正确选中单词，而是会将附近无关的类容也一并选上

### ISSUE THREAD

**Issue by winddriver** [electerm/electerm#3087]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.58-win-x64-portable.tar.gz

### Platform detail (平台详情)

Windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

连接任意SSH
执行ls列出一些文件内容
在随便一个文件名上双击鼠标

然后就会看到不只是双击的那个文件名被选中，同一行两边的也一并被选中了
![image](https://github.com/electerm/electerm/assets/3221597/44efe89e-2f0c-40a7-87a2-eb63b864c271)

### What should have happened?(期望的结果)

正确的选择双击位置的单词

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

**Comment by wenmang** [comment]
设置 -> 终端单词分离器中 加个空格再试试

![image](https://github.com/electerm/electerm/assets/34470691/2199e9e3-d389-4c2c-bd8a-2d1dc6d2d719)

**Comment by zxdong262** [comment]
楼上的方法是可以的，下个版本我会把空格默认加入
