### ISSUE TITLE
Unable to log in after submitting the password to the software, urgent

### ISSUE THREAD

**Issue by dlxydqz** [electerm/electerm#3088]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

After submitting the password for the software, when logging in, the prompt 'Login failed' will be displayed. Do you still need a password for software uninstallation and reinstallation? How can I solve this problem?

### What should have happened?(期望的结果)

Can log in to

**Comment by dlxydqz** [comment]
Recurrence: Multiple clicks on the submit arrow on the right during setup.
Solution:"AppData\Roaming\electerm\users\default_user\electerm.data.nedb",delete Or Edit salt and hashPassword

**Comment by zxdong262** [comment]
Thank you the feedback, would fix in next release
