### ISSUE TITLE
双击文字时，会将文字两边的空格也选中

### ISSUE THREAD

**Issue by danghuagood** [electerm/electerm#3089]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

现在新的版本在双击拷贝文字时，会将文字两边的空格也拷贝进去，之前的版本不会出现这个问题
![image](https://github.com/electerm/electerm/assets/8109501/a70337fa-b31b-4ac8-97b5-d2c9557a10e2)
![image](https://github.com/electerm/electerm/assets/8109501/dc4f3ce1-0034-42b7-9c4c-e9d00dfdcb00)

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入空格分隔，暂时可以参考https://github.com/electerm/electerm/issues/3087自己加入空格
