### ISSUE TITLE
sftp 打开本地文件时，中文文件名或者有中文目录时，无法打开文件

### ISSUE THREAD

**Issue by CRLLL** [electerm/electerm#3094]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.34.58.win-x64-installer.exe

### Platform detail (平台详情)

win64

### What steps will reproduce the bug?(重新问题的详细步骤)

sftp连接后，打开本地文件时，中文文件名或者有中文目录，无法打开文件，报错信息如下：
  Invoke-Item : ObjectNotFound

### What should have happened?(期望的结果)

可以正常打卡中文名文件或者有中文目录文件

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
请问后缀名是什么，如果到文件夹双击打开什么情况，会不会是没有绑定打开程序？

**Comment by CRLLL** [comment]
后缀名就是txt,在文件夹可以打开
![image](https://github.com/electerm/electerm/assets/20264874/f2bf69b1-0717-45f8-b573-6686914e527b)
