### ISSUE TITLE
rz命令上传的时候不显示进度条

### ISSUE THREAD

**Issue by wuwhai** [electerm/electerm#3096]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

rz命令上传文件的时候不显示进度条

### What steps will reproduce the bug?(重新问题的详细步骤)

 1、使用 rz命令上传文件
2、打开上传进度条，但是不显示进度百分比

### What should have happened?(期望的结果)

打开上传进度条，并显示进度百分比

**Comment by zxdong262** [comment]
如果有权限安装，可以试试 https://github.com/trzsz/trzsz
