### ISSUE TITLE
建议增加自定义css的功能

### ISSUE THREAD

**Issue by winddriver** [electerm/electerm#3097]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

比如允许用户创建一个custom.css，程序启动时自动加载该css即可，只要保证这个css最后加载，用户的修改就能覆盖默认值
这样用户就能很方便对界面进行一些简单的自定义

**Comment by zxdong262** [comment]
将在下个版本加入
![Screen Shot 2023-11-22 at 09 31 54](https://github.com/electerm/electerm/assets/1641949/687fef8f-fa92-4397-89c7-07b7d7725f1b)
