### ISSUE TITLE
No terminal emulation

### ISSUE THREAD

**Issue by shantur** [electerm/electerm#3098]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Hi,

Thanks for an excellent app.
I am using it for serial access and sometimes I need to disable all terminal emulation, just print plain text.
Is this feature possible ?

Thanks

**Comment by zxdong262** [comment]
Can you provide more detail? maybe screenshot from other serial terminal?

**Comment by shantur** [comment]
Thanks for reply. The screenshots attached are from Serial app from Appstore on Mac

<img width="593" alt="Screenshot 2023-11-16 at 13 52 01" src="https://github.com/electerm/electerm/assets/586441/10ca4a88-6a2f-4c97-8ee1-b32c65d869a0">
<img width="1313" alt="Screenshot 2023-11-16 at 13 52 47" src="https://github.com/electerm/electerm/assets/586441/6b5f1614-8db6-4da7-bed2-411cfb7c124d">

**Comment by zxdong262** [comment]
I will do some test to confirm, thank you for the feedback

**Comment by zxdong262** [comment]
Would add a display raw text switch in bookmark form in next release
![Screen Shot 2023-11-21 at 19 31 54](https://github.com/electerm/electerm/assets/1641949/4da14e59-afbd-4768-93bd-5fb2658aa9d4)
