### ISSUE TITLE
mac 默认新连接卡住

### ISSUE THREAD

**Issue by ddlzr** [electerm/electerm#3099]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.34.68-mac-x64.dmg

### Platform detail (平台详情)

Darwin huwangdeMacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.最近的一段时间的版本，每次安装后，第一次打开，默认打开的"新连接"标签页正常。
2.第二次开始，默认打开的"新连接"标签页，是卡住的状态，zsh和bash都是同样的问题。此时，再打开新的连接标签页是正常的。
用rm -rf ~/Library/Application\ Support/electerm* 清理后重装，也一样的问题。
zsh如下图：
![zsh](https://p.sda1.dev/14/fcadbe62e08f55f07fbb39e4de598c7d/electerm-bug-zsh.png)

bash如下图：
![bash](https://p.sda1.dev/14/3b7f109b53cdca029b6afcbe5809c3c3/electerm-bug-bash.png)

### What should have happened?(期望的结果)

希望默认打开的"新连接"标签页正常加载数据。

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by ddlzr** [comment]
> 可以试试最新版吗

试了最新的1.37.68版本，这个问题已经修复了。

**Comment by ddlzr** [comment]
辛苦
