### ISSUE TITLE
Highlight exit/Exit

### ISSUE THREAD

**Issue by hanhaowen-mt** [electerm/electerm#3102]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Exit/Exit is an important status keyword, it would be great if it could be highlighted and turned yellow

**Comment by zxdong262** [comment]
Can you provide more detail, maybe a screenshot?

**Comment by hanhaowen-mt** [comment]
![image](https://github.com/electerm/electerm/assets/144977798/07e7b15f-c96b-4159-8225-b9e7b96e7411)
![image](https://github.com/electerm/electerm/assets/144977798/cee6abd8-6367-4874-9a12-876ff36af63f)
![image](https://github.com/electerm/electerm/assets/144977798/bc7de914-958a-4543-b1d2-c58eb301dda2)

比如mobaxterm就会高亮information disabled exit ip地址等

**Comment by zxdong262** [comment]
明白了，感谢反馈，将在下个版本优化

**Comment by hanhaowen-mt** [comment]
> 明白了，感谢反馈，将在下个版本优化

感谢作者

**Comment by zxdong262** [comment]
在下个版本将支持自定义高亮关键词，支持正则
![Screen Shot 2023-11-23 at 20 16 36](https://github.com/electerm/electerm/assets/1641949/5eacaff4-03da-4d50-8928-177f84c620d9)

**Comment by hanhaowen-mt** [comment]
阿里嘎多裹扎伊马斯
