### ISSUE TITLE
一个终端程序搞什么快捷键啊, 这不和终端本身冲突的吗

### ISSUE THREAD

**Issue by 4781121** [electerm/electerm#3106]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64.tar.gz

### Platform detail (平台详情)

windows

### What steps will reproduce the bug?(重新问题的详细步骤)

真的是服了

### What should have happened?(期望的结果)

去掉快捷键或者设置成可开启或者可关闭的那种

### Additional information(其他任何相关信息)

无

**Comment by 4781121** [comment]
我用tmux Ctrl+b结果出来书签了, 我是真服了, 新版本怎么搞这功能

**Comment by zxdong262** [comment]
> 我用tmux Ctrl+b结果出来书签了, 我是真服了, 新版本怎么搞这功能

可以在这设置里换个别的快捷键

**Comment by zxdong262** [comment]
> 我用tmux Ctrl+b结果出来书签了, 我是真服了, 新版本怎么搞这功能

很多用户需要快捷键的，issue列表里就可以看到，每个人习惯不一样，冲突在所难免，新版本至少可以自行设置

**Comment by zxdong262** [comment]
不过ctrl+B确实不太合适，下个版本默认会设为ctrl+n

**Comment by zxdong262** [comment]
发布了 https://github.com/electerm/electerm/releases/tag/v1.35.6
