### ISSUE TITLE
1.35.0 版本开倒车!!!

### ISSUE THREAD

**Issue by linzhanyu** [electerm/electerm#3107]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

不要开倒车!
1. Fullscreen这个实用的占满窗口的按钮怎么就消失了呢?
2. ctrl + w 不要直接把连接给关了! 否则就无法方便地删除一些敲错的词.
3. 没等尝试直接回退版本了.

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
发布了 https://github.com/electerm/electerm/releases/tag/v1.35.6
