### ISSUE TITLE
Sftp栏目名称显示不全

### ISSUE THREAD

**Issue by miaokela** [electerm/electerm#3108]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.35.6-mac-arm64.dmg

### Platform detail (平台详情)

macos arm

### What steps will reproduce the bug?(重新问题的详细步骤)

Sftp栏目名称显示不全
<img width="967" alt="a" src="https://github.com/electerm/electerm/assets/30903265/2c7bb9d8-7245-426e-93ef-e958180c2801">

### What should have happened?(期望的结果)

正常显示

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
@miaokela 感谢赞助~！
