### ISSUE TITLE
自定义css不起作用

### ISSUE THREAD

**Issue by winddriver** [electerm/electerm#3109]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.35.6-win-x64-portable.tar.gz

### Platform detail (平台详情)

Windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

设置了如图的css
`.type-tab{text-transform: uppercase;padding: 0 20px}`
![image](https://github.com/electerm/electerm/assets/3221597/91d1d878-e0e2-4e04-a15e-404a1977edc0)

然后退出程序，并清空了 %APPDATA%\electerm 缓存目录
然后重新运行程序，结果见下图，css根本没生效
![image](https://github.com/electerm/electerm/assets/3221597/d41f1696-2274-4bd5-890a-9193cfc60523)

### What should have happened?(期望的结果)

希望自定义css能够生效

**Comment by zxdong262** [comment]
感谢反馈，确实重启后失效了，将在下个版本修复
