### ISSUE TITLE
electerm-1.36.1-mac-arm64.dmg 无法全屏

### ISSUE THREAD

**Issue by barryzpc** [electerm/electerm#3110]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.36.1-mac-arm64.dmg

### Platform detail (平台详情)

electerm-1.36.1-mac-arm64.dmg

### What steps will reproduce the bug?(重新问题的详细步骤)
![image](https://github.com/electerm/electerm/assets/20941518/0d590fdc-0d20-4f0f-af6f-80a9900141ba)
![image](https://github.com/electerm/electerm/assets/20941518/7c22d0c0-763e-454a-b425-b0038b4c4a07)

左上角窗口操作的三个按钮没有了。右上角的全屏按钮，在mac上并不能全屏

### What should have happened?(期望的结果)

mac上显示左上角的窗口操作按钮，并能全屏。去掉右上角windows窗口操作按钮

**Comment by zxdong262** [comment]
可以设置里使用系统标题栏

**Comment by barryzpc** [comment]
> 可以设置里使用系统标题栏

可以了，谢谢啦
