### ISSUE TITLE
1.36.1版本，捷径设置“终端缩放”快捷键后，原有快捷键没有被覆盖，mac按住command+鼠标滚轮依然可进行缩放

### ISSUE THREAD

**Issue by Lction** [electerm/electerm#3111]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.36.1-mac-arm64.dmg

### Platform detail (平台详情)

 mac os(ARM or x64)

### What steps will reproduce the bug?(重新问题的详细步骤)

1.36.1版本，捷径设置“终端缩放”快捷键后，原有快捷键没有被覆盖，mac按住command+鼠标滚轮依然可进行缩放
<img width="897" alt="image" src="https://github.com/electerm/electerm/assets/40019242/75c2a77a-57fa-468e-86b3-6a7426f18135">

### What should have happened?(期望的结果)

原有快捷键被覆盖

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
