### ISSUE TITLE
建议 将最新版的 1.36.1版本的 Ctrl+v 强制 设定为 终端的粘贴，改为用户可选

### ISSUE THREAD

**Issue by mianxiangdahai** [electerm/electerm#3115]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

建议 将最新版的 1.36.1版本的 Ctrl+v 强制 设定为 终端的粘贴，改为用户可选，现在的强制 Ctrl+v,为粘贴，会导致在使用vim编辑器的过程中，想要切换为 ’VISUAL BLOCK‘模式的时候，习惯性的按 Ctrl+v ，结果变成了粘贴 剪贴板 里面的内容，而无法进入 ’VISUAL BLOCK‘模式。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by zxdong262** [comment]
失败了，暂时改不了，可以用ctrl+q 切换为 ’VISUAL BLOCK‘模式

**Comment by zxdong262** [comment]
我知道原因了，将在下个版本修复
