### ISSUE TITLE
我只想打包win64的安装包，请问npm 命令是啥？

### ISSUE THREAD

**Issue by CRLLL** [electerm/electerm#3117]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

只打包win64的安装包npm 命令是啥？

**Comment by zxdong262** [comment]
```node build/bin/build-win-nsis```

**Comment by CRLLL** [comment]
![image](https://github.com/electerm/electerm/assets/20264874/d63008ba-ec4f-4f67-9644-93a7bc8782e4)
大哥，报这个错

**Comment by zxdong262** [comment]
这个看不出来，我自己也没有在windows上构建过，也是用github ci构建的，有什么需求吗，要自己构建？

**Comment by CRLLL** [comment]
![image](https://github.com/electerm/electerm/assets/20264874/b3b8c1b6-4cd4-4bbf-b73a-a0c05e36133f)
大哥 报这个错，知道啥问题吗？

**Comment by CRLLL** [comment]
我是在Codespaces里构建的，想着自己改改样式

**Comment by zxdong262** [comment]
设置里有自定义样式，可以试试满足需求不

**Comment by zxdong262** [comment]
如果用ci可以参考 https://github.com/electerm/electerm/blob/master/.github/workflows/win-nsis.yml

**Comment by CRLLL** [comment]
ok，我试试。辛苦了
