### ISSUE TITLE
1.37.1版本自动放大

### ISSUE THREAD

**Issue by louiejordan** [electerm/electerm#3118]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.1-win-x64.tar.gz

### Platform detail (平台详情)

Windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

每当移动边框的时候就会自动放大一次

### What should have happened?(期望的结果)

更新怕了，稳定就好，越更新问题越多

**Comment by zxdong262** [comment]
可以截图看看吗，我没有复现

**Comment by louiejordan** [comment]
> 可以截图看看吗，我没有复现

没办法截图，就是拖动一下边框它就会自动放大一圈，而且会随着拖动次数的增加无限放大。额，不知道这么解释能不能通。

**Comment by zxdong262** [comment]
只是终端放大还是整个UI缩放呢

**Comment by louiejordan** [comment]
> 只是终端放大还是整个UI缩放呢

就是整个终端放大，就是拖动一下就突然最大化的那种意思

**Comment by zxdong262** [comment]
> > 只是终端放大还是整个UI缩放呢
> 
> 就是整个终端放大，就是拖动一下就突然最大化的那种意思

可以远程看看不，我很想知道咋回事，我这里复现不了

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by louiejordan** [comment]
> 感谢反馈，将在下个版本修复

更新了，还是不行，我把旧版本全删了，全新的也是这样，有空我录个视频给你吧

**Comment by zxdong262** [comment]
> > 感谢反馈，将在下个版本修复
> 
> 更新了，还是不行，我把旧版本全删了，全新的也是这样，有空我录个视频给你吧

请问是1.37.16吗

**Comment by louiejordan** [comment]
> > > 感谢反馈，将在下个版本修复
> > 
> > 
> > 更新了，还是不行，我把旧版本全删了，全新的也是这样，有空我录个视频给你吧
> 
> 请问是1.37.16吗

就是你今天更新的：electerm-1.37.16-win-x64.tar.gz  奇怪为什么只有我有这个问题

**Comment by CRLLL** [comment]
我也有这个问题 点击下标题栏窗口就会变大。更新到1.37.16也是这样。还有个问题 拖动标签 鼠标就和窗口粘在一起了

**Comment by zxdong262** [comment]
> > > > 感谢反馈，将在下个版本修复
> > > 
> > > 
> > > 更新了，还是不行，我把旧版本全删了，全新的也是这样，有空我录个视频给你吧
> > 
> > 
> > 请问是1.37.16吗
> 
> 就是你今天更新的：electerm-1.37.16-win-x64.tar.gz 奇怪为什么只有我有这个问题

我找到一台电脑复现了，但是1.37.16在这台电脑可以修复

**Comment by zxdong262** [comment]
可以了解一下详细的电脑信息吗？屏幕分辨率刷新率，鼠标dpi

**Comment by louiejordan** [comment]
> 可以了解一下详细的电脑信息吗？屏幕分辨率刷新率，鼠标dpi

显示器4K60hz，系统Windows11 dev23590.1000，CPU是AMD 5600x，96G内存，显卡是6700xt，蓝牙鼠标有线键盘，DPI默认1000-1200

**Comment by zxdong262** [comment]
> 显示器4K60hz，系统Windows11 dev23590.1000，CPU是AMD 5600x，96G内存，显卡是6700xt，蓝牙鼠标有线键盘，DPI默认1000-1200

可以调低dpi试试不

**Comment by louiejordan** [comment]
> > 显示器4K60hz，系统Windows11 dev23590.1000，CPU是AMD 5600x，96G内存，显卡是6700xt，蓝牙鼠标有线键盘，DPI默认1000-1200
> 
> 可以调低dpi试试不或者其他鼠标

不行，我调到最低600，还是一样

**Comment by zxdong262** [comment]
可以试试1.37.20吗，有人说这版本修复了

**Comment by louiejordan** [comment]
> 可以试试1.37.20吗，有人说这版本修复了

更新了，没问题
