### ISSUE TITLE
新版本 electerm 快捷键和终端里的组合键冲突

### ISSUE THREAD

**Issue by 9-2-1** [electerm/electerm#3119]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

在使用新版 electerm 时，ctrl+a ctrl+v 这些按键会被理解为全选/粘贴，alt+w会被理解为关闭终端，这在使用 vim/emacs 的时候会不方便

建议：在终端进入应用模式（类似vim/emacs独占窗口）时暂时禁用快捷键，或者添加快捷键关闭功能（当前无法关闭快捷键，尤其是粘贴的组合键不能修改）

**Comment by zxdong262** [comment]
alt+f可以在设置快捷键里改成别的，ctrl+c/ctrl+v的我试了没有修改成功，得研究一下

**Comment by zxdong262** [comment]
最新版解决了，可以试试
