### ISSUE TITLE
Please stop these stupid shortcut keys

### ISSUE THREAD

**Issue by linzhanyu** [electerm/electerm#3121]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

There are already shortcut keys for copying and pasting, why do we need to add several non-configurable Ctrl-C/V/X?
How to adapt an SSH terminal to Windowser's operating habits?
VIM user says: Fuck Ctrl-V

**Comment by zxdong262** [comment]
Thank you for the feedback, it indeed caused by these extra settings, will fix in next release, sorry for the trouble caused by these versions.

**Comment by zxdong262** [comment]
I thoght it is xtermjs default setting issue, your feedback reminds me, then I realized it is my extra setting caused it.
