### ISSUE TITLE
双击标题栏不能最大化界面

### ISSUE THREAD

**Issue by advancejar** [electerm/electerm#3123]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.36.1-win-x64-portable.tar.gz

### Platform detail (平台详情)

win10 企业版

### What steps will reproduce the bug?(重新问题的详细步骤)

双击标题栏不能最大化界面

### What should have happened?(期望的结果)

双击放大或还原

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

一直存在

**Comment by zxdong262** [comment]
> 1.37.6问题更严重了，现在双击后虽然能放大，但是鼠标左键按住标题栏往左上拖动下整个框就变大（右和下都增大），循环往复。

是跟https://github.com/electerm/electerm/issues/3118一样的情况吗

**Comment by advancejar** [comment]
是的，就是这个问题

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
可以试试1.37.16吗
