### ISSUE TITLE
书签新增后无法删除，建议新增删除功能

### ISSUE THREAD

**Issue by li362692680** [electerm/electerm#3124]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/electerm/electerm/assets/23658572/ebb851e3-f27f-4425-8508-bd056c7150d0)

**Comment by zxdong262** [comment]
![Screen Shot 2023-11-27 at 14 26 54](https://github.com/electerm/electerm/assets/1641949/401248f9-a017-4896-a213-dea6609d236f)
是在设置里面吗？

**Comment by li362692680** [comment]
![image](https://github.com/electerm/electerm/assets/23658572/e6c2b173-7f12-487a-9c3c-f24f27c341ed)
为什么第一个标签分类没有删除按钮，第二个有

**Comment by zxdong262** [comment]
默认的不允许删除
