### ISSUE TITLE
增加SFTP不使用打包的选项

### ISSUE THREAD

**Issue by Seraphli** [electerm/electerm#3126]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

在很早之前的版本中，SFTP下载到本地的时候是不会打包然后下载的，这个逻辑在最近的版本变成了打包然后下载。我看到进度条一直卡在0，看到过gzip的进程，而有些文件gzip并不会加速多少。比如包含了一个视频文件，gzip不会压缩多少，但是会耗费很长时间进行打包工作。这个行为最好能够开放一个选项，让用户选择是否开启。对于很多小文件的情况，打包确实能加速，但是对于大文件就不能加速。另外如果要打包，也可以考虑使用能够并行压缩的软件，并且用户可以指定进程数，这样就不至于卡在进度0。另外打包最好能在进度里显示正在打包，而不是显示进度0。还有我还碰到过长时间等待之后发现gzip的进程没了，但是进度还是0的情况。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化
