### ISSUE TITLE
SFTP下载路径设置错误

### ISSUE THREAD

**Issue by Seraphli** [electerm/electerm#3127]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.34.68

### Platform detail (平台详情)

Linux 6.1.62-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Nov  9 03:01:44 UTC 2023 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

大概是当下载的路径中存在冒号时？，下载的文件在目录同一级产生了，并且文件名出现了问题。可能是因为这个文件名只可能存在于Linux系统所以没有测试到

1. 建立名为`2023-11-27 19:10:24`的文件夹
2. electerm中进入这个文件夹，然后拖拽远程文件下载

![image](https://github.com/electerm/electerm/assets/1586755/33d66068-7f97-46df-b56e-7cce1e2414d4)

### What should have happened?(期望的结果)

保存在文件夹下

**Comment by zxdong262** [comment]
bing的gpt4说不能用冒号？
The use of colons (:) in file and folder names is not recommended on macOS and Linux systems. [On macOS, colons are used as directory indicators, and using them in file or folder names can cause issues with the Finder and other applications ](https://superuser.com/questions/1662786/how-to-find-files-that-have-a-colon-in-the-file-name)[1](https://superuser.com/questions/1662786/how-to-find-files-that-have-a-colon-in-the-file-name). [On Linux systems, colons are not allowed in file or folder names by default ](https://freefilesync.org/forum/viewtopic.php?t=9279)[2](https://freefilesync.org/forum/viewtopic.php?t=9279).

If you need to use a special character in a file or folder name, consider using an underscore (_) or a hyphen (-) instead.

I hope this helps!

**Comment by Seraphli** [comment]
Manjaro上可以使用。

**Comment by zxdong262** [comment]
明白了，将在下个版本修复
