### ISSUE TITLE
快捷键分屏有问题，打开多台服务器连接，每次快捷键分屏都是第一个tab ，看着有点像使用快捷键无法确定当前所在的tab。默认都是第一个tab中进行分屏

### ISSUE THREAD

**Issue by Loading828** [electerm/electerm#3129]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-x64.dmg

### Platform detail (平台详情)

快捷键分屏有问题，打开多台服务器连接，每次快捷键分屏都是第一个tab ，看着有点像使用快捷键无法确定当前所在的tab。默认都是第一个tab中进行分屏

### What steps will reproduce the bug?(重新问题的详细步骤)

快捷键分屏有问题，打开多台服务器连接，每次快捷键分屏都是第一个tab ，看着有点像使用快捷键无法确定当前所在的tab。默认都是第一个tab中进行分屏

### What should have happened?(期望的结果)

使用快捷键分屏，不管当前所在任何tab ，只会操作当前的tab，进行分屏，不会默认只对第一个tab进行分屏

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

快捷键分屏有问题，打开多台服务器连接，每次快捷键分屏都是第一个tab ，看着有点像使用快捷键无法确定当前所在的tab。默认都是第一个tab中进行分屏

### Additional information(其他任何相关信息)

快捷键分屏有问题，打开多台服务器连接，每次快捷键分屏都是第一个tab ，看着有点像使用快捷键无法确定当前所在的tab。默认都是第一个tab中进行分屏

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by Loading828** [comment]
好的，感谢，现在看已经修复了👍
