### ISSUE TITLE
希望可以加一个命令收藏功能

### ISSUE THREAD

**Issue by li362692680** [electerm/electerm#3132]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

希望可以加一个命令收藏功能，收藏经常执行的命令。

**Comment by zxdong262** [comment]
可以试试快速命令功能
![Screen Shot 2023-11-28 at 11 41 23](https://github.com/electerm/electerm/assets/1641949/079d04f2-f0b7-46f8-bd2e-df9315e31236)
![Screen Shot 2023-11-28 at 11 41 42](https://github.com/electerm/electerm/assets/1641949/de33229d-649a-4ab8-9d29-c5d80ad983d1)
