### ISSUE TITLE
请求关键字高亮示例

### ISSUE THREAD

**Issue by hanhaowen-mt** [electerm/electerm#3133]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/electerm/electerm/assets/144977798/e1e4b6dc-91c8-4661-b41b-58d642bc14b4)
如图，正则表达式写法有很多种，不知道electerm支持的是哪种写法？我这样写是希望匹配fail/failed，但是直接electerm就挂了这样写，能否添加正则表达式示例？

**Comment by zxdong262** [comment]
```failed|fail```就行了

**Comment by zxdong262** [comment]
将在下个版本加入示例
