### ISSUE TITLE
Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by flycomte-mzx** [electerm/electerm#3135]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.16-1-linux-amd64.deb

### Platform detail (平台详情)

Linux g7 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

when start the app, can't run it.
![Selection_016](https://github.com/electerm/electerm/assets/81898342/fc777a93-62ee-48c7-b450-695ed120a838)

### What should have happened?(期望的结果)

I have re-install 1.37.16-1 or 1.37.1-1, both has the same error.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

no

**Comment by zxdong262** [comment]
how is the PC memeory size, more than 512M?

**Comment by zxdong262** [comment]
Newly installed one or upgrade to new version?

**Comment by zxdong262** [comment]
Could be load a big json file bigger than 512M, any thing unusual?

**Comment by zxdong262** [comment]
Can you run `ls -al ~/.config/electerm/users/default_user/` to see the file sizes

**Comment by flycomte-mzx** [comment]
(base) zhixiang@g7:~$ ls -al ~/.config/electerm/users/default_user/
total 636100
drwxrwxr-x 2 zhixiang zhixiang      4096 12月  4 12:56 .
drwxrwxr-x 3 zhixiang zhixiang      4096 6月  27 00:23 ..
-rw-rw-r-- 1 zhixiang zhixiang         0 12月  4 12:56 electerm.addressBookmarks.nedb
-rw-rw-r-- 1 zhixiang zhixiang       154 12月  4 12:56 electerm.bookmarkGroups.nedb
-rw-rw-r-- 1 zhixiang zhixiang      6307 12月  4 12:56 electerm.bookmarks.nedb
-rw-rw-r-- 1 zhixiang zhixiang    717890 12月  4 12:56 electerm.data.nedb
-rw-rw-r-- 1 zhixiang zhixiang      2225 12月  4 12:56 electerm.dbUpgradeLog.nedb
-rw-rw-r-- 1 zhixiang zhixiang     18037 12月  4 12:56 electerm.history.nedb
-rw-rw-r-- 1 zhixiang zhixiang         0 10月 17 10:01 electerm.jumpHosts.nedb
-rw-rw-r-- 1 zhixiang zhixiang 650592004 11月 28 16:57 electerm.lastStates.nedb
-rw-rw-r-- 1 zhixiang zhixiang         0 12月  4 12:56 electerm.log.nedb
-rw-rw-r-- 1 zhixiang zhixiang         0 12月  4 12:56 electerm.quickCommands.nedb
-rw-rw-r-- 1 zhixiang zhixiang      1540 12月  4 12:56 electerm.terminalThemes.nedb

**Comment by zxdong262** [comment]
看起来lastStates处理有bug

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
