### ISSUE TITLE
1.37.16版本窗口会不停自动变大

### ISSUE THREAD

**Issue by dragon-dan** [electerm/electerm#3141]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.16-win-x64-portable.tar.gz

### Platform detail (平台详情)

win11

### What steps will reproduce the bug?(重新问题的详细步骤)

在非最大化窗口模式，鼠标拖动窗口的时候，窗口边缘一直在闪动，发现窗口在不停变大。测试几次发现只要鼠标在顶部可拖动的标签栏上按住左键不松，就会出现这个情况

### What should have happened?(期望的结果)

自定义大小模式，窗口大小不要变化

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

其他软件没发现

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.37.20 吗

**Comment by dragon-dan** [comment]
> 可以试试 https://github.com/electerm/electerm/releases/tag/v1.37.20 吗

这个版本的可以了
