### ISSUE TITLE
新版本更新的提示中 忽略按钮点击好像没什么反应

### ISSUE THREAD

**Issue by miaokela** [electerm/electerm#3142]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.16-mac-arm64.dmg

### Platform detail (平台详情)

mac os arm

### What steps will reproduce the bug?(重新问题的详细步骤)

新版本更新的提示中 忽略按钮点击好像没什么反应
<img width="407" alt="1" src="https://github.com/electerm/electerm/assets/30903265/295058bf-2321-41d9-91b0-85a2c4d560aa">

### What should have happened?(期望的结果)

应该是隐藏窗口，并且下次更新前不再提示

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
