### ISSUE TITLE
修改了生成书签名称的程序后，书签名称不变

### ISSUE THREAD

**Issue by NB611** [electerm/electerm#3146]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.37.20

### Platform detail (平台详情)

win

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/20264874/a05db6f6-fd40-4980-9aff-eddd7c57671e)
![image](https://github.com/electerm/electerm/assets/20264874/fde71389-78e2-4022-a09d-e28bc7511cf9)
我fork了本项目，然后修改了生成书签名称的程序，去掉了后面的登录名和IP，使用github action构建打包，
    图一是软件主窗口，书签名称没改变；
    图二是新建窗口，书签名改过来了。
请问书签名称是有缓存吗，怎么清理缓存？

### What should have happened?(期望的结果)

希望主窗口的书签名称可以正常展示 我修改后的书签名

**Comment by zxdong262** [comment]
有缓存，可以把package.json里版本号改掉，重新构建即可，或者从菜单里打开开发者工具，在网络里关闭缓存刷新一次即可
![Screen Shot 2023-12-01 at 16 06 37](https://github.com/electerm/electerm/assets/1641949/57bf1d52-a3c6-4de8-91cf-271167f20860)

**Comment by NB611** [comment]
刷新了下，可以了，多谢
