### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by xizonghu** [electerm/electerm#3149]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.20-linux-x64.tar.gz

### Platform detail (平台详情)

ubuntu22.04

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/25141630/90c95694-3194-475c-b9e7-dd4d6073003b)

### What should have happened?(期望的结果)

能正常使用

**Comment by zxdong262** [comment]
.deb可以试试吗

**Comment by zxdong262** [comment]
有处理过什么大文件吗，超过2g的

**Comment by xizonghu** [comment]
先安装了deb，我主机有3个屏幕，发现electerm只能以全屏方式附在第1，3屏幕上，不能显示在中间的2号屏幕上。然后关闭软件，在打开就提示上述错误了。然后就卸载了deb，下载了tar.gz包，解压后直接打开可执行文件，发现还是一样的错误

**Comment by zxdong262** [comment]
可以`ls -al ~/.config/electerm/users/default_user/`看看文件情况不

**Comment by xizonghu** [comment]
![image](https://github.com/electerm/electerm/assets/25141630/8911a750-af6c-4a47-8f23-9a76eea413fd)
这么大啊。
rm -rf ~/.config/electerm/users/default_user/*
删除后，可以打开软件了，但还是会出现"electerm只能以全屏方式附在第1，3屏幕上，不能显示在中间的2号屏幕上，在1，3屏幕上也不能正常窗口化，只能最小化或最大化"的问题

**Comment by xizonghu** [comment]
rm -rf ~/.config/electerm/users/default_user/*
删除后，可以打开软件了，但还是会出现"electerm只能以全屏方式附在第1，3屏幕上，不能显示在中间的2号屏幕上，在1，3屏幕上也不能正常窗口化，只能最小化或最大化"的问题

**Comment by zxdong262** [comment]
感谢反馈，lastState处理有bug导致的，将在下个版本修复

**Comment by zxdong262** [comment]
最新版修复了这个问题
