### ISSUE TITLE
bookmarks的标签能不能可以改变宽度啊？

### ISSUE THREAD

**Issue by kele2016** [electerm/electerm#3153]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

参考Xshell。因为目前是固定宽度的。（也许是我没找到？）
我喜欢给固定住，这样，有的IP+端口显示不出来。
![image](https://github.com/electerm/electerm/assets/17295910/33af2a95-7b2f-48cf-91f3-e44de4ce8e60)
如果可以允许向右增加宽度，就好了。

**Comment by zxdong262** [comment]
感谢反馈，将在后续版本加入

**Comment by kele2016** [comment]
![5115809-3111360426-kakas](https://github.com/electerm/electerm/assets/17295910/8658e60a-ff0a-462c-816d-f14d5ea71e0e)
这个是变宽了。但是省略号部分，并没有加载出来。

**Comment by zxdong262** [comment]
> ![QQ截图20240103110335](https://private-user-images.githubusercontent.com/17295910/293825846-83919ab0-72a9-4eed-bdab-efba1a9aa67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTMyMjAsIm5iZiI6MTcwNDYxMjkyMCwicGF0aCI6Ii8xNzI5NTkxMC8yOTM4MjU4NDYtODM5MTlhYjAtNzJhOS00ZWVkLWJkYWItZWZiYTFhOWFhNjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA3MzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZjVhNjkyZTU2ZTA5YzNjYjg4OTYwZjZmZTRkNWQ2MzdhNTk5YmMyNDliMzI3MjY4OGI2YTNmODQxOTVkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KKwoXZBsbQdK05u44vTaoTkNwfkvSKWIpNs4MFc_im0)
> 
> 这个是变宽了。但是省略号部分，并没有加载出来。

将在下个版本优化
