### ISSUE TITLE
backspace key turn into null key

### ISSUE THREAD

**Issue by dhtz123456** [electerm/electerm#3159]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.38-win-x64-installer.exe

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/129825070/1a37d8e7-6219-462c-8325-03cdbcd8fc76)

### What should have happened?(期望的结果)

![image](https://github.com/electerm/electerm/assets/129825070/3eb62bd6-8a64-4fcc-8a5d-f3db5fcd0c10)

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

not happen in other terminal app

**Comment by zxdong262** [comment]
试了一下没有复现，方便详细描述下吗，可能有细节没注意到，或者有其他电脑可以试试对比一下，有什么不一样的

**Comment by wpf973** [comment]
个人目前发现H3C v5的设备不能删除 目前用  ctrl+h进行删除。。。

**Comment by dhtz12** [comment]
弄删除按钮一直是空格，我试了四个服务器有两个出现这种问题，我也不知道这两个服务器有什么区别

**Comment by dhtz12** [comment]
四个服务器都是虚拟机，不知道跟什么配置有关

**Comment by dhtz12** [comment]
我的ctrl + h 也是空格，没法删除

**Comment by zxdong262** [comment]
必应的gpt-4给出的答案是：
```
您的服务器的 stty 设置不正确，导致它无法正确识别退格键发送的字符。您可以在服务器上运行 stty -a 命令，查看 erase 字段的值，一般应该是 ^? 或 ^H。如果不是，您可以使用 stty erase ^? 或 stty erase ^H 命令，将 erase 字段的值设置为正确的字符。您可以通过按 Ctrl + v 然后按退格键，来查看您的终端发送的退格字符是什么。
```

**Comment by zxdong262** [comment]
我看看能不能在electerm里兼容

**Comment by zxdong262** [comment]
另外根据https://github.com/termux/termux-packages/issues/1061#issuecomment-334784572，可以试试运行
```sh
TERM=xterm-color256
```
试试

**Comment by wpf973** [comment]
> 必应的gpt-4给出的答案是：
> 
> > 您的服务器的 stty 设置不正确，导致它无法正确识别退格键发送的字符。您可以在服务器上运行 stty -a 命令，查看 erase 字段的值，一般应该是 ^？或 ^H。如果不是，您可以使用 stty erase ^？或 stty erase ^H 命令，将 erase 字段的值设置为正确的字符。您可以通过按 Ctrl + v 然后按退格键，来查看您的终端发送的退格字符是什么。


目前发现H3C V5平台是不能删除。 H3Cv7是正常的。 个人一般是交换机、路由器这些网络设备用的 这些东西环境是写死的，没法修改

**Comment by zxdong262** [comment]
#1767

**Comment by zxdong262** [comment]
将在下个版本尝试提供支持

**Comment by wpf973** [comment]
![image](https://github.com/electerm/electerm/assets/22835238/1b13c511-4bb3-43b7-ad42-9ad470c0e891)

**Comment by wpf973** [comment]
从putty看到了这个 ，应该就是这的问题，，估计需要加个选项

**Comment by zxdong262** [comment]
加了个shift+backspace识别， 就是另外一种输出

**Comment by wpf973** [comment]
加个选项 更舒服点~毕竟一次修改。一直收益

**Comment by zxdong262** [comment]
> 加个选项 更舒服点~毕竟一次修改。一直收益

目前的修改测试的结果是兼容两种情况，不用按shift，可能得下个版本实际测试看看，如果在实际的设备商不好使，会尝试加个选项

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.37.80 吗

**Comment by zxdong262** [comment]
Can you try https://github.com/electerm/electerm/releases/tag/v1.37.80

**Comment by zxdong262** [comment]
最新版在终端设置里加入了退格键设置^?或者^H，同时也可以shift+backspace键切换
