### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by websecer** [electerm/electerm#3162]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![doc_2023-12-09_00-29-53](https://github.com/electerm/electerm/assets/15323260/cdbfad0d-f723-4a8b-9b57-255ff78367b6)

**Comment by RomaneeSean** [comment]
我也是无法更新，点击更新一直0%，windows10，openvpn 香港的节点  开不开vpn都一样

**Comment by zxdong262** [comment]
请问从哪个版本升级的

**Comment by websecer** [comment]
我N个月前也用过这个工具，但是是ubuntu系统，也是无法升级，从我使用这个工具那一刻起，就没有升级成功过，而且升级提示还挺频繁

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复，确实是windows下有问题
