### ISSUE TITLE
现在command+w 快捷键盘不能关闭标签了？

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3163]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.46-mac-x64.dmg

### Platform detail (平台详情)

mac x86

### What steps will reproduce the bug?(重新问题的详细步骤)

现在command+w 快捷键盘不能关闭标签了

### What should have happened?(期望的结果)

command+w 快捷键关闭标签,  我记得以前是支持的啊

**Comment by zxdong262** [comment]
可以在快捷键设置修改，默认是alt+w
