### ISSUE TITLE
粘贴文本时，总是会在前后加上几个字符，导致只能手动修改，比如我要粘贴 “path-to-file”，实际粘贴的是“00~path-to-file01~”

### ISSUE THREAD

**Issue by anzhizecheng** [electerm/electerm#3164]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.46-mac-arm64.dmg

### Platform detail (平台详情)

mac os arm

### What steps will reproduce the bug?(重新问题的详细步骤)

复制一段文字，粘贴到终端窗口，比如我要粘贴 “path-to-file”，实际粘贴的是“00~path-to-file01~”

### What should have happened?(期望的结果)

当粘贴 “path-to-file”，实际粘贴的是“path-to-file”，不要附加任何额外字符

**Comment by zxdong262** [comment]
请问从github这里复制的也会这样吗 ```path-to-file```
