### ISSUE TITLE
v1.37.58 出现异常无法使用

### ISSUE THREAD

**Issue by lowmanisbusy** [electerm/electerm#3166]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

打开后出现如下异常：
Cannot destructure property 'id' of 'e' as it is null.
TypeError: Cannot destructure property 'id' of 'e' as it is null. at http://127.0.0.1:30974/js/electerm-1.37.58.js:173:50927 at Array.map (<anonymous>) at Go.render (http://127.0.0.1:30974/js/electerm-1.37.58.js:173:52068) at Jl (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:30:65233) at si (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:30:65031) at ya (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:9572) at pa (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:932) at cc (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:863) at fn (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:722) at ao (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:32:10777)

### What should have happened?(期望的结果)

![Snipaste_2023-12-12_09-49-31](https://github.com/electerm/electerm/assets/34531528/42241ca1-7bd3-4234-a666-4728ceae5ea0)

**Comment by zxdong262** [comment]
可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看

**Comment by SoDebug** [comment]
> 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看

我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗

**Comment by zxdong262** [comment]
> > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> 
> 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗

对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗

**Comment by SoDebug** [comment]
> > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > 
> > 
> > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> 
> 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗

在公司电脑上，明天可以发

**Comment by SoDebug** [comment]
> > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > 
> > 
> > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> 
> 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗

[electerm.quickCommands.zip](https://github.com/electerm/electerm/files/13654751/electerm.quickCommands.zip)

**Comment by zxdong262** [comment]
> > > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > > 
> > > 
> > > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> > 
> > 
> > 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗
> 
> [electerm.quickCommands.zip](https://github.com/electerm/electerm/files/13654751/electerm.quickCommands.zip)

请问删除这个文件能启动吗？

**Comment by lowmanisbusy** [comment]
我看上面有个出现了相同异常的朋友已经发出了你需要的文件，我已降级到了早前正常的版本，就不重复发送了，感谢作者的无私奉献，希望项目越来越好。

> 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看

**Comment by SoDebug** [comment]
> > > > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > > > 
> > > > 
> > > > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> > > 
> > > 
> > > 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗
> > 
> > 
> > [electerm.quickCommands.zip](https://github.com/electerm/electerm/files/13654751/electerm.quickCommands.zip)
> 
> 请问删除这个文件能启动electerm 1.37.58吗？

能，不过不删除也能，只是会概率性的弹出那个报错

**Comment by zxdong262** [comment]
> > > > > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > > > > 
> > > > > 
> > > > > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> > > > 
> > > > 
> > > > 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗
> > > 
> > > 
> > > [electerm.quickCommands.zip](https://github.com/electerm/electerm/files/13654751/electerm.quickCommands.zip)
> > 
> > 
> > 请问删除这个文件能启动electerm 1.37.58吗？
> 
> 能，不过不删除也能，只是会概率性的弹出那个报错

是机械硬盘还是固态硬盘呢

**Comment by SoDebug** [comment]
> > > > > > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > > > > > 
> > > > > > 
> > > > > > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> > > > > 
> > > > > 
> > > > > 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗
> > > > 
> > > > 
> > > > [electerm.quickCommands.zip](https://github.com/electerm/electerm/files/13654751/electerm.quickCommands.zip)
> > > 
> > > 
> > > 请问删除这个文件能启动electerm 1.37.58吗？
> > 
> > 
> > 能，不过不删除也能，只是会概率性的弹出那个报错
> 
> 是机械硬盘还是固态硬盘呢

固态

**Comment by zxdong262** [comment]
> > > > > > > > 可以发一下 C:\Users\你的用户名\AppData\Roaming\electerm\users\default_user\electerm.quickCommands.nedb看看吗，然后把它改名成xx.nedb0再次启动electerm看看
> > > > > > > 
> > > > > > > 
> > > > > > > 我也有这个问题，而且频繁出现。“xx”是指1任意字符串吗
> > > > > > 
> > > > > > 
> > > > > > 对，其实删除也一样，只是想看看数据上有什么异常，如果方便的话可以发一下吗
> > > > > 
> > > > > 
> > > > > [electerm.quickCommands.zip](https://github.com/electerm/electerm/files/13654751/electerm.quickCommands.zip)
> > > > 
> > > > 
> > > > 请问删除这个文件能启动electerm 1.37.58吗？
> > > 
> > > 
> > > 能，不过不删除也能，只是会概率性的弹出那个报错
> > 
> > 
> > 是机械硬盘还是固态硬盘呢
> 
> 固态

是打开electerm就出现这个错误还是需要某些操作？跟截图的报错位置一模一样吗？

**Comment by zxdong262** [comment]
发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗

**Comment by SoDebug** [comment]
> 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗

因为是在项目中使用串口进行调试时发现的，现在项目进入下一个阶段了移交了，我暂时无法继续测试😥😥。抱歉啊

**Comment by lowmanisbusy** [comment]
> 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗

经测试使用，没有再出现以上异常。

**Comment by lowmanisbusy** [comment]
> > 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗
> 
> 因为是在项目中使用串口进行调试时发现的，现在项目进入下一个阶段了移交了，我暂时无法继续测试😥😥。抱歉啊



> 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗

**Comment by lowmanisbusy** [comment]
> 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗

还是会出现，之前是只要打开软件就一直出现异常，现在是不是时不时会出现。

**Comment by zxdong262** [comment]
发布了 https://github.com/electerm/electerm/releases/tag/v1.37.66 应该修复了，方便试试吗

**Comment by lowmanisbusy** [comment]
> 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.66 应该修复了，方便试试吗

升级了最新版，测试使用半天，没有再现异常，看后续运行情况。
