### ISSUE TITLE
"drag to resize side panel"功能向左拖拽超过一定宽度就显示异常

### ISSUE THREAD

**Issue by miaokela** [electerm/electerm#3169]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.58-mac-arm64.dmg

### Platform detail (平台详情)

macos arm

### What steps will reproduce the bug?(重新问题的详细步骤)

"drag to resize side panel"功能向左拖拽超过一定(最小)宽度就显示异常
<img width="510" alt="image" src="https://github.com/electerm/electerm/assets/30903265/d70a555b-dc26-47a3-b46b-d5d75d2ba684">

### What should have happened?(期望的结果)

修复，到最小宽度就无法向左拖动

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by miaokela** [comment]
而且这个拖拽会有一个奇怪的回弹效果，不一定能拖到指定位置。

**Comment by miaokela** [comment]
<img width="764" alt="image" src="https://github.com/electerm/electerm/assets/30903265/2ee59dad-1093-4062-85f1-e339f61500db">
还有命令行宽度没有自适应
