### ISSUE TITLE
1.37.58 使用的时候 报错Cannot destructure property 'id' of 'e' as it is null.

### ISSUE THREAD

**Issue by yangLin98** [electerm/electerm#3171]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.58-win-x64-installer.exe

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

Cannot destructure property 'id' of 'e' as it is null.
TypeError: Cannot destructure property 'id' of 'e' as it is null. at http://127.0.0.1:30974/js/electerm-1.37.58.js:173:50927 at Array.map (<anonymous>) at Go.render (http://127.0.0.1:30974/js/electerm-1.37.58.js:173:52068) at Jl (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:30:65233) at si (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:30:65031) at ya (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:9572) at pa (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:932) at cc (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:863) at fn (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:34:722) at ao (http://127.0.0.1:30974/chunk/react-1.37.58-fc7967b2.js:32:10777)

### What should have happened?(期望的结果)

希望能修复好

**Comment by zxdong262** [comment]
启动就报错还是需要什么操作呢

**Comment by yangLin98** [comment]
> 启动就报错还是需要什么操作呢

用着用着，没有异常操作，就报这个错

**Comment by yangLin98** [comment]
![Uploading 微信截图_20231213150823.png…]()

**Comment by yangLin98** [comment]
![微信截图_20231213150823](https://github.com/electerm/electerm/assets/48380561/7c653dab-74cd-4509-a350-ac377a4d6680)

**Comment by zxdong262** [comment]
发布了 https://github.com/electerm/electerm/releases/tag/v1.37.60 尝试修复这个问题，不过是依据报错位置的表面修复，还不清楚根本原因，可以试试吗
