### ISSUE TITLE
Proxy 功能异常

### ISSUE THREAD

**Issue by barry-chen0901** [electerm/electerm#3175]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.37.60

### Platform detail (平台详情)

windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

新版本 1.37.60 不能使用配置代理去访问 ssh 远程server

1. 启用全局代理
![image](https://github.com/electerm/electerm/assets/68989626/4658141b-e989-4d08-8058-62c3d0deee70)
2. 连接失败：
![image](https://github.com/electerm/electerm/assets/68989626/e9bf1d44-4317-4b9a-be8a-ee7e1ca5a6dd)

我能确保我的代理是可用的，因为我用electerm-1.24.13 的版本是没有问题的

### What should have happened?(期望的结果)

能在新版本1.37.60里使用http://<proxy_server>:3128 代理连接上远程linux server

**Comment by barry-chen0901** [comment]
补充一下，是说的这个全局代理配置：
![image](https://github.com/electerm/electerm/assets/68989626/dc573296-8fa0-4898-8ed8-d8643dfbfc1e)

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
发布了 https://github.com/electerm/electerm/releases/tag/v1.37.66 修复了

**Comment by barry-chen0901** [comment]
> 发布了 https://github.com/electerm/electerm/releases/tag/v1.37.66 修复了

可以了。感谢！！会持续支持这个软件
