### ISSUE TITLE
exit/logout命令不能关闭标签页

### ISSUE THREAD

**Issue by dan-kuroto** [electerm/electerm#3180]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.68-win-x64-installer.exe

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

- 使用本机PowerShell（新连接）时，输入 `exit` 命令后，标签页不会自动关闭
- 连接服务器时，输入 `exit` 命令能关闭标签页，但输入 `logout` 命令不能关闭标签页，会弹出提示 `终端连接丢失`

### What should have happened?(期望的结果)

- 使用本机PowerShell（新连接）时，输入 `exit` 命令后，标签页能自动关闭
- 连接服务器时，输入 `logout` 命令能自动关闭标签页

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化
