### ISSUE TITLE
批量上传文件时，一直提示文件冲突

### ISSUE THREAD

**Issue by RULAISZ** [electerm/electerm#3182]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.68-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

批量上传文件提示文件冲突，但是远程文件夹里并无提示的冲突文件
选择全部覆盖无用
从冲突文件开始后面的文件全部停止上传，进度条为0%，不再上传

### What should have happened?(期望的结果)

正常上传文件

**Comment by zxdong262** [comment]
可以截图看看操作详情吗

**Comment by whqgo** [comment]
删掉之前的刷新下在上传就行

**Comment by RULAISZ** [comment]
> 可以截图看看操作详情吗

公司的文件，不太好截图

**Comment by RULAISZ** [comment]
> 可以截图看看操作详
