### ISSUE TITLE
删除键在删字符时太慢了，像电脑卡了一样

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3185]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.80-mac-x64.dmg

### Platform detail (平台详情)

mac x86

### What steps will reproduce the bug?(重新问题的详细步骤)

随便打点字符，然后按信删除键不放手，  删除得太慢了。像电脑卡了一样

### What should have happened?(期望的结果)

正常速度删除

### Additional information(其他任何相关信息)

![z9](https://github.com/electerm/electerm/assets/8625218/47e13cf8-2524-431a-b4e2-2b0d3bb02517)

**Comment by rikukiix** [comment]
可以试着先退回1.37.68版本

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by xxoxx** [comment]
1.37.88 版本问题依旧啊，还没有改啊  @zxdong262

**Comment by zxdong262** [comment]
> 1.37.88 版本问题依旧啊，还没有改啊 @zxdong262

下个版本

**Comment by zxdong262** [comment]
可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.37.92

**Comment by zyz954489346** [comment]
> 可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.37.92

长字符删除还是卡，版本是最新版v1.37.92 macos-arm64。
我的系统是MacOS(m1x) 12.0.1 。
退回十月3的版本就不卡了。

**Comment by Kabulaka** [comment]
返回68小版本不卡

**Comment by miaokela** [comment]
刚更新了，也注意到这个删除确实不流畅

**Comment by zxdong262** [comment]
最新版本修复了 https://github.com/electerm/electerm/releases/tag/v1.37.93

**Comment by zyz954489346** [comment]
> 最新版本修复了 https://github.com/electerm/electerm/releases/tag/v1.37.93

我下载来试了下，长字符删除还是不够流畅。
v1.34.39长字符删除非常流程，1.37.93使用确实比上个版本92好一些了，但还是不流畅。

**Comment by xxoxx** [comment]
刚更新了1.37.93，注意到这个删除还是不流畅，还是卡顿，  还是没有iTerm2流畅， 你可以参考一下iTerm2的效果  @zxdong262

**Comment by zyz954489346** [comment]
> 最新版本修复了 https://github.com/electerm/electerm/releases/tag/v1.37.93

Update to v1.37.96, no more stuck，good 👍🏻 , thx
