### ISSUE TITLE
Stuck in fullscreen

### ISSUE THREAD

**Issue by floweringmind** [electerm/electerm#3186]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.80-linux-amd64.deb

### Platform detail (平台详情)

ZorinOS 17 based on Ubuntu

### What steps will reproduce the bug?(重新问题的详细步骤)

1. Run Electerm
2. Click Unmaximize button in the upper right.
Can't resize the window.

### What should have happened?(期望的结果)

I should have been able to resize the window/

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

no

**Comment by zxdong262** [comment]
Thank you for the feedback, would fix in next release
