### ISSUE TITLE
Popup helpers off screen

### ISSUE THREAD

**Issue by floweringmind** [electerm/electerm#3187]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.80-linux-amd64.deb

### Platform detail (平台详情)

ZorinOS 17 -  6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

Hover the icons in the screenshots:

https://ibb.co/0j6vP2T
https://ibb.co/yQjMxCq

### What should have happened?(期望的结果)

They should have been on the screen. Below you can see what happens at fullscreen.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

no

**Comment by zxdong262** [comment]
Thank you for the feedback, should be fixed in next release
