### ISSUE TITLE
升级后ctrl+c无法复制了

### ISSUE THREAD

**Issue by lgy1027** [electerm/electerm#3192]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.88-win-x64-installer.exe

### Platform detail (平台详情)

Linux master-1 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

升级后ctrl+c无法复制了，设置中也没有相关设置，我忘了之前用的哪个版本是可以的，今天升级后不行了，并且删除很卡

### What should have happened?(期望的结果)

正常复制删除

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
可以复制，只是ctrl+v无法粘贴，可以用ctrl+shift+v粘贴

**Comment by zxdong262** [comment]
可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.37.92
