### ISSUE TITLE
鼠标长按拖动软件 Bug

### ISSUE THREAD

**Issue by barry-chen0901** [electerm/electerm#3196]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.88-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

当在两个显示器（配有不同的分辨率）之间进行来回拖动进行作业，electerm窗口大小会有一些浮动
鼠标长按拖动软件位置时，如果鼠标还是长按状态，但是鼠标指针不指在软件上时，软件还是随着鼠标移动并不能再继续操作了

https://github.com/electerm/electerm/assets/68989626/0ee40536-a42d-46e5-8761-4bccb773b65c

### What should have happened?(期望的结果)

鼠标指针不指在软件上时 就不能移动了

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.37.92

**Comment by barry-chen0901** [comment]
尝试重现问题。验证过已经修复了
