### ISSUE TITLE
误操作，导致字体变得很小，并且很难恢复成正常大小的字体

### ISSUE THREAD

**Issue by qinzhiliang** [electerm/electerm#3197]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

mac容易误操作， 按着Command，滑动触摸板，导致字体变得十分的小，建议加个控制开关，不允许改变字体。谢谢！

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by zxdong262** [comment]
应该是按cmd键加滚轮，可以在快捷键设置里设为其他按键，避免触发

**Comment by qinzhiliang** [comment]
> 应该是按cmd键加滚轮，可以在快捷键设置里设为其他按键，避免触发

好的，谢谢！只能暂时改快捷键了，可能是触摸板不太好调整大小的原因。
