### ISSUE TITLE
长按删除按钮时删除文字的速度不会增加

### ISSUE THREAD

**Issue by Lction** [electerm/electerm#3198]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.88-mac-arm64.dmg

### Platform detail (平台详情)

macos14 M1

### What steps will reproduce the bug?(重新问题的详细步骤)

![20231226164228](https://github.com/electerm/electerm/assets/40019242/55e2a063-5b02-4a69-a32c-b367bfe55490)

### What should have happened?(期望的结果)

删除的速度

**Comment by zxdong262** [comment]
最新版本修复了 https://github.com/electerm/electerm/releases/tag/v1.37.93
