### ISSUE TITLE
整个electerm窗口莫名的被一直选中，鼠标移动就跟着移动

### ISSUE THREAD

**Issue by ffhx1234** [electerm/electerm#3199]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.88-win-x64-installer.exe

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

用着用着莫名的整个窗口都被鼠标选中，光标移动，整个窗口跟着移动，但是我并没有按鼠标左右键

### What should have happened?(期望的结果)

https://github.com/electerm/electerm/assets/10555612/01e3e2d1-0e06-49ea-a8ab-14b79dbb6416

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.37.92

**Comment by zxdong262** [comment]
可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.37.96
