### ISSUE TITLE
使用mac在切换窗口时，会明显卡顿，不知道是系统版本的问题还是什么，之前没升级系统版本，没出现过，升级之后出现切换卡顿

### ISSUE THREAD

**Issue by smile-vi** [electerm/electerm#3200]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

mac

### What steps will reproduce the bug?(重新问题的详细步骤)

触摸板，向上滑动，切换窗口卡顿

### What should have happened?(期望的结果)

看有没有办法优化

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

希望能解决，蛮看好这个

### Additional information(其他任何相关信息)

暂无

**Comment by zxdong262** [comment]
是打开就卡顿还是运行一段时间呢，具体是哪个版本呢
