### ISSUE TITLE
输入Backspace响应很慢，有时甚至没有响应

### ISSUE THREAD

**Issue by kevinhonor** [electerm/electerm#3201]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.37.92

### Platform detail (平台详情)

windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

输入Backspace响应很慢，有时甚至没有想用

### What should have happened?(期望的结果)

输入Backspace快速响应

**Comment by zxdong262** [comment]
最新版本修复了 https://github.com/electerm/electerm/releases/tag/v1.37.93
