### ISSUE TITLE
在终端使用键盘按下Backspace时，终端响应慢甚至有时不响应，导致无法删除

### ISSUE THREAD

**Issue by kevinhonor** [electerm/electerm#3202]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.92-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

想删除最后的字符s，需要键盘按下多次Backspace键
![Snipaste_2023-12-27_10-22-43](https://github.com/electerm/electerm/assets/41811631/049fd8d8-734d-42bd-aac6-3d13d1d9c942)

### What should have happened?(期望的结果)

键盘按下Backspace键时，能快速响应

**Comment by czxin788** [comment]
我也遇到这个问题了，上个版本就很卡，这个版本似乎还没修复，好像比上个版本还卡一些，我干脆回退到10月份版本了，流畅多了

**Comment by Lction** [comment]
macos14 m1 同样的问题

**Comment by ffhx1234** [comment]
同样 win10 ， 我直接用delete键删除

**Comment by barry-chen0901** [comment]
+1 我也遇到这个问题。删除键位有点难使用

**Comment by fu1996** [comment]
我也遇到这个问题了，mac m3 系统

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by haixiaosheng** [comment]
上个版本删除键略卡，这个版本删除键特别卡，win 11系统

**Comment by github-xiaoh** [comment]
是真难受啊，每次删除打错的字母卡的都不想用这个软件了

**Comment by czxin788** [comment]
> 是真难受啊，每次删除打错的字母卡的都不想用这个软件了

多回退几个版本试一下，我已经回退好多个版本前了，速度非常丝滑

**Comment by 429pm** [comment]
Just to add my experience - and if I have duplicated some stuff please forgive me I don't read Chinese at all.

**Comment by zxdong262** [comment]
最新版本修复了 https://github.com/electerm/electerm/releases/tag/v1.37.93
Fixed in latest release  https://github.com/electerm/electerm/releases/tag/v1.37.93
