### ISSUE TITLE
Bookmarks 标签左侧绿点状态不准确

### ISSUE THREAD

**Issue by miaokela** [electerm/electerm#3203]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.92-mac-arm64.dmg

### Platform detail (平台详情)

mac os arm

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="876" alt="image" src="https://github.com/electerm/electerm/assets/30903265/a256ea6a-a791-4ab5-bd61-d97abcaeda76">
Bookmarks 标签左侧绿点表示的是成功连接么？这个状态不对

### What should have happened?(期望的结果)

调整正确状态，名称跟标识是不是隔开一点好一些

**Comment by zxdong262** [comment]
菱形是颜色标签，创建时候可以设定，白色的应该是颜色标签功能之前创建的
![Screen Shot 2023-12-27 at 15 18 11](https://github.com/electerm/electerm/assets/1641949/ff7bb171-7898-4de9-87ca-6651e36f2e57)
