### ISSUE TITLE
1.37.92 输入响应慢，卡顿明显，backspace键按了很多时候无响应

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#3204]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.37.92 electerm-xx.xx.xx-linux-x86_64.rpm

### Platform detail (平台详情)

centos8

### What steps will reproduce the bug?(重新问题的详细步骤)

1.37.92 输入响应慢，卡顿明显，backspace键按了很多时候无响应， 最近两个版本输入卡顿非常明显

### What should have happened?(期望的结果)

希望优化效率

**Comment by zxfskr** [comment]
我也遇到这个情况了，退格键有时候无反应，我用powershell直接试了没事，不是服务器的问题，应该就是Electerm的问题

**Comment by zxdong262** [comment]
1.37.93修复了

**Comment by czxin788** [comment]
我刚试了一下1.37.93，感觉backspace还是有点卡，不流畅。
我退回1.35.0，这个挺流畅
