### ISSUE TITLE
1.37.93 backspace键在交互场景下无法正常删除字符

### ISSUE THREAD

**Issue by xbestwiz** [electerm/electerm#3205]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.93-mac-arm64.dmg

### Platform detail (平台详情)

mac os m1

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="561" alt="image" src="https://github.com/electerm/electerm/assets/29454458/e805668d-eb09-4a04-9aa4-3080e8929c3e">

### What should have happened?(期望的结果)

backspace键在交互场景下正常删除字符

**Comment by zxdong262** [comment]
可以截图看看吗？

**Comment by zxdong262** [comment]
shift+退格键可以吗

**Comment by zxdong262** [comment]
我试了shift+退格键可以，可能会在下个版本加个提示，如果删除不成功，提示使用shift+退格

**Comment by zxdong262** [comment]
将在下个版本彻底解决删除卡顿和拖动窗口问题，恢复为默认的删除模式

**Comment by zxdong262** [comment]
请试试  https://github.com/electerm/electerm/releases/tag/v1.37.96 
希望不要再有需要修的bug了

**Comment by xbestwiz** [comment]
> 请试试 https://github.com/electerm/electerm/releases/tag/v1.37.96 希望不要再有需要修的bug了

验证过了，96版本没出现这个问题了
