### ISSUE TITLE
新版本按退格键响应非常慢

### ISSUE THREAD

**Issue by chengjuny1978** [electerm/electerm#3206]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

新版本按退格键响应非常慢

### Platform detail (平台详情)

新版本按退格键响应非常慢

### What steps will reproduce the bug?(重新问题的详细步骤)

新版本按退格键响应非常慢

### What should have happened?(期望的结果)

新版本按退格键响应非常慢

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

新版本按退格键响应非常慢

### Additional information(其他任何相关信息)

新版本按退格键响应非常慢

**Comment by zxdong262** [comment]
请问是哪个版本，如果不是1.37.93,可以试试1.37.93

**Comment by zhouchitc** [comment]
> ### Electerm Version and download file extension(Electerm版本和下载文件后缀)
> 新版本按退格键响应非常慢
> 
> ### Platform detail (平台详情)
> 新版本按退格键响应非常慢
> 
> ### What steps will reproduce the bug?(重新问题的详细步骤)
> 新版本按退格键响应非常慢
> 
> ### What should have happened?(期望的结果)
> 新版本按退格键响应非常慢
> 
> ### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)
> 新版本按退格键响应非常慢
> 
> ### Additional information(其他任何相关信息)
> 新版本按退格键响应非常慢

老哥，1.37.92确实慢，mac和windows都慢。1.37.93应该是没了

**Comment by zxdong262** [comment]
将在下个版本彻底解决删除卡顿和拖动窗口问题，恢复为默认的删除模式

**Comment by zxdong262** [comment]
请试试  https://github.com/electerm/electerm/releases/tag/v1.37.96 
希望不要再有需要修的bug了
