### ISSUE TITLE
少点花里胡哨的，聚焦基础功能，现在基础操作体验极差

### ISSUE THREAD

**Issue by tonyinsg** [electerm/electerm#3208]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

1. ssh命令操作响应比之前感官慢了1-2秒，经常3-5秒没响应，同时打开了另外的SSH工具对比测试，electerm操作就是乌龟
3. 例如：回退健删除经常按了没反应
4. 例如：输入命令也是经常假死，需要等待
5. 例如：窗口总是莫名其妙的跟随鼠标
6. 例如：复制粘贴命令莫明没粘贴对（这个存疑可能是复制问题）

主要问题：基础操作(SSH)反馈慢，其他都不重要

版本：1.37.92
MAC:  M1 Pro

**Comment by tonyinsg** [comment]
一直使用electerm并给不少同事安利，越用有点小失望，现在动不动就有提示更新...

**Comment by zxdong262** [comment]
感谢反馈，92删除有bug，发布了93修复了，将在下个版本继续优化

**Comment by zxdong262** [comment]
请问在92版本也有窗口总是莫名其妙的跟随鼠标情况吗？

**Comment by tonyinsg** [comment]
之前比较常见，92昨天触发了2次左右，在操作顶部拖动窗口时会偶然触发

**Comment by zxdong262** [comment]
将在下个版本彻底解决删除卡顿和拖动窗口问题

**Comment by zxdong262** [comment]
请试试  https://github.com/electerm/electerm/releases/tag/v1.37.96 
希望不要再有需要修的bug了

**Comment by tonyinsg** [comment]
🤙🤙🤙
1. 简单上手快速体验了一下，比92版本操作响应明显提高
2. 开了5个页签，来回切换，快速输入与删除，目前回显与反应速度可以接受
3. 分屏操作，来回切换，快速输入与删除，目前回显与反应速度可以接受
4. 窗口来回拖动，放大缩小，双击放大，拖动，没有发现鼠标跟随现象

**Comment by zxdong262** [comment]
@tonyinsg 感谢支持！
