### ISSUE TITLE
作为ssh客户端，electerm的功能已经够用了，不要为了增加新功能，影响了基本功能的稳定性，建议出一个lts版本

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3209]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

1.感觉electerm经常在因为上了一些锦上添花(花里胡哨)的功能、特性后， 从而影响的基本功能的使用。
2.目前electerm的基本功能对大部分用户来说，真的已经够用了。
3.建议出一个lts版本，只用维护bug就行了， 不用上什么新功能了，很多时间我们只需要稳定
4.理解开源项目不易
5.希望采纳
6. 也希望广大用户支持

**Comment by barry-chen0901** [comment]
同意，选择electerm 就是因为它界面简结+功能刚好够，我主要还是用SSH + SFTP 
确实最近的更新，越更新越多bug ，哈哈哈哈

**Comment by zxdong262** [comment]
确实，我也想歇两天，总有bug，不停修，修一个，引入一个，熊瞎子掰苞米了属于。
请试试  https://github.com/electerm/electerm/releases/tag/v1.37.96 
希望不要再有需要修的bug了

**Comment by louiejordan** [comment]
是的，更新太频繁了，难绷~
