### ISSUE TITLE
改变文件名称时，有时不能显示下划线_符号，关闭软件，在重新打开时，又能输入下划线_符号了

### ISSUE THREAD

**Issue by kevinhonor** [electerm/electerm#3211]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.96-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

需要把data改名为data_backup,键盘输入时不显示data_backup,只显示data backup，但确实改名成功了
![Snipaste_2023-12-28_19-06-23](https://github.com/electerm/electerm/assets/41811631/49a24c75-9873-4774-ad1b-6260cb7198b3)
![Snipaste_2023-12-28_19-07-25](https://github.com/electerm/electerm/assets/41811631/26c61175-ca44-46b3-878c-9b5eaebcaa04)

### What should have happened?(期望的结果)

输入时，能正常显示下划线_

**Comment by kevinhonor** [comment]
关闭软件，又重新打开，又可以正常显示下划线_符号

**Comment by zxdong262** [comment]
可能跟字体有关，可以试试Fira code之类的字体
