### ISSUE TITLE
快速命令bug（必现）

### ISSUE THREAD

**Issue by ningqingsheng** [electerm/electerm#3213]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.96-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

1. 创建多个快速命令
2. 多次点击列表的最后一个快速命令，会执行错误的指令。例如创建了ABC，多次点击C，但是实际的命令可能是ABC其中的一个。

### What should have happened?(期望的结果)

执行对应的命令

**Comment by zxdong262** [comment]
目前快速命令会根据点击频率排序，是不是点击太快了，顺序已经变了？

**Comment by ningqingsheng** [comment]
抱歉，没注意更新之后是这样设计，之前习惯了这样用。我的
