### ISSUE TITLE
启动后没有UI，任务栏图标鼠标悬浮后有窗口预览界面

### ISSUE THREAD

**Issue by wytitan** [electerm/electerm#3214]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.96-win-x64-installer.exe

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

无

### What should have happened?(期望的结果)

无

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

### Additional information(其他任何相关信息)

无

**Comment by zxdong262** [comment]
可以命令行运行看看什么输出吗

**Comment by wytitan** [comment]
> 可以命令行运行看看什么输出吗

10:34:20 debug 鈥?electerm start
10:34:22 info 鈥?database version: 1.37.96
10:34:23 info 鈥?server runs on 127.0.0.1 30975
10:34:23 debug 鈥?error parsing $HOME/.ssh/config
10:34:23 debug 鈥?maybe no $HOME/.ssh/config, it is ok
10:34:24 debug 鈥?command line params {
  options: {},
  argv: [],
  helpInfo: 'Usage: electerm [options] sshServer\n' +
    '\n' +
    '\n' +
    '### Connect ssh server from command line examples:\n' +
    '- electerm user@xx.com\n' +
    '- electerm user@xx.com:22\n' +
    '- electerm --password password --set-env "SECRET=xxx USER=hhhh" user@xx.com:22\n' +
    '- electerm -l user -P 22 -i /path/to/private-key -pw password xx.com -T -t "XX\n' +
    'Server"\n' +
    '\n' +
    '### Other params examples:\n' +
    '\n' +
    '- server port:\n' +
    'electerm -sp 30976\n' +
    '\n' +
    '- load and run batch operation from csv file:\n' +
    'electerm -bo "/home/root/works.csv"\n' +
    '\n' +
    '\n' +
    'Options:\n' +
    '  -V, --version                    output the version number\n' +
    '  -t, --title [Tab Name]           Specify the title of the new tab\n' +
    '  -nw, --new-window                Open this connection using standalone window\n' +
    '  -l, --user <user>                specify a login name\n' +
    '  -P, --port <port>                specify ssh port\n' +
    '  -bo, --batch-op <batchOpFile>    load and run batch operation from csv file\n' +
    '  -sp, --server-port <serverPort>  specify server port, default is\n' +
    '  -i, --private-key-path <path>    specify an SSH private key path\n' +
    '  -ps, --passphrase <passphrase>   specify an SSH private key passphrase\n' +
    '  -pw, --password <password>       specify ssh server password\n' +
    '  -pw, --set-env <setEnv>          specify envs\n' +
    '  -so, --sftp-only                 only show sftp panel\n' +
    '  -h, --help                       display help for command\n'
}
10:34:24 debug 鈥?command line opts {
  type: 'remote',
  status: 'processing',
  id: 'wb3xGsL',
  encode: 'utf-8',
  envLang: 'en_US.UTF-8',
  enableSsh: true,
  authType: 'password',
  pane: 'terminal',
  term: 'xterm-256color'
}
10:34:25 debug 鈥?ws: connected to terminal -> s2mcLfD

然后就没UI出来了

**Comment by zxdong262** [comment]
可以到C:\Users\你的用户名\AppData\Roaming\electerm，删除除了users文件夹以外的所有文件夹吗，然后再启动看看

**Comment by wytitan** [comment]
> 可以到C:\Users\你的用户名\AppData\Roaming\electerm，删除除了users文件夹以外的所有文件夹吗，然后再启动看看

一样的，还是没有UI

**Comment by zxdong262** [comment]
把C:\Users\你的用户名\AppData\Roaming\electerm\users备份一下，也删除试试？

**Comment by wytitan** [comment]
> 把C:\Users\你的用户名\AppData\Roaming\electerm\users备份一下，也删除试试？

这个可以了，不知道是哪段配置导致的

**Comment by zxdong262** [comment]
可以把备份的users/default_users/electerm.data.nedb，users/default_users/electerm.lastStates.nedb删除之后恢复回去覆盖同名文件，如果有旧的书签等数据需要恢复

**Comment by wytitan** [comment]
已恢复正常，感谢大神
