### ISSUE TITLE
命令行窗口总宽度问题

### ISSUE THREAD

**Issue by miaokela** [electerm/electerm#3217]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.96-mac-arm64.dmg

### Platform detail (平台详情)

macos arm

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="817" alt="image" src="https://github.com/electerm/electerm/assets/30903265/cf283489-35ec-409c-b93d-0783b354aeca">
<img width="892" alt="image" src="https://github.com/electerm/electerm/assets/30903265/84e3842c-948b-4555-a8a9-7668432e8507">

### What should have happened?(期望的结果)

调整宽度

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
请问有缩放和字体设置吗？

**Comment by miaokela** [comment]
我测试了，不管字体设置多大，怎么缩放，还是被遮挡了一部分

**Comment by miaokela** [comment]
windows上没有问题 我用的是macos

**Comment by zxdong262** [comment]
请问设置了什么字体吗，终端设置里？

**Comment by miaokela** [comment]
<img width="441" alt="image" src="https://github.com/electerm/electerm/assets/30903265/84726dc3-4ad1-4d00-9ec7-e912d31a15aa">

**Comment by zxdong262** [comment]
可以重置为默认试试吗，我猜测可能是因为只有等宽字体才能正确计算换行

**Comment by miaokela** [comment]
![Uploading image.png…]()
![Uploading image.png…]()还是一样的，我怀疑是macos的分辨率问题，我默认的分辨率是1470*956

**Comment by miaokela** [comment]
<img width="724" alt="image" src="https://github.com/electerm/electerm/assets/30903265/a4ab6631-b722-4ecc-85de-d93939b2e302">
<img width="607" alt="image" src="https://github.com/electerm/electerm/assets/30903265/546d6470-c97f-4a02-a4d0-323d3b5f56c2">

**Comment by zxdong262** [comment]
有其他分辨率可以试试吗？

**Comment by miaokela** [comment]
其他分辨率也不行。v1.37.58 这个版本开始的，是不是之前修改bookmarks的时候调整了宽度把命令行的挤过去了

**Comment by zxdong262** [comment]
> 其他分辨率也不行。v1.37.58 这个版本开始的，是不是之前修改bookmarks的时候调整了宽度把命令行的挤过去了

我知道了，是固定左侧书签栏时候宽度不对
