### ISSUE TITLE
Ctrl+r失效，版本1.37.96，win10，在终端，vim，快捷键设置中，均无法输入Ctrl+r

### ISSUE THREAD

**Issue by dooway** [electerm/electerm#3218]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.96-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19045.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

Ctrl+r失效，版本1.37.96，win10
在终端，vim，快捷键设置中，均无法输入Ctrl+r

### What should have happened?(期望的结果)

终端和vim正常输入Ctrl+r

**Comment by zxdong262** [comment]
将在下个版本修复，感谢反馈
