### ISSUE TITLE
Customize interface font support / 界面字体自定义支持

### ISSUE THREAD

**Issue by liumingedwin** [electerm/electerm#3220]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Hello! I have already changed my `GNOME` font by `gnome-tweaks` and customize my `electerm` terminal with `"Source Code Pro"`. However, the `electerm` interface font is isolated with the system. Could I change the font of `electerm` interface? Thanks.    
我认为使界面字体易于更改很必要，是否能更进？ 谢谢！

**Comment by zxdong262** [comment]
Could try the custom css in setting page add something like 可以试试设置里的自定义css:

```css
body {
  font-family: Fira Code;
}
```

**Comment by liumingedwin** [comment]
谢谢！
