### ISSUE TITLE
突然只在状态栏显示，桌面看不到

### ISSUE THREAD

**Issue by HankeXia** [electerm/electerm#3222]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.106-win-x64-installer.exe

### Platform detail (平台详情)

win11 22H2

### What steps will reproduce the bug?(重新问题的详细步骤)

一直在状态栏 点击桌面不显示

### What should have happened?(期望的结果)

桌面显示

**Comment by zxdong262** [comment]
试试删除 C:\Users\你的用户名\AppData\Roaming\electerm\users\eleterm.data.nedb 和 C:\Users\你的用户名\AppData\Roaming\electerm\users\eleterm.lastStates.nedb 然后启动electerm

**Comment by zxdong262** [comment]
请问升级之前是哪个版本呢

**Comment by zxdong262** [comment]
将在下个版本修复，感谢反馈

**Comment by HankeXia** [comment]
升级之前那个版本记不清了。。自动升级的 没注意。。昨天用的时候一直不显示，以为电脑问题。。重启好几次

**Comment by zrh-0523** [comment]
我这儿也有同样的情况

**Comment by zxdong262** [comment]
可以试试删除 C:\Users\你的用户名\AppData\Roaming\electerm\users\eleterm.data.nedb 和 C:\Users\你的用户名\AppData\Roaming\electerm\users\eleterm.lastStates.nedb 然后启动electerm

**Comment by zxdong262** [comment]
可以试试最新版吗 https://electerm.html5beta.com/ cdn链接应该快一些

**Comment by zrh-0523** [comment]
> 可以尝试删除 C:\Users\你的用户名\AppData\Roaming\electterm\users\eleterm.data.nedb 和 C:\Users\你的用户名\AppData\Roaming\electterm\users\eleterm.lastStates。 nedb 然后启动 electterm

按照这个方法显示恢复了，感谢感谢

**Comment by HankeXia** [comment]
我试试新版本 我先不删除文件

**Comment by HankeXia** [comment]
新版本可以了
