### ISSUE TITLE
sftp右边地址栏看不全，看不到刷新

### ISSUE THREAD

**Issue by LiFuHai1106** [electerm/electerm#3223]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.106-mac-arm64.dmg

### Platform detail (平台详情)

mac m1

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/57932634/9ad6b92f-cbe0-456a-95e0-71db5f13c99c)

### What should have happened?(期望的结果)

看得到刷新

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本改进

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/2cb44c2d053304833720c782c81b3e3498ac5632

**Comment by zxdong262** [comment]
发布了新版修复了这个问题 https://electerm.html5beta.com/
