### ISSUE TITLE
sftp界面显示不完整

### ISSUE THREAD

**Issue by liutexing** [electerm/electerm#3224]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.106-win-x64-installer.exe

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

sftp界面显示不完整，右边被截断，无论全屏大小或非全屏大小都有一样的问题，如图所示
![问题](https://github.com/electerm/electerm/assets/13727849/f8c263b8-5529-48f1-aa3e-a0835ae1b29b)

### What should have happened?(期望的结果)

正常完整显示内容。还有就是sftp页面左右窗口（本地/远程）大小不能拖动调整大小吗？希望可以拖动调整左右窗口大小，谢谢！

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
