### ISSUE TITLE
哎，心累了，在有两个显示器的情况下，不能把electerm拖动到另一个显示器

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#3230]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.110-mac-x64.dmg

### Platform detail (平台详情)

mac x64

### What steps will reproduce the bug?(重新问题的详细步骤)

在有两个显示器的情况下，不能把electerm拖动到另一个显示器

就算不拖动到另一个显示器，在当前显示器用鼠标拖动作窗口也能明显感到卡顿

### What should have happened?(期望的结果)

流畅的拖动

**Comment by xxoxx** [comment]
![z10](https://github.com/electerm/electerm/assets/8625218/bcff0e02-b889-4ede-b479-8f8c29227be9)

**Comment by xxoxx** [comment]
现在electerm的品控越来越低了， 越用越心累， 我都给我的朋友安利了那么多出去了。。   现在不讲功能， 整体稳定性、流畅程度electerm比tabby差了好多了哦，   electerm是个好产品， 但是目前新特性上缓一缓，  把现有的功能打磨精了来。  还有就是目前electerm缺少一个好的测试。 好多功能都没有经过充分的测试就直接上线。  我也理解作为开源项目的不容易

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by xxoxx** [comment]
这个bug从我这来看已经持续了好几个版本了。

**Comment by xxoxx** [comment]
只要electerm一出新版本，我都是第一时间升级。  也真心希望electerm做得更好。

**Comment by zxdong262** [comment]
> 现在electerm的品控越来越低了， 越用越心累， 我都给我的朋友安利了那么多出去了。。 现在不讲功能， 整体稳定性、流畅程度electerm比tabby差了好多了哦， electerm是个好产品， 但是目前新特性上缓一缓， 把现有的功能打磨精了来。 还有就是目前electerm缺少一个好的测试。 好多功能都没有经过充分的测试就直接上线。 我也理解作为开源项目的不容易

确实问题很多，最近只修bug，不会加入新的功能，感谢支持~

**Comment by zxdong262** [comment]
请问拖到最右侧时候，第二个显示器不显示electerm吗

**Comment by zxdong262** [comment]
哦我知道了，跨越两个屏幕时候就会停止

**Comment by xxoxx** [comment]
是的， 拖不动啊。   其它软件都不会出现这个问题。

**Comment by xxoxx** [comment]
已经修复
