### ISSUE TITLE
sftp远端地址报127错误，解决不了

### ISSUE THREAD

**Issue by gszhaochengyong** [electerm/electerm#3231]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.25.50和1.37.110都一样。exe安装包

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

在FTP传输文件时，误操作了鼠标拖动文件，然后卡死了。
重启后无论如何，都会报如下错误 ，关掉重开没用，重启软件 没用，重启电脑没用，卸载重装也没用，装其他版本也没用。
Received exit code 127 while establishing SFTP session
Error: Received exit code 127 while establishing SFTP session at http://127.0.0.1:30974/js/electerm-1.37.110.js:144:15903 at Object.resolve (http://127.0.0.1:30974/js/electerm-1.37.110.js:69:5320) at Worker.F0 (http://127.0.0.1:30974/js/electerm-1.37.110.js:69:6214)

### What should have happened?(期望的结果)

可以正常使用SFTP功能 

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

无

### Additional information(其他任何相关信息)

无

**Comment by zxdong262** [comment]
可以试试删除C:\Users\your-user-name\AppData\Roaming\electerm，删除之前先备份C:\Users\your-user-name\AppData\Roaming\electerm\users,可以恢复回去书签设置等数据

**Comment by zxdong262** [comment]
另外可以试试其他sftp软件对比一下，是不是服务器有什么变化

**Comment by gszhaochengyong** [comment]
> 可以试试删除C:\Users\your-user-name\AppData\Roaming\electerm，删除之前先备份C:\Users\your-user-name\AppData\Roaming\electerm\users,可以恢复回去书签设置等数据

删除了重新进入还是有这个错误提示。想不到什么办法可以解决这个问题了。所以只能求救了。

**Comment by gszhaochengyong** [comment]
![SFTP报错](https://github.com/electerm/electerm/assets/32763397/d4c222aa-aaab-4724-8886-23ead346e6e9)

**Comment by gszhaochengyong** [comment]
关闭问题，原来 是IT突然在服务器上关闭了winSCP操作。
