### ISSUE TITLE
Upload folders and files within them at the same time in Sftp

### ISSUE THREAD

**Issue by TomoyaKuroda** [electerm/electerm#3232]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

I wonder if it's possible to upload folders and files within them in Sftp.
When I drag and drop folders in Sftp, it just upload folders but they don't have any files like empty folder.

**Comment by zxdong262** [comment]
Thank for the feedback, it do works this way, pack the whole folder and upload then unpack it, do get report that sometimes some files missing, can not reproduce the situation yet, still need investigation.

**Comment by zxdong262** [comment]
Can you provide electerm version and OS ?

**Comment by TomoyaKuroda** [comment]
@zxdong262 Sure. 
Version: 1.37.110
OS: Windows 11
It fails even if there is one 1kb file in a folder. It's CPanel server and dropping a folder (e.g. images) into /home/username/public_html/abc doesn't succeed while it just upload the empty folder without files.

**Comment by zxdong262** [comment]
Can you run this cmd in your server, just to check if tar cmd works as expected

```sh
mkdir xxx && cd xxx && for i in {1..5}; do dd if=/dev/zero of=file$i bs=1024 count=1; done && cd .. && tar -cf xxx.tar xxx && rm -rf xxx && tar -xf xxx.tar
```

then check if there is a xxx folder with 5 1k files in it

**Comment by TomoyaKuroda** [comment]
@zxdong262 
The command works fine and it creates 5 files.

**Comment by zxdong262** [comment]
I think I know it, you drag from OS file manager, right? that is bug for sure! Would fix in next release. 

Drag file from electerm built-in manager would be fine.

**Comment by TomoyaKuroda** [comment]
Yeah, I drag folders from Windows file manager.
I'm looking forward to the next release. And thank you for your amazing work!

**Comment by zxdong262** [comment]
1.37.121 should fixed the issue

**Comment by TomoyaKuroda** [comment]
Thanks a lot!
