### ISSUE TITLE
1.37.101 比上版本反应明显慢了，是否有效率问题？

### ISSUE THREAD

**Issue by sguphil** [electerm/electerm#3233]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.37.101  electerm-xx.xx.xx-linux-x86_64.rpm

### Platform detail (平台详情)

centos8

### What steps will reproduce the bug?(重新问题的详细步骤)

较上一版本，敲ls命令明显卡顿，输入字符显示也感觉有反应迟钝，不知道十分有什么变动影响效率？

### What should have happened?(期望的结果)

希望效率优先，反应要快

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

N/A

### Additional information(其他任何相关信息)

N/A

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/compare/v1.37.106...v1.37.110 不涉及性能方面 我试了没有变化，是不是和服务器的网络波动？
可以在同时对比下看看吗？

**Comment by sguphil** [comment]
let me check again. thanks
