### ISSUE TITLE
下载文件列表许多时，列表没有反应了

### ISSUE THREAD

**Issue by lizhuangs** [electerm/electerm#3236]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.110-linux-amd64.deb

### Platform detail (平台详情)

deepin 

### What steps will reproduce the bug?(重新问题的详细步骤)

![43399954-DC92-42b1-844C-22A64689EDA5](https://github.com/electerm/electerm/assets/7904121/4853e80c-88ef-4ad4-96f7-12b768d3fd8b)
如图所有，没有反应了。这个问题几年前就存在了。。今天更新到最新看了下，还是存在。。

### What should have happened?(期望的结果)

希望可以正常下载

**Comment by zxdong262** [comment]
请问具体情况，多个文件夹吗，大小多少呢

**Comment by lizhuangs** [comment]
没具体数过，文件有上千个，大小在30多G。而且只要出现这个错之后，我再下载其它的文件夹也不行了。

**Comment by zxdong262** [comment]
文件夹会打包后上传再解压，对于过大的文件夹预期会卡主住，有待优化

**Comment by lizhuangs** [comment]
我这个是下载，下载也会打包么？建议直接下载呀，异步进行。如果一定要打包的话，判断一下，如果文件超过指定大小或数量，就不要打包了。

**Comment by lizhuangs** [comment]
简单易用就行，不要整太复杂的，容易出问题。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化

**Comment by lizhuangs** [comment]
我是19年那会就开始用了，直到今天我的同事给我推荐，我升级到最新发现这个问题还在，/笑哭

**Comment by zxdong262** [comment]
> 我是19年那会就开始用了，直到今天我的同事给我推荐，我升级到最新发现这个问题还在，/笑哭

我一般不会测试这么大的文件夹，我怕发现问题😂

**Comment by lizhuangs** [comment]
感谢，上次更新后测试感觉好多了。
