### ISSUE TITLE
SFTP选中多个文件下载时会出现进度重叠 文件损坏的情况

### ISSUE THREAD

**Issue by Seraphli** [electerm/electerm#3237]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.37.20

### Platform detail (平台详情)

Manjaro Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

选中多个文件同时拖拽到本地. 刚开始会显示多个进度条, 当结束几个之后, 进度条上的数字就开始在几个进度里跳. 当显示所有的下载都完成的时候, 检查文件其中有几个是损坏的. 下载的是6+个压缩包, 所以解压的时候一下子就发现损坏了. 每个文件大小大概400MB左右.

### What should have happened?(期望的结果)

正常下载

### Additional information(其他任何相关信息)

一个个单独下载没有问题, 所以不会是文件问题. 另外这个情况碰到过好多次.

**Comment by zxdong262** [comment]
可以试试最新版吗，这样方便依据最新版来定位问题

**Comment by Seraphli** [comment]
目前AUR上最新的版本是1.37.106，我需要更新到哪个版本比较合适？
https://aur.archlinux.org/packages/electerm-bin

**Comment by zxdong262** [comment]
可以试试刚发布的37.121 https://electerm.html5beta.com/

**Comment by Seraphli** [comment]
1.37.121 进度跳变的问题依旧存在，同时拖拽下载6个文件，剩最后一个的时候，进度一直在跳变
这次测试暂时没碰到文件损坏

**Comment by Seraphli** [comment]
1.37.121仍有文件损坏的情况, 这次同时下载的是4个文件, 其中有两个压缩包是损坏的. 这个是由于进度条不显示了, 其实还是在下载导致的. 我看到软件里没有显示进度了, 于是就认为是下载完成了, 但是解压缩的时候发现损坏了. 而我等了一会儿再去解压的时候, 文件又正常了. 说明应该是后端下载完成了, 但是前端可能判断已完成所以没显示进度.

**Comment by etanman** [comment]
这个问题不知道解决了没，这是的确是一个容忽视的问题。

**Comment by Seraphli** [comment]
我还没测试新版本, 这几天测试一下. 之前我是使用电脑的网络下载速度监控来判断是否下载完成的

**Comment by Seraphli** [comment]
测试了1.38.11还存在这个问题

**Comment by Seraphli** [comment]
https://github.com/electerm/electerm/assets/1586755/f38ef8d5-ea58-47fc-aaa1-78ec3e91d3a8

一个视频来阐述这个情况
1. 进度百分比跳变
2. 显示完成但是右下角网络流量仍然很高

**Comment by Seraphli** [comment]
另外发现，如果一个session已经在下载，此时再从另一个session同时下载文件，比如一个已经下载到只剩4个下载任务，另一个刚开始下载10个内容，导致下载列表图标上的数字一直在4和14之间跳变。

**Comment by zxdong262** [comment]
最新版已修复
