### ISSUE TITLE
macos 系统添加书签内文件夹时，中文无法录入

### ISSUE THREAD

**Issue by cherl** [electerm/electerm#3242]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

mac os(ARM)

### What steps will reproduce the bug?(重新问题的详细步骤)

书签功能添加二级文件夹时中文无法输入进去，自动变成打的拼音。
![image](https://github.com/electerm/electerm/assets/13915638/24cf4e54-875e-4110-8a03-db30324ca34b)

### What should have happened?(期望的结果)

可以正常输入中文。

**Comment by cherl** [comment]
截图内2级中文文件夹是在vscode中先录入复制进去添加成功的。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by cherl** [comment]
已修复，感谢开发大佬。
