### ISSUE TITLE
sftp无法拖拽上传文件，mac 1.37.121版本

### ISSUE THREAD

**Issue by Loading828** [electerm/electerm#3245]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

mac 1.37.121版本

### Platform detail (平台详情)

sftp无法拖拽上传文件，mac 1.37.121版本

### What steps will reproduce the bug?(重新问题的详细步骤)

sftp无法拖拽上传文件，mac 1.37.121版本

### What should have happened?(期望的结果)

支持拖拽上传文件

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

sftp无法拖拽上传文件，mac 1.37.121版本

### Additional information(其他任何相关信息)

sftp无法拖拽上传文件，mac 1.37.121版本

**Comment by zxdong262** [comment]
我试了可以啊，请问从哪里拖拽，可以截图看看怎么操作吗

**Comment by Loading828** [comment]
嗯嗯，好 直接拖拽到服务器这个目录，没有效果的，能帮忙看下吗，这个工具用习惯了。还挺方便的。现在没办法直接把文件拖拽上传有点难受







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHAO ***@***.***&gt;; 
发送时间: 2024年1月9日(星期二) 下午3:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [electerm/electerm] sftp无法拖拽上传文件，mac 1.37.121版本 (Issue #3245)





 
我试了可以啊，请问从哪里拖拽，可以截图看看怎么操作吗

**Comment by zxdong262** [comment]
邮件发的回复看不到图片的

**Comment by Loading828** [comment]
嗯嗯，好吧。就是现在切到sftp 是不支持把本地的文件，直接拖拽到服务上了吗？ 目前我把本地文件，拖拽后，没有任何效果的。也没和以前一样看到上传进度的。有微信号吗？可以加一下微信的。。。

**Comment by zxdong262** [comment]
> 嗯嗯，好吧。就是现在切到sftp 是不支持把本地的文件，直接拖拽到服务上了吗？ 目前我把本地文件，拖拽后，没有任何效果的。也没和以前一样看到上传进度的。有微信号吗？可以加一下微信的。。。

哦，确实不行，我用文件夹验证的可以，文件不可以，将在下个版本修复，感谢反馈

**Comment by Loading828** [comment]
嗯嗯，好的，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHAO ***@***.***&gt;; 
发送时间: 2024年1月12日(星期五) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [electerm/electerm] sftp无法拖拽上传文件，mac 1.37.121版本 (Issue #3245)





  
嗯嗯，好吧。就是现在切到sftp 是不支持把本地的文件，直接拖拽到服务上了吗？ 目前我把本地文件，拖拽后，没有任何效果的。也没和以前一样看到上传进度的。有微信号吗？可以加一下微信的。。。
  
哦，确实不行，我用文件夹验证的可以，文件不可以，将在下个版本修复，感谢反馈
