### ISSUE TITLE
快速连接的弹窗宽度变窄，看不全内容，希望可以改回以前的宽度或者可自定义宽度

### ISSUE THREAD

**Issue by Lction** [electerm/electerm#3249]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)
我回退到以前的版本，发现这里应该是自适应最长的那一个，很不错，希望能像以前那样，多谢！
<img width="343" alt="image" src="https://github.com/electerm/electerm/assets/40019242/b4d6b9e4-e874-4e64-abca-0fc921580fd8">

**Comment by zxdong262** [comment]
可以拖拽调整这里的宽度，然后下拉菜单宽度也会随之改变
![Screen Shot 2024-01-12 at 17 14 31](https://github.com/electerm/electerm/assets/1641949/a7aa8591-e5eb-46cc-8fc8-c293500c88d6)

**Comment by Lction** [comment]
嗯嗯确实可以，只不过拖拽那里比较难触发，需要先保持书签面板打开，然后再调节。非常感谢回复！

**Comment by zxdong262** [comment]
> 嗯嗯确实可以，只不过拖拽那里比较难触发，需要先保持书签面板打开，然后再调节。非常感谢回复！

点击那个别针按钮即可固定在左侧，这样就可以方便拖拽了
