### ISSUE TITLE
linux系统上无法将窗口拖到状态栏下

### ISSUE THREAD

**Issue by lfxx** [electerm/electerm#3250]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.126-linux-amd64.deb

### Platform detail (平台详情)

5.15.0-71-generic #78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

鼠标拖动界面往状态栏下时，无法实现

### What should have happened?(期望的结果)

![20240112-191016](https://github.com/electerm/electerm/assets/27956643/8ae97fa4-39cb-49c3-8217-3571b07b964d)
如图所示

**Comment by zxdong262** [comment]
暂时的解决方案是设置里使用系统标题栏

**Comment by lfxx** [comment]
> 暂时的解决方案是设置里使用系统标题栏

好的，感谢！
