### ISSUE TITLE
增加快捷键

### ISSUE THREAD

**Issue by leoliuxd** [electerm/electerm#3254]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)
![WechatIMG629](https://github.com/electerm/electerm/assets/4088477/201fc6f0-cf9b-4e6d-bd54-d256b5804694)

希望能够增加快捷键操作。尤其是当前窗口刷新重连。

**Comment by sguphil** [comment]
@zxdong262 能不能提供修改调ctrl+a全选这个快捷键？ 这个和终端的ctrl+a回到行首冲突了，也无法修改
