### ISSUE TITLE
不使用系统标题栏 的时候，点击 书签 等功能 会遮挡顶部标题栏导致无法移动窗口。

### ISSUE THREAD

**Issue by iseeyou** [electerm/electerm#3256]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-v1.37.126-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

其他功能也会遮挡顶部导致不可移动。

### What should have happened?(期望的结果)

任何功能里面都可以点击标题栏移动窗口

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本优化
