### ISSUE TITLE
A config about ctrl-A

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#3267]
@zxdong262 能不能提供修改调ctrl+a全选这个快捷键？ 这个和终端的ctrl+a回到行首冲突了，也无法修改

_Originally posted by @sguphil in https://github.com/electerm/electerm/issues/3254#issuecomment-1909248769_

**Comment by zxdong262** [comment]
请问什么操作系统，默认终端的行为是不是一致的？

**Comment by sguphil** [comment]
centos8, 系统默认终端ctrl+a是返回行首

**Comment by sguphil** [comment]
![2024-01-30_101948](https://github.com/electerm/electerm/assets/8896611/7ba6d6c6-99d4-408a-9ba0-e17da47ff8e6)
默认终端全选是这个快捷键 不会和ctrl+a冲突

**Comment by zxdong262** [comment]
已经在最新版解决
