### ISSUE TITLE
希望终端的tab标签卡可以顶屏幕天花板显示

### ISSUE THREAD

**Issue by PaTTeeL** [electerm/electerm#3271]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

现在electerm每个终端tab对应的标签卡比较小，有时候鼠标移到屏幕顶端会点空：
![image](https://github.com/electerm/electerm/assets/9150277/84320073-7467-4ab6-bfe8-c78d2f5d59cc)

希望主界面上每个终端tab对应的标签卡可以跟Edge的网页标签卡一样顶着天花板显示，即鼠标移到屏幕顶端最上面的位置点击也能选择到标签卡（现在是拖拽模式T_T，详见上一条issue）并切换到对应的终端tab，如下图：
<img width="225" alt="image" src="https://github.com/electerm/electerm/assets/9150277/008d8b38-3dfd-4315-bff4-12b4584d4fcb">

**Comment by zxdong262** [comment]
最新版到顶了(1.38+)

**Comment by PaTTeeL** [comment]
> 最新版到顶了(1.38+)

感谢更新，静候微软商店的推送！

**Comment by PaTTeeL** [comment]
商店升级到1.38.8了，感觉上应该是可以顶格点击了，但因为#3270 的原因，所以鼠标挪到屏幕顶端显示的是拖动按钮，按下去就变成resize了，所以是不是得等窗口最大化后边框不可选择时才能顶格点到选项卡？
