### ISSUE TITLE
tab的标签卡可以支持鼠标滚轮或自动缩放

### ISSUE THREAD

**Issue by PaTTeeL** [electerm/electerm#3272]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

标签卡撑满屏幕横向像素后会出现滚动按钮：
<img width="241" alt="image" src="https://github.com/electerm/electerm/assets/9150277/32f461f1-3e28-4af9-9d61-e882b43b2b8d">
这时候点击左右两个方向按钮是可以进行横向滚动的，但使用鼠标滚轮没反应，希望可以加入鼠标滚轮的支持

或者跟Edge一样使用自动缩放来避免出现滚动现象
![image](https://github.com/electerm/electerm/assets/9150277/e2c86b0b-36ad-4d81-9b0f-3d529a3a30be)

这样鼠标切换tab会顺手一些

**Comment by etanman** [comment]
我倒是希望通过滚轮来切换标签卡

**Comment by zxdong262** [comment]
@etanman @PaTTeeL 感谢反馈，将在下个版本支持滚轮滚动横向滚动
