### ISSUE TITLE
为什么总是报这个错误？

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3274]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.8-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

![1706576359652](https://github.com/electerm/electerm/assets/45775943/bf550eb4-579d-42ed-b356-26c980302aae)

### What should have happened?(期望的结果)

好像要连接127.0.0.1本地服务器，什么情况呢？

**Comment by etanman** [comment]
![1706576832630](https://github.com/electerm/electerm/assets/45775943/cc3b4828-4b51-4c06-a8df-9ac458008496)

**Comment by zxdong262** [comment]
electerm资源文件是通过启动一个本地服务器提供的 你可以通过访问http://127.0.0.1:30974/文件路径  来查看

**Comment by zxdong262** [comment]
提示只是表明在js文件触发的位置，不是说访问这个js文件导致的错误
