### ISSUE TITLE
请问后期有可能加入语法高亮显示吗？

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3275]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

就像mobaxterm那样，支持各种交换机路由器等设备的语法高亮显示

**Comment by zxdong262** [comment]
已经加入，参考https://github.com/electerm/electerm/wiki/Terminal-keywords-highlight-regular-expression-exmaples

**Comment by etanman** [comment]
请问这个功能如何启用，我测试最新版本还是没有高亮功能，如图，最下面是mobaxterm的高亮效果：
![image](https://github.com/electerm/electerm/assets/45775943/a9faeee6-1685-4bd0-8ee6-ee1cee31fd5a)
![1707994672067](https://github.com/electerm/electerm/assets/45775943/1c20fc20-dbe1-4ef5-9eef-754590840cc4)

**Comment by etanman** [comment]
原来需要自定义呀，我试一了IP的高亮，的确可以了，但也把子掩码255.255.255.0也同时高亮了，这不是我想要的，不知道语法上应该怎么写才能只高亮IPv4地址。
