### ISSUE TITLE
sz下载文件后，再输入命令，输出结果中如果有中文就变成乱码了

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#3277]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

windows 11 1.38.8

### Platform detail (平台详情)

windows 11 

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/13861904/dc8622f3-809e-4b4f-8a55-8b54ccb1e4e7)

### What should have happened?(期望的结果)

期望不要出现乱码

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
