### ISSUE TITLE
文案提示有误

### ISSUE THREAD

**Issue by hanbing5210** [electerm/electerm#3280]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.106-win-x64-installer.exe

### Platform detail (平台详情)

Win11 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/32626294/f2679839-3330-4d30-a8ca-ec59292a0e0d)
这个地方和上面一个重复了  缩写的参数名也应该是独立的

### What should have happened?(期望的结果)

所有参数名的全称和缩写保持一致

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

目前没有和本软件有相似功能的

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by hanbing5210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
