### ISSUE TITLE
关键词高亮设置的颜色与终端实际的颜色不一致

### ISSUE THREAD

**Issue by NB611** [electerm/electerm#3282]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.11-win-x64-installer.exe

### Platform detail (平台详情)

win11 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/20264874/712d1404-a2a0-4034-a859-c312fedbdbc8)
![image](https://github.com/electerm/electerm/assets/20264874/adc74600-6573-4154-b544-3c0ec5b3b978)

### What should have happened?(期望的结果)

关键词高亮设置的颜色与终端实际的颜色可以一致

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
