### ISSUE TITLE
单独的sftp功能

### ISSUE THREAD

**Issue by simon-fu** [electerm/electerm#3284]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

有些服务器只开放了sftp功能（当ftp用），禁用了ssh功能。这种场景下，electerm不能连接到sftp。
希望本产品能支持这种场景，谢谢。

**Comment by etanman** [comment]
这是确是个问题，另外，有时想让终端和sftp界面同时显示，也不知道如何实现，某操作会不得不来回切换，非常不方便。

**Comment by zxdong262** [comment]
新建书签的设置栏里有个ssh，关闭应该就可以了，可以试试吗

**Comment by zjhdota** [comment]
我也遇到了这个问题，关闭了SSH也不行，服务器只开放了SFTP，右边永远加载不出来，也不出报错。
![image](https://github.com/electerm/electerm/assets/19267610/636c9b2c-d40b-47f6-92dc-e9f2a2039d2c)


> 新建书签的设置栏里有个ssh，关闭应该就可以了，可以试试吗
