### ISSUE TITLE
建议无需新建书签

### ISSUE THREAD

**Issue by murongxu** [electerm/electerm#3285]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

OS：Windows10

我尝试使用1.38.11时发现必须要新建书签后才能通过书签访问到远程linux环境
而且在点击【+打开新连接】时，默认打开Windows的CMD.
建议可以在悬停【+】出来的浮动框中，增加直接访问远程连接的选项

以上

**Comment by zxdong262** [comment]
新建书签里可以直接点击“连接”按钮就是直接连接不保存书签

**Comment by murongxu** [comment]
感谢您的协助
抱歉回复晚了

我早上尝试了一下，当我点击新建链接时，默认打开了Windows平台的CMD窗口。
我希望能够在新连接时，可以通过输入ip或者域名以达到直接访问远程Linux机器的目的。

还请您继续协助我
以上
