### ISSUE TITLE
新建连接时如何不保存用户名，在连接时提示输入用户名。

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3286]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

因为我不想保存用户名，这样连接时又不会提示输入用户名，造成困难。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入

**Comment by etanman** [comment]
> 感谢反馈，将在下个版本加入

新版本ssh已经完美解决了这个问题，但是telnet还是有严重的问题，请作者再检查一下。
