### ISSUE TITLE
新增窗口排序混乱

### ISSUE THREAD

**Issue by mvpyangxu** [electerm/electerm#3288]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-mac-arm64.dmg

### Platform detail (平台详情)

macOS  ARM

### What steps will reproduce the bug?(重新问题的详细步骤)

连续新增窗口，关闭其中一个，再新增。
![CleanShot 2024-02-18 at 16 54 36](https://github.com/electerm/electerm/assets/54459610/1a779056-5950-42a2-8143-034c3da88c04)

### What should have happened?(期望的结果)

序号按顺序显示

**Comment by mvpyangxu** [comment]
首先还是感谢作者辛苦努力的付出，其实这个问题并不影响实际使用，只是看着有些奇怪，希望可以修复一下，再次感谢。

**Comment by zxdong262** [comment]
考虑保持序号和标签的关联，因此决定序号不会因为标签数量而变化。
