### ISSUE TITLE
快速命令无法完全输入

### ISSUE THREAD

**Issue by Soulballad** [electerm/electerm#3301]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.19-win-x64-installer

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/19262272/b45a3cf7-d4ec-4c95-b9fd-bb401b614d0b)
通过跳板机登录服务器，设置了快速命令，只能执行前面2句，无法第3句进入到指定目录
![image](https://github.com/electerm/electerm/assets/19262272/87f82e69-ea99-4990-8940-025d76be3a1b)

### What should have happened?(期望的结果)

快速命令全部执行，并进入指定目录

**Comment by zxdong262** [comment]
可以试试最新版吗，每个快捷命令可以有多条命令和间隔
