### ISSUE TITLE
Sftp输入框输入路径，回车后无法打开对应路径目录。

### ISSUE THREAD

**Issue by yanyouqing** [electerm/electerm#3308]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.19-win-x64.tar.gz

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

1、打开electerm客户端，进入Sftp页面输入存在的目录地址后按回车键。

### What should have happened?(期望的结果)

能够正常打开输入的目录地址

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否

### Additional information(其他任何相关信息)

无

**Comment by zxdong262** [comment]
可以截图看看吗什么样的地址？

**Comment by yanyouqing** [comment]
![企业微信截图_17116781618957](https://github.com/electerm/electerm/assets/41279456/8408570d-fb0b-4279-99f8-23ebc0b5089b)

**Comment by zxdong262** [comment]
windows下地址应该用反斜杠d:\pub
