### ISSUE TITLE
终端中的超链接点右键不应该弹出web页

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3313]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.30-mac-x64.dmg

### Platform detail (平台详情)

x64

### What steps will reproduce the bug?(重新问题的详细步骤)

本来想右键菜单复制终端时的网址，结果和左键一样，弹出了web页![image](https://github.com/electerm/electerm/assets/45775943/fff4dd9e-208c-421d-8b98-2966a3632d9a)

### What should have happened?(期望的结果)

右键点击到url上不要弹出web页

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
