### ISSUE TITLE
关于mac版本默认打开窗口尺寸

### ISSUE THREAD

**Issue by Hcreak** [electerm/electerm#3314]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

目前每次打开electerm都是窗口模式 这样很不方便
能否改为保留上次关闭时窗口的尺寸 如上次关闭时是全屏 则打开默认为全屏
或者可以设置锁定默认全屏打开的选项
谢谢

**Comment by compasss** [comment]
+1
像iterm2那样设置窗口大小就好了。

**Comment by zxdong262** [comment]
方便按照模版填写一下吗
