### ISSUE TITLE
有时候右键粘贴的是全屏幕的内容，但是我无法复现，也不知道是怎么产生的

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#3317]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.30-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

很抱歉，我无法提供复现问题的步骤，因为我也不知道是什么操作引发的问题。
当我选中一行中的某部分内容，右键自动粘贴时，会把electerm整个屏幕的所有内容都粘贴到命令上，这个问题在所有electerm版本都存在。

注意，这个问题是偶尔发生的，可能是一周发现一两次的概率。
但我不知道是怎么引起的，当我试图重复刚才发生问题的操作时，发现又正常了。

我不知道有没有人也遇到过这个问题。
发帖在这，希望有遇到这个问题的人，能提供更多的信息。

### What should have happened?(期望的结果)

选中需要的内容后，不要把整个屏幕内容都右键粘贴到命令行上。

**Comment by czxin788** [comment]
我发现一种情况。
ctr +a，会变成全选。

其实，我用ctr +a，是为了实现光标快速移动到行首。
但是我发现electerm，按ctr +a，会同时实现两个功能，一个是文字权限，另一个功能是光标快速移动到行首。

那这时可能就会出现一种情况，按了ctr+a，然后右键会自动把全屏的内容，粘贴到命令行上，这种情况很可怕。


我又对比了xshell，发现xhsell的ctr +a就没有全选功能，而是只实现了快速将光标移动到行首，我觉得xshell的这个功能是对的。
用ssh工具，我们几乎不需要ctr +a全选文字的功能。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by czxin788** [comment]
今天又发生了，这次不是ctr +a，但却把全屏的内容都粘贴到命令行上了。
还是没搞明白是怎么发生的。

**Comment by czxin788** [comment]
因为全屏选中文字的这个问题确实很头疼，不知道怎么发生的。
今天测试了一款新的ssh工具windterm，这个工具有个功能挺不错，就是粘贴多行时，会自动弹出个对话框出来，防止多行执行的问题：

![image](https://github.com/electerm/electerm/assets/13861904/f953bf9a-db2e-40e4-9049-12484cb89a55)

windterm 这个工具也挺不错的，不过它也有问题，就是上传下载的文件名是中文时，会变成乱码。

目前发现业界除了xshell和secureCRT，没有一款完美的，每个都有各种问题。

**Comment by mychoxin** [comment]
是的，我也提了这个问题，这个问题很恼火，ctrl-a 是移动光标到开头，但是它还会选中屏幕上的内容，触发选中复制功能。

**Comment by czxin788** [comment]
> 是的，我也提了这个问题，这个问题很恼火，ctrl-a 是移动光标到开头，但是它还会选中屏幕上的内容，触发选中复制功能。

哈哈，同样遭遇。
那你遇到过不是ctr-a，引起的全屏内容复制到命令行的情况吗，我发现好像还有这个问题，但我不知道是怎么产生的。

我觉得可以像windterm工具那样，对于多行内容，应该弹出个对话框来提醒一下，我觉得可以规避一下这个问题。

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by czxin788** [comment]
> 可以试试最新版吗

最新版可以了，赞
