### ISSUE TITLE
希望加上关闭标签可以选择中断本地连接

### ISSUE THREAD

**Issue by dhanweb** [electerm/electerm#3318]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

由于公司项目众多，我把这个软件当做一种快速启动本地项目的工具，只需要点一下就能启动对应项目。
但由于电脑配置不高，我修改完某个项目我习惯性直接关闭标签页，启动下一个项目。我希望能够和win11的 powershell一样，关闭标签页就会中断当前标签页的终端。

**Comment by zxdong262** [comment]
方便用issue模版填写一下吗，包括详细的运行什么命令

**Comment by dhanweb** [comment]
貌似没看见有新功能/特性或者建议的issue模板

我一般只有两条命令：
cd 项目路径
npm run dev

**Comment by zxdong262** [comment]
明白了，感谢，将在下个版本修复

**Comment by zxdong262** [comment]
已修复
