### ISSUE TITLE
标签栏 + 号选择 连接，下拉窗口抖动

### ISSUE THREAD

**Issue by ZYL2019999** [electerm/electerm#3319]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

点击标签栏上的加号会弹出一个纵向的悬浮窗口，在窗口中选择链接时，端口会抖动。怀疑是 链接标题 长短不一导致，希望能优化一下。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
