### ISSUE TITLE
书签页顺序老自己变

### ISSUE THREAD

**Issue by MrZhangWeiCe** [electerm/electerm#3320]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.30-mac-arm64.dmg

### Platform detail (平台详情)

mac os ARM 

### What steps will reproduce the bug?(重新问题的详细步骤)

书签页设置好之后 过几天不管 自己就突然变了顺序了  不知道什么原因导致的，这个bug在之前的版本一直存在。

### What should have happened?(期望的结果)

书签页设置好顺序后不要来回变
<img width="283" alt="image" src="https://github.com/electerm/electerm/assets/29146229/43afdccf-698d-4a55-898c-958f852154a9">

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
请问拖动调整顺序后，再重启程序顺序会变吗？

**Comment by MrZhangWeiCe** [comment]
> 请问拖动调整顺序后，再重启程序顺序会变吗？

不一定，拖动修改好之后，一般很长时间都不会变，但是不一定哪一天就突然变了，也不知道为什么，不知道是不是自动同步那的问题。

**Comment by zxdong262** [comment]
确实跟同步有关

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by MrZhangWeiCe** [comment]
> 可以试试最新版吗

目前测试最新版，没有出现过书签自动变的问题。
