### ISSUE TITLE
选中复制功能问题

### ISSUE THREAD

**Issue by mychoxin** [electerm/electerm#3324]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.25.41-win-x64-installer.exe

### Platform detail (平台详情)

Windows 10 Enterprise

### What steps will reproduce the bug?(重新问题的详细步骤)

BUG1:
1 设置选中复制
2 Ctrl + A 将光标移动到开头
期望：仅仅将光标移动到开头
实际情况：将窗口里所有内容被选中，并复制到粘贴板。
这会导致：一个不小心就会将粘贴板里的大量内容复制到命令行自动执行，不仅污染命令历史记录，还自动执行了一堆乱起八糟的命令，比如不小心点了鼠标右键就复制过来了。
说明：选中复制功能应该仅仅在鼠标选中情况下复制，Ctrl + A 只有在编辑框里有选中功能，在命令行里只有移动光标的功能才对。

BUG2:
1 设置选中复制
2 点击搜索
期望：从底下网上搜索
实际情况：从最上面的地方开始搜索，滚动到最上面，并且被搜索的内容被自动复制到粘贴板
第一点：还是那句话，鼠标选中的才需要复制。
第二点：搜索的时候优先展示最新的数据，旧数据是之前的命令的结果，几乎没啥用，而且自动往上滚了这么远，展示没用的数据。

BUG3：
1 比如编译大型项目
2 产生大量输出
3 ctrl-c
期望：立即结束命令的执行
实际情况：根本结束不了，收不到信号，还影响其他的远程登录窗口，被卡住。

BUG4:
1 比如跑测试用例
2 产生大量输出
期望：较快结束
实际情况：比较慢，用其他的远程登录工具，比如 git bash 就很快。

### What should have happened?(期望的结果)

仅仅鼠标选中时才复制，搜索时不自动复制，ctrl - A 不自动复制

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

没有

### Additional information(其他任何相关信息)

忍受快一年了，不知道为什么其他人没有这些问题
难不成我应该让公司给我买 xshell.

**Comment by zxdong262** [comment]
方便试试最新版不

**Comment by mychoxin** [comment]
一直更新，一直有这些问题，目前版本是 1.38.19

**Comment by czxin788** [comment]
> 一直更新，一直有这些问题，目前版本是 1.38.19

你试试 1.38.41版本，作者解决了ctr +a 全选的问题

**Comment by mychoxin** [comment]
ctrl - A 问题已经解决了，但上面的其他问题不见改观。
