### ISSUE TITLE
1.38.3 版本点击关闭无法正常关闭软件

### ISSUE THREAD

**Issue by fungjcode** [electerm/electerm#3326]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.30-win-x64-installer.exe

### Platform detail (平台详情)

windows 11 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.38.3 版本点击关闭无法正常关闭软件

### What should have happened?(期望的结果)

点击关闭，正常退出软件

**Comment by zxdong262** [comment]
可以试试最新版吗
