### ISSUE TITLE
新增的图标都重叠了

### ISSUE THREAD

**Issue by MrZhangWeiCe** [electerm/electerm#3330]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.41-mac-arm64.dmg

### Platform detail (平台详情)

mac os ARM 

### What steps will reproduce the bug?(重新问题的详细步骤)

书签里新增的图标都重叠了。
<img width="379" alt="image" src="https://github.com/electerm/electerm/assets/29146229/84c422ac-4d09-4286-8c5a-ad3a0893f595">

<img width="460" alt="image" src="https://github.com/electerm/electerm/assets/29146229/2a48b69e-84f0-43fd-bd95-abc2a076fce7">

### What should have happened?(期望的结果)

修改成原来的样子

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
