### ISSUE TITLE
sftp的地址收藏能不能设置增加收藏到列表底部而不是列表顶部

### ISSUE THREAD

**Issue by 4781121** [electerm/electerm#3332]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

sftp的地址收藏能不能设置增加收藏到列表底部而不是列表顶部, 常用的我一般会先收藏然后后添加的都是偶尔用的, 如果总插入到顶部就感觉不太方便, 不知道我的建议合不合适, 谢谢!

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入拖拽排序
