### ISSUE TITLE
windows最新版gitee下载配置报错

### ISSUE THREAD

**Issue by zhang-jianqiang** [electerm/electerm#3334]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.42-win-x64-installer.exe

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

设置token和gist id后点击下载配置报错
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Ap.r.downloadSetting (http://127.0.0.1:30975/js/electerm-1.38.42.js:61:19547)

### What should have happened?(期望的结果)

期望能正常不报错

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

在其它windows和mac上都能复现

**Comment by zhang-jianqiang** [comment]
mack只要下载配置也会提示同样的错误信息

**Comment by zxdong262** [comment]
可以试试先上传一次吗

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zhang-jianqiang** [comment]
> https://github.com/electerm/electerm/releases/tag/v1.38.43

看到您修复了，点赞
