### ISSUE TITLE
【BUG】无法关闭程序

### ISSUE THREAD

**Issue by Meizuamy** [electerm/electerm#3336]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.43-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22631.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

打开应用程序，直接关闭，点击ok之后无法关闭窗口。
https://github.com/electerm/electerm/assets/38857631/6041088e-d66f-4627-a4c1-227334665b7d

### What should have happened?(期望的结果)

可以直接关闭程序

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

没有使用过其他版本

### Additional information(其他任何相关信息)

无

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
