### ISSUE TITLE
终端连接失效 再连接会弹出“ error Cannot set properties of undefined (setting 'onclose')”

### ISSUE THREAD

**Issue by xiediedie** [electerm/electerm#3339]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.43-win-x64

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

连接centos，vim修改文件，按了ctrl+s 就卡死在那里，然后强制关闭后再开窗口，过一会在右下角弹出“error Cannot set properties of undefined (setting 'onclose')”

### What should have happened?(期望的结果)

能够正常使用

**Comment by darkknightxb** [comment]
确实，从1.38.41版本开始就有这个问题，目前能正常使用的最新版本是1.38.30

**Comment by zxdong262** [comment]
可以试试最新版吗 [1.38.50](https://github.com/electerm/electerm/releases/tag/v1.38.50)

**Comment by LLIUZC** [comment]
更新了vite版本好像还是不行，基本上只要关闭了会话就会直接报错，然后无法再进行输入指令

**Comment by xiediedie** [comment]
不行，刚打开就冒出失败，不知道哪里有electerm-1.38.43-win-x64版本使用的缓存数据，导致刚打开就冒出“error
Cannot set properties of undefined (setting 'onclose')”

> 可以试试最新版吗 [1.38.50](https://github.com/electerm/electerm/releases/tag/v1.38.50)

**Comment by xiediedie** [comment]
> 不行，刚打开就冒出失败，不知道哪里有electerm-1.38.43-win-x64版本使用的缓存数据，导致刚打开就冒出“error Cannot set properties of undefined (setting 'onclose')”
> 
> > 可以试试最新版吗 [1.38.50](https://github.com/electerm/electerm/releases/tag/v1.38.50)

![image](https://github.com/electerm/electerm/assets/50254803/88fc8a5b-0664-46e1-b30d-906adfe09f6e)

**Comment by xiediedie** [comment]
> 可以试试最新版吗 [1.38.50](https://github.com/electerm/electerm/releases/tag/v1.38.50)

不行，1.38.50版本刚打开就冒出失败，不知道哪里有electerm-1.38.43-win-x64版本使用的缓存数据，导致刚打开就冒出“error Cannot set properties of undefined (setting 'onclose')”
![image](https://github.com/electerm/electerm/assets/50254803/c6cbb875-f7fa-4097-bd75-1d1f67cacba0)

**Comment by zxdong262** [comment]
可以删除 `C:\Users\your-user-name\AppData\Roaming\electerm` 里面除了users以外的文件和文件夹试试吗

**Comment by LLIUZC** [comment]
还是不行，windows10下开启了新的标签页关闭了其中一个就会报错，并且在其他的标签页内无法再做输入指令操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHAO ***@***.***&gt;; 
发送时间: 2024年4月6日(星期六) 晚上6:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [electerm/electerm] 终端连接失效 再连接会弹出“ error Cannot set properties of undefined (setting &#39;onclose&#39;)” (Issue #3339)














 
可以删除 C:\Users\your-user-name\AppData\Roaming\electerm 里面除了users以外的文件和文件夹试试吗

**Comment by zxdong262** [comment]
可以试试1.38.60吗，应该修复了

**Comment by LLIUZC** [comment]
![1712537993510](https://github.com/electerm/electerm/assets/102634309/4845596c-4df8-475b-88f4-47350bf38984)
我试了安装了应用程序还有dev启动还是会出现这个问题，dev启动的时候我切换了不同的node版本(18.13.0、18.15.0、18.16.1)，但是报错仍然是v18.16.1

**Comment by xiediedie** [comment]
> 可以试试1.38.60吗，应该修复了

试了1.38.60版本，ok了

**Comment by LLIUZC** [comment]
那可能是我这边环境问题了

**Comment by darkknightxb** [comment]
我换了新版仍然是有这个问题，在切换标签的时候，发现有这个图标在闪，一会就消失了，感觉像是连接断开了？但我用的是本地命令行啊。
基本上是有三种问题，第一种是长时间运行的任务会自动停止，第二种是光标处无法输入新的内容，第三种是新的Tab页打开后无法连接。
删掉用户目录下的electerm文件夹仍然无效。
![image](https://github.com/electerm/electerm/assets/10458461/49f425aa-f420-46b8-9e69-313e7175344d)

**Comment by huu3301** [comment]
用的最新版本v1.38.65，也是出现同样的问题。连接到centos，啥都没做，只是cd 到某个目录，等一会就出现连接断开，之后怎么都连接不上，关闭整个electerm后再打开可以连接，但是cd后又会出现同样的问题。

**Comment by zxdong262** [comment]
> 用的最新版本v1.38.65，也是出现同样的问题。连接到centos，啥都没做，只是cd 到某个目录，等一会就出现连接断开，之后怎么都连接不上，关闭整个electerm后再打开可以连接，但是cd后又会出现同样的问题。

可以试试保活间隔设为0试试吗

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by darkknightxb** [comment]
试了最新的portable版本，还是一样的，开始好用，过段时间就不好用了。敲击键盘没反应，按回车会出现这样的绿色符号。
![image](https://github.com/electerm/electerm/assets/10458461/0be92e24-23d6-4254-8cce-3111bd513dd2)

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.81 吗

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.86 吗

**Comment by LLIUZC** [comment]
是的能正常关闭本地会话了

> 可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.86 吗

**Comment by darkknightxb** [comment]
> 可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.86 吗

用了一天，目前没发现问题
