### ISSUE TITLE
[Bug]mac 1.38.60版本，点击“快速命令”后显示异常

### ISSUE THREAD

**Issue by liumingxiyou** [electerm/electerm#3346]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.60-mac-x64.dmg

### Platform detail (平台详情)

 mac os(x64)

### What steps will reproduce the bug?(重新问题的详细步骤)

1、点击右下角“快速命令”
2、electerm报错，显示如下：
Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes') at http://127.0.0.1:30975/js/electerm-1.38.60.js:94:1521 at Array.some (<anonymous>) at a (http://127.0.0.1:30975/js/electerm-1.38.60.js:94:1504) at http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:28807 at nn (http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:859) at http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:28783 at http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:26924 at http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:23245 at lu (http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:26896) at mu (http://127.0.0.1:30975/chunk/lodash-es-1.38.60-e27ce080.js:1:28756)
![iShot_2024-04-08_11 26 36](https://github.com/electerm/electerm/assets/119272127/3df77050-3e63-4e56-b1d1-969090c47c9d)
![iShot_2024-04-08_11 26 06](https://github.com/electerm/electerm/assets/119272127/a49f03fb-ed2d-4124-b6c7-39762f58fc17)

### What should have happened?(期望的结果)

正常显示快速命令

**Comment by liumingxiyou** [comment]
调整过快捷命令顺序

**Comment by zxdong262** [comment]
最新版已经修复
