### ISSUE TITLE
SFTP批量上传会遗漏文件

### ISSUE THREAD

**Issue by kennysoul** [electerm/electerm#3353]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.60-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

这个问题印象中是从最开始就一直都存在，我每次全选我的web目录的文件上传，都会剩下一到两个文件（绝大多数时候是最后的1、2个）没有传上去，如下图所示，我全选了选择上传，最后就有两个文件没有上传
![Screenshot 2024-04-09 143329](https://github.com/electerm/electerm/assets/17644491/b8719a39-ed2e-4a71-b187-b07472ad0325)
下面是上传完毕后的结果：
![Screenshot 2024-04-09 143405](https://github.com/electerm/electerm/assets/17644491/e06df414-2845-4323-be2d-734b15e7b032)

### What should have happened?(期望的结果)

希望能修复这个bug，虽然用的不多，但是这个问题已经存在很长时间了

**Comment by zxdong262** [comment]
感谢反馈，确实存在，争取下个版本修复
