### ISSUE TITLE
在screen命令下，按ctr+a，无法实现快速将光标移动到行首

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#3358]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-.38.65-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

[root@bigdata-report05 scripts]# screen 
[root@bigdata-report05 scripts]# fdfdfdfd   在这按ctr +a无法实现将光标快速移动到行首

### What should have happened?(期望的结果)

期望在screen命令下，也能实现按ctl +a，也能将光标快速移动到行首

**Comment by zxdong262** [comment]
我试了默认linux终端screen下面ctrl+a也不会回到行首，这似乎是默认行为

**Comment by czxin788** [comment]
收到，谢谢解答，辛苦了
