### ISSUE TITLE
每次升级都会清除安装目录下的其他文件

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3362]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows 7/8/10/11

### What steps will reproduce the bug?(重新问题的详细步骤)

我在安装目录下存放了一些图片当终端背景，结果一升级都补删除掉

### What should have happened?(期望的结果)

希望升级时删除程序相关文件，不要删除无法文件

**Comment by zxdong262** [comment]
目前安装包没有这种功能

**Comment by etanman** [comment]
我的意思是说版本升级时，会把我放到安装目录里的图片给误删掉，希望解决这个问题。

**Comment by zxdong262** [comment]
> 我的意思是说版本升级时，会把我放到安装目录里的图片给误删掉，希望解决这个问题。

构建安装包没有这种功能，建议把图片之类的文件放在自己的文件目录，windows权限管理是有缺陷的，允许放在安装目录下

**Comment by etanman** [comment]
> > 我的意思是说版本升级时，会把我放到安装目录里的图片给误删掉，希望解决这个问题。
> 
> 构建安装包没有这种功能，建议把图片之类的文件放在自己的文件目录，windows权限管理是有缺陷的，允许放在安装目录下

建议作者在安装目录随便放一些文件，然后执行软件的安装程序，的确会先删除安装目录下所有文件，而不是程序自己的文件，这样是很危险的动作。
