### ISSUE TITLE
希望命令行和输入的命令可以有别的颜色

### ISSUE THREAD

**Issue by freedomspiritJohn** [electerm/electerm#3363]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

<img width="699" alt="PixPin_2024-04-11_20-15-30" src="https://github.com/electerm/electerm/assets/129288685/98a802f0-2f72-4828-8204-e36dad1d2af3">
可以给命令行设置一个背景色，给命令设置不同的颜色

**Comment by zxdong262** [comment]
主题编辑功能试试可以满足需求不？

**Comment by freedomspiritJohn** [comment]
> 主题编辑功能试试可以满足需求不？

但是我不知道哪个字段是控制输入命令和用户颜色的。你找到它了吗

**Comment by zxdong262** [comment]
> > 主题编辑功能试试可以满足需求不？
> 
> 但是我不知道哪个字段是控制输入命令和用户颜色的。你找到它了吗

我也不知道，可以试试那些iterm2主题，也许有合适的

**Comment by freedomspiritJohn** [comment]
> > > 主题编辑功能试试可以满足需求不？
> > 
> > 
> > 但是我不知道哪个字段是控制输入命令和用户颜色的。你找到它了吗
> 
> 我也不知道，可以试试那些iterm2主题，也许有合适的

好像不行，还是无法单独设置命令和用户的颜色

**Comment by zxdong262** [comment]
![Screen Shot 2024-06-24 at 19 26 50](https://github.com/electerm/electerm/assets/1641949/58b248cf-c42d-4326-87ed-1488a5c27f65)

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/wiki/Terminal-keywords-highlight-regular-expression-exmaples
