### ISSUE TITLE
增加其它连接方式，实现同一软件管理所有业务系统

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [electerm/electerm#3366]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

软件当前支持SSH、telnet、console直连，能实现对部分交换机、服务器的管理。但是，在企业中，有些交换机只支持Web操作；有些服务器是Windows系统，需要通过远程桌面进行管理。希望该软件能支持Web和RDP，以实现在一个软件上管理企业内的所有交换机、服务器。望采纳，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by zxdong262** [comment]
请问web方式是指浏览器访问地址吗？

**Comment by AisinGioroKiIoi** [comment]
> 請問web方式是指瀏覽器訪問位址嗎？

是的，浏览器收藏夹功能。哪怕是只保存个书签，点一下连接，能调用电脑自身浏览器也好。这样在一个软件中既可以分辨出哪些是SSH的，哪些是telnet的，哪些是Web的，哪些是远程桌面的；又能比较明确的看到有哪些系统。

**Comment by zxdong262** [comment]
[1.39.2](https://github.com/electerm/electerm/releases/tag/v1.39.2) 已经支持RDP和web

**Comment by WLaoDuo** [comment]
感谢大佬开发。好家伙，真成万能终端了，以前只能连linux类设备，现在功能挺全的了

**Comment by WLaoDuo** [comment]
> ### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)
> 
> 软件当前支持SSH、telnet、console直连，能实现对部分交换机、服务器的管理。但是，在企业中，有些交换机只支持Web操作；有些服务器是Windows系统，需要通过远程桌面进行管理。希望该软件能支持Web和RDP，以实现在一个软件上管理企业内的所有交换机、服务器。望采纳，ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

之前我是使用 https://github.com/1Remote/1Remote 来登录win主机，linux就使用命令行调用elcterm登录。勉强做到一个软件登录大多数设备（套娃调用），现在大佬的elcterm新功能真nb
