### ISSUE TITLE
书签同步问题

### ISSUE THREAD

**Issue by MrZhangWeiCe** [electerm/electerm#3370]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.65-mac-arm64.dmg

### Platform detail (平台详情)

macos m2 

### What steps will reproduce the bug?(重新问题的详细步骤)

书签修改名称后同步gitee失效，终端不能同步过去

### What should have happened?(期望的结果)

能正常同步

**Comment by zxdong262** [comment]
请问具体哪一步报错呢，保存？上传？下载？有没有密码呢？

**Comment by zxdong262** [comment]
有没有其他机器可以试试？

**Comment by zxdong262** [comment]
改完之后点击上传了吗？

**Comment by MrZhangWeiCe** [comment]
> 改完之后点击上传了吗？

上传可，我看了下gitee同步的数据，gitee上数据是新的 同步不到我的笔记本上面

**Comment by MrZhangWeiCe** [comment]
> 改完之后点击上传了吗？

上传了，我看了下gitee同步的数据，gitee上数据是新的，但是同步不到我的笔记本上面

**Comment by MrZhangWeiCe** [comment]
重新生成新token后 再同步报错

SyntaxError: "undefined" is not valid JSON at JSON.parse (<anonymous>) at Ap.r.downloadSetting (http://127.0.0.1:30975/js/electerm-1.38.65.js:61:19668)


<img width="382" alt="image" src="https://github.com/electerm/electerm/assets/29146229/e8f56f6f-2cb6-4dae-879a-b7dacd95909d">

**Comment by zxdong262** [comment]
> 重新生成新token后 再同步报错
> 
> SyntaxError: "undefined" is not valid JSON at JSON.parse () at Ap.r.downloadSetting (http://127.0.0.1:30975/js/electerm-1.38.65.js:61:19668)
> 
> <img alt="image" width="382" src="https://private-user-images.githubusercontent.com/29146229/322663391-e8f56f6f-2cb6-4dae-879a-b7dacd95909d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjc4NzcsIm5iZiI6MTcxMzIyNzU3NywicGF0aCI6Ii8yOTE0NjIyOS8zMjI2NjMzOTEtZThmNTZmNmYtMmNiNi00ZGFlLTg3OWEtYjdkYWNkOTU5MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTZkYjNjYjVhNjgzOTJiN2Y4NDk4OTQwYjFlYjRmMmM5ZDQ3NzNlNGJjYmE4ODM1MjQ1MjA1OGQ1MzA1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8aqxfZTSNG7OqCi4W2_cH9PQFwdWR_o7aRQSyS9Qkw">

可以检查下gist不， 看看有没有userConfig.json这个文件？

**Comment by MrZhangWeiCe** [comment]
> > 重新生成新token后 再同步报错
> > SyntaxError: "undefined" is not valid JSON at JSON.parse () at Ap.r.downloadSetting (http://127.0.0.1:30975/js/electerm-1.38.65.js:61:19668)
> > <img alt="image" width="382" src="https://private-user-images.githubusercontent.com/29146229/322663391-e8f56f6f-2cb6-4dae-879a-b7dacd95909d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjc4NzcsIm5iZiI6MTcxMzIyNzU3NywicGF0aCI6Ii8yOTE0NjIyOS8zMjI2NjMzOTEtZThmNTZmNmYtMmNiNi00ZGFlLTg3OWEtYjdkYWNkOTU5MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTZkYjNjYjVhNjgzOTJiN2Y4NDk4OTQwYjFlYjRmMmM5ZDQ3NzNlNGJjYmE4ODM1MjQ1MjA1OGQ1MzA1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8aqxfZTSNG7OqCi4W2_cH9PQFwdWR_o7aRQSyS9Qkw">
> 
> 可以检查下gist不， 看看有没有userConfig.json这个文件？

没有那个json文件

<img width="693" alt="image" src="https://github.com/electerm/electerm/assets/29146229/23db7b9f-f293-4c82-b467-531b119c91a8">

**Comment by MrZhangWeiCe** [comment]
> > 重新生成新token后 再同步报错
> 可以检查下gist不， 看看有没有userConfig.json这个文件？

同步github有userConfig.json 这个文件 gitee没有

**Comment by zxdong262** [comment]
> > > 重新生成新token后 再同步报错
> > > 可以检查下gist不， 看看有没有userConfig.json这个文件？
> 
> 同步github有userConfig.json 这个文件 gitee没有

感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
最新版已经修复
