### ISSUE TITLE
DD系统后发现ET貌似有个BUG

### ISSUE THREAD

**Issue by 8u8m** [electerm/electerm#3372]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

任意版本都存在的问题，试了最新版本也一样存在

### Platform detail (平台详情)

WIN10 X64

### What steps will reproduce the bug?(重新问题的详细步骤)

不知道ET是有缓存还是怎么回事，我的甲骨文VPS进行DD完系统后，无论怎么设置使用KEY登录并禁止密码登录都不能生效。使用KEY确实能登录，但使用任意密码也能登录，注意是任意密码，也就是无论我怎么修改密码或者禁止密码登录，用ET使用123456做密码都能登录。我不知道是不是ET存在缓存的问题还是什么原因，在使用FINALSHELL就是正常的，用任何密码是登录不了的，只能用KEY登录，这和我的设置是一致的。

### What should have happened?(期望的结果)

修复BUG或者告知我如何处理，否则因为这个原因可能无法放心用下去了。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

并没有

**Comment by zxdong262** [comment]
我试了，即便允许密码登录，错误密码也无法登陆，也许有什么细节我没有掌握？是通过书签吗？方便截图看看不？

**Comment by 8u8m** [comment]
> 我试了，即便允许密码登录，错误密码也无法登陆，也许有什么细节我没有掌握？是通过书签吗？方便截图看看不？

不好意思，原来是我的问题。我是直接复制了旧的登录信息，在私匙那里没有删除清空（因为框太小也看不见内容），从而导致后面无论什么密码都能登录。十分抱歉，这不是BUG，是我的错，对不起！
