### ISSUE TITLE
SFTP: Delete action while using 'del' button

### ISSUE THREAD

**Issue by rationalgaze** [electerm/electerm#3374]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.60-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22621.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

While renaming a file in sftp filebrowser if I'm hitting `Del` button on my keyboard it triggers delete file action. (Then I hit cancel button in the delete popup and it exit renaming)
![image](https://github.com/electerm/electerm/assets/7567945/d5377f88-696b-419c-9de4-92dc268b7f51)

### What should have happened?(期望的结果)

When I'm using `Del` button on my keyboard it should delete filename letters without triggering delete-file action.

**Comment by zxdong262** [comment]
Thank you, would fix in next release

**Comment by zxdong262** [comment]
Fixed in latest release
