### ISSUE TITLE
书签、访问历史被快速命令遮挡（不保持面板打开的情况下）

### ISSUE THREAD

**Issue by ningqingsheng** [electerm/electerm#3377]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.65-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

与https://github.com/electerm/electerm/issues/3348  类似
![image](https://github.com/electerm/electerm/assets/31916341/8d69b665-5fce-4199-b05b-a7e0ab633536)

### What should have happened?(期望的结果)

不被遮挡或与保持面板打开时的展示方式相同

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
最新版已修复
