### ISSUE TITLE
网页直接打开软件，自动连接登录

### ISSUE THREAD

**Issue by Ryoui** [electerm/electerm#3378]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![QQ截图20240422141622](https://github.com/electerm/electerm/assets/18000474/e818020d-dba5-4d16-b0c7-766c503cc793)
能支持这种方式打开吗，现在选择软件后能打开，但没自动连接，xshell,putty,SecureCRT等都支持

**Comment by zxdong262** [comment]
请问是希望打开其他软件的链接还是专属链接比如electerm://xxxxx

**Comment by Ryoui** [comment]
@zxdong262 我不清楚具体实现。场景就是一个网页选择了用哪个客户端（xshell,putty,SecureCRT等），然后就提示上面的截图内容，然后点打开就自动连接服务器（使用网页上提供的ip，端口等参数）。我只是希望electerm提供这种能力，后面才有厂商对接

**Comment by Ryoui** [comment]
验证了下，好像还是不行，不知道是不是我使用问题：  
electerm版本：1.38.86  
直接浏览器访问：electerm://host=192.168.2.215&password=xxx&user=root&port=22  
上述参数直接用软件能连上。用浏览器访问会提示是否打开electerm软件，点击打开，只会打开软件不会自动连接，如图：  
![QQ截图20240507101526](https://github.com/electerm/electerm/assets/18000474/0f9059b1-b046-42a9-966f-fc491178537c)

**Comment by Ryoui** [comment]
1.39.2验证了，也不行。不知道什么情况：
`<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>验证electerm</title>
    <script>
        function openBaidu() {
            window.open('electerm://host=192.168.2.215&password=密码&user=root&port=22', '_blank');
        }
    </script>
</head>
<body>
<button onclick="openBaidu()">打开electerm</button>
</body>
</html>`

**Comment by Ryoui** [comment]
![图片](https://github.com/electerm/electerm/assets/18000474/ef5d81e7-9208-4462-8cb1-662fee863bc5)

**Comment by zxdong262** [comment]
> 1.39.2验证了，也不行。不知道什么情况： `
> 
> <title>验证electerm</title> <script> function openBaidu() { window.open('electerm://host=192.168.2.215&password=密码&user=root&port=22', '_blank'); } </script> 打开electerm `

可以试试地址栏直接访问测试吗？
