### ISSUE TITLE
无法同时连接同一个服务

### ISSUE THREAD

**Issue by unesco3187** [electerm/electerm#3385]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.70-mac-arm64.dmg

### Platform detail (平台详情)

MacBook Pro Apple M1 Max

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="893" alt="image" src="https://github.com/electerm/electerm/assets/18564706/876c756f-e046-42b5-a2ca-1625b1e1ca3c">
<img width="1227" alt="image" src="https://github.com/electerm/electerm/assets/18564706/d911db68-535b-4c60-be01-3436254b5e3c">

### What should have happened?(期望的结果)

希望和以前一样,同一个服务可以多个窗口同时连,换了其他的ssh连接工具都是正常的,希望可以尽快修复

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能

**Comment by zxdong262** [comment]
Mac上复现不了，难道arm mac的特殊情况？有没有其他设备可以试试的？

**Comment by unesco3187** [comment]
之前的版本是可以的,升级到最新版本之后就不行了

**Comment by unesco3187** [comment]
应该和公司的网络还有这个服务器也有点关系吧,我试了其他的服务,暂时没发现问题,要不暂时忽略吧,麻烦您了
