### ISSUE TITLE
win11系统下关闭默认new terminal 后，新建的terminal均无法连接。

### ISSUE THREAD

**Issue by ma-chengpeng** [electerm/electerm#3387]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

# 1.关闭左上角默认new terminal

# 2.点击左上角加号或直接点击新的需连接服务器，将一直显示在加载中无法连接
![无法连接_1](https://github.com/electerm/electerm/assets/50961349/844b63c2-7082-4981-9894-5c0d714b490e)
![无法连接_2](https://github.com/electerm/electerm/assets/50961349/b4494c58-6e54-4361-abad-bc54de6cfc3e)
![无法连接_3](https://github.com/electerm/electerm/assets/50961349/fbfd1ff6-cc4e-4863-bdb9-9dcb4ae342a2)

### What should have happened?(期望的结果)

关闭默认terminal 后，新建的terminal 应该都可以连接。

**Comment by chaizp** [comment]
同样有相同问题，现象和执行了exit退出了默认的终端一样

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.86 吗

**Comment by ma-chengpeng** [comment]
在v1.38.81版本已修复，非常感谢！
