### ISSUE TITLE
第一次打开sftp时，将ssh中的路径带入到sftp

### ISSUE THREAD

**Issue by Arjen10** [electerm/electerm#3388]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

现在每次想上传文件时候，都需要pwd一下，将当前路径复制到sftp的输入框回车。

能否自动将ssh的当前路径带入到sftp下？

![461986D1-EE1A-4593-878C-7563296761A3](https://github.com/electerm/electerm/assets/47875127/a9d6ca37-000c-4dd6-948b-31bb098da574)

**Comment by zxdong262** [comment]
Sftp文字右边有个锁定路径的按钮，可以试试
