### ISSUE TITLE
在“新连接”窗口中执行exit客户端将无法操作

### ISSUE THREAD

**Issue by chaizp** [electerm/electerm#3389]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.70-win-x64.tar.gz

### Platform detail (平台详情)

windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

问题如图，执行exit后几秒客户端中的所有连接都无法在输入
![屏幕录制-2024-04-29-05-59-26](https://github.com/electerm/electerm/assets/7780550/b01aaae8-7804-4b67-b46c-8703d26e0ae1)
关掉默认终端，几秒后所有终端都无法操作了
![屏幕录制-2024-04-29-08-37-37](https://github.com/electerm/electerm/assets/7780550/69a82d87-1f57-48fc-9fb3-62c3f36e7eee)

### What should have happened?(期望的结果)

正常操作

### Additional information(其他任何相关信息)
期望增加同屏功能，类似xshell在一个界面中同时操作多个不同连接
_No response_

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.86 吗

**Comment by chaizp** [comment]
> 可以试试https://github.com/electerm/electerm/releases/tag/v1.38.86吗

已修复
