### ISSUE TITLE
sz命令传文件卡住不动

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#3402]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.86-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/13861904/50164373-895f-42ec-9be3-65cf32c950d8)

sz命令传文件一直卡着不动。
![image](https://github.com/electerm/electerm/assets/13861904/e8dc77fa-c1c7-46da-be86-fb121836e2c1)

发现rz也卡着。

electerm现在最不好用的地方就是rz和sz命令。

### What should have happened?(期望的结果)

sz命令传文件不要卡着

**Comment by zxdong262** [comment]
请问是每次都复现吗，我试了几次都没有复现这个问题

**Comment by czxin788** [comment]
不是每次都卡，一开始用着好好的，不知道为什么突然rz和sz命令就不用了了，只能通过其他窗口强杀掉那个会话。
我先用trzsz吧，需要用的机器提前安装个trz和rsz命令，这两个命令用着还行。
