### ISSUE TITLE
可不可以增加个系统设置, sftp的隐藏文件默认是显示还是隐藏这个功能?

### ISSUE THREAD

**Issue by 4781121** [electerm/electerm#3404]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

隐藏文件太多, 一般用不到但占据列表位置, 我想默认隐藏掉, 可以增加这个功能吗? 谢谢你!

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入

**Comment by zxdong262** [comment]
感谢支持！

**Comment by 4781121** [comment]
感谢!

**Comment by zxdong262** [comment]
最新版已加入 https://github.com/electerm/electerm/releases/tag/v1.39.2
