### ISSUE TITLE
跨版本下载设置失败

### ISSUE THREAD

**Issue by JinLong369** [electerm/electerm#3405]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.86-win-x64-installer.exe、electerm-1.25.50-win-x64

### Platform detail (平台详情)

windows 10

##### 背景

之前在工作电脑上使用的是 1.25.50 版本（应该是压缩包版本），现在在个人电脑上安装 electerm-1.38.86-win-x64-installer.exe。
然后使用 1.38.86 软件【设置同步】中 gitee 的【下载配置】，直接报错：

```
Error: Seems you have a empty gist, you can try use existing gist ID or upload first at Bp.r.downloadSetting (http://127.0.0.1:30975/js/electerm-1.38.86.js:61:19433)
```

##### 详细步骤

1. 1.25.50 版本，【设置同步】中【gitee】配置 token 及 gist，先后点击【保存】【上传配置】；
2. 升级成 1.38.86 版本，【设置同步】中【gitee】点击【下载配置】，报上面提到的错误。

##### 解决过程

在 Issue [设置同步-gitee-下载设置报错 · Issue #2867 · electerm/electerm](https://github.com/electerm/electerm/issues/2867) 中，提出应该是软件版本有关。

当时上传的 gist 中将软件版本号也一同上传了，所以我下载了对应版本的包，再下载配置就好了。
![105141-0aa46bd2c6](https://github.com/electerm/electerm/assets/50287763/4d51c2f3-a903-4c94-bcdb-f7ae26ee6acd)

但再次更新到最新版本 1.38.6，上传最新配置，再下载配置时，仍然报同样的错误......

怀疑上传配置可能是在之前的基础上进行修改，老版的部分配置新版没有，新版上传时也没有先删除全部片段后新增，导致有部分无效配置遗留。而新版下载配置时，可能校验不通过然后失败......

所以就新创建一个 gist （将原 gist 清空应该也可以，但没测），再上传新版配置，此时【下载配置】恢复正常。
然而新版配置中，版本号配置已经没了，再出问题就不好找版本了......

### What should have happened?(期望的结果)

之前的版本可能不好处理了，但之后的版本，希望配置能兼容下，要不同步起来还是挺麻烦的。

**Comment by zxdong262** [comment]
将在下个版本修复，感谢反馈
