### ISSUE TITLE
RDP不起效

### ISSUE THREAD

**Issue by SniperLockon** [electerm/electerm#3412]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.2-win-x64-installer.exe

### Platform detail (平台详情)

Windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

RDP连接一直不显示，手动用MSTSC没问题
![Snipaste_2024-05-10_00-58-04](https://github.com/electerm/electerm/assets/19585784/7544fff1-17cd-4d43-84c2-990258c6dfd9)

### What should have happened?(期望的结果)

因为这个功能新上线，没有在User GUIDE 找到RDP相关说明
还是因为我的使用方法有误导致的无法连接

**Comment by zxdong262** [comment]
需要关闭网络验证

**Comment by xrhh** [comment]
> 需要关闭网络验证，这个需要提示用户

在哪里关闭网络验证？百度了一下，在以太网的属性里没有找到网络验证这一项

**Comment by zxdong262** [comment]
> > 需要关闭网络验证，这个需要提示用户
> 
> 在哪里关闭网络验证？百度了一下，在以太网的属性里没有找到网络验证这一项

![Screen Shot 2024-05-14 at 16 07 02](https://github.com/electerm/electerm/assets/1641949/09f7d267-6ea0-47a3-88ef-095a4febf884)

**Comment by zxdong262** [comment]
![Uploading Screen Shot 2024-05-14 at 16.10.52.png…]()

**Comment by zxdong262** [comment]
![Screen Shot 2024-05-14 at 16 10 52](https://github.com/electerm/electerm/assets/1641949/6477c46b-fc0a-491c-ac20-21a99394c28b)

**Comment by xrhh** [comment]
> ![Screen Shot 2024-05-14 at 16 10 52](https://private-user-images.githubusercontent.com/1641949/330341781-6477c46b-fc0a-491c-ac20-21a99394c28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzYwNjgsIm5iZiI6MTcxNTczNTc2OCwicGF0aCI6Ii8xNjQxOTQ5LzMzMDM0MTc4MS02NDc3YzQ2Yi1mYzBhLTQ5MWMtYWMyMC0yMWE5OTM5NGMyOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDExNjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZiMDExZWU1NDhkZjQ0ZTZhZWM1Y2JkZjI0OTc2YzU3NmUzYmZkZTc1OGNmOGQ0N2QyN2Q0N2EzYmYzZDk0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HrzNvs6Q_GfF3lqAJBqyXGak22HSUNV6qlH43uTDBgw)

连接成功了。希望能做到其它rdp软件一样不需要设置也能连接

**Comment by zxdong262** [comment]
> > ![Screen Shot 2024-05-14 at 16 10 52](https://private-user-images.githubusercontent.com/1641949/330341781-6477c46b-fc0a-491c-ac20-21a99394c28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzYwNjgsIm5iZiI6MTcxNTczNTc2OCwicGF0aCI6Ii8xNjQxOTQ5LzMzMDM0MTc4MS02NDc3YzQ2Yi1mYzBhLTQ5MWMtYWMyMC0yMWE5OTM5NGMyOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDExNjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZiMDExZWU1NDhkZjQ0ZTZhZWM1Y2JkZjI0OTc2YzU3NmUzYmZkZTc1OGNmOGQ0N2QyN2Q0N2EzYmYzZDk0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HrzNvs6Q_GfF3lqAJBqyXGak22HSUNV6qlH43uTDBgw)
> 
> 连接成功了。希望能做到其它rdp软件一样不需要设置也能连接

暂时不能，这个目前唯一的rdp库已经六年没动了。。。

**Comment by nikelius** [comment]
出现类似问题，同一个服务器，在 1Remote 中可以直接连接。不清楚两者底层有何不同。
