### ISSUE TITLE
连接跳跃后sftp下载失败

### ISSUE THREAD

**Issue by frankterm** [electerm/electerm#3420]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.39.2 mac book m2

### Platform detail (平台详情)

mac book m2 13.1 (22C65)

### What steps will reproduce the bug?(重新问题的详细步骤)

连接跳跃功能特别好，先点个赞。我还赞助了5美元。
ssh连接跳跃没问题，sftp下载文件失败，进度一致0%
![截屏2024-05-13 14 56 10](https://github.com/electerm/electerm/assets/102810662/4383ab64-b079-4a77-b90c-e9c762b0ee5a)

### What should have happened?(期望的结果)

连接跳跃sftp文件上传和下载成功。

**Comment by zxdong262** [comment]
感谢支持！我试了本地几个虚拟机之间跳跃，没有复现这个问题，可以详细描述步骤吗，也许某个某个细节我没有做到

**Comment by frankterm** [comment]
我再次测试，也成功了。也许是当时有暂时性的异常，不一定是咱们软件造成的。
谢谢，辛苦了
