### ISSUE TITLE
Tab过多占满顶部状态栏时, 没有区域可点击拖动窗口

### ISSUE THREAD

**Issue by tonyttz** [electerm/electerm#3434]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

当多打开一些标签后, 标签占满了顶部状态栏, 这时想去拖动窗口, 发现几乎没有可供鼠标点击拖动的地方(顶部被标签占满, 左侧栏不支持拖动). 建议: 1. 控制tab区域, 让顶部栏右侧一小块区域不被 tab 覆盖 2. 左侧菜单栏下部区域支持拖动窗口

**Comment by zxdong262** [comment]
还是有区域的，不过不明显，将在下个版本改进，感谢反馈
![Screen Shot 2024-05-18 at 15 01 17](https://github.com/electerm/electerm/assets/1641949/faf217c8-9183-4f66-a7e5-ac755065cb59)

**Comment by tonyttz** [comment]
Thank you very much
