### ISSUE TITLE
一个很奇怪的渲染问题

### ISSUE THREAD

**Issue by winddriver** [electerm/electerm#3441]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.18-win-x64-portable.tar.gz

### Platform detail (平台详情)

Windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

SSH远程连接，窗口中输出的某些符号经常会变成很奇怪的样子
如图的 <= 和 >= 就有一些变样子了
![image](https://github.com/electerm/electerm/assets/3221597/055ed1ad-589e-4699-9e86-17c4bf03103d)

只要我把窗口大小来回调整，让窗口重新渲染，多试几次就会发现渲染有时候能恢复正常
![image](https://github.com/electerm/electerm/assets/3221597/402259e5-b95c-4fdb-a147-443c7f422ff5)

其实这个问题在很早的版本中就存在了，一直到目前最新的版本也有

### What should have happened?(期望的结果)

希望能正确渲染，不要出现奇怪的乱字符

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不能

**Comment by winddriver** [comment]
重置终端设置之后，然后重新打开了一个SSH标签，显示同样一段内容，效果如下
![image](https://github.com/electerm/electerm/assets/3221597/e6c01f15-1e06-4612-befb-c4a95359b9ff)

同样的内容，在另一个终端软件中显示如下
![image](https://github.com/electerm/electerm/assets/3221597/d11fa406-b251-4689-a614-75a750e1316f)

**Comment by winddriver** [comment]
[test.log](https://github.com/electerm/electerm/files/15399608/test.log)
这个问题可以百分之百重现，只要你把这个test.log放到任意需要ssh连接的服务器上，然后用electerm连上去
用cat或者tail查看该文件内容，你就会发现其中很多 => 和 <= 变成乱码了

**Comment by winddriver** [comment]
甚至用vi编辑，也是同样的问题，所以可以肯定是渲染的代码出了问题

**Comment by zxdong262** [comment]
=>等渲染成连在一起是专门使用支持连字符的字体和专门的渲染实现的，出于美观的目的，如果不习惯，可以设置换成其他字体不支持连字符的就不会了

**Comment by winddriver** [comment]
把字体中的Fira Code去掉之后居然真的没问题了
![image](https://github.com/electerm/electerm/assets/3221597/41336472-8f12-458a-859d-8fa377cc1864)
![image](https://github.com/electerm/electerm/assets/3221597/f41c27e9-3c85-45cc-a27f-dda799e307fc)
