### ISSUE TITLE
渲染类型无法切换到dom与webGL,只能选canvas

### ISSUE THREAD

**Issue by night-rainy** [electerm/electerm#3450]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electem-1.39.18-win-x64-installer.exe

### Platform detail (平台详情)

winows11

### What steps will reproduce the bug?(重新问题的详细步骤)

点击设置,终端设置,切换渲染类型无效

### What should have happened?(期望的结果)

渲染类型可以切换

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
