### ISSUE TITLE
SSH Tunnel on Same Local Port

### ISSUE THREAD

**Issue by YXL76** [electerm/electerm#3452]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.18-linux-amd64.deb

### Platform detail (平台详情)

6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

When two SSH connection whcih enable tunnel on the same local port, an `uncaughtException` will be raised and all new connection will hung on connecting state.

```log
uncaughtException Error: listen EADDRINUSE: address already in use 127.0.0.1:12345
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
```

### What should have happened?(期望的结果)

The error will be caught.

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
