### ISSUE TITLE
建议标签的侧边栏可以左右拖拽，这样有时需要看起各个标题完整名很方便

### ISSUE THREAD

**Issue by czxin788** [electerm/electerm#3464]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/electerm/electerm/assets/13861904/0fe12b85-178a-4afa-acfb-b64328920828)
建议标签的侧边栏可以左右拖拽，这样有时需要看起各个标题完整名很方便

**Comment by zxdong262** [comment]
可以的，你试试

**Comment by czxin788** [comment]
确实可以，固定才能左右拉，先前没发现，谢谢。
