### ISSUE TITLE
全部展开问题

### ISSUE THREAD

**Issue by yang1yangyang** [electerm/electerm#3468]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.35-win-x64-installer.exe

### Platform detail (平台详情)

windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

1.刚打开软件，进入界面
2.点击全部展开没有实现目标动作全部展开
3.点击全部关闭后
4.再次点击全部展开，这时可以实现目标动作

### What should have happened?(期望的结果)

刚进入软件，默认记住关闭时展开状态或点击全部展开时可以实现目标动作

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
最新版已经修复
