### ISSUE TITLE
希望增加连接目标机器cpu、内存等可视化界面状态

### ISSUE THREAD

**Issue by yang1yangyang** [electerm/electerm#3469]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

希望增加连接目标机器cpu、内存等可视化界面状态，
可以展示出当前目标机器目前cpu、内存、存储等使用情况，占用百分比信息

**Comment by zxdong262** [comment]
可以试试右下角的信息图标

**Comment by yang1yangyang** [comment]
谢谢
