### ISSUE TITLE
希望KeyboardInteractive 能像password有个一样的预填框

### ISSUE THREAD

**Issue by Ecalose** [electerm/electerm#3475]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

最近有台机它的认证方式是KeyboardInteractive ，每次都需要连进去后输答案，所以能否给KeyboardInteractive 也加个预填，用户可以选择提前预填好几个问题的答案

**Comment by zxdong262** [comment]
有道理，将在下个版本加入，感谢反馈

**Comment by Ecalose** [comment]
> 有道理，将在下个版本加入，感谢反馈

十分感谢
