### ISSUE TITLE
最新版本1.39.46 打开书签分组报错，1.39.35没有问题

### ISSUE THREAD

**Issue by qinci** [electerm/electerm#3478]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.39.46.dmg

### Platform detail (平台详情)

 mac os x64

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/electerm/electerm/assets/16683610/6eb949ee-f417-4fd4-9de9-27bc341f4f4a)

### What should have happened?(期望的结果)

正常打开书签分组

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
