### ISSUE TITLE
书签栏能够使用等宽字体的设置项

### ISSUE THREAD

**Issue by buzzybee-cc** [electerm/electerm#3491]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

现在书签中的英文不是等宽字体，看起来很丑，如图BJ比CS的宽度窄
![微信图片_20240630085959](https://github.com/electerm/electerm/assets/102048573/6e21e3c5-6a3a-4c44-af92-60f50e0e3a5f)

**Comment by zxdong262** [comment]
可以通过自定义css设置来改变字体
![Screen Shot 2024-06-30 at 19 30 24](https://github.com/electerm/electerm/assets/1641949/22ea0e81-7e93-4573-ac62-50a4e3a1e862)
