### ISSUE TITLE
“退出前确认”对系统标题栏不生效

### ISSUE THREAD

**Issue by HiddenTesla** [electerm/electerm#3501]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64.tar.gz

### Platform detail (平台详情)

Windows 10

### What steps will reproduce the bug?(重新问题的详细步骤)

打开“设置”窗口， 将“使用系统标题栏”和“退出前确认”开启， 它们变成蓝底白字状态。
开启多个标签。
点击系统的（而不是typescript做的）退出按钮。
![image](https://github.com/electerm/electerm/assets/18553210/810f3adc-5990-4bdb-a1a0-9ef94d65faad
![image](https://github.com/electerm/electerm/assets/18553210/e21590ac-b447-4996-a923-c50804b4891c)
)

### What should have happened?(期望的结果)

期望有弹框提示是否要关闭所有的标签。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

该问题是纯粹的本软件UX，与ssh无关，因此无所谓其他同类软件。

### Additional information(其他任何相关信息)

如果将“使用系统标题栏”关闭， 则退出前会有弹窗提示。

**Comment by zxdong262** [comment]
请问是最新版吗，我试了最新版没有复现问题

**Comment by HiddenTesla** [comment]
1.34.68 （提这个issue时的最新版）是能复现这个问题的。
这里说的是**系统标题栏**上的关闭按钮不受**退出前确认**的影响，**里层**的关闭按钮是受它控制的。

**Comment by zxdong262** [comment]
> 1.34.68 （提这个issue时的最新版）是能复现这个问题的。 这里说的是**系统标题栏**上的关闭按钮不受**退出前确认**的影响，**里层**的关闭按钮是受它控制的。

1.39.76 复现不了这个问题

**Comment by HiddenTesla** [comment]
自动更新一直在0%， 有log能看看为啥吗
![image](https://github.com/user-attachments/assets/42649d42-d0c8-4ea7-a166-6edd1edc90ee)

**Comment by zxdong262** [comment]
> 自动更新一直在0%， 有log能看看为啥吗 ![image](https://private-user-images.githubusercontent.com/18553210/351162336-42649d42-d0c8-4ea7-a166-6edd1edc90ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDI2NTgsIm5iZiI6MTcyMTcwMjM1OCwicGF0aCI6Ii8xODU1MzIxMC8zNTExNjIzMzYtNDI2NDlkNDItZDBjOC00ZWE3LWExNjYtNmVkZDFlZGM5MGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAyMzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYzNhNmZlOTE4NTI1ZTkzMzcwM2RlODAyYmUyMWIxYWZmNmQ3NGVhM2RhZTBjM2YzMDNjMWIwNjM0ODFhYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WpsPx9mpa4KbXfENshpUi5BNgFpbjknPrmPyno58o7w)

可以在设置里设置一个代理，这样更新就通过代理更新

**Comment by HiddenTesla** [comment]
emm 不太可能是代理的问题， 我在公司可以直连github。

**Comment by HiddenTesla** [comment]
验证1.39.103 已修复该问题。感谢。
