### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by JFallen** [electerm/electerm#3503]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

搜索的时候，如果没有展开菜单栏，就不能展开了，需要去掉搜索，重新展开之后，才能张开。
希望可以搜素的时候能自动展开菜单栏

**Comment by zxdong262** [comment]
可以截图看看菜单栏是哪里吗？

**Comment by JFallen** [comment]
![recording](https://github.com/user-attachments/assets/8de33b30-a857-44b1-b384-5bbd39e22669)
就是这里终端书签这里的搜素

**Comment by JFallen** [comment]
期待再来一个打开软件需要密码。
然后excle能进行会话导入导出。

**Comment by zxdong262** [comment]
设置里可以设置登录密码，这样打开就需要密码了
