### ISSUE TITLE
布局显示重复

### ISSUE THREAD

**Issue by JFallen** [electerm/electerm#3504]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

![image](https://github.com/user-attachments/assets/8779e411-725e-4c01-8e0b-f3ab0d63e964)
当左侧的BookMarks固定，底下的快捷命令固定，就会挡住
而且底下的快捷命令希望也可以自由拉缩

**Comment by zxdong262** [comment]
请问什么什么版本？操作系统？

**Comment by JFallen** [comment]
Windows 11 家庭中文版 23H2
electerm-1.39.68

**Comment by JFallen** [comment]
> 请问什么什么版本？操作系统？
Windows 11 家庭中文版 23H2
electerm-1.39.68

**Comment by zxdong262** [comment]
oh这是在线demo啊，实际下载的程序不会有这个问题

**Comment by zxdong262** [comment]
至少我试了没有复现，可能我操作的顺序不对？方便的话可以详细描述复现步骤吗？

**Comment by JFallen** [comment]
就是固定书签，然后快速命令再点快速命令
![image](https://github.com/user-attachments/assets/f8f567f3-6371-4de9-863f-4209a70d6daa)

**Comment by zxdong262** [comment]
我知道了，拖拽之后，不是原始宽度了，感谢反馈，将在下个版本修复
