### ISSUE TITLE
Activities 功能优化建议

### ISSUE THREAD

**Issue by zyzhang15** [electerm/electerm#3506]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

1. 建议去除 “Copy”按钮，或者优化交互方式，目前的交互，当鼠标经过时 弹出“Copy”按钮，比较突兀，建议不要鼠标复制功能或者点击即复制功能；
2. 建议将 Activities列表的列表窗口高度，设计为可以拖动调整，从而可以同时看到更多行数据，同时每一行建议不要太高，可以更紧凑些，可以看到更多数据行；
3. 建议优化cmd 列的显示，比如不要换行，或者过长时候优化显示逻辑，如下图，当命令行太长时候，一行进程信息会特别高，页面都占满了；
4. 建议每一列宽度自适应方面优化，例如下图，内存列换行了，观感不好。

最近用了两月有余，觉得electerm 很新颖，有很多特别好用的点，希望越来越好！

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/400a8dc3-0548-4aa8-bc94-0643e0f6d12d">

**Comment by zxdong262** [comment]
感谢反馈，将在后续版本优化

**Comment by zxdong262** [comment]
> 目前最新版本优化之后，显示效果不太理想(版本：1.39.88)
> 
> <img alt="企业微信截图_b8b3e23e-f26b-45c9-88d5-c20668e4cc39" width="1007" src="https://private-user-images.githubusercontent.com/16697756/351211746-3d00a272-a8fa-4068-9ee4-66c49bca9002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjIxODgsIm5iZiI6MTcyMTcyMTg4OCwicGF0aCI6Ii8xNjY5Nzc1Ni8zNTEyMTE3NDYtM2QwMGEyNzItYThmYS00MDY4LTllZTQtNjZjNDliY2E5MDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA4MDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMWZiN2EwMzhhMTU2YTJhMGE2NDE0MzhhYzM0NGI1YzhkY2YxYWY0Yjc1ODk3YWMzYzM5NTM4YTA2YjlhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5V3kJDRpHQVAA0yEQDU93qJ4i0qVgbGS6C8EjXP6bE">
感谢反馈，将在下个版本优化
