### ISSUE TITLE
书签栏不要固定大小

### ISSUE THREAD

**Issue by JFallen** [electerm/electerm#3507]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

希望书签栏不要固定大小，可以自己随意拖动大小
现在这个尺度已经是最小了，希望可以更小一点
![image](https://github.com/user-attachments/assets/92515652-7459-4f3e-ae5d-d23560a6aac1)

快速命令固定之后，也希望可以自己调整大小
![image](https://github.com/user-attachments/assets/32febf31-7f60-446c-83d8-43dd9b2d8b42)

批量输入不用隐藏起来。
每次使用都需要鼠标移动到批量输入，然后再把鼠标移到 全部终端执行，很麻烦
![image](https://github.com/user-attachments/assets/e1c03605-2cac-4093-93b4-678905fb308b)

**Comment by zxdong262** [comment]
侧边栏可以拖动，鼠标需要移动到合适位置，你试试

**Comment by JFallen** [comment]
试过了不行，侧边栏只能移动到这么小的，再小就不行了
![recording](https://github.com/user-attachments/assets/d0abd0a7-d848-455e-9d6a-98f5b9a5b996)


> 侧边栏可以拖动，鼠标需要移动到合适位置，你试试
