### ISSUE TITLE
Let user select what data to sync

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#3514]
Hello,

would it be possible to build the sync so that I can provide bookmarks and bookmark groups for all users, but everything else remains assigned to the user. The point is that I would like to use electorm in a larger team so that everyone has all the connections in electorm that we use

_Originally posted by @mcordes92 in https://github.com/electerm/electerm/discussions/3512_

**Comment by mcordes92** [comment]
I saw that they integrated this function in the latest release, now I have a question about it:

If user1 creates a connection and stores their profile there and it is then synced, then the profile ID is transmitted

If user2 then retrieves the data again, then a profile ID is stored in the connection that does not exist for user2.

The background is that I want to synchronize the same connections for several users, but every user should also be able to use their profile if possible

**Comment by zxdong262** [comment]
I see, currently, profile is part of bookmark, would make profile standalone in next release

**Comment by mcordes92** [comment]
I don't mean the selection of what should be synced, but when I look at the JSON that arrives at the sync server, the ProfileID is stored in the object of a connection, which the user can specify when creating a connection.

If User1 creates the connection with his profile and this is then synced, User2 cannot use the connection because a different profile is stored there.

**Comment by zxdong262** [comment]
> I don't mean the selection of what should be synced, but when I look at the JSON that arrives at the sync server, the ProfileID is stored in the object of a connection, which the user can specify when creating a connection.
> 
> If User1 creates the connection with his profile and this is then synced, User2 cannot use the connection because a different profile is stored there.

How about the default profile has same id: default or need more profile, then we need a feature that user could edit id

**Comment by mcordes92** [comment]
> How about the default profile has same id: default or need more profile, then we need a feature that user could edit id

The standard profile is good and would be a great feature if it were included.

The other idea that comes to mind would be a new settings screen (site) where the user can specify which profile should be used for which connection. So that every user can generally specify this themselves.
