### ISSUE TITLE
记住「SFTP路径与终端同步」开关状态

### ISSUE THREAD

**Issue by QPYIDRWIMG** [electerm/electerm#3524]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

每次重启 electerm，都要点击标签页旁边的回形针按钮才能启用「SFTP路径与终端同步」功能，有点麻烦，希望可以新增一项功能，用来记住「SFTP路径与终端同步」开关状态

**Comment by zxdong262** [comment]
新版本已经加入设置
