### ISSUE TITLE
什么时候能能够解决windows下sftp无法删除文件夹的问题

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3535]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.88-win-x64-installer.exe

### Platform detail (平台详情)

windows 7/8/10/11

### What steps will reproduce the bug?(重新问题的详细步骤)

![image](https://github.com/user-attachments/assets/4cf19087-7a03-48f6-a676-a448f2cc2887)
无法删除文件夹，上传文件没有问题，但直接sftp里新建一个文件也不行，由于windows下的cifs容易被攻击，公司的windows服务器现在都用sftp在维护，希望electerm能早日良好兼容windows下的sftp.

### What should have happened?(期望的结果)

希望electerm能早日良好兼容windows下的sftp.

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本支持
