### ISSUE TITLE
[BUG]打开的连接超过一定数量后，有两个问题：1、向左向右的按钮是失效无法使用的，无法切换到后面的连接。2、下拉切换连接的时候，后面的连接标签无法显示出来。

### ISSUE THREAD

**Issue by 9653865** [electerm/electerm#3536]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.88-win-x64-installer.exe

### Platform detail (平台详情)

windows 10 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

[BUG]打开的连接超过一定数量后，有两个问题：
1、向左向右的按钮是失效无法使用的，无法切换到后面的连接。
2、下拉切换连接的时候，后面的连接标签无法显示出来。

### What should have happened?(期望的结果)

当打开比较多连接的时候，连接标签管理需要能正常切换 和显示 。

**Comment by 9653865** [comment]
![微信图片_20240802085744](https://github.com/user-attachments/assets/f3bd1c3c-8b56-46a7-bbbd-a0809699c712)

**Comment by zxdong262** [comment]
新版本已修复，感谢反馈

**Comment by 9653865** [comment]
@zxdong262 我下载安装了最新的版本1.39.99，发现该问题并没有解决呀，与我之前反馈的问题没有任何变化 。
是不是我没有描述清楚问题？我再详细描述一下：
1、当连接打开到一定数量，大概十来个吧，最上端的连接标签，就无法通过向右或者向左来切换到需要的连接标签上（最上方的连接标签没有变化，实际连接是切到新连接上了），例如，我一共打开了15个连接，那可能只能看到10个连接标签，另外5个显示不出来。
2、最右边的下拉连接标签按钮，下拉后可以出现所有的连接 ，但是由于最上方的连接标签无法变动，所以通过下拉切换连接 ，最上方的连接 标签也无法显示出来。这一点很重要，需要知道当然连接是哪个。

这个功能对我很重要，因为管理的机器会比较多，同时打开的连接也就多。

**Comment by zxdong262** [comment]
确实没有解决，我看看咋回事，将在下个版本修复

**Comment by zxdong262** [comment]
我试了，不使用系统标题栏时候是正常的，你那里是不是也是这样？

**Comment by 9653865** [comment]
> 我试了，不使用系统标题栏时候是正常的，你那里是不是也是这样？
的确是的，不用系统标题栏可以正常切换，不好意思，给您添麻烦了。
