### ISSUE TITLE
访问历史建议

### ISSUE THREAD

**Issue by sunchunfeng** [electerm/electerm#3541]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

<img width="339" alt="image" src="https://github.com/user-attachments/assets/7c50e60c-8139-484c-a57b-59918716be43">
您好，如图，每次重新打开软件上一次的访问历史都会重新计算存储为本次软件重启后的记录，本地之前打开的访问历史，列表中都找不到了。建议开发者能不能加上之前的软件打开记录的访问历史，并且访问历史做下访问次数的越多，越靠前的排序。方便每次打开访问历史便于快速找到访问频次高的服务器，快速打开。

**Comment by zxdong262** [comment]
感谢反馈,将在下个版本优化

**Comment by sunchunfeng** [comment]
感谢采纳，期待 Electrm 不断进步，未来更加辉煌。
