### ISSUE TITLE
监控服务器的资源(CPU/RAM/Network/disk/...) 使用情况

### ISSUE THREAD

**Issue by shanon00** [electerm/electerm#3544]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Many times, we like to have a status bar to check the resources of the server.  
![image](https://github.com/user-attachments/assets/8f0c6670-14d1-4cd3-b64e-ccbdecc148eb), It's a bit like MobaXterm.

**Comment by zxdong262** [comment]
Did you try the info icon in right bottom?

**Comment by shanon00** [comment]
Hahahah😂, I think I found this cutie, and I may use it for a while. Thanks for your reply.
