### ISSUE TITLE
Mass deletion of bookmarks

### ISSUE THREAD

**Issue by mbzik** [electerm/electerm#3545]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Thanks again for your product, it makes life very easy. Faced with this aspect of work when deleting bookmarks, as I think it would be very convenient if there was a possibility to delete them in bulk. Or add an option when deleting a section, also give the option to choose to delete along with the bookmarks inside and after the user chooses to delete them. Thanks again for your product

**Comment by zxdong262** [comment]
Click thed edit icon on top of bookmarks edit panel, would show multi select tree

**Comment by mbzik** [comment]
Yeah, that's what I wanted. Thank you so much for your help!
