### ISSUE TITLE
1.39.99的版本中删除所有变成递归删除了，而且完全没有提示，可以再加一个清空目录的功能吗，否则目录太深删除太慢了

### ISSUE THREAD

**Issue by LuoSven** [electerm/electerm#3555]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

1.39.99的版本中删除所有变成递归删除了，而且完全没有提示，可以再加一个清空目录的功能吗，否则目录太深删除太慢了

**Comment by zxdong262** [comment]
有道理，感谢反馈，之前是用rm-rf会很快，为了兼容windows服务器考虑改为递归删除，下个版本会先尝试rm-rf失败了，再尝试递归

**Comment by LuoSven** [comment]
等你加，原来这个就不用改了，我主要是清空目录，发布用
