### ISSUE TITLE
希望可以添加“打开多个tab页时，某个tab如果有新的输出，可以高亮闪一下，或者tab页标签变色”

### ISSUE THREAD

**Issue by Wjt11** [electerm/electerm#3556]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

打开多个tab页时，某个tab如果有新的输出，可以高亮闪一下，或者tab页标签变色，直到打开这个标签页，才恢复原样。

**Comment by zxdong262** [comment]
目前有输出时候会有一个绿色#闪烁

**Comment by Wjt11** [comment]
现在的现象是在A标签（A标签、B标签是同一台服务器）中tail -f 某日志，然后去B标签中操作，让A标签输出日志，这个绿色#不闪烁。只有我点过去A标签，在点到B标签，A的#才会闪烁，如果A标签继续输出日志然而我当前在B标签，那么A标签的#并不会闪烁。（不好意思，描述的有点啰嗦了）

**Comment by zxdong262** [comment]
明白了，感谢反馈，将在下个版本修复

**Comment by zxdong262** [comment]
忘记了，推迟到下个版本 @Wjt11

**Comment by Wjt11** [comment]
ok，没问题
