### ISSUE TITLE
windows下的sftp彻底不能用了

### ISSUE THREAD

**Issue by etanman** [electerm/electerm#3558]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.103-win-x64-installer.exe

### Platform detail (平台详情)

windows 7/8/10/11

### What steps will reproduce the bug?(重新问题的详细步骤)

![1723970125902](https://github.com/user-attachments/assets/d35ca420-9764-4c00-b697-d1a908d14891)
看前面作者说已经解决windows下sftp无法删除文件夹和新建文件的问题，但今天试了一下，sftp连文件列表下无法出现了。

### What should have happened?(期望的结果)

请作者再检查一下

**Comment by zxdong262** [comment]
可以试试地址栏输入正确地址回车吗

**Comment by zxdong262** [comment]
或者书签设置一个远程开始路径试试行不行

**Comment by etanman** [comment]
> 可以试试地址栏输入正确地址回车吗
地址栏输入\，的确可以了，以前是不需要的。

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by etanman** [comment]
> 可以试试最新版吗

感谢作者修复，没问题了，关于sftp列表速度还需要进一步优化，现在虽然比以前速度快了不少，不知道是不是与软件架构有关，跟windterm那种流畅的反应速度还是有着很大差距。
