### ISSUE TITLE
1.39.99版本，配置导出按钮点击无反应

### ISSUE THREAD

**Issue by darkknightxb** [electerm/electerm#3562]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.99-win-x64-portable.tar.gz

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

如题

### What should have happened?(期望的结果)

导出配置信息

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
