### ISSUE TITLE
"SFTP路径与终端同步"功能异常回显

### ISSUE THREAD

**Issue by milkbrother666** [electerm/electerm#3563]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.99-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.20348.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

打开"SFTP路径与终端同步"后，终端会出现异常回显`echo "=__+__$PWD"`，不管是本地还是远程终端。
实测最新版本1.39.103也存在此bug。
![electerm_bug](https://github.com/user-attachments/assets/51eb87ab-4541-4922-bfed-a9289c78ac31)

### What should have happened?(期望的结果)

bug修复，功能正常使用。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

未重现

**Comment by zxdong262** [comment]
已知问题，这个功能是实验性质的，存在固有缺陷，发现任何问题关闭即可
