### ISSUE TITLE
SFTP privilege increase

### ISSUE THREAD

**Issue by mbzik** [electerm/electerm#3567]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Add the ability to elevate privileges to sudo on SFTP connections to be able to edit/read files. Is it possible to do this or is it technically impossible because of the library that is used to set up sftp connections?

Perhaps this functionality already exists, but I haven't found it. Can someone suggest it? 
![image](https://github.com/user-attachments/assets/c33ed04f-d211-40ca-ab5a-8a65907185df)

**Comment by zxdong262** [comment]
Currently I have no idea how to do it

**Comment by mbzik** [comment]
I haven't found a solution on how to implement this either. Thank you for your reply.
