### ISSUE TITLE
Profiles should be encrypted

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#3573]
Hello!
There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.

_Originally posted by @AASabancev in https://github.com/electerm/electerm/discussions/3570_

**Comment by emoxam** [comment]
> Hello! There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.
> 
> _Originally posted by [@AASabancev](https://github.com/AASabancev) in [#3570](https://github.com/electerm/electerm/discussions/3570)_

Where did you find "encryption of bookmarks using password"  option?

**Comment by zxdong262** [comment]
Thank you for the feedback, you are right, keys should be encrypted too, would update in next release

> > Hello! There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.
> > _Originally posted by [@AASabancev](https://github.com/AASabancev) in [#3570](https://github.com/electerm/electerm/discussions/3570)_
> 
> Where did you find "encryption of bookmarks using password" option?

**Comment by emoxam** [comment]
> Thank you for the feedback, you are right, keys should be encrypted too, would update in next release
> 
> > > Hello! There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.
> > > _Originally posted by [@AASabancev](https://github.com/AASabancev) in [#3570](https://github.com/electerm/electerm/discussions/3570)_
> > 
> > 
> > Where did you find "encryption of bookmarks using password" option?

Thanks! But i don't understand what option we are talking about?) Is there any master password that encrypts the data ?

**Comment by zxdong262** [comment]
> > Thank you for the feedback, you are right, keys should be encrypted too, would update in next release
> > > > Hello! There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.
> > > > _Originally posted by [@AASabancev](https://github.com/AASabancev) in [#3570](https://github.com/electerm/electerm/discussions/3570)_
> > > 
> > > 
> > > Where did you find "encryption of bookmarks using password" option?
> 
> Thanks! But i don't understand what option we are talking about?) Is there any master password that encrypts the data ?

In data sync, there is a password input, optional, when set, the data would be encrypted and upload the sync server, the profile already encrypted when password set, I forget about it

**Comment by emoxam** [comment]
> > > Thank you for the feedback, you are right, keys should be encrypted too, would update in next release
> > > > > Hello! There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.
> > > > > _Originally posted by [@AASabancev](https://github.com/AASabancev) in [#3570](https://github.com/electerm/electerm/discussions/3570)_
> > > > 
> > > > 
> > > > Where did you find "encryption of bookmarks using password" option?
> > 
> > 
> > Thanks! But i don't understand what option we are talking about?) Is there any master password that encrypts the data ?
> 
> In data sync, there is a password input, optional, when set, the data would be encrypted and upload the sync server, the profile already encrypted when password set, I forget about it

I want encrypt but i don't want to upload it anywhere, should i set password? How can i check that data is encrypted ?

**Comment by zxdong262** [comment]
> > > > Thank you for the feedback, you are right, keys should be encrypted too, would update in next release
> > > > > > Hello! There is now encryption of bookmarks using password, however, encryption does not work on profiles. And in profiles private keys are saved in open form. I think it is important to enable encryption of profiles with the same password.
> > > > > > _Originally posted by [@AASabancev](https://github.com/AASabancev) in [#3570](https://github.com/electerm/electerm/discussions/3570)_
> > > > > 
> > > > > 
> > > > > Where did you find "encryption of bookmarks using password" option?
> > > 
> > > 
> > > Thanks! But i don't understand what option we are talking about?) Is there any master password that encrypts the data ?
> > 
> > 
> > In data sync, there is a password input, optional, when set, the data would be encrypted and upload the sync server, the profile already encrypted when password set, I forget about it
> 
> I want encrypt but i don't want to upload it anywhere, should i set password? How can i check that data is encrypted ?

No that option yet, think about this: any private key in ~/.ssh is not encrypted, do you worry about its safety?

**Comment by emoxam** [comment]
> do you worry about its safety?

I didn't think about it..
