### ISSUE TITLE
Import/Export syntax highlights

### ISSUE THREAD

**Issue by mbzik** [electerm/electerm#3574]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Add the ability to import/export syntax highlights separately, not the whole thing with all settings. Sometimes there are situations when I want to share customizations with my friend, but only in terms of syntax.

**Comment by zxdong262** [comment]
Great idea!

**Comment by zxdong262** [comment]
Would be in next release

**Comment by mbzik** [comment]
Great! Thanks!
