### ISSUE TITLE
Mac M1 快速命令无法搜索

### ISSUE THREAD

**Issue by tianyunperfect** [electerm/electerm#3579]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.109-mac-arm64.dmg

### Platform detail (平台详情)

mac os(ARM or x64)

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="677" alt="image" src="https://github.com/user-attachments/assets/7542722f-1baf-4d7d-ad7c-986a7681c336">
设置页面，快速排序无法搜索，无法输入任何内容！！！

### What should have happened?(期望的结果)

期望输入后，应该可以模糊筛选。

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
