### ISSUE TITLE
服务器的/tmp目录中存在一个巨大的压缩包，是什么情况

### ISSUE THREAD

**Issue by h4dmKatiePatter1lwedson** [electerm/electerm#3584]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.38.11

### Platform detail (平台详情)

win10

### What steps will reproduce the bug?(重新问题的详细步骤)

[root@eos1 tmp]# ll -h
total 49G
-rw-r--r--. 1 root root 49G Aug 27 10:02 electerm-aHfKW8N.tar

### What should have happened?(期望的结果)

我不知道这是什么用途的文件，想知道这是干嘛用的，是否与数据安全有关

**Comment by zxdong262** [comment]
当上传文件夹时候会先打包成压缩包，然后上传，在服务器端解压缩

**Comment by zxdong262** [comment]
最新版本中应该会检查文件夹大小，太大的就拒绝上传了
