### ISSUE TITLE
建议增加田字形式的分屏

### ISSUE THREAD

**Issue by xshqhua** [electerm/electerm#3593]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

只有水平和垂直分屏需要打开多个终端是，希望同时支持水平和垂直。
![image](https://github.com/user-attachments/assets/2989eabe-445e-4c05-88ee-d8bcad7c9353)
类似于这种

**Comment by zxdong262** [comment]
将在后续版本加入

**Comment by zxdong262** [comment]
最新版已经加入
