### ISSUE TITLE
无法正确下载文件夹名字带空格的文件夹

### ISSUE THREAD

**Issue by Seraphli** [electerm/electerm#3619]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.40.6

### Platform detail (平台详情)

Linux 6.9.12-3-MANJARO GNU/Linux

### What steps will reproduce the bug?(重新问题的详细步骤)

无法正确下载 远程主机 文件夹名字带空格的文件夹
比如我在远程建了文件夹叫`llama3.1 405b`
点击下载之后会提示一下然后就消失了，进度里显示下载完成，但实际是下载没有成功

### What should have happened?(期望的结果)

正常下载

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
