### ISSUE TITLE
[Featrue Request] 希望能记住且全局应用Zoomin/Zoomout设置

### ISSUE THREAD

**Issue by chuwza** [electerm/electerm#3628]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

开发者你好，目前的放大缩小区间太大，不好用，而且我只希望放大缩小终端画面（因为系统界面的大小正合适）。所以我用Zoomin/Zoomout来调节终端画面到合适位置，但是好不容易调整到舒服大小，新打开另一个SSH会话，发现没有全局应用；这时关掉Electerm再打开，发现刚才调半天的大小又恢复成默认的尺寸了😂😥（这里要说一下，默认的终端视图大小真的偏大，对比一下Tabby和Termius就可以看到，默认的视图不舒服）
![屏幕截图 2024-10-11 213737](https://github.com/user-attachments/assets/1dc80300-209c-4084-ba70-4cd21baecdd1)

在不调整目前的默认视图的情况下，希望能添加选项：记住且全局应用Zoomin/Zoomout设置。这样就可以把终端视图调节到自己觉得舒服的大小了

**Comment by zxdong262** [comment]
终端设置里可以设置字体大小，试试这个？

**Comment by chuwza** [comment]
> 终端设置里可以设置字体大小，试试这个？

这样可以满足我的需求，非常感谢大佬！👍
