### ISSUE TITLE
在某些Linux系统下sftp异常

### ISSUE THREAD

**Issue by nikelius** [electerm/electerm#3630]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.40.16-win-x64

### Platform detail (平台详情)

windows 11 （版本：23H2，内部版本：22631.4317）

### What steps will reproduce the bug?(重新问题的详细步骤)

在Windows环境中使用 electerm 连 CentOS-7.9 服务器——ssh成功，但sftp异常。
服务器版本：Linux pm-119 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
异常信息：Packet length 589325167 exceeds max length of 262144
Error: Packet length 589325167 exceeds max length of 262144 
at http://127.0.0.1:30975/js/electerm-1.40.16.js:101:16154 
at Object.resolve (http://127.0.0.1:30975/js/electerm-1.40.16.js:61:5472) 
at Worker._x (http://127.0.0.1:30975/js/electerm-1.40.16.js:61:6364)
补充：electerm 是从windows的mircrosoft store中安装的。

### What should have happened?(期望的结果)

能正常使用sftp功能。

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

在SecureCRT中能正常使用ssh和sftp功能。

### Additional information(其他任何相关信息)

补充：错误信息截图如下：
![image](https://github.com/user-attachments/assets/e33d4c38-3d79-4545-bad3-b5cf4fc22958)

_No response_

**Comment by nikelius** [comment]
补充：错误信息截图如下：
![8f4e6712e5901849891083969478f3d](https://github.com/user-attachments/assets/805ab6d0-a3e4-48a3-9631-431960db3242)

**Comment by zxdong262** [comment]
可以参考下这个 https://github.com/electerm/electerm/issues/3413#issuecomment-2104459513

**Comment by nikelius** [comment]
修改目标主机的.bashrc文件，删除所有涉及控制台输出的命令，再使用sftp就正常了。
