### ISSUE TITLE
建议用dockview改写分屏

### ISSUE THREAD

**Issue by mankeheaven** [electerm/electerm#3639]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

看了一下现在的分屏有挺多issue的，先前我做分屏的时候来你这看看思路的，不过没找到。
然后我找到了dockview，花了一个星期总算把我做的软件改成了分屏。
给你看看效果。当然我这个是不开源的。

![image](https://github.com/user-attachments/assets/c61881d9-25f7-4117-a25e-f7d1af7d31d8)

**Comment by zxdong262** [comment]
目前在重写，会提供类似vscode的分屏，不会使用外部依赖，可能还需要一段时间

**Comment by zxdong262** [comment]
最新版已经加入分屏
