### ISSUE TITLE
希望web连接可以直接在软件上打开url，而不用跳转到默认的浏览器（chrome）

### ISSUE THREAD

**Issue by xingyuezhiji** [electerm/electerm#3650]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

相当于是一个浏览器的功能了

**Comment by zxdong262** [comment]
最新版已经加入

**Comment by xingyuezhiji** [comment]
> 最新版已经加入

感谢支持，我看快速命令在web连接上还不可以直接使用，这里支持适配吗

**Comment by zxdong262** [comment]
> > 最新版已经加入
> 
> 感谢支持，我看快速命令在web连接上还不可以直接使用，这里支持适配吗

可以详细描述一下快速命令在web连接上怎么直接使用吗

**Comment by xingyuezhiji** [comment]
> > > 最新版已经加入
> > 
> > 
> > 感谢支持，我看快速命令在web连接上还不可以直接使用，这里支持适配吗
> 
> 可以详细描述一下快速命令在web连接上怎么直接使用吗

就是类似ssh连接的快速命令一样，我点击之后，就可以快速输入命令到网页上（我用web连接打开的网页也是一个ssh连接的页面）
<img width="845" alt="image" src="https://github.com/user-attachments/assets/b82c32a3-7f8a-4849-bb34-83094a953e86">
