### ISSUE TITLE
“粘贴选择内容/粘贴所选内容”功能添加到右键菜单中

### ISSUE THREAD

**Issue by Hoshiya233** [electerm/electerm#3654]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

这个功能特别实用，提高了好几倍工作效率，但是入口有点难找，我是搜索了issue才知道有这个功能的

比较顺手的操作应该是鼠标选中一段内容，右键，粘贴到终端，所以我觉得特别有必要放到右键菜单里
![image](https://github.com/user-attachments/assets/65cbc175-4cd2-4ac0-9bfe-096bd5344ec2)

虽然【选中后自动复制到剪贴板，右键自动粘贴】也能实现，但是这样会让大量的临时文本污染OS的剪贴板历史记录，自从有了win+v剪贴板历史记录以后，这种操作已经不实用了

**Comment by zxdong262** [comment]
有道理，将在后续版本加入

**Comment by zxdong262** [comment]
最新版已经加入
