### ISSUE TITLE
Bulk input

### ISSUE THREAD

**Issue by mbzik** [electerm/electerm#3661]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

Bulk input is also one of the features I use constantly. I would like to add the ability to choose in which of the currently open tabs to execute commands. Sometimes I forget to close some tabs and end up executing commands in them as well.

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本加入

**Comment by zxdong262** [comment]
最新版已经加入
