### ISSUE TITLE
1.50.21 建议

### ISSUE THREAD

**Issue by younglabfun** [electerm/electerm#3666]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

把分屏功能弄回来吧！
ctrl+/快捷键貌似无效
用终端的用户都有自己的操作习惯，升级不要减功能，完善就好，这个版本的同屏多开窗口不是太习惯。

**Comment by zxdong262** [comment]
感谢反馈，忘记了，下个版本ctrl/meta+/将复制当前连接到下一个分屏

**Comment by zxdong262** [comment]
最新版已经部署ctrl/meta+/将复制当前连接到下一个分屏
