### ISSUE TITLE
The build for MAC ARM failed

### ISSUE THREAD

**Issue by TomasNovo** [electerm/electerm#3684]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.50.40-mac-arm64.dmg

### Platform detail (平台详情)

mac os 14.7.1 - M1 Pro

### What steps will reproduce the bug?(重新问题的详细步骤)

I've updated Electerm. Now, when I press to open Electerm, I get an error

### What should have happened?(期望的结果)

Electerm should open without errors

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

No

### Additional information(其他任何相关信息)

![image](https://github.com/user-attachments/assets/163707cc-f53b-40d5-8c45-565c0e6eb93b)

**Comment by Xiaofufufu** [comment]
I just updated and got the same error

Uncaught Exception:
Error: dlopen(/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4, 0x0001): tried: '/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' (code signature in <28752521-7D1F-3A33-84D9-B86517FFC6EC> '/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' (no such file), '/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' (code signature in <28752521-7D1F-3A33-84D9-B86517FFC6EC> '/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' (code signature in <28752521-7D1F-3A33-84D9-B86517FFC6EC> '/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' (no such file), '/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' (code signature in <28752521-7D1F-3A33-84D9-B86517FFC6EC> '/private/var/folders/pd/0f1sqr6n64lc_s6tp5_87wxw0000gn/T/.org.electerm.electerm.UNKZZ4' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at node:internal/modules/cjs/loader:967:12
at Function._load (node:electron/js2c/asar_bundle:2:13327)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:110:18)
at load (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)
at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/electron-app-universal-protocol-client/dist/bindings.js:3:53)

**Comment by TomasNovo** [comment]
But now using older versions does not work for me as well

**Comment by zxdong262** [comment]
The build for mac arm failed, trying to fix it...currently no luck

**Comment by TomasNovo** [comment]
hey @zxdong262 , is there a way to install an older version that is working? The old versions I tried produce a similar error

**Comment by wujunfeng1991** [comment]
same error.

> ### Electerm Version and download file extension(Electerm版本和下载文件后缀)
> electerm-1.50.40-mac-arm64.dmg
> 
> ### Platform detail (平台详情)
> mac os 14.7.1 - M1 Pro
> 
> ### What steps will reproduce the bug?(重新问题的详细步骤)
> I've updated Electerm. Now, when I press to open Electerm, I get an error
> 
> ### What should have happened?(期望的结果)
> Electerm should open without errors
> 
> ### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)
> No
> 
> ### Additional information(其他任何相关信息)
> ![image](https://private-user-images.githubusercontent.com/28056414/391952781-163707cc-f53b-40d5-8c45-565c0e6eb93b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODA0OTYsIm5iZiI6MTczMzI4MDE5NiwicGF0aCI6Ii8yODA1NjQxNC8zOTE5NTI3ODEtMTYzNzA3Y2MtZjUzYi00MGQ1LThjNDUtNTY1YzBlNmViOTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAyNDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMWU0NjMzYWQ3YzRiMThjMDlkZTZmMzQ4MGZhNjAxMGE1ODY2NDM3OGUxYWFkZGIwZTI4Njk2MGJjZDYwYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tFVOBXHcYb4hvErvvZnqjpEl5Z9-tpvTkz9Ra1LYjPU)

**Comment by longzl** [comment]
same error.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/releases/tag/v1.50.46 Fixed in latest release
