### ISSUE TITLE
【bug】ssh 密码保存的时候，会有js 错误提示

### ISSUE THREAD

**Issue by ferocknew** [electerm/electerm#3695]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.50.46-mac-arm64.dmg

### Platform detail (平台详情)

mac os(ARM）

### What steps will reproduce the bug?(重新问题的详细步骤)

<img width="279" alt="image" src="https://github.com/user-attachments/assets/614944b3-553f-421f-8f19-02e29b18dbb7">

### What should have happened?(期望的结果)

不弹出提示

**Comment by zxdong262** [comment]
最新版已经修复

**Comment by ferocknew** [comment]
辛苦了
