### ISSUE TITLE
Illogical ssh-jump settings

### ISSUE THREAD

**Issue by mbzik** [electerm/electerm#3701]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.50.59-win-x64-installer.exe

### Platform detail (平台详情)

Microsoft Windows NT 10.0.22631.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

Set up a connection through SSH-jump. Specify address A as the address in the bookmark, and address B as the address in the "Connection Hopping" tab.

### What should have happened?(期望的结果)

The connection should be made to address B first and then to address A. Currently, it happens the other way around.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

In clients like SecureCRT, MobaXterm, and others, the connection to address B occurs first, followed by the connection to address A.

### Additional information(其他任何相关信息)

Thank you for developing and supporting your product!

The logic of configuring ssh-jump differs from all other clients, such as SecureCRT, MobaXterm, etc. The discrepancy lies in the fact that when creating a bookmark, the main address specified is the initial address, and further hops are configured in the "Connection Hopping" tab. According to the logic of all other clients, it should be the opposite. The address specified on the main tab when creating a connection should be the last in the chain, and the ssh jumps that need to be made before connecting to the main address. Because of this, there is an illogical display; if you have multiple connection addresses through a terminal server, it will appear as several different connections but all with the same name. There is a strong request to change the connection order so that the hops from "Connection Hopping" occur first, and then the connection to the main address from the bookmark takes place.

**Comment by zxdong262** [comment]
Thank you for the feedback, it make sense! Just need think a way to be compatible with user's old jump settings.

**Comment by zxdong262** [comment]
@mbzik Thank you for the support! Would update in next release

**Comment by mbzik** [comment]
> @mbzik Thank you for the support! Would update in next release

Thank you for your product and its development!

**Comment by zxdong262** [comment]
In latest release now
