### ISSUE TITLE
1.50.59版本无法使用rz

### ISSUE THREAD

**Issue by pengxinwen** [electerm/electerm#3704]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.50.59-win-x64-installer.exe

### Platform detail (平台详情)

windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

输入rz命令未弹窗windows的文件选择框

### What should have happened?(期望的结果)

老版本可以正常使用

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复
