### ISSUE TITLE
1.50.65版本多窗口条件下无法使用快速命令

### ISSUE THREAD

**Issue by Xiangxiang-M** [electerm/electerm#3707]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

设置多个快速命令后，使用三个不同窗口，点击快速命令在当前光标选中窗口无法执行

### What should have happened?(期望的结果)

多个窗口都可以使用快速命令

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

No

**Comment by zxdong262** [comment]
感谢反馈，已经在最新版修复 https://github.com/electerm/electerm/releases
