### ISSUE TITLE
快速命令失效

### ISSUE THREAD

**Issue by frankterm** [electerm/electerm#3710]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.50.65

### Platform detail (平台详情)

MacOS ARM 14.5

### What steps will reproduce the bug?(重新问题的详细步骤)

此版本快速命令点击没有效果

### What should have happened?(期望的结果)

快速命令能够起作用

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

electerm1.50.65会有这个问题，其他软件未注意

**Comment by zxdong262** [comment]
最新版修复了
