### ISSUE TITLE
快速命令失效

### ISSUE THREAD

**Issue by frankterm** [electerm/electerm#3711]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

1.50.65 mac book m2

### Platform detail (平台详情)

mac book m2 14.5

### What steps will reproduce the bug?(重新问题的详细步骤)

快速命令点击无效

### What should have happened?(期望的结果)

快速命令可用

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

不知道

### Additional information(其他任何相关信息)

原来是有效的。我记得提交过这个问题，没查到再提交一次

**Comment by zxdong262** [comment]
1.50.66版本修复了
