### ISSUE TITLE
1.50.66版本使用rz会卡住

### ISSUE THREAD

**Issue by thdwen** [electerm/electerm#3716]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.50.66-mac-arm64.dmg

### Platform detail (平台详情)

Darwin Mac-mini.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:51:37 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8112 arm64

### What steps will reproduce the bug?(重新问题的详细步骤)

使用rz下载一个13M左右大小的文件，进度条显示100%后会卡住。
<img width="627" alt="F3F9D7AD-1EC1-4E5E-86FB-7B7CA35B1D3F" src="https://github.com/user-attachments/assets/8a75e7c4-652c-4a91-a26d-4e5e76bec9cf" />

### What should have happened?(期望的结果)

正常使用lrzsz

**Comment by zxdong262** [comment]
可以试试提示里的trzsz，可靠很多

**Comment by thdwen** [comment]
> 可以试试提示里的trzsz，可靠很多

请问这种问题是lrzsz本身的问题，还是使用前端技术栈开发的软件都会有这种问题，我也使用过tabby，也有类似的问题

**Comment by zxdong262** [comment]
> > 可以试试提示里的trzsz，可靠很多
> 
> 请问这种问题是lrzsz本身的问题，还是使用前端技术栈开发的软件都会有这种问题，我也使用过tabby，也有类似的问题

tabby和electerm都是使用 zmodemjs , 我觉得这个轮子不够可靠, 虽然lrzsz本身也不完善
