### ISSUE TITLE
每次启动打开书签的顺序都是乱的

### ISSUE THREAD

**Issue by lvwshuai** [electerm/electerm#3729]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

v1.51.3

### Platform detail (平台详情)

mas OS Sequoia ARM 

### What steps will reproduce the bug?(重新问题的详细步骤)

退出electerm 重新启动打开，书签顺序就变乱了

### What should have happened?(期望的结果)

重启后书签顺序不要乱

**Comment by zxdong262** [comment]
感谢反馈，将在下个版本修复

**Comment by lvwshuai** [comment]
> 感谢反馈，将在下个版本修复

[v1.50.46] 之后的版本书签全是这个问题

**Comment by zxdong262** [comment]
最新版已经修复
