### ISSUE TITLE
出现一个书签无法修改、删除，卸载重装也无效

### ISSUE THREAD

**Issue by leic4u** [electerm/electerm#3733]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.51.8-win-x64.appx 微软商店版，猜测应该是 appx 的

### Platform detail (平台详情)

windows 11 微软商店版

### What steps will reproduce the bug?(重新问题的详细步骤)

不知道如何复现。

1. 很久之前临时用过的一个连接（可能是 vnc 连接，记不清了），现在突然出现在了一个 ssh-config 的书签分类下（我并没有建过这个分类）。
![PixPin_2024-12-29_03-52-26](https://github.com/user-attachments/assets/be1974b0-be82-401c-9b9b-e669e167622f)

2. 而且只能在书签列表看到，可以点击编辑按钮进行编辑，但修改后无法保存成功。
![PixPin_2024-12-29_03-53-41](https://github.com/user-attachments/assets/bbd18ed2-430b-47a7-9898-a257f5b48a5c)

3. 修改为 default 分类（或其他任意分类）可以保存成功，但是会在那个分类下也出现 1 个相同的书签，都无法修改、删除。
![PixPin_2024-12-29_03-55-04](https://github.com/user-attachments/assets/c7ff0598-a591-4137-9c21-abd9588ae9a4)

4. 进入书签编辑列表，看不到这个书签，所以无法删除。
![PixPin_2024-12-29_03-55-37](https://github.com/user-attachments/assets/c9b6bb82-baaa-4679-bc0a-98d8e78575bb)

5. 已尝试过卸载重装，还是存在这个问题。

### What should have happened?(期望的结果)

可以正常展示并修改、删除这个书签。

**Comment by zxdong262** [comment]
ssh config 是从~/.ssh/config读取的，设置里可以关掉，在之后的版本会取消这个功能，改为导入~/.ssh/config

**Comment by leic4u** [comment]
好的，删除掉 `C:\Users\username\.ssh\config` 文件后，重启 electerm ，就算在设置中不隐藏 ssh-config 分类，也看不到这个书签了。

感谢开发者，期望这个功能的后续优化！
