### ISSUE TITLE
Ability to use with proxy

### ISSUE THREAD

**Issue by keshaipad** [electerm/electerm#426]
It will be awesome, if you can add here ability to use proxy in electerm (for ssh and sftp connections)
Thanks =)

**Comment by JSkalskiSBG** [comment]
It would be great to proxy thru SSH server to SSH.
I got a lots of servers to manage that are inside private network. Now I got to create SSH tunnel in console to connect to them from Filezilla/terminal.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/617

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/71c5ca64ddd2bdbce3c4740f938ec62285781e11
