### ISSUE TITLE
Link to not existing file blocks 'files manager' files listing

### ISSUE THREAD

**Issue by JSkalskiSBG** [electerm/electerm#481]
In my main directory (/home/jskalski/) I got link:

    jskalski@jskalski-pc ~ $ ls -lah | grep steampath
    lrwxrwxrwx  1 jskalski jskalski   33 maj 25 07:08 .steampath -> /home/jskalski/.steam/sdk32/steam

Target file **/home/jskalski/.steam/sdk32/steam** does not exist.

When I try to browse that directory with 'file manager' it only shows error:
```
Error: ENOENT: no such file or directory, stat '/home/jskalski//.steampath' 
at o.once.e (http://localhost:3000/js/essh.bundle.js?0.21.7-c7e4639644a2590959131a53b4e82138073129b1:1:86306) 
at WebSocket.n (http://localhost:3000/js/essh.bundle.js?0.21.7-c7e4639644a2590959131a53b4e82138073129b1:1:117969)
```
and does not update files listing window.

**Comment by zxdong262** [comment]
@JSkalskiSBG thank you.feedback really helps. and new version released with fixes https://github.com/electerm/electerm/releases/tag/v0.21.13
