### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by javehimself** [electerm/electerm#534]
Hey! @zxdong262 

I'm a graphic designer who wants to contribute to open source projects by designing logos.

For me it looked like your project is in need of a neat logo. So I decided to design one!

What do you think? Any suggestions and which colors you want to go with?

![showcase1](https://user-images.githubusercontent.com/39443012/42032559-4028a620-7ada-11e8-9da9-a79c1a3240f5.png)

**Comment by zxdong262** [comment]
hi, thank you, 
if I can get a better logo, I would love to replace the old ones.
l think the color is all ok, but the font is not stylish enough.
anyway, if you still want to contribute, you can email me zxdong@gmail.com, or fork https://github.com/electerm/electerm-resource

**Comment by javehimself** [comment]
No prob, feel free to make any change suggestions!

I've tried out a few fonts. Is one of them stylish enough? And should I also change the "e" logo?

![showcase2](https://user-images.githubusercontent.com/39443012/42049868-a1c969fa-7b07-11e8-98c6-0315f2e73ec9.png)

**Comment by zxdong262** [comment]
the core function of this app is working as a terminal, not "elect",  which is from core dependency: electron..
![qq 20180629131905](https://user-images.githubusercontent.com/1641949/42074513-41ebe344-7b9f-11e8-9947-7073a68995b1.png)
this font seems better, 
somehow I feel that I am wasting your time by being picky, unfortunately it is a subjective thing.
