### ISSUE TITLE
Something went wrong with the sftp of electerm-0.22.17 

### ISSUE THREAD

**Issue by gaoyanglion** [electerm/electerm#538]
when I enter a directory with symbolic link in it, elec is down and show errors below:

Something went wrong.reload

this.state[e].filter is not a function
TypeError: this.state[e].filter is not a function at t.default.L.getFileList.e [as getFileList] (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:6:327121) at t.default.renderSection (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:6:333113) at p.default.get.c.default.createElement.e.map (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:6:334749) at Array.map (<anonymous>) at t.default.renderSections (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:6:334733) at t.default.render (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:6:335345) at m (http://localhost:3000/_bc/react-dom/umd/react-dom.production.min.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:129:298) at beginWork (http://localhost:3000/_bc/react-dom/umd/react-dom.production.min.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:136:264) at e (http://localhost:3000/_bc/react-dom/umd/react-dom.production.min.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:168:321) at f (http://localhost:3000/_bc/react-dom/umd/react-dom.production.min.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:169:74)
No such file
Error: No such file
    at t.once.e (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:6:296744)
    at WebSocket.n (http://localhost:3000/js/essh.bundle.js?0.22.17-6e34a38b25ad7c1a758650ff42639e0883c8d006:1:119059)

then even I connect the connection, the errors above show again.
my os is Ubuntu 18.04 LTS

**Comment by zxdong262** [comment]
can you provide more detail?I can not recreate the bug.remote or local folder? `ll`

**Comment by gaoyanglion** [comment]
try to enter the remote folder which having a symbolic link to a folder. 
now I can't connect connection because of the error 
by the way, I login in the centos 7 via VPN

**Comment by zxdong262** [comment]
what kind of `symbolic link to a folder`?I tried to repeat it in a 18.04 virtual machine, did not happen.

**Comment by gaoyanglion** [comment]
now I just even can't connect any connection
maybe it is the fault of my environment

**Comment by gaoyanglion** [comment]
[electerm.log](https://github.com/electerm/electerm/files/2151422/electerm.log)
here is some log

**Comment by zxdong262** [comment]
mine
```
zxd@ubuntu:~$ ll .config/
total 104
drwx------ 20 zxd zxd 4096 Jun 29 22:50 ./
drwxr-xr-x 23 zxd zxd 4096 Jun 29 22:50 ../
drwx------  2 zxd zxd 4096 Jun 29 22:55 dconf/
drwx------  4 zxd zxd 4096 Jun 29 21:03 electerm/
-rw-rw-r--  1 zxd zxd  479 Jun 29 22:55 electerm-localstorage.json
-rw-rw-r--  1 zxd zxd   20 Jun 29 21:03 electerm-user-config.json
```

**Comment by zxdong262** [comment]
it crashed when run from cmd line

**Comment by gaoyanglion** [comment]
from deb and panel. I will try to install it in another machine on Monday and check it

**Comment by gaoyanglion** [comment]
check like this . login in the remote server, cd /opt  ,run ln -s /home/username test  ,create a symbolic link. then try to viste /opt with sftp .
I chagne a machine which installed the Ubuntu 18.04 LTS , it is the same error

**Comment by zxdong262** [comment]
@gaoyanglion thank you for your feedback and patience. a new release with bug fix on the way, will be released in half an hour.

**Comment by gaoyanglion** [comment]
@zxdong262 good job ! thank you very much ! the bug is fixed !
