### ISSUE TITLE
ssh terminal auto scroll may not work

### ISSUE THREAD

**Issue by gaoyanglion** [electerm/electerm#580]
如题，偶发垂直滚动条无法自动滚动到底部，以显示最新的内容。用yum命令更新系统时发现。

**Comment by gaoyanglion** [comment]
I open two tabs to  login in two centos server ,then run "yum update" to update the os.  when I switch at the two tabs, I found the auto scroll not working well.

**Comment by zxdong262** [comment]
Confirmed, I saw this happen.

**Comment by gaoyanglion** [comment]
good job !
