### ISSUE TITLE
bookmarks grouping

### ISSUE THREAD

**Issue by grubin1989** [electerm/electerm#590]
OS: Ubuntu 18.04
    Can bookmarks grouping? I think it is a great idea when i have so many bookmarks. I am looking forward to the new features. 
BTW, could you add a confirm dialog when clicking the bookmark's close button? because this is often mishandled. thanks so much.

**Comment by zxdong262** [comment]
- [ ] add new category
- [ ] edit category
- [ ] category drag&drag
- [ ] new bookmark tree select
