### ISSUE TITLE
when I press [supr] key, it changes to upper case or lower case

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#634]
when opening a document with the editor "vi" and you want to delete a character by pressing the [supr] key, the character changes from lowercase to uppercase. You should delete the character.

**Comment by saulperez2905** [comment]
Hello:
I'm sorry my keyboard is in Spanish.

In windows 10, I connect to a Linux server, inside the server I edit a file with the editor "vi".

When I try to delete a character by pressing the "delete" key (top right corner on a laptop). When pressing this key, the character in the document changed to uppercase if it is in minuscule and vice versa
![2018-08-01 18_58_19-000144](https://user-images.githubusercontent.com/28075454/43554948-0d1e746e-95bd-11e8-88bd-6e314c7007cb.jpg)

**Comment by zxdong262** [comment]
@saulperez2905 

https://stackoverflow.com/questions/3230722/delete-key-is-changing-letter-case-in-vim

hope this helps, it is vi's behavior, not electerm's

**Comment by saulperez2905** [comment]
Hi @zxdong262 
I am using Windows 10 and can not edit VIM. If you mean to edit VIM on each computer that I connect to using "electerm", it becomes too tedious to do so.

Why when do I connect using "Putty" if it works correctly?

**Comment by zxdong262** [comment]
@saulperez2905 You are right.it it a problem.I will try to find out why.

**Comment by saulperez2905** [comment]
Hi @zxdong262 

probably also influences the copying and pasting within "sqlplus" of Oracle Database Software.

1) When I paste a query in a single line it executes correctly:

select owner, object_type from dba_objects where owner = 'USR_FRM';

2) But when executed, line after line, it fails:

select owner,
object_type
from dba_objects
where owner = 'USR_FRM';

As I said before, this in putty, termius or other terminal works normally.

![2018-08-20 22_11_37-000148](https://user-images.githubusercontent.com/28075454/44378321-6d5b9b00-a4c6-11e8-8c20-7d243f2bd97c.jpg)

**Comment by zxdong262** [comment]
@saulperez2905 a new version released, with fix, your feedback really helps, thank you.
