### ISSUE TITLE
Enable scp -C compress option

### ISSUE THREAD

**Issue by satels** [electerm/electerm#682]
I'm interested for enable compressing when i copy big files

**Comment by zxdong262** [comment]
ssh2 docs says the default is `only use compression if that is only what the server supports`
> compress - mixed - Set to true to enable compression if server supports it, 'force' to force compression (disconnecting if server does not support it), or false to explicitly opt out of compression all of the time. Note: this setting is overridden when explicitly setting a compression algorithm in the algorithms configuration option. Default: (only use compression if that is only what the server supports)

refer to this one:
https://serverfault.com/questions/697363/why-is-scp-with-compression-slower-than-without

> Compression is desirable on modem lines and other slow connections, but will only slow down things on fast networks.

seems compression should not be used when transfer big files?

**Comment by zxdong262** [comment]
Close it for now, if you have question or suggestions, feel free to leave a comment.
