### ISSUE TITLE
Need a direct file edit option

### ISSUE THREAD

**Issue by simongomes** [electerm/electerm#761]
## Expected Behavior
Once I login to sftp there should be an option to edit file directly.

## Current Behavior
No option to edit file directly on server.

## Possible Solution
From the right click menu, add a option so I can chose any editor to edit the file directly.

## Steps to Reproduce
![On Right Click](https://i.imgur.com/BLc3zPi.png "On RIght Click")

1. Open Electerm
2. Login to a sftp server
3. Right click on any file

## Context (Environment)

My main requirment wa using ssh and file manager side by side and edit any file directly from server

Make an option so that I can edit a file from server directly. Do not want to download it.

## Detailed Description

Make an option so that I can edit a file from server directly. Do not want to download it.

**Comment by zxdong262** [comment]
Seems a interesting feature, I will try to achieve it.

**Comment by simongomes** [comment]
Is there any update about this buddy?

**Comment by zxdong262** [comment]
@simongomes Might do this next week, in milestone 0.26.

**Comment by zxdong262** [comment]
@simongomes Released new version: - fix #761 Double click to edit remote file function(only for small files)(#840)
