### ISSUE TITLE
paste SQL statements wrongly

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#769]
## electerm version:
0.24.20
## operating system(linux, macos, or windows?):
Windows
## Current Behavior

when opening the Electerm and then, from the PowerShell terminal that Electerm uses, the connection to the Database is made using the SQLPLUS application (in no time we connect to a linux, everything is done from Windows). Once connected to the database, SQL statements are pasted, "electerm" pastes them continuously as if it were a single line.

## Steps to Reproduce

1.open electerm
2.From the power shell I run: sqlplus sys/oracle@NAME_DB as sysdba

PS C:\Users\sperez\Documents\Electerm_sael\electerm-0.24.20-win-x64>
PS C:\Users\sperez\Documents\Electerm_sael\electerm-0.24.20-win-x64>sqlplus sys/oracle@NAME_DB as sysdba
Connected to:
Oracle Database 11g Release 11.2.0.4.0 - 64bit Production

SQL> 

4. I need to paste the following questions:
COLUMN COMP_NAME FORMAT a35 word_wrapped
COLUMN VERSION FORMAT a15 word_wrapped
COLUMN STATUS FORMAT a10 word_wrapped
SELECT COMP_NAME
        , VERSION
        , STATUS
FROM SYS.DBA_REGISTRY;

5. But when you paste the query, you paste it in a single line and obviously it is an error

SQL> COLUMN COMP_NAME FORMAT a35 word_wrappedCOLUMN VERSION FORMAT a15 word_wrappedCOLUMN STATUS FORMAT a10 word_wrappedSELECT   COMP_NAME       , VERSION       , STATUSFROM SYS.DBA_REGISTRY;
SP2-0735: unknown COLUMN option beginning "word_wrapp..."
SQL>

6. I attached an example of how it results from powershell in the windows programs
![2018-09-27 13_18_48-000171](https://user-images.githubusercontent.com/28075454/46166195-32cce700-c258-11e8-99d7-70a0b9f56ae7.jpg)

**Comment by zxdong262** [comment]
Thank you for the feedback. I will handle it tonight, around 12hour from now, I believe I know the source of the bug.

**Comment by saulperez2905** [comment]
Thanks for the help

**Comment by zxdong262** [comment]
Maybe tonight I can fix it.

**Comment by zxdong262** [comment]
New version released, let me how it works.@saulperez2905

**Comment by saulperez2905** [comment]
Hello
I just checked and the problem is still being presented, I send you a screen

 



 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: sábado, 29 de setiembre de 2018 08:17
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] paste SQL statements wrongly (#769)

 

New version released, let me how it works.@saulperez2905 <https://github.com/saulperez2905>

**Comment by zxdong262** [comment]
New version released, I believe it it fixed and,
 once again, your feedback helped me to find a import bug! Thank you!
.@saulperez2905
