### ISSUE TITLE
How to change font

### ISSUE THREAD

**Issue by corelon** [electerm/electerm#775]
Hello,

I saw from the closed issues that the code for changing fonts has been integrated, but there still is no UI way of doing so.
As I am very eager to change the terminal font, is there any way to do that using Dev Tools?

Thanks in advance.

**Comment by zxdong262** [comment]
Font family change: https://github.com/electerm/electerm/issues/695
Font size change: https://github.com/electerm/electerm/issues/717
All not done yet.
which one you want to change? I may add the feature first.

**Comment by corelon** [comment]
Hi. 
I am looking to change both, but my main concern is font family.
Is there any way to do that via the embedded Dev Tools as of now?

**Comment by zxdong262** [comment]
@corelon building, may release in 17 min.

**Comment by zxdong262** [comment]
Released @corelon

**Comment by corelon** [comment]
Thanks!
Just downloaded. The only issue I see is that I cannot find a way to change the font on the Powershell terminal. Only on the SSH sessions. 
Am I missing something?

**Comment by zxdong262** [comment]
@corelon released a new version with global default font settings which will control all local terminal font setting.

**Comment by corelon** [comment]
Excellent! Thanks a million
