### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#798]
## Electerm version:
2.4.33
## Operating system(linux, macos, or windows?):
windows
## Expected Behavior

![](https://gist.githubusercontent.com/agnoster/3712874/raw/characters.png)
## Current Behavior

![](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fw63kuxz1tj30af00w3yb.jpg)
## Possible Solution

try in server and client install [powerline-fonts](https://github.com/Lokaltog/powerline-fonts) and change electerm font to `Go Mono for Powerline`,but not can solv. 
## Steps to Reproduce

1.install oh-my-fish
2.install agnoster theme

## Context (Environment)

fish, version 2.2.0
electerm font setting `Go Mono for Powerline, courier-new, courier, monospace`

```
/root/.local/share/fonts/
├── DejaVu Sans Mono Bold for Powerline.ttf
├── DejaVu Sans Mono Bold Oblique for Powerline.ttf
├── DejaVu Sans Mono for Powerline.ttf
├── DejaVu Sans Mono Oblique for Powerline.ttf
├── devicons.ttf
├── DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf
├── fonts.dir
├── fonts.scale
├── mtextra.ttf
├── symbol.ttf
├── Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
├── WEBDINGS.TTF
├── wingding.ttf
├── WINGDNG2.ttf
└── WINGDNG3.ttf

/root/.config/fontconfig/conf.d
└── 10-powerline-symbols.conf
```

## Detailed Description

This is a font issue, I tried to install the font on the server, but it didn't work. If this is a problem with my system installing fonts, please let me know.
I run command
```
apt-get install fonts-powerline
git clone https://github.com/powerline/fonts
cd fonts && ./install.sh
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mkdir ~/.config/fontconfig/conf.d
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
fc-cache -vf ~/.local/share/fonts/

```

**Comment by zxdong262** [comment]
Hi, @blue-bird1 
Font should be install in electerm's current OS(in your case, your windows os)

**Comment by blue-bird1** [comment]
I in windows os Downloaded font,but I I found that the font seems to only work in my powershell

linux
![](http://wx3.sinaimg.cn/mw690/0060lm7Tly1fw6k35exfvj307g01ca9u.jpg)

windows
![](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fw6k4a91p8j306l00tgld.jpg)

**Comment by zxdong262** [comment]
What is the linux image about? @blue-bird1

**Comment by blue-bird1** [comment]
putty 
![](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fw6wbon1wpj306y015jr5.jpg)

**Comment by zxdong262** [comment]
try `print u'\ue0b0'.encode('utf8')`
