### ISSUE TITLE
Where can I donate?M?

### ISSUE THREAD

**Issue by egorsmorgunov** [electerm/electerm#811]
This application is what I was looking for!
Some connections lack FTP.

**Comment by zxdong262** [comment]
@egorsmorgunov Thank you! 

Glad you like it, but currently no donation method, it is not a graduated product, still need more work to do. Use it then, tell me what you think, I would like to make it better and better.

**Comment by zxdong262** [comment]
@egorsmorgunov 
Are you using window 7/10? did this bug happened in your OS, https://github.com/electerm/electerm/issues/814

**Comment by egorsmorgunov** [comment]
elementaryos

**Comment by zxdong262** [comment]
Released a new version with some bug fix
