### ISSUE TITLE
Bookmark selector does not clear selection after selecting bookmark.

### ISSUE THREAD

**Issue by x0rsw1tch** [electerm/electerm#813]
## Expected Behavior

After selecting a bookmark from the list at the top, the selection clears and allows for the same selection again, if desired.

## Current Behavior

Selection from the drop-down is retained and am not able to select the same bookmark again, even if the original selection's resulting tab is no longer active. The only way around this is to select something else from the drop-down, then you're able to select the host you want.

## Possible Solution

Clear bookmark drop-down selected host after an option has been clicked, so that it may be selected again.

## Steps to Reproduce

1. Create a bookmark for a host in the settings dialog
2. Close settings dialog
3. In the main window, select newly created host from the bookmarks drop-down
4. Open bookmarks drop-down again and attempt to select the same host. Not able to select that option.

## Context (Environment)

If I open an SSH session through the bookmarks drop-down, and that session disconnects or if I want to open another tab of the same host, I am unable to do so. Even if I logout of that session, close the tab, and want to re-open the session, this is not possible unless another host is selected (not wanted), then re-select my desired host. It's not uncommon to want the ability to have the same host opened in full view in two tabs as well. 

## Detailed Description

Clearing the bookmark drop-down selection after clicking an item would solve this problem.

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/8f360f7b85bfb7f72983bac15e18dfa429f3a3e0
