### ISSUE TITLE
SFTP not showing remote host

### ISSUE THREAD

**Issue by x0rsw1tch** [electerm/electerm#814]
## Expected Behavior

When an SSH session is created, I can see the directory and file listing in the right column.

## Current Behavior

When selecting the SFTP tab, nothing is displayed in the right column and an error is shown.

```
Error: No such file
    at t.once (http://localhost:3000/js/electerm.0.24.39-39e96d0d2c834eb231dd160d11a5db3cabe5370a.js:21:792032)
    at WebSocket.o (http://localhost:3000/js/electerm.0.24.39-39e96d0d2c834eb231dd160d11a5db3cabe5370a.js:21:757160)
```

## Steps to Reproduce

1. Create an SSH session using a bookmark, SSH session is displayed as usual
2. An error message is display once the session is open
3. Clicking on the SFTP tab shows an empty right column

![image](https://user-images.githubusercontent.com/9543257/47170332-b7e57200-d2d3-11e8-886a-f197403b9740.png)

![image](https://user-images.githubusercontent.com/9543257/47170453-0c88ed00-d2d4-11e8-854e-0355a56cf8f2.png)

## Context (Environment)

On multiple computers connecting to different hosts, the SFTP functionality has not worked

**Comment by zxdong262** [comment]
@x0rsw1tch Thank you for the feedbacks!
What is your ssh host's OS, linux or windows?

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/791

**Comment by x0rsw1tch** [comment]
Two SSH hosts were CentOS 7.2, and one was Linux Mint 17.3. I did see #791, but the error message is different, so safe bet to report

**Comment by zxdong262** [comment]
Might be some situation I never know, can you provide `ls -al` output for server home folder, or the root folder for sftp is special?

**Comment by x0rsw1tch** [comment]
Nothing special from what I can see. SFTP root should just be ~. I should mention SFTP does work with other clients (FileZilla, MobaXTerm) on the same hosts.

![image](https://user-images.githubusercontent.com/9543257/47202240-9ffd0500-d34a-11e8-9432-4ff381bbd84d.png)

**Comment by zxdong262** [comment]
What happens if you click the eye icon(show hidden files)?

**Comment by x0rsw1tch** [comment]
Hmm, that worked, but only on one host, and wasn't able to navigate to / on any of the hosts. The hosts where it doesn't work at all have Symlinks in them. Maybe that's the issue?

**Comment by zxdong262** [comment]
@x0rsw1tch I thought it was about symlinks too, so I tested by creating some symbolic link(`ln -s xxx yyy`), no problem in my ubuntu server, I wonder there might be some symlink situation I do not know, can you provide some info about that?

**Comment by x0rsw1tch** [comment]
@zxdong262 

Not much going on. Looks like the symlinks are just pointing to Tomcat directories, as a shortcut. Originally, they were owned by root:root, so I changed the owner and group to match the rest of the files. Unfortunately, it still resulted in the same error. Here is the directory listing on this host, if it helps.

![image](https://user-images.githubusercontent.com/9543257/47251604-51f80800-d403-11e8-8cab-29bb5716031f.png)

**Comment by zxdong262** [comment]
I know it now, must be windows related, in linux or mac it works fine
