### ISSUE TITLE
Dialog/Modal UI Color Scheme to match main UI

### ISSUE THREAD

**Issue by x0rsw1tch** [electerm/electerm#815]
## Suggestions?

I would like to see a "Dark UI" or night mode option for the dialog windows, modals, and notification pop-ups. Something along the lines of Postman's dark mode, another Electron based app.

Example Screenshot:

![image](https://user-images.githubusercontent.com/9543257/47170765-db5cec80-d2d4-11e8-8a37-9f333c39e454.png)

Cheers! ^_^

**Comment by zxdong262** [comment]
@x0rsw1tch All dark them for all UI now, you may try the leastest release.
