### ISSUE TITLE
split window not can close

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#828]
## Electerm version:
latest

## Operating system(linux, macos, or windows?):
windows

## Expected Behavior

can close split window

## Current Behavior

Can't find a way to close

## Steps to Reproduce

1.ssh
2.ctrl+/

## Suggestions?
In code have `delSplit` function,but seem not use.

**Comment by zxdong262** [comment]
@blue-bird1 There is a trash can icon at right-top corner of the terminals, click that to delete current ssh split, the icon UI not google enough, I would improve this, thank you.
