### ISSUE TITLE
add offline event check

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#832]
## Electerm version:
latest
## Operating system(linux, macos, or windows?):
windows
## Expected Behavior

offline  check
## Current Behavior

Network offline, terminal will be unresponsive
## Possible Solution

https://electronjs.org/docs/tutorial/online-offline-events
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
@blue-bird1 Thank you for the feedback!
