### ISSUE TITLE
Want to use electerm

### ISSUE THREAD

**Issue by prashantjeetsingh** [electerm/electerm#833]
Hi,

Can you please help me in using electerm with my electron app.

I want to add electerm with my electron app

**Comment by zxdong262** [comment]
? Do not understand your question.

**Comment by prashantjeetsingh** [comment]
I am trying to build an electron that will also have an SSH / SFTP Client. Is there anyway I can use electerm within my application in order to provide user an interactive shell in a Div ?

**Comment by zxdong262** [comment]
Since electerm is a electron app too, you could fork it, modify the code as you like, but it is not a module could be imported.

**Comment by prashantjeetsingh** [comment]
Thanks for the info
