### ISSUE TITLE
No double auth

### ISSUE THREAD

**Issue by Sakubz** [electerm/electerm#836]
## Current Behavior

When i log to SSH, this message appear : 

Error: All configured authentication methods failed
    at t.once (http://localhost:3075/js/electerm.0.25.0-b6000b167a482ae0d8e2e3ba44fa8199087bbd10.js:9:795930)
    at WebSocket.o (http://localhost:3075/js/electerm.0.25.0-b6000b167a482ae0d8e2e3ba44fa8199087bbd10.js:9:760802)

## Possible Solution
Add double auth ?

## Steps to Reproduce

1. Create ssh server 
2. add key auth + password auth into serv
3. try to connect with key priv ssh and prompt for password ( masked if possible ) and go connect

## Context (Environment)
i juste want connect to my ssh server

## Suggestions?

Can you add a "explorer" bloc at left ? For search any bookmarked ssh, like mremoteNG :) Thanks for your job !!!

**Comment by zxdong262** [comment]
I tested loging with private key, it works, did you put your pubkey in server's `.ssh/authorized_keys`?

**Comment by Sakubz** [comment]
Yeah, but my server (at work) need a ssh key (it's ok) but after, the server need a password for login, not the password of the key ^^
so when i try to connect, with option ssh key, it's ok but the prompt password is not effect ans i can't connect
Have a good day :)

(i'm french, i wish you can read my english well ^^')

30 octobre 2018 14:11 "ZHAO Xudong" <notifications@github.com (mailto:notifications@github.com?to=%22ZHAO%20Xudong%22%20<notifications@github.com>)> a écrit:
	I tested loging with private key, it works, did you put your pubkey in server's .ssh/authorized_keys?

**Comment by zxdong262** [comment]
@Sakubz Do you know how to set a server like this? I would like to solve this problem, just I do not have a server like this yet.

**Comment by Sakubz** [comment]
Yes sure :)
You need a server on linux (mine is Debian 9), make this to connect with your RSA key et add a password auth.
In your sshd_config add this :

	AuthenticationMethods publickey,password 

	AuthenticationMethods publickey,password 

	AuthenticationMethods publickey,password 

	AuthenticationMethods publickey,password 
if is not clear, make your server ok with RSA key login and at the end of your sshd_conf add :
	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes 

	AuthenticationMethods publickey,password RSAAuthentication yes PubkeyAuthentication yes PasswordAuthentication yes AuthenticationMethods publickey,password
PubkeyAuthentication yes
PasswordAuthentication yes

With that, you need your RSA key to connect and the server will prompt for your password

	AuthenticationMethods publickey,password 
31 octobre 2018 12:38 "ZHAO Xudong" <notifications@github.com (mailto:notifications@github.com?to=%22ZHAO%20Xudong%22%20<notifications@github.com>)> a écrit:
	@Sakubz (https://github.com/Sakubz) Do you know how to set a server like this? I would like to solve this problem, just I do not have a server like this yet.

**Comment by zxdong262** [comment]
@Sakubz Now support auth with publickey + password now

**Comment by Sakubz** [comment]
Thanks !! :o

**Comment by zxdong262** [comment]
@Sakubz How is it going?
