### ISSUE TITLE
[enhancement] theme background image 

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#839]

**Comment by zxdong262** [comment]
Since the terminal is rendered in canvas element, without xterm.js support, it will not be possible.

**Comment by zxdong262** [comment]
@blue-bird1 Now it support custom terminal background image

**Comment by emoxam** [comment]
How to change it? or how to remove default one ?

**Comment by zxdong262** [comment]
> How to change it? or how to remove default one ?

https://www.bilibili.com/video/BV18gJVzQEcg/?share_source=copy_web&vd_source=4959cdb7c0b3452cf4f00e2cc9b748ca
