### ISSUE TITLE
open connection to another host when splitting a window

### ISSUE THREAD

**Issue by zhangfuwen** [electerm/electerm#842]
I've been finding a XShell like terminal app that works under linux env for a long time, and this is just what I wanted. Thank you for building this app.

## Suggestions
when opening a split view on a SSH window, another SSH session to the same host is set up.  I think this should be called a "duplicate split". what I usually want to do when splitting the window is to open a different, or many other different hosts for a split view. so my suggestion is to add an option to connect to a different host for split view.

**Comment by zxdong262** [comment]
@zhangfuwen Thank you for the feedback, it is useful, I will think about how to do it properly.

**Comment by zxdong262** [comment]
Latest release now support layout: 1x2, 1x3, 2x2 views
