### ISSUE TITLE
set localshell

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#885]
## Electerm version:
0.25.12
## Operating system(linux, macos, or windows?):
windows
## Expected Behavior

customize localshell to gitbash
## Current Behavior

[Hardcoded to powershell.exe](https://github.com/electerm/electerm/blob/aa6c573bdee6e1784637d803db840308dbadcb36/app/lib/terminal.js#L28).(It seems that if there is no powershell it will be a disaster, Lead to some unknown bugs)
## Steps to Reproduce

1.in windows open app, get a powershell
2.
3.
4.

**Comment by zxdong262** [comment]
I remembered I used cmd.exe at first, but for some reason(I do not remember the reason now), it do not work, so I changed to `powershell.exe`, I checked vscode, it use `pwershell.exe` as default too, I guess for the same reason.

**Comment by zxdong262** [comment]
I may release a new version with custom exec support in a few days. #1117

**Comment by zxdong262** [comment]
Hi, @blue-bird1 Released a new version with custom exec support in settings.

**Comment by zxdong262** [comment]
#1117
