### ISSUE TITLE
home dir error 

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#903]
## Electerm version:
0.25.21
## Operating system(linux, macos, or windows?):
windows
## Expected Behavior

localshell in home dir . 
## Current Behavior

localshell in download electerm  dir 
## Possible Solution

```
diff --git a/app/lib/terminal.js b/app/lib/terminal.js
index 4e4d25b..5360c2e 100644
--- a/app/lib/terminal.js
+++ b/app/lib/terminal.js
@@ -27,11 +27,12 @@ class Terminal {
     let {platform} = process
     let exe = platform.startsWith('win') ? 'powershell.exe' : 'bash'
     let argv = platform.startsWith('darwin') ? ['--login'] : []
+    let home = platform.startsWith('win') ? process.env.USERPROFILE : process.env.HOME
     this.term = pty.spawn(exe, argv, {
       name: 'xterm-color',
       cols: cols || 80,
       rows: rows || 24,
-      cwd: process.env.HOME,
+      cwd: home,
       env: process.env
     })
     return Promise.resolve()
```
## Steps to Reproduce

1.
2.
3.
4.

## Suggestions?

windows not have process.env.HOME, but have process.env.USERPROFILE :

**Comment by zxdong262** [comment]
@blue-bird1 Thanks, I will try.

**Comment by blue-bird1** [comment]
@zxdong262 How should  I only build a Windows package in Linux

**Comment by zxdong262** [comment]
@blue-bird1 Possible by using wine, or some pre-built docker image, I did build some simpler windows app in linux, but electerm is more complicated, too much trouble I guess, so I use appveyor to do the build.
