### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by tanzhihang** [electerm/electerm#949]
## Electerm version:
0.25.35
## Operating system(linux, macos, or windows?):
'npm run release' on Mac os
run electerm.exe on Windows 10 x64
## Expected Behavior

![image](https://user-images.githubusercontent.com/6611880/48754822-066c9e80-ecce-11e8-8b13-e7f514028312.png)

## Steps to Reproduce

1. git clone https://github.com/electerm/electerm.git
2. npm install
3. modify package.json: "output": "./node_modules/.bin/electron-builder --win --x64"
4. npm run release
5. copy the 'electerm-0.25.35-win-x64.tar.gz' package to Windows 10 and tar it 
6. run electerm.exe

**Comment by zxdong262** [comment]
Would ver 0.33 from release work?

**Comment by tanzhihang** [comment]
v0.25.33 doesn't work

**Comment by tanzhihang** [comment]
It's missing a node-pty module from \resources\app.asar.unpacked\node_modules
![image](https://user-images.githubusercontent.com/6611880/48760117-083f5d80-ece0-11e8-8b3d-0e66cd232dac.png)

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/releases/download/v0.25.33/electerm-0.25.33-win-x64.tar.gz So this one do not work too?

**Comment by tanzhihang** [comment]
This package is works

> https://github.com/electerm/electerm/releases/download/v0.25.33/electerm-0.25.33-win-x64.tar.gz So this one do not work too?
This package is works

**Comment by tanzhihang** [comment]
I found the package is missing files of I building, but just happening on Windows

**Comment by zxdong262** [comment]
I do not know how to build it in mac os, I build the windows release with **appveyor**, building it in windows is recommended way.

**Comment by tanzhihang** [comment]
build for Windows must be dependent on vc++ build tools. so I build it on Windows and it works
