### ISSUE TITLE
electerm-0.25.37 freezes without the possibility to reload the Connection

### ISSUE THREAD

**Issue by NoirPi** [electerm/electerm#955]
## Electerm version:
electerm-0.25.37
## Operating system(linux, macos, or windows?):
Windows 10 Professional
## Expected Behavior

The Electerm Console should not freeze and then be unable to reconnect
## Current Behavior

The Opposite of what really should happen
## Steps to Reproduce

1. I've connected to Console and tried to upload a file
2. The Console freezed and i tried to reload the connection
3. After that doesnt work for more then 2 Minutes i closed Electerm
4. https://i.imgur.com/6Nyp2hD.png

**Comment by zxdong262** [comment]
So upload with sftp? How big the file is?

**Comment by NoirPi** [comment]
![explorer_boggmrhdoq](https://user-images.githubusercontent.com/34034616/49012652-54741d00-f17a-11e8-9469-23b0fbcc63e6.png)

its a very very very small File
So its definitely not the Problem with the File

**Comment by NoirPi** [comment]
Sadly i have no Idea but it happens all the time and makes electerm unusable for me =/
https://i.imgur.com/SmxBrvJ.png Im not able to upload any file to my server with electerm

**Comment by zxdong262** [comment]
@NoirPi is your server windows server?

**Comment by NoirPi** [comment]
Uhm i have debian 9.6 on my Server.
SSH-key
with the
Subsystem sftp  /usr/lib/openssh/sftp-server
if you need more informations you need to tell me what you need

**Comment by zxdong262** [comment]
@NoirPi Have no clue for now, do you have any other windows 7/10 PC or virtual machine that you can try electerm? To see if electerm can work in different env.

**Comment by NoirPi** [comment]
At least today i had the Chance to test it on my Laptop with Windows 10
Same result.

I drag - Drop a File (no matter what file) into the SFTP Tab and the Connection times out instantly
after that i need to restart electerm to reconnect.

When exiting electerm after it freezes, i get following Error:
![errorelecterm](https://user-images.githubusercontent.com/34034616/50335935-27aeed80-050d-11e9-9bc6-969adb3cb2fc.png)

**Comment by zxdong262** [comment]
Hi @NoirPi 

It has been a while, can you try the latest version, to see if this happens.

**Comment by zxdong262** [comment]
Close it for now, has been a while, feel free to reopen if you still stuck in this situation.
