### ISSUE TITLE
Ask for passphrase at connection

### ISSUE THREAD

**Issue by JimboJoe** [electerm/electerm#959]
## Expected Behavior

I would like to be able to only type passphrase for a privateKey SSH access at connection, so that the passphrase doesn't get stored on disk. I'm OK with typing the passphrase every time so that my SSH access stays secured if my laptop get stolen/hacked.

## Current Behavior

I tried to leave the passphrase field blank, in the hope that it would be asked at connection, but the connection just failed.

## Possible Solution

As said before, ask for passphrase at connection if passphrase field left blank.

## Steps to Reproduce

Stated before.

## Context (Environment)

Mean to prevent storing a privateKey passphrase.

## Detailed Description

See above.

## Suggestions?

See above as well :wink:

**Comment by zxdong262** [comment]
@JimboJoe  I am working on this feature, hope I can support this soon. Similar to https://github.com/electerm/electerm/issues/836

**Comment by JimboJoe** [comment]
Thanks for your quick response!
It's "similar" yet different from #836: #836 is about providing a privateKey AND a user password, my use case is just about providing a privateKey, but not storing the passphrase and asking for it at every connection. I'm sure you had understood, I'm just rephrasing to avoid any misunderstood :smile:

**Comment by zxdong262** [comment]
@JimboJoe I did think it is the same, now I undertand it is not. Thanks for the explaining it.

**Comment by zxdong262** [comment]
@JimboJoe New version released, check it out~

**Comment by JimboJoe** [comment]
Works fine for me!
As a bonus, could you maybe not show key pressed for a password by default...? :wink: 
Thanks a lot!

**Comment by zxdong262** [comment]
@JimboJoe Ah, right, it is a password! Thank you for the tip!

**Comment by zxdong262** [comment]
Hi, @JimboJoe, Please check you bookmark item if the passphrase is there, only when you check the save password checkbox, the passphrase or password will be saved into bookmark item. If it is stored in bookmark item, you could delete it, then try it again, let me know how it works.

**Comment by JimboJoe** [comment]
No, I checked prior to commenting that the password wasn't there any more (I removed it after connection).

**Comment by zxdong262** [comment]
Removed it after connection? Should remove it before connection.
