### ISSUE TITLE
[Feature Request] Bundle/Embed an X11 server

### ISSUE THREAD

**Issue by krishnakumarg1984** [electerm/electerm#966]
## Background
I am a PhD student working on computational modelling. I have a very powerful `linux` workstation at my desk. However, I sometimes work from the university library in a different campus wherein only windows 10 machines without any admin rights are only provided. On a network mounted drive (labelled 'home drive' by our ICT department), I currently have a portable copy of `mobaxterm`, a single executable which bundles in all the standard unix `coreutils` in addition to bundling an SSH client and an `X11 server` that is set to run automatically on starting the application (along with a few other nifty utilities that are easily available to install from the `cygwin` repos). 

This is useful in the following situation. In meetings with my PhD advisor in their office, they prefer to have discussions with slides/software displayed on a large screen permanently hooked to their computer.  To show them something from my computer that involves a graphical application, I simply need to download a __single__ binary executable and SSH into my workstation to fire up the graphical application.  This works quite neatly!  

I am satisfied with this workflow, except for a couple of issues:
* `mobaxterm` is not open source and there is no public interface to see the roadmap or features planned.
* They ship really old vulnerable software, eg. the default `bash` shell is around 4.1 which is prior to the `shellshock` bug. Most other `coreutils` are also old.

## Feature Request - Bundling of a simple X11 server
I love `electerm`.  Although it is not a __single__ binary, at least it is portable enough with a couple of  clicks to extract the archive and we are good to go. Can you bundle/embed a simple `X11` interface to this?  Perhaps something like [`vcxsrv` ](https://sourceforge.net/projects/vcxsrv/files/) which is open source and quite actively developed.

**Comment by zxdong262** [comment]
Hi, @krishnakumarg1984 ,
Thanks for the feedback, I will dig into this.

**Comment by krishnakumarg1984** [comment]
Mobaxterm is indeed an amazing software brimming with features. In a __single portable__ binary, they have packaged

1. local terminal 
2. bash shell 
3. coreutils 
4. gazillion remote connection protocols (SSH, RDP, VNC, ICA, Mosh and a couple of others)
5. seamless X-server that auto-starts
6. graphical SFTP browser that follows the terminals `cd` commands on a remote server, and 
7. package manager with access to the entire cygwin repo ecosystem

However, the only drawbacks are 

1. the shipped busybox utils are quite outdated
2. it is a 32-bit binary executable (also 32-bit for `cygwin` packages)
3. terminal doesn't support 24-bit truecolor and vim cursor modes
3. not open-source

**Comment by krishnakumar-gopalakrishnan** [comment]
@zxdong262  Thanks a lot. So, this is done?

**Comment by zxdong262** [comment]
@krishnakumarg1984 Yes, I believe so, will release in half an hour maybe.

**Comment by krishnakumar-gopalakrishnan** [comment]
@zxdong262  Great. thanks a lot for this amazing level of support.

**Comment by zxdong262** [comment]
@krishnakumarg1984 https://github.com/electerm/electerm/releases/download/untagged-c1455015ceb991b66314/electerm-0.25.60-win-x64.tar.gz

Windows build done, you may try this, releases for other platform are still building.

**Comment by zxdong262** [comment]
May requires run Xming or MobaXterm or other xserver running first.

**Comment by zxdong262** [comment]
@krishnakumarg1984 Your feedback pushed me to get this done, thank you.

**Comment by zxdong262** [comment]
@krishnakumarg1984 Released

**Comment by saulperez2905** [comment]
This is amazing, X11, very good !!!!

**Comment by saulperez2905** [comment]
X11, for which version will be available?

**Comment by zxdong262** [comment]
@saulperez2905 0.25.60
