### ISSUE TITLE
option "Select all" does not work

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#976]
## Electerm version:
0.25.43
## Operating system(linux, macos, or windows?):
Windows
## Expected Behavior

Select all content stored in the terminal
## Current Behavior

no row is selected
## Steps to Reproduce

1.
2.
3.
4.

**Comment by saulperez2905** [comment]
Steps to Reproduce
1.Go to the symbol ET
2.go to edit option
3.execute "select all"

**Comment by zxdong262** [comment]
@saulperez2905 Thank you for the feedback, the select all in the menu should be removed I guess, the select all in context menu works.

**Comment by saulperez2905** [comment]
Hello, this option is very useful, other tools such as putty, mobaxterm, etc, have it or have the option to export a log.
