### ISSUE TITLE
npm run app command is not working

### ISSUE THREAD

**Issue by cagdassalur** [electerm/electerm#992]
## Electerm version:
0.25.50
## Operating system(linux, macos, or windows7/8/10?):
Windows 10
## Expected Behavior
App should run as instructed in the Dev section of the readme.md file

##  Current Behavior
Getting this error:
`'..' is not recognized as an internal or external command,
operable program or batch file.`

## Possible Solution
I'm guessing it's a windows related bug. But i have no idea what is the problem.

## Steps to Reproduce
1. >git clone git@github.com:electerm/electerm.git
2. >cd electerm
3. >npm i
4. >npm start
5. >npm run app 

Last command is executed on a seperate terminal session.

## Context (Environment)
I'm trying to build the project locally.

**Comment by zxdong262** [comment]
@cagdassalur Fixed, please update and try it  now.
